### ISSUE TITLE
Extra space on right of dock when nothing running

### ISSUE THREAD

**Issue by MatthewScholefield** [solus-project/budgie-desktop#1031]
[Low Priority]

Solus Latest
Budgie latest git (254d284cf6857e5ab3fed37cbaea4d8e09d9daad)

It looks like the dock is off centered when no applications are running because of the spacer inside the Icon Task List to separate applications and launchers.
![offcentered](https://user-images.githubusercontent.com/5875019/28194860-96a3f07c-680c-11e7-89e1-ab2c484fa2cd.png)

**Comment by JoshStrobl** [comment]
This no longer appears to be an issue, so I'm going to cough it up to either being a theming issue from then.
