### ISSUE TITLE
Tray Applet Padding Setting

### ISSUE THREAD

**Issue by GreyAsteroid** [solus-project/budgie-desktop#1037]
**Operating System**: N/A
**Budgie version**: 10.3.1-383-g254d284

Consider adding a setting to adjust the System Tray applet padding between icons. There doesn't currently seem to be a way to do this while the padding of all other applets can be adjusted via theme or through the use of spacers.

**Comment by orschiro** [comment]
What do you need the padding setting for? Do you think the default system tray applet lacks padding?

**Comment by Spriithy** [comment]
Hey, just a little bump for this. I'm using Budgie on my HiDpi screen and I find pretty sad that the system tray doesn't showcase more options, most notably padding between icons (on high resolution screens, it looks very stacked).

**Comment by JoshStrobl** [comment]
Resolved as of #1998 :tada:

Thanks @serebit
