### ISSUE TITLE
Budgie and Gnome window button entanglement in Arch

### ISSUE THREAD

**Issue by coxackie** [solus-project/budgie-desktop#1040]
**Operating System**: Arch
**Budgie version**: Budgie 10.3.1

**The issue encountered**

This is related to budgie-desktop and gnome (and their entanglement) on Arch, where I have tried it. I am not sure whether it is related in any way to #261 (Missing features for compatibility with GNOME).

 I have installed both gnome and budgie-desktop (10.3.1, with all optional dependencies) on Arch (clean installation). I log in Budgie (I use gdm), and note that at Raven settings, when I choose left location of window buttons, either nothing happens, or a flicker on the headerbar of open windows and then nothing. In subsequent log-ins, and if I have "left" location enabled, some (but not all) windows have buttons on the left, and the others on the right.

 The real fun starts when I log back in to gnome session. There all kinds of screwed up stuff with window buttons happen. For example, windows with CSDs now open in gnome in windows that inherit budgie's style (all window buttons present, sometimes on the left), while other ones (ones with titlebars, without CSDs) follow the style that is determined from gnome-tweak-tool. (I only have "minimize" enabled, if at all). Even if I change gnome-tweak-tool's settings, windows that inherited the different button placement stubbornly stay as they are.

 Weirdly so, the issues are more pronounced in gnome on Xorg; in gnome wayland the situation is better, it seems to be more robust.

 I really like Budgie and would like to use it on Arch alongside gnome (although I am considering moving to Solus, especially after v11, but maybe not for the time being); these quirks are preventing me from using budgie on Arch seriously. I have tested this in both desktop and laptop, and in virtual machines. I always get the same (somewhat unpredictable) behaviour.

 Sorry for the long post - if you feel this should be mentioned somewhere else, I will be glad to do so.﻿
 ...

**Steps to reproduce the issue**

 I believe the description of the problem contains also steps to reproduce it.

**Comment by ikeydoherty** [comment]
Budgie's placement of window controls is determined by GNOME schema. It will update those GNOME settings based on the singular setting in Budgie's schema. This is known to work conflict free elsewhere, so therefore I have to assume that this comes from the non standard Arch additions to the Budgie package, via the "budgie-helper".

Can you verify whether these issues persist with a vanilla build?

**Comment by coxackie** [comment]
Thanks, Ikey,

 I built it "vanilla" (in a clean Arch installation, with GNOME installed), using dependencies from

https://aur.archlinux.org/packages/budgie-desktop-git/

 The dependency packages you provide are for Solus, so I had to fiddle a bit. I actually had to downgrade mason for successful build. I still could not get 100% success, because for some reason libmutter is not found as a dependency (!), but I do not know what to do with this. I am not sure whether this could be the reason for the issue.

 Anyway, the result in the end is the same: In GNOME X.org session, windows with CSD inherit the button style of Budgie (all three buttons), and it is impossible to change this. When only titlebars are there, the GNOME schema is used. As I mentioned, at least in the VM, GNOME (wayland) does not seem to have this issue, but in a desktop installation I also have issues with wayland.

**Comment by ikeydoherty** [comment]
What GNOME version are you using? Because honestly I can leak you a development ISO of Solus Budgie and you'll see they behave properly

**Comment by coxackie** [comment]
Using 3.24.

 I trust you that in Solus they behave properly, I just do not know what is happening in Arch.

 I will wait (I guess not too long, heh?) until the next release of budgie-desktop and check again afresh.

**Comment by ikeydoherty** [comment]
Yeah I mean there is every possibility this is some 10.3.1 jankiness that I can't see due to not using 10.3.1..

**Comment by coxackie** [comment]
Hi Ikey,

I am following up on this, since you have released Budgie 10.4 (which is awesome, btw).

 I can confirm the the issue that I have mentioned above still persists, even in clean installs. It even happens in Solus 3 Budgie (not on Arch that I mentioned), once I also install GNOME alongside Budgie per the instructions here:
https://solus-project.com/articles/software/desktop-environments/en/

 Let me repeat shorty the issue: windows with CSDs open in GNOME inheriting Budgie's style: all window buttons present; other windows with titlebars (without CSDs) follow the GNOME schema. The issue only happens at GNOME Xorg. The windows at GNOME wayland work as the should (I am only able to test the latter in Arch).

**Comment by enachesilviu** [comment]
Hi,

Just installed Arch using Antergos: Antergos Linux release 17.12 (ISO-Rolling), budgie-desktop v10.4-8-gff09a510

I encountered the same problem as **coxackie** , setting prefference to display window buttons on the left side had no effect in budgie, however it worked in gnome 3.26.2 (it appears to be X11 session). I found this workaround that fixed it for me:

https://wiki.archlinux.org/index.php/Budgie_Desktop  see "Changing button layout"

`gsettings set com.solus-project.budgie-wm button-layout 'close,minimize,maximize:appmenu'
gsettings set com.solus-project.budgie-helper.workarounds fix-button-layout 'close,minimize,maximize:menu'`

Another system I'm using runs Ubuntu 17.10, I believe I have budgie 10.4 and I cannot reproduce the problem on that install. It's either strictly related to Arch or perhaps a regression after some patch.

**Comment by vanitasvitae** [comment]
I'm having the exact same issue. Gnome seems to ignore its own settings after trying out budgie-desktop. As a result, CSD windows had their buttons on the left, while "normal" windows followed my configuration and placed their buttons on the right.

A "solution" for me was to reinstall budgie-desktop and set the button layout to left in budgies settings. That placed the buttons back on the left in Gnome too.

I installed budgie-desktop in Antergos from the official sources (using pacman).

**Comment by coxackie** [comment]
Just leaving this here (even though the issue is closed) for those who may encounter the same. After some digging around, I discovered that budgie sets
```org.gnome.settings-daemon.plugins.xsettings overrides {'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'menu:minimize,maximize,close'>}``` 
Simply execute `gsettings reset org.gnome.settings-daemon.plugins.xsettings overrides` and the problem is gone.

**Comment by fcole90** [comment]
I had the same problem with Ubuntu 20.04. I found the same setting that @coxackie suggested and deleting it made the window controls to be again according to the gnome settings. :heavy_check_mark: 

Thank you very much @coxackie, I was getting crazy to find what was not working. :pray:
