### ISSUE TITLE
Audio inputs/output sources problem in Raven

### ISSUE THREAD

**Issue by thumos333** [solus-project/budgie-desktop#1057]
Hi,
After the most recent updates, I still have the issue with choosing audio sources in Raven. As I power on my computer, it works fine; but if I plug out the USB dock, which is also my primary audio card, and plug it back, then all options are highlighted and I can't choose between them. Plugging the dock out and in again doesn't help. Please see the screenshot.

![screenshot from 2017-07-21 09-06-40](https://user-images.githubusercontent.com/29035180/28451241-cdf3104c-6df4-11e7-81c7-65ff4c800a78.png)

I am using Solus 2017.04.18.0 64-bit and Budgie 10.3.1-143. My laptop is Thinkpad T440s.

Thank you.

**Comment by lifeofdan** [comment]
I also have this issue. I have my audio interface plugged in via a hardware kvm switch. If I have things hooked up to the solus box on boot everything works/looks right. Whenever I switch between computers I have the issue as stated above.

**Comment by NickelGhost** [comment]
I also have this issue; after connecting my TV through HDMI on my video card, both HDMI ports (monitor and TV) get highlighted and no audio output switching works inside of Raven.

**Comment by hdak1945git** [comment]
I also have this issue, however in my case, using `pavucontrol` (PulseAudio Volume Control) to change one of my output profiles essentially "fixed" it.

I have two devices, one for the graphics card (owner of the "HDMI" option) and a run of the mill motherboard sound card ("Builtin-in Audio", owner of "Line Out" and "S/PDIF"). Only changing the motherboard sound card profile was warranted.

My "Builtin-in Audio" card profile was initially set to "Analog Stereo Duplex" (for unknown reasons). On this profile I could not change between "Line Out," "HDMI," and "S/PDIF" listed in the Budgie panel -- both "Line Out" and "HDMI" are checked. And while clicking on "S/PDIF" will uncheck "Line Out," it doesn't always mute "Line Out." (I don't have a S/PDIF device to test if it actually switches to it).

Changing the card profile to "Analog Stereo Output" and then, logging off and then back on again, restores the expected option button behavior. Now only one option is checked (which defaults to "Line Out"). Clicking on the other options now properly unchecks the previous selection and checks the desired option, effectively switching outputs.

---

A caveat: I've tried repeating the above changes, using `pulseaudio --kill` to simulate a log-off, but I only could get the problem to resurface intermittingly.

My system: Arch Linux, Budgie 10.4 (10.4+8+gff09a510-1)
Similar issues: #779, #909; #804 (though closed) has a helpful images describing it.

**Comment by chax** [comment]
The same here, but doesn't happen always

![screenshot from 2018-05-21 09 55 20](https://user-images.githubusercontent.com/632945/40296612-661e145c-5cdd-11e8-9ff7-659429f2c8d5.png)

**Comment by chax** [comment]
Logout/login resolves it and i can always change output in Sound settings

**Comment by JoshStrobl** [comment]
Should be resolved with a6a6ef353a29c71d01ab1a624c23ec9f594a2796

**Comment by chax** [comment]
This is actually still a bug in new budgie 10.5, which is currently in Solus unstable repo.

**Comment by JoshStrobl** [comment]
The only likely way for me to resolve this in a manner which is most reliable is to rebuild the entire devices view. That'll get implemented before the final release. Thanks for testing.

P.S. Budgie 10.5 isn't a thing yet, as was stated in the announcement about updated Solus Budgie to newest git.

**Comment by chax** [comment]
I know it isn't finished yet but i wanted to test it since this is the only bug that is bothering me in current version of Budgie. For me this happens whenever i plug in hdmi/dp monitor with sound output. Workaround is to reload budgie panel with `budgie-panel --replace &` or just go into sound settings and change output there but it becomes cumbersome to do this everytime.

**Comment by JoshStrobl** [comment]
Yea, that's obviously not ideal. It'll be taking another pass at this before the final release :+1:

**Comment by chax** [comment]
Yep, i see no more radio buttons, it works now, thanks Josh.

**Comment by JoshStrobl** [comment]
Yay! Thanks for testing.
