### ISSUE TITLE
Reboot/shutdown don't work on Arch OpenRC

### ISSUE THREAD

**Issue by angiest** [solus-project/budgie-desktop#1067]
**Operating System**: Arch OpenRC
**Budgie version**: i.e. Budgie 10.3.1

    budgie-desktop --version
budgie-desktop 10.3.1
Copyright © 2014-2017 Ikey Doherty, Solus Project

Under Arch OpenRC, the reboot and shutdown options (either from Raven or the user indicator applet) produce their respective dialogs, however, when clicking on the action, nothing happens.  My guess is that these functions assume systemd is installed, but I was unable to find anything after a quick perusal of the source.  I did find some references to logind, and maybe the privilege is coming through that.  Right now, the Arch OpenRC repositories do not have a functional elogind, so at present, I am unable to test with that.

 ...

Install Budgie under Arch OpenRC with all the relevant polkit and consolekit packages.  Attempt to shutdown or reboot.

 ...

**Comment by ikeydoherty** [comment]
Sounds more like a GNOME/Arch OpenRC integration issue to me tbqh. The shutdown dialog is linked explicitly to gnome-session.

**Comment by JoshStrobl** [comment]
Closing due to no actionable items on our part.
