### ISSUE TITLE
Suggestion: Suspend option for lid closure

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1081]
**Operating System**:Solus 2017.04.18.0
**Budgie version**: v10.3.1-404-g128a50a

**The issue encountered**

There's no option in the Power menu to disable suspend upon lid closure. For practical reasons, I often need to close the lid, but because suspend is so unstable, I'd prefer to disable it. Ideally, the default behavior would be hibernation, which would be safe against overheating and fire in transit, but would also avoid the perils of suspend.

**Steps to reproduce the issue**

N/A.

 ...

**Comment by JoshStrobl** [comment]
Close as WONTFIX since this is a deficiency in GNOME Control Center. You can install GNOME Tweak Tool and toggle off "Suspend when laptop lid is closed" via its Power section.
