### ISSUE TITLE
[Feature Request] Panel to handle multiple rows

### ISSUE THREAD

**Issue by yk11** [solus-project/budgie-desktop#110]
Request to have the Budgie panel be multi-row.

An interesting, but not crucial, enhancement would be option to specify if launcher/applet should take 1 spot or span all rows (as would be used by a menu as seen below).

![image](https://cloud.githubusercontent.com/assets/553283/5072350/e7d841fe-6e46-11e4-9ea4-16151c411c97.png)

**Comment by ikeydoherty** [comment]
One applet (icon tasklist) now supports rows, we'll add more in future :)
