### ISSUE TITLE
Budgie menu freezes when search buffer is overfilled.

### ISSUE THREAD

**Issue by blackomegax** [solus-project/budgie-desktop#1105]
**Operating System**: Solus 3

When filling the search bar in menu with excess data, menu hard freezes and requires reboot.

 ...

**Steps to reproduce the issue**
copy aaaaaaaaaaaaaaaaaaaaaaaa to clipboard
launch menu
hold ctrl-v down and let paste loop until freeze.

 ...

**Comment by blackomegax** [comment]
Preferred fix:
Buffer limit at ~256 char input should fix

**Comment by JoshStrobl** [comment]
Closing, unable to reproduce issue.
