### ISSUE TITLE
Budgie panel overextends beyond screen limits when populating the task list

### ISSUE THREAD

**Issue by Kabouik** [solus-project/budgie-desktop#1111]
**Operating System**: Solus 3 and Solus rolling
**Budgie version**: Budgie 10.4 and earlier

Budgie panels overextend beyond screen limits when what they have to show cannot fit in the limited space. I specifically remember discussing this with @ikeydoherty but I haven't seen an issue for this, so here's one. Sorry if I missed it.

![screenshot from 2017-08-20 16 41 15](https://user-images.githubusercontent.com/7107523/29495794-6db17270-85c6-11e7-92d9-f275a4ade329.png)

It's particularly obvious in my case because my two monitors are not aligned at the top, which makes the panel overextend in the middle of the second monitor.

This may not be too big a deal when using Icon list because icons don't fill the Budgie panel easily, but the limit is reached very quickly when using Task list as in the screenshot above.
 
 ...

**Steps to reproduce the issue**
1. Fill the Budgie panel with applications.
2. Profit.

It's visible also with a single monitor, the Budgie panel will just be truncated on the right.
 ...

**Comment by gnokix** [comment]
I have the same Issue, but as I use just one monitor I lost all the Icons beyond my screen, I'm sure it appears after an update

**Comment by LukasSommerTu** [comment]
I can confirm this issue. With a single-monitor setup the panel is truncated, with a dual-monitor setup it extends to the second screen. My budgie-desktop version is budgie-desktop v10.4-8-gff09a510.

**Comment by pMeridjen** [comment]
same thing here, except that my main desktop windows on the right screen (in dual). So the budgie panel disappear on the right

**Comment by eaydin** [comment]
Same problem here. It seems there isn't a workaround for this?

![image](https://user-images.githubusercontent.com/1251030/34164951-05f51148-e4ec-11e7-915d-171b377d3974.png)

**Comment by ProxiBlue** [comment]
Same issue. Using ubuntu budgie (latest)

![selection_017](https://user-images.githubusercontent.com/4994260/34282150-5fa9c706-e6fe-11e7-9834-063982cfd600.png)

**Comment by bdmthrfckr** [comment]
I have the same issue. I use Budgie at both home and work, and would really, really appreciate the task panel to behave appropriately :)

![screenshot from 2018-01-03 11-03-48](https://user-images.githubusercontent.com/35068618/34523401-1e174d6e-f076-11e7-9e15-1e423d5b1b97.png)

**Comment by maxmbed** [comment]
Same problem here. To many opened applications will shift right the end panel applets :(.

**Comment by zacharyPuthoff** [comment]
I'll add my vote to this as well --- single monitor setup, on top of Solus. Behaves the same as described previously. Any news on a potential fix?

**Comment by ThoranRion** [comment]
Same problem here, any news on fix this?

**Comment by bjo81** [comment]
Unfortunately this issue also exists with Solus 10.5.

**Comment by MazeW** [comment]
Please fix this

**Comment by JoshStrobl** [comment]
There are no plans on addressing this until Budgie 11. Locking comments to prevent further "me too's".
