### ISSUE TITLE
Budgie Panel Resize issue (Left or Right)

### ISSUE THREAD

**Issue by Danissl** [solus-project/budgie-desktop#1115]
Solus 3
Budgie Version: 10.4

I am encountering an issue when moving the panel to the left or right. It is not scaling down to match the icon size for left/right as it does on the top and bottom. Dock Mode changes nothing either. Attached are screenshots of top and bottom, left and right.  

Top: http://i.imgur.com/HSP0mfB.jpg
Right (Also has the strange issue of clipping between both monitors, and locking any windows that were maximized on the second screen): http://i.imgur.com/OA7ABtc.jpg
Bottom: http://i.imgur.com/8kNz160.jpg
Left: http://i.imgur.com/UDZvRzo.jpg

To recreate, simply move the panel to the left or right, and scale below 40 on the size.

**Comment by Coeur-Noir** [comment]
Icon size is not « progressive ».
It changes in stages, sort of.
Under X for size of panel, size icon is 1
Above X, then it's 2
And it's maybe related to theme, as I noticed panels are sometimes not drawn under a certain size value ( that size may be fixed by the them ? )
