### ISSUE TITLE
window menu

### ISSUE THREAD

**Issue by wapec** [solus-project/budgie-desktop#1127]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**
While window menu is opened (default key combination Alt+F2) and I switch to another language source, **window menu closes**.
I have to reopen it to start searching again.
 ...

**Steps to reproduce the issue**
Alt+F2(default) -> Switch input source (default Super+Space)
 ...

**Comment by ikeydoherty** [comment]
Can't really see why this is a bug. If you steal focus from the window, it disappears (it's meant to)

**Comment by gabrc52** [comment]
Because changing the input method or keyboard layout isn’t supposed to steal focus from the active window?

**Comment by wapec** [comment]
i use window menu alot to search for apps, settings etc.  + i have 4 different language inputs :)
it doesn't suppose to disappear. look, i open window menu, see that the language is not one i want to search with, i click Super+Space and window menu disappears. i have to envoke it again to search. why? i've just changed the language to type keyword to search though apps and files :) tried to do this on mac. they have it called Spotlight. it doesn't disappear while language input changing and it is convenient :)
