### ISSUE TITLE
Windows ignore upper Budgie bar in new Solus installation

### ISSUE THREAD

**Issue by der-eismann** [solus-project/budgie-desktop#1137]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**

I was using for about a year on my laptop and I loved it, last week I was doing a new install on a different laptop. I moved the bar to the top like I was used to but somehow all the windows choose to ignore the bar. That means that if you maximize a window the top of the window is hiding behind the Budgie bar.
![bildschirmfoto vom 2017-09-04 09-21-13](https://user-images.githubusercontent.com/10406217/30016925-71e0590a-9157-11e7-82e7-cfdeb837b6a9.png)

**Steps to reproduce the issue**

Fresh install of Solus 3, use Budgie settings to move bar from bottom to top.

**Comment by euventura** [comment]
i have same issue on ubuntu-budgie

**Comment by fossfreedom** [comment]
as per #1144 - looks to be because the manual panel sizing is smaller than the allocated displayed size.

not sure where in the code-base this calculation is applied though...

**Comment by manokara** [comment]
From what I could tell, this issue must be caused by the Budgie Menu applet. The widget makes the panel height increase but internally budgie-panel is still the original height you set, that's why the windows are placed under the bar. If you remove Budgie Menu and restart the panel, the problem is gone.

**Comment by kaaylim** [comment]
Same as #869. I see this problem starting when panel is less than 55px

**Comment by mactepp** [comment]
I had this issue with ubuntu budgie, but to me was the "Show Desktop" applet. After removing it from the panel, I was able to lower the visible panel height and not only the "theoretical" one and it stopped windows from going under the panel. I hope it is still relevant though.

**Comment by JessedeJonge** [comment]
This is STILL an issue. Anyone knows a fix for this?

**Comment by bsucker98** [comment]
same here, when I set the panel size to less than 39

**Comment by Danisodu** [comment]
@JessedeJonge like already said above, you need to set top bar size higher

**Comment by JoshStrobl** [comment]
Not sure why some people are arbitrarily closing valid open issues, regardless of whether or not they use the OS or desktop environment anymore...

**Comment by der-eismann** [comment]
Because it is over 2 years old and I wanted it out of my issues list. After so much time I thought you were unable or unwilling to fix this.

**Comment by JoshStrobl** [comment]
This isn't something we can fix until Budgie 11. It's still something I want tracked.
