### ISSUE TITLE
Volume Controls not working 

### ISSUE THREAD

**Issue by Binero** [solus-project/budgie-desktop#114]
When I am in GNOME, I can change my volume using my mouse. The mouse sends, through USB, a volume signal to the desktop. 

In Budgie however, nothing happens when I try to change my volume. 

I am not sure if this is a bug, a missing feature or simply something ill-configured on my system. Regardless I do not see a reason for it to work in GNOME but not in Budgie.

**Comment by ikeydoherty** [comment]
Now we have mediakeys etc working, please confirm if this works. Wasn't possible to get working before as it was specifically sending the volume button.

**Comment by Binero** [comment]
Still nothing... :s

**Comment by Justinzobel** [comment]
![screenshot from 2015-03-24 16-13-09](https://cloud.githubusercontent.com/assets/1370117/6796312/b7f49344-d240-11e4-89eb-9bedc8aea103.png)

Try re-mapping it here @Binero

**Comment by Binero** [comment]
The button itself works, when I reassign my volume up to going to the next workspace, it behaves as intended. When I assign it to actually raising the volume, it doesn't. 

Sorry for late answer!

**Comment by ikeydoherty** [comment]
Fixed in v10
