### ISSUE TITLE
Can't login to budgie using GDM

### ISSUE THREAD

**Issue by gabrc52** [solus-project/budgie-desktop#1149]
**Operating System**: Manjaro Linux
**Budgie version**: Budgie 10.4

**The issue encountered**

 I can't seem to be able to login to budgie using GDM, but I am able to with SDDM.

**Steps to reproduce the issue**

Use GDM as display manager
Login to Budgie
Back in login screen

**Comment by mantlecurve** [comment]
Having the same issue with Arch linux using lightdm/gdm.

**Comment by mantlecurve** [comment]
removed the outdated arch package and the installation from aur fixed the issue.

**Comment by Ste74** [comment]
Seem i have a duplicate here https://github.com/budgie-desktop/budgie-desktop/issues/1190
@mantlecurve you confirm the aur version work on gnome 3.26.1 or you are in stable repo ?

**Comment by mantlecurve** [comment]
Gnome: 3.26.1
Budgie: budgie-desktop v10.4-6-g9e2cc0f2 (via aur)

**Comment by mantlecurve** [comment]
I am using lightdm

**Comment by mantlecurve** [comment]
Tested with lightdm and gdm, both works
Lightdm 1.22.0

**Comment by Ste74** [comment]
Thank you , will push a new budgie version in our repo

**Comment by marek287** [comment]
For me it's not working. 
After upgrading this package, I can't login:
gnome-settings-daemon 3.24.3-2 -> 3.26.1-1

**Comment by mantlecurve** [comment]
Are you on arch?

**Comment by marek287** [comment]
Yes I am Arch Linux user.

**Comment by mantlecurve** [comment]
Update everything to latest. Syyu
-Rns budgie-desktop
yaourt -S budgie-desktop-git

This is what i have done and worked out perfect

**Comment by philmmanjaro** [comment]
The issue seems to be a regression introduced to **mutter 3.26.1** for Xorg-Sessions. If you turnoff animations via Tweaks, then crashing whilst maximised/tiled does not occur (or at least much harder to invoke a crash). It is recommended to do a **git-bisect** between v3.26.0 and v3.26.1 to find the commit introducing this regression.

**Comment by MohamedLEGH** [comment]
I have the same issue (I am also on ArchLinux with gdm). I will wait a new version of the package (I don't want to use the aur git version) and use another desktop environment in the meantime.
