### ISSUE TITLE
Beginning of notification text is cut off

### ISSUE THREAD

**Issue by DrMarkuse** [solus-project/budgie-desktop#1154]
Using Solus 3 with Budgie 10.4 on a ThinkPad T430 (newly installed and language set to German) beginning of notifications text is cut off (screenshot annexed) when text to be displayed is wider than the Raven panel.
![notifications - beginning of words cut off](https://user-images.githubusercontent.com/31903781/30350246-364ab3fc-9816-11e7-8571-a42b7185df55.png)

Not sure if this is a bug, but I would prefer the beginning of the notification to be displayed ("Sicherheitsaktualisierung ver,,,").

---
Issue occurs every time notification wider than width of Raven is to be displayed.

**Comment by EDavidF** [comment]
This, too, is a big problem for me: I can't read most notifications in Raven (because they are cut-off), and clicking (in any combination) does nothing. I have searched for other ways to see these messages, but cannot find anything.
