### ISSUE TITLE
Opening a modal freezes panel

### ISSUE THREAD

**Issue by MrYakobo** [solus-project/budgie-desktop#1171]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**

When opening a modal in the settings, the (bottom) panel freezes and is non interactive. This is fixed by alt-tabbing to the modal and closing it.

 ...

**Steps to reproduce the issue**

Budgie settings
Autostart
Click on the +, "Add command".

 ...

Other notes:
This doesn't happen when opening the "Fonts" settings (also in Budgie settings). My observation here is that the Font window doesn't lock the parent window, so you can open the Font settings and then wander around in the UI whilst it is still open. This isn't the case with the "Add command"-window, as it forces the user to close it before other actions can be made.

**Comment by JoshStrobl** [comment]
Unable to reproduce with latest release or git builds of Budgie.
