### ISSUE TITLE
budgie-desktop hangs when tiling - mutter 3.26.1

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1185]
budgie-desktop 10.4 Ubuntu 17.10

Heads up report:

Ubuntu 17.10 beta 2 just updated with the latest mutter point release 3.26.1

report here https://bugs.launchpad.net/ubuntu/+source/budgie-desktop/+bug/1721700

Tiling left/right with the second window causes budgie-desktop to hang / first window to become unresponsive.

Looks very much like that the "fixes" in gnome-shell for better tiling has adversely affected budgie-desktop

EDIT:

talking to jbicha - apparently tiling changes where made 20hrs after the 3.26.1 freeze - the tiling changes for mutter also needed GTK+ changes as well. So may have unfairly fingered mutter here - could be GTK+.

EDIT: have recompiled 3.26.0 version of mutter but still broken - so maybe another 3.26.1 package change.

**Comment by Jacob-Vlijm** [comment]
Additional observations:

- Seemingly at random, the wallpaper shows totally black for a second or 2/3 
- Window tiling via shortcut either makes the window stuck on its initial position, or on the side it was moved to.
- After the window gets stuck due to tiling, the mouse loses its ability to set (change) window focus. Changing focus by clicking Plank works though.
- Occasionally, after testing window tiling, -> black wallpaper followed by log out.

All seemingly random errors, I can' t see a clear pattern

**Comment by fossfreedom** [comment]
@ikeydoherty we need to-do some more longer test runs - but it looks like the random crashes/tiling are due to the windows animations - turning it off seems to make things more stable.

cross fingers.

Need to decide now if we should ship 17.10 with animations off by default.

**Comment by fossfreedom** [comment]
two curious observations.

If on ubuntu the "mutter" package is installed, then random crashes when animation is switched on.

If we purge this package then all is sweet and light with or without animation.

Second observation.  Tiling "Tilix" or "gedit" or libreoffice draw and closing these apps via "x" whilst they are tiled crashes budgie-wm .  Havent figured out how to get a backtrace though.

**Comment by ikeydoherty** [comment]
Ok. Our Solus upgrade is nearly complete now. We'll be able to start working through these 3.26 regressions

**Comment by fossfreedom** [comment]
is this relevant - found in syslog at the time of the window manager crash:

```
Oct  8 22:32:58 dad-VirtualBox budgie-wm[4862]: The program 'budgie-wm' received an X Window System error.#012This probably reflects a bug in the program.#012The error was 'BadWindow (invalid Window parameter)'.#012  (Details: serial 4389 error_code 3 request_code 18 (core protocol) minor_code 0)#012  (Note to programmers: normally, X errors are reported asynchronously;#012   that is, you will receive the error a while after causing it.#012   To debug your program, run it with the GDK_SYNCHRONIZE environment#012   variable to change this behavior. You can then get a meaningful#012   backtrace from your debugger if you break on the gdk_x_error() function.)
Oct  8 22:32:58 dad-VirtualBox kernel: [ 5852.469369] traps: budgie-wm[4862] trap int3 ip:7f0d5c6f6961 sp:7ffd6801e4e0 error:0 in libglib-2.0.so.0.5400.1[7f0d5c6a6000+111000]
Oct  8 22:32:58 dad-VirtualBox gnome-session[4602]: gnome-session-binary[4602]: WARNING: Application 'budgie-wm.desktop' killed by signal 5
Oct  8 22:32:58 dad-VirtualBox gnome-session-binary[4602]: WARNING: Application 'budgie-wm.desktop' killed by signal 5
Oct  8 22:32:58 dad-VirtualBox nautilus-deskto[4944]: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
Oct  8 22:32:59 dad-VirtualBox nautilus-deskto[4944]: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
Oct  8 22:32:59 dad-VirtualBox budgie-wm.desktop[5089]: Window manager warning: "XF86RFKill" is not a valid accelerator
```

this? Window manager warning: "XF86RFKill" is not a valid accelerator - kind of curious gnome-settings-daemon in the changelog mentions this https://github.com/GNOME/gnome-settings-daemon/commit/248eb834f9d428a493457e26a8d2e3687ee576db

**Comment by ikeydoherty** [comment]
So this is actually an upstream GNOME issue

https://bugzilla.gnome.org/show_bug.cgi?id=788666

**Comment by Jacob-Vlijm** [comment]
Just tested the fix. Although closing a tiled window now works fine, at some point (in my case after 5-10 times tiling) the tiled window is stuck again, unable to change focus with a mouse click. The issue was "anounced" by a small black out (again) during workspace switch.

**Comment by ikeydoherty** [comment]
Wondering if there is a way for us to just turn off all this special tiling behaviour..

**Comment by Jacob-Vlijm** [comment]
Another important observation: the tiling issue seems limited to gedit now. Tried firefox, libreoffice, gnome-terminal, all fine. first gedit test -> stuck.

**Comment by GrindamN** [comment]
Seems to happen in Chromium too.

**Comment by fossfreedom** [comment]
With the new mutter 3.26.2 drop on Ubuntu 17.10 yesterday I can no longer make windows to hang/stick.

Ubuntu 17.10 doesnt have the disable maximise animations patch - so it seems good news.

Can anyone verify please (on any distro) to confirm if with the new 3.26.2 mutter that they can still make windows hang?

**Comment by brxck** [comment]
With the new mutter I can only make Chromium stick. 

Google Chrome and gedit previously stuck for me but not any more.

**Comment by fossfreedom** [comment]
Closing this - it was a mutter issue that is no longer supported by the master branch.
