### ISSUE TITLE
Raven stretches and won't reset

### ISSUE THREAD

**Issue by xeals** [solus-project/budgie-desktop#1187]
**Operating System**: Solus 3, `linux-current`
**Budgie version**: Budgie 10.4

**The issue encountered**

Raven has stretched beyond the width of the screen and won't shrink back down.

**Steps to reproduce the issue**

I honestly don't know how to reproduce this, I'm sorry. I came to my computer this morning and found a notification with a stream of `?` that seemed to not be line broken. It caused Raven to stretch way beyond the edge of the screen and now won't properly collapse again, for both the notification and applets view.

The issue is fixed on a restart of Budgie.

![2017-10-07-102052_1920x1080_scrot](https://user-images.githubusercontent.com/21125058/31301944-b015a822-ab49-11e7-9d3b-feeeea946050.png)

![screenshot from 2017-10-07 10-26-31](https://user-images.githubusercontent.com/21125058/31301991-0afe816e-ab4a-11e7-805d-82172d358a04.png)

**Comment by JoshStrobl** [comment]
With the rewrite of this aspect of Raven, with NotificationGroups and tweaks to labels, this has since been resolved.
