### ISSUE TITLE
Icon theme is not applied to the workspace switcher applet

### ISSUE THREAD

**Issue by scileo** [solus-project/budgie-desktop#1188]
**Operating System**:  Solus (lastest stable as of 2017 10 07)
**Budgie version** : Budgie 10.4

**The issue encountered**
The icon theme which is choosen in the budgie settings app is not applied in the workspace preview (check the screenshot below for explanations).

**Steps to reproduce the issue**
- Choose Papirus (any variant) as default icon theme with the Budgie Desktop Setting application.

- Add a workspace viewer applet (translation may not be accurate) to your panel.

- Open an app (works with Hexchat) : the icon printed on the window list is not the same as the one which is displayed in the workspace viewer.

![capture du 2017-10-07 14-20-52](https://user-images.githubusercontent.com/25402018/31307755-c4fe3ea4-ab6a-11e7-96d9-8e049e70ebab.png)
(as you can see, the Exchat's icon which can be seen in the icon task list is not the same as the workspace switcher's one)

**Comment by Juankz** [comment]
Confirmed. Sometimes it doesn't even take any icon for specific applications, here is how looks Go-For-It and Notes-Up (flatpak app)

![budgie_issue](https://user-images.githubusercontent.com/18577412/33526628-1a9eb176-d812-11e7-9225-0d3ead0d3967.png)

**Comment by Nequo** [comment]
Is there any update on this? I have the same issue with slack, the icon shows in the menus but in the desktop switcher its just the blank window as above. I don't know which settings to change etc.. Thanks!

**Comment by Umlatt** [comment]
I am still seeing missing icons in the workspace switcher applet (whilst the icons exist in the system tray & icon task list applets).

**Comment by kwiat** [comment]
Also true when using regular icons — e.g. the case for Slack installed from the 'Third Party' section from the Software Center: https://imgur.com/wJ7paZI

**Comment by RafalSkolasinski** [comment]
Still the case for apps installed from Flatpak

![image](https://user-images.githubusercontent.com/10928117/89731313-eea6f200-da3d-11ea-8e05-6cbae73cc7dc.png)

**Comment by JoshStrobl** [comment]
Unfortunately not something in our control. This is directly from the libwnck folks. I'd suggest filing a bug with them.
