### ISSUE TITLE
Budgie Desktop start a gnome session

### ISSUE THREAD

**Issue by ArtyomFR** [solus-project/budgie-desktop#1191]
**Operating System**: Arch Linux LTS X64
**Budgie version**: Budgie 10.3 et 10.4 (both tested)

After a fresh install of my laptop:
Installing nvidia drivers (nvidia-lts and nvidia) and gnome: Work fine.
Installing Budgie Desktop: Work fine.
Using Budgie Desktop: Don't Work
Login with the Budgie Desktop just launch a standard Gnome session

**Comment by ikeydoherty** [comment]
IDK what this means.

**Comment by santisteban** [comment]
I've seen this before, but when trying to launch Budgie using GDM. A workaround was to use another display manager like LXDM or SDDM.

I don't know if this is the same case, with Budgie broken after Gnome 3.26.1, it could be a different issue.

**Comment by ArtyomFR** [comment]
I've already have this problem before but manage to solve it with good video driver installation.

On my laptop, first installation:
I got the probleme, install nvidia proprietary (maybe video-vesa, I no more remember): Work.

Same laptop now:
I get the probleme, install nvidia et nvidia LTS (I also try to install video-vesa and/or video-intel): Don't work.
My Laptop has Optimus so I install nvidia driver with Optimus compatibility (fresh install) following the arch wiki, to prevent all bugs from it. Though it worked without: Don't work.

When trying to execute budgie-desktop from gnome terminal nothing happen (no output log).

If I can provide any log resources, just tell me how or where.

**Comment by ArtyomFR** [comment]
Nevermind work smooth and nicely under lightdm when Optimus architecture is correctly set up.

**Comment by skullscream** [comment]
I can't login to Budgie either. Installed the complete gnome group, installed dependencies listed here https://www.archlinux.org/packages/community/x86_64/budgie-desktop/ updated etc... Now I'll try installing the git version from AUR since i see this one's flagged out of date. Will come back here once it's done.

Antergos openbox was installed initially, then removed and installed mate.

**Comment by ikeydoherty** [comment]
Go with aur budgie-desktop-git if you want a chance of it working :)

**Comment by Ste74** [comment]
Or take pkgbuild for 10.4 from our community repo ( Manjaro ) and compile it  ;)

**Comment by ikeydoherty** [comment]
Ah - or that. We need to centralise this info :P

**Comment by skullscream** [comment]
I get 
```
eson encountered an error in file subprojects/gvc/meson.build, line 31, column 0:
Sandbox violation: Tried to grab file gvc-channel-map.c from a different subproject.

A full log can be found at /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...
```
with the AUR. Gonna post the log it says in a sec.

**Comment by skullscream** [comment]
```
Build started at 2017-10-11T16:34:14.587176
Python binary: /usr/bin/python
Python system: Linux
The Meson build system
Version: 0.43.0
Source dir: /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git
Build dir: /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/build
Build type: native build
Project name: budgie-desktop
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/build/meson-private/sanitycheckc.c -o /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 7.2.0)
Appending CFLAGS from environment: '-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt'
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Appending CPPFLAGS from environment: '-D_FORTIFY_SOURCE=2'
Running compile:
Working directory:  /tmp/tmpeuchtlna
Command line:  valac /tmp/tmpeuchtlna/testfile.vala -C -C -o /tmp/tmpeuchtlna/output.obj 

Code:
 class MesonSanityCheck : Object { }
Compiler stdout:
 Compilation succeeded - 1 warning(s)

Compiler stderr:
 warning: --output and -o have no effect when -C or --ccode is set

Native Vala compiler: valac (valac 0.38.2)
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Program meson_post_install.sh found: YES (/home/milan/.cache/pacaur/budgie-desktop-git/src/budgie-desktop-git/meson_post_install.sh)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gtk+-3.0 found: YES 3.22.24
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency glib-2.0 found: YES 2.54.0
Determining dependency 'gio-unix-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gio-unix-2.0 found: YES 2.54.0
Determining dependency 'libpeas-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpeas-1.0 found: YES 1.22.0
Determining dependency 'gdk-x11-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gdk-x11-3.0 found: YES 3.22.24
Determining dependency 'uuid' with pkg-config executable '/usr/bin/pkg-config'
Native dependency uuid found: YES 2.30.2
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gtk+-3.0 found: NO found '3.22.24' but need: '< 3.19'
Dependency gtk+-3.0 found: NO
Determining dependency 'ibus-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency ibus-1.0 found: YES 1.5.16
Determining dependency 'gnome-desktop-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gnome-desktop-3.0 found: YES 3.26.1
Determining dependency 'gsettings-desktop-schemas' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gsettings-desktop-schemas found: YES 3.24.1
Determining dependency 'libwnck-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libwnck-3.0 found: YES 3.24.1
Determining dependency 'accountsservice' with pkg-config executable '/usr/bin/pkg-config'
Native dependency accountsservice found: YES 0.6.45
Running command: /usr/bin/git describe
--- stdout----
v10.4-6-g9e2cc0f2

----stderr----


Program intltool-merge found: YES (/usr/bin/intltool-merge)
Configuring config.h using configuration

Executing subproject gvc.

Project name: gvc
Native C compiler: cc (gcc 7.2.0)
Determining dependency 'libpulse' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpulse found: YES 11.1
Determining dependency 'libpulse-mainloop-glib' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libpulse-mainloop-glib found: YES 11.1
```

**Comment by skullscream** [comment]
You here said one should do
```
git submodule init
git submodule update
```

Once i clone the repository from AUR and cd into it, then i should do it, yes?

**Comment by ikeydoherty** [comment]
@skullscream if the package is properly done there is no reason for that, it would use our release tarball

**Comment by skullscream** [comment]
```
Native dependency gtk+-3.0 found: NO found '3.22.24' but need: '< 3.19'
Dependency gtk+-3.0 found: NO
```

I think this is the culprit. I need to downgrade?

I'll try downloading now straight from github.

**Comment by skullscream** [comment]
hm, when i did the
```
git submodule init
git submodule update
```
i never got the build directory. I can't compile it.

**Comment by asherCW** [comment]
I seem to be having the same issue. My normal budgie stopped working this morning across all display managers so I tried to switch to the AUR version, but when building that I get the same 
`Meson encountered an error in file subprojects/gvc/meson.build, line 31, column 0:
Sandbox violation: Tried to grab file gvc-channel-map.c from a different subproject.
`
error as above

**Comment by ikeydoherty** [comment]
Possible theres another regression with meson?

**Comment by JeanBarriere** [comment]
Yes @ikeydoherty they should solve their problem downgrading meson to version `0.42.1`.

**Comment by skullscream** [comment]
I re-installed arch completely. Now it's a fresh arch installation (not antergos) with only xorg, xorg-server, gdm, firefox and dependencies. When I first logged in using gdm it gave me gnome with only settings from budgie. Everything else that i noticed was from gnome. When i switched to lightdm and restarted it wouldn't even log me into that gnome session, just pulls me back to the login. 

Fully updated arch.

**Comment by alunux** [comment]
@skullscream @electrifeye You can build the latest master branch using meson 0.43.0, now.
