### ISSUE TITLE
Default desktop background is blank

### ISSUE THREAD

**Issue by electrifeye** [solus-project/budgie-desktop#1196]
Linux 4.13.5.1-ARCH
budgie-desktop v10.4-8-gff09a510

The default desktop background appears blank for me on the latest budgie version from the git.

I can successfully change to other backgrounds using the "change background" interface but when I change back to the default backdrop (which is supposed to change over time) the entire backdrop is blue.

 ...

This happened for me on a newly reinstalled budgie from the git

 ...

**Comment by ikeydoherty** [comment]
We don't support XML backgrounds from GNOME Shell

**Comment by JoshStrobl** [comment]
Closing since this was resolved in ad00c095afb80f5b1f7b14cc6ab5c01fb8e8fb4e
