### ISSUE TITLE
budgie-daemon segfault at each shutdown

### ISSUE THREAD

**Issue by mts19** [solus-project/budgie-desktop#1201]
Using Solus 3 up to date.

    budgie-desktop --version
10.4

**The issue encountered**
budgie-daemon segfault at each shutdown. hidden crash dump files created in home directory.
aprox 43MB.
 ...

**Steps to reproduce the issue**
Happens at each shutdown.

 ...
`Oct 17 11:35:05 solus systemd-logind[613]: System is powering down.
Oct 17 11:35:05 solus gvfsd[829]: A connection to the bus can't be made
Oct 17 11:35:05 solus gnome-session[820]: gnome-session-binary[820]: WARNING: Lost name on bus: org.gnome.SessionManager
Oct 17 11:35:05 solus gnome-session-binary[820]: WARNING: Lost name on bus: org.gnome.SessionManager
Oct 17 11:35:05 solus kernel: budgie-daemon[1061]: segfault at 0 ip 00007f18f641d281 sp 00007ffe29bc8f40 error 6 in libwnck-3.so.0.3.0[7f18f6407000+3e000]
Oct 17 11:35:05 solus kernel: audit: type=1701 audit(1508204105.598:35): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=1061 comm="budgie-daemon" exe="/usr/bin/budgie-daemon" sig=11 res=1
Oct 17 11:35:05 solus kernel: rfkill: input handler enabled
Oct 17 11:35:05 solus audit[1061]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=1061 comm="budgie-daemon" exe="/usr/bin/budgie-daemon" sig=11 res=1
Oct 17 11:35:05 solus budgie-daemon[1061]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 11:35:05 solus budgie-daemon[1061]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 11:35:05 solus budgie-daemon[1061]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 11:35:05 solus budgie-daemon[1061]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 11:35:05 solus budgie-daemon[1061]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 11:35:05 solus budgie-daemon[1061]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 11:35:05 solus gsd-rfkill[901]: g_object_notify: object class 'CcRfkillGlib' has no property named 'kernel-noinput'
Oct 17 11:35:05 solus systemd[1]: Unmounted /run/user/1000/gvfs.

Oct 17 12:25:01 solus budgie-daemon[1090]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 12:25:01 solus budgie-daemon[1090]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 12:25:01 solus gsd-print-notif[924]: Source ID 2 was not found when attempting to remove it
Oct 17 12:25:01 solus budgie-daemon[1090]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 12:25:01 solus budgie-daemon[1090]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 12:25:01 solus budgie-daemon[1090]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 12:25:01 solus budgie-daemon[1090]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 12:25:01 solus audit[1090]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=1090 comm="budgie-daemon" exe="/usr/bin/budgie-daemon" sig=11 res=1
Oct 17 12:25:01 solus kernel: budgie-daemon[1090]: segfault at 0 ip 00007ff38e5cc281 sp 00007fff55755010 error 6 in libwnck-3.so.0.3.0[7ff38e5b6000+3e000]
Oct 17 12:25:01 solus kernel: audit: type=1701 audit(1508207101.164:35): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=1090 comm="budgie-daemon" exe="/usr/bin/budgie-daemon" sig=11 res=1
Oct 17 12:25:01 solus budgie-polkit-d[1091]: instance with invalid (NULL) class pointer
Oct 17 12:25:01 solus systemd[822]: Stopping D-Bus User Message Bus...
Oct 17 12:25:01 solus budgie-polkit-d[1091]: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Oct 17 12:25:01 solus systemd-logind[615]: System is powering down.
Oct 17 12:25:01 solus kernel: rfkill: input handler enabled

Oct 17 16:15:05 solus kernel: budgie-daemon[1078]: segfault at 0 ip 00007f7b6ea8c281 sp 00007ffcd0b0f0c0 error 6 in libwnck-3.so.0.3.0 (deleted)[7f7b6ea76000+3e000]
Oct 17 16:15:05 solus kernel: audit: type=1701 audit(1508220905.275:35): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=1078 comm="budgie-daemon" exe="/usr/bin/budgie-daemon" sig=11 res=1
Oct 17 16:15:05 solus gsd-media-keys[888]: Error releasing name org.gnome.SettingsDaemon.MediaKeys: The connection is closed
Oct 17 16:15:05 solus budgie-daemon[1078]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 16:15:05 solus budgie-daemon[1078]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 16:15:05 solus budgie-daemon[1078]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 16:15:05 solus budgie-daemon[1078]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 16:15:05 solus budgie-daemon[1078]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 16:15:05 solus budgie-daemon[1078]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
Oct 17 16:15:05 solus gsd-color[934]: Error releasing name org.gnome.SettingsDaemon.Color: The connection is closed
Oct 17 16:15:05 solus gnome-session[829]: gnome-session-binary[829]: WARNING: Lost name on bus: org.gnome.SessionManager
Oct 17 16:15:05 solus gnome-session-binary[829]: WARNING: Lost name on bus: org.gnome.SessionManager`

Attaching crash dump file if possible. 
Have zipped file but don't seem to be able to upload it.

**Comment by fossfreedom** [comment]
FYI - I have also seen this in Ubuntu during 17.10 but it magically disappeared at around our beta time in Sept.  I know that really is an unhelpful statement ... but you are not alone in seeing it happen.

**Comment by cernyjakub** [comment]
Just for the record, we experience the exact same issue, on Budgie 10.4 running on Ubuntu 16.04 (from budgie-remix PPA). I see this in dmesg output after user tries to log-out:

```
[ 2485.929186] budgie-daemon[1471]: segfault at 0 ip 00007f6048e20be3 sp 00007ffea68041e0 error 6 in libwnck-3.so.0.2.2[7f6048e0c000+3d000]
```
I think the key is this fragment in the output from @mts19:

```
Oct 17 11:35:05 solus budgie-daemon[1061]: invalid unclassed pointer in cast to 'WnckWindow'
Oct 17 11:35:05 solus budgie-daemon[1061]: _wnck_window_destroy: assertion 'WNCK_IS_WINDOW (window)' failed
```
I will be happy to do more testing if needed. The logout experience is bad now - PC frozes for cca 90 secs and then systemd respawns lightdm, which draws login screen and users can login again...

regards!
Jakub

**Comment by mts19** [comment]
Since last Fridays updates I still have a budgie daemon segfault on shutdown. However I am not getting a hidden crash dump file. That seems to have been resolved.
Oct 31 20:02:01 solus kernel: budgie-daemon[1058]: segfault at 0 ip 00007fc7ad726281 sp 00007ffc4145b2a0 error 6 in libwnck-3.so.0.3.0[7fc7ad710000+3e000

**Comment by fossfreedom** [comment]
ok - the stacktrace from 1729986 that has been automatically reported hundreds of times since 10.3 is

http://paste.ubuntu.com/25970126/

I've built the 10.4 version on ubuntu and enclosed is the generated .c files in budgie-daemon which seem to correspond to the stacktrace.

[daemon.zip](https://github.com/budgie-desktop/budgie-desktop/files/1476441/daemon.zip)
