### ISSUE TITLE
Sound settings icon associated with wrong shortcut

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1204]
**Operating System**: Solus 3
**Budgie version**: i.e. Budgie 10.4
**The issue encountered**

Pinning the shortcut to the sound settings to the panel results in a shortcut that connects to the wifi settings, not the sound settings. This is even more painful than it normally would be, because Budgie (Solus?) doesn't seem to remember previously attached audio source prioritization, so I'm constantly having to go to sound settings (which is really wifi), back out to the actual sound settings, then set the same priority order that I set a hundred times before for the same old XYZ audio system.

**Steps to reproduce the issue**

Open the sound settings under "System Settings". Right-click on the icon on the taskbar and select "Pin to Panel". Then click on it again later, which will take you to wifi settings. As I wrote this, I also found that the same thing happens when you click on "Details" in the start menu under "System Settings".

 ...

**Comment by fossfreedom** [comment]
check the .desktop file that you are pinning has "exec=gnome-control-center sound"

**Comment by KloudKoder** [comment]
Where would I find that file?

**Comment by casucci** [comment]
The file you are looking for is located in /usr/share/applications and called gnome-sound-panel.desktop

**Comment by KloudKoder** [comment]
I found the file, but it does not contain the word "exec". Does that explain why pin-to-panel is pointing the icon to wifi control instead of sound control?

**Comment by JoshStrobl** [comment]
Appears to be resolved, tested against latest Budgie git and Solus 3 (installed).
