### ISSUE TITLE
Brightness hotkeys are now broken

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1205]
**Operating System**: e.g. Solus 3
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

Fn+(brightness up) and Fn+(brightness down) have suddenly stopped working. The only workaround is to go to the power settings and change the brightness there. (For that matter it would help to have a link in the display settings that connects it to the power settings in this specific case. Or just put the same setting under both menus and not have the trouble in the first place. After all, brightness is both a power issue and a display property.)

**Steps to reproduce the issue**

As above.

**Comment by fossfreedom** [comment]
Ubuntu 17.10 users have reported a similar issue - some Fn keys work, some don't.  Given that it happened when moving to the gnome 3.26.1 stack probably related.

**Comment by KloudKoder** [comment]
Thanks fossfreedom, it only just started after a recent update, so perhaps you're right. It should be easy to discover in that case. Also, when manually adjusting the brightness in the Power menu, it can only be done with the touchpad. When you use the keyboard, you can decrease the brightness with the left arrow, but the right arrow does nothing, as though there's some sort of implied cap on value. Weird.

**Comment by MaxJonasG** [comment]
for me (Dell XPS13) it is the sound up/down keys that do work only intermittently. However I also believe this is a Ubuntu 17.10 general problem rather than a Budgie specific one.

**Comment by KazuDante** [comment]
I'm not sure if Chromebooks are supported but  none of the hotkeys work.

**Comment by ikeydoherty** [comment]
Let's focus on the immediate regression, i.e. things that stopped working. Things that don't work but aren't known to work before will lead us down rabbit holes and are usually kernel related :)

**Comment by KloudKoder** [comment]
This appears to be fixed.

**Comment by iwantedsupernovabutitwastaken** [comment]
For me screenshot shortcuts don't work. So hitting Alt+PrintScrn, Shift+PrintScrn and Shift+Alt+PrintScrn doesn't work.
