### ISSUE TITLE
Missing (or wrong) labels in "Places" applet

### ISSUE THREAD

**Issue by Maestroschan** [solus-project/budgie-desktop#1234]
**Operating System**: Ubuntu Budgie
**Budgie version**: 10.4
 (the bug also occurs on Solus but i didn't note the version of Budgie)

**The issue encountered**

Some specific bookmarks don't have labels in the "Places" widget.
Screenshot: https://www.hostingpics.net/viewer.php?id=188049Capturedu20171030013958.png

**Steps to reproduce the issue**

Add recent:/// or trash:/// to your Nautilus bookmarks, add the widget to a panel, open it, and notice that these items don't have a label.
The problem is still occuring after renaming bookmarks.

**Comment by Coeur-Noir** [comment]
( also there https://bugs.launchpad.net/ubuntu/+source/budgie-desktop/+bug/1730014 )

**Comment by Maestroschan** [comment]
In fact, the issue is wider: in the applet, all bookmarks are not labeled with their name, but with the name of the last folder in the URI

**Comment by Coeur-Noir** [comment]
Maybe related to https://github.com/budgie-desktop/budgie-desktop/issues/1173 ?

**Comment by JoshStrobl** [comment]
Closing as duplicate of #1173.
