### ISSUE TITLE
network icon no-show from sys tray

### ISSUE THREAD

**Issue by n8v8R** [solus-project/budgie-desktop#1235]
Distro: Solus 3.1 (3.26.1)
Kernel: 4.13.8-28.current x86_64
bits: 64
gcc: 6.4.0
Desktop: Budgie 10.4
Budgie version: Budgie 1.4 updated

With the Ethernet setting 

> automatically connect to VPN when using this connection

 the network icon is a no-show in the sys tray, until the LAN and VPN connections are actually established.

![network icon missing](https://user-images.githubusercontent.com/13611490/32270443-3dd465e4-bef6-11e7-950d-8c056e43f0a0.png)

**Comment by JoshStrobl** [comment]
Closing as we use nm-applet, any issues with it specifically should be reported to them and this is likely resolved.
