### ISSUE TITLE
Panel Applet Icon Task List Configuration Location

### ISSUE THREAD

**Issue by migueldemoura** [solus-project/budgie-desktop#1237]
**Operating System**: Ubuntu Budgie 17.10
**Budgie version**: 10.4

Where is the icon task list configuration stored at? I'd like to add a custom .desktop script but can't use the right click "Pin to panel" for obvious reasons.

**Comment by gersonjferreira** [comment]
Same thing here. The software Mathematica has a .desktop, but the Task List does not show a "pin" option.  I believe that this is because the .desktop points to a script that redirects the call, so the system does not associate the window to the .desktop file.

**Comment by JoshStrobl** [comment]
You need to have a valid desktop file that corresponds to a valid DesktopAppInfo object for it to be pinnable.
