### ISSUE TITLE
Disabling Bluetooth on Startup

### ISSUE THREAD

**Issue by Immortalin** [solus-project/budgie-desktop#1247]
On OSes such as windows, it is possible to set the default mode of bluetooth i.e. it persists after reboots

**Comment by casucci** [comment]
Bluetooth can be enabled/disabled through gnome-control-center

**Comment by YoyPa** [comment]
If gnome fail (my case) you can also do it via TLP: http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
With the following inside /etc/default/tlp:
```
# Radio devices to disable on startup: bluetooth, wifi, wwan.
# Separate multiple devices with spaces.
DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
```
