### ISSUE TITLE
Status icon does not get hidden

### ISSUE THREAD

**Issue by DonHugo69** [solus-project/budgie-desktop#1271]
**Operating System**: Solus, stable (updated at the time of writing, 17.12.17), kernel 4.14.6-40.current
**Budgie version**: budgie-desktop 10.4
**Hardware**: ThinkPad X230T, Intel graphics

**The issue encountered**

The upper panel which contains the status icons (e.g. Riot, Nextcloud) is set to intelligent auto-hide. However, not all icons get hidden. Here, Nextcloud stays visible.
Noteworthy might be, that this does only happen when using the Intel or the modesetting graphics driver. Using "nomodeset" in GRUB leads to VESA being used and the icon hides together with the panel.
![20171217_181121](https://user-images.githubusercontent.com/10484857/34082103-84a5de2c-e358-11e7-92a3-349228e0d30f.jpg)

**Comment by gkr09** [comment]
Hey, I am having similar issues with panel intelligent hiding where the **network** icon is still displayed ! None of the budgie applets have this problem though, only the system tray ones.
:)

**Comment by Awwkaw** [comment]
I'm havving the exact same issue:

![image](https://user-images.githubusercontent.com/25682700/48295030-9ddd2080-e488-11e8-9da6-b51b576df1cf.png)

**Comment by JoshStrobl** [comment]
May be resolved with #1998
