### ISSUE TITLE
Budgie panel appears to close/re-open after unplugging usb sound device

### ISSUE THREAD

**Issue by bwat47** [solus-project/budgie-desktop#1275]
OS: Solus 3 with all updates
Budgie version: 10.4.0
Hardware: Dell XPS 13 9360

Steps to Re-create:
1. Plug in USB Headphones
2. Unplug USB Headphones

Expected: Budgie panel should not close

Actual: when I unplug the USB headphones the budgie panel briefly disappears and comes back

**Comment by bwat47** [comment]
I noticed these entries in journalctl when it happens:

Dec 25 23:28:19 xps13-solus gsd-media-keys[733]: Unable to get default sink
Dec 25 23:28:19 xps13-solus budgie-panel[855]: gvc_mixer_stream_get_ports: assertion 'GVC_IS_MIXER_STREAM (stream)' failed
Dec 25 23:28:19 xps13-solus budgie-panel.desktop[855]: **
Dec 25 23:28:19 xps13-solus budgie-panel.desktop[855]: Gvc:ERROR:../src/gvc/gvc-mixer-card.c:208:_pa_context_set_card_profile_by_index_cb: assertion failed: (card->priv->target_profile)
Dec 25 23:28:19 xps13-solus budgie-panel[855]: gvc_mixer_stream_get_id: assertion 'GVC_IS_MIXER_STREAM (stream)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: gvc_mixer_stream_get_description: assertion 'GVC_IS_MIXER_STREAM (stream)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: invalid (NULL) pointer instance
Dec 25 23:28:19 xps13-solus budgie-panel[855]: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: gvc_mixer_stream_get_volume: assertion 'GVC_IS_MIXER_STREAM (stream)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: gvc_mixer_stream_get_is_muted: assertion 'GVC_IS_MIXER_STREAM (stream)' failed
Dec 25 23:28:19 xps13-solus budgie-panel[855]: invalid unclassed pointer in cast to 'GvcMixerCard'
Dec 25 23:28:19 xps13-solus gnome-session[658]: gnome-session-binary[658]: WARNING: Application 'budgie-panel.desktop' killed by signal 6
Dec 25 23:28:19 xps13-solus gnome-session-binary[658]: WARNING: Application 'budgie-panel.desktop' killed by signal 6

**Comment by JoshStrobl** [comment]
Validated that this should no longer be an issue as of a6a6ef353a29c71d01ab1a624c23ec9f594a2796, tested with my Blue Yeti.
