### ISSUE TITLE
pkexec hangs when "cancel" is clicked on the generated polkit prompt.

### ISSUE THREAD

**Issue by mhogomchungu** [solus-project/budgie-desktop#1279]
Operating System: Ubuntu 17.10
Budgie version: 10.4

pkexec hangs when "cancel" is clicked on the generated polkit prompt.

Steps to reproduce are documented here: https://github.com/mhogomchungu/zuluCrypt/issues/85#issuecomment-354562072

**Comment by nickdonnelly** [comment]
I'm experiencing this issue as well. Happens both when manually invoked from a shell and from applications. This can be a big issue for some applications, bricking them until a response is given.

**Comment by santileortiz** [comment]
I managed to solve this issue in elementary's Polkit Agent here https://github.com/elementary/pantheon-agent-polkit/pull/26, maybe this will work for budgie's agent too?
