### ISSUE TITLE
Budgie cannot grab pointer

### ISSUE THREAD

**Issue by Binero** [solus-project/budgie-desktop#128]
I have so issue where sometimes budgie doesn't respond to the pointer anymore. I can move the pointer, but when I click on something, it won't respond, and when I hover over something that's supposed to give me a hover effect, nothing happens. 

I was trying to fix this issue yesterday, and I pressed Alt+F2 to try to execute some commands, and while I was doing this, an error popped up saying it could not grab the pointer. I'm not sure what program was giving me this error, but I'm pretty confident it wanted to show me a password dialog.

This issue never occured to me on GNOME, or any other desktop I run on this computer. On Budgie it occurs quite often. I have a few theories about when the bug can occur, although it's hard to be certain because it feels to occur randomly:
 * using multiple workspaces
 * running full screen applications using SDL, and Alt-Tabbing between them
 * simply using the mouse too quickly

**Comment by ikeydoherty** [comment]
This pointer issue is unrelated to Budgie, but a gksu or polkit prompt. Budgie in no way requests any details or passwords from you, or indeed has any integration with these tools.

**Comment by Binero** [comment]
Well I never saw a password dialogue, that was just what I was expecting it to do. Also, that only happened *after* I lost my mouse already, and I was trying to get it back, so the problem shouldn't be there.

**Comment by ikeydoherty** [comment]
What commands are you running and on what distribution, precise version? I'm sorry but this isn't a *security issue* in Budgie, it's exactly as described. One thing is fighting with another thing for control of the mouse pointer. It could even be the Budgie Menu if you're using keyboard shortcuts. I've just pushed changes to rework grabbing behaviour in Budgie, see:

7aa7ecc75c85a62abd4fcdce1c0dd947d477ccd4
2fb8f68dec6ecab8c5dff47b105d620a6ac5ce6c

Popvers are the only place within Budgie we explicitly use grabs, I'm *hopeful* that this is the related issue and will fix this problem for you. Can you (in your own time, ofc :)) confirm whether this makes a difference ?

**Comment by Binero** [comment]
Will do after the weekend - away from home at this time.

**Comment by ikeydoherty** [comment]
Awesome, cheers :)

**Comment by Binero** [comment]
I'm having a lot of errors in the new version - is there a way I can get a log of budigie errors to diagnose?

**Comment by ikeydoherty** [comment]
Errors building or running ?

**Comment by Binero** [comment]
Running.

**Comment by ikeydoherty** [comment]
Can I get some information on these errors.. ?

**Comment by Binero** [comment]
I would, but the errors are very reverse and hard to describe. Some of them include random applications freezing and budgie not being able to detect applications being killed. 

Is there a way to get an error log?

**Comment by ikeydoherty** [comment]
Error logs are distribution specific, we rely on .xsession-errors mostly.. Given the issue is unrelated to Budgie (grabbing pointer, this is nothing to do with budgie, but another application) - I'm closing this.
