### ISSUE TITLE
Time is displayed too small to read

### ISSUE THREAD

**Issue by Siilwyn** [solus-project/budgie-desktop#1283]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4

**The issue encountered**
On a screen with a resolution of 1920 by 1080, the displayed time in the panel is too small to read:
![image](https://user-images.githubusercontent.com/5701149/34565978-1dd535ea-f15d-11e7-9fb2-83fa58612ac2.png)

The default text size of the gedit text editor and gnome terminal seem much better.

**Comment by hfel** [comment]
This seems to be a scaling issue with HiDPI screens - you can install GNOME Tweaks and under Fonts tweak the 'Scaling Factor' to suit your preferred font & widget size.

On my 12.5" 1920 by 1080 screen, a factor of 1.35 is optimal for me.

**Comment by bja-au** [comment]
G';day - thanks hfel for the fonts tweak idea however it increases the fonts in ALL windows - be nice if it was only the menu bar :(
BTW Siilwyn, love your desktop pic :)
BJA

**Comment by Siilwyn** [comment]
Hi @hfel thanks for the suggestion, as @bja-au indicated the global font size is perfect as it is. Just the displayed time is very small.
Also tried out GNOME instead of Budgie and the time display in the top bar there is bigger.

@bja-au thanks! ^^
