### ISSUE TITLE
[Feature Request] Screen Brightness Control Applet

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1285]
Budgie should offer a way to control screen brightness from the taskbar, as it's sometimes inconvenient to reach for the proper keys, and towards the extreme low end of brightness the intervals by which brightness changes via keyboard control are too long due to higher sensitivity. 

This could be implemented, for example, as

- a standalone applet, 
- a controller in the Raven panel alongside volume control, or
- an extra feature in the 'status indicator' applet, perhaps together with the battery indicator à la KDE.

**Comment by alunux** [comment]
Already there https://github.com/ilgarmehmetali/budgie-brightness-control-applet

**Comment by hfel** [comment]
Thanks! I wasn't aware of that. In any case it would be nice if it was included with the DE.

**Comment by ICA3DaR5** [comment]
I am going to try and package this.

**Comment by JoshStrobl** [comment]
Closing since a 3rd-party applet provides this functionality.

**Comment by hfel** [comment]
Will it be included in the repository?

**Comment by JoshStrobl** [comment]
In the repository of what exactly? Your operating system? budgie-desktop?

**Comment by hfel** [comment]
Sorry, I meant the Solus repos. Though since seems a very basic feature, it would be nice if it came packaged with Budgie itself.

**Comment by JoshStrobl** [comment]
In terms of Solus, the [appropriate package request](https://dev.solus-project.com/T5495) on our development tracker needs to be reviewed. The resolution of this issue should not be indicative of any action that'll be taken in regards to our repo and that request, merely that there is an available alternative option. I welcome you to comment on the task if you feel that this applet would suit your needs.
