### ISSUE TITLE
[Feature Request] Exclude Notifications From Notifications List

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1286]
In addition to allowing per-app control of notification popups, Budgie should have an analogous feature for notifications appearing in the notifications list/drawer. Currently, as all notifications end up populating the list, it becomes rather useless as common notifications (such as song changes in some audio players, removable drive mount status, message notifications, etc.) mix with uncommon ones (new updates, alarms, etc.), and is sometimes more trouble than good when one has to manually clear the list after every mundane notification to make it useful for the rarer ones.

**Comment by nextgensparx** [comment]
Kind of related [mockup](https://github.com/budgie-desktop/budgie-desktop/issues/763#issuecomment-271078987). If this kind of grouping get's implemented then having different categories may not be necessary.
Per-app control of notifications already exists. It just doesn't seem to support very many programs.

**Comment by JoshStrobl** [comment]
Resolved as of 21421252046e4561a8a7ef36b434b177b2b1f1e6 given you can now curate which apps actually provide notifications via GNOME Control Center. This is something that can be expanded on with Budgie 11 and our own control center down the road.

**Comment by hfel** [comment]
Does this mean that the user can still receive notifications, but choose to not have them count towards the drawer list? I.e. I'd still like to get a notification when a songs changes in my music player, but I don't want it to highlight the notification bell, which should be reserved for more important notifications.

**Comment by hfel** [comment]
Bump.
