### ISSUE TITLE
[Feature Request] Display menu bar startup notification

### ISSUE THREAD

**Issue by bja-au** [solus-project/budgie-desktop#1289]
G'day - more a request rather than an issue. When I start some applications (eg Vivaldi) by clicking on the menu bar icon it can take a while to startup and in that time you can't tell if you clicked correctly etc - would it be possible to (say) pulse the icon to indicate that  it is opening the app.

Thanks
BJA 

Solus 3
Linux 4.9.75-68.lts
Budgie 10.4

**Comment by JoshStrobl** [comment]
Closing since we have a pulsating animation during load and an indicator nowadays
