### ISSUE TITLE
[REQUEST] Longer default notification window duration

### ISSUE THREAD

**Issue by Iiari** [solus-project/budgie-desktop#1295]
**Operating System**: e.g. Ubuntu 17,10
**Budgie version**: Lastest Budgie release (sorry, not in front of it right now)

Hi all.  I've learned talking to the Ubuntu Budgie team that the default for notifications to timeout in Budgie is 4 seconds.  For some apps and browser extensions (like Pushbullet) where you can have long texts to read and/or have actionable options, this is far too short to read, let alone act, before the window vanishes.  Also, some apps (again, like the Pushbullet Chrome extension) have the option to have 8 vs 30 second notifications.  Some DE's (like Gnome) seem to respond to that, while Budgie is closing them in 4 seconds no matter what you choose.  

So my request would be to increase that duration to something like 8 or 10 seconds, and/or give the user a choice for this somewhere in settings.  

Thank you for your time and attention, and thanks for Budgie!

**Comment by JoshStrobl** [comment]
Closing. Notifications should be sent with the desired expiration timeout. By default, anything more than 20s (20000ms) will be set back to 4s (4000ms), anything *less* than that will be also set to 4s. However, scenarios where it is 8s or 10s, etc. would be correctly handled if the notification sets the right timeout info.
