### ISSUE TITLE
Disable the Login/Logout Sound [Feature-Request]

### ISSUE THREAD

**Issue by XxPhenixX** [solus-project/budgie-desktop#1298]
Hello,

I'm really annoyed by the login sound. It would be great if you could turn off/on this in the settings!
Thank you for your commitment.

Greetings
Martin

Version: budgie-desktop 10.4

**Comment by ikeydoherty** [comment]
Budgie doesn't play sounds by itself. canberra has a login sound service (usually a systemd unit) that can be turned off, for everything else it'd be sound effects in the GNOME Control Center :)

**Comment by XxPhenixX** [comment]
I've replaced the file 
/usr/share/sounds/freedesktop/stereo/service-login.oga

with a blank audio, but that's just a workaround, because I only find the solution to turn off the whole Canberra Sound Service...
But if Canberra only play the Sounds for Login and Logout that's the better way.

**Comment by ikeydoherty** [comment]
In Solus we have these files:

```
/usr/share/gdm/autostart/LoginWindow/libcanberra-ready-sound.desktop
/usr/share/gnome/autostart/libcanberra-login-sound.desktop
/usr/share/gnome/shutdown/libcanberra-logout-sound.sh
```

I think the autostart files are the issue? There are a bunch of files that look like they **might** do it.
