### ISSUE TITLE
Tooltips contents offset the first time they are opened

### ISSUE THREAD

**Issue by nextgensparx** [solus-project/budgie-desktop#1303]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4

**The issue encountered**

When any tooltip opens for the first time, its text is offset about halfway-down and thus unread-able.

![broken_tooltip](https://user-images.githubusercontent.com/19307714/35485002-7b148cd0-0461-11e8-8819-4227e658f7a3.png)

After moving the mouse away and back, the issue is gone. This only happens to the first tooltip hovered on after startup.

![broken_tooltip2](https://user-images.githubusercontent.com/19307714/35485003-7ca700aa-0461-11e8-8c7e-fac0cad854c7.png)

**Steps to reproduce the issue**

Put your mouse over any graphical element with a tooltip. 
A restart may be required beforehand.

**Comment by JoshStrobl** [comment]
Unable to reproduce this issue and it appears to be related to a specific application or GTK itself, as opposed to Budgie (which isn't responsible for drawing those tooltips).

**Comment by nextgensparx** [comment]
It's not related to specific applications (from my testing) and doesn't happen on other DEs (like GNOME) but it could still be a GTK issue.
