### ISSUE TITLE
[FEATURE REQUEST] Possibility to remove all bars

### ISSUE THREAD

**Issue by shizonic** [solus-project/budgie-desktop#1312]
Is it possible to add the possibility to remove all bars? Right now I do have to have at least one at the top, bottom, left or right...

 I want to use polybar instead of the built in one. That's why I want to remove all the panels of budgie... and the autohide option does not hide the panel by default.

**Comment by fossfreedom** [comment]
If you are referring to the panels - you can set the panel to autohide via budgie-settings - panel settings

**Comment by shizonic** [comment]
I know but this works only if I choose the built in theme...

**Comment by fossfreedom** [comment]
hmm?  works here on my desktop - not using the built in theme.

**Comment by shizonic** [comment]
hmm ... which distro and which theme?

**Comment by fossfreedom** [comment]
Ubuntu Budgie - tested with Arc and Adapta - works fine - just maximise a window and the top bar autohides.

**Comment by shizonic** [comment]
Thanks. But this isn't what I want. I want to use polybar instead of the built in one. That's why I want to remove all the panels of budgie...

**Comment by fossfreedom** [comment]
Tidied up comment list now that the crux of the issue has been determined.

**Comment by shizonic** [comment]
Thanks a lot!

**Comment by JoshStrobl** [comment]
Closing, no plans on supporting this.
