### ISSUE TITLE
Tap-to-click problem

### ISSUE THREAD

**Issue by gersonjferreira** [solus-project/budgie-desktop#1313]
I'm running the Budgie Destkop on Manjaro Linux with Parcellite on the system tray. When I click (full click either with the touchpad or mouse), Parcellite works well. However, if I simply use the tap-to-click feature of the touchpad, the clipboard list only blinks (opens and closes immediatelly).

This does not happen to other apps in the tray. I wonder if this is a Parcellite problem, or a Budgie problem. So I'll post this message in both forums.

budgie-desktop v10.4-8-gff09a510

**Comment by JoshStrobl** [comment]
As these applications are responsible for their own XEmbed trays, this would be a Parcellite issue.
