### ISSUE TITLE
Add support to display via a lightdm based greeter to show the selected user chosen wallpaper

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1326]
Issue raised from here https://github.com/linuxmint/slick-greeter/issues/94#issuecomment-365616160

Applies to lightdm v1.25.2 and later

Recent changes in [lightdm](https://github.com/CanonicalLtd/lightdm/commit/6015bce25f241e7580c03594d846769f8236232f) now support the capability of a lightdm greeter (such as slick greeter) to display the wallpaper of the current highlighted user on the greeter.  Its a bit of bling that was previously limited to Ubuntu based distro's.    It didnt apply to encrypted home-drives I understand.

The changes to lightdm (according to the maintainer) utilise upstream AccountsService changes and thus enable all distros to benefit from this capability.

It is entirely up-to the distro itself whether to enable/disable the capability via the lightdm config file.

The suggestion here is to add the callout to the dbus service mentioned in the linked issue.  First off the blocks were linux mint with cinnamon.  Implementation was via their [settings-damon](https://github.com/linuxmint/cinnamon-settings-daemon/commit/63f501e60cbff2a8989e29dfb65018db8269e0a7) by calling gnome_bg_set_accountsservice_background whenever the gnome wallpaper settings is changed and also when first drawing the background (I think).

@ikeydoherty mentioned possibly adding such capability to budgie-daemon.

Speculation also on the budgie implementation: 

Maybe also to https://github.com/budgie-desktop/budgie-desktop/blob/master/src/wm/background.vala ? i.e. line 70 for the change event on settings and maybe the function at line 206 - both add the same callout to gnome_bg.set_accountsservice_background (I'm assuming that isnt a cinnamon specific function) ?

**Comment by ikeydoherty** [comment]
Pretty sure thats yet-another-ubuntu-patch :) So we'll need to investigate what its actually doing and replicate the functionality

**Comment by fossfreedom** [comment]
okey-dokey - just recording this here.  To change the lightdm wallpaper this format of dbus call is required:

    dbus-send --system --print-reply --dest=org.freedesktop.Accounts /org/freedesktop/Accounts/User$(id -u) org.freedesktop.DBus.Properties.Set string:org.freedesktop.DisplayManager.AccountsService string:BackgroundFile variant:string:/full/path/to/jpg/or/empty/string

**Comment by Coeur-Noir** [comment]
« Its a bit of bling » a bit yes but very convenient when dealing with many machines with many users on each.

FWIW it's also implemented in Xubuntu 18.04
