### ISSUE TITLE
Application entry appearing twice on the main menu with option "Show Headers" turned off

### ISSUE THREAD

**Issue by ehepp** [solus-project/budgie-desktop#1327]
Solus version: 3
Budgie version: 10.4

The issue:
"LibreOffice Draw" appears twice on the "All" category of the main menu.

How to reproduce the issue:
Open the main menu, and while on the "All" category, roll down until you find this application entry twice.

**Comment by ehepp** [comment]
I've changed the title since it makes sense for an app to appear more than one time on the main menu if there are headers specifying the categories to which the app belongs. But, it's not the case on a headerless situation, when an app simply appears to be duplicated without reason.

**Comment by samuelcecilio** [comment]
Same issue here, Solus 3.9997. Font Viewer, Font Manager and LibreOffice.

![2018-05-22 10-36-34](https://user-images.githubusercontent.com/30150045/40365938-3c9a00c6-5dac-11e8-8caa-648026ca619d.png)

![2018-05-22 10-37-44](https://user-images.githubusercontent.com/30150045/40365942-3e4107e4-5dac-11e8-8f99-8319ad87a013.png)
