### ISSUE TITLE
Which license you have for this file?

### ISSUE THREAD

**Issue by rilian-la-te** [solus-project/budgie-desktop#1328]
**Operating System**: Any
**Budgie version**: commit 897f9288d1e486b4cb7bcbe38a88fe7c15cfb7e5

**The issue encountered**

I have some question about budgie-desktop licensing (LGPL vs GPL).

**Steps to reproduce the issue**
Read a file headers and README, look to meson log and resulted builds.

In README you states than

> The shared libraries are available under the terms of the LGPL-2.1, allowing developers to link against the API without any issue, and to use all exposed APIs without affecting their project license.

> The remainder of the project (i.e. installed binaries) is available under the terms of the GPL 2.0 license. This is clarified in the headers of each source file.

But, AFIAK, applets of panel or some other shared libraries is licensed under GPL.
1. https://github.com/budgie-desktop/budgie-desktop/blob/897f9288d1e486b4cb7bcbe38a88fe7c15cfb7e5/src/appsys/AppSystem.vala
2. https://github.com/budgie-desktop/budgie-desktop/blob/master/src/applets/icon-tasklist/IconTasklistApplet.vala
3. https://github.com/budgie-desktop/budgie-desktop/blob/master/src/applets/icon-tasklist/Buttons.vala

It is GPL licensed in headers, but it is a shared libraries. I want to ask you to give this files LGPL permissions, if possible.

**Comment by JoshStrobl** [comment]
It's licensed under GPL-2.0. Whether it's GPL-2.0-only or GPL-2.0-or-later is something I need to converse with @ikeydoherty about.

However, I do not appreciate you stripping out **our** copyright in "your" icon tasklist (as shown [here](https://gitlab.com/vala-panel-project/vala-panel/commit/aa92b4f74b2ce892fa35e40e7ce3f86e47647e84)), and I'm fairly certain that is a violation of the license. I fully expect you to add it back in a future commit.
