### ISSUE TITLE
Contextual menu task bar: More used options in the botton and more consistent menu

### ISSUE THREAD

**Issue by costales** [solus-project/budgie-desktop#1331]
Hi,

When you do a right click with mouse in an app of the task bar, the contextual menu is different from the bottom all the times.

I'm using this way for closing apps (right click + close contextual menu), because it's less movement with the mouse.

Another example: pin/unpin is the most important option (because is in the bottom) and IMHO not so must users will pin/unpin every time, then it should not be the bottom (near option of the mouse)

Propose: 

- Close as 1st (bottom) option in the menu.
- Extra menus (as open in new tab/window of Chromium) in the top for keep consistence of the menu all the time.

Best regards and thanks.
![screenshot from 2018-02-15 23-12-11](https://user-images.githubusercontent.com/5886786/36284203-22dafabe-12a7-11e8-8720-4ad4d5b1fe03.png)
![screenshot from 2018-02-15 23-12-47](https://user-images.githubusercontent.com/5886786/36284204-2302be0a-12a7-11e8-9851-6c7a9175bf45.png)
![screenshot from 2018-02-15 23-12-59](https://user-images.githubusercontent.com/5886786/36284205-232821cc-12a7-11e8-9d79-3c8ed9062586.png)
![screenshot from 2018-02-15 23-13-09](https://user-images.githubusercontent.com/5886786/36284206-234b46e8-12a7-11e8-96b6-40f6bead915e.png)

**Comment by JoshStrobl** [comment]
Closing since this was rewritten to be an IconPopover, where the layout is more consistent.
