### ISSUE TITLE
Automatic suspend notifications shouldn't be persistent in Raven

### ISSUE THREAD

**Issue by bwat47** [solus-project/budgie-desktop#1354]
If you have automatic suspend enabled in gnome settings | power, when the machine is about to suspend automatically there's a warning notification.

This notification is persistent in the raven menu (even after you resume from the automatic suspend).

this is pretty annoying, because over time the raven notifications becomes filled with tons of automatic suspend warnings

**Comment by Snuggle** [comment]
Just to add to this - I get a lot of random notifications from things like Discord or Telegram while I'm doing stuff on my computer. I'd love a feature that would prevent notifications from being "Unread" if I'm actually at my computer and reading them.

Perhaps this could be a setting in _Budgie Desktop Settings_?

**Comment by bwat47** [comment]
@Snuggle It looks like a do not disturb function was already merged: https://github.com/budgie-desktop/budgie-desktop/pull/1167

**Comment by Snuggle** [comment]
Oh sweet! Thanks for letting me know. :smile_cat:
