### ISSUE TITLE
Keyboard shortcuts does not work in Budgie Menu

### ISSUE THREAD

**Issue by IgorWalkers** [solus-project/budgie-desktop#1357]
**Operating System:** Manjaro Linux 17.1.6
**Budgie version:** v10.4-8-gff09a510

**The issue encountered**
When Budgie Menu applet is open none of the keyboard shortcuts is working. I tried to change keyboard layouts while searching for app.

**Steps to reproduce the issue**
Just open Budgie Menu applet.

**Comment by IgorWalkers** [comment]
I am pretty sure my issue is duplicate of #1306 but it`s closed but not fixed.

**Comment by JoshStrobl** [comment]
Duplicate of #420.
