### ISSUE TITLE
Tray icons larger than the others when changing panel size

### ISSUE THREAD

**Issue by leandromqrs** [solus-project/budgie-desktop#1361]
**Operating System**: Solus 3.999
**Budgie version**: Budgie 10.4

**The issue encountered**
Some of the tray icons are disproportionate when placing the panel with size 37+

**Steps to reproduce the issue**
In the panel settings, when setting the panel size to 37 or more, the tray icons are larger than the others regardless of where the panel is located.
Example:
Size 36 or less work correctly
![image](https://user-images.githubusercontent.com/16769222/38125280-c170f038-33be-11e8-8eb3-ba297bb52b04.png)
Size 37 or more
![image](https://user-images.githubusercontent.com/16769222/38125320-f68aab2e-33be-11e8-971a-6e4b1febcd36.png)
Others location with size 37
![image](https://user-images.githubusercontent.com/16769222/38125350-2001ef3a-33bf-11e8-9320-ddb53f06f460.png)

The system tray icons remain the same size, which presents a somewhat uncomfortable appearance regarding the size and organization of the tray icons

**Comment by sid350** [comment]
Any workaround on this?

**Comment by FelschR** [comment]
Some of my icons look way too large on with default Budgie settings (size of 39):
![budgie-tray-icoins](https://user-images.githubusercontent.com/3314323/50380109-56d47480-065d-11e9-853d-9a7786ef4e84.png)

**Comment by serebit** [comment]
This is an issue with the X tray system in and of itself, and not an issue with Budgie. Budgie doesn't control how these icons are sized within their icon images, only how those images themselves are sized and laid out. Some icons will appear to be larger than others, but I can personally assure you that the *icon images themselves* are all sized appropriately. 

As such, if you have an issue with how a particular icon is sized, then you should take it up with the developers of that application.
