### ISSUE TITLE
I can't open the setting

### ISSUE THREAD

**Issue by LoveChocoCat** [solus-project/budgie-desktop#1373]
**OS**
Anarchy Linux (Arch)
**Budgie Version**
budgie-desktop v10.4-42-g298b9ae4
**Problem I encountered**
I can't open budgie desktop setting after installing 

> budgie-desktop-git

from AUR.
Before that i have installed budgie from the official arch repo not the AUR then i remove it using 

> pacman -R budgie-desktop

and install the new budgie with AUR and now I can't open the setting. Should I reinstall it?
**Step to reproduce the problem**
just open the budgie desktop setting and nothing happened

**Comment by JoshStrobl** [comment]
Unable to reproduce under Solus. As we're not responsible for the packaging on Arch, I'd suggest filing this with the respective packager.
