### ISSUE TITLE
Super button opens system tray's icon sub-menu

### ISSUE THREAD

**Issue by NZamp** [solus-project/budgie-desktop#1378]
**Operating System**: Manjaro
**Budgie version**: v10.4-34

So here we go: When the cursor points to an item of the system tray, if the super button is pressed to open up the Brisk menu, it will instead open the menu of the item which the cursor points to, just as it was clicked with the mouse. 

I am not sure if this is the intended behaviour, but I'm reporting this here just to make sure you're informed about it.

**Comment by JoshStrobl** [comment]
This is intended behavior. You notice that if you open the **Budgie Menu** then proceed to hover your mouse over any applets which would have a Budgie.Popover, it will show those.

**Comment by NZamp** [comment]
I am not sure if you understood the case exactly as I intended to. 

If the mouse is on top of the volume icon, pressing the super key will open up the sound submenu. Not the brisk menu.

**Comment by JoshStrobl** [comment]
I do understand the case, your mouse is over the volume icon, therefore it will open the popover associated with that.

**Comment by BryceBeagle** [comment]
Is there a way to disable this feature currently? I don't find it very intuitive. I expect a single outcome when I press the super key (Brisk menu opens) but sometimes, depending on the location I left my cursor to rest, something different happens and I need to go back to my mouse to move the cursor.

**Comment by NZamp** [comment]
Okay then, I'm glad that it's the intended behavior.

**Comment by JoshStrobl** [comment]
> Is there a way to disable this feature currently?

At this moment in time, no. It's not something I'm opposed to having as a feature though.

> Brisk menu opens

Budgie Menu. Brisk Menu is on MATE.

**Comment by NZamp** [comment]
That confused me too when I was trying to search for something in the menu but the cursor was hovering an applet, which's menu eventually opened up when I pressed super.

**Comment by BryceBeagle** [comment]
Sorry, my bad for the terminology. I was unaware of the word for it and just used the term OP used for it.

As far as this being a feature in the future, is there an official way to submit feature requests for tracking?

**Comment by JoshStrobl** [comment]
Yea, you can file a feature request for it on this issue tracke and just remove most of the templated "New Issue" text. It'll be labeled as an enhancement (to disable showing popovers on rollover).
