### ISSUE TITLE
Window seems to disappear according to Budgie Panel

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#1383]
**Operating System**: Solus 3.99999999999
**Budgie version**: Budgie 10.4

**The issue encountered**
This following seems to primarily happen to Visual Studio Code windows. I have not found this issue in other applications.

Open Visual Studio Code windows seem to disappear from Budgie Panel. They show an open state, but then suddenly lose their open visual indicator. Upon clicking the VSCode icon again (which I keep in my icon tray/favorites) VSCode will either take ~1 second to present itself on my screen or start a completely new instance. Upon Alt-Tabbing, the original VSCode instance is still there. @JoshStrobl I know you use VSCode or at least used to. Have you experienced something similar (granted you use GNOME)? I want to pin this to either a VSCode or Budgie issue.
 ...

**Steps to reproduce the issue**
Currently unknown at this time. This happens fairly regularly (and randomly) when I am switching between Firefox/Slack/Spotify on a fairly regular basis. Restarting VSCode seems to fix the issue. There is no way to fix the problem without restarting VSCode from what I can figure out.
 ...

**Comment by acoronado1234** [comment]
I have the same problem, except that when I attempt to resume my VSCode session it puts me on the welcome screen.

**Comment by goldencut** [comment]
Not sure if same bug but seems connected. When I 'Favorite' an app (eg 'Settings') to the Panel then the app's icon immediately disappears from Panel, app stays running. Icon is shown Favorited on Panel after reboot.
