### ISSUE TITLE
Dismiss notification when external medium is unplugged

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1384]
It would be a bit more conveient if the "Ready to be unplugged" notification upon unmounting an external drive would be automatically dismissed when the drive is removed. At the very least, the notification length could be increased so that there is more time to dismiss it, as more often than not the notification gets sent to the drawer and then has to be manually removed, creating useless extra work.

**Comment by bwat47** [comment]
Related: https://github.com/solus-project/budgie-desktop/issues/1354 

In general, it seems like budgie never dismisses notifications that really shouldn't be totally persistent like these two examples

**Comment by JoshStrobl** [comment]
Should be resolved with 4474723405727ac0ffed39d79f89f407f839535d
