### ISSUE TITLE
[Feature Request] Sound Mixer

### ISSUE THREAD

**Issue by hazelnot** [solus-project/budgie-desktop#1385]
Budgie should include a way to control the volume per-app. It's inconvenient to have to dig through app/game settings to get to the volume controls every time you want to change the volume of a specific program. It could probably be implemented similarly to the [Advanced Volume Mixer](https://extensions.gnome.org/extension-data/screenshots/screenshot_212_6.png) GNOME extension.

I took the liberty of creating a mock-up as well:

![group 1](https://user-images.githubusercontent.com/10992973/39251945-70691fb0-489c-11e8-808f-49b934c7f7f0.png)

I realize I'm not using the Arc theme, but I had to boot into Windows to actually design this and the screenshot I took as a base was using Materia.

**Comment by fossfreedom** [comment]
I'm presuming the "mixer" part is an extension to the existing Raven sound controls - not a panel applet?

**Comment by hazelnot** [comment]
It's technically an extension to the volume control in the panel, but the mixer could be applied to the Raven sound controls, either exclusively or in addition to the panel controls.

I'm just looking for a simple way to access pre-app volume controls.

**Comment by Remmus2k** [comment]
I've been looking forever for this feature too. Maybe someone could make a python applet or plug in that adds this.

**Comment by JoshStrobl** [comment]
Resolved with a6a6ef353a29c71d01ab1a624c23ec9f594a2796
