### ISSUE TITLE
I can't open Budgie Desktop Settings.

### ISSUE THREAD

**Issue by Nanotwerp** [solus-project/budgie-desktop#1389]
I currently use Solus 3.999 Unstable, and budgie-desktop v10.4-43-gc5df42b2. A few days ago, I was not able to log into Solus, as it kept sending me back to the login screen when I inserted the right password. After a few updates, login was possible, but the budgie panel was broken: all of my widgets and pinned applications were gone, and the panel floated, exposing a portion of my wallpaper.

After a few more updates, the panel works, but I can't open the Budgie Desktop Settings. When I try to, the panel disappears for a little less than a second, and appears again. I'm sent back to the login screen if I try too many times.

gdb results:

Starting program: /usr/bin/budgie-desktop-settings 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff7921700 (LWP 4157)]
[New Thread 0x7ffff7120700 (LWP 4158)]
[Thread 0x7ffff7921700 (LWP 4157) exited]
[Thread 0x7ffff7923500 (LWP 4153) exited]
[Inferior 1 (process 4153) exited normally]

**Comment by fossfreedom** [comment]
As I understand the unstable channel is preparing for gnome 3.28. Think you really should either be on the stable channel or reporting this on the Solus phabricator issue tracker.

**Comment by fossfreedom** [comment]
@Nanotwerp can we close this now with the very latest changes (Solus 3.9996)  that has been released?

**Comment by Gitimo** [comment]
@fossfreedom I am having the same symptoms with a fresh install of ubuntu-budgie 18.04, maybe related?

I'll search the forums a bit more and create a new issue if necessary

**Comment by Amathadius** [comment]
Same symptoms on Archlinux. I can't open budgie-desktop-settings and sometimes my session log out.

**Comment by alunux** [comment]
@Amathadius Do you use budgie-desktop-git from AUR?

**Comment by Amathadius** [comment]
Yes

**Comment by alunux** [comment]
@Amathadius You need to edit the PKGBUILD, at build() section. Change `meson build --prefix=/usr --sysconfdir=/etc --buildtype plain` to `meson build --prefix=/usr --sysconfdir=/etc --buildtype plain -Dwith-desktop-icons=none`
