### ISSUE TITLE
Icon tasklist grouping broken with Libreoffice

### ISSUE THREAD

**Issue by clauded** [solus-project/budgie-desktop#1405]
**Operating System**: e.g. Solus 1.3

**Budgie version**: i.e. Budgie v10.4-62-g269740af

**The issue encountered**
Icon tasklist grouping broken with Libreoffice 

**Steps to reproduce the issue**

- Ensure no libreoffice instance running
- Start libreoffice-writer from Budgie menu: white LO icon is displayed in panel (this icon cannot be pinned to panel)
- From LO, choose File->New->Text document: blue LO-writer is displayed in panel (this icon can be pinned)
- Pin the blue LO-writer icon
- Close all LO documents
- Open LO from pinned icon: white LO icon will appear (blue icon will blink)

So the first instance launched of LO will always display that white icon so grouping only works for subsequent instances.

Plank doesn't have this bug BTW.

Related bug: https://github.com/budgie-desktop/budgie-desktop/issues/817

**Comment by ikeydoherty** [comment]
Please actually fill out the OS and version fields. Also I'm pretty sure this is one of about 20 duplicates that has already been resolved.

**Comment by clauded** [comment]
It's not resolved as of Kernel: 4.16.7-66.current x86_64 bits: 64 Desktop: Budgie 10.4-70-g15c960cc

My feeling is that it takes too long to load LO so the default icon is used.

![image](https://user-images.githubusercontent.com/4673125/39673863-c4909cda-5111-11e8-812c-0b161ed41c0c.png)

https://imgur.com/a/WjvnhuH

**Comment by Coeur-Noir** [comment]
>  Start libreoffice-writer from Budgie menu: white LO icon is displayed in panel (this icon cannot be pinned to panel)
fwiw : I can't find LO-startcenter in App Menu here on Ubuntu-Budgie 18.04 but able to launch it from terminal. And also able to pin that instance in panel, permanently.

**Comment by JoshStrobl** [comment]
@Coeur-Noir Sounds more like an issue with Ubuntu's packaging than anything. On Solus we have "LibreOffice" as a desktop entry, which upon clicking presents the window to select what you want to open (Calc, Draw, Writer, etc.).

**Comment by Coeur-Noir** [comment]
You're most probably very right @JoshStrobl ;-) Or the app-menu widget can't see the .desktop file which is actually in /usr/shar/applications
![ubudgie_1804_lostartcenter](https://user-images.githubusercontent.com/1895947/44497623-ca984d80-a67a-11e8-8508-29b91e4eae2d.png)
My comment was answering to the « this icon cannot be pinned to panel » part of @clauded 's description. Here I can pin the _LO « startcenter »_ in panel.
![ubudgie_1804_lostartcenter_pinned](https://user-images.githubusercontent.com/1895947/44497645-da179680-a67a-11e8-8ee2-fe44bc242c3b.png)
But I have same behavior, anything launched from LOstartcenter keeps white icon, one can expect icon changed for matching app' ( writer, calc… but no longer startcenter ).
![ubudgie1804_2icons_for_lowriter](https://user-images.githubusercontent.com/1895947/44498388-73947780-a67e-11e8-8eff-101fe0e2a087.png)

**Comment by tristan957** [comment]
I think this is the issue tracking this bug. Just to update the ticket, the problem still exists on `budgie-desktop v10.4-85-g36667bcb`
