### ISSUE TITLE
Two windows of the same application is not restored by clicking on the icon on the panel

### ISSUE THREAD

**Issue by abhishek-raj** [solus-project/budgie-desktop#1409]
Operating System: Solus 3.9995
Budgie version: v10.4-62-g269740af

**The issue encountered**

 After updating Solus this week, Budgie now clubs two windows of the same application into a single icon on the panel. When a application with more than two window is minimized using the icon, all the windows are minimized of the application but then clicking on the icon doesn't restore the other windows, but only one of the windows. Only way to access those windows is by pressing alt+tab.
Window grouping is on.

**Steps to reproduce the issue**
Open two windows of same application like firefox or terminal.
Click on the icon displayed on the panel.
All windows are minimized.
Click on the icon again, only one window is restored.
No way to restore the other windows without alt+tab or right clicking on the icon.

**Comment by abhishek-raj** [comment]
Files also keep on flickering #1396

**Comment by lmacoretta** [comment]
I have the same problem. Also the new programs that I open and minimize, do not go to the taskbar, the only way to open them by tapping alt + tab.

**Comment by cybre** [comment]
You can access the rest of the windows by right clicking the application icon in the tasklist and selecting a window from the list or simply by scrolling over the icon.
