### ISSUE TITLE
Wrong ja_JP translation for Clock Applet setting

### ISSUE THREAD

**Issue by ykhrito** [solus-project/budgie-desktop#1413]
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: Budgie 10.4

Japanese translation for "Show seconds" setting's label of Clock Applet is incorrect.

![clock_settings_ja_jp](https://user-images.githubusercontent.com/1698606/39612742-fa380f1a-4f9c-11e8-976c-177503ef3caa.png)

"病を表示する" should be "秒を表示する".

(I've requested to join a team on transifex, but if it's not going to be approved,  I'd appreciate if someone correct it.)

**Comment by ikunya** [comment]
Thank you for your report. I've fixed it.
