### ISSUE TITLE
Cannot open second window for terminal applications

### ISSUE THREAD

**Issue by aparadis** [solus-project/budgie-desktop#1417]
**Operating System**: Debian Buster (testing)
**Budgie version**: 10.4+git20171031.10.g9f71bb8-1.2

**The issue encountered**
When pinning a terminal application to the taskbar, I cannot spawn additonal instances of this application use right-click -> New Window, as the menu is missing

**Steps to reproduce the issue**
Open and pin one of these applications:  gnome-terminal, xfce4-terminal, xterm, mate-terminal.
Right-click pin icon and look for "New Window", menu is missing

The same steps work with other applications (Chrome, Files manager) and also with gnome-shell.
 
This problem was also filed downstream on the Debian BTS (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897570)

**Comment by clauded** [comment]
As a workaround, try this:
copy /usr/share/applications/org.gnome.Terminal.desktop to .local/share/applications/org.gnome.Terminal.desktop

And add these lines to the file:

Actions=new-window
[Desktop Action new-window]
Name=Open a New Window
Exec=gnome-terminal

I guess that Budgie don't take into account "X-GNOME-SingleWindow=false"....

**Comment by aparadis** [comment]
Yes it does work that way.

I also looked at xfce4-terminal's .desktop, and it doesn't have any mention of the X-GNOME-SingleWindow parameter, yet it does have a "New Window" menu in gnome-shell.

```
(Excluded Name/Comment/GenericName entries)
Exec=xfce4-terminal
Icon=utilities-terminal
Terminal=false
Type=Application
Categories=GTK;System;TerminalEmulator;
StartupNotify=true
```

Not quite sure what determines whether an app gets the New Window item or not, without having to add it manually to the .desktop file

**Comment by JoshStrobl** [comment]
Validated that issue is resolved in git with new IconPopover. If the issue persists, feel free to let me know.

**Comment by aparadis** [comment]
Is this slated to hit a specific release/version number, and if so when
would that be?
