### ISSUE TITLE
System Tray applet in the Top Panel doesn't show after sleep

### ISSUE THREAD

**Issue by robetus** [solus-project/budgie-desktop#1419]
Ubuntu 18.04

When I close the lid of my laptop and reopen it the System Tray applet does not show in the top panel again unless I change the size of the top panel in the settings. After a restart it shows, this only happens when I close the lid and then open it again and it only happens with the System Tray applet in the Top Panel.

Anyone know what I can try to fix this?

**Comment by JoshStrobl** [comment]
May be resolved with #1998
