### ISSUE TITLE
Feature Request: quarter-screen tiling

### ISSUE THREAD

**Issue by matt-della** [solus-project/budgie-desktop#142]
So far only Cinnamon and Compiz (perhaps KDE as well) seem to have the ability to tile windows to a quarter of a screen when dragging them into a corner, but I think it's a very underrated feature that really adds a level of polish to any DE that implements it. It would probably be helpful to add keybindings for quarter-screen tiling as well, but that's not as important.

**Comment by Justinzobel** [comment]
This is a planned feature for the WM.

**Comment by ikeydoherty** [comment]
This will come directly from Mutter support in 3.20 hopefully, but not something we implement ourselves
