### ISSUE TITLE
Icon Task list applet couldn't distinguish between chrome-apps

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1425]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4-70-g15c960cc

**The issue encountered**

Icon Task list applet couldn't distinguish between chrome-apps(including google-chrome) when window grouping is enabled, it is almost as if it can't distinguish between say Google+ and Google Photos. If you open Google+ first and Google Photos second both act as one(u can access both Google+ and photos from google+ icon), even if u have closed one, both the icons would be still there until u close it all.

**Steps to reproduce the issue**

enable window grouping, open two or more chrome-apps

**Comment by oakbrad** [comment]
I am having the same issue. I use the Chrome Hangouts app.

If I open Chrome and Hangouts, closing Chrome will close both applications.

If I open both and close Hangouts, the Hangouts icon remains but it shows the window grouping and options for Chrome.

**Comment by FunkyloverOne** [comment]
This issue becomes even more annoying when you're screen sharing through Hangouts, and eventually you cannot access your normal chrome window via task list applet. :c

**Comment by dan-dr** [comment]
Same here. 
![screenshot from 2018-08-23 01-06-00](https://user-images.githubusercontent.com/6669808/44493488-cb2be680-a670-11e8-8de3-249f09367699.png)

clicking on either Chrome or Videostream (the orange icon) minimizes both windows.

**Comment by FelschR** [comment]
With the update today on the stable channel my Chrome + PWAs still behave incorrectly:
![budgie-chrome-issue](https://user-images.githubusercontent.com/3314323/50710656-d4d84880-106b-11e9-9f8e-3d5d2edce9ea.png)

They selection indicators is shown for all all apps when one is selected.
And e.g. when I use the scroll wheel while hovering over one of the apps it toggles between all the Chrome windows including the apps.

**Comment by FelschR** [comment]
Other Chromium-based browsers like Brave still have the original issue.
The recent code changes seems to be specific to Chrome. And even with Chrome it's not working for me properly.

@JoshStrobl could you reopen the issue and perhaps have a look at this again?

**Comment by FelschR** [comment]
@JoshStrobl any update?

**Comment by FelschR** [comment]
I just noticed that the same problem appears when I have multiple wine applications open (started via Lutris).

**Comment by DonatCallens** [comment]
Same here. When I save a web page as a shortcut in Google Chrome, I cannot pin the icon in the task bar, unless I enable windows grouping in the panel first. (latest version of Solus 4 freshly installed)

**Comment by dan-dr** [comment]
Still not working for me. While the apps have separate icons, clicking the icon minimizes all the chrome windows + all the chrome apps.
Help us lord @JoshStrobl

**Comment by dan-dr** [comment]
FYI Gnome Web works well with "Web sites as apps" so if you have chrome apps which are simple wrappers around websites it's a good solution until this is fixed.

**Comment by dan-dr** [comment]
We probably need this in https://github.com/solus-project/budgie-desktop/blob/master/src/applets/icon-tasklist/DesktopHelper.vala:
```vala
	    public GLib.List<unowned Wnck.Window> get_stacked_for_classname(string class_name)
    {
        GLib.List<unowned Wnck.Window> list = new GLib.List<unowned Wnck.Window>();
        screen.get_windows_stacked().foreach((window) => {
            if (window.get_class_group_name() == class_name && !window.is_skip_tasklist()) {
                var workspace = window.get_workspace();
                if (workspace == null) {
                    return;
                }
                if (workspace == get_active_workspace()) {
                    list.append(window);
                }
            }
        });

        return list.copy();
    }
```

Then in https://github.com/solus-project/budgie-desktop/blob/d80b745bd25489751b0290050566b388598b4271/src/applets/icon-tasklist/IconButton.vala#L882

Replace with
```vala
GLib.List<unowned Wnck.Window> list;

if (this.first_app.group.has_prefix("chrome-") || this.first_app.group.has_prefix("google-chrome")) // is chrome or chrome app
{
    list = this.desktop_helper.get_stacked_for_classname(this.class_group.get_name());
}
else {
    list = this.desktop_helper.get_stacked_for_classgroup(this.class_group);
}
```

**Comment by bsucker98** [comment]
Unfortunately even after the commit `84a672b`, this issue still exists :|

**Comment by Poltergeisen** [comment]
Can we re-open this? I'm still having this issue

@JoshStrobl 

![image](https://github.com/solus-project/budgie-desktop/assets/44731113/95e28d7c-bd7e-452d-adb6-f51b7d163bdd)
