### ISSUE TITLE
VirtualBox icon disappears from the panel after a fraction of a second

### ISSUE THREAD

**Issue by Staudey** [solus-project/budgie-desktop#1427]
**Operating System**: Solus 3.9996 ;)
**Budgie version**: v10.4-70-g15c960cc

**The issue encountered**
After launching Oracle VirtualBox the icon shows up for less than half a second in the panel and then just disappears. It's still visible in the ALT+TAB app switcher.

**Steps to reproduce the issue**
1. Install VirtualBox from the Solus repository.
2. Launch VirtualBox.
3. Observe the panel.

System graphics information:
Graphics:  Card: Intel Skylake GT2 [HD Graphics 520]
           Display Server: x11 (X.Org 1.19.6 )
           drivers: intel (unloaded: modesetting,fbdev,vesa)
           Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           version: 4.5 Mesa 18.0.2

Note: I just saw someone else mention the same issue on IRC, so it doesn't seem to be specific to my system.

Note 2: The icon of a launched VM doesn't disappear. Neither does the icon of the information dialogue that appears when you launch a VM in "Scale" mode.

**Comment by bja-au** [comment]
Have exactly the same problem now for a while :(

**Comment by mattiatomeo** [comment]
I have the same problem on my system

**Operating System**: Solus 3.9996
**Budgie version**: v10.4-70-g15c960cc

I have an Nvidia GTX 960 with the nouveau driver

**Comment by sund0wn** [comment]
I confirm I experience the same behaviour. 
Solus 3.9999

**Comment by ouned** [comment]
Same here. When the window of the virtualbox manager shows some modal messgebox it suddenly appears how it is expected.

in contrast, gnome builder shows two icons even though it should only show a single one.

Something must be wrong in how budgie handles that.

**Comment by tristan957** [comment]
This is still a problem as of 9/6/2018

**Comment by Gaming4LifeDE** [comment]
I have the same issue: Solus 3.9999  
budgie-desktop v10.4-85-g36667bcb

**Comment by lorenzgillner** [comment]
I have the exact same issue. After starting VirtualBox, the panel icon appears and then suddenly disappears. Launching the "Virtual Media Manager", for example, from the main window afterwards brings back the icon (plus a second one for the VMM).
I'm on Solus 4.0 with Budgie 10.5.

**Comment by smccuan** [comment]
Same issue with fully updated Solus Budgie as of this moment.

**Comment by ruinb0w** [comment]
same issue
---
manjaro-budgie newest
budgie-desktop 10.5

**Comment by coreyhuinker** [comment]
Same issue. Ubuntu 19.04, ubuntu-budgie-desktop 0.45

**Comment by xXR3H4NXx** [comment]
Yep. Still happens to me as well. Not just with VirtualBox, but with other programs as well. Ex. I open 2 windows of libre office, close one, and the whole icon disappears. Turning off grouping of icons fixes it for me but I really want grouped icons.

**Comment by coreyhuinker** [comment]
@xXR3H4NXx - If I had to guess, the commonality between all those programs would be Java.

**Comment by machsix** [comment]
Same issue here. 
- Linux mach 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64 GNU/Linux.
- budgie-desktop 10.5-1
- The application is comsol multiphysics and it is indeed written in java

**Comment by Enkhiel** [comment]
Issue still persists 
Manjaro Budgie budgie-desktop 10.5.1-1

**Comment by jokinen77** [comment]
Same issue (Budgie-Desktop 19.04 and still 20.04) with Lenovo Legion Y520. Restarting (not sure if correct term) the desktop with command `nohup budgie-panel --replace &` fixes it temporarily if VirtualBox is already running.

**Comment by Jake-Mastandrea** [comment]
This issue still seems to occur for me...

**Comment by kp2401075** [comment]
I have same issue with Solus budgie latest version

OS: Solus 4.1 Fortitude
Budgie: budgie-desktop 10.5.1 (git-42201c183fccd7d65f143f8f6bb70bcf3bcaffd8)

**Comment by JRMA85** [comment]
Same issue here with latest version of Solus and Budgie. Will this ever be fixed? It’s been ongoing from 2018 😃

**Comment by P-A-L-A-D-I-N** [comment]
Same issue with current version of Solus Budgie: Open windows of VirtualBox disappear and there are no more "dots" under the icon in the task bar when an instance of VB is running. 

The icon itself does not disappear since I made it one of my favorites.

Maybe good to know: The problem seems to appear after installing the guest expansions, not before.
