### ISSUE TITLE
'Always on top' - no more :-(

### ISSUE THREAD

**Issue by bobblkabb** [solus-project/budgie-desktop#1428]
**Operating System**: e.g. Solus 3.9996
**Budgie version**: i.e. Budgie 10.4-70-g15c960cc

'Always on top' for pinning a window always in front of any others is missing.

**Comment by bobblkabb** [comment]
View apps work and some don't.

Work: Nemo, Gnome-Weather, Catfish, Gnome To Do, Peek
Don't work: QuiteRSS, Firefox, Caja, Terminal. LibreOffice, smtube, gimp

**Comment by Coeur-Noir** [comment]
![capture du 2018-06-28 21-13-11](https://user-images.githubusercontent.com/1895947/42055688-248fca86-7b18-11e8-8a92-bda35d0b8b8d.png)
This ?
It works as I could expect, as long as Firefox window is not maximized, which looks normal to my eyes.
Ubuntu-Budgie 18.04 here.
