### ISSUE TITLE
Dock on left/right trouble with multiple monitors

### ISSUE THREAD

**Issue by wennaspeedy** [solus-project/budgie-desktop#1440]
Budgie Ubuntu 18.04 LTS

Something went wrong with dock app stick on left or right side. I cant maximize window on the left/right monitor next to left/right dock. When I move dock to top or bottom everything is ok. I tried several dock apps like Docky, always the same.
![screenshot from 2018-05-17 09-07-57](https://user-images.githubusercontent.com/10447994/40161666-d913a8d4-59b1-11e8-9258-d442cc56e12f.png)

**Comment by Sethox** [comment]
I would like to add that Budgie Desktop Settings is not design for multiple monitors (as in it should). The reason it should be design for multiple desktops is so I can add the Applets on the other screens (as well as the panels), on that note a neat feature would be to save the settings or set up for multiple monitors (like a preview how it would look like and when setting it up it look "just like that"). I personally swift from multiple to single, so having the feeling of "it just works swiftly" is just a wish.

**Comment by Jacob-Vlijm** [comment]
Is this also with Budgie Panel or only with 3rd party panels/docks? This bug https://bugs.launchpad.net/plank/+bug/1755731 causes issues like yours. Budgie panel(s) should be fine If I remember well.

**Comment by JoshStrobl** [comment]
> Something went wrong with dock app stick on left or right side.

That's showing plank, not Budgie's IconTasklist with a "Dock" panel. Closing as it isn't a Budgie issue.

**Comment by wennaspeedy** [comment]
Yes, it is. Same with DOCK panel on left or right side!
