### ISSUE TITLE
Panel is not working with fresh install and update

### ISSUE THREAD

**Issue by stobiewan** [solus-project/budgie-desktop#1442]
Release:	3.9997
budgie-desktop v10.4-70-g15c960cc

Budgie panel has no task list, running applications have no icons. Budgie restarts if trying to add task list icons to bottom panel.

'journalctl -ae' gives this after trying to add Icon Task List to bottom panel :

May 19 23:49:35 mark_solus_desktop budgie-wm.desktop[915]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1a00015 (budgie-pan)
May 19 23:49:40 mark_solus_desktop budgie-wm.desktop[915]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1a00754 (Budgie Des)
May 19 23:49:56 mark_solus_desktop budgie-panel[933]: Settings schema 'com.solus-project.icon-tasklist' does not contain a key named 'grouping'
May 19 23:49:56 mark_solus_desktop gnome-session[753]: gnome-session-binary[753]: WARNING: Application 'budgie-panel.desktop' killed by signal 5
May 19 23:49:56 mark_solus_desktop gnome-session-binary[753]: WARNING: Application 'budgie-panel.desktop' killed by signal 5

 ...

**Steps to reproduce the issue**
Install solus from iso on solus website as it was two days ago,
run 'sudo eopkg update'

**Comment by JoshStrobl** [comment]
Closing issue seeing as we've issued a new ISO which features these updates to Budgie, avoiding any issues with schema upgrades or changes that might've caused this.
