### ISSUE TITLE
How can I upstream my applet?

### ISSUE THREAD

**Issue by yursan9** [solus-project/budgie-desktop#1448]
Sorry for my broken english. Regarding [Budgie's news](https://github.com/solus-project/budgie-desktop#re-merge-into-the-solus-project), I want to rewrite my simple [caffeine applet](https://github.com/yursan9/budgie-caffeine-applet), using vala, and make it part of Budgie's default applet. Ultimately, it is used to reduce the maintenance load of the applet itself, and makes it easier for people to contribute something to the applet.

Can I send a pull request or something? I guess I just need confirmation.

**Comment by michallepicki** [comment]
https://github.com/solus-project/budgie-desktop#re-merge-into-the-solus-project

> Please note that we will NOT accept pull requests to add Pythonic applets. Any applets should be written in either C or Vala.

**Comment by JoshStrobl** [comment]
"Please note that we will NOT accept pull requests to add Pythonic applets."

Seeing as the caffeine applet is written in Python, for it to be shipped as part of Budgie, it'd need to be rewritten in C or Vala. At such stage, you'd update `src/applets` and the respective Meson build files, and provide a pull request here in `budgie-desktop`

**Comment by yursan9** [comment]
Thank @JoshStrobl, I'll close this issue.
