### ISSUE TITLE
Cannot set "xml" Backgrounds

### ISSUE THREAD

**Issue by LeoIannacone** [solus-project/budgie-desktop#145]
Hi,

trying to set background XML background for "rotating" wallpapers I get this error:

(budgie-wm:31771): mutter-WARNING **: Failed to load background 'file:///home/l3on/.local/share/shotwell/wallpaper/wallpaper.xml': Unrecognized image file format

**Comment by efernandesng** [comment]
Hi,

this feature is not implemented yet :(
It's necessary read xml file and load the images(maybe create a cache system?)
I some time ago, I started the implementation of this features, but I never finished :(. Maybe do this in my spare time :)

**Comment by ikeydoherty** [comment]
We *could* use libgnome-desktop for this, but its an extra dep..

**Comment by efernandesng** [comment]
We can avoid use of libgnome-desktop. We can do something based on [gnome-bg-slide-show](https://git.gnome.org/browse/gnome-desktop/tree/libgnome-desktop/gnome-bg-slide-show.h). @ikeydoherty  what you think?

**Comment by ikeydoherty** [comment]
That is libgnomedesktop lol

**Comment by efernandesng** [comment]
I know.. I say, do something based, not copied :)

**Comment by ikeydoherty** [comment]
Oh xD Yeah we can make our own using libxml2 tbh. Virtually every system will be using libxml2 somewhere, so its a safe build dependency. Besides given the new modularity of our WM component, it'll be much easier for us now =)

BTW what do you think of the organisational changes to it so far? Not yet finished, obv.

**Comment by efernandesng** [comment]
I agree.. libxml2 is not a problematic dependence and resolves the problem. Also we can use GMarkup (part of GLib), its more light and we can avoid the libxml2 dependence. The advantage of libxml2 use, are the xml validation features.
What is your choise, libxml2 or GMarkup?

The new organisational, it is much better than the previous one. It's more readable and expansible :)

**Comment by ikeydoherty** [comment]
From personal preference, although libxm2 isn't as pretty to work with, GMarkup and similar APIs are very leaky. Common problem with glib.. While I concede its nice to reduce dependencies at build time.. is GMarkup worth it?

**Comment by efernandesng** [comment]
Maybe in this situation.
The xml background files aren't widely used and the files aren't complex.
In systems width few resources (ex: embedded systems), maybe this make the
difference.
If were needed read many xml files in features widely used, maybe libxml2
is best option.

Com os melhores cumprimentos,

*Emanuel Fernandes*

2015-01-31 14:21 GMT+00:00 Ikey Doherty <notifications@github.com>:

**Comment by ikeydoherty** [comment]
How is GMarkup performance? It's likely we can use a dynamic array to store our picture set. Or even a GHashTable tbh, and store the relevant steps, etc

**Comment by efernandesng** [comment]
I have made a small test (compares libxml2, expat and GMarkup) with [testxml.c](https://gist.github.com/efernandesng/dad5db25403056f40be5) and got best results with GMarkup.

parser | cnt | total | average
---------|-----|-------|------------
GMarkup | 10 | 0.000211 | 0.000021
libxml2 | 10 | 0.000365 | 0.000036
expat | 10 | 0.000256 | 0.000026

Yeah, we can use GHashTable or other to create a simple cache sistem and manage the memory. Gnome3 has created a BackgroundManager that have the same function.

**Comment by ikeydoherty** [comment]
Timing is nice, admittedly.. Terrified to valgrind it. Won't bother.
OK looks like GMarkup has the go-ahead then :)

(Nicely done btw :))

**Comment by ikeydoherty** [comment]
Now being tracked in issue #261
