### ISSUE TITLE
Budgie Desktop Settings > Widgets dropdown scrolls infinitely

### ISSUE THREAD

**Issue by royyhlee** [solus-project/budgie-desktop#1453]
**Operating System**:  Solus 3.9997
**Budgie version**: budgie-desktop v10.4-70-g15c960cc

**The issue encountered**

Budgie Desktop Settings > Widgets dropdown scrolls down beyond range. 
It shows blank white spaces.

**Steps to reproduce the issue**

![image](https://user-images.githubusercontent.com/6049018/40455575-7cb20716-5ea2-11e8-8381-58dc8b0db712.png)

**Comment by tristan957** [comment]
This is an Arc issue. I do not see this on Adapta-eta
