### ISSUE TITLE
Regarding the Budgie desktop being a Solus Project once more

### ISSUE THREAD

**Issue by Mikerr1111** [solus-project/budgie-desktop#1454]
Hi @ikeydoherty , 

I was wondering with the last commit you made about 'Budgie desktop being a Solus Project once more' what does mean for other distros(Ubuntu Budgie, Manjaro,etc.) that use Budgie? Will there be any additional steps needed from now on to use the Budgie desktop in another Linux distro? Those are just some thoughts I have and also thank you for all the hard work you put into Solus and many other open source projects! 👍 

![budgie](https://user-images.githubusercontent.com/18353476/40458843-0b7d41f8-5eb3-11e8-83ba-96f8aed799de.PNG)

**Comment by ikeydoherty** [comment]
We won't be responsible for Budgie under other distributions, so basically it doesn't change anything from the users perspective. The distro packagers just need to ensure they're engaging correctly with the project, and to be forward planning. i.e. not creating upgrade paths that cannot be resolved in future (such as budgie-extras) that we ourselves don't and cannot support.

**Comment by Mikerr1111** [comment]
Good to hear and thank you for your response.  I will close this issue now
