### ISSUE TITLE
budgie-core

### ISSUE THREAD

**Issue by tellsela** [solus-project/budgie-desktop#1455]
after I play around with budgie this few week,  i wonder what else can replace budgie core??
thanks

**Comment by tellsela** [comment]
Core package for Budgie-Desktop

**Comment by JoshStrobl** [comment]
Again, what are you remotely meaning here? Are you talking about a specific section of the codebase, are you talking about a distribution package?

**Comment by tellsela** [comment]
Distribution package. 
Sorry for not being clear to you.
This is what happen I kind of love gnome tweak tools so I want to remove budgie desktop setting. 
after I did some research, I found out that there is a package call budgie-core. but when i uninstall it I fail to login to budgie desktop.
So my Question was what else can replace budgie-core

Thanks!

**Comment by tellsela** [comment]
well this is what is want.
i want uninstall budgie-desktop-setting. 
after i uninstall budgie-desktop-setting from softer wear center then i do this commend " sudo apt autoremove. 

when i reboot and login i can not login. "fail to start sesion" 

sorry my english so bad

**Comment by JoshStrobl** [comment]
> This is what happen I kind of love gnome tweak tools so I want to remove budgie desktop setting.

You don't need to uninstall Budgie Desktop Settings to make use of GNOME Tweak Tools.

> i want uninstall budgie-desktop-setting.
> after i uninstall budgie-desktop-setting from softer wear center then i do this commend " sudo apt autoremove.
> when i reboot and login i can not login. "fail to start sesion"

Well, this isn't a configuration we really support. Nor are we responsible for the packaging of Budgie Desktop for Ubuntu and its derivatives.

**Comment by tellsela** [comment]
thanks for your help
