### ISSUE TITLE
No icons on the desktop in .desktop files shortcuts from gog.com games.

### ISSUE THREAD

**Issue by zor1984qq** [solus-project/budgie-desktop#1461]
Solus 1.2.0.5
10.4+git20171031.10.g9f71bb8-1.2ubuntu1 all
budgie-desktop --version
budgie-desktop 10.4

Regular .desktop shortcuts created by installed GOG.com games has no icons displayed on the desktop.

Install any DRM free gog.com game, check [v] to create shortcut on the desktop, see that there no any icon displayed.

I attach some screenshots. Here you can see that desktop shortcuts has no gog icons on the desktop itself but in main budgie menu icons showed up.

![2018-05-29 15-42-23](https://user-images.githubusercontent.com/17200201/40659427-e86a775a-6356-11e8-929a-a9f5e03b333d.png)

I can't do screenshot with opened up main budgie menu cause of these issue:
https://github.com/cybre/budgie-screenshot-applet/issues/24

sorry. but in main menu icons are showed up properly.

**Comment by JoshStrobl** [comment]
Clean up the template stuff so we can more easily understand what you're actually using and what the issue is. Thanks.
