### ISSUE TITLE
Applet : clock + calendar ( agenda ? ) does not remember customised date

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#1467]
Hi,
Here is Ubuntu-Budgie-18.04 with budgie-desktop 10.4
I have clock applet with calendar where I've manually set a customized format for date, using the string : 
%a %e %b %Y  |  %H:%M
Perfect to me.
https://s20.postimg.cc/cmct29qi5/applet_clock_calendar.png
Only problem is that it does not seem « memorized » after reboot.
I have to set it again at next start - system default date format comes back.

**Comment by fossfreedom** [comment]
Sounds like you are using budgie calendar which is a independent third party effort

https://github.com/danielpinto8zz6/budgie-calendar-applet

Btw. Press enter when changing the custom string to save it between sessions.

**Comment by Coeur-Noir** [comment]
Ha, ha, yes press enter does the job ;-) Thanks

Did I expect some « apply » button ?
