### ISSUE TITLE
Task bar takes too much vertical space (feature request)

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1469]
**Operating System**: e.g. Solus 3.999
**Budgie version**: Budgie 10.4

**The issue encountered**
Most people have displays with a 16:9 aspect ratio. These are great for movies, but not so great for development, which typically requires tall text windows. To make matters worse, the task bar at the bottom of the screen is eating precious vertical space.It would therefore be helpful to have an option to make the bar vertical, or simply to have all 4 rectangle sides as optional locations. Perhaps it could even squash itself into a corner when not in use, then inflate back into a square (instead of a very narrow rectangle) when required temporarily for an icon click, then shrink back. Frankly anything that doesn't force us to lose vertical space would be very much appreciated. 

**Steps to reproduce the issue**
(None)

**Comment by JoshStrobl** [comment]
> It would therefore be helpful to have an option to make the bar vertical, or simply to have all 4 rectangle sides as optional locations.

This is already an option (to make it vertical). Use Budgie Desktop Settings, there is a settings section for the panel where you can change its position.
