### ISSUE TITLE
 Do-not-disturb symbol is too big

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1470]
**Operating System**: Solus 3
**Budgie version**: Budgie v10.4-85

**The issue encountered**

 Do-not-disturb symbol is bigger than usual & other(in a reasonable size at-least to report) 

**Steps to reproduce the issue**

just click do-not-disturb button in notification center and note the size of the icon

**Comment by JoshStrobl** [comment]
Yea, seems a few pixels larger. I'll see about downscaling it a bit.

**Comment by bsucker98** [comment]
sorry if this is not the right place to report this,
not trying not be inconvenient, feels kind a related(mm..maybe something similar to get sort with Papirus devs..Idk ¯\_(ツ)_/¯)
even **VLC** app's tray icon is bigger and very noticeable....& **uGet** seems few pixels larger as same as the reported bell icon, specially when with other icons...not a big deal though
