### ISSUE TITLE
libc missing from applet linking?

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1471]
**Operating System**: Debian Buster
**Budgie version**: master as well as 10.4+git20171031.10.g9f71bb8

**The issue encountered**

Debian builds have for a few months now are reporting that there is a libc missing link issue with the budgie-desktop shared object applets. 

"The package installs a library which is not dynamically linked against libc.

It is theoretically possible to have a library which doesn't use any symbols from libc, but it is far more likely that this is a violation of the requirement that "shared libraries must be linked against all libraries that they use symbols from in the same way that binaries are"." https://lintian.debian.org/tags/library-not-linked-against-libc.html

 This is highlighted via lintian:

```
E: budgie-core: library-not-linked-against-libc usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.lock-keys/liblockkeysapplet.so
E: budgie-core: library-not-linked-against-libc usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.separator/libseparatorapplet.so
E: budgie-core: library-not-linked-against-libc usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.show-desktop/libshowdesktopapplet.so
E: budgie-core: library-not-linked-against-libc usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.spacer/libspacerapplet.so
E: budgie-core: library-not-linked-against-libc usr/lib/budgie-desktop/plugins/org.budgie-desktop.applet.tasklist/libtasklistapplet.so
```

Question - is this a false positive or is there a missing meson.build dependency for each of the built applets?

**Comment by smcv** [comment]
This is probably a false positive. Plugins for GLib-based software often don't use libc directly, only via GLib. You can check by using `objdump -Tx /path/to/plugin.so` and checking that there are `NEEDED` entries for the libraries that provide all the referenced symbols.

**Comment by fossfreedom** [comment]
@smcv thanks for the tip.  I've checked each of the lintian reported objects and can confirm NEEDED entries are just for the libraries that provide the referenced symbols.

I'll add a lintian override with an explanation comment why the override is needed and the test performed to confirm.
