### ISSUE TITLE
Samba 4.8

### ISSUE THREAD

**Issue by CyrosX** [solus-project/budgie-desktop#1474]
G'day there!
It would be very great, if Samba 4.8 is in the next updates. 
I want to use the new fullsync capability to connect a time machine hd!
Maybe I'm not the only one to use Solus also for this feature.

**Comment by JoshStrobl** [comment]
This has absolutely nothing to due with Budgie. Our dev tracker is https://dev.solus-project.com. We have no plans of updating Samba away from 4.6 because of issues with it and GVFS.
