### ISSUE TITLE
System Tray appear with keyboard layout indicator.

### ISSUE THREAD

**Issue by maxmbed** [solus-project/budgie-desktop#1479]
**Operating System**: PureOS (Debian)
**Budgie version**: budgie-desktop 10.4

Hi,

There is a keyboard layout indicator which is automatically attached right to the System Tray applet when I added to the panel (see picture). I think it should not be there and only the wifi icon must be appeared.

Any idea ?

![image](https://user-images.githubusercontent.com/24230300/41338390-57e507c0-6ef2-11e8-9420-e31feab0a73a.png)

**Comment by JoshStrobl** [comment]
If it's appear in the system tray, then it isn't our keyboard layout switcher, but rather some other software you're using that is creating that. I'd check whatever control center you're using (not familiar at all with PureOS) to see if there is any input settings that result in the showing of a menu.

**Comment by fossfreedom** [comment]
That is ibus itself. Think ibus-setup controls that.

In dconf-editor you can look and change this setting

[org.freedesktop.ibus.panel:Budgie]

show-icon-on-systray=false

**Comment by maxmbed** [comment]
@fossfreedom well spotted. Disabling *show-icon-on-systray* solve the problem. Thanks
