### ISSUE TITLE
Budgie ignores gnome's primary display setting

### ISSUE THREAD

**Issue by kallisti5** [solus-project/budgie-desktop#148]
The budgie interface always displays on the left most monitor and ignores the Gnome displays preference panel's "Primary" vs "Secondary" setting.

**Comment by ikeydoherty** [comment]
Aaah. Is it at the bottom ?

**Comment by ikeydoherty** [comment]
^ Hopefully fixes it. >_>

**Comment by ikeydoherty** [comment]
Resolved, but closing due to no comment.
