### ISSUE TITLE
Feature: Raven Audio Input/Output names to use property descriptions when available.

### ISSUE THREAD

**Issue by erenfro** [solus-project/budgie-desktop#1483]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4.85-g36667bcb

**The issue encountered**

Raven's output and inputs uses the device.properties.name and some kind of logic to display Digital Output, Analog Output, Speakers for sinks/output, and Digital Input, Analog Input, Line In, Microphone, etc for sources/input. 

pavucontrol does similar, without the logic involved, but replaces those with device.description when those properties are actually set, allowing user customization to make those more understandable names. For example, I could set the description of my primary sound card to be "Main Audio", my USB Headset to be "USB Headset", and my USB audio mixer/eq to "USB Mixer", in sinks, and sources something like "Main Audio", "USB Headset (monitor)", "USB Headset", "Webcam", etc.. and be smaller, more human understandable, and easy to work with. These settings can be set in $HOME/.config/pulse/default.pa for persistence across reboots.

**Steps to reproduce the issue**

pacmd list-sinks | grep name:

```
	name: <alsa_output.pci-0000_06_04.0.analog-surround-51>
	name: <alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo>
	name: <alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo>
```
pacmd 'update-sink-proplist alsa_output.pci-0000_06_04.0.analog-surround-51 device.description="Main Audio"'
pacmd 'update-sink-proplist alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo device.description="USB Headset"'
...

pacmd list-sources | grep name:

```
	name: <alsa_output.pci-0000_06_04.0.analog-surround-51.monitor>
	name: <alsa_input.pci-0000_06_04.0.analog-stereo>
	name: <alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor>
	name: <alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-mono>
	name: <alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo.monitor>
	name: <alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo>
	name: <alsa_input.usb-046d_HD_Webcam_C615_FABC09D0-00.analog-mono>
```

pacmd 'update-source-proplist alsa_output.pci-0000_06_04.0.analog-surround-51.monitor device.description="Main Audio (Monitor)"'
pacmd 'update-source-proplist alsa_input.pci-0000_06_04.0.analog-stereo device.description="Main Audio"'
...

Descriptions set, pavucontrol shows them with the new descriptions, Raven does not.

**Comment by JoshStrobl** [comment]
No plans on fixing this since we're using Gvc rather than pulseaudio directly, utilizing card description and names.
