### ISSUE TITLE
Performance Improvement idea for Solus

### ISSUE THREAD

**Issue by majamee** [solus-project/budgie-desktop#1485]
@ikeydoherty Today I stumbled upon the following article:
https://01.org/blogs/joone/2018/using-chrome-os-graphics-stack-intel-based-linux-desktops

In short words: The Chrome OS graphics stack can be used under Linux providing noteable performance improvements. Maybe this would be a very nice addition on tweaking Solus performance even further. Hope you find this interesting.

**Comment by Jacalz** [comment]
I also think it would be a good idea but you should move the issue https://dev.solus-project.com 😉

**Comment by majamee** [comment]
@Jacalz Thanks for the hint, done: https://dev.solus-project.com/T6565

**Comment by Jacalz** [comment]
You are welcome 🙂

**Comment by alunux** [comment]
@majamee I think you should close this issue.
