### ISSUE TITLE
System tray context menu has old looking style

### ISSUE THREAD

**Issue by nemyxa** [solus-project/budgie-desktop#1486]
Hi, guys. Love Solus, by the way

**Operating System**: Solus 3 (.9999)
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**

In general this is not such a problem, but Budgie must be ideal.
It's related to system tray.
It's awesome, but this is how context menu looks:

![image](https://user-images.githubusercontent.com/18642352/41801819-703e6ff6-7685-11e8-98d0-5d6ef7aab80d.png)
![image](https://user-images.githubusercontent.com/18642352/41801829-8e58435e-7685-11e8-8bb1-0f1fb0f39f6d.png)

I don't know it's only Telegram or not, i don't have any program that hangs in tray :smile:

**Comment by Staudey** [comment]
Is this a Telegram snap or something? Because the Skype snap has similar non-native styling in the tray icon context menu.

**Comment by nemyxa** [comment]
@Staudey, this isn't snap, i installed it from solus repo

**Comment by JoshStrobl** [comment]
This isn't an issue with Budgie, nor is it an issue with our (Solus) package either, it's with Telegram itself.
