### ISSUE TITLE
Would it be possible to add a new label to issues that would be "beginner-friendly"?

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#1489]
I would like to start contributing to the code base, but I am a little unsure of the difficulty in some of the issues. I think a label that could allow new-comers to know what issues are on the easier side of things would be positive.

**Comment by JoshStrobl** [comment]
Consider it done. I'll start using the beginner friendly label :+1:

**Comment by tristan957** [comment]
Thanks Josh. I'll be on the lookout for some easy tasks to pick up.
