### ISSUE TITLE
raven shows up on left side of screen… why ?

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#1490]
**Operating System**: Ubuntu-Budgie 18.04
**Budgie version**: 10.4

**The issue encountered**
Well an image speaks for itself : 
![capture du 2018-06-29 03-16-49](https://user-images.githubusercontent.com/1895947/42068263-40e714ea-7b4b-11e8-91aa-0465322b708b.png)

**Steps to reproduce the issue**
Add a panel on left side of screen, and trigger raven with its applet or through bell-icon for notifications.

**What did I expect ?**
Raven to still show up on the right side of screen.

**Comment by JoshStrobl** [comment]
This is intentional. The main panel being on the left will trigger Raven to be on the left.

**Comment by Coeur-Noir** [comment]
Ah.
It looks like a mistake ( to my eyes ).
If raven applet ( or bell for notifications ) is set on the right side, raven should pop up from the right side too.

**Comment by goodwillcoding** [comment]
@JoshStrobl ... not to a pest, but are you sure it's make sense to drag the mouse all the way accross the scree when the trigger / notificatiion are places on the other side?

**Comment by notuxius** [comment]
Noticed if panel is on the left or right sides without auto hiding - the Raven shows right next to the panel - but with auto hiding - the Raven shows on the opposite screen side

Manjaro Budgie
budgie-desktop 10.5 (git-6d814d566f3744d13eed1a285c8c210fde1fda77)

**Comment by JoshStrobl** [comment]
Hey everyone, I agree that this is not ideal and should be configurable. The decision to close this back in June of 2018 was when I was not the lead developer of Budgie and I was enforcing the current "intended" design at the time.

I'm going to be re-opening this and will be accepting patches that would resolve this in a manner I'd like to see, which is a Raven positioning with 3 possible options: "Automatic" (how it is now), "Left" and "Right".

**Comment by EbonJaeger** [comment]
I can work on this. Shouldn't take too long. :D
