### ISSUE TITLE
Background Wallpaper Crossfade

### ISSUE THREAD

**Issue by MrReSc** [solus-project/budgie-desktop#1493]
**Operating System**: Solus 3.9999
**Budgie version**: budgie-desktop V10.4-85-g36667bcb

I use a script to change the desktop background depending on the time. I use the `gsettings set org.gnome.desktop.background picture-uri "file:/home/wallpaper.jgp" ` command. Each time the background image changes, there is a crossfade. Exactly the same as changing the image in the system settings. I want to make a more dynamic background. For this I would like to turn off this crossfade. In fact, I just want to be able to change the background image pretty quickly (max. 10Hz).

I don't want to use software like Variety or komorebi2, I want to write my own. Unfortunately, I'm facing this fading problem right now.

I already tried to set the key `org.gnome.nautilus.desktop background-fade` to `false`. I'm afraid that didn't work.

I also tried to change the background image with [feh](https://wiki.archlinux.org/index.php/feh). That's not working either.

Does anyone know how I can do this?

**Comment by JoshStrobl** [comment]
Realistically, this isn't something that's going to be addressed in the Budgie 10 series, nor am I entirely certainly I'll make this a feature in Budgie 11's window manager (scripting crossfades, disabling it, etc). I'm going to close this as wontfix for now. I may re-evaluate this when we begin Budgie 11 development (in a separate repo).
