### ISSUE TITLE
Desktop freezes after commanding file to delete permanently

### ISSUE THREAD

**Issue by mcmurphy8097234789** [solus-project/budgie-desktop#1494]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie v10.4-85-g36667bcb

**A file located on the desktop causes a desktop freeze when it is right-clicked and commanded to delete permanently. Sending to trash and then deleting does not cause this issue. **

 ...

**Copy and paste file to desktop. Right click. Select delete permanently. Desktop crash; file does not delete (even after reboot) and no files can be pasted to the desktop. Right click on desktop is non-functional*

Computer specs:

Ryzen 1600x
Asrock ab350M pro4 microatx mbd
MSI GTX 1060 6GB (with proprietary nvidia drivers)
Samsung 850 evo 500GB SSD
16GB GSkill RAM, at 2300(?) MHz, capable of 3200mhz OC

 ...

**Comment by yursan9** [comment]
![peek 2018-08-06 12-11](https://user-images.githubusercontent.com/17114559/43698044-196c42d8-9972-11e8-9ff1-de6d493f0459.gif)
I can't reproduce the issue. I tried using `peek` to record the test.

**Comment by JoshStrobl** [comment]
Closing due to lack of response. Please test this against latest Solus and preferably Budgie git.
