### ISSUE TITLE
Serious lag issues on gentoo

### ISSUE THREAD

**Issue by RainbowDashDC** [solus-project/budgie-desktop#150]
Kernel: 3.18.3
GTK Version installed: 2.24.25, 3.14.7
Gnome Version: 3.14
Budgie Version: master

gcc: -O3 -march=native

Notes:
Scrollbars are laggy, and other UI selections and etc.

**Comment by ikeydoherty** [comment]
GPU+ driver, CPU,RAM?

**Comment by RainbowDashDC** [comment]
GPU: intel i965
CPU: intel i5 1.7ghz dual core (running as 4)
RAM: 4GB

No lag issues on gnome 3.14, just budgie.

**Comment by ikeydoherty** [comment]
Odd, Budgie uses the same library underneath... Define 'laggy' with scrollbar. I think you may be referring to the grab issue of scrollbars on popovers..
If you drag outside the scrollbar region the drag stops.

**Comment by RainbowDashDC** [comment]
Nope, straight line the the scroll bar sorta isn't smooth on movement. I'll see if I can upload some sort of gif

**Comment by ikeydoherty** [comment]
Thanks :)

**Comment by ikeydoherty** [comment]
Heard nothing in a long time - if you feel there's an issue still, reopen.

**Comment by RainbowDashDC** [comment]
Too comment on this, apologies, it seems too work well now. Only issue was the aforementioned scroll region issue. Thanks for the great work :)
