### ISSUE TITLE
[Feature Request] Right-click menu for application menu items

### ISSUE THREAD

**Issue by theCalcaholic** [solus-project/budgie-desktop#1503]
Very often I find myself in the situation that I need to do something else with an installed application than just execute it, e.g. start it with elevated permissions (sudo), find out the executed command, edit the desktop file, etc.

As an example, currently, the fastest way to start an app with root permissions (if you only know the application as it is installed in app menu) is to
1. open the menu editor 
2. search for the application
3. remember or copy the command
4. open a terminal and execute it with sudo

In my opinion it would be a great improvement for usability (especially for users with less Linux experience) to have options like that right from a context menu from inside the main menu (e.g. when right clicking on an application entry).

Ideally, this menu could be configurable by plugins (it's just a command, name and description for each option), e.g. in the dconf. But even without modularity this would be a very nice feature.

**Comment by JoshStrobl** [comment]
There's already multiple related issues for this, like the option to open certain items via Budgie Menu on right-click.
