### ISSUE TITLE
Runing *.desktop launcher with Exec attributes makes no effect

### ISSUE THREAD

**Issue by gitowiec** [solus-project/budgie-desktop#1504]
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: budgie-desktop 10.4

**The issue encountered**

I can't run *.desktop launcher with command arguments. I asked my question on [AskUbuntu](https://askubuntu.com/questions/1054752/how-to-change-ubuntu-budgies-plank-launcher-command-line-parameters), so I will just copy it here.  

I would like to run Tilix with param `--session=~/my-tilix-config.json` with mouse clicking Plank's launcher. I found that references to launchers visible in Plank are kept in `~/.config/plank/dock1/launchers/`. Each `*.dockitem` file is just a simple text file with path to `*.desktop`. In my case I changed `com.gexperts.Tilix.dockitem` content to:

    [PlankDockItemPreferences]
    Launcher=file:///home/user/.local/share/applications/com.gexperts.Tilix.desktop

Next I went to aforementioned path and changed the proper launcher to

    [Desktop Entry]
    Version=1.1
    Type=Application
    Name=Tilix
    Comment=A tiling terminal for Gnome
    Icon=com.gexperts.Tilix
    DBusActivatable=true
    Exec=tilix --session=/home/user/.config/tilix.json
    Actions=new-window;new-session;
    Categories=System;TerminalEmulator;X-GNOME-Utilities;
    Keywords=shell;prompt;command;commandline;cmd;
    StartupNotify=true
    
    [Desktop Action new-window]
    Name=New Window
    Exec=tilix --action=app-new-window --session=/home/user/.config/tilix.json
    
    [Desktop Action new-session]
    Name=New Session
    Exec=tilix --action=app-new-session --session=/home/user/.config/tilix.json

I checked that running `tilix --action=app-new-session --session=/home/user/.config/tilix.json` opens Tilix reconfigured with my config, then I logged out and logged in again to make sure settings were applied. When I click Tilix launcher passed argument does not work - it just runs Tilix in standard single mode (my config makes Tilix splitted into 4 quarters) 

###How can I launch Tilix with param?

**Steps to reproduce the issue**

Copy Tilix *.desktop lanucher to desktop folder, edit it, add `--session` param with path argument, save, double click, give it execution rights when asked if it is save, and observe no effect.

**Comment by JoshStrobl** [comment]
We're not responsible for Plank.
