### ISSUE TITLE
RFC: Inclusion of a hotcorners applet

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1506]
![](https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-hotcorners/menu.png?raw=true)

https://github.com/UbuntuBudgie/experimental/tree/master/hotcornersII_projectfolder/applet_uc

(similar RFC: https://github.com/solus-project/budgie-desktop/issues/1499)

We have developed a vala based hotcorners Applet - abilities to

- define corners on the primary display to invoke an action when the cursor hits that area
- a user defined "Pressure" setting as to the speed that the cursor needs to enter the area to invoke i.e. prevent accidental activation
- applet popover gui to launch predefined / custom actions.
- actions and settings are all gsettings based.

Is this something the budgie desktop team is interested in to be included in the git tree?

If yes, we will do a proper PR, integration and will rejig the source files to fit the style of current applets.

**Comment by JoshStrobl** [comment]
I'd much rather this be something that is integrated into Budgie Settings (a new Hotcorners panel) rather than being a dedicated applet.

**Comment by Jacob-Vlijm** [comment]
@JoshStrobl Not sure why that is. I'd rather be able to quickly switch commands then digging up Budgie settings first. The "more general" pressure setting is in Budgie Settings though.

**Comment by JoshStrobl** [comment]
@Jacob-Vlijm Because this level of customization deserves a dedicated space rather than being squashed into an applet. I don't really see the value-add in having hotcorner actions be changeable on-the-fly, they're typically something you "set and forget".

**Comment by Jacob-Vlijm** [comment]
Ah, ok, must be a different user case then. I am switching it all the time, depending on the job I am on. Using it via Budgie Settings would be a pain for me. Could easily move the Applet section to Budgie Settings of course for an upstream version.

**Comment by yursan9** [comment]
Sorry for the intrusion... What do you think about keeping the applet as the switch? If you want to deactivate the trigger easily, you can use the applet.

**Comment by Jacob-Vlijm** [comment]
The project has moved btw, the new location is https://github.com/UbuntuBudgie/experimental/tree/master/hotcornersII_final

**Comment by fossfreedom** [comment]
I have been led here where Hot corners was discussed. Given the discussion I will close this offer. 

https://dev.solus-project.com/T5010
