### ISSUE TITLE
Clip-board doesn't remember the recent item after a certain time

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1507]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4-85

**The issue encounterd**

Clip-board doesn't remember the recent item after a certain time, after not using it for a while. it just takes quite a little time make it even more annoying.
Now I'm pretty sure on this case, as my letter 's' is broken. to tell u, it still tend to forget taht letter, which in use frequently.

**Steps to reproduce the issue**

copy some text, don't use it for a while,(I cannot give u n exact time frame) take quite some time for testing purpose, to make sure that the issue exist, and then try to paste it.

**Comment by JoshStrobl** [comment]
None of this has anything to do with Budgie.
