### ISSUE TITLE
RFC: Inclusion of a QuickNote applet

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1512]
![](https://raw.githubusercontent.com/UbuntuBudgie/budgie-extras/master/budgie-quicknote/quicknote.png?raw=true)

https://github.com/UbuntuBudgie/experimental/tree/master/QuickNoteII

We have developed a vala based QuickNote Applet - abilities to

 - Size the popover via budgie settings
 - Chose the folder where to save the text added to the applet edit field e.g. Dropbox folder for sync
 - undo/redo capability

Is this something the budgie desktop team is interested in to be included in the git tree?

If yes, we will do a proper PR, integration and will rejig the source files to fit the style of current applets.

**Comment by JoshStrobl** [comment]
Yep, this is something that be great to have in budgie-desktop :+1:
