### ISSUE TITLE
Keyboard Shortcut isn't working

### ISSUE THREAD

**Issue by maelodic** [solus-project/budgie-desktop#1516]
**Operating System**: Solus - Latest
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**

Using the "Super+`" custom keyboard shortcut to try and switch workspaces fails. Other key combinations on the same action work, and this one works intermittently. I haven't been able to determine the difference between what works and what doesn't, and it works on other WMs/DEs.

Using Super+Shift+` works for moving windows to that workspace, just not switching to the workspace

**Steps to reproduce the issue**

Set "Switch to workspace 1" to "Super+`" and press the key combination.

**Comment by maelodic** [comment]
EDIT: It looks like an easy way to trigger it not working is launching certain programs such as gmusicbrowser.

**Comment by yursan9** [comment]
Maybe that certain key combination is used by gmusicbrowser. Because I can't reproduce the issue

**Comment by maelodic** [comment]
This occurs even when gmusicbrowser isn't launched, and occurred before I
even had it installed with the base software installed.

I have "setxkbmap -option caps:super" set to run on startup, and the same
thing that disables the shortcut is also resetting that option. Something
must be resetting it.

I have tried this on a base solus install with no further customizations or
software installs and it still occurs randomly during the session.

**Comment by maelodic** [comment]
Hidden in dconf there's a shortcut for "super+above_tab" - not super+grave or super+` and that's what's interfering. Removing that shortcut resolves the issue.
