### ISSUE TITLE
Panel unhide shrinks windows

### ISSUE THREAD

**Issue by Ringstaart** [solus-project/budgie-desktop#152]
If you set the panel to autohide, and it unhides because you move your cursor over it, it shrinks the maximized windows so that the panel doesn't overlap. I understand this is intentional, and I assume it's to make sure that you can still use anything that's at the bottom of the window that would otherwise be covered.

It doesn't achieve that, though. When you try to use one of the elements that would otherwise be covered, you move your cursor out of the panel area, which causes it to hide itself again, and the element is moved away from your cursor, causing you to misclick. This means that it doesn't offer that benefit, but does make the panel hiding look clunky.

Wouldn't it make more sense to let the panel cover the windows, or does the current behaviour have other advantages I missed?

**Comment by ikeydoherty** [comment]
I know it seems clumsy right now, but its the intended behaviour. When intellihide lands that wont enforce  a barrier, which will not "shrink" the windows as you've described :)
