### ISSUE TITLE
Audio Overdrive not changing the relevant key

### ISSUE THREAD

**Issue by yursan9** [solus-project/budgie-desktop#1525]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: d93f59220561c8cdae75399cdf182a1dfe52815b

**The issue encountered**
On activating allow raising volume above 100% in Budgie Desktop Settings, the org.gnome.desktop.sound gschema key `allow-volume-above-100-percent` is not changed.

**Steps to reproduce the issue**
1. Open Budgie Desktop Settings and Dconf Editor
2. Activate allow raising volume above 100% on Budgie Desktop Settings, and watch the key `allow-volume-above-100-percent` in org.gnome.desktop.sound unchanged.

![peek 2018-08-07 08-39](https://user-images.githubusercontent.com/17114559/43749258-90c1bbbe-9a1d-11e8-9724-0382f36a0d60.gif)

**Comment by JoshStrobl** [comment]
Again, as I mentioned in your PR it doesn't seem like you are running the latest daemon.

**Comment by yursan9** [comment]
Well, okay... So what should I do?

**Comment by JoshStrobl** [comment]
Well how are you compiling and installing Budgie? You need to have compiled it recently and restarted your session or the daemon (budgie-daemon) itself.

**Comment by yursan9** [comment]
Dang, so I need to restart or logout? Wait a minute, I'll try logging out and go back in. After that I can make PR for adding mark to Gtk.Scale

**Comment by JoshStrobl** [comment]
Yea the `budgie-daemon` doesn't restart when you do a `--replace` on the panel, you'll likely need to relog or restart. I haven't found `budgie-daemon --replace &!` to be reliable in this regard.

**Comment by yursan9** [comment]
Okay, it's working. Thank you @JoshStrobl
