### ISSUE TITLE
Tray icon context menu issues

### ISSUE THREAD

**Issue by pclark36** [solus-project/budgie-desktop#1530]
**Operating System**: Ubuntu 18.04
**Budgie version**:  Budgie 10.4

**The issue encountered**
When clicking a tray icon to get a context menu, you need to click the same mouse button to interact with the menu that was used to pull it up.  i.e. Use left mouse to pull up menu, right click on menu action, action will be ignored.  If left click to open menu and left click to select, action performed.  If you right click tray icon and left click the action, the action is ignored.  Seems to apply to all tray icons I have. 

 ...

**Steps to reproduce the issue**

1.  Right click on any tray icon to bring up menu. 
2.  Left click on the menu to try to perform action
     a.  Menu will blink like clicked, but action will not be performed.
3.  Right click on tray icon to bring up menu.
4.  Right click on menu action.
     a.  Action will be performed.
5.  Left click tray icon to bring up menu
6.  Left click Menu action
    a.  Action is performed.  

 ...

**Comment by EbonJaeger** [comment]
I cannot reproduce this on Solus as of the current commit of Budgie; right clicking on any icon either in the task list or system tray and left clicking a menu item performs the action as expected.

**Comment by pclark36** [comment]
posted to the wrong budgie github,  will get on the ubuntu fork.  Apologies.

**Comment by JoshStrobl** [comment]
@pclark36 Eh? What applet was being used?

**Comment by pclark36** [comment]
it was appindicator.  It's a known issue on ubuntu budgie already.
