### ISSUE TITLE
Flashing elements in Budgie Welcome

### ISSUE THREAD

**Issue by RasmusKallas** [solus-project/budgie-desktop#1533]
**Operating System**: e.g. Ubuntu 18.04 LTS (fresh install)
**Budgie version**: i.e. Budgie 10.4 OR specific git commit

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `4`, to provide the
exact version of your Budgie installation:

    budgie-desktop --version

**The issue encountered**
Budgie Welcome User Interface and Settings part flashes everywhere it is included.
[Link to video.](https://youtu.be/063iYmVDsJc)
 ...

**Steps to reproduce the issue**
Install Ubuntu Budgie 18.04 LTS, (if not already opened) open Budgie Welcome, click Getting Started, Click Customization. The elements are blinking.

 ...

**Comment by RasmusKallas** [comment]
I didn't see, that it was not solus-project's, accidentally issued it there.

**Comment by fossfreedom** [comment]
Huh? Nothing to do with budgie desktop.  Wrong issue tracker.

**Comment by RasmusKallas** [comment]
With what then?
