### ISSUE TITLE
[Feature Request] Screenshot Widget: upload already existing image/gif 

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#1536]
I miss a feature to upload already existing image or gif file, e.g. I made a gif using Peek and want to upload it via Screenshot Widget.

**Comment by JoshStrobl** [comment]
We already have a third-party screenshot widget called Budgie Screenshot Applet, developed by a Budgie developer (@cybre). You can find it at https://github.com/cybre/budgie-screenshot-applet and is already shipped in the Solus repo.
