### ISSUE TITLE
3rd party program: albert launcher - tray icon is way too large

### ISSUE THREAD

**Issue by dreamcat4** [solus-project/budgie-desktop#1539]
**Operating System**: ubuntu 18.04
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

See picture:

https://imgur.com/a/a5vITIM

**Steps to reproduce the issue**

Install albert application launcher, make it appear in system tray.

This is the issue, over on albert repo:

https://github.com/albertlauncher/albert/issues/700

However we do not understand why this occurs, or what needs to be done, to fix it! Can you help us? Thank you.

**Comment by ManuelSchneid3r** [comment]
Just a note: The icon used is a scalable icon (svg). There are no particular sized icons (like 16x16, 24x24, 32x32 px…). [QSystemTrayIcon](http://doc.qt.io/qt-5/qsystemtrayicon.html) is the mechanism used.

**Comment by fossfreedom** [comment]
Is that an traditional system tray app or is it an appindicator app?
 
If it is a system tray based applet then I don't know why the icon is huge.


It it is an appindicator your icon probably a .png and it should be 22px in size i.e. the appindicator spec. If it is a .svg then that will be correctly resized

**Comment by ManuelSchneid3r** [comment]
At least I did not explicitly use libappindicator. I dont know what Qt does internally.

**Comment by rilian-la-te** [comment]
If it is qt5 or sni-qt installed, Qt actually uses SNI (appindicators).

**Comment by fossfreedom** [comment]
Please close this issue. It is not a budgie desktop matter. Something to do with QT5 and incorrect presentation to appindicator implementations I would suggest
