### ISSUE TITLE
[Feature Request] Egg timer / stopwatch

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#1540]
I think it would be nice if Budgie had an timer/alarm applet (either panel, Raven or standalone) for pulling things out of the oven etc. What do you think? :P

**Comment by PizzaLovingNerd** [comment]
This is a nice idea, however you can use GNOME Clocks. However an applet would be convenient. I wouldn't want it on my panel, however, it's a nice feature for the Raven menu.

**Comment by dreamcat4** [comment]
Here is another 3rd party program / tray indicator:

http://alarm-clock.pseudoberries.com/
