### ISSUE TITLE
Laptop automatically shuts down on low battery, no warning, no hibernate.

### ISSUE THREAD

**Issue by RasmusKallas** [solus-project/budgie-desktop#1541]
**Operating System**: Ubuntu Budgie 18.04 LTS (bionic-proposed)
**Budgie version**: 10.4

**The issue encountered**
Laptop shuts down without any low battery warning. It would be also nice, if there was at least an option to hibernate or suspend.
 ...

**Steps to reproduce the issue**
_Be in the middle of your things to find out your laptop battery is 5% and enjoy the shutdown screen._

 ...

**Comment by RasmusKallas** [comment]
Me too, kind of new user and kind of confused about all the repo names...

**Comment by lourenzo** [comment]
I'm still experiencing this using budgie 10.5 on Ubuntu 18.04. Any tips on how to fix that?

**Comment by vc7ee** [comment]
I have moved to Fedora, I suggest you to open an issue with Ubuntu Budgie.

**Comment by vc7ee** [comment]
![image](https://user-images.githubusercontent.com/38327267/61188919-c354a680-a675-11e9-9592-e38645bd6799.png)
What censorship is this on an open-source community? @JoshStrobl

**Comment by JoshStrobl** [comment]
Low battery notifications are sent under Solus and will show up under Budgie. This is not an issue with the Budgie Desktop and we do not provide Ubuntu support, that is more appropriate for either Ubuntu's support channels or Ubuntu Budgie's. Beyond that, the Budgie Desktop shipped in Ubuntu 18.04 is really old (Budgie 10.4) and is not supported by us.
