### ISSUE TITLE
[Feature Request] Option to disable Super button from opening system tray icon sub-menus

### ISSUE THREAD

**Issue by BryceBeagle** [solus-project/budgie-desktop#1542]
Currently, if the Super button is pressed while the cursor is hovering over a system tray applet with a Budgie.Popover, its menu is shown.

I would like a way to disable this feature and have it just always open the Super menu. I don't find the current functionality very intuitive. I expect a single outcome when I press the super key (Budgie menu opens) but sometimes, depending on the location I left my cursor to rest, something different happens and I need to go back to my mouse to move the cursor.

( Feature request created based on discussion in #1378 )

**Comment by JoshStrobl** [comment]
As the rollover functionality has been removed from the Budgie PopoverManager in git, considering this resolved.
