### ISSUE TITLE
Alt+shift shortcut to change keyboard layout

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [solus-project/budgie-desktop#1543]
It is now impossible to use alt+shift keyboard shortcut in budgie in order to change the language
I wish you can solve this in the next release.

**Comment by JoshStrobl** [comment]
Our keyboard shortcut for it has always been Win+Space, not Alt+Shift.

**Comment by ahmed-h-ayyad** [comment]
Why no option to use alt+shift at least

**Comment by EbonJaeger** [comment]
@ahmed-h-ayyad There is an option for it. If you open the menu and search for Keyboard, open those settings, and scroll down to the typing section.
