### ISSUE TITLE
Budgie menu : accented letters & alphabeatical sorting

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#1546]
Hello, hello…

**Operating System**: UbuntuBudgie 18.04
**Budgie version**: 10.4

**The issue encountered**
In Budgie Menu, applications are alphabetically sorted.
But accented letters seem to be out of place : they are all after Z

**my expectation**
À to be found near A
É near E
and so on

**other note**
French here but I assume other languages using accented letters might be concerned.

**for reference** https://discourse.ubuntubudgie.org/t/applications-menu-incomplete-keyboard-browsing-no-recent-category/879

**Comment by JoshStrobl** [comment]
> But accented letters seem to be out of place : they are all after Z

This isn't a bug, this is valid sorting. Foreign characters are considered to be symbols, which get sorted after normal characters. See http://www.asciitable.com

**Comment by Coeur-Noir** [comment]
Sorry.

That may not be a bug regarding ASCII table

But that is a bug regarding human languages.

Accented letters are not symbol grammatically speaking, there are usual letters + accent.

So À or É are not symbols, they are A or E letters. And are already sorted as such in many app's.

So please don't close that actual bug.

**Comment by Coeur-Noir** [comment]
So… two examples out of many : 
1. unity app menu ( and yes it's not perfect Endless Sky should be first or last of the E names )
![french_alphabetical_sorting](https://user-images.githubusercontent.com/1895947/44611114-c6496d00-a7ff-11e8-97f7-247d8ab2fd7b.png)
2. how LOcalc sort those **letters** : 
![french_alphabetical_sorting](https://user-images.githubusercontent.com/1895947/44611196-22ac8c80-a800-11e8-8007-87fc9df63332.gif)
