### ISSUE TITLE
Crashes when switching windows

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1548]
**Operating System**: Ubuntu Budgie 18.04 / 18.10
**Budgie version**: 10.4 & current git master

**The issue encountered**

Getting various launchpad reports over the last year about window manager crashes  - I guess its alt tabbing by virtue of the "budgie_budgie_wm_switch_windows" in the logs

```
Thread 1 (Thread 0x7f02fe910a80 (LWP 1401)):
#0  0x00007f0309243aa5 in g_type_check_instance_is_fundamentally_a (type_instance=type_instance@entry=0x4c0d3b70, fundamental_type=fundamental_type@entry=80) at ../../../../gobject/gtype.c:4023
        node = <optimized out>
#1  0x00007f030922486e in g_object_ref (_object=0x4c0d3b70) at ../../../../gobject/gobject.c:3212
        _g_boolean_var_ = <optimized out>
        object = 0x4c0d3b70
        old_val = <optimized out>
        __func__ = "g_object_ref"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#2  0x0000555a496cf904 in _g_object_ref0 (self=<optimized out>) at src/wm/src@wm@@budgie-wm@exe/wm.c:6443
No locals.
#3  budgie_budgie_wm_switch_windows (self=0x555a4a9e4550, display=0x555a4c0c0000, window=<optimized out>, event=<optimized out>, binding=<optimized out>) at src/wm/src@wm@@budgie-wm@exe/wm.c:6443
        cur_time = 1327561
        workspace = 0x0
        _tmp0_ = <optimized out>
        _tmp1_ = <optimized out>
        _tmp2_ = <optimized out>
        data = 0x0
        _tmp3_ = <optimized out>
        _tmp4_ = <optimized out>
        _tmp5_ = <optimized out>
        _tmp6_ = <optimized out>
        _tmp11_ = 0
        _tmp12_ = <optimized out>
        _tmp13_ = <optimized out>
        _tmp17_ = <optimized out>
        _tmp18_ = <optimized out>
        _tmp22_ = <optimized out>
        __func__ = "budgie_budgie_wm_switch_windows"
#4  0x00007f03092fa9e2 in invoke_handler (binding=0x555a4c0acc40, event=0x7f02f8004860, window=0x555a4c0acc40, handler=<optimized out>, display=0x555a4c0c0000) at core/keybindings.c:1866
No locals.
#5  process_event (display=display@entry=0x555a4c0c0000, window=window@entry=0x555a4c0fd4f0, event=event@entry=0x7f02f8004860) at core/keybindings.c:1941
        keys = 0x555a4c0c0148
        keycode = 23
        resolved_combo = {keycodes = 0x7fffd48bac0c, len = 1, mask = 8}
        binding = 0x555a4c0acc40
#6  0x00007f03092fd007 in process_key_event (event=0x7f02f8004860, window=0x555a4c0fd4f0, display=0x555a4c0c0000) at core/keybindings.c:2186
        keep_grab = 1
        all_keys_grabbed = <optimized out>
        handled = <optimized out>
        keep_grab = <optimized out>
        all_keys_grabbed = <optimized out>
        handled = <optimized out>
        backend = <optimized out>
        xdisplay = <optimized out>
#7  meta_keybindings_process_event (display=display@entry=0x555a4c0c0000, window=window@entry=0x555a4c0fd4f0, event=event@entry=0x7f02f8004860) at core/keybindings.c:2219
        keys = 0x555a4c0c0148
#8  0x00007f03092f6d13 in meta_display_handle_event (event=0x7f02f8004860, display=0x555a4c0c0000) at core/events.c:313
```

These are marked as private bug calls because they contain user sensitive data such as IP addresses - so the above is a snip of the bug report that I can share

 ...

**Steps to reproduce the issue**

Alt+ Tab - looks like 99.9% of the time all is ok

From the code line 1205 or src/wm.vala looks interesting:

```
if ((data = workspace.get_data("__flagged")) == null) {
```

from here https://valadoc.org/libwnck-3.0/Wnck.Screen.get_active_workspace.html says that is may return null

The crash mentions a boolean type check which is probably the `==null` so I guess the workspace may be invalid and the window manager is in some sort of weird very rare unknown scenario?

**Should we put in a quick check such as this?**

```
var workspace = screen.get_active_workspace();
If (workspace == null) {
   return;
}

```
get_active_workspace is used a few places elsewhere.

**Happy to-do a PR with a "null" check where appropriate so that an invalid variable is not used to check against.**

~~EDIT: in 18.10 ALT+Tab crashes the whole session repeatedly. So the above "fix" isn't a fix.  Not sure at the moment the best way to debug~~ resolved 18.10 repeated crash ... so as before should we have null checks in place?

**Comment by alunux** [comment]
I can't reproduce it on Fedora 28 (GNOME 3.28, Meson 0.47.2, Vala 0.40.8, GCC 8.1.1). But, I can reproduce this issue on Fedora 29 (GNOME 3.30, Meson 0.47.2, Vala 0.42.0, GCC 8.2.1), https://github.com/solus-project/budgie-desktop/pull/1523 is applied.

Btw, I see your works, there are https://github.com/UbuntuBudgie/budgie-desktop/commit/825353ea27af8ca2e54e95421072561a1bcfb488 and https://github.com/UbuntuBudgie/budgie-desktop/commit/665076e68be7de280177eff45f224a7c2ea4a212. When I applied those patches, this issue was solved.
