### ISSUE TITLE
disabled notifications are re-enabled after restart

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1553]
*Operating System**: Ubuntu 18.04
**Budgie version**: git master https://github.com/solus-project/budgie-desktop/commit/cb35f5b4f1c71d8dfa3aa8f78298b3825ce85cc2

**The issue encountered**
After restart of the panel / logout login, disabled global notifications become re-enabled.

Is this intentional? - is the global notifications enable/disable button connected up schema key org.gnome.desktop.notifications show-banner ... or something elsewhere in dconf?
 ...

**Steps to reproduce the issue**

 - disable global notifications via Raven - Notifications
 - logout and login

 ...

**Comment by JoshStrobl** [comment]
> Is this intentional?

Yes. Not everything is intended to be controlled through Notifications on GNOME Control Center, just what actually exposes over that (which isn't every app). So if someone muted it and rebooted their system, we'd want to show Solus SC notifications.

**Comment by EliasCK** [comment]
I realize I'm probably in the minority, and understand your reasons for wanting them session based. But  I would like them gone permanently, so is it possible to disable notifications through a command line? That way I could make a startup script that disables notification popups permanently. 

Overlay notifications causes my games to lag (did so on Windows as well), and notifications annoy me in general :)

**Comment by EliasCK** [comment]
@JoshStrobl 

I realize I'm probably in the minority, and understand your reasons for wanting them session based. But I would like them gone permanently, so is it possible to disable notifications through a command line? That way I could make a startup script that disables notification popups permanently.

Overlay notifications causes my games to lag (did so on Windows as well), and notifications annoy me in general :)
