### ISSUE TITLE
Tray menus for apps don't work if you use two different mouse buttons

### ISSUE THREAD

**Issue by Leon422** [solus-project/budgie-desktop#1554]
**Operating System**: Ubuntu Budgie 18.04 64 bit
**Budgie version**: 10.4

**The issue encountered**

If you RIGHT click the tray icon for an app to open its tray menu and then LEFT click an option in the menu, it does nothing, the menu just closes.
Same if you LEFT click the tray icon and then RIGHT click an option in the menu.

In other words: it only works if you use the same button for both opening the menu and clicking an option. So left button twice works, right button twice also works. Tested with the tray menus of Steam, Telegram Desktop, Dropbox, and various pre-installed apps.

This might sound like an edge case, but anyone coming from Windows **will** try to right click the tray icons and left click an option, since that's how it usually works on Windows (since left clicking the icon usually opens the app and not the tray menu). It just made me think that tray menus were not working at all, until I randomly realised that it was because I was switching buttons.

**Steps to reproduce the issue**

Try to open a tray menu and then select an option, with different mouse buttons.

**Comment by fossfreedom** [comment]
Please close this issue since it is not an upstream matter

https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/12
