### ISSUE TITLE
Title bar of GTK2 apps doesn't change when changing themes

### ISSUE THREAD

**Issue by Vistaus** [solus-project/budgie-desktop#1562]
**Operating System**: Solus 3.9999
**Budgie version**: v10.4-123-gf2dbc215

**The issue encountered**

The title bar of GTK2 apps/window border don't change to the ones of the selected theme. Headerbars of GTK3 apps, however, do change.

**Steps to reproduce the issue**

-Install a different theme
-Select the theme
-Notice how the title bar of GTK 2 window borders don't change

**Comment by JoshStrobl** [comment]
You need to restart the app.

**Comment by Vistaus** [comment]
I even restarted the whole system but the issue remains. And this is a clean install of Solus, btw.
