### ISSUE TITLE
Built-in theme problem

### ISSUE THREAD

**Issue by 0azizi0** [solus-project/budgie-desktop#1565]
Solus: V3.9999
Budgie: v10.4-85-g36667bcb

Only happens when toggling built-in theme in Budgie settings, the applications menu will look different, I added some screenshots to see the problem.
![screenshot from 2018-09-11 21-55-39](https://user-images.githubusercontent.com/7659180/45382393-c673a600-b610-11e8-9f5e-8012178caad2.png)
![screenshot from 2018-09-11 21-56-02](https://user-images.githubusercontent.com/7659180/45382409-d55a5880-b610-11e8-8623-07d0e834abe0.png)

**Comment by JoshStrobl** [comment]
The intent of "built-in theme" is to be used with Arc. This isn't valid.
