### ISSUE TITLE
Dark theme inconsistenty

### ISSUE THREAD

**Issue by 0azizi0** [solus-project/budgie-desktop#1566]
Solus: V3.9999
Budgie: v10.4-85-g36667bcb

I added screenshots, because pictures explain better than me.

![screenshot from 2018-09-11 21-54-19](https://user-images.githubusercontent.com/7659180/45383312-7c3ff400-b613-11e8-95ce-a8984566c3ed.png)
![screenshot from 2018-09-11 21-53-42](https://user-images.githubusercontent.com/7659180/45383325-895ce300-b613-11e8-8af7-e45061b14b1c.png)
also with context menus
![screenshot from 2018-09-11 22-29-34](https://user-images.githubusercontent.com/7659180/45383368-9f6aa380-b613-11e8-8265-84f2bb6adb75.png)
![screenshot from 2018-09-11 22-29-14](https://user-images.githubusercontent.com/7659180/45383369-a2fe2a80-b613-11e8-8ae2-43ba3a26189c.png)

**Comment by JoshStrobl** [comment]
That's because nm-applet isn't developed by us and is exposed via our system tray for legacy xembed support. See #610.
