### ISSUE TITLE
Scroll bars are difficult or impossible to grab

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1567]
**Operating System**: Solus 3.999
**Budgie version**: 10.4

**The issue encountered**

I realize that sometimes scroll bars are hidden, which in itself creates more frustration than UI benefit, but this issue concerns more than that. It's that, even when the bars are visible, one must grab them by exactly the leftmost pixel row, or they can't be grabbed at all, even when the tip of the mouse pointer is within the shaded area comprising the bar. (Sometimes it's even worse in that they're flat out ungrabbable, as is the case with various text editors.) All in all, lots of time is wasted trying to unhide and then grab scroll bars. It would be nice if we could at least disable all this evasiveness in favor of fat, unhidden, and easily grabbed ones.

**Steps to reproduce the issue**

(See above.)

**Comment by JoshStrobl** [comment]
This is entirely dependent on the application (whether they set overlay scrolling or not) and GTK theme, not Budgie.
