### ISSUE TITLE
[bug] Dark theme forces Firefox inputs backgrounds color

### ISSUE THREAD

**Issue by gitowiec** [solus-project/budgie-desktop#1570]
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: 10.4

**The issue encountered**

Setting style Adwaita-dark (Dark Theme off, built-in theme off) forces Firefox Developer Edition 63.0b1 inputs and textareas backgrounds black and ink color white.

**Steps to reproduce the issue**
Install Ubuntu Budgie and latest Firefox Dev Editon
Set style as above
Run Firefox and open web page with a <form> element with inputs and textareas in it 

 ...

**Comment by fossfreedom** [comment]
This is a theming issue and not a budgie desktop matter.  You should report this to the theme maintainer
