### ISSUE TITLE
Pinned-Only feature for Icon Task List does not work.

### ISSUE THREAD

**Issue by Schyken** [solus-project/budgie-desktop#1571]
**Operating System**:
Solus 3.9999

**Budgie version**:
10.4-85-g36667bcb

**The issue encountered**
The Icon Task List for Budgie Panel's "Only show pinned" functionality does not work. 
 ...

**Steps to reproduce the issue**
Add the icon Task List to the Budgie Panel/Dock, enable "Show only pinned" in its respective settings toggles, and then open windows that are not pinned to the Icon Task List. You might see something like this ( https://photos.app.goo.gl/F7r4FGXWen4z4y2JA ), where the icons from Chrome to Geary are pinned, but the Audacity and Terminal applications are not, despite them being shown in the Icon Task List.

 ...

**Additional system information because I like cute animals**
System:
  Host: schyken-ryzen-horizon Kernel: 4.18.5-90.current x86_64 bits: 64 
  compiler: gcc v: 8.2.0 Desktop: Budgie 10.4-85-g36667bcb 
  Distro: Solus 3.9999 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x 
  serial: <filter> UEFI: American Megatrends v: 4011 date: 04/19/2018 
CPU:
  Topology: 8-Core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen 
  rev: 2 L2 cache: 4096 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 108600 
  Speed: 2722 MHz min/max: 1550/3400 MHz Core speeds (MHz): 1: 2729 2: 2741 
  3: 2722 4: 2627 5: 3172 6: 2726 7: 2718 8: 2687 9: 2727 10: 2735 11: 2725 
  12: 2681 13: 3216 14: 2705 15: 3270 16: 3392 
Graphics:
  Device-1: AMD Vega 10 XT [Radeon RX Vega 64] driver: amdgpu v: kernel 
  bus ID: 0c:00.0 
  Display: x11 server: X.Org 1.19.6 driver: ati,modesetting 
  unloaded: fbdev,radeon,vesa resolution: 2560x1440~60Hz 
  OpenGL: 
  renderer: Radeon RX Vega (VEGA10 DRM 3.26.0 4.18.5-90.current LLVM 6.0.1) 
  v: 4.5 Mesa 18.1.6 direct render: Yes 
Audio:
  Device-1: Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] 
  driver: snd_hda_intel v: kernel bus ID: 09:00.0 
  Device-2: AMD driver: snd_hda_intel v: kernel bus ID: 0c:00.1 
  Device-3: AMD Family 17h HD Audio driver: snd_hda_intel v: kernel 
  bus ID: 0e:00.3 
  Device-4: Logitech HD Pro Webcam C920 type: USB 
  driver: snd-usb-audio,uvcvideo bus ID: 3-3:3 
  Device-5: C-Media Blue Snowball type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-2:2 
  Sound Server: ALSA v: k4.18.5-90.current 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  driver: r8169 v: 2.3LK-NAPI port: f000 bus ID: 04:00 
  IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 2.05 TiB used: 7.58 GiB (0.4%) 
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 960 EVO 250GB 
  size: 232.89 GiB 
  ID-2: /dev/sda vendor: Western Digital model: WDS500G2B0A-00SM50 
  size: 465.76 GiB 
  ID-3: /dev/sdb vendor: Western Digital model: WDS500G2B0A-00SM50 
  size: 465.76 GiB 
  ID-4: /dev/sdc vendor: Western Digital model: WDS500G2B0A-00SM50 
  size: 465.76 GiB 
  ID-5: /dev/sdd vendor: Western Digital model: WDS500G2B0A-00SM50 
  size: 465.76 GiB 
Partition:
  ID-1: / size: 220.08 GiB used: 7.58 GiB (3.4%) fs: ext4 
  dev: /dev/nvme0n1p2 
  ID-2: swap-1 size: 6.78 GiB used: 0 KiB (0.0%) fs: swap 
  dev: /dev/nvme0n1p3 
Sensors:
  System Temperatures: cpu: 38.4 C mobo: N/A gpu: amdgpu temp: 34 C 
  Fan Speeds (RPM): cpu: 0 gpu: amdgpu fan: 501 
Info:
  Processes: 327 Uptime: 39m Memory: 31.41 GiB used: 1.49 GiB (4.7%) 
  Init: systemd runlevel: 5 Compilers: gcc: N/A Shell: bash v: 4.4.19 
  inxi: 3.0.21

**Comment by xulongwu4** [comment]
I can confirm it. I am running Solus Budgie 3.9999 on Gigabyte Aero 15.

**Comment by Miroslav11** [comment]
I can also confirm it. Also running Solus Budgie 3.9999
