### ISSUE TITLE
Lock screen 'sign in' box is huge.

### ISSUE THREAD

**Issue by twodogsdave** [solus-project/budgie-desktop#1573]
**Operating System**: Solus 3.9999 (the new Solus refresh ISO)
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**
Sign in 'box' is huge.  Lock the screen and then 'sign in' inside a huge box.   The box should be a lot smaller.  

 ...

**Steps to reproduce the issue**
Click the 'user indicator' icon on the budgie panel and click 'lock.'

 ...

**Comment by twodogsdave** [comment]
![screenshot from 2018-09-22 18-13-34](https://user-images.githubusercontent.com/43505645/45922195-51676280-be93-11e8-98ad-dc6d88fcc69c.png)

**Comment by alunux** [comment]
This is not Budgie's issue, it's GNOME Screensaver.

**Comment by iknownothingaboutcomputers** [comment]
Phew! Thought I was the only one having this issue. Started happening from yesterday.

**Comment by JoshStrobl** [comment]
Closing issue, not Budgie.
