### ISSUE TITLE
Option to mirror display disappears when more than 2 monitors are connected 

### ISSUE THREAD

**Issue by TheHarveyBirdman** [solus-project/budgie-desktop#1575]
On: Solus Budgie - stable - up to date

The option to mirror a display disappears when you have more than 2 monitors connected

https://ibin.co/4GeMKeU3Kw9i.png

Reproduce:
Have no more than 2 displays connected. Note the mirror display option is present. Connect another display and the option disappears.

Other users with the issue:
https://www.reddit.com/r/SolusProject/comments/9i2ojt/cant_mirror_monitor/

**Comment by JoshStrobl** [comment]
This isn't an issue with Budgie, this is more GNOME stack items (Control Center, Mutter, etc.)
