### ISSUE TITLE
Constant video playback pauses

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1578]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4

**The issue encountered**

This seems to happen on every video website. It has nothing to do with my internet connection. When I play a video, for instance on YouTube, the frame freezes every several seconds. If I move the mouse to wake the CPU, it resumes moving. Otherwise, it might be up to 10 seconds before it continues.  Furthermore, I think this affects the entire browser window, not just video playback, for example the whirlpool thingy that spins when it's waiting on something. All this started weeks to months ago. I'm not sure when, but it wasn't always this way. Try both Firefox and Chrome if you can't get it to occur.

**Steps to reproduce the issue**

Go to YouTube (perhaps with a recent Intel integrated video controller). Watch a video. See it pause.

**Comment by JoshStrobl** [comment]
Likely nothing to do with Budgie. File this at https://dev.getsol.us
