### ISSUE TITLE
Application icons on panel

### ISSUE THREAD

**Issue by dokker** [solus-project/budgie-desktop#1579]
**Operating System**: 4.18.8-arch1-1-ARCH
**Budgie version**: budgie-desktop 10.4+123+gf2dbc215-1

**The issue encountered**

Hi,

After upgrading to 10.4 the Spotify icon on the panel changed to a default state. I don't know if it is just a spotify issue or budgie. Please let me know If I should post somewhere else.
![spotify_icon](https://user-images.githubusercontent.com/607583/46012932-f7e97880-c0ca-11e8-9693-779d09444e10.png)

By the way before the upgrade the foxitReader's icon was in default state in another way:
![foxit_icon](https://user-images.githubusercontent.com/607583/46013013-37b06000-c0cb-11e8-8ac5-25e1cf0773d5.png)

I tried to change my icon theme but it didn't solve the issue.

**Steps to reproduce the issue**
Upgrade to budgie 10.4 and install spotify

 ...

**Comment by marc0tjevp** [comment]
I have the same issue with Spotify and Budgie 10.4

**Comment by JoshStrobl** [comment]
This has since been resolved in git for Budgie 10.5 with our new Icon Tasklist.
