### ISSUE TITLE
Discord always shows at least two icons and one stays until reboot

### ISSUE THREAD

**Issue by RayBB** [solus-project/budgie-desktop#1580]
**Operating System**: e.g. Solus 3.999
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**

I'm running on the latest stable of everything and recently installed discord. (I tried with eopkg and snap) Either way I install it there's always a second icon when it opens. Example
Any ideas how this can be fixed? If I quit discord only one icon stays but then if I open it again after quitting there are three icons.

Rebooting makes it go away but it's quite annoying to do that.

Here's an example image:
![image](https://user-images.githubusercontent.com/921217/46040261-d0e87200-c0dd-11e8-8b0c-20d40bb5dd2c.png)

**Steps to reproduce the issue**
1. Install Discord
2. Open Discord
3. Close Discord
4. Open Discord
5. Now there are three discord icons at the bottom.

Link to reddit thread where I first posted this:
https://www.reddit.com/r/SolusProject/comments/9iusmd/why_does_discord_open_two_icons_and_one_stays/

PS: I was advised to post here but feel like this could be a Discord issue but not sure.

**Comment by Miclebrick** [comment]
I have Discord, I installed it with the deb from the discord site, no issue
