### ISSUE TITLE
[FEATURE REQUEST] super+ num to launch pinned apps

### ISSUE THREAD

**Issue by kp2401075** [solus-project/budgie-desktop#1584]
Adding a feature to budgie desktop

Launch pinned app with super + nun key

Something like the os which shall not be named here

Thanks and kind regards to solus team

**Comment by proudlytm** [comment]
+1 !

But to launch any app from the task list, not just the pinned apps. 

I'd really appreciate it, if that feature request gets approved, since I used it a lot on Ubuntu 18.04, but now that I am on Ubuntu Budgie 18.04, I really miss it..

**Comment by JoshStrobl** [comment]
Duplicate of #1015
