### ISSUE TITLE
Places Applet : adapt its icon size regarding panel size ?

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#1585]
Hi,
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**:  budgie-desktop 10.4

**The issue encountered**
When used in larger panels ( lets's say above 45 px ) places' folder-symbolic icon stays at its « menu » size. It looks quite little if near, for example, icon tasks list.

**Steps to reproduce the issue**
Add a left panel of 53px size, where you put side to side Places applet and Icon Tasks List applet.

**What one may expect**
A folder-symbolic icon of the same size as the icons in Task List.
The ability to eventually select another icon would be nice too.

**for reference**
https://discourse.ubuntubudgie.org/t/places-applet-change-icon/907

![capture du 2018-10-01 01-45-38](https://user-images.githubusercontent.com/1895947/46264318-bcf8a200-c51b-11e8-9473-3a4d239aaa0a.png)

**Comment by JoshStrobl** [comment]
This happens regardless of the applet, those don't scale. Closing the issue since it won't be addressed until Budgie 11, which will be on a different development tracker.
