### ISSUE TITLE
meson.build fails to recognize libmutter-3.so

### ISSUE THREAD

**Issue by SapiensAnatis** [solus-project/budgie-desktop#1587]
**Operating System**: e.g. Arch Linux (rolling release)
**Budgie version**: master at time of writing: https://github.com/solus-project/budgie-desktop/commit/00b0fe445694d14d4e6859f92a9e4a021b58d4e8

**The issue encountered**

 When attempting to build budgie-desktop from source, the meson command only looks for libmutter-2, libmutter-1, libmutter-0 and libmutter. On Arch, with mutter 3.30:

```
$ pacman -Q mutter
> mutter 3.30.0+13+g2fb3db765-1
```

In the build guide in the wiki it says only mutter >= 3.32 is required, which should mean that I can build it. I've tried adding a copy-paste section to meson.build in src/wm/ to search for libmutter-3.so (which is on my system, I've checked) but it doesn't seem to change anything

**Steps to reproduce the issue**
- Have mutter 3.30
- Clone git repo and respective submodules
- Attempt to run `meson build --prefix=/usr --sysconfdir=/etc`
- Fails

----

I get that this is probably a case where the issue lies between the keyboard and the chair (i.e. me) but even if it is true that budgie cannot yet be compiled against libmutter-3, it'd be nice for you to add a note in the build wiki saying that this is the case. Thank you!

**Comment by JockeTF** [comment]
See pull request #1523 for this. But, I'd recommend the following branch:

https://github.com/UbuntuBudgie/budgie-desktop/tree/mutter330reduxII

**Comment by fossfreedom** [comment]
@JockeTF 

I'll do a PR shortly - kind of got stuck on a couple of issues - so the PR will be just a reference point - to be ignored/cherry-picked etc etc.
