### ISSUE TITLE
Unable to Compile Budgie-Desktop on Solus Due to Missing (But Installed) Dependencies

### ISSUE THREAD

**Issue by moriel5** [solus-project/budgie-desktop#1589]
Solus 3.9999
Budgie-Desktop v10.4-85-g36667bcb

I was trying to compile the latest git version of Budgie-Desktop on my Laptop, running Solus (of course), however Meson spits out errors about missing dependencies, all of which are actually installed, such as `ibus-1.0`, when `iBus is actually installed on my laptop already (no dualbooting).

1. Clone the latest git version of Budgie Desktop.
2. Run "meson build"

"Missing" dependencies according to meson.build:
`ibus-1.0`;
`gnome-desktop-3.0`
`gsettings-gnome-schemas`
`libwnck`
`accountsservice`

**Comment by alunux** [comment]
Did you follow the wiki?

**Comment by moriel5** [comment]
Sorry, I don't always have access to the internet nowadays (since I had moved to a different room in the house).
I'll check the wiki when I'll be able to.
