### ISSUE TITLE
Crashing when Clock Applet and Status Applet menus are both up

### ISSUE THREAD

**Issue by PariahVi** [solus-project/budgie-desktop#159]
Somehow, when I have managed to click the default clock applet to get the calendar up and click on the status applet right afterwards to bring that menu up without closing the calendar from the clock applet.  When that happens, everything freezes, but flash appears to still work, at least with sound. *I was on a different workspace than the browser, so I couldn't check video*

I got this to happen twice and I did not check to see if I could do Ctrl+Alt+F# to get into a console out of X.  I did a force shutdown using the hardware shutdown button both times and I have been trying to reproduce the problem after turning it back on after the second shutdown, but I haven't had any luck repeating the problem.

**Comment by PariahVi** [comment]
So I managed to reproduce the problem.  The only times I can get it to reproduce are when I click the status applet, then the clock applet, then the status applet again.  It doesn't happen enough for it to happen on demand.  When I reproduced the problem, I went into a virtual console with Ctrl+Alt+F1 and used `top` to see a little bit more into why everything was freezing.  Top showed that budgie-panel was using up 97-99% of the CPU, so there is quite possibly an infinite loop going on somewhere, although I don't know enough in this case to really diagnose any problems.

My distro is Arch Linux 64-bit and I had gnome-control-center installed in addition to budgie-desktop-git from the Arch User Repository so the dependencies would be installed automatically.

**Comment by theSoenke** [comment]
Have the same problem when the menu is open and then click on the shutdown button. Same software setup as @PariahVi

**Comment by ikeydoherty** [comment]
Reproduced locally - will let you know when I have a fix (they're fighting :))

**Comment by ikeydoherty** [comment]
Resolved. Please confirm using latest git.

**Comment by PariahVi** [comment]
Sorry for the late reply.  I just tested out the latest git and it works perfectly! Thanks!

I'll close this issue now.

**Comment by ikeydoherty** [comment]
Awesome - thanks :)
