### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Dirli** [solus-project/budgie-desktop#1590]
Operating System: Gentoo
Budgie version: current

../budgie-desktop-10.4/src/raven/headerwidget.vala:25.5-25.24: error: Property `Budgie.HeaderExpander.expanded' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool expanded {

../budgie-desktop-10.4/src/raven/raven.vala:150.5-150.39: error: Property `Budgie.Raven.screen_edge' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public Gtk.PositionType screen_edge {

**Comment by JockeTF** [comment]
See #1591.

**Comment by JoshStrobl** [comment]
Closing as duplicate.
