### ISSUE TITLE
Hotkeys to move current window 1 workspace right or left.

### ISSUE THREAD

**Issue by RasmusKallas** [solus-project/budgie-desktop#1592]
**Operating System**: Ubuntu Budgie 18.04LTS
**Budgie version**: Budgie 10.4

[From Ubuntu Budgie forums.](https://discourse.ubuntubudgie.org/t/hotkey-to-move-active-window-1-right-and-1-left/1077)

There should be 2 hotkeys to move current, selected window 1 workspace right or left.
Currently the only way to move windows with hotkeys is 'move to workspace *'.

**Comment by nunocastromartins** [comment]
If I understand your request correctly, this is already possible using `dconf`.

The keys are `move-to-workspace-left` and `move-to-workspace-right` under `/org/gnome/desktop/wm/keybindings`.

You can set them using `dconf-editor` or via terminal with something like:
```sh
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left "['<Shift><Ctrl><Alt>Left']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right "['<Shift><Ctrl><Alt>Right']"
```

**Comment by JoshStrobl** [comment]
For Solus, we already ship with keybinds enabled for moving an application between workspaces. Not our responsibility to apply it to Ubuntu Budgie.
