### ISSUE TITLE
button-layout

### ISSUE THREAD

**Issue by marek287** [solus-project/budgie-desktop#1593]
Manjaro Linux
budgie-desktop 10.4+123+gf2dbc215-1
After upgrading my system I can't change button layout with dfconf editor to some apps.
![bwm](https://user-images.githubusercontent.com/9947650/46757117-dd6dec80-ccd1-11e8-8ef5-b8cbdb518a33.jpg)

**Comment by alunux** [comment]
@marek287 Go to `org.gnome.desktop.wm.preferences`

**Comment by marek287** [comment]
Thank you. Arch Linux wiki seems to be out of date now.
