### ISSUE TITLE
Wine did not install correctly through app installer...Wine solution....Install wine through commandline or use electron...flatpak it. 

### ISSUE THREAD

**Issue by kjm489** [solus-project/budgie-desktop#1595]
Specs...Intel Lenovo v110 series 14IAP Solus 3.999 budgie fully updated. 
Wine did not install properly...uninstalled through command line....Then used electron and flatpak system and used terminal to add it...Any questions just ask...American expat ethical hacker residing in China. -

 Sincerely, Darkelf2000

**Comment by JoshStrobl** [comment]
None of this has anything to do with Budgie.
