### ISSUE TITLE
Raven above 100% bar expands raven size on login/panel resize

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1604]
**Operating System**: Ubuntu Budgie 18.04 GTK+ 3.22
**Budgie version**: https://github.com/solus-project/budgie-desktop/commit/125637b03934988128f410df2a2517b3e18d24fa

**The issue encountered**

On panel restart/logout login - raven is wider than when above 100% option is first toggled on

Picture on first toggle on above 100% option

![workspace 1_082](https://user-images.githubusercontent.com/996240/47321529-f91bb000-d64c-11e8-8142-e52678db63c4.png)

Picture on panel restart / logout and login

![workspace 1_081](https://user-images.githubusercontent.com/996240/47321545-046edb80-d64d-11e8-9ad6-6e297b6a2a64.png)

 ...

**Steps to reproduce the issue**

Toggle above 100% option in budgie-settings.

Restart the panel/logout and login.

 ...

**Comment by JoshStrobl** [comment]
Unable to reproduce using Adapta. Seems more like a theming issue than anything else.

**Comment by fossfreedom** [comment]
hmm ... also occurs with the built-in theme as well

above 100%

![ubuntu budgie test running - oracle vm virtualbox_087](https://user-images.githubusercontent.com/996240/47970976-253f2400-e084-11e8-8c77-80bd933ea163.png)

and standard volume

![ubuntu budgie test running - oracle vm virtualbox_088](https://user-images.githubusercontent.com/996240/47970985-36883080-e084-11e8-933b-1fba6dafb378.png)

**Comment by JoshStrobl** [comment]
Cheers. Yea the internal theming clearly needs to be unborked, likely the issue has to do with the steps being added rather than just having an indicator like Adapta has.

**Comment by JoshStrobl** [comment]
Unable to reproduce against git with built-in theme + dark theme + Arc set.

![old-theming-raven](https://user-images.githubusercontent.com/156574/49308038-bc5e9680-f4df-11e8-8c28-53fcc5d1fe22.png)

**Comment by JoshStrobl** [comment]
Note: On panel restart, it does show two labels, but Raven still remains the same size.
