### ISSUE TITLE
Mouse suddenly goes crazy, necessitating shutdown

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1605]
**Operating System**: Solus 3.9999
**Budgie version**: 10.4

**The issue encountered**

I just started experiencing this in the past week or so. After an hour or so of use, probably at random, the mouse starts going crazy. It doesn't matter whether it's a USB mouse, or just the touchpad. The problem is unfixable and requires a restart, but even that is difficult to accomplish with the mouse randomly clicking and dragging all over the place. It's as though you've missed a hardware notification that a mouse button is being held down when it's not. But I'm not entirely sure because, once it starts happening, it sometimes goes into remission for a few seconds, allowing normal mouse control, before going crazy again. I tried unplugging and replugging my USB mouse during this problem, but it just continued to occur immediately afterward.

**Steps to reproduce the issue**

Not very clear. Perhaps typing and using the mouse a lot in succession would help. For test purposes, you might want to put the mouse on a vibrating surface so it's constantly activated. Touching all the shift keys don't fix it, so it doesn't appear to have anything to due with stuck shift states.

 ...

**Comment by JoshStrobl** [comment]
Closing as duplicate.
