### ISSUE TITLE
Icons disappearing

### ISSUE THREAD

**Issue by odonnellnoel** [solus-project/budgie-desktop#1608]
When reporting issues for Budgie Desktop, ensure you read these guidelines and delete this first
introductory paragraph. If including build failures, or general tool output, please ensure they are
in English, i.e. `LC_ALL=C LANG=C`. If your issue is a Budgie *crash*, include a stack trace. (gdb)

**Operating System**: e.g. Solus 1.2.0.5
**Budgie version**: i.e. Budgie 10.2.7 OR specific git commit

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

    budgie-desktop --version

**The issue encountered**
https://github.com/solus-project/budgie-desktop/issues/1082
 ...

**Steps to reproduce the issue**
https://github.com/solus-project/budgie-desktop/issues/1082

 ...

**Comment by yursan9** [comment]
I don't think you need to make new issues if you end up having the same bug from #1082
