### ISSUE TITLE
Shutdown / Restart on Ubuntu

### ISSUE THREAD

**Issue by funnylookinhat** [solus-project/budgie-desktop#161]
Clicking "Shutdown" or "Restart" has no effect on Ubuntu.  I suspect this has to do with the session manager - but I'm not sure where else to go from here.  I can't find the applicable lines within the code to try to work backwards from this though - so any suggestions would be welcome.

**Comment by ikeydoherty** [comment]
Was this resolved with the other changes ?

**Comment by Justinzobel** [comment]
@ikeydoherty just did a fresh 15.04 with budgie from git, restart and shutdown working from budgie-session-dialog

**Comment by funnylookinhat** [comment]
Yes!  It was a polkit issue that was resolved.

**Comment by ikeydoherty** [comment]
Awesome, thanks
