### ISSUE TITLE
budgie-panel only shows on workspace 1 when running alongside openbox

### ISSUE THREAD

**Issue by txtsd** [solus-project/budgie-desktop#1610]
**Operating System**: Archlinux
**Budgie version**: i.e. Budgie 10.4+123+gf2dbc215-1

**The issue encountered**
When using `budgie-panel` alongside `openbox`, the panel only shows on the first workspace. When switching workspaces, the panel disappears.
This happens, both, when there is no DE (only using openbox + budgie-panel), as well as when running a custom gnome-session (`/usr/bin/budgie-desktop --session=budgie-openbox.session`) which replaces `budgie-wm` with `openbox`.

**Steps to reproduce the issue**
Launch budgie-panel when using no DE and only `openbox`
OR
Launch a custom gnome/budgie session replacing `budgie-wm` with `openbox`

**Comment by JoshStrobl** [comment]
Budgie is currently designed to work in conjunction with budgie-wm, not OpenBox, i3wm, etc. I'm not saying we won't be re-evaluating support for other window managers / compositors for Budgie 11, but I'm going to mark this as closed seeing as it is not technically an issue, just a result of Budgie 10's intended design.

**Comment by txtsd** [comment]
Disappointing, but fair enough. Will it not even be marked as an enhancement for the future?
