### ISSUE TITLE
Window caption font doesn't apply to GTK3 windows

### ISSUE THREAD

**Issue by jrnart** [solus-project/budgie-desktop#1614]
**Operating System**: Solus 3.9999
**Budgie version**: budgie-desktop v10.4-133-g6f75bbd3

**The issue encountered**
The headerbar font doesn't change even though you change it from Budgie settings or gnome-tweaks.

https://i.imgur.com/xEPivCi.png

**Steps to reproduce the issue**
Change header font from Budgie settings (the first setting on the Fonts tab)

**Comment by JoshStrobl** [comment]
> The headerbar font doesn't change even though you change it from Budgie settings or gnome-tweaks.

Then it isn't a Budgie issue.
