### ISSUE TITLE
Backlight shortcuts makes DE slow and/or unresponsive

### ISSUE THREAD

**Issue by minervamcdonalds** [solus-project/budgie-desktop#1615]
**OS** Solus 3.9999
**budgie-desktop** v10.4-85-g36667bcb
Fully updated system as 11-09-2018
Dell Inspiron 3520

**The issue encountered**
When setting the backlight from the keyboard shortcuts, budgie will become slow, unresponsive, apps will not launch, etc. Only way to get control back is to end the session via ctrl+alt+del and login again.

**Steps to reproduce the issue**
Simply pressing the backlight shortcut, in my case, Fn+F4 or Fn+F5.
Setting backlight from the energy settings works as expected.

**Tested solution**
Already tried to add acpi_backlight kernel parameters, as seen [here](https://getsol.us/articles/troubleshooting/boot-management/en/), since proposed as solution to similar problem posted [here](https://bbs.archlinux.org/viewtopic.php?id=124307). No success.

**Comment by minervamcdonalds** [comment]
Found a solution!
Simply applied the fix found on the GNOME/Troubleshoot page of Arch Wiki. It it, in fact, [a problem related to my keyboard layout, Brazilian ABNT2](https://wiki.archlinux.org/index.php/GNOME/Troubleshooting#Gnome_freezes_for_a_second_after_using_a_Function_.28Fn.29_key_shortcut).

Searching the problem and seeing the number of people relating the same problem, however, get me wonder if _all_ of them are using a brazilian layout.

**Comment by JoshStrobl** [comment]
Closing to due it not being a Budgie issue.
