### ISSUE TITLE
Battery icon inconsistent with percentage

### ISSUE THREAD

**Issue by KloudKoder** [solus-project/budgie-desktop#1618]
**Operating System**: Solus 3.9999
**Budgie version**: 10.4

**The issue encountered**

The battery icon is almost full (mostly white with a little gray at the top), but percentage currently reads 41%. Based on how long it's been since the last charge, I would say that the percentage is right, not the icon.

**Steps to reproduce the issue**

No idea. I've never noticed it being wrong before. Doing a Budgie reset at the command line does not fix it, so I suspect this is a different issue than https://github.com/solus-project/budgie-desktop/issues/769 .

**Comment by JoshStrobl** [comment]
I don't consider this to be a bug, as it is working as intended and we're working with the limited battery state icons available to us.

See https://github.com/solus-project/budgie-desktop/blob/master/src/applets/status/PowerIndicator.vala#L77
