### ISSUE TITLE
Notifications leave room for top panel even with no panel

### ISSUE THREAD

**Issue by danrobinson78** [solus-project/budgie-desktop#1619]
**Operating System**: Solus 3.9999
**Budgie version**: 10.4.85-g36667bcb

**The issue encountered**
Notifications leave space for top panel, even with no top panel. Leaves an awkward looking gap. Especially noticeable now that the default layout in Budgie seems to be bottom panel only. Padding looks to be hardcoded into the source. I'm assuming it may cause issues if you're using a non-default panel height on the top as well, although I haven't tested it.

**Steps to reproduce the issue**
Create a notification somehow.
![screenshot from 2018-11-11 20-46-11](https://user-images.githubusercontent.com/32584841/48321904-db5dbd00-e5f2-11e8-9837-1de5c5597a99.png)

**Comment by thesoulless78** [comment]
I'm willing to try to fix this but I want to make sure it's worth doing and that entire code isn't getting scrapped for Budgie 4 imminently, before I put the work in.

**Comment by JoshStrobl** [comment]
While there's been a fair few improvements thanks to @EbonJaeger's work on notification positioning customization, I do not consider the current implementation / top positioning to be a bug. It intentionally has an initial buffer zone that is treated as an offset and the Notification has no knowledge of the panel (so it wouldn't be able to adjust accordingly).
