### ISSUE TITLE
DSL/PPPoE option is present in nm-connection-editor, but doesn't work

### ISSUE THREAD

**Issue by Hasshu** [solus-project/budgie-desktop#1621]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie v10.4-85-g36667bcb

**The issue encountered**

The other day I decided to give Solus a try, but had to uninstall it, since I wasn't able to connect to my ISP: it is possible to add and set up a DSL/PPPoE connection in nm-connection-editor, but any attempts to use it result in disconnect notifications popping up. Incidentally, I had no such issues with nm-connection-editor in other distros. It seems that some package (that should have been bundled) is missing.

**Steps to reproduce the issue**

1. Add a DSL/PPPoE connection in nm-connection-editor, and set it up.
2. Try to reach the Internet via the said connection.
3. Experience grief as nothing happens.

**Comment by JoshStrobl** [comment]
This is not related to Budgie.

**Comment by Hasshu** [comment]
@JoshStrobl Erm... There is basically a dummy option in the DE due to this issue. If you don't think it belongs here, maybe you could forward it to the right place, at least?

**Comment by JoshStrobl** [comment]
You use Solus. The appropriate place is the Solus development tracker.
