### ISSUE TITLE
Notification window does not disappear properly.

### ISSUE THREAD

**Issue by Alexander88207** [solus-project/budgie-desktop#1622]
Arch Linux & happends also in Manjaro (but not in Solus) with budgie-desktop 10.4

if a notification appears and then automatically disappears or get closed, then leaves the window leftovers, which then go away as in the [screenshot](https://cdn.discordapp.com/attachments/483946408676818974/511693152206192640/ezgif.com-video-to-gif.gif) or start to flicker (screenshot soon)

**Comment by fossfreedom** [comment]
Known issue as discussed here - https://github.com/solus-project/budgie-desktop/pull/1591

Need to figure out why the animation section of budgie-desktop is not working with GTK+3.24/Mutter 3.30

In the interim turn off animations in budgie-settings

**Comment by CrackedCrafterz** [comment]
Okay good to know. Thank you for the feedback 😃

**Comment by Alexander88207** [comment]
Fixed by commit 65ea9b242e7721aee163662485c2f6ddc18c9fc5
