### ISSUE TITLE
Upstreaming network applet

### ISSUE THREAD

**Issue by danielpinto8zz6** [solus-project/budgie-desktop#1623]
I've built a network applet, a fork of elementary os network indicator.
What about including it, replacing the nm-applet?
https://github.com/danielpinto8zz6/budgie-network-applet/tree/wip

**Comment by danielpinto8zz6** [comment]
Hi again,
So, I've seen that https://www.youtube.com/watch?v=wjuamlW6Zxw
I'm just curious, what are your expectations about a network applet?
I really didn't liked the initial design too, that why I showed the wip branch wich has a redesign.
Cheers

**Comment by danielpinto8zz6** [comment]
Okay,

**Comment by danielpinto8zz6** [comment]
Oh, okay
here's how it looks atm
![captura de ecra de 2018-11-20 18-21-16](https://user-images.githubusercontent.com/8846362/48794200-26fa2000-ecf1-11e8-9397-81701d31ac8f.png)

**Comment by Jacalz** [comment]
This looks really good in my opinion! I would gladly see this in budgie at some point, since it seems to be a great improvement to what we have now :+1:

**Comment by Justinzobel** [comment]
@DataDrake / @JoshStrobl any movement on this front?

**Comment by Krutonium** [comment]
Ping - I would love to see this in the next release.

**Comment by Jacalz** [comment]
It would be wonderful if we could see this included in Budgie. It looks great!

Would like to see a screenshot of it using the Plata and Plata Noir theme if possibles. The current manager doesn’t really change it’s color when switching to a dark theme. Great job btw 👍

**Comment by JoshStrobl** [comment]
This is not going to be featured in the next release of Budgie. Budgie 10.5.x is feature-freeze and we will have a separate implementation for Budgie 11.
