### ISSUE TITLE
workspace switch animations

### ISSUE THREAD

**Issue by whoizit** [solus-project/budgie-desktop#1628]
I have fresh Solus installation. How can I disable workspace switch animations?

**Comment by Alexander88207** [comment]
I think to disable that you must disable all desktop animations :/ but I could be wrong too
![bildschirmfoto vom 2018-11-24 12-51-15](https://user-images.githubusercontent.com/37543796/48967933-4b534680-efe8-11e8-82d0-6c618520e987.png)

**Comment by whoizit** [comment]
this not works for me, even after reboot. Seems like it's disable menu show/hide animations, but not animations workspace switch. I have updated Solus

**Comment by JoshStrobl** [comment]
Considering this a low priority issue that isn't going to realistically be addressed until Budgie 11, when we have our own window manager that doesn't rely on Mutter. As such, closing this issue.
