### ISSUE TITLE
[abomination.vala] Some apps cause a crash with new "abomination" mechanism?

### ISSUE THREAD

**Issue by tista500** [solus-project/budgie-desktop#1630]
**Operating System**: Ubuntu 19.04 development branch
**Budgie version**: v10.4-142-gf342f930
**libwnck-3-dev**: 3.30.0-1
**libmutter-2-dev**: 3.28.3-2~ubuntu18.04.2 (I compiled budgie with libmutter-2 instead of libmutter-3)
**libglib2.0-dev**: 2.58.1-2

**The issue encountered**
`xev`, `glmark2` and `vulkan-cube` from terminal cause budgie session crash (glxgears as well?)...

the output of bt from gdb:
```
#0  0x00007ffff7238cc0 in g_str_hash () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7237efc in g_hash_table_lookup () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fffea1e3dab in budgie_abomination_add_app (self=0x5555557325d0, window=0x55555605b460)
    at ../src/abomination/abomination.vala:78
#3  0x00007fffea1e3788 in __lambda8_ (self=0x5555557325d0, window=0x55555605b460)
    at ../src/abomination/abomination.vala:52
#4  0x00007fffea1e37b1 in ___lambda8__wnck_screen_window_opened
    (_sender=0x555555cded70, window=0x55555605b460, self=0x5555557325d0) at ../src/abomination/abomination.vala:51
#5  0x00007ffff7329b6d in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff733c8f3 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7345882 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7345ecf in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7178383 in  () at /lib/x86_64-linux-gnu/libwnck-3.so.0
#10 0x00007ffff7178c84 in  () at /lib/x86_64-linux-gnu/libwnck-3.so.0
#11 0x00007ffff7249ae8 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff7249ed8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff724a1d2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff7969685 in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00005555555666d1 in  ()
#16 0x0000000200000810 in  ()
#17 0x00007fffffffdd98 in  ()
#18 0x00007ffff7004040 in flush_cleanup () at /lib/x86_64-linux-gnu/libc.so.6
#19 0x0000000000000000 in  ()
```

I'm not sure but `app.group` may or may not `null` in `this.running_apps.get(app.group)`. I know those apps are not major but I need some of them to do OpenGL/Vulkan stress tests on my iGPUs. And my env has multiple versioned libmutters (2 and 3), so this might not be the standard case...
Is it possible to reproduce with dev's environments like SolusOS?

**Steps to reproduce the issue**
* Pull git master f342f930
* Build budgie with libmutter-2-dev (without any extra downstream patches)
* Login and run gnome-terminal, then run `xev`, `glmark2` and `vulkan-cube` for example
* Session crash happens and display-manager login screen comes up.

Best regards.

**Comment by JoshStrobl** [comment]
I'll take a look at this immediately, thanks!

**Comment by JoshStrobl** [comment]
While it doesn't cause my session to crash, it does cause budgie-panel to crash, which is equally ungood. Working on a fix.
