### ISSUE TITLE
Exclude notifications from notifications list

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1634]
At the moment, it's possible to disable notification _pop-ups_, however there is no way to prevent the notificaiton from appearing in the _notification drawer_ in Raven. Some apps (e.g. [FeedReader](https://jangernert.github.io/FeedReader/)) leave notification control to the desktop environment, meaning there is no way in Budgie to disable all notifications in such cases.

Another reason for being able to control which apps can send notifications to the drawer is that not all notifications are important enough to not be missed: song changes in certain apps, external drive mount status and others particular to a user. Currently, as both important and not-important notifications always get logged in the drawer, using the drawer is more of a chore to constantly clean it rather than having it as a helpful notifier for things important to the user.

For these reasons, it should also be possible to control which apps can send notifications to the drawer as opposed to pop-ups alone.

**Comment by JoshStrobl** [comment]
You can already exclude certain apps using GNOME Control Center's Notification section, so long as you're building against git.

**Comment by hfel** [comment]
> You can already exclude certain apps using GNOME Control Center's Notification section, **so long as you're building against git**.

A rather non-technical user here, could you elaborate on the emphasized part? Does it mean that it's only possible to control notification drawer logging for apps built from git?

**Comment by yursan9** [comment]
![screenshot from 2018-12-04 09-32-19](https://user-images.githubusercontent.com/17114559/49414942-aedb3200-f7a7-11e8-97ee-79f5b23d7f97.png)
