### ISSUE TITLE
Unable to Compile Budgie-Desktop due to Missing Alsa?

### ISSUE THREAD

**Issue by moriel5** [solus-project/budgie-desktop#1636]
Operating System: Solus 3.9999 (Unstable)

The issue encountered:
For some odd reason, since last week, whenever I attempt to compile `budgie-desktop`, Meson spits out that `alsa` is missing, which prevents Ninja from compiling the project.

Steps to reproduce the issue:
After cloning, "meson --prefix /usr --libdir /usr/lib64 --sysconfdir /etc -Dwith-stateless=true build --buildtype plain" with the error:
"|Dependency alsa found: NO (tried pkgconfig)

subprojects/gvc/meson.build:60:2: ERROR:  Dependency "alsa" not found, tried pkgconfig"

, which prevents "ninja -j$(($(getconf _NPROCESSORS_ONLN)+1)) -C build" from compiling the project.

**Comment by EbonJaeger** [comment]
Need the alsa development files now for Budgie. On Solus the package is `alsa-lib-devel`.

**Comment by moriel5** [comment]
Thanks, oddly enough, I did not find that package in the Software Center last week (I mainly use the new one for discovery, while directly invoking `eopkg` for installation.

**Comment by lupodellasleppa** [comment]
Having same problem in Ubuntu 18.04, I have
- `alsa-base`
- `alsa-utils`
- `gstreamer1.0-alsa`
- `libasound2`

installed, however when I try to run 
```
meson build --prefix=/usr --sysconfdir=/etc
```

I get the following error:
```
subprojects/gvc/meson.build:60:2: ERROR: Native dependency 'alsa' not found
```

**Comment by lupodellasleppa** [comment]
I suggest adding `libasound2-dev` as a requirement for building in Ubuntu since it isn't installed by default and meson will give an error on alsa dependency otherwise
