### ISSUE TITLE
Literally Tried Every Other Linux Distro/DE, Solus/Budgie The BEST!

### ISSUE THREAD

**Issue by pushqrdx** [solus-project/budgie-desktop#1637]
I am so sorry to open this as an issue here but wanted to express my absolute gratefulness for Budgie, I never used Linux before and recently i decided to switch from Windows 10. Tested all DEs out there all of them had either terrible performance or terrible design. Budgie (Ironically i didn't want to try firstly) absolutely strikes both performance and aesthetics. 

Again, gratitude to the developers behind this awesome project.

**Comment by JoshStrobl** [comment]
Thank you for the kind words, it's really appreciated =)
