### ISSUE TITLE
Order applications in panel by drag and drop

### ISSUE THREAD

**Issue by theSoenke** [solus-project/budgie-desktop#164]
Just a small usability thing, but it would be nice if pinned applications in the panel could be ordered by drag and drop with the mouse

**Comment by starquake** [comment]
I would like to add a bounty to this issue but cannot find it on bountysource. Could you fix that?

**Comment by ikeydoherty** [comment]
Bountysource seems broken when it comes to our project, and never worked, so we just kinda stopped using it (as it never seemed to interest anyone :))

**Comment by snwh** [comment]
Bump.

**Comment by ikeydoherty** [comment]
Please don't bump.

**Comment by ikeydoherty** [comment]
Landed in git, will premier in 10.2.8
