### ISSUE TITLE
Live background displays a solid

### ISSUE THREAD

**Issue by giladfrid009** [solus-project/budgie-desktop#1644]
**Operating System**: Solus 3.9999 (in virtualbox)
**Budgie version**: Budgie 10.4-157-g5af3a35d

**The issue encountered**

the live wallpapers doesn't work and display a solid color wallpaper

![image](https://user-images.githubusercontent.com/28793332/49675552-dae40500-fa7e-11e8-89fe-881f50229799.png)

 ...

**Steps to reproduce the issue**

right click on the desktop, choose change background and choose a live wallpaper.
the wallaper changes to a solid color (the first live wallpaper changes the background to blue and the second live wallpaper changes the background to white)

 ...

**Comment by JoshStrobl** [comment]
Live wallpaper isn't supported and may not function as intended, even with the new User Backgrounds functionality added in. This functionality applies to GNOME Shell.
