### ISSUE TITLE
gnome-terminal new tab desktop action does not open new tab

### ISSUE THREAD

**Issue by lallenfrancisl** [solus-project/budgie-desktop#1646]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4
**The issue encountered**
When opening new tab from context menu from panel it does not open a new tab but instead a new window.
**Steps to reproduce the issue**
Right click gnome-terminal from panel and click new tab.

**Comment by JoshStrobl** [comment]
Seems to be an issue with GNOME Terminal itself, as seen [here](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1661211). I've decided to remove the desktop actions from GNOME Terminal specifically.

**Comment by lallenfrancisl** [comment]
But `gnome-terminal --tab` works for us from gnome-terminal when it is **not super user** with error
```
# Failed to load module "/usr/lib/libplotinus.so"
# Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**When it is super user(from a terminal where `su` is running)** we get the error message and **opens in a new window**:
`# Failed to load module "/usr/lib/libplotinus.so"`

**When from a normal terminal typing** `sudo gnome-terminal --tab` will **also give new window** but **no error message.**
