### ISSUE TITLE
the virtualbox symbol disappears in the icon task list.

### ISSUE THREAD

**Issue by Alexander88207** [solus-project/budgie-desktop#1647]
**Operating System**: Arch-Linux
**Budgie version**: v10.4-123-gf2dbc215

i dont know if this is an issue, but I'll report it anyway.

**The Issue**
the virtualbox symbol disappears in the icon task list.
 ...

**Steps to reproduce the issue**
Open VirtualBox
![virtualbox](https://user-images.githubusercontent.com/37543796/49684419-093fff80-fad4-11e8-944b-5819b448f2b9.gif)

 ...

**Comment by JoshStrobl** [comment]
This is incredibly out-of-date and not representative of current Budgie. It also includes a multitude of patches for an unsupported configuration of Budgie, which is on top of the GNOME 3.30 stack. Closing as WONTFIX.
