### ISSUE TITLE
Severe screen tearing in VirtualBox

### ISSUE THREAD

**Issue by giladfrid009** [solus-project/budgie-desktop#1648]
**Operating System**: Solus 3.9999
**Budgie version**:  Budgie 10.4-85-g36667bcd 

**The issue encountered**

when installing Solus in a Virtualbox VM (on windows 10 os) I experience severe screen tearing.
a way to bypass this issue is by pressing host+f1 (terminal view) and then host+f7 (back to GUI)

 I  have this issue with both fully up to date Solus and with freshly installed not up to date version.

![image](https://user-images.githubusercontent.com/28793332/49684940-9c346600-fae3-11e8-99c7-1268a63b24fc.png)

This issue occurs after the installation of the OS and not with the live version from the iso. No issues whatsoever with the live iso. 

also, the OS doesn't seem to auto-resize to the window size of virtualbox.
guest additions are installed.

![image](https://user-images.githubusercontent.com/28793332/49685038-2630fe80-fae5-11e8-8c8c-70a0eb2452af.png)

* i guess this issue has nothing to do with budgie, but i don't know where else to post in. 
 ...

**Steps to reproduce the issue**

install Solus in a Virtualbox.
 ...

**Comment by JoshStrobl** [comment]
Solus has a development tracker at https://dev.getsol.us

**Comment by Alexander88207** [comment]
@giladfrid009 you need to enable EFI 

![image](https://user-images.githubusercontent.com/37543796/49685400-08fb3080-fae3-11e8-874a-3be750260ff4.png)
