### ISSUE TITLE
Print Screen doesn't work if the Super menu is open

### ISSUE THREAD

**Issue by dandv** [solus-project/budgie-desktop#1651]
**Operating System**: Live boot of Budgie 18.04.1
**Budgie version**: i.e. Budgie 10.4

**Steps to reproduce the issue**

1. Press the Super Key (the windows key on my Thinkpad X1C)
2. Press PrtSc

Nothing happens. PrtSc otherwise works. The problem is that I wanted to capture [this bug with the Super menu](https://github.com/solus-project/budgie-desktop/issues/1650) and had to do the extra work of starting the Screenshot app, make it wait for a few seconds etc. instead of just pressing Ctrl+Shift+PrtSc to capture a rectangular area of the screen.

**Comment by JoshStrobl** [comment]
The popovers steal focus, working as intended.

**Comment by dandv** [comment]
I suspect not "as intended" by any user who wants to take a screenshot with the popover open :)
