### ISSUE TITLE
Simulate right mouse button click in the bottom right corner of the touchpad

### ISSUE THREAD

**Issue by dandv** [solus-project/budgie-desktop#1652]
**Operating System**: Ubuntu Budgie 18.04.1
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

Most touchpads nowadays no longer include physical buttons, yet those buttons are useful. For example, holding Alt while dragging with the RMB resizes the window under cursor - a feature I use all the time.

Just as Edge scrolling lets one easily scroll with one finger, an option to simulate the RMB being pressed if the user touches the lower-right corner of the touchpad would be super useful. I know I can simulate a right *click* with a two-finger tap, but that doesn't work if I want to drag with the RMB.

**Comment by JoshStrobl** [comment]
This isn't something we're planning to add to the Budgie 10 series. We may evaluate such emulation in Budgie 11, but closing for now.

**Comment by dandv** [comment]
Fair enough. What is the mechanism to reopen the issues slated for later series?

Perhaps using the Milestones or [Projects](https://github.com/solus-project/budgie-desktop/projects) features in GitHub?
