### ISSUE TITLE
Chromium inactive tab text barely visible with GTK+ theme

### ISSUE THREAD

**Issue by dandv** [solus-project/budgie-desktop#1654]
**Operating System**: e.g. Ubuntu Budgie 18.04
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

Fresh new budgie install. Installed the recommended updates. Didn't change any themes or visual settings. Chrome tabs look like this:

![image](https://user-images.githubusercontent.com/33569/49692996-ab83d580-fb1c-11e8-8f00-3832402f2d4c.png)

This might be a Chromium issue, because I didn't see it in the default version of Chrome that Budgie ships with (67). In that case, please file it at crbug.com.

**Steps to reproduce the issue**

1. Install Budgie
2. Update Chromium to v70.

**Comment by dandv** [comment]
A workaround is to go to `chrome://settings/` and change the theme from GTK+ to Classic.

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue.

**Comment by fqlx** [comment]
Can you escalate this issue to the correct product? I see this too and the tabs are 🤮.
