### ISSUE TITLE
Raven menu - sound apps - Big blue box issue ?

### ISSUE THREAD

**Issue by RubiconTwenty** [solus-project/budgie-desktop#1655]
Solus 3.9999
Budgie-desktop 10.5-173

The issue encountered:
Trying out the new Budgie-desktop build, i noticed that when you left click on a sound app, will result in a big blue square in the apps "box". Changing the sound volume slider or muting the volume wont result in this behavior.
When the blue box is there i cant remove it again, clicking between two sound apps, change the blue box from one app to the other one.

Steps to reproduce the issue:
Open a sound app, then left click on it's name in the Raven menu - "Apps" section.

Not sure if this is a work in progress thing or not working as intended yet ?

**Comment by RubiconTwenty** [comment]
Just wanted to add that i very much enjoy the changes made to Budgie, all the changes in the Raven menu, and the new popover functionality i Budgie, are all really awesome changes. 

Thank you very much and everyone involved for your hard work, i really appreciated it!

**Comment by RubiconTwenty** [comment]
Have tried both Adapta-Eta & Plata-Compact:

file:///home/dave/Pictures/Blue.png

file:///home/dave/Pictures/Blue2.png

**Comment by RubiconTwenty** [comment]
Have tried both Adapta-Eta & Plata-Compact:

![blue](https://user-images.githubusercontent.com/45721068/49705138-6050ec00-fc1c-11e8-9dff-659797e88a1c.png)

![blue2](https://user-images.githubusercontent.com/45721068/49705142-6646cd00-fc1c-11e8-9133-7d86cd64c610.png)

**Comment by EbonJaeger** [comment]
I can reproduce this using Plata-Noir.
