### ISSUE TITLE
Software center icon rightclick "Updates" not working 

### ISSUE THREAD

**Issue by RubiconTwenty** [solus-project/budgie-desktop#1656]
Solus 3.9999
Budgie-desktop 10.5-173
Solus-sc 22-37

The issue encountered:
When rightclicking on the Software center icon in the taskbar, choosing "Updates" does nothing on my system, and if you try it a couple of times the icon sometimes flicker between being bright or dark.

Steps to reproduce the issue:
Open Software center and rightclick on the icon in the taskbar, and choose "Updates" with the left mouse button. If the icon is not flickering try again, or close Software center then open it again and try again.

This might not be a Budgie-desktop issue, maybe it is related to https://dev.getsol.us/R2930:979bf782a6a8f7ec2601b137ace5f2d5276be9b4 - "Add Desktop Action for going to Updates view." in the Solus bugtracker?

**Comment by JoshStrobl** [comment]
> Open Software center and rightclick on the icon in the taskbar, and choose "Updates" with the left mouse button.

That's not how that works. It launches a new instances with the specific action specified in Desktop Actions. If you want the updates view while the application is open, click on it in the app. If you have SC pinned but not launched, clicking the Updates will work as intended.
