### ISSUE TITLE
Login screen picture showing shortly, then switch to desktop wallpaper.

### ISSUE THREAD

**Issue by RubiconTwenty** [solus-project/budgie-desktop#1657]
Solus 3.9999
Budgie-desktop 10.5-173

The issue encountered:
Before switching to Budgie-desktop 10.5-171, 172 or 173, i had a slick-greeter.conf file to show a picture on the login screen, before logging into the Budgie desktop which had a different background. 
With the new Budgie-desktop versions, the picture show very briefly then it fades to the desktop wallpaper, before i log in to the desktop.

Steps to reproduce the issue:
Using this script found on the forum:
sudo mkdir -p /etc/lightdm
echo "[Greeter]" | sudo tee -a /etc/lightdm/slick-greeter.conf
echo background=/"path to your wallpaper" | sudo tee -a /etc/lightdm/slick-greeter.conf
chmod o+r /"path to your wallpaper"

**Comment by fossfreedom** [comment]
That is the inbuilt functionality of slick-greeter which git master now
supports by default.

If you want to have a static slick-greeter background picture set in
slick-greeter.conf

draw-user-backgrounds=false

**Comment by RubiconTwenty** [comment]
Thank you very much fossfreedom, i was not aware of that.

Adding "draw-user-backgrounds=false" to my /etc/lightdm/slick-greeter.conf fixed the issue.

**Comment by thespyboss** [comment]
I also found out, you can change it by using lightdm-settings. Just run sudo lightdm-settings and the setting is be under Appearance. Just turn off Draw user backgrounds.
