### ISSUE TITLE
Sound output widget has wrong name for firefox

### ISSUE THREAD

**Issue by Jacalz** [solus-project/budgie-desktop#1659]
**Operating System**:
Solus 3.9999

**Budgie version**:
Budgie 1.5 latest from 596f0a9

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

budgie-desktop v10.4-160-g596f0a90

**The issue encountered**
 The sound output widget calls Firefox for AudioIPCserver:
![sound](https://user-images.githubusercontent.com/25466657/49700049-c7997c80-fbd9-11e8-9366-f7e87b05edc4.png)

 
**Steps to reproduce the issue**
Switch to unstable repo in Solus and load a tab with some sound playing. ex, play.spotify.com

 ...

**Comment by JoshStrobl** [comment]
So it's a derper like Discord, noted :P
