### ISSUE TITLE
Applications not appearing in panel

### ISSUE THREAD

**Issue by theSoenke** [solus-project/budgie-desktop#166]
Sometimes running applications do not appear in the panel. 

Here is an example with firefox running, but missing in the panel

![budgie](https://cloud.githubusercontent.com/assets/1757301/6200701/f8fab2ae-b483-11e4-871e-fa6f289a1eb4.png)

**Comment by ikeydoherty** [comment]
Need more details please. Host OS, versions involved such as GTK, etc, which version of Budgie.

**Comment by theSoenke** [comment]
I'm using arch. Don't know gtk version, but i've switched now from this package https://aur.archlinux.org/packages/budgie-desktop-git/ to https://aur.archlinux.org/packages/budgie-desktop/
Because it seems to be the never version and now the problem does not occur anymore. My only problem is now that the windows key does not open the menu anymore :)

**Comment by theSoenke** [comment]
I was wrong. It still happens. But it only seems to happen to pinned applications. In the screenshot are files and firefox greyed out, althouth both are running and pinned to the panel. For comparison i also opened settings. A click on firefox in the panel would now open a new window

![budgie2](https://cloud.githubusercontent.com/assets/1757301/6204339/14d29f40-b548-11e4-9386-5ddfa1afa1b0.png)

**Comment by michaelrutherford** [comment]
Having the same issue with Solus Beta 2 running Budgie. Seems that this problem only happens with pinned applications.

**Comment by theSoenke** [comment]
Issue still exist in Budgie v10

**Comment by ikeydoherty** [comment]
I can now reproduce.

**Comment by ikeydoherty** [comment]
Please test from latest git if possible.

**Comment by theSoenke** [comment]
Looks good. Issue seems to be gone :)
Thanks
