### ISSUE TITLE
Desktop icons are cropped out if second monitor is higher than the primary monitor

### ISSUE THREAD

**Issue by nordisker** [solus-project/budgie-desktop#1664]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4-85-g36667bcb

**The issue encountered**
When you have an extended desktop setup and the second monitor is set to be higher than your main screen, the icons in the main desktop get cropped out as seen in the following screenshots.
![desktop1](https://user-images.githubusercontent.com/10269873/49892662-a9798980-fe30-11e8-9fc2-2c8c851274d1.png)

and below is the extended desktop with the setup

![desktop2](https://user-images.githubusercontent.com/10269873/49892675-b0a09780-fe30-11e8-9446-320c40585caf.png)

**Steps to reproduce the issue**

1. Add files to the top edge of the desktop 
2. Connect a second monitor in an extended desktop mode
3. Move the second monitor in display settings to have its top edge above the main monitor's
4. Observe the icons being cropped out

 ...

**Comment by chax** [comment]
I think this is actually the problem with Gnome and not Budgie, but since Budgie is based on Gnome stack it suffers from the same issue.

**Comment by chax** [comment]
It is the bug in Gnome Files (Nautilus) which we are running the version 3.26.4. Nautilus 3.28 removed support for Desktop icons (I guess because of this bug and other things, they just decided they won't fix it), and sometime in the past, @ikeydoherty updated to that version and realized we are missing Desktop icons, so he reverted to 3.26. which we still use to this day.

**Comment by JoshStrobl** [comment]
Closing as wontfix. We won't be addressing this until we have a desktop view baked into the WM (or a separate DESKTOP-type window). Upstream Nautilus resolved the issue but nuking desktop view (as mentioned by @chax) and moving the support to GNOME Shell.
