### ISSUE TITLE
Budgie Crash When run steam

### ISSUE THREAD

**Issue by minamorcose** [solus-project/budgie-desktop#1666]
I Don't Know What is Stack Trace So It There is any thing you  need You could teach me how i get it and  i will get it 
**Operating System**:  Fedora 29
**Budgie version**: budgie-desktop 10.4 Git Commit (deb7707)
https://copr.fedorainfracloud.org/coprs/alunux/budgie-desktop-git/

    

**The issue encountered**

When running  Steam Budgie crash  Steam

 ...**Steps to reproduce the issue**

Just Run Steam 

I tested on gnome and it worked it's problem with budgie not on steam or drivers 

--------------------------------------------------------------------------------------------------------------

**Comment by JoshStrobl** [comment]
The referenced Budgie Desktop is not one supported by the project, has unsupported applets, introduces a configuration which is not currently supported, etc. This is effectively about as far away from a proper Budgie experience as you can get. I'm able to consistently run Steam successfully on my Solus system.
