### ISSUE TITLE
After update: volume widget in raven up to 150%

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#1667]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4-175-g487eef22

**The issue encountered**
After update: volume widget in raven up to 150% but in settings it is disabled.

**Comment by JoshStrobl** [comment]
Thanks for filing this issue. I've identified the problem and will get it addressed when I wake up.

**Comment by JoshStrobl** [comment]
I'll be updating Solus to latest git. If it isn't resolved on Friday's sync, let me know / re-open.
