### ISSUE TITLE
Some apps have no icons in notifications

### ISSUE THREAD

**Issue by lallenfrancisl** [solus-project/budgie-desktop#1669]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: i.e. Budgie 10.4-175-g487eef22

**The issue encountered**
`gnome-pomodoro` app don't have app icon in notification.
![screenshot from 2018-12-15 21 25 35](https://user-images.githubusercontent.com/21018348/50045060-dd63e180-00b2-11e9-88d6-7b3ca21a8092.png)

**Steps to reproduce the issue**
Open the app and let the notifications come to raven.

**Comment by Alexander88207** [comment]
gnome-terminal also

**Comment by lallenfrancisl** [comment]
They show an icon when the notification appears but not when it comes to raven

**Comment by JoshStrobl** [comment]
Confirmed. This is the result of them using `gnome-pomodoro` when their desktop name is `org.gnome.Pomodoro`. It's not consistent with other GNOME applications, but it is something I can see about supporting by doing a lookup for Icon= in the DesktopAppInfo.
