### ISSUE TITLE
CPU#16 stuck for 23s! 

### ISSUE THREAD

**Issue by r4jk3** [solus-project/budgie-desktop#1671]
**Operating System**:  Solus-3.9999-Budgie.iso

**The issue encountered**
Encountered issue during the system installation on laptop ASUS - FX753VD
Got error message about the: 
`BUG: soft lockup - CPU#16 stuck for 23s! `
It just hangs there like this for ever which prevents start of the system installation process.

**Various systems boot report**
I've tried upgrading BIOS version but still no success in booting up the system.
Boot test on various systems but on same lap top:
- Windows 10 x64 (works without any problems).
- Windows 8.1 x64 (complains about usb 3 drivers).
- Solus complains about soft lockup.
- Manjaro complains about soft lockup.
- Ubuntu is having issues too - installation just freezes (i'm guessing its the same issue).

**Steps to reproduce the issue**
Just mount from DVD and boot it on same hardware as i :)

### ***WORKAROUND / SOLUTION***
During the boot menu instead of proceeding with installation (and fail) i press E key on keyboad and have added following command at the end of the line: 

> nouveau.modeset=0

i presse enter, and installation continues normally.. (at a time of this edit i'm using Solus OS Buddgie).

I'm not sure what is causing this bug but its very annoying.
Solution for this problem is is taken from youtube and is applicable for Solus as well (at least was in my case was) here is the link:
[https://youtu.be/nPprHes-K_Y](url)

**Comment by JoshStrobl** [comment]
This is not relevant to Budgie. Solus' issue tracker is at https://dev.getsol.us
