### ISSUE TITLE
Night Light doesn't turn off when windows are fullscreen

### ISSUE THREAD

**Issue by JagdCake** [solus-project/budgie-desktop#1673]
**Operating System**: Solus 3.9999 (latest sync (2018-12-14))
**Budgie version**: 10.4-175-g487eef22t

**The issue encountered**
I reinstalled Solus on my laptop and saw that there is an option to "Disable Night Light mode when windows are fullscreen", in the Budgie Desktop Settings. Tried it, works perfectly on the laptop but not on my desktop PC (both are on the latest sync).

I've been using a script to turn off night light in fullscreen apps, by calling `gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false`. The script still works but it requires me to start it manually, so I don't think it conflicts with the integrated option.

**Steps to reproduce the issue**
- Enable the option — "Disable Night Light mode when windows are fullscreen", from the Budgie Desktop Settings, "Windows" section
- When the screen colors become warmer, go fullscreen in any application

**Comment by JoshStrobl** [comment]
> The script still works but it requires me to start it manually, so I don't think it conflicts with the integrated option.

It does, since that is what we're manipulating as well.
