### ISSUE TITLE
Raven Widgets are always expanded after system restart

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#1674]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4-175-g487eef22

**The issue encountered**

Raven Widgets are always expanded after system restart

**Comment by Solarunit** [comment]
budgie-desktop, version: 10.5, release: 183
Still have this problem

**Comment by JoshStrobl** [comment]
I'm not able to reproduce this issue. What settings do you have set under the Raven section in Budgie Desktop Settings?

**Comment by Solarunit** [comment]
![Alt Text](https://ibin.co/4R89D5hy69kl.png)


This is how Raven Widgets look like before reboot:
![Alt Text](https://ibin.co/4R8ACuUrwdCZ.png)


After reboot:
![Alt Text](https://ibin.co/4R8APi9gKhxI.png)

**Comment by JoshStrobl** [comment]
I fail to see what the issue is here. You have things set to show, it's showing, and input isn't, because you have that turned off. It doesn't save its expanded state.
