### ISSUE TITLE
[Feature-Requests] Unintuitive behaviour of Raven Sound Control 

### ISSUE THREAD

**Issue by JonnyCodewalker** [solus-project/budgie-desktop#1676]
**The issue encountered: Slider / Mute button interaction**
After setting the slider to 0 and closing an app, when starting it again the mute button is enabled, even if it was not when closing. Because of this you have to do 2 actions to undo your one action(clicking the button and moving the slider to undo moving the slider). 

**Steps to reproduce the issue**
- Open app with sound
- Set slider to 0
- Close app
- Open app again

**The issue encountered: Slider / Mute button interaction take 2**
Unmuting an app does not set any level of sound, meaning that if you want to unmute an app whose slider is at  0 you have to move the slider afterwards. This is only an issue in regards to the first point here.

**Comment by JoshStrobl** [comment]
This is intentional. Our muted state is actually just setting the volume to 0, since gvc muting is incredibly buggy otherwise.

**Comment by JoshStrobl** [comment]
Concerns likely addressed with refinements at e284bd058055bfb7a8dc74bb419b3ad49277fb7b
