### ISSUE TITLE
Feature Request: StatusNotifier tray.

### ISSUE THREAD

**Issue by rilian-la-te** [solus-project/budgie-desktop#168]
I am already implemented realization, it needs only to ported to Budgie-Panel, as far as I know.

Here is link: https://github.com/rilian-la-te/vala-panel/tree/master/applets/core/sntray

What work I must done to port it to your panel?
Most important part is positioning and configuration dialog.

**Comment by ikeydoherty** [comment]
Out of curiosity why haven't you looked at merging our efforts?

It's quite clear you follow budgie-panel closely, your toplevel README imitates our README in every possible way (it uses my own style and language.)

**Comment by ikeydoherty** [comment]
Uh hold on a minute here dude.

https://github.com/rilian-la-te/vala-panel/commit/e5e2add59b6dd82ddd7a2b8696ccccae085b44bc
https://github.com/rilian-la-te/vala-panel/commit/4f4f8ec3f60c2ecbd42a45d5a2793d37e2cdbb9b

Wanna explain?

**Comment by ikeydoherty** [comment]
Nvm. So if you're using budgie stuff within vala-panel, you'll need to point out somewhere that you're doing so :) (Its part of using the GPL)

Also, I'd suggest altering the text of your README as it is content written for Budgie Desktop, and as such it indicates a connection that does not exist, and could be misconstrued as purposeful plaigarism.

If you wanna chat about this some more, just drop me an email to ikey@evolve-os.com.

In the mean time, wrt. sntray, there are some things that would need fixing prior to inclusion in Budgie. The use of QMarkup parsing isn't required as GLib/GTK already has internal markup support, best to leave it to them =)

**Comment by rilian-la-te** [comment]
I have emailed to you.
