### ISSUE TITLE
Impossible to navigate in the menu using only keyboard keys

### ISSUE THREAD

**Issue by mimi89999** [solus-project/budgie-desktop#1680]
**Operating System**: Debian GNU/Linux buster/sid
**Budgie version**: 10.4+git20180830.02.f2dbc215fdb-2

**The issue encountered**

After opening Budgie Menu with the super key, I can't navigate in it using my keyboard arrows. I can navigate between the search field and the all category and then scroll in it. It is however impossible to navigate between categories.

**Steps to reproduce the issue**

Open Budgie Menu and try to navigate between categories using only your keyboard.

**Comment by fossfreedom** [comment]
Duplicate of this https://github.com/solus-project/budgie-desktop/issues/1240

**Comment by mimi89999** [comment]
Sorry
