### ISSUE TITLE
budgie-desktop.org domain expired

### ISSUE THREAD

**Issue by thehandytek** [solus-project/budgie-desktop#1681]
budgie-desktop.org domain expired

Displayed at the top of the page...

This domain name expired on 2018-12-24 11:28:17 
Click here to renew it.

**Comment by JoshStrobl** [comment]
Yes, unfortunately Ikey has not been in contact with me since he left the project, despite my multiple attempts, so I never was provided access (or clarification on it) to the domain. Nothing I can do about it until it is available for purchase.
