### ISSUE TITLE
Libreoffice tasklist icon disappears if only one of many windows is closed

### ISSUE THREAD

**Issue by stevenmos** [solus-project/budgie-desktop#1682]
**Operating System**: Solus 3.9999 (linux 4.19.9-105.current)
**Budgie version**: budgie-desktop 10.5 (git-8a710056664f860224d4260b566d248948866a90)

**The issue encountered**

If one has more than one libreoffice writer window open (which collapse onto one icon in the icon task list) that are all unminimised and one window is closed, the icon in the icon task list disappears but the other window(s) remain.

**Steps to reproduce the issue**

cd /dir
ls
one.odt ... n.odt
libreoffice --writer ./* &
[close one window via GUI]

**Comment by yursan9** [comment]
The other Writer windows isn't registered to IconTasklist. The IconTasklist only register the first instance of Writer.
