### ISSUE TITLE
Do-not-disturb symbol is blurry

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1683]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

do-not disturb icon on the panel is noticebly blurry. I think it's that icon's edges that are blurry.

**Steps to reproduce the issue**

go to raven notifications & click on the bell icon

**Comment by JoshStrobl** [comment]
Won't fix, I'm having to force downscale it for it to be a smaller size than it actually is. Talk to the papirus folks about fixing their icon. See #1470
