### ISSUE TITLE
Do-not disturb icon is bigger

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1684]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

do-not disturb icon which is on raven notification is noticeably few pixels larger.

**Steps to reproduce the issue**

go to raven notification and click on the bell icon & see it's getting bigger.

**Comment by JoshStrobl** [comment]
Duplicate of #1470
