### ISSUE TITLE
Microphone input widget shows an arrow for further settings at right corner

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1685]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

Microphone input widget shows an arrow for further settings at right corner.
On-click it just expands the card(widget) with empty space (no settings at all)
**note** :- no microphone is connected to my PC (no idea wt happens if connected)

**Steps to reproduce the issue**

disconnect if a microphone available device or a microphone connected. 
make sure show microphone input widget is enabled in budgie settings under raven.
open raven and notice microphone input widget.

**Comment by JoshStrobl** [comment]
It's not further settings, it's where it'd list your devices. I can see about it having it hide the widget altogether if there are no devices detected.
