### ISSUE TITLE
Unable to Pin terminal to Panel

### ISSUE THREAD

**Issue by rbharathkumar** [solus-project/budgie-desktop#1689]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie-Desktop 10.5

Unable to pin Terminal to Panel both from the Application Menu and after the terminal is open as well.
 ...

**Steps to reproduce the issue**
1. Press super Key to open the Application Menu.
2. Type Terminal or Navigate to System Tools -> Terminal
3. Right Click option does not have the Pin to Panel Option.
4. Alternatively, open the terminal and then right click on the terminal icon in Panel. The Pin option is still not available.

 ...

**Comment by rbharathkumar** [comment]
From the Panel -> Clicking on the Favorite Button seems to pin the Terminal to the Panel.
The issue can be closed or kept open for the "Right Click to Pin" implementation.

I agree it is not possible to implement the Right Click option to all the applications from the Application Menu, but atleast for System Tools alone, it can be done if time permits.

Definitely not an issue. Maybe a feature request.

Thanks for all the hard work. Great Job guys.

**Comment by EbonJaeger** [comment]
Favoriting and pinning are two different words for the same action. The 'favorite' icon is what you want.

**Comment by rbharathkumar** [comment]
Yes, figured that one out....But like it is available in the Solus-KDE build, having the option to Favorite or Pin before opening the App would be a nice feature to have.

But as mentioned it is merely a "Good to Have feature" and not an issue.

Do advise if we can have this open or do you want me to close it ?

**Comment by JoshStrobl** [comment]
This is not an issue, it's a feature request which was already requested.

**Comment by EbonJaeger** [comment]
Ah. Being able to pin apps from the menu is a fair point. I guess just wait and see what Josh says about it.
