### ISSUE TITLE
About Budgie in Ubuntu 14.04

### ISSUE THREAD

**Issue by sidjad** [solus-project/budgie-desktop#169]
I will go to install Budgie-desktop in my ubuntu 14.04 64 bit , I am bit confuse about change Desktop Environment. is any issue to installing Budgie
Thanks..

**Comment by Justinzobel** [comment]
https://evolve-os.com/forums/viewtopic.php?f=6&t=7&p=35 this shows you how to install from source on Ubuntu

**Comment by ikeydoherty** [comment]
Closing - inactive.
