### ISSUE TITLE
Software Center - Unable to Sort Installed Packages based on Size

### ISSUE THREAD

**Issue by rbharathkumar** [solus-project/budgie-desktop#1690]
Operating System**: Solus 3.9999
Budgie version**: budgie-desktop 10.5
**The issue encountered**
Software Center - Unable to Sort Installed Packages based on Size

Steps to reproduce the issue
1. From the application menu, select the Software Center.
2. Select Installed on the Left Pane.
3. No option to sort packages based on size. Useful when running out of space and in need to remove any unnecessary packages.

 ...

**Comment by JoshStrobl** [comment]
This is nothing to do with Budgie.
