### ISSUE TITLE
Panel breaks when dragging Trash to its task icons applet for pinning

### ISSUE THREAD

**Issue by H-yphen** [solus-project/budgie-desktop#1691]
Solus 3.9999 with GNOME 3.28.2
budgie-desktop v10.4-85-g36667bcb

**The issue encountered**

Attempting to add the trash icon from the default Nautilus-backed desktop (3.26.4) to the Task List (the icons variant) applet in the budgie panel by drag and drop produces:

- a panel crash
- no trash icon added

This happens every single time.

**Comment by JoshStrobl** [comment]
The IconTasklist is for applications, not random files or locations (which the trash location is). Regardless, I'll see about fixing this by ignore non-desktop-file locations.

**Comment by H-yphen** [comment]
Please allow me to add a question;
With it disabled after 67edfa2, how would I go about pinning the trash applet to my statusbar/dock for quick drag and drop deletions? Was there a correct way to do it that I'm not aware of? #

**Comment by JoshStrobl** [comment]
You can't. The point of the IconTasklist is to have running applications, not misc. files. There isnt a "trash applet", at least not in Budgie itself (not accounting for any third party applets?
