### ISSUE TITLE
Scale up core applets in Dock mode

### ISSUE THREAD

**Issue by streambinder** [solus-project/budgie-desktop#1693]
It's not actually an issue, but an optimization proposal.
It would be nice to consider the case the main Budgie panel to be in Dock mode.
Consider the out-of-the-box panel configured at the first installation of Budgie: it hosts `Menu` option, few pinned apps on the left and many system and core applets/options on the right. If you configure your desktop to have only one panel, in Dock mode, you'll result in a messy panel: the icons that were originally on the left scale correctly, while the ones originally on the right don't, because they're not meant to be hosted on a bigger - such as the Dock mode panels - panel. It would be nice if you provide the ability to configure Budgie that way, with a single Dock mode panel hosting core applets that are able to scale correctly as well as all the other applications icons.
As I get back at home and have few minutes, will post some screens that underline what I mean, both the issue itself and what you (and me at first) could be interested in.

**Comment by JoshStrobl** [comment]
I would recommend you use the following configuration:

- Top panel
 - Budgie Menu applet on left
 - Clock and Raven Trigger on right
- Bottom panel
 - Only IconTasklist applet.
