### ISSUE TITLE
Indicator icons displayed incorrectly

### ISSUE THREAD

**Issue by Gaming4LifeDE** [solus-project/budgie-desktop#1694]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

Indicator icons for some applications are displayed incorrectly. One example would be skype but I've had this issue with ckb-next and others too. Here's a screenshot:

![whatsapp image 2019-01-02 at 12 42 46](https://user-images.githubusercontent.com/33233376/50590609-01356e80-0e8c-11e9-8084-917dbbff3126.jpeg)

**Steps to reproduce the issue**

- Install skype
- Open it

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue, it's an issue with Skype itself (and its use of Electron). See https://github.com/solus-project/3rd-party/issues/352
