### ISSUE TITLE
Suggestions to improve the Budgie's interface functionality

### ISSUE THREAD

**Issue by matbezlima** [solus-project/budgie-desktop#1696]
I tried Solus 3.9999 Budgie.

About the SO as whole (skip this paragraph if you want to see my suggestions about the Budgie interface), I found amazing how many great functions and programs it brings as a standard, as VPN creator and hotspot wifi, in Windows you need to download a program to make these same things. There were many other small details and functions that I also found amazing in the settings and programs installed, I was pleasantly surprised to discover that you can open cbr files, and they also have icons showing the first page of the comic in the file manager, and read comics normally without installing any program, I have thousands of digital comics in cbr format in my PC, so this was really great! 

The Budgie interface is clean and beautiful, polished, simple enough without seeming dated, like Mate or Cinammon, I would be ready to use it, but the Budgie's native file explorer had some limitations. Such limitations are only small details, but small details often make the most difference. My complaints are:

- You only can hide files manually, by renaming the files with a dot in the start. You can't even rename multiple files at once! I also wish that I could hide automatically the folders and files  and apply to all sub-folders and files inside them by simply opening the properties, like I can do in Windows.

- For some reason, changing the size of the files' icons in the file manager also changes the size of the desktop icons. Why do that, honestly, this is really inconvenient!

- If you have more than one window of the same program open, they are only one icon in the taskbar. This is great, but you only can show any of the already open windows of the app by using the right click in the mouse, if you use the left, nothing happens! I wondered if the system was broken. Having to use right click is specially anoying with a touchpad in a notebook. Why not being able to use both right and left?

- You also don't have an easy acess button to show your desktop without any window in front of it, like you can in both Windows and KDE's taskbar also, if I am not mistaken.

Please, implement these changes in a future update.

**Comment by yursan9** [comment]
Hello, I'll answer some of your suggestion.

1. You can rename multiple files in Nautilus (Files). Select multiple files -> right click on mouse -> select Rename... Hiding files with dot is one of Linux's file system characteristic.

2. This is because desktop icon is provided by Nautilus, the files manager.

3. I think this is the intended behaviour. You can 2 finger click to simulate right-click on most touchpad. Or you can disable window grouping in `Budgie Desktop Settings`.

4. To show your desktop, or minimizing all opened windows, Budgie have an applet named `Show Desktop` that can be added to panel.

**Comment by JoshStrobl** [comment]
Pretty much what @yursan9 said. I don't see any actionable items here.
