### ISSUE TITLE
Can't close Budgie Desktop Settings from IconTaskList popover

### ISSUE THREAD

**Issue by yursan9** [solus-project/budgie-desktop#1697]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: i.e. Budgie 10.5 (git-8a710056664f860224d4260b566d248948866a90)

**The issue encountered**

I tried closing Budgie Desktop Settings using IconTaskList Popover, but the windows won't close.

**Steps to reproduce the issue**

1. Open Budgie Desktop Settings
2. Right click the icon in panel
3. Click the `X` icon, or the close all windows icon

**Comment by JockeTF** [comment]
Can confirm this issue for a "new Mutter" branch (based on 7b1c1141).

**Comment by JoshStrobl** [comment]
This is the result of Budgie Desktop Settings being largely incorporated into the panel. Best way to resolve this besides completely separating Budgie Desktop Settings in all likelihood is to have a dbus signal to close the app and have case handlers for it in IconButton+IconPopover.

**Comment by JoshStrobl** [comment]
@fossfreedom Note that regarding your issue on it leaving a blank icon, I'm working on improving Budgie Desktop Settings / budgie-panel tracking and detection at the moment so it's properly calculating the amount of items to add. I already have a partial fix working but still doing more testing and adding more checks / validation in various places. This fix may also (hopefully) resolve this related issue as well.
