### ISSUE TITLE
Per app notifications muting from raven

### ISSUE THREAD

**Issue by lallenfrancisl** [solus-project/budgie-desktop#1699]
It would be nice if you can mute notifications per app from raven like in android. This is already in the gnome settings, so wouldn't it be possible.

**Comment by JockeTF** [comment]
Agreed. I've been missing this feature as well.

**Comment by JoshStrobl** [comment]
It does, in fact, work. It's been implemented since 21421252046e4561a8a7ef36b434b177b2b1f1e6. I've tested it against multiple applications such as Hexchat. If the application doesn't send a `desktop-entry` hint however, it will not work, and it's not our responsibility to implement such hints.
