### ISSUE TITLE
vivaldi icon gets not displayed in the notification

### ISSUE THREAD

**Issue by Alexander88207** [solus-project/budgie-desktop#1700]
OS: Solus 3.9999 shannon
Budgie version: 10.5 (git-d14d88890e680be0759178ca11adebb7726ef4df)

**Steps to reproduce the issue**

![repro](https://user-images.githubusercontent.com/37543796/50736533-0c0b3e80-11bf-11e9-8c9c-481e05694e56.gif)

**Comment by JoshStrobl** [comment]
This is an issue with Vivaldi. It reports its name as Vivaldi, which is fine, however it doesn't report with a standard icon at all. It reports as `file:///tmp/.com.vivaldi.Vivaldi.KpPn10` in my testing, though that's not likely to be consistent. I'm really hesistant to start adding a bunch of hacks, derper checks, etc. for these so I'd recommend you file an issue with the Vivaldi devs instead.
