### ISSUE TITLE
Incorrect number of instances of same program in the task list

### ISSUE THREAD

**Issue by yaymalaga** [solus-project/budgie-desktop#1703]
Operating System: Solus 3.9999 up-to-day (07/01/2019)
Budgie version: budgie-desktop 10.5 (git-d14d88890e680be0759178ca11adebb7726ef4df)

If you open three documents in LibreOffice Writer and you put the mouse over the task list icon and use the wheel to change between the instances, it will only allow you to change between two. If you repeat this with just two open files, it just shows one instance.

The thing here is that if you press the icon with the mouse right button, it is showing correctly all the instances, and you can switch them without any issue.

**Comment by JoshStrobl** [comment]
Each LibreOffice window actually has its own Wnck.ClassGroup, as I noted in 32bc83acc455a726ab36fe3fe5c35b70a9a0323d, which is why the functionality does not work for LO. I'll see about having it pull the Wnck.Window list from our popover, which is far smarter than Wnck by itself.
