### ISSUE TITLE
Starting windows on Center does not always work.

### ISSUE THREAD

**Issue by JonnyCodewalker** [solus-project/budgie-desktop#1704]
**Operating System**: 3.9999
**Budgie version**: budgie-desktop 10.5 (git-1f8eceaa58e7c9c2978484215775fbd03466959d)

**The issue encountered**
After enabeling centering for new Windows not every window centers. Noticeable programs from outside the repo do not seem to work (bitwarden appimage eg). But also some apps from the Repo (signal-desktop).

Apps that do not work:
- Signal Desktop
- Libre Office
- Nautilus
- Calculator (whatever the default one on solus budgie is)

**Steps to reproduce the issue**
- Enable Opening new Windows in Center
- Install Signal-Desktop
- Start Signal, the window appears off-center.

**Comment by JoshStrobl** [comment]
Unfortunately there isn't much we can do this in this regard, this is simply a deficiency in Mutter, which is what Budgie WM leverages. Closing and hopefully we can make sure it is more consistent when we dropkick Mutter in Budgie 11.
