### ISSUE TITLE
Tabswitcher only supports alt or super as modifiers

### ISSUE THREAD

**Issue by friday** [solus-project/budgie-desktop#1705]
**Operating System**: Antergos/Arch (not relevant for this issue)
**Budgie version**: 10.4

**The issue encountered**

The current tabswitcher is hardcoded for super or alt as the modifier. These are the common modifiers for it, but since you can override it with pretty much anything using gnome-control-center or dconf this is not a safe assumption.

See #1668

**Comment by friday** [comment]
I haven't tried but this should be fixed by #1972

**Comment by rbreaves** [comment]
#1972 was withdrawn due to bugs w/ my implementation still but #2026 was merged recently which only adds Ctrl.
