### ISSUE TITLE
Caffeine mode wont turn off after switch off computer

### ISSUE THREAD

**Issue by Skyeun** [solus-project/budgie-desktop#1706]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

 When you switch off your computer with Caffeine mode active, your power settings (dim screen and automatic suspend) will always be disabled.

**Steps to reproduce the issue**

- Turn on Caffeine mode
- Switch off your computer
- Switch it on again
- Settings will still be on caffeine mode

**Comment by JoshStrobl** [comment]
Going to consider this a bug since there's almost certainly a better way of doing the setting retaining and restoration (which I plan on doing).

**Comment by Skyeun** [comment]
It appen when I'm using the normal way to switch off my computer. A clean
way could be to read the state of the parameters and then display the
Caffeine mode as on or off. Not sure how easy it is.

Le jeu. 10 janv. 2019 à 00:28, Joshua Strobl <notifications@github.com> a
écrit :

**Comment by JoshStrobl** [comment]
> A clean way could be to read the state of the parameters and then display the Caffeine mode as on or off. Not sure how easy it is.

That's already what we do, that wouldn't change a thing. The applet just manipulates a schema boolean key/val, the daemon handles all the logic.
