### ISSUE TITLE
Battery status on Arch Linux does not update

### ISSUE THREAD

**Issue by embik** [solus-project/budgie-desktop#171]
Hey there, so this is my first issue on GitHub and I hope it's okay I'm talking about Budgie on Arch Linux (not sure if you want to support that, so it might be not really important to you).

I love Budgie on Arch (as I prefer minimal desktops not getting into my way like GNOME3 and Plasma do) and I've installed it from the git repository to stay up-to-date (I'm well aware this is some kind of risky in case of crashes, but well ... cutting edge and stuff). Overall I have to say it's amazing and works very nice, but it looks like the battery status indicator does not update on Arch Linux. It's basically in the state the battery had on start/login, both in terms of icon and percentage displayed.

Is there anything I can do to debug the issue? I've taken a look into the [code](https://github.com/evolve-os/budgie-desktop/blob/master/panel/applets/status/PowerIndicator.vala) and as far as I can say, there is a condition called `#if ! HAVE_UPOWER0999` - I tried to comment this out, but after compiling budgie with these changes the status applet is not there anymore (and you cannot add it via budgie settings as well).

Regarding the version of upower (I guess that's important):
```
[embik@arch ~]$ pacman -Q  upower
upower 0.99.2-2
```

**Comment by clevrpwn** [comment]
+1 The same problem is occuring on an Ubuntu vivid vervet base and a Debian Jessie base, it seems to have only started occuring very recently.

**Comment by libregeek** [comment]
+1 I have this problem in Fedora 21. The batter applet always shows the battery status at startup and it doesn't get updated afterwards.

**Comment by ikeydoherty** [comment]
Should be fixed in git a while now - please confirm.

**Comment by hemjaj** [comment]
Confirmed, this has been fixed for me (Arch Linux, using budgie-desktop-git v8.1.r98.ga843ca5-1).

**Comment by ikeydoherty** [comment]
Cheers - now I need to make the gvc stuff update the current audio mixer when it changes.. one of the other big papercut issues ^^
