### ISSUE TITLE
Caffeine mode turn off automatic suspend and not turn on

### ISSUE THREAD

**Issue by lallenfrancisl** [solus-project/budgie-desktop#1712]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: budgie-desktop 10.5 (git-aa0d4797ed3d630710afa0c4d7e3d672f317222a)

**The issue encountered**

It turns off automatic suspend

**Steps to reproduce the issue**
Turn on automatic suspend and then turn on caffeine mode

**Comment by JoshStrobl** [comment]
That's the whole point of Caffeine Mode, disable lock and suspend actions...

**Comment by lallenfrancisl** [comment]
No sorry for the confusion, it doesn't turn it back on when caffeine mode is turned off
