### ISSUE TITLE
Caffeine mode turn off automatic suspend and not turn it back on after caffeine mode is turned off

### ISSUE THREAD

**Issue by lallenfrancisl** [solus-project/budgie-desktop#1715]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: budgie-desktop 10.5 (git-aa0d4797ed3d630710afa0c4d7e3d672f317222a)

**The issue encountered**
It turns off automatic suspend and does not turn automatic suspend back on after caffeine mode is turned off. 
This had been reported earlier but it caused confusion and was closed so I thought a new one would be better.

**Steps to reproduce the issue** 
Turn on automatic suspend and then turn on caffeine mode and turn off caffeine mode. Automatic suspend does not revert to the original value.

**Comment by JoshStrobl** [comment]
Please run the following command in a Terminal **both before and after** turning Caffeine Mode on and then off and paste the results from both runs, thanks!

```
gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-type' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-type'
```

**Comment by lallenfrancisl** [comment]
Ok now the original issue is fixed. I think it had something to do with configurations, because it got fixed when reinstalled solus. But now the issue is that suspend setting resets to **on** even if it was set as **only on battery power originally**

**before:**
![screenshot from 2019-01-17 17 28 06](https://user-images.githubusercontent.com/21018348/51317477-aef47000-1a7d-11e9-8720-aaef02aa128c.png)

**when on:** 
![screenshot from 2019-01-17 17 25 01](https://user-images.githubusercontent.com/21018348/51317514-c7648a80-1a7d-11e9-9957-15cc308dac31.png)

**after:**
![screenshot from 2019-01-17 17 24 05](https://user-images.githubusercontent.com/21018348/51317535-d77c6a00-1a7d-11e9-9c6d-3b62966b99d4.png)


**Commandline (before, then when it is on, after):**
![screenshot from 2019-01-17 17 35 02](https://user-images.githubusercontent.com/21018348/51317692-422da580-1a7e-11e9-8917-72ad576a99cf.png)

**Comment by JoshStrobl** [comment]
1. Did you make any modifications to Power settings after installation? There is no indication to me based on looking at the code that it would've explicitly set it to suspend otherwise. We get the string solely at the start of the daemon and it is not modified by **us** unless you are turning Caffeine Mode on or off.
2. Refrain from posting screenshots, it is unnecessary information.
3. Post the **text** as actual text, not a screenshot of the settings I requested.

The re-installation certainly isn't helpful to debugging this issue

**Comment by JoshStrobl** [comment]
> I have only used the gnome-control-center and not anything like dconf after installation.

Except GNOME Control Center changes those key values in gsettings / dconf, so yes effectively you did use dconf.

Your text is just the commands I requested repeatedly, not the results.

**Comment by lallenfrancisl** [comment]
I have deleted the commands from the comment and only kept the results

**Comment by yursan9** [comment]
I can reproduce the issue.
```
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-type' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-type'
uint32 0
true
'nothing'
'suspend'
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-type' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-type'
uint32 0
false
'nothing'
'nothing'
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-type' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-type'
uint32 0
false
'nothing'
'nothing'
```

**Comment by JoshStrobl** [comment]
@yursan9 Is this just by pressing the Caffeine Applet or are you trying to log out or end the session while Caffeine Mode is on? Still trying to reproduce the issue on my laptop, but it's acting in a consistent manner. I'm tempted to test just setting the battery and ac timeouts to 0 instead of modifying the sleep-inactive-{ac,battery}-type, since it's reported that it'll never be considered inactive when that is the applied value.

**Comment by yursan9** [comment]
@JoshStrobl I only tested the Caffeine Mode activation from the applet.

**Comment by JoshStrobl** [comment]
@yursan9 Please try against cb8088300f0abab9cec9e2f78afcc7272099e3df and instead of the above mentioned gsettings CLI calls, please do:

``` bash
gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
```

**Comment by yursan9** [comment]
@JoshStrobl, I tried building from cb80883 and the result is below.
The first one is when I restarted my computer after installing Budgie. It sets my `idle-delay` and `idle-dim` to diffrent value. The second one is when I toggle on the Caffeine mode, and the last one is when I toggle off the Caffeine Mode.

```
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 0
false
3600
900
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 0
false
0
0
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 0
false
3600
900
```

**Comment by JoshStrobl** [comment]
@yursan9 Okay, it appears that like with the timeout, I'll need to have us update the `default_idle_delay` and `default_idle_dim`values if it is modified when Caffeine Mode is off, otherwise it will just stay at the default when it's initially checked, which is `0` and `false` respectively. It does look like it is properly restoring the timeout values however, which is good.

**Comment by JoshStrobl** [comment]
@yursan9 Please try against fdb23316fbd49046a37e998ed0dcd3bed80d87b1

**Comment by yursan9** [comment]
@JoshStrobl The last commit squash the bug.

```
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 60
true
3600
900
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 0
false
0
0
~ gsettings get org.gnome.desktop.session 'idle-delay' && gsettings get org.gnome.settings-daemon.plugins.power 'idle-dim' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-ac-timeout' && gsettings get org.gnome.settings-daemon.plugins.power 'sleep-inactive-battery-timeout'
uint32 60
true
3600
900
```

**Comment by JoshStrobl** [comment]
Yay. Thanks for testing, I'll get this into the Solus repo today before sync.
