### ISSUE TITLE
Shutdown doesn't work

### ISSUE THREAD

**Issue by sntdevco** [solus-project/budgie-desktop#1717]
I am running the latest version of Ubuntu Budgie 18.04.1 LTS, downloaded from the official website. I have a 64-bit PC (laptop). The installation succeeds and I can log in (past lightdm), however when I try to shut down, all the applets close and the screen remains stuck endlessly, just showing the wallpaper. I have tried adding acpi=force to grub.cfg but it doesn’t help and the only way to turn it off, is by pressing and holding the power button. I have done fresh installs twice and still, the issue persists. I think this is a bug.

**EDIT 1**: `shutdown` from the terminal also does not work. And only `reboot -p` works and shuts down the computer completely.

Kind regards,
Sayan

**Comment by fossfreedom** [comment]
I would kindly suggest that this is not a budgie-desktop matter (this is
the upstream issue tracker for the desktop interface) and you should use
the support choices for your distro i.e. askubuntu.com/ ubuntuforums.org or
discourse.ubuntubudgie.org
