### ISSUE TITLE
MPRIS album art is blurry

### ISSUE THREAD

**Issue by vredesbyyrd** [solus-project/budgie-desktop#1719]
**Operating System**:  Arch Linux / Kernel  4.20.2-1
**Budgie version**: Budgie 10.4 (commit 6da0da3bcb794936c575b44dc27ea696d345558f) & patched for mutter 3.30.  
**Music Player**: Lollypop 0.9.911

**The issue encountered**:
MPRIS album cover art is blurry. Perhaps unreasonable so? Are album covers compressed to reduce overhead when passed over dbus, or something along those lines? I poked around `MprisWidget.vala` and `MprisGui.vala`  but did not see anything that made me think so, although that does not prove much as I am not really familiar with vala. 

The album cover in the screenshot is a 1400x1400px jpg.  I do not use any embedded art so did not test that yet. Lastly, I tried a handful of different themes which did not have an effect so I think funky css can be ruled out.  

Thanks to the budgie / solus team for your continued work.

![screenshot from 2019-01-16 11-24-31](https://user-images.githubusercontent.com/22080838/51278821-34eeb900-19a1-11e9-994c-ff47b275ee50.png)
 
 ...

**Comment by JoshStrobl** [comment]
This is in fact not an issue with Budgie, but rather with the image which lollypop provides.

From my testing, Lollypop produces a scaled down image at 200x200px, which we then set as the background for the MPRIS player. However, as a result of the MPRIS player background size being 250x250px, it gets scaled up and thus ends up being blurry.

I decided to take a look at the lollypop code and you can see the offending function [here](https://gitlab.gnome.org/World/lollypop/blob/master/lollypop/art_album.py#L144) which writes the image to the cache. I would suggest filing a bug with the Lollypop dev on their tracker.

Sorry but there is no actionable items on my part. Scaling the image up even with the best interpolation mode is still going to look bad.

**Comment by vredesbyyrd** [comment]
Fixed in lollypop  [commit](https://gitlab.gnome.org/World/lollypop/commit/918b6cfa6bc5eece12754d7ae5c2d2f2033cf4af)
