### ISSUE TITLE
Pen is not rotated along with screen

### ISSUE THREAD

**Issue by sm8ps** [solus-project/budgie-desktop#1720]
**Operating System**: Ubuntu Budgie 18.10
**Budgie version**: Budgie 10.4

**The issue encountered**
Screen rotation works perfectly but the integrate digitizer does not rotate along, meaning that the axes and/or their orientation are mixed up. This happens on an Acer Spin 111 with a pen recognized by xinput as 04F3224A:00 04F3:255A Pen that presumably is manufactured by Elan. Unfortunately I have not found ways to determine any more information; neither lsusb nor lshw make it show up.

**Steps to reproduce the issue**
Rotate device (with iio-sensor-proxy running) and move pen on screen.
There seem to be some remedies available like the one given by 
https://wiki.debian.org/InstallingDebianOn/Acer/Spin1
However, I think this should be taken care of the desktop environment directly. I hope this is the right place to bring this forth. Otherwise please direct me to the appropriate place, thank you!
And thank you for this beautiful desktop environment in general!

**Comment by fossfreedom** [comment]
I would kindly suggest that this is not a budgie-desktop matter (this is
the upstream issue tracker for the desktop interface) and you should use
the support choices for your distro i.e. askubuntu.com/ ubuntuforums.org or
discourse.ubuntubudgie.org
