### ISSUE TITLE
Wrong comment in Budgie Desktop Setting "Style"

### ISSUE THREAD

**Issue by Geert1959** [solus-project/budgie-desktop#1721]
**Operating System**: Solus 3.999
**Budgie version**: budgie-desktop 10.5 (git-04412c7ca21ad919b6b52f3146e883da42625fc3)

**The issue encountered**
See printscreen of comment in Weblate
![schermafdruk van 2019-01-18 09 23 51](https://user-images.githubusercontent.com/12219674/51388409-9d68a200-1b29-11e9-81ac-a3b1e5e941b8.png)

 ...

**Steps to reproduce the issue**

 ...

**Comment by JoshStrobl** [comment]
Yep, the description for the settings row is not correct. I'll get it fixed up. Thanks for bringing it to my attention! 👍
