### ISSUE TITLE
Ubuntu Budgie can't pin snap applications to panel

### ISSUE THREAD

**Issue by Andrewyg** [solus-project/budgie-desktop#1724]
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

 I found out that looks like if the applications install from software are provided by snap, it can't be pinned to the panel since its desktop launcher file is located in snap's directory.

**Steps to reproduce the issue**

 Install firefox by searching in software on Ubuntu Budgie 18.04, remove the docker and add icon task list to budgie's panel, right-click on Firefox and you'll notice there isn't a pin to panel option.

**Comment by JoshStrobl** [comment]
I would suggest installing Solus or the latest Ubuntu Budgie (18.10) and testing against that. While I don't know if Ubuntu Budgie has the latest git of Budgie, I know Solus does. I'm not really willing to fix issues with a version of Budgie that's over a year old and no longer supported, especially so close to a newer Budgie release.

**Comment by fossfreedom** [comment]
No need install another distro.

Both 18.04 and 18.10 will have budgie desktop v10.5 backported once it has
been tagged as released.

Git versions of budgie desktop are available for testing as well.
discourse.ubuntubudgie.org if you want more details.
