### ISSUE TITLE
Caffeine icon is not properly aligned

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1725]
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

 caffeine icon stays a little below than other icons
![screenshot from 2019-01-20 15 54 47](https://user-images.githubusercontent.com/38057676/51437967-c032bc00-1ccb-11e9-9fb2-b60a48ec65c1.png)

**Steps to reproduce the issue**

add caffeine applet to the panel and take a good look, so u would notice that it's not properly aligned

**Comment by JoshStrobl** [comment]
Duplicate of #1586
