### ISSUE TITLE
Ability to unbind/rebind notification center keyboard shortcuts

### ISSUE THREAD

**Issue by Tristan971** [solus-project/budgie-desktop#1730]
### Current Budgie version
budgie-desktop 10.5 (git-6d814d566f3744d13eed1a285c8c210fde1fda77)

### Use-cases
- Given that I use some developer tools that have shortcuts bound to Meta/Super + N
- Or have a keyboard layout that has the `~` character as Alt + N
- Or otherwise in general apps using a modifier + N for some functionnality

I'd like to have it be sent to the app rather than open the notification center.

### Proposal
Sounds reasonable (to me at least that is) to be able to at least unbind the notification center shortcuts, and even better to be able to rebind it.

### References
Not that I know of but it sounds like something that'd have been mentioned already, so apologies if that is the case...

Bets regards

**Comment by JoshStrobl** [comment]
You can already manually change the keyboard shortcut by changing the binding values found as `toggle-notifications` and `toggle-raven` in `com.solus-project.budgie-wm`, via something like dconf-editor.
