### ISSUE TITLE
Sometimes budgie panel tooltips are offset to the right

### ISSUE THREAD

**Issue by bwat47** [solus-project/budgie-desktop#1733]
## Description
Sometimes when mousing over icons in the budgie taskbar, the tooltips aren't displayed in the correct position (they are offset to the right, see the attached screenshot)

## Budgie version
10.5-189

## Operating system
Solus 3.9999

## Steps to reproduce the issue
This seems to happen randomly, sometimes they are placed correctly, sometimes they are not. I can re-create it reliably by just mousing over icons on the budgie taskbar for a minute or so

## Actual result
![tooltip](https://user-images.githubusercontent.com/1442520/51677644-4b4fd280-1fa8-11e9-84f3-ce2871bb1d1f.png)

## Expected result
Tooltips should always be centered above the taskbar icon

**Comment by JoshStrobl** [comment]
This a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/2784
