### ISSUE TITLE
Sometime's can't un-minimize nautilus

### ISSUE THREAD

**Issue by bwat47** [solus-project/budgie-desktop#1734]
## Description

If I minimize nautilus, I cannot un-minimize it by clicking the nautilus icon in the budgie taskbar

## Budgie version
budgie-desktop, version: 10.5, release: 191

## Operating system
Solus 3.9999

## Steps to reproduce the issue
Pin nautilus to taskbar. Open nautilus. Minimize nautilus, then try un-minimizing it by clicking the icon on the taskbar.

Doesn't seem 100% re-producible, but if I try this a few times the issue usually occurs

## Actual result
Clicking the taskbar button doesn't un-minimize the nautilus window

## Expected result
Clicking the tasbkar icon should un-minimize the nautilus window

## Additional information
When this happens, if I use alt-tab to switch to the nautilus window it un-minimizes as expected

NOTE: I don't recall ever seeing this issue until the last budgie-desktop update (191)

NOTE: I found that if I disable desktop icons in budgie settings, this does not seem to happen

**Comment by bwat47** [comment]
Also, when this happens, if instead of clicking the nautilus icon in the taskbar, I right click on it and then click the specific nautilus window from the popover, it does un-minimize as expected.

Note that in my scenario, I do only have one nautilus window open

**Comment by bwat47** [comment]
I found that if I disable desktop icons in budgie settings, this does not seem to happen

**Comment by sixtyfive** [comment]
People are starting to ask me if I can't install them something other than Solus because of *this* thing. Is there a holdup because of difficulties with figuring this bug out or is it a manpower problem?

**Comment by JoshStrobl** [comment]
Neither, the solution is to implement our own desktop icons implementation, which is something I'm doing for 10.5.2.

**Comment by JoshStrobl** [comment]
Closing this as the new [Budgie Desktop View](https://github.com/getsolus/budgie-desktop-view) has been released (with a 1.0 next week, 0.99.3 tagged at the moment), which eliminates the use of the legacy Nautilus implementation.

Building on that, there is now a vendor-specific configuration (also accessible to end users if you dig in the dconf / gsettings options enough) for alternatives such as DesktopFolder and Nemo, subject to what is available in your operating system's repositories, should you not desire to use the official desktop icons / view implementation.

**Comment by sixtyfive** [comment]
Thank you for not forgetting about this, Josh!
