### ISSUE TITLE
Feature Request: Option to automatically hide notifications when in a fullscreen application/game

### ISSUE THREAD

**Issue by smt923** [solus-project/budgie-desktop#1735]
### Current Budgie version

10.5

### Use-cases

Notifications popping up on top of fullscreen games can sometimes mess up the compositor unredirection temporarily, or otherwise just be somewhat distracting, and it can often by annoying or easy to forget to manually turn them off and then back on again every time you do something fullscreen

### Proposal

Some sort of Budgie specific setting that allowed the automatic hiding of notifications, I know there's a way to manually hide notifications but it would be a nice quality of life option to automatically hide them whenever Budgie detected a fullscreen application or game

### References

n/a

**Comment by serebit** [comment]
Agreed. I'll give this a shot.

**Comment by serebit** [comment]
This'll require some fixes to nightlight auto-toggling (the two are related). The nightlight fixes will make it into v10.5.2, but the rest will have to wait for v10.5.3, as I don't want to step on Josh's toes.
