### ISSUE TITLE
Hidden dock not unhiding with icon task list

### ISSUE THREAD

**Issue by matt-froggatt** [solus-project/budgie-desktop#1737]
Since update 10.5-190 of Budgie, docks that have been hidden that contain the icon task list applet do not properly un-hide when hidden.

**Comment by JoshStrobl** [comment]
I believe this is an issue relating to fe2c855dff7a29159f09840b0e2f287e5af9615f by @LulzFTW. @LulzFTW mind taking a look?

**Comment by matt-froggatt** [comment]
It could be. I honestly don't understand how the docks work well enough to say for sure, but I have found that these docks do not un-hide no matter what components are on the dock, as long as it contains at least one icon task list.

**Comment by LulzFTW** [comment]
Are you using a HiDPI monitor?

I am unable to reproduce any issues with panel hiding on my non-HiDPI desktop, but it seems to be broken on my HiDPI laptop.

On my laptop, panels in the Right or Bottom position will not unhide on mouseover. However, adding or removing the IconTaskList or any other components has no effect on this behavior in my case, so I'm not sure if I'm experiencing the same issue.

**Comment by AppMathIsRealMath** [comment]
I've got the same problem which started after 10.5-189.
Bottom dock in autohide won't reveal when covered by a maximized window. I use a Dell 17-5770 1920x1080 laptop.

**Comment by LulzFTW** [comment]
@matt-froggatt @AppMathIsRealMath What GTK theme are you using?

**Comment by matt-froggatt** [comment]
Currently using Adapta-Nokto, I was using Ant-Dracula before though and I had the same problem.

**Comment by AppMathIsRealMath** [comment]
Adwaita-Dark.

**Comment by AppMathIsRealMath** [comment]
I do have Built-In Theme enabled. As a test I reinstalled -192 and disabled the BiT. It looked terrible with Adwaita-Dark but the dock autohide reveal did work. So it does seem that's the problem. I see from a recent commit that the BiT is unmaintained which is a shame because I rather like it.

But I'm sure I can find an alternative if the BiT is deprecated!

**Comment by LulzFTW** [comment]
I've removed the code that overrides the size allocation and it seems to resolve this issue for me (tested on Adapta, Ant, and the Built-in theme).

**Comment by DSpaceman** [comment]
I am running Solus with the version of Budgie that includes fix #1742 and I am still having the issue where fullscreen windows prevent the bottom dock from unhiding, changing the theme and going inbetween BIT doesn't seem to help. I have a 14" 3200x1800 HiDPI screen.

**Comment by LulzFTW** [comment]
I have also confirmed that unhiding is broken on HiDPI screens in my previous post: https://github.com/solus-project/budgie-desktop/issues/1737#issuecomment-459892202.

However, I believe that it is a separate issue, unrelated to IconTaskList, as adding/removing IconTaskList had no effect on this behavior.

@DSpaceman Did this break on a recent update?

**Comment by DSpaceman** [comment]
@LulzFTW I couldn't tell you. I usually use the default Solus taskbar and a side-dock for my workspaces which has mostly worked so far. It does seem though like the cursor is not reaching the very bottom of the screen to trigger the un-hiding.

**Comment by opennomad** [comment]
For me the behavior is different. when I change the settings to hide automatic or intelligent, it unhides once and then hides properly, but it only works once. IconTasklist does not make a difference for me.

Ubuntu 20.04 and budgie-desktop 10.5.1-6
