### ISSUE TITLE
Double 100% displayed when using the system theme

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1740]
## Description
For volume above 100% option is chosen in budgie-desktop-settings - raven + built in theme you see 100% twice.

## Budgie version
budgie-desktop 10.5 (git-2edafbd2e3e48e1f4e079efe44cafe35089d8aac)

## Operating system
UB 18.04.1

## Steps to reproduce the issue
1. For volume above 100% option is chosen in budgie-desktop-settings - raven
2. Remove the calendar from raven
3. select built in theme 
4. restart the panel or logout/login

## Actual result
![ubuntu budgie - new development bionic running - oracle vm virtualbox 1_116](https://user-images.githubusercontent.com/996240/52156026-b327ac80-267d-11e9-952c-17922084a6f6.png)

## Expected result
Should just see either 100% or maybe better just a line tick

## Additional information
N/A

**Comment by JoshStrobl** [comment]
Please make sure you are building against 73df80757c8b1781dc238cc3a155f16a58f59e5a
