### ISSUE TITLE
Caps lock key isn't switching keyboard layouts

### ISSUE THREAD

**Issue by notuxius** [solus-project/budgie-desktop#1743]
## Description
I tried to set Caps lock as keyboard layout changer in Gnome Tweaks -> Keyboard & Mouse -> Additional Layout Options -> Switch to another layout but it's not working

## Budgie version
budgie-desktop 10.5 (git-6d814d566f3744d13eed1a285c8c210fde1fda77)

## Operating system
Manjaro Budgie

## Additional information
Also tried to set Caps key in Gnome Settings -> Devices -> Keyboard and it's not setting there

**Comment by JoshStrobl** [comment]
The supported keyboard shortcut for changing the keyboard layout is Super (Win) + Space. Not all settings in **GNOME** Tweaks / **GNOME** Control Center necessarily apply to Budgie.

**Comment by ViktorPegy** [comment]
@JoshStrobl, Ok, how to change it with Caps Lock? It is very necessary

**Comment by kirienko** [comment]
For some reason not all settings from `gnome-tweaks` are supported by all OS. I had the very same problem in Solus 4.1 with Budgie 10.5.1. The solution which works for me is the following:
* go to `dconf-editor`
* there is `org/gnome/desktop/wm/keybindings/switch-input-source`
* put `['Caps_Lock']` as a "Custom value" there
That's all. Additional switching options are [here](https://github.com/solus-project/budgie-desktop/issues/269).

**Comment by JoshStrobl** [comment]
We support Super + Space and Alt + Shift in git builds. No further support is planned.
