### ISSUE TITLE
Touchpad tap to click not working

### ISSUE THREAD

**Issue by parkerlreed** [solus-project/budgie-desktop#175]
Arch x86_64
budgie-desktop-git

50-synaptics.conf has TapButton1 set to 1. Tapping works in i3 and Xfce.

When I launch budgie desktop trackpad works but tapping does nothing.

**Comment by Justinzobel** [comment]
Assuming this has to do with:
chromeos_laptop is the module. Path is drivers/platform/x86/chromeos_laptop.c 
CONFIG_CHROMEOS_LAPTOP=m

**Comment by Justinzobel** [comment]
Found this: "The GTX 750/750 Ti will work with Nouveau but you still need to manually extract the GPU firmware/microcode from the binary blob to expose hardware acceleration support."

Going to guess budgie wm is an accelerated desktop that needs the GPU?

**Comment by parkerlreed** [comment]
The touchpad works fine. Kernel module is there. Budgie seems to not be respecting the xorg conf file. It works in other DEs.

**Comment by ZetaHunter** [comment]
It works perfectly well on my Asus, but then again, I didn't have any custom changes to xorg synaptics conf.

**Comment by ikeydoherty** [comment]
Unrelated to Budgie - it doesn't manage X11 specifics. If your distribution disables configuration via gnome-control-center + gnome-settings-daemon (the normal way) you'll need to edit X11 configuration manually.
