### ISSUE TITLE
Updated en_GB translations

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1750]
as an aside there doesn't seem to be an obvious way to ping the reviewers of a translation on the weblate instance ...

Please can the reviewers of the en_GB translation please have a look at my suggestions.

Seems like quite a few Americanisms have appeared in the British English approved strings.

TIA

**Comment by JoshStrobl** [comment]
There's a contact link at the bottom of Weblate for contacting those of us which administrate the translations. That's the more appropriate means of reaching out regarding translations.
