### ISSUE TITLE
Unable to Build, 2 Errors

### ISSUE THREAD

**Issue by Krutonium** [solus-project/budgie-desktop#1752]
## Description
Unable to Build - 2 Errors, 20 warnings (this part doesn't matter though)

## Budgie version

Latest HEAD,  f625241

## Operating system
Arch Linux

## Steps to reproduce the issue
Attempt to build, and have it fail.

## Actual result
```
../src/raven/raven.vala:150.5-150.39: error: Property `Budgie.Raven.screen_edge' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public Gtk.PositionType screen_edge {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

../src/raven/headerwidget.vala:25.5-25.24: error: Property `Budgie.HeaderExpander.expanded' with custom `get' accessor and/or `set' mutator cannot have `default' value
    public bool expanded {
    ^^^^^^^^^^^^^^^^^^^^
```

## Expected result
Builds Successfully.

## Additional information
I'm attempting to build the desktop from git. I explicitly installed libmutter2, as it is required, then proceeded to build budgie-desktop-git. The above errors result.

**Comment by JoshStrobl** [comment]
Sounds like you have too new a release of Vala, which deprecated their default values in newer releases. This isn't something we'll sort until Budgie 10.5.1.

**Comment by Krutonium** [comment]
What is the newest version that should work for this?
