### ISSUE TITLE
Budgie crashes and removes applets

### ISSUE THREAD

**Issue by BananaLoaf** [solus-project/budgie-desktop#1756]
## Description
At first budgie stops responding to hotkeys and media keys, after a reboot and after logging in it loads only one applet, that is weather, without any panels. After another reboot budgie randomly deletes half of applets in the upper panel. 
[budgie-log.txt](https://github.com/solus-project/budgie-desktop/files/2923242/budgie-log.txt)

## Budgie version
budgie-desktop 10.4

## Operating system
Ubuntu 18.04.2 LTS

**Comment by BananaLoaf** [comment]
After trying to place all of my applets back on their places, budgie crashed after I tried to add weather applet, after a reboot, budgie refused to start, threw me back to login screen, and after that the only thing that loaded was desktop time applet, no panels at all.

budgie-desktop-settings won't start because
> ** (process:5295): WARNING **: 18:05:39.135: budgie-desktop-settings.vala:27: Failed to launch settings UI: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.budgie_desktop.Panel was not provided by any .service files

Here are the logs that followed
[budgie-log_2.txt](https://github.com/solus-project/budgie-desktop/files/2923254/budgie-log_2.txt)

**Comment by fossfreedom** [comment]
Sounds like something gone wrong with your installation.  

Try resetting your panel before making changes step by step

CTRL+ALT+T to open a terminal

    nohup budgie-panel --reset --replace &

**Comment by BananaLoaf** [comment]
@fossfreedom I have reinstalled it before, when I had that issue, but it surfaced again, but I will let you know if anything happens again

**Comment by BananaLoaf** [comment]
@fossfreedom I have not had any crashes yet, but last 2 applets behave really weird. The one before the last applet can not be moved down and they constantly switch places in the panel. This was also observed in freshly installed Ubuntu Budgie 18.10
![image](https://user-images.githubusercontent.com/42458049/54880749-81e78380-4e59-11e9-8a41-d516d8f80f73.png)

**Comment by fossfreedom** [comment]
You must have done a minimal install. Make sure you have showtime, dropby
and quick note applets installed. You dont have to display then on the
panel but they need to remain installed.  Reset your panel and then all
will be ok.

Since you no longer have crashes you can close this issue.
