### ISSUE TITLE
ShowTime applet hidden under desktop

### ISSUE THREAD

**Issue by asamwow** [solus-project/budgie-desktop#1757]
## Description
The ShowTime applet gets hidden when the background is clicked on. My guess is the background is being moved in front of it. 

## Budgie version
v10.4-123-gf2dbc215

## Operating system
arch

## Steps to reproduce the issue
1. Add ShowTime applet
2. Click on background

## Actual result
ShowTime applet disappears. Sometimes reappears when changing workspaces.

## Expected result
ShowTime applet always above background, but below any other windows.

## Additional information
Sorry if this is just a gnome issue!

**Comment by JoshStrobl** [comment]
This is not something we ship, develop, or support. Talk to the Ubuntu Budgie devs.
