### ISSUE TITLE
Files search not matching contents in non-home folders.

### ISSUE THREAD

**Issue by splace** [solus-project/budgie-desktop#1759]
this is an issue tracker for a budgie specific fix, maybe by somehow copying gnomes activation method, because it seems the related upstream known issue only occurs when activation is through the command line.

https://gitlab.gnome.org/GNOME/nautilus/issues/502

budgie-desktop 10.5 (git-f62524110961cbbaf6e947b8edcd5d0773e74e32)

Solus 3

**Comment by JoshStrobl** [comment]
It's quite clearly an upstream issue. We're also on Nautilus 3.26.4 (we hold it back for desktop icons), not 3.28.x

**Comment by splace** [comment]
OK, well gnome doesn't seem to have any interest, (reported back in 2013 in 3.8.x )

and now i guess budgie doesn't.

so this report is for information, stop other people wasting time reporting something that isn't going to be fixed, perhaps it would be nice to include some documentation, or remove a non-functional feature?

**Comment by JoshStrobl** [comment]
We are not responsible for the development or maintaining of a separate project's file manager, no more if there was an issue with Caja (MATE's file manager).

**Comment by splace** [comment]
> this report is also for information, to stop other people wasting time reporting something that isn't going to be fixed

and has a link to where to add weight to getting it fixed.

**Comment by JoshStrobl** [comment]
Again, this is an upstream issue. It needs to get fixed, upstream.
