### ISSUE TITLE
error: The type name `GLib.ListModel' could not be found | on Gnome 3.16

### ISSUE THREAD

**Issue by alexis-diavatis** [solus-project/budgie-desktop#176]
VALAC    libicontasklistapplet_la_vala.stamp
gtk+-3.0.vapi:3135.27-3135.40: error: The type name `GLib.ListModel' could not be found
		public void bind_model (GLib.ListModel? model, owned Gtk.ListBoxCreateWidgetFunc create_widget_func);

**Comment by ikeydoherty** [comment]
Yeah thats a vala issue, you need to newer Vapi

**Comment by alexis-diavatis** [comment]
How I get that? I have Vala from master. Plus Budgie-Desktop package on AUR is also broken on 316 with the same error.

**Comment by Justinzobel** [comment]
You need to use the git version

**Comment by alexis-diavatis** [comment]
@Justinzobel That's Im saying. I have the Git version

**Comment by alexis-diavatis** [comment]
@Justinzobel @ikeydoherty I can build it with Vala 0.26, but not with Vala 0.28 or Vala from master.

**Comment by Justinzobel** [comment]
budgie-desktop in the AUR is not the git version, budgie-desktop-git is.
You said you were running budgie-desktop.

Budgie hasn't yet been tested fully with GTK3.16 or Vala 0.28 so we are
unable to provide support for it just yet.

**Comment by alexis-diavatis** [comment]
@Justinzobel I just let you know. I have it running now!

**Comment by kzero11** [comment]
@alexis-diavatis I am having the same error, what did you do to correct it?

**Comment by Justinzobel** [comment]
@kzero11 are you using budgie-desktop or budgie-desktop-git from the AUR?

**Comment by kzero11** [comment]
@Justinzobel I am using budgie-desktop-git.

**Comment by ZetaHunter** [comment]
I solved my issue by doing yaourt extra/vala, which installed older version compared to testing branch.
And then budgie-desktop-git, worked perfectly.

**Comment by kzero11** [comment]
@ZetaHunter that solved the issue of building the Budgie desktop. Thanks.

**Comment by alexis-diavatis** [comment]
@kzero11 Sorry for the late response. I compiled it against Vala 0.26, with Jhbuild. But I see you already fixed that from AUR :)

**Comment by ikeydoherty** [comment]
So given this isnt a Budgie issue it seems, I'll close it? Its OK to reopen if its still an issue..

**Comment by IcyTesseract** [comment]
This is still an issue at least with Vala 0.28.0-1 and GTK 3.16.2-1 so I'd reopen it if Solus OS intends to make use of GTK 3.16.

**Comment by HeikoAdams** [comment]
Budgie-Desktop doesn't compile on Fedora 22 beta with Vala 0.28.0-1 and GTK 3.16.1-1

**Comment by ZetaHunter** [comment]
@IcyTesseract, @HeikoAdams Please, for sake of gods, read the thread and understand that we do not yet support Vala 0.28, please downgrade to Vala 0.26.
