### ISSUE TITLE
New applet switcher minor polish

### ISSUE THREAD

**Issue by P4prik4** [solus-project/budgie-desktop#1760]
installed the window preview applet and loving it. 
what would perfect it for me:

mostly make 123... clickable and bullets bigger. 

when hovering over workspace of choice on release alt go to work space
the workspace bullets could be a tad bigger. 

make 123... clickable/hoverable too.

**Comment by JoshStrobl** [comment]
> installed the window preview applet and loving it.

We don't have a window preview applet. This should be reported with the applet developers, likely Ubuntu Budgie.
