### ISSUE TITLE
Some Media Keys (Not all) and custom keyboard shortcuts irregulary don't work after boot/reboot

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1763]
Copy paste  from the launchpad bug report.  Note - we have had several reports over the years but this bug report has been analysed by a kind GNOME dev and gave a possible implication of what is causing the issue.

https://bugs.launchpad.net/ubuntubudgie/+bug/1818978

## Description
After boot or reboot some media keys (Volume Up/Down) don't work, but others do (e.g. Brightness Up/Down). Custom Keyboard Shortcuts then don't work at all. When a non working media key oder shortcut is pressed the following message appears in syslog:

gsd-media-keys[2016]: Could not find accelerator for accel id 169

This happens irregularly. Sometimes everything works, sometimes it doesn't work as described above until next reboot.

This bug was first reported here: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/151 (And also here: https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/1817286 but important information is provided by first link)
Benjamin Berg, Maintainer of gnome-settings-daemon, found out it's related to budgies implementation of gsd-media-keys. Please look at this issue for logs and details. He even pointed out where the root issue might be (It seems like 'UngrabAccelerator' isn't implemented correctly)

I can only reproduce this bug inside budgie desktop enviornment, not inside an ubuntu gnome session installed via 'sudo apt-get install ubuntu-gnome-desktop'

## Budgie version
budgie desktop v10.4 and 10.5

## Operating system
Ubuntu Budgie 18.04/18.10/19.04

## Steps to reproduce the issue
This is really hard to reproduce - it does appear to be random - but mainly after a clean boot/reboot rather than a logout and login

"After boot or reboot some media keys (Volume Up/Down) don't work, but others do (e.g. Brightnes Up/Down). Custom Keyboard Shortcuts then don't work at all."

## Actual result
some media keys (Volume Up/Down) don't work, but others do

## Expected result
All media keys should work

## Additional information
Linked GNOME report https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/151

"Please point your distribution/budgie developers to:

Mär 05 17:07:52 BaBook budgie-wm[11980]: g_hash_table_iter_next: assertion 'ri->version == ri->hash_table->version' failed

https://developer.gnome.org/glib/stable/glib-Hash-Tables.html#g-hash-table-iter-init saying Modifying the hash table after calling this function invalidates the returned iterator

https://developer.gnome.org/glib/stable/glib-Hash-Tables.html#g-hash-table-iter-remove
https://github.com/solus-project/budgie-desktop/blob/master/src/wm/shim.vala#L222

 Benjamin Berg @bberg · 1 day ago
Maintainer

Hah, I looked a bit more. Budgie doesn't implement UngrabAccelerator …
"

EDIT:

Currently testing whether changing https://github.com/solus-project/budgie-desktop/blob/master/src/wm/shim.vala#L222 to `iter.remove()` resolves this issue.

**Comment by xiorcal** [comment]
I have the same issue (custom keyboard shortcut not working after reboot) as well.

**Comment by nemoforum** [comment]
Confirm. Very annoying.

**Comment by kopaczew** [comment]
Same story (Ubuntu 18.04). Sometimes my Tilix shortcut doesn't work (I have to restart lightdm). In syslog there is a message:
```
gsd-media-keys[4874]: Could not find accelerator for accel id 158
```
Budgie version:
```
~$ budgie-desktop --version budgie-desktop
budgie-desktop 10.5
Copyright © 2014-2019 Budgie Desktop Developers
```
