### ISSUE TITLE
Setting to Partially Hide the Budgie Panel (like have half showing)

### ISSUE THREAD

**Issue by P4prik4** [solus-project/budgie-desktop#1766]
### Current Budgie version
10.4

### Use-cases
what I have going so far to navigate: 
https://peertube.geekshell.fr/videos/watch/c2d2e4ee-7f68-4007-afd9-a17853a335f8

I like how tint 2 alot (customization wise) and like how you can have task run up the entire width of the panel this way (major sell) I also like how they don't group even and that they just get thinner like browser tabs the more you have. (plus we have workspaces anyways why do we need to group/stack windows?). Though I could see sorting windows by type. 
I also like to exit a task by right click too. 
lets people have a unique looking desktop. 

Another application is it would work nicely with Ubuntu's Budgie Pixel Saver Applet & Global Menu Applet, that is preferably if the budgie panel also had a short unhide delay. 

in the video you see the setup I'm using with tint2 panel.  It works pretty nicely but could be made more seamless/intended. 

the main use for this feature aside from alongside tint2 panel is if you like a large bar with bigger icons. 
but since it pairs so well with tint2 I think that on it's own makes it worth while. 

### Proposal
make it so you can partially hide the budgie panel, so it would just shift part way down.  Enough to show the tint2 panel more. when hovering over budgie bar show it in full. 

### References
would pair well with this request to add a slight show delay: 
#1762 - "Pls add option to set a panel hide delay"

**Comment by JoshStrobl** [comment]
I have no plans on support other panels for the Budgie Desktop.
