### ISSUE TITLE
Raven calendar display day adds extra row of numbers

### ISSUE THREAD

**Issue by craig-toyoracer** [solus-project/budgie-desktop#1769]
## Description

When selecting the new display day in Raven, an extra row of numbers appear on the left side of calendar.

## Budgie version

Budgie 10.5

## Operating system

Solus 4

## Steps to reproduce the issue

toggle on/off selector with Raven open and row will appear/disappear

## Expected result
no extra row

**Comment by JoshStrobl** [comment]
> When selecting the new display day in Raven, an extra row of numbers appear on the left side of calendar.

It isn't new day, it's to display the week numbers. It's intentional.
