### ISSUE TITLE
Changing keyboard layout is not working

### ISSUE THREAD

**Issue by ovr** [solus-project/budgie-desktop#177]
Hey! And thank you for awesome DE

I am using 2 languages

english as default
russian

Shorcut is not working
And change button in languages preferces is not working

Thanks

**Comment by Anachron** [comment]
After a few reboots it was fixed for me. Not sure if it had anything to do with my latest update though.

**Comment by ikeydoherty** [comment]
This is not a Budgie issue - this is either a distribution or packaging issue.  Is it on Solus or not?

**Comment by ovr** [comment]
It was a Solus project, but now I cant check latest update via I removed it from my laptop

@ikeydoherty Please check it in the latest OS, for example add ru and en languages and try to change it by shortcuts

**Comment by ikeydoherty** [comment]
@ovr thats why I asked, we have a gnomes-settings-daemon issue in Solus where the keyboard layout isn't being updated. Keeping this open.

**Comment by Abdulrahman-N** [comment]
I'm having the same issue with the latest release (beta 2), I can't type in any other language besides English.

**Comment by ovr** [comment]
@ikeydoherty 
I installed budgie-desktop (latest master) on Ubuntu 15.04 and change language is not working by keyboard shorcut. It's working only by clicking it by mouse
:(

**Comment by ikeydoherty** [comment]
@ovr  do any shortcuts work?

**Comment by ovr** [comment]
@ikeydoherty 
Yeap, for example alt + tab is working but with 25ms slow effect

**Comment by ikeydoherty** [comment]
Ok what about non-wm-internal shortcuts, like windows key, alt+space, ctrl+alt+{left,right} (workspace), that require gnome-settings-daemon shortcut integration? (Better yet, media keys)

**Comment by ovr** [comment]
ctrl+alt+{left,right} working without delay
ctrl+window+{left, top, bottom} is working but ctrl+window+right is not working

alt+space nope what is it?

**Comment by tista500** [comment]
Greetings,

Usually G-S-D's Input-Method handler (means a wrapper of ibus) won't work properly outside the Gnome-Shell (at least on Ubuntu) from when Gnome3 devs had dropped supporting flashback session. If so, we can call "ibus's shortcut keys" directly. This is an alternative method and outdated today, but sometimes it would be useful on some DEs.

We can set it via `ibus-setup`.

![alt text](http://s7.postimg.org/6a914iu0r/Screenshot_from_2015_06_07_12_32_28.png "ibus-setup1")

![alt text](http://s2.postimg.org/z1skijs5l/Screenshot_from_2015_06_07_12_39_52.png "ibus-setup2")

And finishing such settings, you'd better to reload ibus via `ibus-daemon -rd &` in terminal.

Then IM-switcher window can be handled by WM (like mutter, metacity and openbox or so) without Gnome-Shell's UI. Fortunately ibus still has old-school systray indicator, so we can see it inside the budgie-panel's message-area (if systray plugin was loaded).

![alt text](http://s17.postimg.org/lkg3zjhjz/Screenshot_from_2015_06_07_12_51_01.png "ibus switcher")

Regards.

**Comment by ikeydoherty** [comment]
Fixed in v10

**Comment by ovr** [comment]
@ikeydoherty Thank you, i will try it by VM on OSX ASAP
:beers: :cake:

**Comment by waltharius** [comment]
Hi all,
I've just installed Solus 2017.01.01 on VirtualBox and I faced this problem too. I choose Polish after installation as my input method and English as my system language but no polish letters available :(
When I tried this workaround with ibus-setup polish letters appears but after solus being restarted I can login but no desktop showed. Only wallpaper.
