### ISSUE TITLE
When updating to Solus 4 budgie the new Plata theme was not included.

### ISSUE THREAD

**Issue by joshontech** [solus-project/budgie-desktop#1773]
## Description

I installed Solus Gnome and than installed the budgie desktop both prior to 4.0 release. After the 4.0 update I do not see the new Plata theme at all. I only get the old themes as options. 

## Budgie version

10.5

## Operating system

Solus 4.0

## Actual result

![Screenshot from 2019-03-19 12-27-16](https://user-images.githubusercontent.com/44295541/54624223-5886bc00-4a43-11e9-835e-3e2b4e124a09.png)

## Additional information
I am really hoping I do not have to reinstall but if I must I will.

**Comment by JoshStrobl** [comment]
This has nothing to do with Budgie and is intentional. The plata default is part of a different branding sub-package so we don't force its installation on user systems. Just install the theme from the repo.

**Comment by joshontech** [comment]
Sweet thanks for the reply its much appreciated. I figured I could get it
somehow just wanted you to be aware if it was an issue. Thanks again for
your hard work on solus :)
