### ISSUE TITLE
Dock length issue creating empty slots

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#1775]
## Description
As you can see here: https://discuss.getsol.us/d/249-dock-issue/
I have a problem with the dock, when I close a software that is not in the favourites the dock adds an empty slot and the dock's length keeps growing.

## Budgie version
budgie-desktop 10.5

## Operating system
Solus last sync

## Steps to reproduce the issue
Open an non-favourite software then close it when you have a dock that only shows favourite software

## Actual result
Check the link above

**Comment by TarsolyGer** [comment]
Have the same issue with 10.5-1 on Arch Linux, running in VirtualBox.

![VirtualBox_Arch Test Fist try_09_06_2019_22_11_20](https://user-images.githubusercontent.com/51498143/59159365-91df3d00-8b03-11e9-8c93-db4c24245c9e.png)
![VirtualBox_Arch Test Fist try_09_06_2019_22_11_36](https://user-images.githubusercontent.com/51498143/59159366-94419700-8b03-11e9-9806-38fb2dea9f61.png)
