### ISSUE TITLE
Touchpad not working on Lenovo 11e

### ISSUE THREAD

**Issue by zerolozen** [solus-project/budgie-desktop#1778]
Did a clean install to the laptop and the touchpad is not working on my Lenovo Thinkpad 11e (20D9). Any ideas?

**Comment by zerolozen** [comment]
Bump.

**Comment by VladStelin** [comment]
On the laptop in the buttons F1-F12 there is an image of the dot, you need to press Fn + F with the dot

**Comment by JoshStrobl** [comment]
Stop bumping. You also already created a support query at https://discuss.getsol.us/d/343-touchpad-not-working-on-lenovo-11e
