### ISSUE TITLE
[Feature Request] Could you please switch to other Gtk theme(s) from Plata as default?

### ISSUE THREAD

**Issue by tista500** [solus-project/budgie-desktop#1780]
### Current Budgie version
10.5 (git-c61ccfc02a59d2aa9f56bf39f0d731bbb54def35)

### Use-cases
Mate 1.22 brings new Marco, but I won't support new Marco anymore.

### Proposal
Please hunt other themes.

### References
https://gitlab.com/tista500/plata-theme/issues/38

**Comment by kyrios123** [comment]
To be clear, this concern the MATE edition, not Budgie (and GNOME).

**Comment by tista500** [comment]
Ah, wrong place.
