### ISSUE TITLE
Windows crash when I click

### ISSUE THREAD

**Issue by edivandjs** [solus-project/budgie-desktop#1788]
Windows lock when I click. If I open more than one window in the file manager, while minimizing them, when I click they do not open. They remain as if they were locked. Another thing that does not appear a preview of the window when I move the mouse through the minimized tabs.

**Comment by JoshStrobl** [comment]
I'd be curious for you to elaborate what you mean by windows crashing. What windows? All of them? Do you have any logs such as when you have the application running from the Terminal to indicate the cause of the crash?

Regarding your other issues:

1. We do not by default show all windows when you click an item in the IconTasklist. This can be enabled in the Budgie Desktop Settings applet settings for the IconTasklist.
2. Your other issue isn't an issue, window previous for IconTasklist items is a feature-request, not something that is supported at this time.

**Comment by edivandjs** [comment]
![Sem nome](https://user-images.githubusercontent.com/42190126/55361264-1b8fe000-54ad-11e9-9e41-273e295b9f9a.png)

Notice that in the file manager icon there are two windows open. The bug is that I often click to open and it does not open.

**Comment by JoshStrobl** [comment]
> The bug is that I often click to open and it does not open.

That's not a bug. You have multiple windows open. Right click and click on the window, scroll up with your touchpad or mouse to switch between them, or enable the option I specified.

That's nothing to do with crashing.

**Comment by edivandjs** [comment]
Thanks for the time made available.

The confusion was this: I was imagining that it was possible to right-click to see the windows, when minimized, but that by clicking with the esquedro they would maximize. Since they were not maximizing, I imagined it to be a bug. But I appreciate the explanation.
