### ISSUE TITLE
Animation speed depends on random GPU-related factors

### ISSUE THREAD

**Issue by serebit** [solus-project/budgie-desktop#1789]
## Description
With the proprietary Nvidia drivers installed, most (if not all) Budgie animations are significantly sped up to varying degrees. The place this is most obvious is the software center, where the updates loading spinner moves at lightning speed. In addition, the button highlights on click when using Plata don't appear to bubble out, they just instantly highlight. This has happened from Budgie 10.4.1 to Budgie 10.5 (from testing), and Nvidia 390 to 418, on my laptop's GeForce 940MX. It's been happening for at least 6 months, to my knowledge. If the Nvidia drivers are not installed and the system instead uses the Intel iGPU, these animation accelerations are not present.

Edit: Correction, this also happens with the line `Option      "AccelMethod" "sna"` in an xorg conf file when using my Intel iGPU. In this case, animations don't play at all, as described below by @lallenfrancisl.

Edit 2: This also appears to happen on my desktop PC, which uses an AMD RX 480 with the open-source Mesa drivers, but to a lesser extent. The animations are faster, but still slow enough that they didn't catch my eye until recently.

Edit 3: After further inspection, the speed of the animations seems to depend on the speed of the compositor on AMD systems. With two monitors, one at 144 Hz and one at 60 Hz, the animations play at normal speed. With only one monitor enabled at 144 Hz, the animations play quickly. With only one monitor enabled at 60 Hz, the animations play at normal speed.

## Budgie version
10.4.1 to 10.5.1

## Operating system
Solus 4.1, latest updates.

## Steps to reproduce the issue
- Install the Nvidia GLX drivers from the official repository on an Optimus laptop, and reboot.
- Add `Option      "AccelMethod" "sna"` in an xorg conf file on a system that uses an Intel iGPU.

## Actual result
Animations are significantly sped up, slightly sped up, or don't play at all

## Expected result
Animations should play at normal speed

**Comment by lallenfrancisl** [comment]
Yes this happens to me too. It becomes as if animations are turned off.
Budgie 10.5 on Solus 4

**Comment by serebit** [comment]
This is curious... It also seems to happen if I enable certain flags in Xorg when using my Intel iGPU (seemingly `"AccelMethod" "sna"`). When I do that, it's as you describe @lallenfrancisl, the animations just seem to not play at all.

**Comment by serebit** [comment]
Updated the OP with more info, since I found this to also happen on my AMD-driven desktop.

**Comment by hmnd** [comment]
Happening for me too with a 960m. However, it doesn't always happen for me and usually goes away after a reboot.

**Comment by serebit** [comment]
This might not be an issue anymore. I'll have to test further.

**Comment by serebit** [comment]
Appears to have been caused by an issue with part of the DE stack other than Budgie. Closing. Feel free to reopen if this starts to happen again.
