### ISSUE TITLE
Budgie freezes when opening apps menu and settings menu (left hand menu)

### ISSUE THREAD

**Issue by clevrpwn** [solus-project/budgie-desktop#179]
Budgie freezes when opening apps menu and settings menu (left hand menu), the problem was fixed when I merged in laracraft93's clock settings into my fork so it seems the problem is originating in the clock applet.

**Comment by ikeydoherty** [comment]
What version of Budgie are you using? The lockup was resolved a little while ago

**Comment by clevrpwn** [comment]
I've been building from git on ubuntu gnome 15.04 and it persisted until I merged it the clock settings 4 days ago however it may have very well have been an isolated issue.

**Comment by clevrpwn** [comment]
seems I hadn't merged in your changes for a while closing since the issue is resolved.

**Comment by ikeydoherty** [comment]
Out of curiosity why have you forked Budgie.. ? We could do with people working upstream with us as opposed to various feature forks
