### ISSUE TITLE
Change the "Show the run command prompt" text for ALT + F2

### ISSUE THREAD

**Issue by mjarkk** [solus-project/budgie-desktop#1790]
## Description
The text `Show the run command prompt` seems a bit unappropriated.

I think this is unappropriated because this launches a program it does not run a command.  
beside that i think this is the same name as the original gnome desktop `alt` + `F2` binding.

## Budgie version
`10.5`

## Operating system
Solus 4.0

## Steps to reproduce the issue
1. Open Settings
2. Click Devices
3. Click Keyboard
4. Go to the System section
5. The last item it's name

## Actual result
(The original keybinding was `alt` + `F2`)  
![image](https://user-images.githubusercontent.com/15320763/55686309-e594a500-595f-11e9-9525-add1a7cd0e90.png)

## Expected result
Something like **App launcher** or **Quick launch**

## Additional information
Just installed Solus today and seems to be a great distro!!, Great work keep it up.

**Comment by JoshStrobl** [comment]
That is from GNOME Control Center and applies to GNOME Shell, not Budgie.
