### ISSUE TITLE
Cannot compile under Gentoo

### ISSUE THREAD

**Issue by EGStein** [solus-project/budgie-desktop#1792]
OS: Gentoo
Budgie Version: 10.5

Hello, I am currently trying to compile the Desktop under Gentoo. However, when I try to compile it via the directions on the wiki page, I get this error:
```
Dependency vapigen found: NO (tried pkgconfig and cmake)

meson.build:44:0: ERROR:  Dependency "vapigen" not found, tried pkgconfig and cmake
```

I know I have all the dependencies installed and I have tried to ln -s vapigen, but it didn't do anything different. Is there a way I could get it to detect dev-lang/vala?

**Comment by JoshStrobl** [comment]
There are multiple tasks related to Vala builds and newer GNOME stack upgrades. Please search for them.
