### ISSUE TITLE
[Request] Combine active titlebar with top panel.

### ISSUE THREAD

**Issue by ripefig** [solus-project/budgie-desktop#1793]
Take advantage of fitt's law to manage active window by transferring some titlebar features to the mostly empty top bar.

### Use-cases

Move mouse to the top of the screen and drag to move active window. This would work best if you could drag from any point on the top panel, including menus and applets (you never need to drag a menu in the panel). This behavior would be consistent with how GTK headerbars work - you can drag a window by the controls.

Right-click or double click on empty space in the top bar to maximize restore. 

Close window by putting a close button in the right-hand corner of the top bar.

### Proposal

See above.

### References

For an implementation see Latte dock on KDE. It's very useful to be able to take advantage of the top edge to quickly move, maximize and close windows.

**Comment by JoshStrobl** [comment]
While I appreciate the feature request, no further features are being added into the Budgie 10 series. I also don't agree with the user experience of having the window titles merged into the panel (like it was on Unity). It negatively impacts usability of menus on multi-monitor systems.

**Comment by ripefig** [comment]
@JoshStrobl I don't really see what this has to do with menus. I am by no means proposing global menus  (there are better ways to address the menu problem, such as [moving it to a HUD, which is incredibly productive](https://medium.com/@leftcrane/gui-hud-using-global-menu-features-hacks-572760272168), though flatpak and gnome are sadly doing everything possible to make this difficult. Could be done with the backing of a major desktop though.)

This is just plain window management. Can we consider this for Budgie 10? If the feature were implemented, it would only apply to windows on the monitor with the panel. 

For secondary monitors, it's not really that important because they are not used as often and the titlebar of maximized/tiled windows complies with Fitts. It's incredibly productive - especially for multimotor - to be able to throw your mouse to the top of the display, drag and fling and snap the window to any location. 

Overall I'd like to see Budgie take Unity innovations and Fitts more seriously, otherwise it's hard to see what it's offering over stock Gnome.
