### ISSUE TITLE
public key to verify the tarball

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1794]
@JoshStrobl 

quick question - I would like to verify the 10.5 tarball using your public key - had a quick search here but could not find you https://keyserver.pgp.com

Have you uploaded your public pgp key?  if so where so that I can download?

TIA

**Comment by JoshStrobl** [comment]
The GPG key is available at https://getsol.us/releases/joshua-strobl.gpg as well as sks-keyservers: http://pool.sks-keyservers.net:11371/pks/lookup?op=get&search=0xDD672FE9A2BE5892

**Comment by fossfreedom** [comment]
Josh - on behalf of Debian - much appreciated.
