### ISSUE TITLE
Pinned Firefox icon in Icon Task List applet sometimes spawns new a instance instead of switching to running instance

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#1797]
## Description
This has so far only happened with Firefox.  That could also be that it's the application I'm most often interacting with, so I can't be sure it's isolated to Firefox.

I've been having issues for the past several weeks with my pinned Firefox icon spawning a new instance of Firefox when clicked, instead of switching to the running instance.   It has the single blue dot under it, as if it knows there's a running instance already... yet it spawns a new instance instead of bringing the existing window to the foreground.

It happens randomly, usually once every day or two.  I don't have a clue what causes this.  I use private windows a lot and I always open them from inside Firefox.  Maybe something to do with that? 

desktop file: [firefox.desktop](https://github.com/solus-project/budgie-desktop/files/3096345/firefox.desktop.txt)

Screen recording: https://www.youtube.com/watch?v=NgQvCqQx25Y
(Youtube's player controls are going to obscure what you're supposed to be looking at for the first few seconds until it disappears.)

## Budgie version
budgie-desktop 10.5

## Operating system
Solus 4

## Firefox version
Stable 66.0.3, as shipped with Solus

## Steps to reproduce the issue
Unsure, very random.  Could possibly have something to do with me opening a lot of private windows from within Firefox?

## Actual result
A new instance is spawned
https://www.youtube.com/watch?v=NgQvCqQx25Y

## Expected result
The already-running instance is of Firefox is brought to the foreground.

## Additional information
Will edit if I find anything else

**Comment by chathurawidanage** [comment]
This can be reproducible on 20.04 too. Any workaround for this?
