### ISSUE TITLE
Budgie Panel freezes occasional.

### ISSUE THREAD

**Issue by ZetaHunter** [solus-project/budgie-desktop#180]
Hello,
I am using Arch Linux, ever since I installed Budge WM on my work laptop.
Occasionally the panel when opened will freeze the whole system dead, or rather just the Xserver.
The only way to unfreeze it I found is opening SSH or TTY session and doing pkill panel.
Would love to share some logs but I can't as I couldn't find any logs.
I tried watching journal and dmesg, neither outputted anything.
I'd love to fix it myself, but I don't know Vala.
It happens about 10 times a day, I already have a seperate ssh session just to pkill it.
Another problem caused by this is that when I pkill it, every 2nd time the whole WM will bringe itself down, thus killing my whole session, not nice.

My Budgie version is that of AUR git branch.

**Comment by ZetaHunter** [comment]
I just cloned the repo and recompiled myself and against what was suggested in #179 it still freezes, much less common, but still happens.
Also weird bug: after killing panel process it loses its transparency and is that of gtk theme color.

**Comment by ZetaHunter** [comment]
Okay so I think I got to narrow it down to some events related to scrolling.
Source: It froze again when I was scrolling in menu looking for Thunderbird.

Off topic suggestion (not sure if another thread should be made):
The Budgie preference -> Menu has an option for category-name less menu, but when turned on, only the names go away, and so say an application is in 2 categories as the same time, it will show up in the menu 2 or more times.
For example Steam, it has Games and Internet categories.

**Comment by ikeydoherty** [comment]
Popover is going to need a rewrite then. Fun :)

**Comment by ikeydoherty** [comment]
Popover changes are in, please confirm if this issue is now resolved.

**Comment by ikeydoherty** [comment]
If you kill budgie-panel the session will exit on the 3rd time, this is built in behaviour. If budgie-panel looses transparency its because the wm was killed and not the panel.

I believe the panel issue was resolved, and I'm going to close this now due to lack of response. If you find this still happens, reopen.

**Comment by nickcorona** [comment]
Not solved. Still occurring in 2019.
