### ISSUE TITLE
Budgie settings wont open

### ISSUE THREAD

**Issue by Alexander88207** [solus-project/budgie-desktop#1804]
## Description
Budgie settings wont open

## Budgie version
the latest from git

## Operating system
Sabayon

## Steps to reproduce the issue
Build budgie from git & try to open the budgie-settings.

## Actual result
(budgie-panel:24478): GLib-GIO-ERROR **: 18:59:59.199: Settings schema 'org.gnome.nautilus.desktop' is not installed

## Expected result
That the settings open

**Comment by JoshStrobl** [comment]
Not a valid issue. You should only be compiling it with Nautilus Desktop Icons support if you're using Nautilus 3.26, as stated in the meson file.

**Comment by Alexander88207** [comment]
Alright thanks!
