### ISSUE TITLE
Url at repo description seems to be incorrect 

### ISSUE THREAD

**Issue by andreujuanc** [solus-project/budgie-desktop#1806]
![image](https://user-images.githubusercontent.com/360052/56870223-82e97300-6a0c-11e9-85e5-4ff88cb6f242.png)

I believe  https://solus-project.com is down and the new one is https://getsol.us

Might save people a couple of clicks.

Cheers

**Comment by JoshStrobl** [comment]
Unfortunately, the previous project lead never assisted us in getting myself and @DataDrake full administrative access to all solus-project GitHub org repositories, and therefore that is not something we  can change, otherwise I would've changed it.
