### ISSUE TITLE
Dock tooltip off the screen

### ISSUE THREAD

**Issue by howyay** [solus-project/budgie-desktop#1809]
## Description

Tooltip text on dock icons is off the screen

## Budgie version

Budgie 10.5, built from latest git commit

## Operating system

Arch linux

## Steps to reproduce the issue

Create a bottom panel,
Change panel type into dock mode
Add icon task list applet to the dock,
Hover cursor over the icons near the bottom of the screen

## Actual result

Tooltip texts are off the screen
![image](https://user-images.githubusercontent.com/28365438/57023541-4f6f3a00-6c00-11e9-8b42-eed64a9d800c.png)

## Expected result
Show tooltip above the cursor if the cursor is near the bottom of the screen

**Comment by haoyet** [comment]
This doesn't happen when auto hide panel is set to intelligent/always regardless of the state

**Comment by yursan9** [comment]
Okay, I can reproduce the bug. But, It only happens on some applet like notification and NetworkManager applet.

**Comment by goldencut** [comment]
On Solus the panel doesn't even have to be in dock mode.
![Screenshot from 2019-06-28 00-23-51](https://user-images.githubusercontent.com/5072792/60386411-27d00d00-9a9d-11e9-8df0-43e0d0aea543.png)

**Comment by pitermacher** [comment]
I'm having similar issue on Solus 4.
Bottom dock panel containing just 'Icon Task List' when size is equall and over 55.
![morethan55](https://user-images.githubusercontent.com/57494657/68421071-78ffb400-0195-11ea-8a85-2a00664477fa.jpg)

When size is lower tooltips works fine.
![lessthan55](https://user-images.githubusercontent.com/57494657/68421027-6a190180-0195-11ea-8960-c5e2a0ff8a7b.jpg)

Not a burning issue since you can always decrease the size of icons to see tooltips.
I will stick with 54.

**Comment by brandum** [comment]
Same issue on Solus 4.1 -- tooltips over system tray icons not appearing correctly.

when the panel on bottom I hover over the notifications icon I see this (notice the little grey bar)
![1_bad](https://user-images.githubusercontent.com/47691573/77828566-95889280-711c-11ea-9e5d-aa2d2a5333e7.png)

...but when I move the panel to the top I see:
![1_good](https://user-images.githubusercontent.com/47691573/77828575-a46f4500-711c-11ea-9981-27acd391aaa8.png)

Same thing with the notifications icon:
![2_bad](https://user-images.githubusercontent.com/47691573/77828590-b2bd6100-711c-11ea-976f-9d9b00880ce9.png)

...then with the panel at the top:
![2_good](https://user-images.githubusercontent.com/47691573/77828606-c072e680-711c-11ea-8594-c3a599ae80a0.png)

**Comment by serebit** [comment]
This appears to be an issue with GTK and not with Budgie. Please give your input on the relevant issue here: https://gitlab.gnome.org/GNOME/gtk/-/issues/2784
