### ISSUE TITLE
Budgie WM dosen't work with Xephyr well

### ISSUE THREAD

**Issue by ZetaHunter** [solus-project/budgie-desktop#181]
Hello, tried to make a debug script https://gist.github.com/ZetaHunter/9232d6feb6fd4562648e
But it seems to be having hard time working, especially on a laptop.
My screen isn't big, and so when I start it, the new WM makes the screen expand to whatever the current WM is running in. Which is problematic. Could this be caused by poor Budgie Xorg variable handling / ignoring?

PS. Ikey how do you normally debug Budgie?

**Comment by ikeydoherty** [comment]
Tbh I've never used with with Xephyr - its notoriously difficult with Mutter. In short, what works with Mutter will work with Budgie. If you need me to add further debugging output I can?

**Comment by ikeydoherty** [comment]
Fixed in v10 - use `test.sh`
