### ISSUE TITLE
Applet icon-tasks list : popover on right click stays on screen? 

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#1812]
## Description

When you right click on icon, there is a popover.

When you click on anything in that popover, the popover stays in place, you have to click anywhere else to shut it down.

## Budgie version

budgie-desktop 10.5

## Operating system

Ubuntu Budgie 18.04

## Actual result

![Capture du 2019-05-05 02-08-13](https://user-images.githubusercontent.com/1895947/57186210-09a1c280-6edb-11e9-9e83-90e588c8a235.png)

## Expected result
I’d expect the popover to vanish once I click one of its features, and have focus on the latest thing I have launched.

## Additional information
( + as soon as there is _any_ popover active _from panel_, the PrintScreen key no longer works. )

**Comment by JoshStrobl** [comment]
This is intentional, because you may want to perform multiple actions on a window.

**Comment by Coeur-Noir** [comment]
Mmm.

If the most used case is « one action » then it's a click-waste.

If one needs more than one action, then just right click on icon again.

It looks broken the way it stays now because it's a waste of time to have to click to make it vanish.

It's a popover not a full dialog box, that should not stay in the way.

Le 5 mai 2019 05:27:24 GMT+02:00, Joshua Strobl <notifications@github.com> a écrit :
>This is intentional, because you may want to perform multiple actions
>on a window.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/solus-project/budgie-desktop/issues/1812#issuecomment-489385717

-- 
Envoyé depuis Lenovo K6 Note via le courrieleur K9-mail.
