### ISSUE TITLE
Items Clickable for Brief Period before Lock Screen pops in - VirtualBox

### ISSUE THREAD

**Issue by rbharathkumar** [solus-project/budgie-desktop#1813]
## Description
I Currently use Solus-Budgie as a VM in my primary system and Solus - KDE in my laptop.
This issue occurs only inside the VM. If the VM has been left idle for sometime and then clicked back on, there is a brief period of time say 15 seconds for which items are clickable in the desktop before the Lock Screen kicks in. The expected behavior is for the lock screen to pop up immediately.

## Budgie version

budgie-desktop --version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)

## Operating system
Solus 4.0

## Steps to reproduce the issue
1. Install Solus inside a VM.
2. Open a couple of apps, switch back to host system until it is ready to go to sleep.
3. Switch back to Solus, 
4. Try clicking on stuff.

## Actual result
1. There is a small window of time where items are clickable before the lock screen kicks in.

## Expected result
The lock screen should kick in immediately.

**Comment by WaldHabets** [comment]
The issue seems to be related to #1374 
As mentioned in one of the comments, it is likely a gnome issue.
