### ISSUE TITLE
The `Background` window is unresponsive - loading wallpapers takes too long

### ISSUE THREAD

**Issue by szmarczak** [solus-project/budgie-desktop#1814]
## Budgie version

```
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)
```

## Operating system
```
Linux solus 5.0.7-114.current #1 SMP PREEMPT Sun Apr 14 16:32:16 UTC 2019 x86_64 GNU/Linux
```

## Steps to reproduce the issue

1. Open `Settings`.
2. Switch to the `Background` tab.
3. Click on the `Background` box.
4. Try to scroll down immediately as the window pops up. It won't scroll down, it will take a while to load all the wallpapers.

## Actual result

The window is unresponsive for a while.

## Expected result

It should be responsive.

**Comment by JoshStrobl** [comment]
Nothing to do with Budgie.
