### ISSUE TITLE
Enable always-on night light (manual control)

### ISSUE THREAD

**Issue by Xcess** [solus-project/budgie-desktop#1817]
### Current Budgie version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)

### Use-cases
I have sensitive eyes and want to toggle night light (blue color reduction) manually. I want it be always on and turn it off for viewing a movie manually. Current settings does not allow this scenario. The on/off toggle only changes the behavior on other time-controlled modes (sunset to sunrise/ time range). (Windows 10 has Night Light feature the way I want for example)

### Proposal
Add of option to disable schedule and be completely manual in the applet (and settings). Then all you have to do is to toggle the button in applet to enable night light.

**Comment by treepi3** [comment]
You can.

![image](https://user-images.githubusercontent.com/13264659/57750946-bcc3a600-76a9-11e9-86fa-a5bcfdb1c06c.png)


Just click manual and set it for 24hrs.

**Comment by treepi3** [comment]
Set it up like this: 
![image](https://user-images.githubusercontent.com/13264659/57750980-e7adfa00-76a9-11e9-9bea-4b31eb687777.png)

**Comment by JoshStrobl** [comment]
This is a deficiency in GNOME Settings Daemon, I'd suggest filing it with them.
