### ISSUE TITLE
Budgie Menu Bar Display Issue When Changing Size

### ISSUE THREAD

**Issue by treepi3** [solus-project/budgie-desktop#1819]
## Description
When adjusting the panel size, a bit of the top portion of program windows get covered up by the menu bar. I've included a screenshot below. Pay attention to the top bar and the tabs I have opened in brave. You will see how the menu bar overlaps part of the program window.

This only happens when shrinking the menu bar size. If I increase the menu bar size from the default, then it functions properly. But when lowering the size from the default, part of the program window slides under the menu bar.

## Budgie version
Budgie 10.5

## Operating system
Solus 4.0 - Budgie 10.5

## Steps to reproduce the issue
Shrink the size of the top menu bar below the default value. The smaller you make it, the more it overlaps the program window.

## Actual result
Pay attention to the top menu bar and how it overlaps my browser window.
![image](https://user-images.githubusercontent.com/13264659/57749136-73238d00-76a2-11e9-8e1f-c7193bd3dbd1.png)

**Comment by JoshStrobl** [comment]
Please search for existing issues. #869

**Comment by treepi3** [comment]
> Please search for existing issues. #869

My issue wasn't resolved the same way that one was. The issue you posted seemed to be a display or multi-monitor issue. Completely different from what happened to me. But, I just figured out how to fix my issue.

**_Here is the solution if anyone comes across this issue in the future:_**
The fix was just turning off the "Stylize Regions" setting in: Budgie Settings Manager > Top Panel > Settings > Flip the "Stylize Regions" switch.

**Comment by treepi3** [comment]
Edit: Actually it's working with "Stylized Regions" enabled too. Hmm, weird. I just checked to see if it was maybe the previous theme I was using, but that wasn't it either. I guess it fixed itself the last time I rebooted. Weird.
