### ISSUE TITLE
Auto-show/hide an on-screen keyboard when no physical keyboard is attached

### ISSUE THREAD

**Issue by moghingold** [solus-project/budgie-desktop#182]
I'm really jazzed about the idea of having a desktop environment based on material design that allows for the use of existing GNU/Linux applications inside of a clean, from-scratch design paradigm. I was wondering if there were any plans to add an on-screen keyboard to support accessibility and portable devices? If so, is there any way it could auto-show/auto-hide whenever the user needs to input text depending on whether or not the OS detects the presence of a physical keyboard?

**Comment by ZetaHunter** [comment]
My opinion:
I see 2 scenarios here.
1) You go shoot yourself in feet trying to hook into every single input event to see if keyboard is necesarry.
2) You get an icon in taskbar to open a virtual keyboard, which can really be done by most of the virtual KB packages.
What you are asking here is very specific feature, one that use could only be seen on very high-end tablets that can do Linux or a laptop with touch screen (in which scenario why not just use keyboard).
So my advice is: grab one of dozen existing packages, write a script, be done with it.

**Comment by ikeydoherty** [comment]
So Caribou already solves this issue. It needs to be enabled from accessibility settings

**Comment by justinkterry** [comment]
@ikeydoherty Hey, this is broken in the current release. On a perfectly working touch screen (Windows and Ubuntu), touching the screen (outside of a text box) throws it up, and having it on makes it semi-randomly turn on or off whether or not you're touching the screen. This makes simple things like scrolling or clicking icons with the touch screen on a laptop nearly unusable.

**Comment by benyanke** [comment]
I am also finding Caribou broken on 18.04. It blocks a spot on the screen, but instead of showing the keyboard, the spot where the keyboard is trying to load just freezes, meanwhile the rest of the screen continues to move according to whatever is running.
