### ISSUE TITLE
Firefox Volume per sound output resets to minimum

### ISSUE THREAD

**Issue by Gaming4LifeDE** [solus-project/budgie-desktop#1820]
## Description
I noticed this spefically when listening to music on Deezer using Firefox but Firefox doesn't seem to be the only application affected.

When I change the volume of the audio stream via Raven, it resets on each new song (probably because the stream has a different ID or so), so the volume changes with it. Weird thing is, it resets to 1% or so but sometimes it shows the slider as muted, sometimes it shows it as 50% or so, sometimes as 100%.

## Budgie version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)

## Operating system
Solus 4

## Steps to reproduce the issue
1. Access Deezer via Firefox
2. Listen to a playlist
3. Change the volume in Raven

It might take a while for the issue to arise since it seems to save the volume for the audio stream ID, which only get recycled after a while.

## Expected result
The ideal scenario would be that the volume is being carried through from the last stream of the same source (i.e. Firefox) but it would also be ok to just reset it to 100%

**Comment by Coeur-Noir** [comment]
It still happens in Ubuntu Budgie 20.04 / Firefox 78.0.1
