### ISSUE TITLE
Budgie-desktop-settings don't open

### ISSUE THREAD

**Issue by Amathadius** [solus-project/budgie-desktop#1821]
## Description
When I want to start budgie-desktop-settings once, budgie panel blink. The second time, it takes longer before the panel blinks. The third time, budgie desktop crash et return to GDM.

## Budgie version
Last git version (10.5.r13.g48d1bc4b-1)

## Operating system
Archlinux

## Steps to reproduce the issue
Open Budgie-desktop-settings

## Actual result
Budgie-desktop-settings doesn't open and Budgie crash.

## Expected result
Budgie-desktop-settings opens. Budgie doesn't crash.

**Comment by Alexander88207** [comment]
See #1804

**Comment by nelth-fr** [comment]
Sorry @Alexander88207  but it doesen't help for me. I don't know if @Amathadius finally get this fixed but I have the same issue as explain :)

**Comment by Amathadius** [comment]
For now, I give up with budgie desktop. So, no, that doesn't fix issue. Sorry.
