### ISSUE TITLE
Taskbar: Weird behaviour with Android emulator

### ISSUE THREAD

**Issue by yaymalaga** [solus-project/budgie-desktop#1822]
I'm using Solus up-to-day. 

Budgie detects two instances of the Android Emulator, as it is formed by the emulator itself and a secondary control tab. Even though they are actually two windows, they act as a one, so budgie should detected this way too.

**Comment by JoshStrobl** [comment]
What is the window type of the secondary control tab?

**Comment by yaymalaga** [comment]
These are the "two windows":
![1](https://user-images.githubusercontent.com/2735961/96490715-77fa5200-1241-11eb-8430-b95b7f33c436.png)
![2](https://user-images.githubusercontent.com/2735961/96490717-7892e880-1241-11eb-93d9-463848542e52.png)

How can I provide you with more information?

**Comment by JoshStrobl** [comment]
Yes, I need you to run `xprop` on the widget control one please. If you don't have it installed, it's just the `xprop` package on Solus. Basically run the emulator, open a terminal, type `xprop` and then click the widget control thing.

**Comment by yaymalaga** [comment]
Alright! When clicking on the widget, this is the output:
`_NET_WM_ICON_GEOMETRY(CARDINAL) = 310, 0, 39, 34
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_TRANSIENT_FOR(WINDOW): window id # 0x5c00005
_NET_WM_ICON_NAME(UTF8_STRING) = 
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):

XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Emulator"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x5c00007
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x5c00007
WM_CLIENT_MACHINE(STRING) = "yaymalaga"
_NET_WM_PID(CARDINAL) = 50206
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 96469001
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 637, 101
		user specified size: 61 by 512
		program specified minimum size: 61 by 512
		program specified maximum size: 61 by 512
		window gravity: Static`

Just in case, here you have the same for the proper emulator:
`_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5c00016
_NET_WM_ICON_GEOMETRY(CARDINAL) = 310, 0, 39, 34
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_ICON_NAME(UTF8_STRING) = 
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):

XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Android Emulator - Nexus_5X_API_30:5554"
_NET_WM_NAME(UTF8_STRING) = "Android Emulator - Nexus_5X_API_30:5554"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x5c00007
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x5c00007
WM_CLIENT_MACHINE(STRING) = "yaymalaga"
_NET_WM_PID(CARDINAL) = 50206
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 96468998
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 178, 101
		user specified size: 484 by 863
		program specified minimum size: 200 by 200
		window gravity: Static`

**Comment by JoshStrobl** [comment]
@yaymalaga Mind letting me know what android emulator you're using specifically (a link would be handy) so I can validate a local fix?

**Comment by JoshStrobl** [comment]
GitHub closed issue due to keyword in referenced commit. Re-opened for pending validation.

**Comment by yaymalaga** [comment]
I'm using the official Android emulator: `https://developer.android.com/studio/run/emulator#install`

**Comment by JoshStrobl** [comment]
Thanks

**Comment by JoshStrobl** [comment]
Validated that my recent commit of 210608988ec9b2edb8a3a433a065240382a95eb5 resolves the issue. You'll get this on Friday if you're on the stable repo, sooner if you're on unstable (probably tomorrow).

![android-emulator-confirmed-fix](https://user-images.githubusercontent.com/156574/96600394-8e63e480-12f9-11eb-9b2c-fa5046b7ae45.jpg)

**Comment by yaymalaga** [comment]
Thanks!!
