### ISSUE TITLE
Disable merging application windows into single icon

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [solus-project/budgie-desktop#1825]
Hi, i'm trying to disable multiple instances of the same application to be stacked in a single icon but i could manage to find a way to do it.

I'd like to get one icon for each instance of my terminal for example.

![2019-05-19_11-55](https://user-images.githubusercontent.com/9869312/57984812-74034880-7a2d-11e9-96e9-84a8d6875f1a.png)

**Comment by EbonJaeger** [comment]
Open Budgie Settings, click the Panel tab on the left, select Icon Task List, and un-toggle Window Grouping in the settings on the right.

**Comment by Cedric-Lefebvre** [comment]
Thanks! exactly what i was looking for :)
