### ISSUE TITLE
xkb options settings

### ISSUE THREAD

**Issue by bgodard** [solus-project/budgie-desktop#1829]
A way to setup xkb options should be provided.

### Use-cases
There are many use cases for needing to set xkb options:

In my particular case, I use with my laptop an external keyboard with german layout but I want the numpad delete key to produce a dot instead of a comma (which is the decimal separator in german). 
The xkb option kpdl:dotoss produces the desired behavior. 
Different solutions are proposed here:
https://askubuntu.com/questions/209636/how-to-change-decimal-comma-to-decimal-period-in-numpad
The most interesting ones are relying on gsettings or dconf, but budgie does not seem to use those configuration values. Of course one could also try to use xorg.conf (I have not needed such a file in more than 10 years now) but would this still work with the budgie keyboard switching applet?

### Proposal
The easiest would probably be for budgie to simply read the options in dconf org.gnome.desktop.input-sources and enable them.
Additionally for commonly used options, it would be good to have a toggle in the input-sources configuration panel similar to what gnome-tweak-tool provides: https://mikewilliamson.files.wordpress.com/2014/03/tweak_tool.png

### References
Similar problem reported here:
https://github.com/solus-project/budgie-desktop/issues/1391

**Comment by bgodard** [comment]
So apparently I was mistaken the options in dconf are applied but only for the first layout.
This is a long standing issue in xkb:
https://gitlab.freedesktop.org/xorg/xserver/issues/653

There is also apparently no way to specify multiple sets of options so a fix would probably mean to have to apply the options to all keyboards. 
This is not reassuring considering xkb is apparently the only keyboard input source for wayland too.

I managed to solve it by switching the layout order (I don't need an option for the other layout)
Wouldn't it be better that xkb manages only one layout at a time: The user would specify layout and options for each keyboard configuration (in dconf or in the desktop input sources config tool) he desires and the desktop layout switch applet would perform the configuration switches by resetting all xkb settings so that the server is only aware of one layout and set of options at a time.

**Comment by JoshStrobl** [comment]
Closing since it's not an issue with Budgie specifically.
