### ISSUE TITLE
Shutdown from Raven power strip

### ISSUE THREAD

**Issue by SimoB** [solus-project/budgie-desktop#1831]
### Current Budgie version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)

### Proposal
From the "Power Strip" applet in Raven there is no way to shutdown, only lock or logout are possible, a fourth "shutdown" option would be welcome.

I know that the"User Indicator" applet has all the functions and probably the Power Strip is a leftover from previous versions but alternatives are great!

**Comment by SimoB** [comment]
There is a related issue from 2016 that is not solved yet
My proposal is about adding a fourth shutdown option rather than relying on gnome-session.
https://github.com/solus-project/budgie-desktop/issues/609

**Comment by JoshStrobl** [comment]
Power Strip is disabled by default in Budgie 10.5 as I intent to remove it entirely in Budgie 11, so I don't want new users to get used to it being there. As such, I will not be adding new functionality to the "power strip".
