### ISSUE TITLE
Put similar task list icons next to each others without grouping

### ISSUE THREAD

**Issue by triorr** [solus-project/budgie-desktop#1832]
Hello
I like my tasklist icons ungrouped for easy access but they get a bit messy. 
![Screenshot from 2019-06-02 17-46-15](https://user-images.githubusercontent.com/7348074/58765160-3212f000-855f-11e9-8eb2-8f5b473b3eee.png)

It would be nice if the similar icons sit next to each other.

Thanks

**Comment by triorr** [comment]
Hello
I like my tasklist icons ungrouped for easy access but they get a bit messy. 
![Screenshot from 2019-06-02 17-46-15](https://user-images.githubusercontent.com/7348074/58765160-3212f000-855f-11e9-8eb2-8f5b473b3eee.png)

It would be nice if the similar icons sit next to each other.

Thanks

**Comment by JoshStrobl** [comment]
This sort of "mess" is exactly what grouping resolves. Anything beyond that is IMO feature bloat.
