### ISSUE TITLE
Grub-Customizer Does Not Open

### ISSUE THREAD

**Issue by freddyyeddy** [solus-project/budgie-desktop#1834]
## Description
When grub-customizer is installed through the software center (or command line) it will not launch do to a missing dependency

## Budgie version
I am running the GNOME desktop

## Operating system
Solus 4.0 Fortitude
with Gnome 3.32.1

## Steps to reproduce the issue

Install the grub-customizer and try to run

## Actual result

 *** initializing (w/o specified bootloader type)…
   * reading partition info…
   * Loading Framebuffer resolutions (background process)
   * Finding out if this is a live CD
sh: hwinfo: command not found
 *** initializing (w/ specified bootloader type)…
   * Checking if the config directory is clean
 *** loading configuration
 *** loading - preserveConfig: no
   * unsetting saved config
 *** loading settings
 *** loading grub list
   * loading scripts…
   * loading proxies…
Segmentation fault

## Expected result

It to launch and allow easy configuration of the grub interface.

## Additional information

This is due to the missing hwinfo package. It is not in the software center and i cannot get it to compile manually.

**Comment by EbonJaeger** [comment]
Not a Budgie issue, from the sounds. I believe you'll want to report this at https://dev.getsol.us.
