### ISSUE TITLE
Error while running autoconfigure.sh in Fedora 21

### ISSUE THREAD

**Issue by niyasc** [solus-project/budgie-desktop#184]
I'm trying to compile budige-desktop in Fedora 21(with all updates).

      While running `autoconfigure.sh`, I'm getting following error message.
      budgie-plugin/Makefile.am: installing './depcomp'
      gvc/Makefile.am:49: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL  
      imports/natray/Makefile.am:18: warning: variable 'libnatray_la_la_LIBADD' is defined but no program or
      imports/natray/Makefile.am:18: library has 'libnatray_la_la' as canonical name (possible typo)

How can I solve this issue?
Please let me know, in case any additional information is required.

**Comment by ikeydoherty** [comment]
Per my comment on the other thread, please install gobject-introspection - whichever name it may be on your distro.

**Comment by niyasc** [comment]
`gobject-introspection` was already installed.
Installing `gobject-introspection-devel` resolved the problem
