### ISSUE TITLE
Raven Sidebar Appears Off to the Right/On the Wrong Side of the Monitor on RTL Configurations

### ISSUE THREAD

**Issue by moriel5** [solus-project/budgie-desktop#1841]
When using Budgie in an RTL configuration, such as hebrew, the Raven sidebar appears on the right of the monitor instead of the left.

For comparison, Windows 10 has it's sidebar appear on the left with RTL configurations.

Alternatively, if that was a design choice, it is not appearing on the edge, but rather slightly to the right, and it's width is much smaller than in english.

Budgie 10.5, On fully updated Solus (Stable)
![bug](https://user-images.githubusercontent.com/20175297/60040504-d224ea80-96c1-11e9-9f32-b0692dce490c.png)

**Comment by JoshStrobl** [comment]
Resolved since Budgie 10.5.2, position is configurable.
