### ISSUE TITLE
Icon task list

### ISSUE THREAD

**Issue by makitso** [solus-project/budgie-desktop#1844]
Latest version of Solus, updated.
There are situations where Libreoffice writer will not show in the top panel.  I can reproduce error:
1.  Open Libreoffice writer
2.  Close Libreoffice writer
3.  Open Terminal
4.  Close Terminal
5.  Open Libreoffice writer

![image](https://user-images.githubusercontent.com/5147603/60385246-186ca780-9a3c-11e9-9081-59079834758c.png)

**Comment by JoshStrobl** [comment]
And what happens if you enable window grouping?

**Comment by makitso** [comment]
With windows grouping turned on I an not reproduce the problem.  
This is a weird problem in that it appears to only happen with Libreoffice writer not any other Libreoffice products.

**Comment by makitso** [comment]
BTW, this problem did not exist with the budgie desktop version 10.4

**Comment by makitso** [comment]
On the current Solus update, if I remove all workspaces except 1 and then set the Restrict to workspace flag in Icon Task List the problem goes away.

**Comment by JoshStrobl** [comment]
> 
> 
> BTW, this problem did not exist with the budgie desktop version 10.4

Yes, it did exist. You just weren't affected by it. The issue existed before I rewrote the IconTasklist, implemented the new popovers, implemented the new application tracking, etc. See #1405, the issue was raised in 10.4

**Comment by makitso** [comment]
Any fix available?

**Comment by makitso** [comment]
I believe that setting the logo=0 in /etc/libreoffice/sofficerc turns off the spash screen.

https://www.howtogeek.com/287367/how-to-disable-libreoffices-startup-splash-screen-on-windows-and-linux/
