### ISSUE TITLE
global-menu-applet shows title for the run dialog

### ISSUE THREAD

**Issue by sntdevco** [solus-project/budgie-desktop#1845]
### Description

The budgie global-menu-applet shows a title for the run menu (usually CTRL+F2), which is not supposed to happen. Instead we should be showing something like "Search" for the title. This makes more sense than setting the title as budgie-run-dialog

### Budgie version
**budgie-desktop:** 10.5

### Operating system
Ubuntu 18.04.2 LTS

### Steps to reproduce the issue
Use the CTRL+F2 combo while using the global menu applet, and you'll see the title set as budgie-run-dialog

### Actual result
The `budgie-menu-applet`'s title is set to "budgie-run-dialog"

### Expected result
Something like "search" would be more subtle and formal

### Additional information
I am using the backports ppa, for testing the global-menu-applet

**Comment by sntdevco** [comment]
This may be related: https://github.com/solus-project/budgie-desktop/blob/b85ed82c6ed6a8d76d15377aac0a0c3959cb2f8e/src/rundialog/RunDialog.vala#L116

**Comment by JoshStrobl** [comment]
We don't develop this applet. It's not part of Budgie Core.
