### ISSUE TITLE
Black screen after waking from suspend/hibernate

### ISSUE THREAD

**Issue by luukatyuo** [solus-project/budgie-desktop#1848]
## Description

When I wake my laptop from suspend/hibernate/whatever it wakes, flashes the screen for 1 second and the screen turns black. When i hit any key or move my cursor it flashes on and i can enter the password. This is kinda annoying, coz if u miss the first flash, u wont know if it already woke up.

## Budgie version

budgie-desktop 10.5 (git-38b69f05619f0b1a681276dc258929f2fcb7a750)

## Operating system

Manjaro
Kernel: 5.1.15-1-MANJARO 
DISTRIB_RELEASE=18.0.4, all up to date

Any workaround? Any ideas? Hope for help/fix :-)

**Comment by JoshStrobl** [comment]
Not really an issue with Budgie as so much an issue with whatever screensaver / lock screen (such as gnome-screensaver).

**Comment by luukatyuo** [comment]
*clap clap*, nice reaction coz budgie must not deal with the gnome-shiat it's based on - workaround?
