### ISSUE TITLE
panel shadow blocking mouse hover/clicks

### ISSUE THREAD

**Issue by splace** [solus-project/budgie-desktop#1851]
Budgie-desktop 10.5 (git-8450ae384660c87bced67ded58c783be58a65a29)
Solus 4

![Peek 2019-07-10 16-16](https://user-images.githubusercontent.com/1234848/61593096-25ac2a80-abd3-11e9-9eba-7a83f1a2ec6b.gif)

**Comment by JoshStrobl** [comment]
That's because it's actually part of the panel and is reserved space. It's working as expected.

**Comment by splace** [comment]
>> It's working as expected.

never a users expectation.
