### ISSUE TITLE
Disable Transparency

### ISSUE THREAD

**Issue by hersh-verthun** [solus-project/budgie-desktop#1852]
## Description
The bottom panel exhibits transparency despite turning it off in **Budgie Desktop Settings**.

## Budgie version
10.5

## Operating system
Solus 4

**Comment by JoshStrobl** [comment]
Unable to reproduce. I have it set to none and there is no transparency. What theme are you using?

**Comment by hersh-verthun** [comment]
> Unable to reproduce. I have it set to none and there is no transparency. What theme are you using?

I am using the default theme.

**Comment by JoshStrobl** [comment]
1. No screenshot was provided
2. If you are referring to https://github.com/horst3180/vertex-theme, it hasn't seen an update for several years and doesn't support any remotely new version of Budgie.

I would suggest trying a different, known supported theme such as Plata.

**Comment by hersh-verthun** [comment]
> If you are referring to https://github.com/horst3180/vertex-theme, it hasn't seen an update for several years and doesn't support any remotely new version of Budgie.
> 
> I would suggest trying a different, known supported theme such as Plata.

I just updated the screenshot.

**Comment by MatthewScholefield** [comment]
A transparent panel means that Budgie won't draw *anything* behind icons. It doesn't have control over whether the theme chooses to make their solid panel bars a little bit transparent for artistic effect.
