### ISSUE TITLE
A Chinese localized translation for Budgie。

### ISSUE THREAD

**Issue by yjwork-cn** [solus-project/budgie-desktop#1855]
Correct some mistakes and complete translation.Add previous contributors.
I do not have permission to submit.
Chinese (Simplified)
https://dev.getsol.us/file/download/meqcjgrziuckgzxp5zwe/PHID-FILE-ngdhqmsx54oyok7hug56/budgie-desktop-translations-zh_Hans.po

**Comment by JoshStrobl** [comment]
For proposing changes to translations, use our dedicated Weblate that we have set up for translations: https://translate.getsol.us

**Comment by yjwork-cn** [comment]
https://translate.getsol.us
My ID:yjwork
I do not have permission to submit.
So I hope your help.

**Comment by JoshStrobl** [comment]
> https://translate.getsol.us
> My ID:yjwork
> I do not have permission to submit.
> So I hope your help.

Everybody has permission to create suggestions, not directly submit translation changes. For that, one is required to be on the respective language-specific translation team.

If we determine that such suggestions by a user are repeatedly of a certain quality / accuracy, we will consider adding them to respective translation team (if one does not exist, one is created) or consult the lead of that specific team.

**Comment by yjwork-cn** [comment]
There are too many modified translation.

 Well,I give up.

Two obvious mistakes：
"Are you sure you want to end your session?”"确实要结束回话吗？”
Right："确实要结束会话吗？"

"Dock mode” "对接方式"
Right："Dock 模式"
