### ISSUE TITLE
Animated workspace switching

### ISSUE THREAD

**Issue by Unia** [solus-project/budgie-desktop#186]
Hey Ikey,

On G+ the other day (https://plus.google.com/+Solus-Project/posts/6SsQmoKLN4v) I mentioned I was working on animated workspace switching that would be finished this weekend. I just pushed the code here: https://github.com/Unia/arek-wm/commit/40ae98c4bcc12b8f457c0b091d6f5903aacd4fcf

It is the same effect that GNOME Shell uses and it doesn't use any deprecated Clutter functions as opposed to the default Mutter plugin.

If wanted, I can easily implement this in Budgie wm as well but I thought I'd check with you first before doing so. I can have it done before the end of the weekend.

**Comment by ikeydoherty** [comment]
I'd be happy to see it join our repo, thank you :) Considering our similarity in plugin approach (i.e. organised, not like default! :)) it would be simpler I believe :)

I'm eyeing up your tiling stuff btw... ^^

**Comment by Unia** [comment]
Alright, I'll get to it then :) Feel free to take anything you want by the way!
