### ISSUE TITLE
"Restore keyboard shortcuts" locks up desktop on black screen

### ISSUE THREAD

**Issue by x6herbius** [solus-project/budgie-desktop#1860]
## Description
When invoking the "Restore keyboard shortcuts" shortcut using Super + Escape, the following occurs:

* First invocation: Screen goes black and then fades back up again.
* Second invocation: Screen goes permanently black and system stops responding. The only way to restore functionality is to power cycle the system.

## Budgie version
10.5

## Operating system
Solus 4.0

## Steps to reproduce the issue
* Invoke shortcut using Super + Escape.

## Actual result
Screen goes black permanently on second invocation.

## Expected result
Not sure, as I was playing around with this shortcut to see what it did. Pretty sure "lock up the desktop" was not the intended outcome.

## Additional information
None

**Comment by MatthewScholefield** [comment]
This doesn't seem to do anything for me. Can you confirm it's still an issue?

**Comment by x6herbius** [comment]
I had to uninstall Solus because the entire distro kept freezing my machine, so I don't have a way to test it any more. It could well have been something specific to my system, so feel free to close if it's not reproducible.

**Comment by MatthewScholefield** [comment]
Just to throw it out there, I get a black screen like this describes when changing desktops after closing guake. Probably not useful, but could help debug if a similar problem ever comes up.
