### ISSUE TITLE
Unable to type in password box after locking

### ISSUE THREAD

**Issue by joseph-foote** [solus-project/budgie-desktop#1861]
## Description
I have installed the Budgie desktop package on Debian 10 Buster with a fresh install of the OS. All software packages are up to date and I have attempted to try both ```lightdm``` and ```gdm3``` with no luck regarding fixing the issue.

The issue seems to occur fairly randomly but I'd say there is a roughly 1 in 3-5 chance. From what I can tell, the lock screen input does not take focus upon locking and all ability to switch focus is disabled when locked.

I can use the buttons to unlock or switch user, just not actually type in my password. I had a look through the various logs in ```/var/log/``` and by running ```gnome-logs``` but couldn't find anything useful.

It is worth noting once I have hit ```Super+L``` or ```Ctrl+Alt+L```, the lock screen can take anywhere from 1 to 10 seconds before it shows up. I wanted to just use the regular gnome lock screen or ```slick-greeter``` but I couldn't find any useful documentation.

## Budgie version
```
# sudo apt list --installed | grep budgie 
budgie-core/stable,now 10.5-1 amd64 [installed,automatic]
budgie-desktop/stable,now 10.5-1 all [installed]
budgie-dropby-applet/stable,now 0.7.1-3 all [installed]
budgie-extras-common/stable,now 0.7.1-3 amd64 [installed,automatic]
budgie-previews-applet/stable,now 0.7.1-3 all [installed]
budgie-quicknote-applet/stable,now 0.7.1-3 amd64 [installed]
budgie-trash-applet/stable,now 0.7.1-3 amd64 [installed]
gir1.2-budgie-1.0/stable,now 10.5-1 amd64 [installed,automatic]
libbudgie-plugin0/stable,now 10.5-1 amd64 [installed,automatic]
libbudgie-private0/stable,now 10.5-1 amd64 [installed,automatic]
libbudgietheme0/stable,now 10.5-1 amd64 [installed,automatic]
```

## Operating system
```
# uname -a && lsb_release -a
Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

## Steps to reproduce the issue
Either lock and unlock the computer multiple times or intentionally randomly click and attempt to switch windows while locking.

**Comment by JoshStrobl** [comment]
Budgie doesn't provide a lockscreen, this is typically provided through the likes of gnome-screensaver.
