### ISSUE TITLE
Missing audio devices in Raven

### ISSUE THREAD

**Issue by ktw** [solus-project/budgie-desktop#1863]
## Description
Optical S/PDIF audio devices not shown in Raven.

## Budgie version
budgie-desktop 10.5 (git-8450ae384660c87bced67ded58c783be58a65a29)

## Operating system
Solus 4

## Steps to reproduce the issue
Connect a S/PDIF audio device.

## Actual result
All audio devices but optical S/PDIF is shown.
![billede](https://user-images.githubusercontent.com/105196/62831770-47259280-bc24-11e9-953a-4a8b1e322e35.png)

## Expected result
Same list as shown in both pavucontrol and Settings / Audio / Output. 

## Additional information
Motherboard:
[ASUS PRIME X370-PRO](https://www.asus.com/Motherboards/PRIME-X370-PRO/specifications/)
Connected speakers:
[Edifier S350DB](https://www.edifier.com/int/en/speakers/s350db)

inxi -A output:
```
Audio:
  Device-1: NVIDIA GP102 HDMI Audio driver: snd_hda_intel 
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel 
  Device-3: Kingston HyperX 7.1 Audio type: USB 
  driver: hid-generic,snd-usb-audio,usbhid 
  Sound Server: ALSA v: k5.2.7-123.current 
```

**Comment by JoshStrobl** [comment]
Digital Output devices are intentionally hidden because they've been proven to be buggy / problematic with GVC (GNOME Volume Control).

https://github.com/solus-project/budgie-desktop/blob/fa28f74728fb81e9de9b0a548799f7e22ff97c70/src/raven/sound.vala#L230

From e1922ed627afda92fa2caed9fe73168986e9bb6d

**Comment by ktw** [comment]
Too bad.
Audio is actually working very well here.
A Raven settings option to enable it at own risk would be nice.

**Comment by jamiefraser77** [comment]
I have a headset, the analogue output entry for the headset only goes through one ear, so having the choice of setting a digital device output would be good!
