### ISSUE TITLE
Detecting Second Monitor when no other monitor is plugged in.

### ISSUE THREAD

**Issue by Aegor1998** [solus-project/budgie-desktop#1865]
## Detecting Second Monitor when no other monitor is plugged in.
Solus detected a secondary monitor when there is none. My taskbar got switched to the secondary monitor.

## Additional information
I made a temp fix by going into display settings and turning single display mode on.

**Comment by bjo81** [comment]
Your second monitor is not developed by Solus, so this is not a Budgie issue.
