### ISSUE TITLE
Number of desktops aren't saved across logins

### ISSUE THREAD

**Issue by MatthewScholefield** [solus-project/budgie-desktop#1868]
## Description
When logging out of Budgie Desktop and back in, the number of workspaces is always reset to 1.

## Budgie version
Budgie 10.5 from Solus Repo (git-8450ae384660c87bced67ded58c783be58a65a29)
Budgie HEAD from GitHub (git-70ff6fda82242393638b0e6e807b59e890dbdda8)

## Operating system
Solus latest (as of 8/30/19)

## Steps to reproduce the issue
 - Add a workspace switcher applet to the panel with the option `"Add" button visibility` set to `Always show`
 - Click the plus button on the workspace switcher applet to add a few desktops
 - Log out and log back in

## Actual result
Only 1 desktop exists when logging back in

## Expected result
All the desktops created in the previous session should still exist

## Additional information
This wouldn't be a problem if dynamic workspaces had been implemented like in #1316 or #879. This did not used to happen which is why I'm assuming it's a bug

**Comment by JoshStrobl** [comment]
> This did not used to happen which is why I'm assuming it's a bug

I'm not seeing any evidence that we ever properly hooked into the `org.gnome.desktop.wm.preferences.num-workspaces` key to trigger BudgieWM to create additional workspaces, so it's not related to the workspace applet *entirely*.

Dynamic workspaces **are** implemented, #879 should have been closed a long time ago. You dynamically create a workspace by dragging an icon. Dynamic workspaces don't really have anything to do with workspaces which are generated on session start either.

Either way, this is indeed a bug. Until Budgie 11 stops using gnome-desktop keys, we should ideally respect the num-workspaces key, so I'll look into adding that.
