### ISSUE TITLE
Unusual Memory Usage (Budgie) Solus 4

### ISSUE THREAD

**Issue by 4ndril** [solus-project/budgie-desktop#1869]
I noted the other day when I was transferring files to my new phone that my 32GB of memory was taking a hit. I was able to reproduce by opening 2 Budgie windows and copying 3 random compressed files https://imgur.com/PqD71ew

Has anyone else experienced this? Are there any fixes?

**Comment by MatthewScholefield** [comment]
I think this would be better suited for the [Solus forums](https://discuss.getsol.us/) or the [Solus bugtracker](https://dev.getsol.us/) (this is just for the desktop manager dealing with the UI).
