### ISSUE TITLE
Desktop / Wallpaper / Background Image Randomizer

### ISSUE THREAD

**Issue by cryptodan** [solus-project/budgie-desktop#1870]
### Current Budgie version

cryptodan@pegasus ~ $ budgie-desktop --version
budgie-desktop 10.5 (git-38b69f05619f0b1a681276dc258929f2fcb7a750)
Copyright © 2014-2019 Budgie Desktop Developers

### Use-cases

The ability to change at random time settings the wallpapers located in /usr/share/backgrounds

### Proposal

It can be done on other desktops like MATE or Cinnamon via settings or applet.

**Comment by JoshStrobl** [comment]
We're not implementing any new features like this in the Budgie 10 series, nor will we be using this issue tracker (or repo) for the development of Budgie 11. As such, I'm going to be closing this issue and it may be reassessed when development of Budgie 11 commences.

Until then, I suggest just installing the Variety app. It's in the Solus repository, if you're not using Solus then I imagine you can find it in a repo near you.
