### ISSUE TITLE
Editing Budgie Favorited Items and Application Menu

### ISSUE THREAD

**Issue by cryptodan** [solus-project/budgie-desktop#1871]
I am running Budgie on the following system:

System:
  Host: pegasus Kernel: 5.2.13-arch1-1-ARCH x86_64 bits: 64 compiler: gcc 
  v: 9.1.0 Desktop: Budgie 10.5 Distro: Arch Linux 
Machine:
  Type: Laptop System: PowerSpec product: 1710 v: 1.0 
  serial: <root required> 
  Mobo: Clevo model: 1710 v: 1.0 serial: <root required> 
  UEFI: American Megatrends v: 1.05.05 date: 06/23/2017 
Battery:
  ID-1: BAT0 charge: 67.4 Wh condition: 67.4/66.9 Wh (101%) 
  model: Notebook BAT status: Full 
CPU:
  Topology: Quad Core model: Intel Core i7-7700HQ bits: 64 type: MT MCP 
  arch: Kaby Lake rev: 9 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 44944 
  Speed: 800 MHz min/max: 800/3800 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:
  Device-1: NVIDIA GP104BM [GeForce GTX 1070 Mobile] vendor: CLEVO/KAPOK 
  driver: nvidia v: 435.21 bus ID: 01:00.0 
  Display: x11 server: X.Org 1.20.5 driver: nvidia 
  unloaded: modesetting,vesa resolution: 1920x1080~75Hz 
  Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:
  Device-1: Intel CM238 HD Audio vendor: CLEVO/KAPOK driver: snd_hda_intel 
  v: kernel bus ID: 00:1f.3 
  Sound Server: ALSA v: k5.2.13-arch1-1-ARCH 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: CLEVO/KAPOK driver: r8169 v: kernel port: d000 bus ID: 3b:00.0 
  IF: enp59s0 state: down mac: 80:fa:5b:4a:6a:11 
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: d000 
  bus ID: 3d:00.0 
  IF: wlp61s0 state: up mac: cc:2f:71:28:8c:f0 
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:01 
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:08 
Drives:
  Local Storage: total: 2.05 TiB used: 829.80 GiB (39.6%) 
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 960 EVO 250GB 
  size: 232.89 GiB 
  ID-2: /dev/sda vendor: Samsung model: SSD 860 EVO 2TB size: 1.82 TiB 
Partition:
  ID-1: / size: 209.84 GiB used: 11.76 GiB (5.6%) fs: ext4 
  dev: /dev/nvme0n1p2 
  ID-2: /home size: 1.79 TiB used: 818.05 GiB (44.6%) fs: ext4 
  dev: /dev/sda1 
  ID-3: swap-1 size: 18.43 GiB used: 0 KiB (0.0%) fs: swap 
  dev: /dev/nvme0n1p3 
Sensors:
  System Temperatures: cpu: 47.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 259 Uptime: 13m Memory: 15.61 GiB used: 2.74 GiB (17.6%) 
  Init: systemd Compilers: gcc: 9.1.0 clang: 8.0.1 Shell: bash v: 5.0.9 
  inxi: 3.0.36

I would like to know how to edit the favorite items on the panel to reflect a new path for the short cut and how to add applications to the menu.  I do not see any menu editing functions like I do with XFCE, Cinnamon, or MATE.

I have two instances of Discord for Linux, and one is from the Arch User Repos, and the other is from discord.com.  I would like to use the one from discord.com, but that one doesn't have an install script which would like do all of the tasks listed.

**Comment by JoshStrobl** [comment]
> I would like to know how to edit the favorite items on the panel to reflect a new path for the short cut and how to add applications to the menu. I do not see any menu editing functions like I do with XFCE, Cinnamon, or MATE.

This isn't something we're planning on implementing in the Budgie 10 series, but rather menu editing may be something we bring in Budgie 11 (which will use a different bug tracker via the GetSolus org). For now, use a menu editor from your repository.
