### ISSUE TITLE
Cannot take screenshot using PrintScreen

### ISSUE THREAD

**Issue by rabinadk1** [solus-project/budgie-desktop#1872]
## Description

I cannot take screenshot by default using PrintScreen button of keyboard. It was removed some times ago but now it has creeped it

## Operating system

Solus updated to latest

**Comment by JoshStrobl** [comment]
Unable to reproduce. I would make sure that:

1. You have gnome-screenshot installed
2. You don't have any of the menus or popovers open when taking a screenshot.

**Comment by rabinadk1** [comment]
It was fixed in recent update, thank you :)!
