### ISSUE TITLE
Set a specific wallpaper for desktop not respect gsettings schemas?

### ISSUE THREAD

**Issue by Ste74** [solus-project/budgie-desktop#1873]
Hi there,
we have to build a new Manjaro ISO to test before release. The wallpapers of background into the desktop did not respect our override file. The key is reverted to the default gnome wallpaper.
Here you can see our [gsettings schemas override](https://gitlab.manjaro.org/profiles-and-settings/desktop-settings/blob/master/community/budgie/schemas/99_manjaro-settings.gschema.override#L12).
I don't understand what happened? If our wallpaper is not into an XML file is not recognized? 
This is a strange issue since the gsettings key have the correct syntax.

Cheers
Stefano

**Comment by JoshStrobl** [comment]
Hi there. Using `:Budgie` session-specific keys isn't something that we support or intend on supporting (given in Budgie 11 we'll be moving away from GNOME stack for the vast majority of schemas, including those provided by libgnome-desktop, thus making the support in Budgie 10.x pointless). In Solus' branding for example, we use `org.gnome.desktop.background`. I would suggest using that instead.
