### ISSUE TITLE
Manjaro Budgie: pamac-tray not show in the panel

### ISSUE THREAD

**Issue by Ste74** [solus-project/budgie-desktop#1879]
## Description
With new version Gnome v3.34 seem Budgie session is recognized like GNOME session; pamac-tray.desktop file use an array to not show in KDE and GNOME sessions. Before all work as expected but not now. The tray icon is not displayed only if we remove the GNOME session from the list but we can't because pamac in GNOME session use a dedicated extension.
You can see my report in our [gitlab instance](https://gitlab.manjaro.org/applications/pamac/issues/658#note_13372)
Cheers
Stefano Capitani 

## Budgie version
10.5.1

## Operating system
Manjaro Unstable Branch

**Comment by fossfreedom** [comment]
I dont know what your "pamac-tray.desktop" is supposed to run but why not just create a budgie equivalent i.e. a "budgie-pacmac.desktop"

```
[Desktop Entry]
Name=Update Notifier
Icon=update-notifier
Exec=sh -c "GDK_BACKEND=x11 pamac-tray"
Terminal=false
Type=Application
StartupNotify=false
OnlyShowIn=Budgie;
```

**Comment by Ste74** [comment]
Sorry for delay, yeah at the end we use this solution.
Thank you 
Stefano
