### ISSUE TITLE
Panel does not work well with more then one screen

### ISSUE THREAD

**Issue by ZetaHunter** [solus-project/budgie-desktop#188]
Once in a while when I boot up my system and hook up my home 23'' widescreen to work on a project I get a weird bug when the panel will be the width of my 23'' but the panel shadow will start on laptop screen.
Here is how it looks: http://i.imgur.com/9eDiX6I.png
Notice how the menu and any other popups are dislocated (the menu button is on the far right bottom corner yet menu is completely elsewhere.

This isn't as annoying as freezeups but also shouldn't be hard to fix (I hope, I haven't seen the logic).

**Comment by ikeydoherty** [comment]
Can you try with the latest changes?

Also popover freeze have been addressed as of today. Shadow is getting fixed shortly (going to use a single widget and not two windows..)

**Comment by ikeydoherty** [comment]
Fixed in v10
