### ISSUE TITLE
Dark theme cannot be switched on or off in version 10.5.1

### ISSUE THREAD

**Issue by ArjenR** [solus-project/budgie-desktop#1881]
## Description
To work more easily with librecad I am used to switching off the dark theme in budgie-desktop. After the recent update to 10.5.1 the toggle does not work. Even not when toggeling /com/solus-project/budgie-panel/dark-theme using the dconf editor.

## Budgie version

budgie-desktop 10.5.1

## Operating system

Solus 4 updated to 5-10-2019

## Steps to reproduce the issue
Start "Budgie Desktop Settings"
Go to Style tab
Switch dark theme Off

## Actual result

Theme stays dark

## Expected result
Theme switches to the light version.

## Additional information
Using the dconf editor to toggle /com/solus-project/budgie-panel/dark-theme also has no effect.

**Comment by JoshStrobl** [comment]
And what is your GTK Theme?

**Comment by JoshStrobl** [comment]
I just tested it with Plata (not Plata-Noir) and toggling on and off the dark theme, it works as expected. Having it as Plata-Noir specifically didn't cause it to toggle, which is expected behavior (I want to add better handling around this but that's more a feature than a bug).

**Comment by ArjenR** [comment]
Ok thanks for testing and your reply. It happens to be a quite fresh install. No changes in visuals other then the background. I am not at that machine right now. But iirc it said Plata-Noir.

Will try with your suggestion later.

**Comment by JoshStrobl** [comment]
Yea in the future I'd like to have a system in place that'll swap between the themes when you toggle on / off dark mode so it'll be consistent and enforced properly across the board, but right now my work on desktop icons is taking priority :)

**Comment by ArjenR** [comment]
Ok so indeed, switching to Plata or Plata-luminous even, enabled the toggle to have effect. I see there is logic to it. Success on the desktop icons.

**Comment by JoshStrobl** [comment]
I'm going to mark this as resolved / invalid then, with the note that while I do agree this may not fully be the expected behavior by the user, it is in fact currently the intended behavior. The behavior of it **is** something I will improve within the Budgie 10.5 series however.
