### ISSUE TITLE
Nextcloud Client Not Displayed Properly under Plata-Noir

### ISSUE THREAD

**Issue by circlenaut** [solus-project/budgie-desktop#1884]
[Check it out](https://imgur.com/a/xhOx4vM). Nextcloud client does not render properly under the plata-noir theme. The light version works fine.

Running Budgie 10.5.1 under Solus 4 Stable.

**Comment by JoshStrobl** [comment]
This has nothing to do with Budgie.

**Comment by circlenaut** [comment]
Is this an issue with nextcloud not rendering gtk themes correctly? Should I post this under nextcloud desktop client?

**Comment by JoshStrobl** [comment]
> Is this an issue with nextcloud not rendering gtk themes correctly?

Sounds more like you just need to restart the client. Some Qt applications aren't going to fully and properly adjust until you've done that. Nextcloud renders fine for me under Plata-Noir + Dark Theme toggle.
