### ISSUE TITLE
Widget to Quickly Change Between Themes

### ISSUE THREAD

**Issue by circlenaut** [solus-project/budgie-desktop#1885]
It would be useful to have a widget that allows us to quickly change between themes or to select between a dark and light theme. The light and dark themes could be configured through the widget.

A stretch would be to tie this to the night light widget. In the widget's drop-down; switching "Night Light" on and off could be optionally tied to switching between dark and light mode.

On another note, turn off night mode should change the icon from a crescent moon to a sun :)

**Comment by JoshStrobl** [comment]
There are no plans on adding additional features of this nature to Budgie 10.5 series and this would be more suitable for a third-party developer to create.
