### ISSUE TITLE
Customize place for the notifications

### ISSUE THREAD

**Issue by Akronix** [solus-project/budgie-desktop#1886]
### Current Budgie version

budgie-desktop 10.4

### Use-cases

The current location of the notifications overlaps the tabs of my browser so I'd like to have the possibility to move it.

### Proposal

Add an option inside the notifications settings to select the location for notifications.

### References

I like the way Telegram has implemented this:
![image](https://user-images.githubusercontent.com/2631430/66747329-89698b00-ee84-11e9-8edf-5885523b88ba.png)

**Comment by EbonJaeger** [comment]
You can select what corner notifications appear in in Budgie Desktop Settings.

**Comment by JoshStrobl** [comment]
Also, you're on a seriously old version of Budgie. Latest is Budgie 10.5.1.
