### ISSUE TITLE
Add a close button in notifications

### ISSUE THREAD

**Issue by Akronix** [solus-project/budgie-desktop#1887]
### Current Budgie version

budgie-desktop 10.4

### Use-cases

Many times I get notifications I want to dismiss and continue doing my work, I'm missing a "close" or "dismiss" button to hide them.

### Proposal

Add a close button in every notification popup so it can be hidden.

### References

I like the way Telegram has implemented this.

**Comment by EbonJaeger** [comment]
Notifications *do* have a close button in their upper right corner.

**Comment by JoshStrobl** [comment]
Yep, they do. Invalid.

**Comment by Akronix** [comment]
I don't get that button in notifications coming from [Rambox](https://rambox.pro/#home), which is based on electron. Maybe it's Rambox or Electron's fault and not budgie.
The version of Budgie I'm using is the one which ships with Ubuntu 18.04 :man_shrugging:
