### ISSUE TITLE
Printer Samsung M2070 not working in Solus Linux

### ISSUE THREAD

**Issue by affiss** [solus-project/budgie-desktop#1894]
Hello,

I'm trying to print on Solus 4.0 Fortitude (Budgie Desktop) with a Samsung M2070 Printer. However, I'm getting no response from the printer. The printer itself is shown in the printer settings, i.e. it's being recognized by the system. 

I've attempted a troubleshoot. Please see the error log in the attachment.
[printer_troubleshoot.txt](https://github.com/solus-project/budgie-desktop/files/3798372/printer_troubleshoot.txt)

Can it be fixed?

Best Regards

**Comment by EbonJaeger** [comment]
This isn't a Budgie issue. You should make a post on the Solus forums (https://discuss.getsol.us) and/or open a ticket on the Solus issue tracker (https://dev.getsol.us).

**Comment by affiss** [comment]
Okay, Thanks :)
