### ISSUE TITLE
clr-boot-manager update error

### ISSUE THREAD

**Issue by mablue** [solus-project/budgie-desktop#1896]
I have error when I run system upgrade 
all of things work good just one fail in clr-boot-manager happend:

<pre>
Installing 386 / 386
xorg-driver-video-radeon-19.1.0-42-1-x86_64.eopkg [cached]
Installing xorg-driver-video-radeon, version 19.1.0, release 42
Upgrading to new upstream version
Extracting the files of xorg-driver-video-radeon
Upgraded xorg-driver-video-radeon
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✗] Updating clr-boot-manager                                           failed

A copy of the command output follows:

[FATAL] cbm (../src/bootman/kernel.c:L657): Failed to install initrd /boot/EFI/com.solus-project/initrd-com.solus-project.current.5.3.7-132: **No space left on device**
[FATAL] cbm (../src/bootman/update.c:L380): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.5.3.7-132

 [✓] Running depmod on kernel 5.3.7-132.current                         success
 [✓] Updating graphical driver configuration                            success
 [✓] Updating system users                                              success
 [✓] Updating systemd tmpfiles                                          success
 [✓] Reloading systemd configuration                                    success
 [✓] Compiling AppArmor profiles                                        success
 [✓] Reloading AppArmor profiles                                        success
 [✓] Compiling glib-schemas                                             success
 [✓] Rebuilding font cache                                              success
 [✓] Updating mimetype database                                         success
 [✓] Updating icon theme cache: hicolor                                 success
 [✓] Updating icon theme cache: Adwaita                                 success
 [✓] Updating icon theme cache: default                                 success
 [✓] Updating icon theme cache: Papirus                                 success
 [✓] Updating icon theme cache: Papirus-Dark                            success
 [✓] Updating icon theme cache: Papirus-Adapta                          success
 [✓] Updating icon theme cache: Papirus-Adapta-Nokto                    success
 [✓] Updating icon theme cache: HighContrast                            success
 [✓] Updating icon theme cache: Papirus-Light                           success
 [✓] Updating icon theme cache: solus-sc                                success
 [✓] Updating icon theme cache: breeze_cursors                          success
 [✓] Updating desktop database                                          success
 [✓] Rebuilding dconf database                                          success
 [✓] Updating GTK2 input module cache                                   success
 [✓] Updating GTK3 input module cache                                   success
 [✓] Updating manpages database                                         success
 [✓] Updating SSL certificates                                          success
 [✓] Reloading udev rules                                               success
 [✓] Applying udev rules                                                success
</pre>

I searched about that but nothing founded.

this is my system detiles:

<pre><font color="#5FD7FF">mab</font><font color="#8A8A8A">@</font><font color="#FF5FD7">mab </font><font color="#8A8A8A">~ </font><font color="#5FD7FF">$ </font>uname -a
Linux mab 4.20.16-112.current #1 SMP PREEMPT Fri Mar 15 02:54:46 UTC 2019 x86_64 GNU/Linux
<font color="#5FD7FF">mab</font><font color="#8A8A8A">@</font><font color="#FF5FD7">mab </font><font color="#8A8A8A">~ </font><font color="#5FD7FF">$ </font>lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	4.0
Codename:	fortitude</pre>

how can I fix that?I used to install solus alongside win 10 and win 10 maked a 100MB EFI partition and now solus want me to resize it !! :S
Because of that I resized my windows efi partition but error still alive:

<pre><font color="#5FD7FF">mab</font><font color="#8A8A8A">@</font><font color="#FF5FD7">mab </font><font color="#8A8A8A">~ </font><font color="#5FD7FF">$ </font>sudo clr-boot-manager set-timeout 5 &amp;&amp; sudo clr-boot-manager updateNew timeout value is: 5
[FATAL] cbm (../src/bootman/kernel.c:L657): Failed to install initrd /boot/EFI/com.solus-project/initrd-com.solus-project.current.5.3.7-132: No space left on device
[FATAL] cbm (../src/bootman/update.c:L380): Failed to install default-current kernel: ///usr/lib/kernel/com.solus-project.current.5.3.7-132
</pre>

**Comment by JoshStrobl** [comment]
This has nothing to do with Budgie.

**Comment by mablue** [comment]
Oh sorry İ have a mistake
