### ISSUE TITLE
The login window on the login screen is very small on high-resolution (high-DPI) screens

### ISSUE THREAD

**Issue by marek-lach** [solus-project/budgie-desktop#1897]
## Description
On the Budgie Desktop log in screen, when using a high DPI screen, like the one on the Surface Pro, the input field for the password, as well as the icons in the top panel are unnaturally small. On typical full-HD monitors the password input window is simply usually much bigger.

After log in, everything scales-up properly though, once the display auto-scales from 100 to 200%.

## Budgie version
10.5.1

## Operating system
Solus 4, also Manjaro Budgie 18.1

**Comment by JoshStrobl** [comment]
Budgie doesn't provide this login screen. This is an issue with LightDM and/or Slick Greeter, depending on what you use.
