### ISSUE TITLE
Budgie Desktop Settings Font selection doesn't work as intended

### ISSUE THREAD

**Issue by tomocafe** [solus-project/budgie-desktop#1900]
## Description

Budgie Desktop Settings Font selection doesn't work as intended. Setting the font for _Window Titles_ has no effect. Everything seems to follow the _Interface_ font family, but it hardcodes different styles/weights for different UI elements. Selecting a style/weight is not honored here.

## Budgie version

10.5.1

## Operating system

Solus 4

## Steps to reproduce the issue

Open `budgie-desktop-settings`, go to the _Font_ tab, and play with the Fonts, including selecting different styles/weights (e.g. italic or bold).

## Actual result

Everything seems to follow the _Interface_ font family, but it hardcodes different styles/weights for different UI elements. Selecting a style/weight is not honored here.

## Expected result
Allow _Window Titles_ to use a different font than the _Interface_ font. Allow font style and weight to be overridden.
**OR**
Rewrite this settings dialog to be in alignment with the actual implementation if we are getting rid of this functionality.

**Comment by tomocafe** [comment]
Possibly relevant: https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/137
and: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/commit/8e1002af

**Comment by emmi-ari** [comment]
Doesn't that make `Window Titles` setting obsolete?
