### ISSUE TITLE
Steam Game Shortcut crashes system.

### ISSUE THREAD

**Issue by Xrey274** [solus-project/budgie-desktop#1901]
## Description
After installing a Steam game a shortcut(.desktop file) on the desktop. If you go into the properties of said file and try to set the icon, you will receive a prompt saying that something has gone wrong and that you must log out.

## Budgie version
10.5.1 | Gnome 3.34.1

## Operating system
Solus 4

## Steps to reproduce the issue
1. Install any game using Steam
2. Create a desktop shortcut for said game from Steam(Library->Game->Manage->Add Desktop Shortcut)
3.Right click on shortcut->Properties->Select Icon

## Actual result
System crashes with a prompt asking me to log out.

## Expected result
Nautilus to open.

**Comment by JoshStrobl** [comment]
Nothing to do with Budgie, the desktop icon view is provided by an old version of Nautilus on Solus, which isn't under development by GNOME anymore (and in a future release of Budgie, we'll have our own desktop icons view).
