### ISSUE TITLE
Numerous glitches when rebooting.

### ISSUE THREAD

**Issue by Xrey274** [solus-project/budgie-desktop#1902]
## Description
When rebooting(or shuting down and then booting again) numerous glitches occur.
1.Tray icons are glitched. Not only do they not retract along with the panel, but also they appear visually "stacked"
![Screenshot from 2019-11-17 17-21-13](https://user-images.githubusercontent.com/30723811/69010860-a1916600-096c-11ea-858b-23835c209c89.png)
![Screenshot from 2019-11-17 17-22-15](https://user-images.githubusercontent.com/30723811/69010863-a8b87400-096c-11ea-9df7-c8c5516b4189.png)
2. Booting takes far longer that usual. Usually stuck at bios logo for a whole minute.(when this issue is not present my machine boots in ~15sec). After reaching the login screen all peripherals turn off. It takes them another minute to start working. Peripherals affected - keyboard, mouse, headset.
3.Some applications set to autostart don't start with boot. To be more specific - CoreCtrl(utility used to control AMD GPUs) does not start sometimes. From what I can tell this behaviour is unpredicatble.

## Budgie version
10.5.1 | Gnome 3.34.1

## Operating system
Solus 4

## Steps to reproduce the issue
Reboot Solus or shut it down and boot it again. 

## Actual result
Upon rebooting the system has numerous problems described above ^.

## Expected result
Normal boot of the OS.

## Additional information
This is issue is not something that fixed by reinstalling the OS. This has happened before on previous installs of Solus Budgie.

**Comment by JoshStrobl** [comment]
1. Tray icons already known and reported via #1249
2. Nothing to do with Budgie.
3. Nothing to do with Budgie.
