### ISSUE TITLE
Trying to change icon of a desktop-shortcut crashes budgie

### ISSUE THREAD

**Issue by Tungdil-Bolofar** [solus-project/budgie-desktop#1910]
## Description

Recently I experienced that, when trying to change the icon of a shortcut on the desktop, budgie crashes completely. 

## Budgie version

budgie-desktop 10.5.1

## Operating system

Solus 4.0

## Steps to reproduce the issue

- right-click on a desktop icon and open the properties dialogue box
- click on the icon in the properties box

## Actual result

Budgie crashes completely.

## Expected result
Dialog for selecting an icon should open.

## Additional information
Output of `dmesg -H`

```
[Dez 8 19:14] rfkill: input handler enabled
[  +0,002681] budgie-daemon[6936]: segfault at 0 ip 00007efecbc34534 sp 00007ffe076daa40 error 6 in libwnck-3.so.0.3.0[7efecbc2b000>
[  +0,000007] Code: 43 40 00 00 00 00 48 8b 7b 60 e8 37 7a ff ff 49 8b 44 24 18 48 8b 15 e3 cc 02 00 48 63 08 48 8b 78 70 48 c7 40 >
[ +52,221996] rfkill: input handler disabled

```

**Comment by ExtremorGP** [comment]
Same problem in version 4.1. I used Virtual Box though.

**Comment by JoshStrobl** [comment]
Closing as Budgie Desktop as its own implementation of desktop icons now via https://github.com/getsolus/budgie-desktop-view
