### ISSUE TITLE
Media keys not working when in lock screen, budgie menu or right click menu

### ISSUE THREAD

**Issue by janispritzkau** [solus-project/budgie-desktop#1911]
## Description

Media keys, like volume up/down and screen brightness don't work when you are in the lock screen or when you have the budgie menu open.

## Budgie version

budgie-desktop 10.5.1 (git-e6433d87974e735296e72cf5b9d2a25466d5fe7a)

## Operating system

Arch Linux

## Actual result
Pressing the keys does not do anything.

## Expected result
Pressing the media keys should give visual feedback and work like normal.

## Additional information
It works normal in the gnome DE.

**Comment by JoshStrobl** [comment]
1. We don't develop the lock screen, that is gnome-screensaver.
2. Budgie Menu intentionally captures keyboard input, just close the menu.
