### ISSUE TITLE
Workspace Application Moving

### ISSUE THREAD

**Issue by JuliusS123** [solus-project/budgie-desktop#1915]
I am in budgie-desktop 10.4.
It is a great desktop, but I would like to propose a new, cool feature.
I am starting a project with your wonderful desktop
This feature would enable you to move between workspaces by pressing Ctrl + alt and a arrow key,
I suggest it because it is in a lot of linux operating systems (Ubuntu, Linux Mint, etc)
I would be happy if this feature would be included, and I am sure that many other poeple ould like it too. Thank you

**Comment by JoshStrobl** [comment]
> This feature would enable you to move between workspaces by pressing Ctrl + alt and a arrow key,

You can already move between workspaces. Check the keyboard shortcuts defined in whatever operating system you're using. Also I'd advise making sure you are on an operating system (e.g. Solus) which supports the latest release of Budgie. We do not support Budgie 10.4 and it is an extremely old release.
