### ISSUE TITLE
BudgieMenu Adjusting size and such. 

### ISSUE THREAD

**Issue by jarrard** [solus-project/budgie-desktop#1917]
Just wondering if its possible to adjust the size of the budgie menu, its a tad bit small at 4k. 

It would also be nice if options existed to adjust text and icon size separately to the rest of the desktop environment.

Maybe even ability to add favourite icons down the side of the menu?  okok I ask too much, perhaps just some info on howto resize this thing.  I suspect something might be doable in gtk css file?

**Comment by JoshStrobl** [comment]
The current model of Budgie Menu in Budgie 10 uses our standard BudgiePopover, which disables resize capability and changes the sizing based on the content's preferred height and width. A resizable Budgie Menu is something I'll likely do for Budgie 11, however it won't be developed in this repository or be referencing these issues, so closing this as a result.
