### ISSUE TITLE
Budgie consistently crashes under a certain sequence of actions

### ISSUE THREAD

**Issue by hyphenrf** [solus-project/budgie-desktop#1919]
I've tried my best to look for duplicats but I believe this is the first time it's being reported.
budgie-desktop 10.5.1
Solus 4.0 latest sync

## Description
The bug in question is a crash screen that reads:
"A problem has occurred and the system can't recover. Please log out and try again."
There was no effective way to screenshot it but I snapped a picture of it with my phone.
![crash image](https://dev.getsol.us/file/data/hbw7xc6kbdkgbn5w7rhc/PHID-FILE-ulr4ikyz6yryj5vphrxs/photo_2019-12-25_19-54-02.jpg)

## Steps to reproduce the issue
The sequence of actions that triggered this crash were to 
- log in, 
- select any number of entries from the desktop (with icons enabled), 
- and choose "Move to....", 
- and it crashes

## Actual result
I pulled my Journal and navigated to the time of the crash. You can read the relevant snippet here: [possibly relevant log](https://dev.getsol.us/file/download/7bfb77xucuw4i5uvgolk/PHID-FILE-tytg4skceo6cy7jihdwq/possible_relevant_journal_entries.txt)

**Comment by JoshStrobl** [comment]
Making this a target for 10.5.2 since that is when I intend on replacing the desktop icons implementation. Sorry for the inconvenience.

**Comment by N1X3L** [comment]
Been struggling with this lately myself. Same crash happening for me as stated above, or when I use the Budgie applet to restart panels just after booting, or if I try to attach a file from the Desktop (but not anywhere else) in a browser regardless of how long it has been since startup.

**Comment by hyphenrf** [comment]
I'm suspecting something.. Allow me to ask, what's your umask @N1X3L ?
And what are the perms on your $HOME, $HOME/Desktop?

**Comment by N1X3L** [comment]
Hopefully that's correct. Let me know if you need further info. This is from my laptop, but both my machines are exhibiting the same behaviour. I can post my desktop info as well when I return home this evening, if that would be of help. Just let me know, and thank you!

![Screenshot from 2020-01-31 13-27-36](https://user-images.githubusercontent.com/58523957/73568512-26e5cc00-442e-11ea-88c6-039df6eb28f8.png)

**Comment by hyphenrf** [comment]
that's fine.. looks like my suspicion about it being a permissions issue is probably wrong -- assuming you haven't changed your desktop perms from the default values.

**Comment by JoshStrobl** [comment]
Closing this as the new [Budgie Desktop View](https://github.com/getsolus/budgie-desktop-view) has been released (with a 1.0 next week, 0.99.3 tagged at the moment), which eliminates the use of the legacy Nautilus implementation.

Building on that, there is now a vendor-specific configuration (also accessible to end users if you dig in the dconf / gsettings options enough) for alternatives such as DesktopFolder and Nemo, subject to what is available in your operating system's repositories, should you not desire to use the official desktop icons / view implementation.
