### ISSUE TITLE
Wifi Icons Poorly Seen on Default Theme

### ISSUE THREAD

**Issue by thumos333** [solus-project/budgie-desktop#1921]
## Description
Icons for wifi networks are barely seen with the default Budgie theme, Plata.

![Screenshot from 2020-01-08 11-02-03](https://user-images.githubusercontent.com/29035180/71960831-08adf700-3207-11ea-8017-6b301ac9daf0.png)

## Budgie version
This has been an issue since a long time but I am now using 10.5.1-204.

## Operating system
Latest Solus 4

## Expected result
Better contrast for the icons

## Additional information
Many thanks to the team making and maintaining Budgie Desktop and Solus.

**Comment by JoshStrobl** [comment]
These icons aren't provided by Budgie, they're provided by the icon theme developer. Not a Budgie issue.

**Comment by thumos333** [comment]
Okay but icons makers will probably say the DE developers did not adjust the interface to the icons... so, not clear who to address here...
