### ISSUE TITLE
File search in Run Dialog(Alt+F2) 

### ISSUE THREAD

**Issue by kp2401075** [solus-project/budgie-desktop#1922]
### Current Budgie version
budgie-desktop 10.5.1

First of all thank you for the good work you guys are doing.

### Use-cases
To quickly open files directly from Run dialog
Rather than opening nautilus and then searching for file and then opening it.

This can make workflow very fast for many users.

### Proposal
may be we can have a look at how gnome implements search in overview.

### References
Don't know if anyone had requested this before.

**Comment by JoshStrobl** [comment]
The intent of the run dialog is for quick launching of applications. I have no desire to implement indexers, Tracker integration, etc. for file searching in it.
