### ISSUE TITLE
Remap Caps Lock to Ctrl

### ISSUE THREAD

**Issue by landersson** [solus-project/budgie-desktop#1924]
I've spent a fair bit of time trying to remap Caps_Lock to Control_L on Budgie 19.10. I've tried the usual ways such as xmodmap, setxkbmap, changing XKBOPTIONS in /etc/default/keyboard, gnome-tweaks etc, and everything has failed.

Can anyone suggest a method that will work?

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue. Please file your support query on the support forums for the OS you use.

P.S: You use **Ubuntu Budgie** 19.10, Budgie itself is 10.5.1.
