### ISSUE TITLE
Brightness and media keys do not work or show feedback when a budgie applet is open.

### ISSUE THREAD

**Issue by gitSaptarshi** [solus-project/budgie-desktop#1926]
I am noticing it for some days that the media and volume keys do not work or show any visual feedbacks upon pressing when a budgie applet is open.

**Actual Result**
When a budgie applet is open, the media and brightness keys do not work or show any visual feedback. It perfectly works when raven sidebar is open but not with any budgie applet.

**Expected Result**
They should work and show feedback whether any budgie applet is open or not.

**My configuration**
OS: _Solus x86_64_
DE: _Budgie 10.5_
LSB Version: 1.4
Release: _4.0_
Codename: _fortitude_
Host: _81H7 Lenovo ideapad 130-15IKB_

**Comment by JoshStrobl** [comment]
> I am noticing it for some days that the media and volume keys do not work or show any visual feedbacks upon pressing when a budgie applet is open.

That's because applets (a.k.a Budgie Popovers) steal focus. Same goes for Budgie Menu.
