### ISSUE TITLE
Add an option to customize workspace animation speed or disable them

### ISSUE THREAD

**Issue by Kabouik** [solus-project/budgie-desktop#1929]
### Current Budgie version
budgie-desktop 10.5.1

### Use-cases
When disabling window animations in Budgie Settings, it would be ideal to also be able to get rid of workspace animations. Having one setting off without ways to disable the other one is visually inconsistent.

### Proposal
Add a setting to toggle workspace animations like the current toggle for window animations as well. Perhaps a way to edit animation speed using dconf could be useful too, but shouldn't be in the UI.

#### IRC excerpt:
> <@Kabouik> Is there a way to remove the workspace change animation in Budgie?
> <@Kabouik> Budgie Settings > Style > Animations only applies to windows animation, not workspaces
> <@JoshStrobl> No.
> <@Kabouik> Ok JoshStrobl, thanks, I was thinking there might be something in dconf.
> <@JoshStrobl> Unfortunately not. The animation is effectively a hard-coded Clutter animation.
> <@Kabouik> Will it still be true after the big Budgie update?
> <@JoshStrobl> It'll probably follow the same logic but it wouldn't be that much work for me to add an option in to disable it.
> <@Kabouik> That would be great I think, it is a bit weird to have animations for workspaces when all other animations are disabled in Budgie settings
> <@JoshStrobl> Mind filing a feature request at https://github.com/solus-project/budgie-desktop/issues ? I'll assign it to myself and have it be a target for 10.5.2.

**Comment by JoshStrobl** [comment]
Thanks for filing the feature request :)
