### ISSUE TITLE
not detected by sddm

### ISSUE THREAD

**Issue by spider623** [solus-project/budgie-desktop#193]
title tells it all, i can't choose it as a desktop environment from sddm

**Comment by ikeydoherty** [comment]
How did you install Budgie?

**Comment by Limero** [comment]
I'm able to choose Budgie in SDDM without any kind of problem. Probably an error in your installation.

**Comment by ikeydoherty** [comment]
Fixed in v10

**Comment by spider623** [comment]
wow, i really need to setup an email notification
