### ISSUE TITLE
Software Center not responding

### ISSUE THREAD

**Issue by szmarczak** [solus-project/budgie-desktop#1931]
## Budgie version

budgie-desktop 10.5.1

## Operating system

```
Linux solus 5.4.12-144.current #1 SMP PREEMPT Mon Jan 20 15:46:35 UTC 2020 x86_64 GNU/Linux
```

## Steps to reproduce the issue

1. Click on `Check for updates` on a third party app.
2. Go to `Updates` tab. Click `Check for updates`.
3. Go back to that third party app and click `Check for updates` again.

## Actual result

Software Center froze and is unresponsive.

![image](https://user-images.githubusercontent.com/36894700/73189990-981f3980-4125-11ea-95a6-b244d837ce11.png)

## Expected result

No freeze.

**Comment by EbonJaeger** [comment]
The Software Center isn't a part of Budgie. Its repo is [here](https://github.com/getsolus/solus-sc). :)

**Comment by szmarczak** [comment]
Oh, thanks :)
