### ISSUE TITLE
Enhance multiple system trays

### ISSUE THREAD

**Issue by mazunki** [solus-project/budgie-desktop#1933]
### Current Budgie version

Running latest Manjaro version, Juhraya 18.1.15 with budgie-desktop.

budgie-desktop 10.5.1-1 (git-e6433d87974e735296e72cf5b9d2a25466d5fe7a)

### Use-cases

I have multiple panels, and I would like to see the system tray in two of these. 

Problem is, the system trays seem to be independent, so I either have my Telegram (example) icon in one of them, or the other one. I can't choose where I want each icon either, as they randomly (or not-so-randomly, but I don't know how apps are added to they tray/s) pick where to be placed. 

### Proposal

Add a settings to the System Tray which allows the user to choose what programs are shown in each tray. Maybe add a drag and drop possibility, and/or a "add all current tray icons to list". Selecting "all except these" should also be possible.

### References

Related somehow to issue #851

**Comment by JoshStrobl** [comment]
This isn't really feasible with the system the System Tray applet leverages, na-tray. Sorry.
