### ISSUE TITLE
Many unread notifications causes poor performance of Raven sidebar

### ISSUE THREAD

**Issue by arcooke** [solus-project/budgie-desktop#1934]
## Description

Raven sidebar animation gets _very_ choppy when there are many unread notifications.

## Budgie version

10.5.1

## Operating system

Solus 4

## Steps to reproduce the issue

Let notifications pile up for weeks and never check them.  Raven sidebar starts performing very poorly.  Clear notifications, problem instantly fixed

## Actual result

Slow/choppy animation when there are many notifications

## Expected result
Not slow/choppy animation when there are many notifications

## Additional information
AMD Vega 64 - Mesa 19.3.2-135

**Comment by JoshStrobl** [comment]
Duplicate of #1802

**Comment by MatthewScholefield** [comment]
@JoshStrobl Why mark as a duplicate of a closed issue? Seems like this presents a real world use case.

**Comment by EbonJaeger** [comment]
...Because it's a duplicate of the issue (i.e., the same issue)?

**Comment by MatthewScholefield** [comment]
True, lol. I guess I mean why close after marking as a duplicate if it presents new info.

**Comment by EbonJaeger** [comment]
Because it should be posted in the original issue, in order to keep everything together and organized.
