### ISSUE TITLE
Make the Bluetooth status icon to not be tied with the other icons like Wifi

### ISSUE THREAD

**Issue by cata0309** [solus-project/budgie-desktop#1937]
### Proposal

I do not use bluetooth and I don't like seeing the useless bluetooth icon from the budgie panel. I know it is in the system tray applet.
My proposal is to make bluetooth to be independently disabled !
The code that should be tweaked is https://github.com/budgie-desktop/budgie-desktop/blob/master/src/applets/status/StatusApplet.vala

**Comment by JoshStrobl** [comment]
Duplicate of #455, no immediate plans on it.
