### ISSUE TITLE
Building on debian sid

### ISSUE THREAD

**Issue by yellowmegaman** [solus-project/budgie-desktop#194]
Hello! I'd like to ask whenever something can be done to fix make.

Part of my "make" output:

make  all-am
make[3]: вход в каталог «/home/emik0/Загрузки/budgie-desktop/rundialog»
  VALAC    budgie_run_dialog_vala.stamp
RunDialog.vala:78.5-78.35: warning: Budgie.RunDialogItem.image hides inherited field `Gtk.Button.image'. Use the `new' keyword if hiding was intentional
    public RunDialogItemImage image;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 1 warning(s)
  CC       budgie_run_dialog-RunDialog.o
RunDialog.c: In function ‘budgie_run_dialog_init_results_box’:
RunDialog.c:1199:2: warning: ‘gtk_misc_set_alignment’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h:72) [-Wdeprecated-declarations]
  gtk_misc_set_alignment ((GtkMisc*) _tmp5_, (gfloat) 0, (gfloat) 0);
  ^
RunDialog.c:1223:2: warning: ‘gtk_misc_set_alignment’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h:72) [-Wdeprecated-declarations]
  gtk_misc_set_alignment ((GtkMisc*) _tmp17_, (gfloat) 0, (gfloat) 0);
  ^
RunDialog.c: In function ‘budgie_run_dialog_search_applications’:
RunDialog.c:1371:11: error: too many arguments to function ‘g_desktop_app_info_search’
  _tmp5_ = g_desktop_app_info_search (_tmp3_, &_tmp4_);
           ^
In file included from RunDialog.c:23:0:
/usr/include/gio-unix-2.0/gio/gdesktopappinfo.h:166:11: note: declared here
 gchar *** g_desktop_app_info_search (const gchar *search_string);
           ^
RunDialog.c:1371:9: warning: assignment from incompatible pointer type
  _tmp5_ = g_desktop_app_info_search (_tmp3_, &_tmp4_);
         ^
RunDialog.c:1372:9: warning: assignment from incompatible pointer type
  search = _tmp5_;
         ^
Makefile:514

All libs are installed as said here:

https://solus-project.com/forums/viewtopic.php?t=385

Thanks a lot in advance!

**Comment by ikeydoherty** [comment]
What versions of Vala and GLib do you have?

**Comment by ikeydoherty** [comment]
Also:
```
↠ grep search /usr/share/vala*/vapi/gio-unix*.vapi
		public static string**[] search (string search_string);
```

**Comment by yellowmegaman** [comment]
Valac 0.26.1-1.1 Debian sid
libglib2.0-dev 2.42.1-1

mybox[~/budgie-desktop] grep search /usr/share/vala*/vapi/gio-unix*.vapi
		public static void*[] search (string search_string);
mybox[~/budgie-desktop]

thanks for quick reply)

**Comment by ikeydoherty** [comment]
So yeah, vapi is borked on your Vala version. Don't worry too much, I'm going to remove that function call shortly... The rundialog is too aggressive on resources. For now you can disable it (check ./configure --help)

**Comment by yellowmegaman** [comment]
Thanks a lot!

clone && ./autogen.sh --prefix=/usr && ./configure --disable-rundialog && make
worked perfectly.

But got errors in "sudo make install" now.

libtool: install: error: cannot install `libbudgiemenuapplet.la' to a directory not ending in /usr/lib/budgie-desktop

Makefile:465: error running recipe for target «install-pkglibLTLIBRARIES»
And so on, does that mean only libtool err must be fixed, so other will just cascade-solved?

**Comment by ikeydoherty** [comment]
Did you clean up after your initial build failures? You might need to use your distributions libdir, I hate libtool sometimes.

**Comment by yellowmegaman** [comment]
That's exactly what i've missed)

Working debian sid command:

git clone https://github.com/solus-project/budgie-desktop.git && cd budgie-desktop && ./autogen.sh --prefix=/usr && ./configure --disable-rundialog && make && sudo make install

Btw how can i debug it now? Logging in from slim gives me blackscreen, running budgie-session from terminal on xfce gives me this:

** (budgie-session:7712): WARNING **: BudgieSession.vala:204: Not relaunching budgie-wm as it has died 3 times already

** (budgie-session:7712): CRITICAL **: BudgieSession.vala:208: Critical desktop component budgie-wm exited with status code 5

**Comment by ikeydoherty** [comment]
Anything in .xsession-errors?

**Comment by yellowmegaman** [comment]
Slim:
** (budgie-session:9558): WARNING **: BudgieSession.vala:204: Not relaunching budgie-wm as it has died 3 times already

** (budgie-session:9558): CRITICAL **: BudgieSession.vala:208: Critical desktop component budgie-wm exited with status code 5
9659 (budgie-wm) closed with exit code: 5
Launched 1 times
9721 (budgie-wm) closed with exit code: 5
Launched 2 times
9741 (budgie-wm) closed with exit code: 5
Launched 3 times

####################################

LightDM - same.

**Comment by ikeydoherty** [comment]
Do you have video drivers/hardware capable of running an accelerated window manager?

**Comment by yellowmegaman** [comment]
Well, i got intel i5-4570 CPU with built-in Intel 4600 HD graphics. Since opengl ( minecraft for testing) is working ok, i assume yes, should be.

Fun thing - i've just notices that after some update, debian thinks i've got 2 monitors, hdmi one (real) and eDP1. Trying to disable it firtst

**Comment by yellowmegaman** [comment]
After adding "eDP-1:d video=HDMI-2:e" to "GRUB_CMDLINE_LINUX_DEFAULT" in /etc/default/grub 
and running sudo update-grub i've managed to disable eDP1.

That got me to budgie-panel showing up for 1sec after login)

**Comment by yellowmegaman** [comment]
Original issue  - "Build on debian sid" is solved, great many thanks! Should i close issue now? And open new one?

**Comment by yellowmegaman** [comment]
Before closing - is there a possibility that some references to rundialog should be removed elsewhere, so everything would be fixed? So sad that compiles ok, but can't use. Best DE i've seen in 10+ years

**Comment by ikeydoherty** [comment]
How do you mean?

**Comment by yellowmegaman** [comment]
I mean that right now i build with "./configure --disable-rundialog && make" and it compiles ok, but selecting budgie desktop session in login manager gives be 1 sec blink of budgie panel and then black screen and errors listed above.

Maybe it doesn't run at all without rundialog? Sorry, C is not one of my skills :(

**Comment by ikeydoherty** [comment]
Rundialog is only invoked when you run ALT+F2. An obvious test would be to see whether GNOME Shell works on your machine, as both budgie-wm and gnome-shell use Mutter.

**Comment by yellowmegaman** [comment]
Just installed GNOME3, and budgie worked finally :)) one question left - how  to fight empty menu? cant launch anything atm..

**Comment by yellowmegaman** [comment]
Nevermind menu, installed "gnome-menus" and its working perfectly! 

Thanks again alot for help!)

Just read  a wiki about sonus, and found out u'r the main dev, its a greate pleasure to "meet" you and talk) 

Best!

**Comment by ikeydoherty** [comment]
*Solus :P 

No problem - glad its all resolved now. I'm going to guess you had a missing gsettings schema for mutter then, something like this happened for someone before :)

**Comment by yellowmegaman** [comment]
Soo basically i need to have full gnome3 installed so budgie will work? Mutter and other packages require almost complete set of gnome packages...

**Comment by ikeydoherty** [comment]
Maybe for Debian - that's an argument you need to take up with that distros maintenance policies. Mutter provides a library for use by budgie-wm, and we also take in gnome-settings-daemon. Debian also sports the ridiculous packaging of gnome-menus by separating it from the library component that Budgie builds against.

On other distros you do not need a "full gnome3 install" - I'd also point out Budgie != GNOME3. GNOME also != GNOME3, GNOME 3 == GNOME Shell.

This is a distro problem. We ask for all the things we require at build time. (Mutter now uses schemas from gnome-settings-daemon, so it should depend on it. Something Debian has failed to address)

**Comment by yellowmegaman** [comment]
Thanks for detailed response,)

**Comment by Justinzobel** [comment]
Are you sure you followed the instructions on the forums, if you had you would've already had all of the required packages: build-essential gnome-common gobject-introspection libglib2.0-dev libgtk-3-dev libpulse-dev libpulse-mainloop-glib0 libmutter-dev libwnck-3-dev libupower-glib-dev libgnome-menu-3-dev libc6-dev libpeas-dev libgee-dev libgee-0.8-dev valac

**Comment by yellowmegaman** [comment]
Tried, doesnt work that way. Only option - compiling like said above, while having gnome3 installed almost full. BTW after compilnig budgie ignores non-default icons completely, gorgeous EvoPop for instance.

**Comment by Justinzobel** [comment]
I've had Budgie compiled on a vanilla Debian install without Gnome3 a 
few times...

What do you mean it ignores non-default? Have you installed and selected 
EvoPop icons in Budgie's settings?

**Comment by yellowmegaman** [comment]
Ok, detailed:
1) http://ftp.nl.debian.org/debian/dists/sid/main/installer-amd64/current/images/netboot/ mini.iso for clean installation (without X, only "ssh-server + standart")
2) Select expert install and then "sid" to get only sid, without upgrading from testing.
3) ssh to box, install packages from https://solus-project.com/forums/viewtopic.php?t=385 ( since apt-get  build-dep budgie-desktop doesn't work, budgie not in repo)

4) git clone https://github.com/solus-project/budgie-desktop.git && cd budgie-desktop && ./autogen.sh --prefix=/usr && ./configure --disable-rundialog && make && sudo make install

5) apt-get install slim, adding budgie.desktop to /usr/share/xsessions/ manually, it is pointed to launch   budgie-session

All above results in "gimme dbus-x11" , after installing, it gives:

** (budgie-session:7712): WARNING **: BudgieSession.vala:204: Not relaunching budgie-wm as it has died 3 times already

** (budgie-session:7712): CRITICAL **: BudgieSession.vala:208: Critical desktop component budgie-wm exited with status code 5

If i install mutter ( with a ton of other packages taken as dependencies) - its working. Menu fixed by installing gnome-menus.

Select icons in budgie settings doesn't work, but selecting theme does work ok.

**Comment by yellowmegaman** [comment]
Ok i've just moved files from EvoPop dir to Adwaita, everything else works, sound/widgets/settings/etc/etc) Still got gnome3 full installed though, but thats the price on debian. Was using xfce for past 5-6yeats, tired of it, Budgie is the best)

**Comment by Justinzobel** [comment]
Try lightdm or gdm instead of slim

**Comment by yellowmegaman** [comment]
Don't understand how it could help, since it wants mutter or its dependencies. But tried with lightdm, exact same thing.
