### ISSUE TITLE
Network connection sometimes completely disconnects on laptop, needs to be restarted

### ISSUE THREAD

**Issue by marek-lach** [solus-project/budgie-desktop#1940]
## Description
WiFi can often completely disconnect from the Network Manager, and only a complete computer restart starts it back again.

Adding
```
[device]
wifi.scan-rand-mac-address=no

[connection-mac-randomization]
wifi.cloned-mac-address=stable
```
can help keep the Wifi active for longer, but it'll disconnect itself eventually no matter what. All power saving features have been turned off, happens anyway.

## Budgie version
10.5.1

## Operating system
Manjaro Linux, EndeavourOS

**Comment by JoshStrobl** [comment]
Nothing to do with Budgie, We're not responsible for network manager.

**Comment by camdenorrb** [comment]
I also experience this issue
