### ISSUE TITLE
Cannot compile Budgie: `new' modifier not allowed on creation method

### ISSUE THREAD

**Issue by RockfordRoe** [solus-project/budgie-desktop#1943]
## Description
Ninja spits out a "'new' modifier not allowed on creation method" error when compiling 

## Budgie version
89fca86

## Operating system
Gentoo GNU/Linux

## Steps to reproduce the issue
Configure the build with `meson build --prefix=/usr --sysconfdir=/etc`

Then run `ninja -C build`

## Actual result

Ninja exists with a build stop.

## Expected result
Successful build of the desktop

## Additional information
[log.txt](https://github.com/solus-project/budgie-desktop/files/4240702/log.txt)

**Comment by tcreek** [comment]
I am getting the same result. I am on Debian 10

**Comment by JoshStrobl** [comment]
Unable to reproduce on Solus. Could you provide me the meson output (which includes the run-time dependency checks) and what flags you're using? Thanks!

**Comment by tcreek** [comment]
Here is mine just using  "meson build --prefix=/usr --sysconfdir=/etc" per the Wiki

```
The Meson build system
Version: 0.53.2
Source dir: /home/trent/Developer/budgie-desktop
Build dir: /home/trent/Developer/budgie-desktop/build
Build type: native build
Project name: budgie-desktop
Project version: 10.5.1
C compiler for the host machine: ccache cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
C linker for the host machine: cc ld.bfd 2.31.1
Vala compiler for the host machine: valac (valac 0.42.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
meson.build:32: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
Program meson_post_install.sh found: YES (/home/trent/Developer/budgie-desktop/meson_post_install.sh)
Dependency gtk+-3.0 found: YES 3.24.5 (cached)
Dependency glib-2.0 found: YES 2.58.3 (cached)
Dependency gio-unix-2.0 found: YES 2.58.3 (cached)
Dependency libpeas-1.0 found: YES 1.22.0 (cached)
Dependency gdk-x11-3.0 found: YES 3.24.5 (cached)
Dependency uuid found: YES 2.33.1 (cached)
Dependency vapigen found: YES 0.42.5 (cached)
Dependency ibus-1.0 found: YES 1.5.19 (cached)
Dependency libnotify found: YES 0.7.7 (cached)
Dependency gnome-desktop-3.0 found: YES 3.30.2.1 (cached)
Dependency gsettings-desktop-schemas found: YES 3.28.1 (cached)
Dependency gnome-settings-daemon found: YES 3.30.2 (cached)
Dependency libwnck-3.0 found: YES 3.30.0 (cached)
Dependency accountsservice found: YES 0.6.45 (cached)
Program intltool-merge found: YES (/usr/bin/intltool-merge)
meson.build:105: WARNING: You must have Nautilus 3.26 or older for desktop icons with Budgie
Configuring config.h using configuration

|Executing subproject gvc method meson 
|
|Project name: gvc
|Project version: undefined
|C compiler for the host machine: ccache cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
|C linker for the host machine: cc ld.bfd 2.31.1
|Dependency gio-2.0 found: YES 2.58.3 (cached)
|Dependency gobject-2.0 found: YES 2.58.3 (cached)
|Dependency libpulse found: YES 12.2 (cached)
|Dependency libpulse-mainloop-glib found: YES 12.2 (cached)
|Dependency alsa found: YES 1.1.8 (cached)
|Configuring config.h using configuration
|Build targets in project: 2
|Subproject gvc finished.


|Executing subproject translations method meson 
|
|Project name: budgie-desktop
|Project version: 10.5
|Build targets in project: 5
|Subproject translations finished.

Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency gtk+-x11-3.0 found: YES 3.24.5 (cached)
Dependency x11 found: YES 1.6.7 (cached)
Program sassc found: YES (/usr/bin/sassc)
Library m found: YES
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Dependency gnome-settings-daemon found: NO found 3.30.2 but need: '>=3.33.90'
Found CMake: /usr/bin/cmake (3.13.4)
Run-time dependency gnome-settings-daemon found: NO (tried pkgconfig and cmake)
Message: Found GNOME Settings Daemon >= 3.33.90
Dependency polkit-gobject-1 found: YES 0.105 (cached)
Dependency polkit-agent-1 found: YES 0.105 (cached)
Dependency libmutter-3 found: YES 3.30.2 (cached)
Dependency libgnome-menu-3.0 found: YES 3.31.4 (cached)
Library m found: YES
Dependency upower-glib found: YES 0.99.10 (cached)
Library m found: YES
Dependency gnome-bluetooth-1.0 found: YES 3.28.2 (cached)
Dependency gnome-settings-daemon found: YES 3.30.2 (cached)
Configuring budgie-desktop.session.in using configuration
Configuring budgie-desktop using configuration
Configuring budgie-desktop.desktop.in using configuration
Program gtkdocize found: YES (/usr/bin/gtkdocize)
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    datadir:                                /usr/share
    sysconfdir:                             /etc
    localedir:                              /usr/share/locale
    libdir:                                 /usr/lib/x86_64-linux-gnu
    module library directory:               /usr/lib/x86_64-linux-gnu/budgie-desktop/plugins
    module data directory:                  /usr/share/budgie-desktop/plugins

    Extra options:
    ==============

    gtk-doc:                                true
    desktop icons:                          nautilus
    stateless:                              false


Build targets in project: 99

budgie-desktop 10.5.1

  Subprojects
             gvc: YES
    translations: YES
```

**Comment by RockfordRoe** [comment]
> Unable to reproduce on Solus. Could you provide me the meson output (which includes the run-time dependency checks) and what gcc flags you're using? Thanks!

Here's mine:

`The Meson build system
Version: 0.53.1
Source dir: /home/ethan/Git/budgie-desktop
Build dir: /home/ethan/Git/budgie-desktop/build
Build type: native build
Project name: budgie-desktop
Project version: 10.5.1
C compiler for the host machine: cc (gcc 9.2.0 "cc (Gentoo 9.2.0-r4 p5) 9.2.0")
C linker for the host machine: cc GNU ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.46.6)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
meson.build:32: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
Program meson_post_install.sh found: YES (/home/ethan/Git/budgie-desktop/meson_post_install.sh)
Dependency gtk+-3.0 found: YES 3.24.14 (cached)
Dependency glib-2.0 found: YES 2.62.5 (cached)
Dependency gio-unix-2.0 found: YES 2.62.5 (cached)
Dependency libpeas-1.0 found: YES 1.22.0 (cached)
Dependency gdk-x11-3.0 found: YES 3.24.14 (cached)
Dependency uuid found: YES 2.35.1 (cached)
Dependency vapigen found: YES 0.46.6 (cached)
Dependency ibus-1.0 found: YES 1.5.21 (cached)
Dependency libnotify found: YES 0.7.8 (cached)
Dependency gnome-desktop-3.0 found: YES 3.32.2 (cached)
Dependency gsettings-desktop-schemas found: YES 3.32.0 (cached)
Dependency gnome-settings-daemon found: YES 3.32.1 (cached)
Dependency libwnck-3.0 found: YES 3.30.0 (cached)
Dependency accountsservice found: YES 0.6.50 (cached)
Program intltool-merge found: YES (/usr/bin/intltool-merge)
meson.build:105: WARNING: You must have Nautilus 3.26 or older for desktop icons with Budgie
Configuring config.h using configuration

|Executing subproject gvc method meson 
|
|Project name: gvc
|Project version: undefined
|C compiler for the host machine: cc (gcc 9.2.0 "cc (Gentoo 9.2.0-r4 p5) 9.2.0")
|C linker for the host machine: cc GNU ld.bfd 2.34
|Dependency gio-2.0 found: YES 2.62.5 (cached)
|Dependency gobject-2.0 found: YES 2.62.5 (cached)
|Dependency libpulse found: YES 13.0 (cached)
|Dependency libpulse-mainloop-glib found: YES 13.0 (cached)
|Dependency alsa found: YES 1.2.2 (cached)
|Configuring config.h using configuration
|Build targets in project: 2
|Subproject gvc finished.


|Executing subproject translations method meson 
|
|Project name: budgie-desktop
|Project version: 10.5
|Build targets in project: 5
|Subproject translations finished.

Found pkg-config: /usr/bin/pkg-config (1.6.3)
Dependency gtk+-x11-3.0 found: YES 3.24.14 (cached)
Dependency x11 found: YES 1.6.9 (cached)
Program sassc found: YES (/usr/bin/sassc)
Library m found: YES
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Dependency gnome-settings-daemon found: NO found 3.32.1 but need: '>=3.33.90'
Found CMake: /usr/bin/cmake (3.16.4)
Run-time dependency gnome-settings-daemon found: NO (tried pkgconfig and cmake)
Message: Found GNOME Settings Daemon >= 3.33.90
Dependency polkit-gobject-1 found: YES 0.116 (cached)
Dependency polkit-agent-1 found: YES 0.116 (cached)
Run-time dependency libmutter-3 found: NO (tried pkgconfig and cmake)
Dependency libmutter-4 found: YES 3.32.2 (cached)
Message: Using new libmutter-4 ABI from GNOME 3.32
Dependency libgnome-menu-3.0 found: YES 3.32.0 (cached)
Library m found: YES
Dependency upower-glib found: YES 0.99.11 (cached)
Library m found: YES
Dependency gnome-bluetooth-1.0 found: YES 3.34.0 (cached)
Dependency gnome-settings-daemon found: YES 3.32.1 (cached)
Configuring budgie-desktop.session.in using configuration
Configuring budgie-desktop using configuration
Configuring budgie-desktop.desktop.in using configuration
Program gtkdocize found: YES (/usr/bin/gtkdocize)
Message: 


    Build configuration:
    ====================

    prefix:                                 /usr
    datadir:                                /usr/share
    sysconfdir:                             /etc
    localedir:                              /usr/share/locale
    libdir:                                 /usr/lib64
    module library directory:               /usr/lib64/budgie-desktop/plugins
    module data directory:                  /usr/share/budgie-desktop/plugins

    Extra options:
    ==============

    gtk-doc:                                true
    desktop icons:                          nautilus
    stateless:                              false


Build targets in project: 99

budgie-desktop 10.5.1

  Subprojects
             gvc: YES
    translations: YES

Found ninja-1.9.0.git.kitware.dyndep-1.jobserver-1 at /usr/bin/ninja
`

**Comment by tcreek** [comment]
I gave you a response, but you responded with your original  question, which mean I am probably unsure of what you want then if I provided is not what you are looking for. 


All I am doing is following the Wiki

> cd budgie-desktop
> meson build --prefix=/usr --sysconfdir=/etc
> ninja -j$(($(getconf _NPROCESSORS_ONLN)+1)) -C build

I provided the output for line #2 from above, and the OP provided from line #3.

**Comment by RockfordRoe** [comment]
I was looking at the source code that ninja complained about and it seems that these lines are causing the trouble:

```#if HAVE_MUTTER_5 || HAVE_MUTTER_6
    private void on_accelerator_activated(uint action, Clutter.InputDevice dev, uint timestamp)
#else
    private void on_accelerator_activated(uint action, uint device_id, timestamp)
#endif
    {
        foreach (string accelerator in grabs.get_keys ()) {
            if (grabs[accelerator] == action) {
                var params = new GLib.HashTable<string, Variant> (null, null);
#if HAVE_MUTTER_5 || HAVE_MUTTER_6
                params.set ("device-id", new Variant.uint32 (dev.id));
                params.set ("action-mode", new Variant.uint32 (action));
                params.set ("device-mode", new Variant.string (dev.get_device_node()));
#else
                params.set ("device-id", new Variant.uint32 (device_id));
#endif
                params.set ("timestamp", new Variant.uint32 (timestamp));
                this.accelerator_activated (action, params);
            }
        }
    }
```

@nirbheek and I are using MUTTER_3 and MUTTER_4 respectively

**Comment by tcreek** [comment]
The wiki does state "mutter >= 3.22.0"

I do wonder if that is outdated. I did notice on the Wiki for the requirements for Ubuntu 18.x it states Mutter =>3.x. but the install they use is for  Mutter 2. Ubuntu 18.x does not even have Mutter 3+

**Comment by RockfordRoe** [comment]
My distribution finally updated Mutter to 3.34. It seems to compile after the update so I think it's an issue relating to Muter versions <=3.32

**Comment by tcreek** [comment]
I would agree. Looking, I see Debian 10 does have Budgie Desktop version 10.5-1 available, so the error must of been introduced after.

**Comment by JoshStrobl** [comment]
You're indeed using too old releases of supported stacks / libraries. I'll be rectifying these inaccuracies in an upcoming commit and will update the wiki accordingly.

Please note that "Mutter 3+" and the like are referencing their pkgconfig are change during different stack releases, e.g. libmutter-3, libmutter-4, libmutter-5, libmutter-6. libmutter-5 is in the 3.34 stack and libmutter-6 is in the upcoming 3.36 stack releases from GNOME and are the supported targets.
