### ISSUE TITLE
Adding more than 8 workspaces via Workspace Switcher Applet results in undesired behavior

### ISSUE THREAD

**Issue by jprostko** [solus-project/budgie-desktop#1944]
## Description
When using Solus 4.1 and trying to create more than 8 Workspaces via the Workspace Switcher applet, Solus becomes unstable, and then logs the user out of their session, resulting in lost work.  While it may or may not have been an intentional choice with Budgie 10.5.1 to limit users to creating a maximum of 8 workspaces, system instability should not result from trying to add more.

## Budgie version
Budgie 10.5.1

## Operating system
Solus 4.1 (Fortitude)

## Steps to reproduce the issue
Try to add more than 8 workspaces via the Workspaces Switcher applet.

## Actual result
When adding the 9th workspace, the desktop background goes black, and then returns a few seconds later.  The 9th workspace does not actually get added either.  Clicking the '+' sign further will result in either the same behavior with the black background, or will ultimately result in an error which leaves the user with the only option of logging out of the session, and subsequently losing any work within the session.

![workspace_addition_bug](https://user-images.githubusercontent.com/563778/76031376-935c5b00-5f05-11ea-8e5f-9e5876dee83d.png)

## Expected result
Either more than 8 workspaces are added successfully, or if it is a designed feature to not allow more than 8 workspaces, then simply not allow a user to attempt to add more than 8 workspaces via the workspace switcher.

## Additional information
This impacts Ubuntu Budgie as well in Focal (what will become Ubuntu Budgie 20.04).

**Comment by fossfreedom** [comment]
hmm - https://github.com/solus-project/budgie-desktop/blob/master/src/wm/wm.vala#L633

commenting out the > 8 restriction prevents this crash. Ack. the comment there for restricting the number.  Also note  - gnome shell nor gala restricts the number of workspaces
