### ISSUE TITLE
Old https://solus-project.com/ link on GitHub

### ISSUE THREAD

**Issue by MatthewScholefield** [solus-project/budgie-desktop#1946]
Link on repo page should be changed to https://getsol.us/
![solus](https://user-images.githubusercontent.com/5875019/76156400-9b5ffa80-60bf-11ea-99cb-847076e1455b.png)

**Comment by JoshStrobl** [comment]
Duplicate of #1849

**Comment by MatthewScholefield** [comment]
Ahh, whoops I skipped right over it.
