### ISSUE TITLE
Video Wallpapers

### ISSUE THREAD

**Issue by Krutonium** [solus-project/budgie-desktop#1947]
### Current Budgie version

10.5.1

### Use-cases

I want to be able to set a video as my desktop wallpaper, like for example a recording of an intersection in Cities Skylines

### Proposal

Have it show up with all the other wallpapers?

### References

Not that I know of.

**Comment by JoshStrobl** [comment]
There are no plans on implementing this in the Budgie 10 series and it is something that is being considered as a planned feature for Budgie 11, which will not be developed in this repo. As such, closing as WONTFIX.

**Comment by Krutonium** [comment]
Can you point me at the Budgie 11 Repo?

**Comment by JoshStrobl** [comment]
No because it doesn't exist yet.

**Comment by Krutonium** [comment]
That is a fair statement. Love budgie by the way, and I wish you all good luck with it going into the future.
