### ISSUE TITLE
Set "open in terminal" to konsole failed.

### ISSUE THREAD

**Issue by zw963** [solus-project/budgie-desktop#1948]
![image](https://user-images.githubusercontent.com/549126/77001783-7314ad80-6995-11ea-8d77-0a8c6bb0d295.png)

Following is my command, it never working, always open a new gnome-terminal.

```
gsettings set org.gnome.desktop.default-applications.terminal exec konsole
```

Thank you.

**Comment by JoshStrobl** [comment]
This isn't part of Budgie Desktop. Please file it with the appropriate project.
