### ISSUE TITLE
The `Restart device` button doesn't do anything

### ISSUE THREAD

**Issue by szmarczak** [solus-project/budgie-desktop#1949]
## Description

![Peek 2020-03-19 14-45](https://user-images.githubusercontent.com/36894700/77073885-417d0000-69f0-11ea-8b79-a823350cfd1f.gif)

## Budgie version

```
budgie-desktop 10.5.1
```

## Operating system

```
Linux solus 5.5.7-150.current #1 SMP PREEMPT Wed Mar 4 03:31:00 UTC 2020 x86_64 GNU/Linux
```

## Steps to reproduce the issue

Dunno.

## Actual result

Nothing happens.

## Expected result

Restarts the device.

**Comment by szmarczak** [comment]
Shutdown doesn't do anything either

**Comment by szmarczak** [comment]
I also noticed that the `gnome-terminal` won't run:

```
$ gnome-terminal
# _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Unit gnome-terminal-server.service not found.
```

**Comment by szmarczak** [comment]
```
$ shutdown
shutdown: error while loading shared libraries: libsystemd-shared-244.so: cannot open shared object file: No such file or directory
```

**Comment by szmarczak** [comment]
```
szm@solus ~ $ reboot
reboot: error while loading shared libraries: libsystemd-shared-244.so: cannot open shared object file: No such file or directory
szm@solus ~ $ sudo reboot
Password: 
reboot: error while loading shared libraries: libsystemd-shared-244.so: cannot open shared object file: No such file or directory
```

**Comment by EbonJaeger** [comment]
When was the last time you updated? If you only now just updated to systemd 244, see this blog post, especially the update instructions in the systemd section: https://getsol.us/2020/01/17/new-updates-for-a-new-decade/

**Comment by szmarczak** [comment]
A few days ago I think

**Comment by JoshStrobl** [comment]
Yea, you 100% need to update and reboot manually per @EbonJaeger's comment.

**Comment by szmarczak** [comment]
I was running the most recent version of Solus (4.1) as of this week 100%

**Comment by szmarczak** [comment]
Solus won't boot:

![image](https://user-images.githubusercontent.com/36894700/77088100-3a5fed00-6a04-11ea-9f4c-72cc53e4e31f.png)

**Comment by szmarczak** [comment]
Today I just installed https://github.com/flightlessmango/MangoHud (built manually) - but I don't think that would cause the problem.

**Comment by szmarczak** [comment]
Can I restore Solus root filesystem somehow?

**Comment by szmarczak** [comment]
Indeed, it was caused by MangoHud: https://github.com/flightlessmango/MangoHud/issues/91
