### ISSUE TITLE
Feature request: Make virtual workspace work without any applet (integrate it with system)

### ISSUE THREAD

**Issue by gitSaptarshi** [solus-project/budgie-desktop#1953]
### Current Budgie version
**Budgie Version**:  budgie-desktop 10.5.1
### Advantages
 1. Virtual workspace without an applet will not create problems for other applets as it will be a part of system itself.
 2. An applet may crash. So a virtual workspace system without an applet will most likely not be crashed.
 3. As it is part of system it will not consume extra resources.
 3. It makes the desktop looks more _clean, simple to use and appealing_ to new users and advance users will also appreciate it.
 4. Current virtual workspace implementation through applet is not that appealing to use which goes against the simple and useful usability of budgie desktop as _most first time users can't find how to use virtual workspaces out of the box in Solus budgie_. 
> Integrating virtual workspace with system (without any applet) and some workspace specific keyboard shortcuts shall make a world of difference.
### Proposal
 I would like to see the implementation of virtual workspace like **elementary os** does. The current workspace implementation of gnome is *meh!!* where elementary's implementation is *woo!!*, which makes total sense. I would like to evaluate some key points below:
- [ ] Make a horizontal workspace.
- [ ] Assign keyboard shortcuts  for opening/closing, switching, moving application between workspaces (which can be done through `Keyboard Shortcuts` option in Gnome Settings).
- [ ] Invoking virtual workspace show all the windows (including minimized ones).
- [ ] Drag n drop support for windows through workspaces.
- [ ] When a minimized window is transferred to another workspace the window should stay minimized.
- [ ] Option to edit workspace names.
- [ ] Add dedicated buttons for creating and deleting workspaces.
- [ ] Add swipe gestures to navigate through workspaces.
- [ ] Static and dynamic workspaces option.
- [ ] Add some nice animations (effects) into it.
- [ ] Add a specific workspace related tab in Budgie Desktop Settings application.

**Comment by JoshStrobl** [comment]
We already have keyboard shortcuts for switching to different workspaces, you can move windows to another workspace without an applet (right click on a window and there is moev to another workspace option).

Other features for workspaces aren't going to see implementation until Budgie 11, which is going to use a different issue tracker and a completely different codebase. As such, closing this.
