### ISSUE TITLE
tooltips over system tray icons appearing off the screen

### ISSUE THREAD

**Issue by brandum** [solus-project/budgie-desktop#1954]
## Description

tooltips over system tray icons appearing off the screen

related to issue #1809 (and posted a comment there) but the difference is my issue is about the system tray icons, not app icons in a dock

## Budgie version

Budgie (git-4f20f7f9f1d20b9d2e99a 

## Operating system

Solus 4.1

## Steps to reproduce the issue

Install Solus 4.1
Hover the mouse over either the Notifications icon or the Wifi icon
(other system tray icons seem to be unaffected)

## Actual result

![1_bad](https://user-images.githubusercontent.com/47691573/77828858-522f2380-711e-11ea-8ce6-7feaebf27e69.png)

![2_bad](https://user-images.githubusercontent.com/47691573/77828862-578c6e00-711e-11ea-8c5f-01d8e80eb424.png)

## Expected result
The tooltips should appear above the panel

## Additional information

If the panel is moved to the top everything's fine:
![2_good](https://user-images.githubusercontent.com/47691573/77828879-6f63f200-711e-11ea-9685-42ba3221c166.png)

**Comment by kp2401075** [comment]
Having same issue as well.

**Comment by dancespiele** [comment]
I have the same issue and in addition I cannot see Icon of the app that is running in background like Discord or Skype

**Comment by davRX** [comment]
Same issue on Manjaro-Budgie, only when "hide panel" is set on "never"; works fine when it is set on "automaticaly" or "intelligent"

**Comment by serebit** [comment]
This appears to be an issue with GTK and not with Budgie. Please give your input on the relevant issue here: https://gitlab.gnome.org/GNOME/gtk/-/issues/2784
