### ISSUE TITLE
Icon Task List distinguish between favourites and other running applications

### ISSUE THREAD

**Issue by zilexa** [solus-project/budgie-desktop#1959]
### Use-cases
When using Icon Task List, you can mark apps as favourite and it becomes your go-to area to launch your favourite apps and see which apps are running. However, running apps that are not a favourite, also appear on this list without any spacer or seperator, which makes it look cluttered. 
For the user to distinguish between her pinned/fixed/favourite applications (running or not) and running non-favourite applications, this feature request has 2 proposals. 

### Proposal
Option 1: The ability to add a separator within Icon Task List. 
Option 2: A setting for Icon Task List to only show non-favourites.
either a seperator within the Icon Task List needs to be possible (currently not possible) OR the user could use 2 instances of Icon Task List with a Panel seperator between: one with the favourite applications, one without any favourite applications. This last one should be limited to only show non-favourite applications, otherwise when you start a fav app, it will also appear on the second instance.

### References
MacOS does something similar with a seperator at the end of the dock, running apps appear next to it. Some Dock alternatives allow for separators between apps. 

### Workaround
create a separator.desktop file and try to create an .svg image with a line that looks like the separator applet. Add this to the Icon Task List as an app. Downside: this is not easy and it will behave as app (it is clickable). A preview of my attempt (below the Firefox icon) attached. The line is unfortunately appearing at the top of its area although the .svg clearly shows it in the middle. 
https://ibb.co/bN5WKhw

**Comment by Coeur-Noir** [comment]
I don't mind having non-favorited app icons aligned with favorites ones, but I do like the idea of separate / many instances of icon-tasks-list, with different modes.
1⋅ favorites and running ( as we already enjoy )
2⋅ running but only non-favorites ( your idea )
and I'd add another
3⋅ dynamic = configurable number of frequently used app's which are non-favorites ( exclude what's already in 1⋅ )

Why such a dynamic mode ?
Because there is not really a place for recent/frequent « things » in Budgie.
We could even imagine such dynamic icon-task-lists may apply to frequently used files or places…
This way a panel could automatically reflect user's activities.

**Comment by JoshStrobl** [comment]
While I appreciate the feature request, I don't wish to add this as I'm satisfied with the current design implementation of the IconTasklist and have concerns over feature bloat.

**Comment by zilexa** [comment]
The options for configuring are extremely limited. You are literally on the other side of the scale when it comes to feature bloat..

**Comment by JoshStrobl** [comment]
You and I clearly have different opinions on it. We have window group toggling, workspace restriction, locking, only showing favorites, two different ways to launch a window, and an option to show all windows on click. That's enough for now. When I merge Tasklist and IconTasklist, I may consider other items.

**Comment by zilexa** [comment]
Please allow me one more comment, as I do agree with you, it should not get overcomplicated and there should not be lots of options to tweak. It should remain simple and work as is with toggles for things that make absolutely sense.

No need to discuss further, but I do believe Coeur-Noir made this request more complicated than necessary. All I was going for was the reverse of the existing option `only show favourites`. Nothing more.
