### ISSUE TITLE
App Menu Flashes At Top Left

### ISSUE THREAD

**Issue by hemjaj** [solus-project/budgie-desktop#196]
On Arch Linux, when the application window is opened, the window is initially displayed in the top-left hand corner of the screen for ~200 ms before it is repositioned in the correct location.  The applet menu (volume, settings, user dialog) has the same behavior.

It wasn't until my most recent system upgrade that this repositioning was visible, I have only tested this with a single-monitor setup.

```
budgie-desktop-git v8.1.r96.gf9e43fd-1
gtk3 3.16.2-1
glib2 2.44.0-1
vala 0.28.0-1
xorg-server 1.17.1-5
linux 4.0.1-1
```

**Comment by ikeydoherty** [comment]
Also happening here. Currently investigating, but I know I introduced that with the recent popover changes

**Comment by ikeydoherty** [comment]
Should be fixed - please confirm

**Comment by ikeydoherty** [comment]
Hmm this introduces another problem. Menu position never changes now..

**Comment by ikeydoherty** [comment]
There we go - much better.

**Comment by hemjaj** [comment]
Solid.  Looks good using ```budgie-desktop-git v8.1.r100.gb36e9e9-1```.

Thanks!

**Comment by ikeydoherty** [comment]
Cheers :D
