### ISSUE TITLE
Budgie crashes on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by MasterGeekMX** [solus-project/budgie-desktop#1960]
## Description

Beforehand sorry if I revive and old issue, but I haven't found a similar issue beforehand.

I'm trying to get Budgie up and running in an openSUSE tumbleweed installation. There is no current package or packages on the default repos, but there are some in other repos, like the [X11:Solus ](http://download.opensuse.org/repositories/X11:/Solus/) one, or some other [community ones](https://software.opensuse.org/package/budgie-desktop). All of them either crash or have a dependency issue. So I tried to tackle this by my own and cloned this repo and build it myself. Same issues.

## Budgie version

10.5.1 (commit [b4cc35c4586ae39cfd26dfd1e49b3d2f5f58bb81](https://github.com/solus-project/budgie-desktop/commit/b4cc35c4586ae39cfd26dfd1e49b3d2f5f58bb81))

## Operating system

openSUSE Tumbleweed 20200411

## Steps to reproduce the issue

1. Install budgie via either the experimental release or by cloning the repo and compiling it
2. launch the desktop via a display manager (Lightdm, GDM3)

## Actual result

The screen freezes by a second, then the gnome-shell appears to come, and then it fails with a screen sayingg that a unrecoverable system crash occurred and prompts to go batck to the display manager

![imagen](https://user-images.githubusercontent.com/10291989/79407753-6452f380-7f5f-11ea-9437-1acf6abf9fbb.png)

## Expected result
Budgie desktop should apper and run

## Additional information
running journalctl reveals a potential helpful info:

`budgie-wm[3000]: Falied to start XWayland: Failed to acquire window manager ownership

gnome-session-binary[2660]: Unrecoverable failure in required component budgie-wm.desktop

gnome-session-binary[2660]: Unrecoverable failure in required component budgie-polkit.desktop
`

**Comment by JoshStrobl** [comment]
> `budgie-wm[3000]: Falied to start XWayland: Failed to acquire window manager ownership

We don't support Wayland. Please ensure your entire graphics stack (including GDM) is using X11. I would also double check that you're using the correct / supported gnome-session-daemon release. This sort of issue is indicative of incorrect schemes, unsupported configurations, or incorrect compilations of Budgie.
