### ISSUE TITLE
Some non-translation errors (in French)

### ISSUE THREAD

**Issue by roxfr** [solus-project/budgie-desktop#1962]
Hi,
I spotted some non-translation errors (in French).
See images below.
Regards,
roxfr

PS : 
System is Solus OS Budgie 4.1
Weblate Solus is at 100% translate in french.

- Menu :

<a href="https://zupimages.net/viewer.php?id=20/17/rmgn.png"><img src="https://zupimages.net/up/20/17/rmgn.png" alt="" /></a>

- Task bar :

<a href="https://zupimages.net/viewer.php?id=20/17/xdj9.png"><img src="https://zupimages.net/up/20/17/xdj9.png" alt="" /></a>

- File manager :

<a href="https://zupimages.net/viewer.php?id=20/17/hxx4.png"><img src="https://zupimages.net/up/20/17/hxx4.png" alt="" /></a>

- Software manager :

<a href="https://zupimages.net/viewer.php?id=20/17/1x07.png"><img src="https://zupimages.net/up/20/17/1x07.png" alt="" /></a>

<a href="https://zupimages.net/viewer.php?id=20/17/t3q0.png"><img src="https://zupimages.net/up/20/17/t3q0.png" alt="" /></a>

<a href="https://zupimages.net/viewer.php?id=20/17/euj3.png"><img src="https://zupimages.net/up/20/17/euj3.png" alt="" /></a>

- DoFlicky :

<a href="https://zupimages.net/viewer.php?id=20/17/c1l4.png"><img src="https://zupimages.net/up/20/17/c1l4.png" alt="" /></a>

- Neofetch for informations :

<a href="https://zupimages.net/viewer.php?id=20/17/becv.png"><img src="https://zupimages.net/up/20/17/becv.png" alt="" /></a>

**Comment by EbonJaeger** [comment]
Translations are done at https://translate.getsol.us/
You can make change suggestions there. :)

**Comment by roxfr** [comment]
> 
> 
> Translations are done at https://translate.getsol.us/
> You can make change suggestions there. :)

All strings are translated into Weblate.
The problem comes from elsewhere ?

<a href="https://zupimages.net/viewer.php?id=20/17/iul7.jpg"><img src="https://zupimages.net/up/20/17/iul7.jpg" alt="" /></a>

<a href="https://zupimages.net/viewer.php?id=20/17/hley.jpg"><img src="https://zupimages.net/up/20/17/hley.jpg" alt="" /></a>

**Comment by JoshStrobl** [comment]
The translations are synced up prior to a Budgie release. Thanks for filing the issue but it is something that will naturally resolve itself :)
