### ISSUE TITLE
Enable mouse rolling over categories to open them in 'AppMenu' applet

### ISSUE THREAD

**Issue by JoaoVictorDaijo** [solus-project/budgie-desktop#1963]
### Current Budgie version
10.5.1

### Use-cases
We have the ability to hover the mouse over menus and open them without clicking on the older Budgie Menu applet. This simple feature was very useful to me.

I really love the new AppMenu applet but it lacks this feature.

### Proposal
Please add something similar for the new applet, it would improve it even further for me.

### References
I think this feature for the older applet was added here:
 #https://github.com/solus-project/budgie-desktop/commit/f6b8e2f71557986dde3c32b58f5b35a10e944f59

**Comment by JoshStrobl** [comment]
I have no idea what you're talking about with an AppMenu applet, we provide the Budgie Menu, which has a roll-over functionality.
