### ISSUE TITLE
Unusual high CPU usage. [previews_creator]

### ISSUE THREAD

**Issue by Skarlett** [solus-project/budgie-desktop#1964]
## Description

a child thread of `xorg` (`xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -notswitch`) which appears to be in relation with `previews_creator` and is causing some kind of high CPU usage - the system returned to normal cpu usage after killing `previews_creator`

## Budgie version

budgie-desktop 10.5.1 (git-10b814fa62bf774ca48e182548d3c6687a852314)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system

4.19.118-1-MANJARO #1 SMP x86_64 GNU/Linux

## Steps to reproduce the issue

When booting initially into the system problem occurs

## Actual result

![image](https://user-images.githubusercontent.com/3759687/80861061-bf5c3a00-8c31-11ea-8ed5-d2a32237aa0c.png)

**Comment by MrPaulBlack** [comment]
This is Manjaro specific as far as I know. There is an application on Manjaro budgie preinstalled, which handles the window preview when pressing alt + tab. Disabling preview control with removing the check-mark Run Previews resolves the issue for know. (but there is also no alt tab menu anymore)

**Comment by JoshStrobl** [comment]
This isn't an official applet or part of the official Budgie Desktop experience.

**Comment by direc85** [comment]
This issue is somewhat widespread, it seems. As this issue is closed, but many people will google their way here, [I created a new thread](https://forum.manjaro.org/t/budgie-previews-creator-segfaults-eats-cpu/146280) over at the Manjaro Forum.

Let's hope this gets resolved soon!
