### ISSUE TITLE
Lock/Hibernate/Restart/Shutdown in User Indicator Not Working

### ISSUE THREAD

**Issue by JonathanBelanger** [solus-project/budgie-desktop#1965]
## Description

After upgrading from 18.04 to 19.10, Lock, Hibernate, Restart and Shutdown are not working at all in the User Indicator menu.  Performing multiple selections of any of these items give the same results.  There does not appear to be any errors thrown.

## Budgie version

Budgie-desktop 10.5

## Operating system
```
Linux dads-old-pc 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Steps to reproduce the issue

Click the "User Indicator" applet and choose Lock, Hibernate, Restart or Shutdown.

## Actual result

Nothing happens no matter how many times you click it.

## Expected result

A pop up window showing:
```
 <Lock/Hibernate/Shutdown/Restart> device:
Are you sure you want to ??? your session?
"Cancel" "Restart"
```

## Additional information

If I use the Budgie Menu and select any of these, they all work as expected.

**Comment by JoshStrobl** [comment]
Unable to reproduce under Solus. Please provide logs via `sudo journalctl -f -e | grep 'budgie' | grep -v 'keysym'`

**Comment by JonathanBelanger** [comment]
The latest version no longer has the issue.
