### ISSUE TITLE
Feature Request: Floating panel

### ISSUE THREAD

**Issue by triorr** [solus-project/budgie-desktop#1966]
Instead of having a panel that takes part of your screen , how about just making it float and move it around.
I would love to have this feature as an option that you can turn on and off.

I hacked around and I made it possible with same code modification and some scripts and I got a nice result.
I can see it being the default state of the panel :stuck_out_tongue: .
I will share everything if the idea pick some interest.
![Screenshot_20200504_184520](https://user-images.githubusercontent.com/7348074/81001688-a3c28080-8e37-11ea-88af-e6de5aa2da13.png)

**Comment by JoshStrobl** [comment]
While I appreciate the feature request, I don't consider this to be a desired feature nor one I would want to have to maintain or be concerned with maintaining in the future.
