### ISSUE TITLE
Sort WiFi Networks By Signal Strength

### ISSUE THREAD

**Issue by TheLostLambda** [solus-project/budgie-desktop#1969]
### Current Budgie version
`budgie-desktop 10.5.1`

### Use-cases
I've been testing out a number of distributions lately and is seems that the majority of them sort WiFi networks by signal strength (as opposed to alphabetical as it seems to be in Budgie). Sorting by the signal means that my wireless network nearly always shows up in the first couple of entries, while on Budgie I need to use "More networks" and pick what is usually the last entry in that menu (the tragic side-effect of a network named "WhyPhi?").

### Proposal
I've not taken a look at the code just yet, but when I connect to a network, the notification contains information on the signal strength so I assume this information is also available to the widget? I've not written code for Solus before, but if this is something the Solus / Budgie team is interested in, I could put in a PR.

**Comment by JoshStrobl** [comment]
The applet you are referring to is nm-applet developed by GNOME. I'd suggest you file your request there as it isn't specific to Budgie: https://gitlab.gnome.org/GNOME/network-manager-applet

If you are not using nm-applet, you are using a non-standard and unofficial applet that also isn't developed by us.

**Comment by TheLostLambda** [comment]
Good call, I managed to miss that. Thanks for the link!
