### ISSUE TITLE
Theme Text White on White

### ISSUE THREAD

**Issue by hemjaj** [solus-project/budgie-desktop#197]
On Arch Linux, when 'GNOME Panel Theme Integration' is OFF, the text of the application menu and applet menu is not readable.  The text color is white and the background is light-grey.  I am using the default Adwaita theme.

I had not noticed this functionality in prior versions (however I typically do run with the theme integration on).

```
budgie-desktop-git v8.1.r96.gf9e43fd-1
gtk3 3.16.2-1
glib2 2.44.0-1
vala 0.28.0-1
gnome-themes-standard 3.16.0-1
```
![budgie-theme](https://cloud.githubusercontent.com/assets/12286128/7508164/8f904488-f438-11e4-8310-5e5fb6746722.png)

**Comment by ikeydoherty** [comment]
Should be resolved - please confirm

**Comment by hemjaj** [comment]
Verified that this issue has been fixed in version:
`budgie-desktop-git v8.1.r98.ga843ca5-1`

Thanks!

**Comment by ikeydoherty** [comment]
Cheers :D
