### ISSUE TITLE
Icons disappear from the system tray and does not respond in Budgie

### ISSUE THREAD

**Issue by JeffLabonte** [solus-project/budgie-desktop#1973]
## Description
Hello everyone,

I have asked for help in the support chat, but I believe this is a bug. When I change the resolution of my 2 screens and then change the position of one my screen, it makes the nm-applet system tray application to crash for some reasons.

See the images below:

https://imgur.com/a/5QxenVF

If anyone know how I could find logs about this piece of software, I would be pleased to give them to you guys!

## Budgie version

budgie-desktop 10.5.1 (git-6f60f10bb03b4779379d9e8ce3681d93a3f17e48)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system

Solus 4.1

## Steps to reproduce the issue

Unplug and plug a second display to budgie and change the resolution (4k to 1080p) and change position of screens.

```bash
#!/bin/bash
xrandr --output eDP1 --mode 1920x1080

xrandr --output HDMI1 --mode 1920x1080 --left-of eDP1
```
## Actual result

https://imgur.com/a/5QxenVF

## Expected result

System tray application of nm-applet still responding and showing in the bar.

## Additional information

It happens also when my PC is locked for a long time (~8 hours)

I have noticed the same problem with Slack. Removing and adding back system tray seems to fix the issue, unless I move it to the right. I have no clue why.

**Comment by JeffLabonte** [comment]
Moving the system-tray in the middle of the bar seem to fix the issue. Would the bar position have an effect on the issue? Cause mine isn't at the bottom just like it is by default!

**Comment by JoshStrobl** [comment]
General system tray issues such as failure for background refreshes are already reported at #1249.
