### ISSUE TITLE
Budgie Bluetooth mouse speed 4k vs 1080p

### ISSUE THREAD

**Issue by JeffLabonte** [solus-project/budgie-desktop#1974]
## Description

Hi there,

It seems that there is a small bug in the code for handling the mouse with Budgie. If my computer uses the 4k resolution, the mouse is too slow. If I switch my screen to 1080p, the mouse speed is perfect.

It feels like the moves from the mouse are calculated using the pixels instead of a percentage of my screen pixels!

I would like to help you guys fix this issue!

Thank you guys!

## Budgie version

budgie-desktop 10.5.1 (git-6f60f10bb03b4779379d9e8ce3681d93a3f17e48)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system

Solus 4.1

## Steps to reproduce the issue

Run Budgie with a bluetooth mouse and a 4k screen

## Actual result

The mouse move way slower than on 1080p without changing mouse acceleration or speed in any way

## Expected result

Same speed on any resolution.

**Comment by JoshStrobl** [comment]
If there is an issue with this, it'll be in a different part of the stack than Budgie, such as Mutter or libinput.
