### ISSUE TITLE
Left justified Applets may be cut off by the center panel position

### ISSUE THREAD

**Issue by rbreaves** [solus-project/budgie-desktop#1976]
## Description
Certain extensions may become cut off unnecessarily if it extends into the center. Example is the Global Menu extension and certain apps.

Issue is also documented here. https://discourse.ubuntubudgie.org/t/global-menu-is-getting-cut-out/1236

![image](https://user-images.githubusercontent.com/10969616/82006033-80b08180-962c-11ea-8a45-a9e6e50b6146.png)

## Budgie version
10.5.1

## Operating system
Solus 4.1 & Ubuntu Budgie 20.04

## Steps to reproduce the issue
Install Global Menu or any extension that may extend out to the center, or combination thereof.

## Actual result
The center position reserved for a centered applets cuts into the left aligned applets if they extend into the center, even when no center applet is set.

## Expected result
Left justified Applets are allowed to take up all the space up until the right side applets begin.

<img width="1097" alt="Screen Shot 2020-05-14 at 10 24 35 PM" src="https://user-images.githubusercontent.com/10969616/82008244-befc6f80-9631-11ea-834e-0b984d424453.png">

## Additional information
Not fully related, but a workaround for some reason, although not a very good one.
https://discourse.ubuntubudgie.org/t/expand-option-in-global-menu-applet-settings/49/8

Can also see an example of a version of the panel working without any center at all in my own fork, but no time has been spent on trying to keep the center, if an applet is defined for the center. https://github.com/rbreaves/budgie-desktop/commit/38ddd08ccf73f5b646b7b1e178af426f1f5c48fa

**Comment by rbreaves** [comment]
For anyone that wants to compile the above

https://discourse.ubuntubudgie.org/t/how-to-hack-the-budgie-desktop-on-ubuntu/574

```
mkdir -p build
cd build
meson setup --wipe .. && meson --buildtype plain --prefix=/usr --libdir=/usr/lib --sysconfdir=/etc ..
sudo ninja install &&  sudo ninja install
budgie-panel --replace &
```

**Comment by rbreaves** [comment]
May be good change the Z order between the left and right panels and allow the left panel to take priority over the right if the two collide temporarily. (or trigger something to autohide some of the right side applets in the manner that the Dozer app does for macOS)

https://github.com/Mortennn/Dozer

**Comment by Coeur-Noir** [comment]
On Ubuntu Budgie 20.04, if there is no applet in center panel, then global menu uses the whole space even when left aligned. No longer truncated at the center.

That was not true in UB19.10 so something has been fixed there - I guess in global-menu-applet, which is part of the things UBudgie team maintains on its own side ( @fossfreedom, confirm ? ).

Behavior of the different sections of the panel may be another issue, for upstream indeed.

**Comment by rbreaves** [comment]
@Coeur-Noir I updated the actual result area as it was not clear, I just repeated what needed to happen apparently. A center applet does not need to be set in 20.04 for the center position to still be reserved for one and apparently cut off the text of a left aligned applet, that is the issue.

**Comment by rbreaves** [comment]
This issue is actually solved on the Ubuntu Budgie fork of this project, so I presume their submission for a merge on the main branch was already rejected due to it being seen as something that just relates the global menu plugin and not a problem in general.

I will be closing this ticket pre-emptively since I do not think this is an issue the maintainers will be fixing in the main branch.
