### ISSUE TITLE
Renewed Interest in Bringing in Blur?

### ISSUE THREAD

**Issue by rbreaves** [solus-project/budgie-desktop#1977]
### Current Budgie version
10.5.1

### Use-cases
Allows for blur throughout the DE?

### Proposal
Rebase Budgie on mutter 3.36+? Am I missing something or might this be a possible ticket item to tackle with what all else is going on, despite the shift away from the 10.5 code base?

### References

```
- Adding a new Blur shader to the Shell. 
```

Mutter 3.36+? (Appears to have blur built in)
https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.35.90-Mutter-Shell

```
I am using budgie desktop on 19.10 ubuntu eoan that is currently compiled with v3.33.91 mutter.
Budgie Desktop is essentially a mutter plugin.
```
- David Mohammad

https://gitlab.gnome.org/GNOME/mutter/issues/751

**Comment by JoshStrobl** [comment]
No, there are no plans or desire at the moment to introduce additional functionality related to the window manager that I don't want to fully commit to for Budgie 11. In terms of support, Budgie 10 already supports the Mutter ABIs in 3.36.
