### ISSUE TITLE
GNOME Applications Hidden

### ISSUE THREAD

**Issue by hemjaj** [solus-project/budgie-desktop#198]
On Arch Linux, the default settings result in the Application Menu hiding GNOME application launchers (such as Settings, Tweak Tool, etc).

I was able to resolve this issue by adding the following code block to my ~/.xprofile:

```bash
# Budige is not displaying GNOME only apps...
if [ "${XDG_CURRENT_DESKTOP}" = "Budgie:GNOME" ]; then
  XDG_CURRENT_DESKTOP="GNOME"
  export XDG_CURRENT_DESKTOP
fi
```

It seems that the XDG menu interface should understand that 'Budgie:GNOME' includes GNOME applications, so it may not explicitly be a Budgie bug, but the current state seems to require 'XDG_CURRENT_DESKTOP' to be explicitly 'GNOME'.

**Comment by hemjaj** [comment]
Version information that was overlooked above:

```
budgie-desktop-git v8.1.r96.gf9e43fd-1
gnome-menus 3.13.3-1
xdg-utils 1.1.0.git20150323-1
```

**Comment by ikeydoherty** [comment]
You'll notice Budgie tries to accommodate this:
```
        if (Environment.get_variable("XDG_CURRENT_DESKTOP") == null) {
            Environment.set_variable("XDG_CURRENT_DESKTOP", "GNOME", true);
        }
```

When XDG_CURRENT_DESKTOP isn't set, it will force it to be GNOME.

The budgie-desktop session file (.desktop.in) specifically sets the session (for supporting display managers..) to:
```
DesktopNames=Budgie;GNOME
```

Note that it is a colon, not a semicolon. I think that's more likely the issue. What DM are you using? And could you try making it "Budgie;GNOME" in your `.xprofile`?

**Comment by hemjaj** [comment]
I am using lightdm:
```lightdm 1:1.14.0-2```

Per your suggestion, I modified my ```.xprofile``` to set ```XDG_CURRENT_DESKTOP``` to ```Budgie;GNOME```, but this change did not cause the expected GNOME-only desktop launchers to be displayed in the menu (I do think that ':' should be the valid delimiter).

As a quick test, I started budgie via a simple ```startx``` command (```.xinitrc``` calls ```exec budgie-session```), as expected ```XDG_CURRENT_DESKTOP``` is simply set to ```GNOME``` and all works as expected.

Looking into the lightdm code, the budgie-desktop.desktop declaration of ```DesktopNames=Budgie;GNOME``` does cause ```XDG_CURRENT_DESKTOP``` to be set to ```Budgie:GNOME``` (with a colon).  If interested, the files are ```session-config.c``` (line 57) and ```seat.c``` (line 990-997).

I do think this is a valid definition (that is, it should indicate to the menu system that _both_ Budgie _and_ GNOME specific desktop files should be displayed).  To back that up, it seems that gnome-menus should support multiple desktops delimited by a ':' (based on this commit https://mail.gnome.org/archives/commits-list/2014-November/msg00267.html), so I am a bit stumped.

I haven't looked into gdm to see how it would handle setting ```XDG_CURRENT_DESKTOP``` when multiple desktops are defined by the ```DesktopNames``` entry, but I would guess it handles it the same way.  My guess is that this somehow falls out as a bug in the gnome-menus library, but I have not had the time to flush that out.

Annoyingly, my Settings desktop (```gnome-control-center.desktop```) defines ```OnlyShowIn=GNOME;Unity;``` and my Tweaks desktop (```gnome-tweak-tool.desktop```) defines ```OnlyShowIn=GNOME;Unity;Pantheon;```. (That is, they call out other non-GNOME desktops by name -- probably as a workaround to the same root issue.)

In looking around, I did come upon #155; which suggested to just set ```DesktopNames=GNOME``` as a workaround to basically the same issue (this looks like it was prior to budgie-desktop.desktop presetting a value). 

It may be of use to revert to only using ```DesktopNames=GNOME``` unless there is another functional reason that this is not valid (or if everything just works for other desktop-managers like gdm). This will only be a problem if Budgie begins to get its own custom applications that define ```OnlyShowIn=Budgie``` (however, my setup seems to indicate that right now even these Budgie specific desktop files would not be displayed when ```XDG_CURRENT_DESKTOP``` defines multiple desktop entries).

I will continue to utilize my work-around (the ```.xprofile``` modification) as it does not require me to patch any source packages at this time.

**Comment by hemjaj** [comment]
I did notice that ```budgie-settings.desktop``` defines ```OnlyShowIn=Budgie;GNOME;```.  I guess that a solid solution that allows ```XDG_CURRENT_DESKTOP``` to properly be ```Bugdie:GNOME``` would allow you to redefine that line to ```OnlyShowIn=Budgie;``` (which would probably be more accurate).

Point being, looks like there is already a use-case for desktop files that are Budgie specific (contrary to my point above); which would lend itself to finding a more complete solution to this issue.

**Comment by ikeydoherty** [comment]
Fixed in v10
