### ISSUE TITLE
DConf of /budgie-panel/panels/{ ... only panel ... }/applets shows cryptic values

### ISSUE THREAD

**Issue by beepbleep** [solus-project/budgie-desktop#1980]
## Description
After full re-installation of budgie-desktop the custom values in dconf-editor (that represent shortcuts on the panel that were recognizable by names such as "some-application.desktop") have been replaced by strings:

`['4a7eff38-9bf9-11ea-a6e0-902b34d787a4', '4a7ac026-9bf9-11ea-a6e0-902b34d787a4', '4aa81a4e-9bf9-11ea-a6e0-902b34d787a4', '4a9f1c00-9bf9-11ea-a6e0-902b34d787a4', '4aa51ca4-9bf9-11ea-a6e0-902b34d787a4', '4a9f0ab2-9bf9-11ea-a6e0-902b34d787a4', '4aa70500-9bf9-11ea-a6e0-902b34d787a4', '4a7eca4a-9bf9-11ea-a6e0-902b34d787a4', '4aa67d06-9bf9-11ea-a6e0-902b34d787a4', '4aa71928-9bf9-11ea-a6e0-902b34d787a4', '4aa75082-9bf9-11ea-a6e0-902b34d787a4', '4aa0a660-9bf9-11ea-a6e0-902b34d787a4']`

## Budgie version
budgie-desktop 10.5

## Operating system
Debian 10

## Steps to reproduce the issue
sudo apt install --reinstall budgie-*

## Actual result
![dconf](https://user-images.githubusercontent.com/56007385/82643189-66b80580-9c0f-11ea-89b6-621d709d2cb0.png)

## Expected result
DConf Editor showing an array of quoted names of .desktop launchers. Then I simply add a properly created .desktop file to the array.

## Additional information
I did, however, run "sudo apt install --reinstall budgie-*" glob actually, but my humble opinion is that it has not caused this behavior. I simply want to add some launchers to the panel that do not show a "star" that pins the application as I have done before this issue. But I don't have a clue what those custom values actually represent now and would like to get back the old "quoted .desktop launchers" array inside the dconf-editor.

**Comment by JoshStrobl** [comment]
The applets is a list of UUIDs to references to applets and their configurations. What your referencing was never in "applets", it is in the IconTaskList configuration, by its UUID reference. You can see it via com.solus-project.budgie-panel.instance.icon-tasklist and the UUID.
