### ISSUE TITLE
Deleting a panel should be obviously different than deleting an applet

### ISSUE THREAD

**Issue by yacn** [solus-project/budgie-desktop#1981]
### Current Budgie version

budgie-desktop 10.5.1 (git-bc1f87765258a2b716a2627c613552497f5240f1)

### Use-cases

While customizing a panel, the add-applet button is right under the delete-panel button.

The pop-up confirmation screen for deleting an applet vs deleting a panel are identical save for `s/applet/panel/`. 

This has lead to me deleting the panel I was customizing instead of the applet I had selected more than once because without thinking I clicked the closest delete button and confirmed the dialog, leading to a frustrating experience. 

### Proposal

A few different ideas:

* change the delete-panel icon to something different than the delete-applet or vice-versa. (maybe one of those circles with a horizontal line, idk)
* move the delete-panel icon to the left side so it's not right under the add-applet panel
* have a restore-panel option where you can restore the most recently deleted panel if one hasn't taken its space yet.

**Comment by Mpc46** [comment]
Agree, I ended up always deleting the panel while trying to remove an applet, is rather annoying :T
