### ISSUE TITLE
Alt Tab Goofiness

### ISSUE THREAD

**Issue by hemjaj** [solus-project/budgie-desktop#199]
On Arch Linux...

Typically Alt-Tab will move through the application-windows in the order that they are displayed in the panel.. typically.

I have noticed that Alt-Tab will occasionally skip over an application -- I don't see any pattern to which application would be skipped, but it seems that once it is skipped it is more likely to be skipped again if you continue to move through the windows using Alt-Tab.

At other times, the Alt-Tab iteration order seems totally arbitrary, that is it will move seemingly randomly from one application window to another in no observable order -- however, that order does seem to repeat if you continue to move through the windows using Alt-Tab.

```
budgie-desktop-git v8.1.r100.gb36e9e9-1
clutter 1.22.0-2
clutter-gtk 1.6.0-2
mutter 3.16.1.1-1
glib2 2.44.0-1
gtk3 3.16.2-1
```

**Comment by ikeydoherty** [comment]
Polite way of putting it :) We need a graphical switcher here too, but I suck with Clutter so Ima need some help with people. And yes, the "order" drives one insane..

**Comment by grvrulz** [comment]
Can we mayeb `steal` stuff from here https://github.com/tom95/gala-alternate-alt-tab ??

**Comment by ikeydoherty** [comment]
@grvrulz can't - its GPLv3 :(

**Comment by paapereira** [comment]
Yeah, a graphical switcher is a must. Was switching from Gnome Shell to Budgie, but gave up.
Little nuisance yes, but was driving me insane :)

**Comment by mehdip2007** [comment]
@ikeydoherty since it uses gnome component, would it not be possible to use gnome alt-tab system?

**Comment by ikeydoherty** [comment]
@mehdip2007 that's in gnome-shell, we don't use gnome-shell :)

**Comment by mehdip2007** [comment]
so there is no possible way to use a alt-tab alternative?

**Comment by ikeydoherty** [comment]
We have to implement one

**Comment by adamjameschristensen** [comment]
Just wanted to say the random alt+tab behaviour is still occurring. Using latest budgie from community/testing on Arch Linux.

**Comment by mehdip2007** [comment]
The implementation is not done yet that's why it exist give it a time ;)
I'm sure it will turn into something coo

**Comment by szjanos** [comment]
Hi!
I am missing this feature a lot as well! :)

**Comment by rmlopes** [comment]
I did not know you were not using gnome-shell. Just spent a lot of time trying to get the gnome-shell and its extensions working in arch. Some do, but none of the alternate-tab alternatives do.

Should have come here sooner....

**Comment by GAZ082** [comment]
This is a pain in where you know...

**Comment by ikeydoherty** [comment]
OK people *please* stop necromancing the issues, I know it's a problem, it's on the TODO list. Really doesn't help "oh me too"'ing everything...

Now closing this. It's being tracked in the TODO.
