### ISSUE TITLE
Desktop "Home, trash and mounted volumes" icons don't work unless the file manager is already open

### ISSUE THREAD

**Issue by ekhalkov** [solus-project/budgie-desktop#1994]
Hello,

Desktop "Home, trash and mounted volumes" icons don't work unless the file manager is already open. Nothing happens when double-clicked.

**Comment by JoshStrobl** [comment]
Desktop Icons rely on an old release of Nautilus at this moment. Given desktop icons support are removed in newer releases and this is a bug specific to Nautilus and not Budgie itself, closing as invslid.

**Comment by ekhalkov** [comment]
Hello Josh,
Is there a way to make it work with another file manager? say Caja?

**Comment by JoshStrobl** [comment]
We only officially support the legacy desktop icons implementation. I will be introducing a more focused native implementation for Budgie in the upcoming point release.

**Comment by ekhalkov** [comment]
Thank you, Josh. I will be looking forward to the new update/release. I have recently discovered Solus as a stability-oriented rolling release. I've immediately liked the idea and switched all my Linux-only-household computers to Solus. Very quickly I fell in love with Budgies' simplicity, practicality, and of course the looks... Love what you guys are doing!
For the moment, the issue with desktop icons and the issue with the fact that it is impossible to drag and drop files into the **icon task list at the panel** to attach them to emails are two major concerns.
Once again, thank you very much, keep up the good work!
