### ISSUE TITLE
[i18n] Impossible to add Occitan to weblate

### ISSUE THREAD

**Issue by Mejans** [solus-project/budgie-desktop#1997]
Hello,

I would like to translate both Brisk and Budgie desktop into Occitan but at the momet this language is not enabled on your weblate. Could you add it so I can strart the translation?
Best regards

**Comment by JoshStrobl** [comment]
Please use the contact link at the bottom of the Weblate for this request. Thanks

**Comment by Mejans** [comment]
Hello @JoshStrobl done so :) How have I got to wait after this?
