### ISSUE TITLE
Missing GPL license/copyright in source files

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#2001]
I've run the usual debian copyright checks over the latest git master source files.  It threw up the following source files that did not include the usual source copyright headers.

Specifically I was looking at the carbontray sources that mentioned na_tray, xfce and mate.  Should those source files have the copyright headers (GPL/Authors) from those sources included?

The following paths are missing information:
- src/applets/caffeine/CaffeineSettings.vala: missing copyright and license
- src/applets/caffeine/CaffeineWindow.vala: missing copyright and license
- src/applets/tray/carbontray/child.c: missing copyright and license
- src/applets/tray/carbontray/child.h: missing copyright and license
- src/applets/tray/carbontray/tray.c: missing copyright
- src/applets/tray/carbontray/tray.h: missing copyright and license
- subprojects/gvc/test-audio-device-selection.c: missing copyright and license
- subprojects/gvc/tests-include/config.h: missing copyright and license

**Comment by serebit** [comment]
For carbontray: None of the code is directly copied from xfce4-panel or na-tray, so I (personally, as the author of the code) believe attribution is sufficient. However, you're right that child.* and tray.* should contain the usual copyright headers, and that's my mistake.

**Comment by serebit** [comment]
Fixed in carbontray sources as of #2002.

**Comment by JoshStrobl** [comment]
> subprojects/gvc/

This needs to be handled by that upstream, we're just using their git repo as a submodule.
