### ISSUE TITLE
"Show desktop" applet

### ISSUE THREAD

**Issue by LouisDK1** [solus-project/budgie-desktop#201]
Hi,

I find the Budgie desktop to be very interesting.
It would be very great with a "Show desktop" applet that can be added to the panel.

**Comment by ikeydoherty** [comment]
Click or hover?

**Comment by LouisDK1** [comment]
I would prefer a clickable one.

**Comment by ikeydoherty** [comment]
Ok the initial applet is in now - could you test it works as expected, and then we can discuss styling changes? (Right now its just a button with a desktop icon)

Thanks!

**Comment by LouisDK1** [comment]
Thanks a lot!
It works as expected, however it has a grey frame on it, which become draker when using the dark theme. 
![showdesktop](https://cloud.githubusercontent.com/assets/4969294/7544285/f2fe2b40-f5cb-11e4-930d-ae552d86e783.png)

Would you be able to make the sounding area transparent like on the other icons?

**Comment by ikeydoherty** [comment]
Done :) Closing - reopen if you need any other fixes to it.
