### ISSUE TITLE
Laradock :: App-Armour :: conflict with syslogd-ng

### ISSUE THREAD

**Issue by xerocole** [solus-project/budgie-desktop#2013]
## Description
App-Armour syslogd-ng profile is killing a docker-container. Very specific type of container none the less. Disabling it fixes the problem but probably not the best work-around considering App-Armour is a good thing to have.

## Budgie version
budgie-desktop 10.5.1 (git-42201c183fccd7d65f143f8f6bb70bcf3bcaffd8)

## Operating system
Solus 4.1

## Steps to reproduce the issue
install git, docker and docker-compose ```sudo eopkg install git docker docker-compose```
add user to docker group ```sudo usermod -aG docker $USER```
clone laradock ```git clone https://github.com/laradock/laradock.git ```
run laradock ```cd laradock & docker-compose up -d```
wait for all containers to download and run
enter into workspace container ```docker compose exec --user=laradock workspace bash```

## Actual result
the container run as they should, but the workspace exits with an error in a few seconds. 

## Expected result
the bash container should stay up permanently

## Additional information
There was an error about dmesg('unix') not having sufficient permission or not found. Once I disable the syslogd-ng app-armour profile everything works as it should.

I am not sure what the issue is since I am not an app-armour expert, but do not it is not ideal to have app-armour profiles turned off. I have tested on Fedora, Ubuntu, and OpenSuse and could not replicate this issue.

**Comment by JoshStrobl** [comment]
This has nothing to do with Budgie.

**Comment by xerocole** [comment]
@JoshStrobl - fair but where can I log this issue. It was more for awareness since docker is a common thing for  developers.
