### ISSUE TITLE
[opensuse-packaging] Keyboard Layout Applet only shows US

### ISSUE THREAD

**Issue by gmbr3** [solus-project/budgie-desktop#2019]
## Description
I am the new official maintainer of Budgie for openSUSE. However, I have encountered a minor problem that the Keyboard Layout Applet only shows English - English(US) no matter what keyboard is selected in Settings. Tested with English (UK). I am unsure whether this is because I have missed something when packaging or whether it is a bug. Tested system had ibus and libibus installed. 

## Budgie version
10.5.1

## Operating system
openSUSE Tumbleweed

## Additional information
[Build log](https://build.opensuse.org/build/X11:Solus/openSUSE_Tumbleweed/x86_64/budgie-desktop/_log)

**Comment by JoshStrobl** [comment]
Unable to reproduce using latest git builds, which do have fixes for IBUS integration in the KeyboardLayout applet. I've added English (UK) to my existing Finnish layout and it immediately added it.

Be sure to be building against git.
