### ISSUE TITLE
Ubuntu updates

### ISSUE THREAD

**Issue by loctauxphilippe** [solus-project/budgie-desktop#202]
the ppa is not updated for the latest version 15.04, could you update them please @ikeydoherty ?
thanks!

**Comment by ikeydoherty** [comment]
I will consider it this weekend @loctauxphilippe - in all honesty Ubuntu is an awful target for us.. Incredibly painful to work with.

**Comment by loctauxphilippe** [comment]
@ikeydoherty cool! thanks! Can't wait to try budgie!

**Comment by Justinzobel** [comment]
In the mean time just check it out from github..

**Comment by tista500** [comment]
@ikeydoherty I've tried to build git-based packages on my PPA for **Vivid (15.04)**...
https://launchpad.net/~tista/+archive/ubuntu/budgie/+packages

I hope someone could check it on vivid system since I've already moved to Wily pre-alpha system.

Best Regards.

**Comment by ikeydoherty** [comment]
Closing due to others taking up the task
