### ISSUE TITLE
Suggestion for the the menu button in Budgie. 

### ISSUE THREAD

**Issue by linusrg1** [solus-project/budgie-desktop#2020]
I realised how easy it was to end up with a blank unusable panel. It would be nice if the menu button was mandatory on at least one panel. This would make it impossible for the budgie desktop to become unusable. On another note, it would be nice if taskbar/dock items could be bigger in than the 20px range as it means you cannot get a true dock experience. One final thing that would be nice to do would be to have the ability to add applets (including the clock) to the centre of a full sized taskbar. As I like Budgie more than Gnome overall, but I kind of liked (and am used to) the layout of gnome, so it would be nice if I could customise panels in this way.

**Comment by Scupake** [comment]
You can press alt+F2 to bring up a menu.

**Comment by JoshStrobl** [comment]
1. As mentioned by @Scupake, you can access Budgie Desktop Settings via the Alt+F2 run dialog.
2. You can already increase the dock and the items will scale based on the next available icon size. They're fixed sizes, we can't assume everything is an SVG or has some high resolution icon that we'd need to scale down (and take more memory for no reason).
3. You can already move applets to the center though...
