### ISSUE TITLE
Tasklist not showing Virtualbox windows

### ISSUE THREAD

**Issue by kp2401075** [solus-project/budgie-desktop#2021]
## Precheck
Have you searched for similar issues before submitting this issue?
Yes I did, I may have missed not sure.
please feel free to contact me if you have any questions.

## Description
I don't see Virtual box windows in icon task list.
Only happens with Virtualbox. all the other apps work perfectly.

Toggeling windows grouping off and on get it to appear.
0r
if i'm connected to external display disconnecting makes it appear.

![external-monitor](https://user-images.githubusercontent.com/20717654/90577132-61b12500-e203-11ea-88f0-591eee5b5f95.png)

same thing happens when i'm not connected to the display as well

![relaunch](https://user-images.githubusercontent.com/20717654/90577291-d6845f00-e203-11ea-9e9a-3050fe720ee7.png)

Only time I am able to see Icons is :
- when I launch virtual box while connected to external monitor and then disconnect the external monitor.
- Toggle window grouping off & on.

![tasklist-laptop](https://user-images.githubusercontent.com/20717654/90577214-99b86800-e203-11ea-933b-aaa21a7c817d.png)

## Budgie version
latest
```
budgie-desktop --version
budgie-desktop 10.5.1 (git-42201c183fccd7d65f143f8f6bb70bcf3bcaffd8)
Copyright © 2014-2019 Budgie Desktop Developers
```

## Operating system
Solus 4.1 Fortitude

## Steps to reproduce the issue
Launch Virtualbox 

## Additional information

it works fine with window grouping turned off

![icon-tasklist-no-grouping](https://user-images.githubusercontent.com/20717654/90577548-940f5200-e204-11ea-95d2-91a27c4e9150.png)

**Comment by JoshStrobl** [comment]
Please use search... #1427

**Comment by kp2401075** [comment]
Thanks,
 Sorry for opening new issue.
