### ISSUE TITLE
[opensuse-packaging] Failed build (GNOME:Next on OBS)

### ISSUE THREAD

**Issue by gmbr3** [solus-project/budgie-desktop#2028]
## Description
Build failure at openSUSE when testing in GNOME Future repo.

## Budgie version
1ed6276b

## Operating system
openSUSE Tumbleweed

## Actual result
[   44s] [22/270] valac -C --pkg libwnck-3.0 --pkg gdk-x11-3.0 --pkg gtk+-3.0 --color=always --directory src/appsys/libappsys.a.p --basedir ../src/appsys --library appsys --header src/appsys/appsys.h --vapi ../appsys.vapi --pkg gio-unix-2.0 --pkg gtk+-3.0 --pkg gdk-x11-3.0 --pkg libwnck-3.0 ../src/appsys/AppSystem.vala
[   44s] FAILED: src/appsys/libappsys.a.p/AppSystem.c src/appsys/appsys.h src/appsys/appsys.vapi 
[   44s] valac -C --pkg libwnck-3.0 --pkg gdk-x11-3.0 --pkg gtk+-3.0 --color=always --directory src/appsys/libappsys.a.p --basedir ../src/appsys --library appsys --header src/appsys/appsys.h --vapi ../appsys.vapi --pkg gio-unix-2.0 --pkg gtk+-3.0 --pkg gdk-x11-3.0 --pkg libwnck-3.0 ../src/appsys/AppSystem.vala
[   44s] ../src/appsys/AppSystem.vala:54.38-54.57: error: Argument 7: Cannot convert from `void Budgie.AppSystem.signal_received (GLib.DBusConnection, string, string, string, string, GLib.Variant)' to `void GLib.DBusSignalCallback (GLib.DBusConnection, string?, string, string, string, GLib.Variant)'
[   44s]                                      this.signal_received);
[   44s]                                      ^^^^^^^^^^^^^^^^^^^^

## Additional information
[Full build log](https://build.opensuse.org/build/home:gmbr3:Solus/GNOME_Next+oS_Factory/x86_64/budgie-desktop/_log)

**Comment by fossfreedom** [comment]
There must be a difference between mutter 3.37.92 in opensuse and Debian's experimental repo which has 3.37.92

Budgie Desktop compiles fine in Debian 

https://packages.debian.org/experimental/mutter
https://packages.debian.org/experimental/budgie-desktop

**Comment by gmbr3** [comment]
@fossfreedom Actually, I forgot GNOME:Next pulls a lot of other testing GNOME stuff not just new GNOME; so the diffreence will be that other openSUSE testings will be ahead of Debian

Might be vala itself; openSUSE has a lot newer version (0.49.92) compared with Debian(0.48.10)
https://salsa.debian.org/gnome-team/vala/
https://build.opensuse.org/package/show/GNOME:Next/vala

**Comment by gmbr3** [comment]
Actually, seems I was correct without knowing!:)

https://gitlab.freedesktop.org/zeitgeist/zeitgeist/-/issues/20
https://github.com/ibus/ibus/issues/2254

**Comment by gmbr3** [comment]
Testing similar fix to
https://gitlab.freedesktop.org/zeitgeist/zeitgeist/-/commit/e9639d48a6bb0aa59f25f25b2c4d7c97324d9c34

**Comment by gmbr3** [comment]
Fix tested good.
