### ISSUE TITLE
The top bar increases height when the Slack icon appears on AppIndicador Applet.

### ISSUE THREAD

**Issue by MessiasLima** [solus-project/budgie-desktop#2030]
## Description
The top bar increases size when the Slack icon appears on AppIndicador Applet.

## Budgie version
budgie-desktop 10.5.1
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system
Ubuntu Budgie 20.04.1 LTS

## Steps to reproduce the issue
1. Open slack
1. The top panel will increase the size overlapping the windows

## Actual result
<a href="https://www.loom.com/share/e2d8118aad6641bcbfebe5cec1c53a6d"> <p>Loom | Free Screen & Video Recording Software - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e2d8118aad6641bcbfebe5cec1c53a6d-with-play.gif"> </a>

## Expected result
The panel must maintain the size no matter the size of the icon shown

## Additional information
```
            .-/+oossssoo+/-.               messias@messias-ThinkPad-E580 
        `:+ssssssssssssssssss+:`           ----------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20KS001JPG ThinkPad E580 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-47-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 52 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2035 (dpkg), 14 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Budgie 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter(Budgie) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Qogir-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Reversal-blue-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: xfce4-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal Font: MesloLGS NF 10 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-8250U (8) @ 3.400GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel UHD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 4334MiB / 15775MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   

```         
- When I change the panel height on Budgie desktop settings, the panel height back to the right height.

**Comment by JoshStrobl** [comment]
> AppIndicador Applet

This isn't our problem, it's not our applet.

**Comment by MessiasLima** [comment]
Do you know where I can report this bug properly?

**Comment by dhaavi** [comment]
We are experiencing an extreme version of this here: https://github.com/safing/portmaster-ui/issues/111

Admittedly, we do supply a huge icon, but all other DEs just handle this perfectly so far. So:

- Is this our fault? If so, where does Budgie specify the required sizes?
  - If the bar is not part of Budgie, what component is it? Ie. where can I report this?
- If this is Budgie's fault, is there any information we can supply to help you tackle this?

**Comment by MessiasLima** [comment]
I reported the issue on Ubuntu budgie repositories. They own the indicator applet repo.
https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/25

But they blame my setup. They said that a 30px bar is "too small"

**Comment by dhaavi** [comment]
Ok, thanks for the pointer! 👌

**Comment by guillotjulien** [comment]
Playing the devil advocate, but have you considered properly scaling your icon @dhaavi? I don't see any developer responding positively to someone trying to use an image as big as that and complaining it's broken, just saying ;)

**Comment by dhaavi** [comment]
Thanks for chiming in @guillotjulien, very much appreciated.

Well, I definitely see your point. I guess this is a lazy developers assumption that if it works an most systems, the others should kind of adapt to how the others are doing it.

Nevertheless, I'm currently looking for the spec to do exactly that - scaling the icon to the size they want it. 😉
I guess this is just the Linux way: Creating software that needs to handle all special cases itself.

**Comment by MessiasLima** [comment]
@guillotjulien IMHO @dhaavi should scale the icon. But ubuntu budgie guys also have to have to implement a fixed size for these icons. @dhaavi can scale the icon, but in my case, I'm not working on Slack. I can't scale the slack icon. So, as a non-developer, in this case, I have nothing to do unless waiting for someone to fix it

**Comment by JoshStrobl** [comment]
Locking thread. If you having issues with the System Tray, XEmbed-based solution that Solus (developers of Budgie, this repo) provide, then a separate issue is appropriate. We already do several forms of resizing, issues like Slack are not present using our System Tray implementation.

If you are having issues with Ubuntu Budgie's appindicator support, then as I mentioned it should be fixed with them. Necroing this task with an issue with a downstream applet rather than using ours is not appropriately. If their applet has issues, switch to the official, better tested one.
