### ISSUE TITLE
Memory usage increases when background picture changes

### ISSUE THREAD

**Issue by LukMas** [solus-project/budgie-desktop#2032]
## Description

As I've found out [here](https://discuss.getsol.us/d/5480-variety-dynamic-wallpapers-and-budgie-memory-usage-6gb/3), there's something strage with Budgie when the background changes.
First I've thought that the problem is the software that I was using, variety, but:
* on variety web site nobody reported such a problem
* trying to load heavy images as backgrounds and changing them fast causes exactly the same problem

## Budgie version
10.5.1-213

## Operating system

Solus 4.1

## Steps to reproduce the issue
Hence, the problem lies somewhere in Budgie. Indeed, and it's really simple to replicate it:
* start the default application to manage the wallpapers (background)
* load a list of heavy images as extra background (not needed, but it shows faster the problem)
* switch fast between this images

## Actual result
Memory usage of Budgie increases really fast, without never being released.
It has something to do with the heap, it looks that the images are loaded but the memory that they use is never releases.

## Expected result
No memory increase, or at least yes, but then the memory should be releases.

**Comment by fossfreedom** [comment]
Suggest have a look at this https://github.com/varietywalls/variety/issues/226#issuecomment-543244906

**Comment by JoshStrobl** [comment]
Closing since this issue lies with how Variety is setting wallpapers.
