### ISSUE TITLE
Vlc instances stays open after you close stream

### ISSUE THREAD

**Issue by AnxiousUK** [solus-project/budgie-desktop#2034]
As title suggest there are vlc instances running in your notification bar even if you close it. I use send to vlc add on on fire fox to watch twitch streams since vlc support hardware acceleration on my weak n3350, but every time I close it and start a new stream it adds another instance to the notifications bar and it keeps adding, doesn't resolve it without reboot. Not sure its budgie related, vlc themselves or solus on its own. Thank you.

**Comment by JoshStrobl** [comment]
This is a VLC preference.
