### ISSUE TITLE
Update gnome-settings-daemon to 3.16 AKA my multimedia keys don't work on Arch

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/budgie-desktop#204]
I installed Budgie Desktop on Antergos fresh from git (0cd8e479b0bdd53effad52c59d0f9004ca187afa) today. Most of my multimedia keys don't work. @ikeydoherty says it's possibly an issue with the changes in gnome-settings-deamon going from 3.14 to 3.16.

**Comment by Mountaineer1024** [comment]
This is probably the same as #114.
Is there anyway we can help track this down?

**Comment by ikeydoherty** [comment]
*Potentially* related - I don't think its the same if the other keys are working in #114. 
Re: helping, if media keys aren't working with Budgie from git on a distribution using g-s-d 3.16, then we know g-s-d 3.16 is the issue.

**Comment by Mountaineer1024** [comment]
Well, I don't know if this is useful to you, but I did some digging based on https://wiki.archlinux.org/index.php?title=Extra_keyboard_keys&redirect=no

In xev, if I hit the volume up or down keys, I get unbound info:
`FocusOut event, serial 37, synthetic NO, window 0x2800001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 37, synthetic NO, window 0x2800001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  64  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0`

But if I I hold down a modifier such as the control key, the XF86AudioLowerVolume key is registered:
`KeyPress event, serial 37, synthetic NO, window 0x2800001,
    root 0x296, subw 0x0, time 4365409, (1093,578), root:(1184,655),
    state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x2800001,
    root 0x296, subw 0x0, time 4366130, (1093,578), root:(1184,655),
    state 0x14, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2800001,
    root 0x296, subw 0x0, time 4366202, (1093,578), root:(1184,655),
    state 0x14, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

MappingNotify event, serial 37, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyRelease event, serial 37, synthetic NO, window 0x2800001,
    root 0x296, subw 0x0, time 4366305, (1093,578), root:(1184,655),
    state 0x14, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False`

If I understand correctly, this implies something is capturing the volume key press before it can be correctly interpreted by the settings daemon.

**Comment by X0rg** [comment]
Same problem, media keys do nothing.

**Comment by tista500** [comment]
Greetings,

I've updated g-s-d to 3.16.2 on Ubuntu (without ubuntu-specified patches) as well, and same issue +1.
Then I saw GLib warning whenever pressing VolumeUP/DOWN keys:
``(gnome-settings-daemon:11430): GLib-GIO-WARNING **: Dropping signal AcceleratorActivated of type (uuu) since the type from the expected interface is (ua{sv})``

AFAIK GVariant seems to be changed after 3.15.xx was released: https://git.gnome.org/browse/gnome-settings-daemon/commit/?id=46525602364088398eeb3a98d7bcfa64deeddd4e

I'm not sure those codes cause the current issue though... anyway ``wm/impl/key.c`` might be related:
```/**
 * Handle GrabAccelerators dbus interface (batch)
 */
static gboolean on_grab_accelerators(ShellKeyGrabber *grab,
                                       GDBusMethodInvocation *i,
                                       GVariant *vars)
{
        GVariantIter iter;
        gchar *seq = NULL;
        guint flag;
        guint id;
        const gchar *sender;
        GVariantBuilder builder;

        g_variant_iter_init(&iter, vars);
        sender = g_dbus_method_invocation_get_sender(i);
        g_variant_builder_init(&builder, G_VARIANT_TYPE("au"));

        while (g_variant_iter_loop(&iter, "(su)", &seq, &flag, NULL)) {
                id = _grab(sender, seq, flag);
                /* May still result in META_KEYBINDING_ACTION_NONE.. */
                g_variant_builder_add(&builder, "u", id);
        }

        shell_key_grabber_complete_grab_accelerators(grab, i, g_variant_builder_end(&builder));
        return TRUE;
}
```

Regards.

**Comment by talesam** [comment]
I'm having the same problem in archlinux , shortcut keys do not function.

**Comment by ikeydoherty** [comment]
We'll change it when we sync with G-S-D 3.16 over the weekend. Almost there no, no panics :]

**Comment by Mountaineer1024** [comment]
Thanks Ikey

**Comment by ikeydoherty** [comment]
Fixed, sorry for delay, was ill.
