### ISSUE TITLE
Icon Task List: Favorites not showing up

### ISSUE THREAD

**Issue by nathanpainchaud** [solus-project/budgie-desktop#2042]
## Description
Favorites are not showing up in the _Icon Task List_ applet when using the following configuration:
- _Window grouping_ and _Restrict to workspace_ toggled on
- Everything else toggled off

Even toggling on _Only show favorited_ doesn't bring up the favorites.

I have also [mentioned the bug on the forum](https://discuss.getsol.us/d/5617-budgie-task-list-favorites-not-showing), so I know it's already been reported, but I have not found any issue related to it here.

## Budgie version

`budgie-desktop 10.5.1 (git-e95518c36afaaa942aa5c12b8f750c34ec22007d)`

## Operating system

Solus 4.1 Fortitude, everything up to date as of Oct 17th.

## Steps to reproduce the issue

Configure the _Icon Task List_ to the settings described above (_Window grouping_ and _Restrict to workspace_ toggled on, everything else toggled off).

I have been able to get the favorites to show up again by toggling off _Restrict to workspace_.

Right after the sync from Oct 16th (rel 217 I think?), I was also able to get the favorites to show by toggling on _Only show favorited_. However, after updating following rel 219, _Only show favorited_ doesn't show the favorites anymore.

## Actual result

Current situation (no favorites showing up):
![budgie_no_favorites](https://user-images.githubusercontent.com/23144457/96356917-efee3e00-10c2-11eb-990e-abd63a86fd2c.png)

Toggling on _Only show favorited_ right after Oct 16th udpate (rel 217):
![budgie_favorites](https://user-images.githubusercontent.com/23144457/96356933-27f58100-10c3-11eb-9ab5-657261c5a9a1.png)

Toggling on  _Only show favorited_ after Oct 17th udpate (rel 219):
![no_favorites_only_favorites](https://user-images.githubusercontent.com/23144457/96356958-54110200-10c3-11eb-81d5-cc12133bf770.png)

Toggling on  _Restrict to workspace_ after Oct 17th udpate (rel 219):
![favorites_restrict_workspace](https://user-images.githubusercontent.com/23144457/96356975-8458a080-10c3-11eb-9394-1f183fa42d70.png)

## Expected result
Favorites should be displayed with any of the settings configurations shown above.

**Comment by synth-ruiner** [comment]
I'm also experiencing this. turning off "restrict to workspace" seems to fix it for me though. all the other toggles for it are also turned off.
