### ISSUE TITLE
Cosmetic issue with budgie-panel Icon Task click animations

### ISSUE THREAD

**Issue by kmandarin-orange** [solus-project/budgie-desktop#2046]
## Description
There's a purely cosmetic bug (maybe intended change, but I doubt it) in which the Icon Task List lacks the typical "ripple" animations on clicking an icon, with a more plain animation that feels a bit out of place. Before the 10.5.1-218 update this wasn't the case.

## Budgie version
budgie-desktop 10.5.1 (git-e95518c36afaaa942aa5c12b8f750c34ec22007d)

## Operating system
Solus 4.1

## Steps to reproduce the issue
Use Icon Task List in a panel and click on an icon, watching for an animation.

## Actual result
The current appearance of clicking icons feels a little unpolished, with just a simple fade in/out animation on the highlight.
![ezgif-3-3f0c75ce6d46](https://user-images.githubusercontent.com/55755379/96516015-f5b36300-122b-11eb-8ab4-1faf0dc656b6.gif)

## Expected result
Expected to use the same ripple effect that appears elsewhere in the desktop, such as buttons or apps in the Budgie Menu list
![Screenshot from 2020-10-19 16-47-34](https://user-images.githubusercontent.com/55755379/96515658-52fae480-122b-11eb-8871-f272d44cd441.png)

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue and should be handle by themes.

**Comment by kmandarin-orange** [comment]
Ah I see, just to make sure I report this in the right place I'd file a bug report at the plata-theme Gitlab, correct? I don't want to ping the wrong project.
