### ISSUE TITLE
Add Ability to Change Default Screenshot tool

### ISSUE THREAD

**Issue by NovaViper** [solus-project/budgie-desktop#2047]
### Current Budgie version

Budgie 10.5.1, EndeavourOS 3.5.1

### Use-cases

I would like to use some sort of screenshot utility that isn't gnome-screenshots, as gnome-screenshots is very limited in functionality and it's really annoyed that the program is hardcoded onto the print screen button. Not even stock Gnome has the utility hardcoded to the print screen button.

### Proposal

Add some sort of setting to allow Print Screen button to be mapped to another program, or at the very least, remove the built-in code that restricts the button to gnome-screenshot so other programs can be mapped to it

**Comment by JoshStrobl** [comment]
This can already be done in git using budgie-wm dconf options.

**Comment by NovaViper** [comment]
@JoshStrobl How do I change it? I can't find anywhere how to change it

**Comment by JoshStrobl** [comment]
You change it via dconf or gsettings. These settings are provided so downstreams can change it and is not intended at this time to be  a broader user-facing feature for customization.

You can modify the `full-screenshot-cmd`, `take-region-screenshot-cmd` and `take-window-screenshot-cmd` key/values exposed via `com.solus-project.budgie-wm`

**Comment by NovaViper** [comment]
The dconf settings only seems to allow for changing the shortcut, but not what program to use

**Comment by JoshStrobl** [comment]
No...You're looking at the conf keys for shortcuts not the programs themselves. Look at my comment again please.

**Comment by JoshStrobl** [comment]
Also as I said:

> This can already be done in git using budgie-wm dconf options.

Keyword being **git**. As in current master. The options landed in 8558e949332102239a5e3d06e2e604ea7d19544f which will be in Budgie 10.5.2 but did not ship in 10.5.1.

**Comment by NovaViper** [comment]
> Also as I said:
> 
> > This can already be done in git using budgie-wm dconf options.
> 
> Keyword being **git**. As in current master. The options landed in [8558e94](https://github.com/solus-project/budgie-desktop/commit/8558e949332102239a5e3d06e2e604ea7d19544f) which will be in Budgie 10.5.2 but did not ship in 10.5.1.

Ah ok! I'll have to wait around for 10.5.2 to release, as EndeavourOS is going by the full releases of Budgie

**Comment by JoshStrobl** [comment]
Yea, Budgie 10.5.2 will be out soon :wink: Been [finishing up the last bits](https://twitter.com/JoshStrobl/status/1318601726354743299) recently.
