### ISSUE TITLE
Add on screen keyboard applet to systray

### ISSUE THREAD

**Issue by mgrouch** [solus-project/budgie-desktop#2062]
Add on screen keyboard applet to systray.
onboard might be?

Add automatic pop up of the keyboard in text fields.

For instance I can't enter password without keyboard after I put screen to hibernate

**Comment by JoshStrobl** [comment]
> For instance I can't enter password without keyboard after I put screen to hibernate

This is something that's the result of gnome-screensaver or whatever locker you end up using, not related to Budgie.
