### ISSUE TITLE
Keyboard layout ['<Shift>Alt_L'] does not work

### ISSUE THREAD

**Issue by AKotov-dev** [solus-project/budgie-desktop#2063]
Hello.
I really liked Your latest build of Budgie-10.5.1 and now I use this DE permanently in Mageia-7.1.
My system has been updated and now I'm testing Budgie-desktop [master] https://github.com/solus-project/budgie-desktop.git on Mageia-8.

I set switching of keyboard input languages (RU/EN):
---
`gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Shift_L']"`
`gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift>Alt_L']"`

Result:
---
Hold "Alt" and press "Shift" - switching works
I hold "Shift" and press "Alt" - switching does not work (there is no reaction)

So switching languages depends on which of the keys was pressed first and works after 5-10 clicks, until the desired finger first presses "Alt". :)

In GNOME itself, the input language switches perfectly. In version Budgie-10.5.1 everything worked fine. What could be the problem in Budgie-(master)? Thanks.

Sincerely,
Alex

**Comment by JoshStrobl** [comment]
You don't need to set the forward one, it's supported in git. Backwards using shift+alt_l wasn't functionality in my testing, hence why it wasn't added.

https://github.com/solus-project/budgie-desktop/blob/master/src/wm/com.solus-project.budgie.wm.gschema.xml#L113
