### ISSUE TITLE
Assets renamed in v10.5.2

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#2065]
## Description
The asset names in the release tag is slightly different from previous releases.

Any change of changing them to the previous naming format please?

The reason for the request is that Debian "watches" for new upstream versions - but the watch file cannot cope with renamed assets.

## Budgie version
10.5.2

## Operating system
Debian Unstable

## Steps to reproduce the issue
N/A

## Actual result
budgie-desktop-v10.5.2.tar.xz
budgie-desktop-v10.5.2.tar.xz.asc

## Expected result
budgie-desktop-10.5.2.tar.xz
budgie-desktop-10.5.2.tar.xz.asc

i.e. without the "v" in the version

## Additional information
N/A

**Comment by JoshStrobl** [comment]
Yea the v was added to be in alignment with the other mkrelease scripts used by Solus, but I can generate a new tarball to resolve that for Debian.

**Comment by fossfreedom** [comment]
Ah. Good that future assets will then have a consistent naming - Debian can then cope with that. I will change the watch for the new convention. No need for generating the previous asset naming format. Cheers Josh.
