### ISSUE TITLE
Disabling Wi-Fi powersaving disables networking Dell Latitude E7240

### ISSUE THREAD

**Issue by chosig** [solus-project/budgie-desktop#2066]
## Description
If I uncheck Settings -> Power -> Wi-fi can be turned off to save power Solus drops the connection and says the card is disabled.
When checking with rfkill it shows the card and that it is unblocked

It's a Dell Latitude E7240

## Budgie version
10.5.2

## Operating system
Solus 4.1

## Steps to reproduce the issue
* Settings
* Uncheck "Wi-Fi can be turned off to save power"

## Actual result
Wi-Fi gets disconnected and the applet says that Wi-Fi is disabled.

## Expected result
Powersaving for Wi-Fi is turned off.

## Additional information
Turning on powersaving feature again re-enables the card

```
chosig@phoenix ~ $ rfkill 
ID TYPE      DEVICE              SOFT      HARD
 1 bluetooth hci0           unblocked unblocked
 2 wlan      dell-wifi      unblocked unblocked
 3 bluetooth dell-bluetooth unblocked unblocked
 4 wlan      phy0           unblocked unblocked
 5 wwan      dell-wwan      unblocked unblocked

chosig@phoenix ~ $ lspci | grep Network
02:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)

chosig@phoenix ~ $ lsmod | grep -i wifi
iwlwifi               299008  1 iwlmvm
cfg80211              856064  3 iwlmvm,iwlwifi,mac80211
```

**Comment by JoshStrobl** [comment]
Not related to Budgie.
