### ISSUE TITLE
Desktop icons disappear when using DesktopFolder

### ISSUE THREAD

**Issue by AvdN** [solus-project/budgie-desktop#2069]
## Description

Budgie now provide official support for DesktopFolders ( according to https://getsol.us/2020/12/02/budgie-10-5-2-released/#budgie-desktop-view ). But unless the icons are locked, they sometimes disappear when you drag something past them (e.g. to another folder). 
Such an icons is not somewhere else on the Desktop and the only way to get such an icon back is by Right-click->Reorganize icons, which put all the icons in their default position, from which they have to be moved to where they are wanted. During that process, one has to make sure not to (a group of) desktop icons over other desktop icons (already moved) as this will at least end up in the drag aborting (with the group back to its original place).

Icons can also not be dragged over open windows of applications. These have to be closed or minimized before moving around the icons. 

Locking the icons in will prevent disappearing from happening, but any additional directory on the Desktop only can be moved in its place by unlocking and tedious moving around to prevent an icon from hovering over another at any given time.

## Budgie version

budgie-desktop 10.5.2

## Operating system

Solus 4.1

## Steps to reproduce the issue

- install DesktopFolders
- create folders under ~/Desktop ( I have 15-20 )
- move 5 folders to bottom of screen on the right, leaving one enough place for a row of icons below these
- drag a single icon passing over the icons of the previous step
- drag multiple icons passing over the icons of the previous step

## Expected result
That the icon(s) move to where they are dragged without disturbing any other desktop icons

## Additional information
I have a three monitor setup (did have the same setup for 5+ years), and this also gives problems when all operations are done on one desktop.

**Comment by JoshStrobl** [comment]
We are not the developers of DesktopFolders. This isn't our problem.

**Comment by AvdN** [comment]
Well sorry, I am just trying to get a working system back. And I gathered from the blog that functionality could be dropped from budgie by officially supporting applications like DesktopFolders.
I am just trying to get a functional system back, because tomorrow the weekend is over and work needs to be done.
Thanks for your help
