### ISSUE TITLE
Budgie 8.2 failed on Debian

### ISSUE THREAD

**Issue by pavroo** [solus-project/budgie-desktop#207]
Hi
I tried to compile Budgie Desktop 8.2 on Debian testing 64 bit, kernel 3.16, but it failed with the output:
-------------------------------------------------------
In file included from RunDialog.c:23:0:
/usr/include/gio-unix-2.0/gio/gdesktopappinfo.h:170:11: note: declared here
 gchar *** g_desktop_app_info_search (const gchar *search_string);
           ^
RunDialog.c:1377:9: warning: assignment from incompatible pointer type
  _tmp5_ = g_desktop_app_info_search (_tmp3_, &_tmp4_);
         ^
RunDialog.c:1378:9: warning: assignment from incompatible pointer type
  search = _tmp5_;
         ^
Makefile:514: recipe for target 'budgie_run_dialog-RunDialog.o' failed
make[3]: *** [budgie_run_dialog-RunDialog.o] Error 1
make[3]: Leaving directory '/home/pavroo/git-evolve/budgie-desktop/rundialog'
Makefile:392: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pavroo/git-evolve/budgie-desktop/rundialog'
Makefile:466: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pavroo/git-evolve/budgie-desktop'
Makefile:397: recipe for target 'all' failed
make: *** [all] Error 2
------------------------------------------------------
Regards
pavroo

**Comment by lachlan-00** [comment]
same on Jessie (All stable) following this page. https://solus-project.com/wiki/Budgie/Install

**Comment by pavroo** [comment]
Missing dependencies.
Can be closed.
Thank's

**Comment by Justinzobel** [comment]
@pavroo which dependencies so I can add it to the guide.

**Comment by pavroo** [comment]
There are deps for 8.1 I used before:
build-essential gobject-introspection libglib2.0-dev libgtk-3-dev libpulse-dev libpulse-mainloop-glib0 libmutter-dev libwnck-3-dev libupower-glib-dev libgnome-menu-3-dev libc6-dev libpeas-dev libgee-0.8-dev valac git gnome-settings-daemon gnome-control-center gnome-menus nautilus

Following the installation wiki guide, I added for 8.2:
intltool gir1.2-gee-1.0 gnome-common libgee-dev libgee2

**Comment by DJviolin** [comment]
I have all of this dependencies installed, but I got this error message:

```
Makefile:514: recipe for target 'budgie_run_dialog-RunDialog.o' failed
make[2]: *** [budgie_run_dialog-RunDialog.o] Error 1
make[2]: Leaving directory '/home/lanti/budgie-desktop/rundialog'
Makefile:647: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/lanti/budgie-desktop/rundialog'
Makefile:466: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by pavroo** [comment]
There is libmutter0f missing

**Comment by DJviolin** [comment]
```
E: Unable to locate package libmutter0f
```

**Comment by lachlan-00** [comment]
It's part of 3.16 which is in testing now. I haven't tried compiling since I went to 3.16 though.

**Comment by pavroo** [comment]
I noticed in the first post that it's Debian testing.
For Debian stable use libmutter0e

**Comment by ikeydoherty** [comment]
-_- what is with Debian and plucking version numbers out of thin air..
