### ISSUE TITLE
Budgie panel crash and restart after launching KeePass

### ISSUE THREAD

**Issue by Staudey** [solus-project/budgie-desktop#2071]
## Description

Budgie panel crashes and restarts after launching KeePass (from the Solus repository). Launching it a second time in close succession completely crashes the session.

## Budgie version

budgie-desktop 10.5.2

## Operating system

Solus 5.6.19-159.current (unstable repository)

## Steps to reproduce the issue

1. Install KeePass from the Solus repository
2. Launch KeePass

## Actual result

1. The panel crashes, disappears for a second and restarts. Closing and launching KeePass again crashes the session completely (unless you wait a while).

## Expected result
1. KeePass launches without crashing the panel

## Additional information
Journal shows the following messages after launching KeePass:

```
Dez 08 21:29:06 solus-pc audit[1344]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 subj==unconfined pid=1344 comm="budgie-panel" exe="/usr/bin/budgie-panel" sig=11 res=1
Dez 08 21:29:06 solus-pc kernel: budgie-panel[1344]: segfault at 0 ip 00007f7dd3065400 sp 00007ffea44c21f0 error 4 in libc-2.31.so[7f7dd2fee000+175000]
Dez 08 21:29:06 solus-pc kernel: Code: 49 89 ec e9 77 fd ff ff 66 90 f3 0f 1e fa 48 83 ec 18 48 8b 05 09 bb 14 00 48 8b 00 48 85 c0 0f 85 7d 00 00 00 48 85 ff 74 70 <48> 8b 47 f8 48 8d 77 f0 a8 02 75 34 48 8b 15 65 b9 14 00 64 48 83
Dez 08 21:29:06 solus-pc gnome-session[1138]: gnome-session-binary[1138]: WARNING: Application 'budgie-panel.desktop' killed by signal 11
Dez 08 21:29:06 solus-pc gnome-session-binary[1138]: WARNING: Application 'budgie-panel.desktop' killed by signal 11
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk.css:2871:35: '-2px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk.css:2877:35: '-1px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk.css:4824:30: '-2px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk-dark.css:2871:35: '-2px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk-dark.css:2877:35: '-1px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-panel[7730]: Theme parsing error: gtk-dark.css:4824:30: '-2px' is not a valid color name
Dez 08 21:29:06 solus-pc budgie-wm.desktop[1326]: Window manager warning: Window 0x620010a sets an MWM hint indicating it isn't resizable, but sets min size 104 x 1 and max size 556 x 310; this doesn't make much sense.
Dez 08 21:29:06 solus-pc budgie-wm.desktop[1326]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x620010a
```

**Comment by JoshStrobl** [comment]
I've just created a [Providing a Backtrace](https://github.com/solus-project/budgie-desktop/wiki/Providing-Backtraces) wiki page to help facilitate issues like this. Please use this document to create a backtrace file so we can look into it further. Thanks!

**Comment by EbonJaeger** [comment]
Confirmed happening here, too. Possible CarbonTray issue?

[budgie-desktop-gdb.txt](https://github.com/solus-project/budgie-desktop/files/5663178/budgie-desktop-gdb.txt)

**Comment by JoshStrobl** [comment]
Yep, looks like it.

**Comment by JoshStrobl** [comment]
Poking @serebit

**Comment by serebit** [comment]
![raw](https://user-images.githubusercontent.com/12981608/101568865-69a6f780-39a1-11eb-9d61-2ec6f0b081d1.gif)

**Comment by serebit** [comment]
Verified this locally, working on a fix. Stay tuned.
