### ISSUE TITLE
Budgie desktop crashes with touch of task icons

### ISSUE THREAD

**Issue by mgrouch** [solus-project/budgie-desktop#2073]
## Description

Budgie desktop crashes with touch of task icons quite often.
If i touch a task icon in task bar, do not let my finger go and slide it up the screen 
budgie desktop would crash.

## Budgie version

10.5-1

## Operating system
Rapberry OS buster, arm 64 (all updated)

## Steps to reproduce the issue

If i touch a task icon in task bar, do not let my finger go and slide it up the screen 
budgie desktop would crash.

**Comment by JoshStrobl** [comment]
> 10.5-1

Please make sure you are on the latest release of Budgie, which is Budgie 10.5.2.
