### ISSUE TITLE
nm-applet in system tray is painted with one icon over another

### ISSUE THREAD

**Issue by mgrouch** [solus-project/budgie-desktop#2074]
## Description
nm-applet in system tray is painted with one icon over another.
same happens with onboard keyboard icon

## Budgie version

10.5-1

## Operating system

Raspberry OS buster, arm 64 (all updated)

## Steps to reproduce the issue

Add

export XDG_CURRENT_DESKTOP=Budgie:GNOME; budgie-desktop &

nm-applet &
onboard &

into

~/.config/openbox/autostart

reboot

## Actual result

nm-applet in system tray is painted with one icon over another.
WiFi reception bars are painted over some kind of another icon.

## Expected result

Expected to see just WiFI reception bars icon.

## Additional information

same happens with onboard keyboard icon in system tray

**Comment by JoshStrobl** [comment]
This has been fixed for a long time. Make sure you are using the most up-to-date version of Budgie, which isn't Budgie 10.5 but rather 10.5.2.
