### ISSUE TITLE
Tooltips do not always disappear

### ISSUE THREAD

**Issue by mgrouch** [solus-project/budgie-desktop#2075]
## Description
Tooltips do not always disppear

## Budgie version
10.5-1

## Operating system
Raspberry OS (buster) arm64

## Steps to reproduce the issue

Use just touchscreen functionality (without mouse)
and tooltips do not always disappear.
Example tooltip on "Toggle the desktop"

## Actual result
Tooltips stay on the screen

## Expected result
Should disappear after a timeout

**Comment by JoshStrobl** [comment]
> 10.5-1

Please make sure you are on the latest release of Budgie, which is Budgie 10.5.2.
