### ISSUE TITLE
Regression - duplicate icons in docks like plank when launching budgie desktop settings

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#2081]
## Description
When launching budgie desktop settings two icons are seen in the plank dock.
On closing the window - budgie-panel icon remains in the dock.

## Budgie version
10.5.2

## Operating system
Ubuntu Budgie 21.04

## Steps to reproduce the issue
Run budgie-desktop-settings with a dock like plank
Note the icons duplication
close the settings window
Note the budgie-panel icon remains

## Actual result
Duplicate icons

## Expected result
One icon.
Icon disappears after the window closes

## Additional information
This is a regression.

First resolved way back https://github.com/solus-project/budgie-desktop/pull/1159

xprop for budgie-desktop-settings under 10.5.2

```
_NET_WM_OPAQUE_REGION(CARDINAL) = 47, 29, 853, 2, 45, 31, 857, 588
_GTK_FRAME_EXTENTS(CARDINAL) = 45, 45, 29, 61
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 25168320, 25168321
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x18009bf
WM_CLIENT_LEADER(WINDOW): window id # 0x1800001
_NET_WM_PID(CARDINAL) = 49080
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "dad-desktop"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 947 by 160
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "budgie-panel", "Budgie-panel"
WM_ICON_NAME(STRING) = "Budgie Desktop Settings"
_NET_WM_ICON_NAME(UTF8_STRING) = "Budgie Desktop Settings"
WM_NAME(STRING) = "Budgie Desktop Settings"
_NET_WM_NAME(UTF8_STRING) = "Budgie Desktop Settings"
```

xprop under budgie desktop 10.5.1

```
_NET_WM_OPAQUE_REGION(CARDINAL) = 47, 29, 858, 2, 45, 31, 862, 588
_GTK_FRAME_EXTENTS(CARDINAL) = 45, 45, 29, 61
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 107026177, 107026178
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x6611700
WM_CLIENT_LEADER(WINDOW): window id # 0x6600001
_NET_WM_PID(CARDINAL) = 10715
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "dad-HP-Pavilion-Notebook"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 952 by 160
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "budgie-desktop-settings", "budgie-desktop-settings"
WM_ICON_NAME(STRING) = "Budgie Desktop Settings"
_NET_WM_ICON_NAME(UTF8_STRING) = "Budgie Desktop Settings"
WM_NAME(STRING) = "Budgie Desktop Settings"
_NET_WM_NAME(UTF8_STRING) = "Budgie Desktop Settings"
```

So the WM_CLASS has changed under 10.5.2 - this obviously now clashes with the budgie-desktop-settings.desktop StartupWMClass= value

However setting StartupWMClass=budgie-panel does resolve the duplicate icons - the remaining of budgie-panel in the dock is puzzling - no quite sure what has changed in this area under 10.5.2

**Comment by fossfreedom** [comment]
@serebit 

Quick question please with regards to your PR https://github.com/solus-project/budgie-desktop/pull/2037

Why was the set_wmclass statement removed as part of the cleanup?

https://github.com/solus-project/budgie-desktop/commit/b2be751b5309473c17ec87ef2bf28e6b150e16ea#diff-18fcc568e79952e006cf4411ef55b661758f3ba65ebd112db33d34377680df08L48

Reverting this bit resolves this particular issue.

**Comment by serebit** [comment]
@fossfreedom I may have misread GTK's documentation on that function in particular, and erroneously believed it was redundant.
