### ISSUE TITLE
solus budgie breaks when installing flatpak

### ISSUE THREAD

**Issue by Demrish** [solus-project/budgie-desktop#2086]
NOTE: This was on a vm. Idk about harddrive

So i installed flatpak for solus. When i reboot it first, made my password incalid, by that i wasnt able to login, once i reboot again it basically shows up the windows blue screen but linux. And this only happened on solus budgie, not mate or kde. Please help

**Comment by JoshStrobl** [comment]
This isn't the support forums for Solus and this wouldn't be a Budgie issue.
