### ISSUE TITLE
External monitor color error

### ISSUE THREAD

**Issue by timemrah** [solus-project/budgie-desktop#2087]
There is a problem with the color standards on the screen that I connected externally to my Ryzen 7 3700U laptop. This error does not vary by monitor brand or model.

At first I thought it was a simple gamma adjustment problem. However, the color accuracy never improved if I tried to use this setting.

Oddly enough, I don't have any problems with all other interfaces except the Budgie interface. I tried this problem of the Budgie interface on Solus, Manjaro and Ubuntu and the result is still the same.

Why can the Budgie interface make the color settings of external monitors so bad?

My screen tests resources
https://laptrinhx.com/5-ways-to-fix-a-stuck-pixel-on-your-screen-1440940953/
(my blue color is very purple on this page)

https://www.simpelfilter.de/en/colorman/gamma_en.html
(on this page square dance)

I am having this problem purely on budgie interface and external monitors only. If you wish, I can take a shot with the camera and send it to you.

**Comment by JoshStrobl** [comment]
Budgie doesn't do anything special related to colors, that'd all be related to Mutter (which GNOME Shell uses as well) or another part of the stack.
