### ISSUE TITLE
Right click menu not working(Context Menu)

### ISSUE THREAD

**Issue by Pyraon** [solus-project/budgie-desktop#2095]
## Description

I can't create folder on desktop. I am not very familiar with the Linux operating system.

## Budgie version

Budgie 10.5.2

## Operating system

Solus Budgie 4.1 Fortitude 64 bit
Gnome version 3.38.3
## Actual result

![20210113_203935](https://user-images.githubusercontent.com/77499735/104808123-2ee07c80-57f5-11eb-8522-535d747d7059.jpg)

## Expected result
![20210113_195847](https://user-images.githubusercontent.com/77499735/104808079-f640a300-57f4-11eb-88e1-4341019eb6f4.jpg)

**Comment by JoshStrobl** [comment]
Budgie Desktop View is the new implementation for desktop icons for Budgie. It's a separate project and creating new files or folders via it is not in its scope or planned. For that, use a file manager.

**Comment by Pyraon** [comment]
Well thank you :)
