### ISSUE TITLE
[Feature] Option for Super key showing start menu or launcher (alt+f2 usually)

### ISSUE THREAD

**Issue by DasJott** [solus-project/budgie-desktop#2098]
### Current Budgie version
budgie-desktop 10.5.2

### Use-cases
Pressing super key opens the menu where you can search and hit enter for opening the uppermost entry.  
The alt+f2 launcher feature is great and some might want to have it on the super key instead.

### Proposal
Have an option in Budgie settings to choose what the super key opens: menu | app launcher

### References
Some might know and love this from Mac.

**Comment by JoshStrobl** [comment]
This is already a hidden feature accessible via gsettings / dconf: com.solus-project-budgie-wm experimental-enable-run-dialog-as-menu

Not going to make it an officially supported feature. Only added it for @DataDrake.

**Comment by DasJott** [comment]
As this is nothing a normal user would urgently need, I am fine with that. Thanks!
