### ISSUE TITLE
alt-tab option to display window-previews only after a certain delay

### ISSUE THREAD

**Issue by astier** [solus-project/budgie-desktop#2100]
### Current Budgie version

budgie-desktop 10.5.2 (git-f0e0f9f1d05c6ce30181d3ff1dca92e864222746)

### Use-cases

I often use alt-tab to switch quickly between the two recently used programs. This mean I press alt-tab only once to switch to the last used window. Since I already now which window this will be I dont want to see the previews of all the windows because it is visually distracting to see a brief flickering of the previews.

### Proposal

Many other DEs have a delay-option for their alt-tab-switchers to display the previews only after a certain time (ex. 200ms). It would be nice if budgie would have such an option too.

**Comment by JoshStrobl** [comment]
> I dont want to see the previews of all the windows because it is visually distracting to see a brief flickering of the previews

I have no idea what you mean by this. Our Alt+Tab implementation doesn't have any preview mechanism.

**Comment by astier** [comment]
If you press alt+tab a small window in the middle of the screen appears which shows a list of the opened windows. This is what I mean with the preview.

**Comment by JoshStrobl** [comment]
Our Alt+Tab implementation just has an icon grid of windows, no previews. It also doesn't switch to a window until you release on the selected application. So no idea what you're talking about still. Maybe would be helpful if you recorded a video showing the issue.

**Comment by astier** [comment]
> icon grid of windows

Thats what I meant when I said previews.

> It also doesn't switch to a window until you release on the selected application

I know. I never said anything contrary.

Let me explain the steps I do and what I think should be changed.

1. Open three windows of any program (ex. browser, terminal and file-manager)
2. Focus first browser by clicking on it with the mouse.
3. Then focus another window ex. terminal by clicking it with the mouse
4. Change focus from terminal to previously focused window (which in this example is the browser) by pressing alt+tab briefly and releasing it quickly

My issue is that the grid-window pops up briefly even if I press and release alt+tab very quick.

I understand thats its the desired behavior that while alt+tab is pressed and not released the grid-window is supposed to be open. However, if I already know that I just want to change the focus to the previously focused window I will press and release alt+tab very fast and I don't need to see the grid-window.

In this case the grid-window is useless, distracting and visually not appealing because it pops up for less than a second. It just flickers briefly on the screen.

My request is that the grid-window only pops-up if alt+tab is pressed and hold after a certain amount of time. It can be very short like like a few hundred milliseconds. Because if I just want to focus previously focused window then I won't hold alt+tab for more than a few hundred milliseconds. However, if I want to switch to another window I will have to hold alt longer and press tab at least two times in which case the grid-window is actually useful because I then can see which window I selected.

**Comment by JoshStrobl** [comment]
Yea there are no plans on supporting this behavior. Thanks for the filed issue though.

**Comment by astier** [comment]
Ok. I can respect that. Just wondering, is there a specific reason you don't like it? I always thought its a small little detail which makes the window-switcher a little bit less obstructive when I was using gnome.
