### ISSUE TITLE
Raven Sound Output Widget & UI Screenshot Issue

### ISSUE THREAD

**Issue by Kuuchuu** [solus-project/budgie-desktop#2103]
## Description
My Raven panel does not show my S/PDIF output in the output widget. I can only change to that specific output through the system sound settings. While attempting to screenshot the issue I found that you also cannot take any screenshots while a drop down menu is open on screen. To get a picture of the drop down menu in the sound settings I had to record my screen with Peek, then take a snapshot of the video's frame in VLC.

## Budgie version
budgie-desktop 10.5.2 (git-481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9)

## Operating system
Solus 4.2 Fortitude

## Steps to reproduce the issue
Open Raven to change sound output, second output not listed.
Open drop down menu in system settings, attempt to take a screenshot.

## Actual result
![Raven](https://user-images.githubusercontent.com/20036947/107711124-bacab480-6c8c-11eb-9907-7e73f61c3c2e.png)
![vlcsnap-2021-02-11-17h07m35s403](https://user-images.githubusercontent.com/20036947/107711125-bacab480-6c8c-11eb-9992-cdc18892908d.png)

## Expected result
All sound outputs listed in Raven widget.
Able to take screenshot regardless of what is on the screen.

**Comment by JoshStrobl** [comment]
That's because we currently exclude S/PDIF outputs because switching to them in the past has been pretty buggy with Gvc. Not really a bug rather intentional, so closing as invalid, but I will re-evaluate this for Budgie 10.5.3.

**Comment by Kuuchuu** [comment]
The issue with screenshots still remains. I have actually found none of my hotkeys seem to work when a system drop-down is active. @JoshStrobl

**Comment by JoshStrobl** [comment]
That isn't a bug and is not relevant to this issue. BudgiePopovers capture keyboard input.
