### ISSUE TITLE
Can't Drag Window when switching workspaces

### ISSUE THREAD

**Issue by prateekmedia** [solus-project/budgie-desktop#2104]
## Description

Don't know if it is a bug or a feature request but still unlike kde or I think gnome, we cound't drag windows when switching workspaces using keyboard shortcuts or with Workspace Switcher.

## Budgie version

budgie-desktop 10.5.2 (git-481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9)
Copyright © 2014-2021 Budgie Desktop Developers

## Operating system

Solus 4.2

## Steps to reproduce the issue

1. open multiple windows
2. Drag window here and there while trying to switch workspace

## Actual result

Window moves but in the same workspace.

## Expected result
Window Should go to the other workspace.

## Additional information
- I think its a bug.

**Comment by JoshStrobl** [comment]
You can drag the icon of a window using the Wnck Workspace applet. The other items aren't in scope for Budgie 10.
