### ISSUE TITLE
Wrong website url in many applets https://budgie-desktop.org/

### ISSUE THREAD

**Issue by prateekmedia** [solus-project/budgie-desktop#2105]
Many Applets like https://github.com/solus-project/budgie-desktop/blob/481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9/src/applets/budgie-menu/BudgieMenu.plugin.in#L7 include https://budgie-desktop.org url which is misleading as website doesn't open/exist.

+ The url in about of this repo is also incorrect it should be getsolus.com

**Comment by JoshStrobl** [comment]
Use the search, this has been filed before.
