### ISSUE TITLE
Error al poner o quitar el applet tray de Gestion de Red.

### ISSUE THREAD

**Issue by gabizzz** [solus-project/budgie-desktop#211]
Al poner o quitar el applet tray de Gestión de Red , provoca que se desplacen los demás applets (setting, clock, sound indicator, etc).﻿

https://plus.google.com/u/0/photos/101427028516468370514/albums/6150747128084038721/6150747130210478434?sqi=104830131595272878110&sqsi=5d22301c-a34b-4aba-8415-a2b687dee751

**Comment by Justinzobel** [comment]
Translation To place or remove the tray applet Network Management, causes other applets (setting, clock, sound indicator, etc.) move.﻿

**Comment by ikeydoherty** [comment]
Closing - we fixed this w/ the rewrite
