### ISSUE TITLE
Inconsistent mouse hovering in some types of files, Ubuntu Budgie 20.10

### ISSUE THREAD

**Issue by UltraBurstXD** [solus-project/budgie-desktop#2110]
## Description

I'm facing some kind of incorrect mouse hovering effect in some files, on Ubuntu Budgie 20.10. The mouse hovering event, should only highlight a little the files, and not obstruct or hide them.

Before hovering:
![Screenshot from 2021-03-08 10-04-02](https://user-images.githubusercontent.com/55871338/110292324-b37d9900-7ff5-11eb-8f13-171e17a0e2d3.png)

After Hovering:
![Screenshot from 2021-03-08 09-22-53](https://user-images.githubusercontent.com/55871338/110292444-e4f66480-7ff5-11eb-8e2d-acc12b1714bc.png)
![Screenshot from 2021-03-08 10-00-27](https://user-images.githubusercontent.com/55871338/110292456-e9bb1880-7ff5-11eb-96c6-5885125bc97a.png)

## Budgie version

budgie-desktop 10.5.1

## Operating system

Ubuntu Budgie 20.10

## Steps to reproduce the issue

1. Just hover on text file or an image

## Actual result

The file is either obstructed or hidden.

## Expected result
The file should only be highlighted a little

## Additional information
I think that it happens in more files types than mentioned above, it's little difficult to know each of them. And some types like *.bmp, etc., aren't highlighted when hovered at all.

**Comment by fossfreedom** [comment]
This is nothing to-do with budgie.  If in doubt raise on UB discourse forum first.

**Comment by UltraBurstXD** [comment]
But I tried with so many themes, and the result is the same...

I think I don't understand why. Perhaps is Nemo issue with theming?

**Comment by UltraBurstXD** [comment]
Since it looks like the issue isn't related to Budgie DE, I'm closing. Nemo seems to be the target.
