### ISSUE TITLE
Bugdie crashes when using vala-panel-appenu and vscode

### ISSUE THREAD

**Issue by misterjupiter** [solus-project/budgie-desktop#2112]
Budgie Desktop crashed when using vala-panel-appmenu and visual studio code with native window settings

## Budgie version
budgie-desktop 10.5.2 (git-481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9)

## Operating system
Solus 4.2

## Steps to reproduce the issue
Add appmenu to the budgie panel. _vala-panel-appmenu 0.7.3_
Open visual studio code . _vscode 1.54.1_
vscode on default settings: "title bar style" = 'native", "menu bar visibility" = 'visible'
Use the app menu on the budgie panel to open a folder in visual studio code.
Notice the budgie panel crashes and restarts
Open another folder in vscode like before
Budgie crashes, full-screen message with a button to log out the user.

## Actual result
budgie session crashes

## Expected result
no crash

## Additional information
no extensions installed in vscode. no settings changed from default.

**Comment by misterjupiter** [comment]
spelll correction

**Comment by JoshStrobl** [comment]
> vala-panel-appmenu

This isn't developed by us. Any issues with third-party applets should be filed with the appropriate developers.

**Comment by rbreaves** [comment]
I think this is still an issue that ought to be looked into considering it is not crashing and restart the panel - it is logging the user out completely. I have had this problem as well. Even if it is caused by Vala-appmeny or VSCode I feel like the exception ought to be handled better. Can we not crash without logging the user out?

As a developer I am considering not making any distro with Budgie as my main driver because I use VSCode a lot and I cannot afford to have my entire session wiped away because of an exception.

**Comment by rbreaves** [comment]
Even though the lack of improved error handling I feel is on the Budgie side here - despite the cause of the crashing being either Vala or VS Code, I will be opening tickets in the appropriate locations. I do not care how or who fixes, or work arounds get implemented, but I would like to see some stability for an issue as severe as one that literally breaks the user space (it immediately causes the user to be logged out at times).

Official support for a particular plugin or not I think most developers would agree that it would be better to catch the error/exception in some way and handle gracefully than to cause an entire user session to be lost. This could impact and effect literally any plugin for the Budgie-panel, particularly ones that would be using DBUS, x11, DE, wayland or other external APIs.

https://gitlab.com/vala-panel-project/vala-panel-appmenu/-/issues/347

**Comment by rbreaves** [comment]
@fossfreedom Indicates the type of memory segmentation fault that occurs isn't something that Budgie can trap or easily trap any ways. Also following up with the Vala author it appears this issue is resolved in the latest 0.7.6, but probably 0.7.5 as well from looking at his release comments.

**Comment by rbreaves** [comment]
Latest dev patch by @fossfreedom seems to have fixed this issue in Ubuntu Budgie 20.04.
