### ISSUE TITLE
Random freezes (Arch Linux)

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#212]
**The panel and various applications freezes randomly, I installed the two versions of Budgie on the AUR ([-git](https://aur.archlinux.org/packages/budgie-desktop-git) and 'not [-git](https://aur.archlinux.org/packages/budgie-desktop)').**

The applications that freezes are:
Chromium (and also a Whatsapp session running under ARC Welder)
Spotify
VLC
Cheese
LibreOffice

I don't know if the problem is my hardware or the desktop environment:
- CPU: Dual core AMD E-300 APU with Radeon HD Graphics, 1024 KB cache
- 1,7 Gb RAM memory
- Graphics card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6310]

**Comment by Justinzobel** [comment]
Are you running budgie-wm or another window manager?

**Comment by feskyde** [comment]
budgie-wm, it is a fresh Budgie installation, I only added the applications

**Comment by feskyde** [comment]
I don't know if this information is useful, but when I run applications from terminal they don't freeze

**Comment by feskyde** [comment]
Another 'little' problem, the entire desktop crashes and send me to LigthtDM again randomly

**Comment by Justinzobel** [comment]
The desktop crashing and sending you back to lightdm is because part of budgie-sessiion (wm/panel) died and restarted, once something has crashed 3 times, on the 4th time it'll restart the session. @ikeydoherty is a bit sick at the moment so once he feels better he'll hopefully be able to help you diagnose what's happening.

**Comment by feskyde** [comment]
Thanks! And I hope he recovers soon.

**Comment by X0rg** [comment]
I have random freezes on Arch Linux me too.

It occurs in application like Firefox, but particularly in Cairo-Dock.
If I move my mouse over Cairo-Dock's dock, the dock is frozen and I need to wait to use it again.

**Comment by feskyde** [comment]
Firefox also freezes on Solus (with my hardware)

**Comment by libcg** [comment]
Spotify and Firefox are randomly freezing here too. I'm using Arch Linux.

**Comment by feskyde** [comment]
And still occurs

@ikeydoherty any idea to resolve this?

**Comment by libcg** [comment]
When using GNOME 3.17 from [gnome-devel] and rebuilding budgie against it, I couldn't reproduce it.

**Comment by ikeydoherty** [comment]
Which Solus are you using @feskyde  ?

**Comment by feskyde** [comment]
After 2 weeks, none. But i used the Stable version and installed the desktop on Arch Linux (from AUR, -git version, as i said above)

**Comment by ikeydoherty** [comment]
Fixed in v10

If you believe it to still be an issue, reopen

**Comment by feskyde** [comment]
Thanks Ikey :grin:, I will test it on the next days
