### ISSUE TITLE
Shutdown buttons not working after opening Budgie Setiings

### ISSUE THREAD

**Issue by elkrien** [solus-project/budgie-desktop#2125]
## Description

On Arch Linux, the Budgie settings now opens (after last update), but once this screen is open and next closed, it is not possible to perform a shutdown, login out or reboot, unless it is done from the terminal. After computer reboot all works OK until You again open Budgie settings.

## Budgie version

10.5.2

## Operating system

Arch Linux

## Steps to reproduce the issue

Open Budgie Setting and then try to log out, reboot or shutdown computer

## Expected result
Shutdown, logout, restart etc. buttons should work even You open Budgie Settings

**Comment by JoshStrobl** [comment]
Unable to reproduce issue using latest master of Budgeie. Reboot / restart function continues to work after Budgie Desktop Settings is opened and subsequently closed.

Please follow https://github.com/solus-project/budgie-desktop/wiki/Providing-Backtraces

**Comment by JoshStrobl** [comment]
Closing due to lack of response.
