### ISSUE TITLE
Panel on the left covers desktop icons.

### ISSUE THREAD

**Issue by ChristiaanWewer** [solus-project/budgie-desktop#2127]
Hello, when I put my panel on the left, it covers the desktop icons. I don't think this is necessarily a bug, but more something that hasn't been dealt with yet.
![left bar](https://user-images.githubusercontent.com/31652362/115008639-a5038680-9eab-11eb-90ed-85aa469121f0.png)
Would be nice to get a fix!
Cheers,
Chris

**Comment by JoshStrobl** [comment]
Duplicate. Use the search.
