### ISSUE TITLE
Can't launch Firefox and Firefox flatpak from the menu

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#2131]
## Description

Can't launch Firefox and Firefox flatpak from the Budgie menu **at the same time**. I have two Firefox items in the menu and if I have Firefox (from Solus repo) running, click on the Firefox flatpak icon just opens another window of the Firefox (from Solus repo) and vice versa.

Additional info: I had to reinstall Firefox (from Solus repo) because its profile was corrupted.

I installed qbittorrent (flatpak) and the qbittorrent from Solus repo is gone from the menu. Only flatpak version icon is there

## Budgie version

budgie-desktop 10.5.2 (git-481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9)

_____

>Not considered a bug. They both provide the same DesktopAppInfo, you need to choose one (by means of uninstalling the other).

But it works on another two installations.

**Comment by JoshStrobl** [comment]
You have already filed this before. https://github.com/solus-project/budgie-desktop/issues/1942

**Comment by Solarunit** [comment]
@JoshStrobl yes, but it is a different issue. I can't launch from the **Budgie menu** (not a Panel). It possible on my another installation.

**Comment by JoshStrobl** [comment]
They both use the same DesktopAppInfo from GLib. As I noted in the forum post, this is **not** considered a bug. Whether it is from flatpak or not, they are both the same providers of the DesktopAppInfo and entries provided by libgnome-menus. Until there is either a mechanism to differentiate the sources of the software, they can't be listed or handled differently.

**Comment by Solarunit** [comment]
I understand. Why then It works fine on my other two installations right now?  :thinking: 
I there a way maybe to reset the Budgie menu, like a Panel?

**Comment by JoshStrobl** [comment]
@Solarunit resetting the panel is not going to change the behavior of the `GMenu.Tree` call. Stil considering this as a duplicate of the other issue.

**Comment by Solarunit** [comment]
@JoshStrobl btw I tried to run Firefox flatpak from the terminal:

`/usr/bin/flatpak run org.mozilla.firefox`

it opens another instance of the Firefox (Solus version) if its already running. 
Is there any workarounds?
