### ISSUE TITLE
meson: Incorrect assert for Budgie Screensaver

### ISSUE THREAD

**Issue by gmbr3** [solus-project/budgie-desktop#2133]
# Version
Git master (12eec71e469c697d71fd4d1b0b6df17b24f335c9)
# OS
@openSUSE Tumbleweed build worker
Meson 0.56.2
# log
meson.build:15:0: ERROR: Assert failed: Budgie Screensaver is a required separate component of Budgie Desktop. Please ensure budgie-screensaver is available at configure and run time. You can find this at https://github.com/getsolus/budgie-screensaver
[Full log](https://github.com/solus-project/budgie-desktop/files/6393333/1619568000-log.txt)

**Comment by JoshStrobl** [comment]
Doesn't seem like a Budgie issue. Make sure you are using the most recent version of budgie-screensaver, which is version v4.0. This includes the required budgie-screensaver binary, which is what we check.

Packaging works fine under Solus and there has been no reported issues of it on Arch either.
