### ISSUE TITLE
[Problem] Resetting keybind settings for change the language layout on reboot

### ISSUE THREAD

**Issue by wizerer** [solus-project/budgie-desktop#2134]
budgie-desktop --version
## Description
There is a problem when setting one button (such as the 'Pause' key in my case) to change the language layout of the keyboard. After setting the switch key the keyboard layout switching works as usual, but only during the current work session. After rebooting the system, the switching setting is reset on default ('Super' + 'Space'). At the same time, in the system settings (graphic window) in the appropriate field the value set earlier (Pause) is shown.

Console command `gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['Pause']"` does not help either.

Actually, the problem appeared back during the summer update (in 2020). I feared that the update might have been crooked, but a clean installation of the system still has the related "one-button" keyboard layout switching problem.

## Budgie version
budgie-desktop 10.5.2

## Operating system
Solus 4.2

## Steps to reproduce the issue
1. Set the keyboard shortcut to switch the language in the settings to one key (e.g., 'Pause').
![VirtualBox_Solus_29_04_2021_12_06_12](https://user-images.githubusercontent.com/83385813/116505196-7c847f00-a8e4-11eb-9fcf-0f474bd8cc6b.png)
2. Check the possibility of switching. [It works!]
3. Restart the system.
4. Check the possibility of switching. [It doesn't work!]
5. Try using the `'Super' + 'Space'` key combination to switch the layout. [It works! O_o]

## Actual result
This resets the user's keybinding settings to their default state. There is a suspicion that this applies not only to the key binding to change the language layout, but also to other dependencies.

## Expected result
Saving user settings by keybindings.

**Comment by guillotjulien** [comment]
Confirming the behavior, changing the shortcut for input switching results in shortcut being reset after a restart of budgie wm.  

This doesn't seem to affect other shortcuts, tested with `Home folder` (no default shortcut) and `Launch help browser` (default shortcut Super+F1) and a few others.

However, manually setting the shortcut, using e.g. `gsettings set com.solus-project.budgie-wm switch-input-source "['<Super>Z']"` result in shortcut not being reset when restarting budgie-wm.
