### ISSUE TITLE
URL for this github project does not work: solus-project.com

### ISSUE THREAD

**Issue by gsfjohnson** [solus-project/budgie-desktop#2135]
## Description
URL for this github project does not work: solus-project.com

## Budgie version
N/A

## Operating system
N/A

## Steps to reproduce the issue
1. Open url: https://github.com/solus-project/budgie-desktop/
2. Click on link, top of right column of the page: solus-project.com.

## Actual result
![Screenshot from 2021-05-01 09-37-16](https://user-images.githubusercontent.com/9522664/116788892-fccfef00-aa60-11eb-92c7-98389278c309.png)

**Comment by EbonJaeger** [comment]
Sadly, it can't be changed. See #1806 (and any of the other issues for the same thing).
