### ISSUE TITLE
Hibernate and suspend seem broken on my machine

### ISSUE THREAD

**Issue by filipedeluna** [solus-project/budgie-desktop#2136]
## Description
1 - Suspend and hibernate do not work. They simply lock the user session.
2 - AppMenu Power Strip should have hibernate option, as well.

## Budgie version
budgie-desktop 10.5.2

## Operating system
Ubuntu Budgie

## Steps to reproduce the issue
1 - Click the hibernate/suspend option on the budgie desktop panel, user indicator applet.

## Actual result
Locks user session, keeping the computer on.

## Expected result
Hibernate or suspend the computer.

## Additional information
I recently upgraded from UB 20.10 to 21.04 and it stopped working, along with a few other things.

systemctl hibernate seems to just shut down the machine.

**Comment by JoshStrobl** [comment]
Suspend and hibernation work properly under Solus. Not considering this to be a Budgie issue.
