### ISSUE TITLE
Mobile "window" mode

### ISSUE THREAD

**Issue by RossComputerGuy** [solus-project/budgie-desktop#2142]
### Current Budgie version

10.5.3

### Use-cases

Devices such as the PinePhone and Librem 5

### Proposal

Checking the DPI or the usable space on the display, windows could be constrainted to a fixed maximized size to fit on mobile screens. I can work on this feature if nobody wants to and implement it into a fork for my OS, ExpidusOS.

### References

* [Device identification library](https://github.com/ExpidusOS/libdevident)

**Comment by JoshStrobl** [comment]
Budgie is designed for modern desktop environments and respective form factors. I have no desire or plans on supporting any mobile operating systems, devices, or form factors.
