### ISSUE TITLE
Second monitor is unusable in top/bottom configuration

### ISSUE THREAD

**Issue by locque** [solus-project/budgie-desktop#2143]
## Description
I've put my second monitor above my primary monitor instead of the the right of it and configured the gnome display settings accordingly, but now I can't use it anymore. I could move windows between monitors using the Super+Shift and Horizontal Arrows or by dragging the window across in the left/right monitor configuration. Neither option works in the top/bottom configuration though.

Dragging the window up to the second monitor does nothing, there is a hard stop at the top border of my primary monitor. The cursor keeps moving, but the window is stuck on the bottom monitor. Super+Shift+Up aligns the window with the top monitor, but doesn't actually move it to that monitor.

This only happens when the bottom monitor is the primary monitor. When I set the top monitor the be the primary monitor, I can move the windows up and down.

### Update

Found the culprit, it's the Budgie panel.

It can't be between the two monitors, or this will happen. The panel has to be at the bottom of the bottom monitor, or the top of the top monitor. 

This is not the only issue that occurs when that rule is broken either. If there is a window on the secondary monitor already and you then move the panel in between the monitors, all hell will break loose on the second monitor. Dropdown menus will appear in random places instead of where they were triggered, and you can't move windows anymore since they will align themselves to misplaced screen boundaries near the center of the second monitor. You can't maximize or resize windows anymore either.

## Budgie version
10.5.3

## Operating system
Arch x86_64, updated on 24th of May 2021

## Steps to reproduce the issue
- Put secondary monitor above primary monitor in gnome display settings
- Make sure there is either a top panel on the bottom monitor or a bottom panel on the top monitor
- Try to move a window from the primary the the secondary monitor

## Actual result

Before pressing Super+Shift+Up: https://i.imgur.com/8m2rIZM.png

And after: https://i.imgur.com/PBUPUxg.png

## Expected result

Can't show this since it's impossible to get a window onto the second monitor by any means.

## Additional information

Primary Monitor: ASUS VH242, 1920x1080, 24"
Secondary Monitor: BenQ FP93GX, 1280x1024, 19"
Gnome shell version: 40.1
Gnome display settings: https://i.imgur.com/QKejNji.png

**Comment by JoshStrobl** [comment]
Other issues filed for this. Use the search. Thanks.
