### ISSUE TITLE
App launcher icon offset

### ISSUE THREAD

**Issue by TheCultLeader666** [solus-project/budgie-desktop#2150]
## Description

When you hover over the app launcher with certain themes, you'll see that the icon is offset to the left compared to the highlighted region

## Budgie version

budgie-desktop 10.5.3

## Operating system

EndeavourOS

## Steps to reproduce the issue

Apply a theme that highlights hovered elements on the panel, then hover over the app launcher an see that it is offset

## Actual result

![image](https://user-images.githubusercontent.com/65368815/123266051-a6fc4e00-d4c9-11eb-8c4b-f4505f5c8cad.png)
(I have tested with multiple icon sets and themes)

## Expected result
The icon for the app launcher will appear in the center of the highlighted region.

## Additional information
N/A

**Comment by JoshStrobl** [comment]
Doesn't happen with Plata and this should be filed with the respective theme developers.
