### ISSUE TITLE
Area of notification greater than the notification box itself

### ISSUE THREAD

**Issue by sammypanda** [solus-project/budgie-desktop#2155]
## Description
Notifications have a greater area than their background suggests :)

## Budgie version
Budgie 10.5.3

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
Get a notification and try to interact with the top right of the screen (around and in the drop-shadow)

## Actual result
Attempting to interact with stuff around the notification doesn't work which makes the notification feel a lot more intrusive than it needs to be.

## Expected result
Be able to interact with things in the shadow and around the notification such as the exit/minimize/maximize buttons.

## Additional information
Lots of love <3 Solus Budgie is awesome, keep up the good work! (^^)

**Comment by JoshStrobl** [comment]
That is because the shadow is still considered part of the notification, you can't click through it.
