### ISSUE TITLE
Lock screen unlocks on multi monitor setups after powering off one screen.

### ISSUE THREAD

**Issue by Alderaeney** [solus-project/budgie-desktop#2156]
## Description

When locking the screen on a multi monitor setup, if you turn off one of the screens, the lock screen will disappear and unlock itself back to the desktop.

## Budgie version

10.5.3

## Operating system

Solus Budgie 4.3

## Steps to reproduce the issue

1.- Lock the screen
2.- Power off one screen

## Actual result

 Lock screen disappears and you get back to the desktop

## Expected result
Lock screen will remain open and you'll need the password to go back to the desktop.

**Comment by JoshStrobl** [comment]
Should be filed at https://github.com/getsolus/budgie-screensaver
