### ISSUE TITLE
Flameshot app broken since last update

### ISSUE THREAD

**Issue by victoriobn** [solus-project/budgie-desktop#2157]
Flameshot app is broken since the last Solus update. I'm getting this error ever since:

```
victoriobn@solus4 ~ $ flameshot 
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
Segmentation fault (core dumped)
```
Could you please verify this? thanks in advance. Didn't find a Bug flag in the forum.
Best

**Comment by guillotjulien** [comment]
This should be created at https://dev.getsol.us as this doesn't seems to be related to Budgie.
