### ISSUE TITLE
How to hibernate ? 

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#216]
Hello world !
Firstly, good work for Budgie ! This is a nice desktop environment and i use it from my archlinux. :)

My issue is simple, can i hibernate with Budgie ? 

When i make: sudo systemctl hibernate with other DE, my PC hibernate with success. With Budgie desktop, after hibernation the desktop freeze. (the windows don't move)

Can you tell me the nature of this problem ? :/ Have you already try to hibernate with Budgie ? 

Thx for read this post and sorry for my bad english. :)

**Comment by X0rg** [comment]
Hi Maximilien.

I'm an Arch user too, and I use Budgie. I run 'systemctl hibernate' as regular user, it works.
On resume, I don't have any problem.

But +1, Hibernation button is missing in power menu. We want it. :)

[Des français qui se parlent en anglais, on a l'air malin. ^^]

**Comment by MaximilienLIX** [comment]
Ok thx for your answer ! (oui très malin xD)

**Comment by X0rg** [comment]
I'm not a Budgie developer, if you use french, the main developer will not be able to help you. ;)

Try to open a topic on ArchLinuxFr forum (if it is a resume issue). I don't know if it's a Budgie specific problem, or a problem with your Arch. We need to check when system crash on your computer at resume time.

**Comment by MaximilienLIX** [comment]
Ok :) I'm going on archlinuxfr forum ^^
