### ISSUE TITLE
Where are the dotfiles? 

### ISSUE THREAD

**Issue by onkoe** [solus-project/budgie-desktop#2160]
Hello, sorry if this is a bit of a dumb question. However, I've been Googling for some time and haven't found an answer. I am currently trying to share one coherent "theme" across all my devices. I already have a script that installs all the required assets, but in Budgie, I currently have to configure everything manually though budgie-desktop-settings or with gsettings commands. If there is a way to backup one config file from a place like ~/.config, I would love to know more about it! Such a feature would be super nitfy to help share my themes with others. Thanks for the great project!

**Comment by JoshStrobl** [comment]
We don't use "dot files", everything is stored via dconf and thus you'll need to use dconf dump + load to back up Budgie and GNOME Settings.
