### ISSUE TITLE
Introduce different power profiles for laptops 

### ISSUE THREAD

**Issue by Metaberg** [solus-project/budgie-desktop#2166]
### Current Budgie version

budgie-desktop 10.5.3 (git-978ba229c884d56888e8b368885a9b6d23308134)

### Use-cases

In order to achieve an optimal performance / battery life for different work situations, it would be helpful if you could switch between 2 to 3 modes.

* Battery saving
* Balanced
* Performance

### References

Similar implementations were used by System 76 (system76-power) and by the GNOME project (power-profiles-daemon )

**Comment by JoshStrobl** [comment]
Not really in the scope for Budgie 10 series, this would need to be in whatever daemon we would have for 11.x.
