### ISSUE TITLE
Windows incorrectly snap when moving to monitor above bar

### ISSUE THREAD

**Issue by tstivers1990** [solus-project/budgie-desktop#2169]
Create a dual monitor layout with one monitor on top of the other, and a top bar on the bottom monitor.
Upon dragging a window to the top monitor, you are unable to properly control the window's position.

The window will either snap to a left or right position. But you are unable to maximize the window or otherwise properly control it.

This is with the latest version of Solus Budgie with all updates installed at the time of this issue, on a fresh install with no additional software.

**Comment by tstivers1990** [comment]
I have a monitor configuration with a row of 3 monitors and a row of one monitor above it, in the center. That's the configuration I encountered the odd window snapping with. When I configured my monitors such that they were all stacked, with one on top of the monitor containing the top bar, it wasn't possible to move a window past the top bar and onto the top monitor at all.

**Comment by tstivers1990** [comment]
Seems related to #474

**Comment by JosephMcc** [comment]
Just a quick thought for whoever looks into this. I fixed a very similar issue in another WM. It was down to the panel strut not being sized properly when it was located at the top of the monitor. The strut was actually covering the entire monitor above the panel preventing the window from moving there and being interacted with properly.

**Comment by JoshStrobl** [comment]
Duplicate. Use the search in the future, thanks.

**Comment by tstivers1990** [comment]
> Duplicate. Use the search in the future, thanks.

A dismissive attitude isn't very welcoming to community contribution.

**Comment by JoshStrobl** [comment]
Nobody is being dismissive. It was mentioned that was it was a duplicate. I asked for you to use the search. No reason to read into things.

**Comment by tstivers1990** [comment]
The behavior I experienced and described isn't described in the issue I referenced. I only realized it after trying to eliminate other factors to try and narrow down the cause to provide more useful information.

It is dismissive when you tell someone to use the search to find an issue they already referenced as *related*.
