### ISSUE TITLE
Override "Gtk/ShellShowsAppMenu" as default

### ISSUE THREAD

**Issue by tista500** [solus-project/budgie-desktop#217]
Greetings,

As known well, Gnome3 apps have 2 types of context-menus, 1st is a standard menu and 2nd is a **AppMenu**. In general, once "org.gnome.Shell' dbus name had been called, g-s-d wants to try setting the key "Gtk/ShellShowsAppMenu" whereever apps are (meant to be inside/outside of Gnome-Shell session). if so, GtkMenubar was hidden and all of AppMenu's contents would be placed into context menus of Gnome-Shell's AppIcon.

![Image of AppMenu](http://3.bp.blogspot.com/-CssfIqYJULc/USeVanQHvZI/AAAAAAAAOEU/x7oGlaoFMbE/s1600/gnome-shell-appmenu.png)
(An image from webupd8)

### Issue

Then in budgie, since there's no place to contain such AppMenu, pure-Gnome3 apps would lost these AppMenus (were always hidden).

### Workaround

We can call override from gsettings:
`gsettings set org.gnome.settings-daemon.plugins.xsettings overrides '@a{sv} {"Gtk/ShellShowsAppMenu": <int32 0>}'`

Regards,
Tista

**Comment by ikeydoherty** [comment]
The Shell App Menu is hidden by default on Solus, we can't control the defaults of other distributions. What are you suggesting?

**Comment by tista500** [comment]
Oh I'm sorry that's ubuntu specific problem...

Regards.

**Comment by ikeydoherty** [comment]
Is there a way we can fix it for other distros.. ?

**Comment by tista500** [comment]
@ikeydoherty I now think hook this override can be included in installation (by making debian/budgie.postinst script). but if you could, it'd be nice to check it and control in budgie-session, so we can switch some DEs side by side dynamically.

Regards.

**Comment by ikeydoherty** [comment]
So a post-install wouldn't work here, we need to affect the users settings.
One possibility is providing a gsettings schema override, but this affects all users.
The downside obviously is this becomes a permanent setting, and would affect
all Mutter-using desktops on your system.

The last part of the issue is that xsettings is the domain of GNOME Settings Daemon too, so we can't even force the change ourselves..

**Comment by tista500** [comment]
OK. sounds hard to solve..
So sorry for disturbing you.

Regards.

**Comment by ikeydoherty** [comment]
No need to be sorry :] Bouncing ideas back and forth..
