### ISSUE TITLE
Outdated link in repo details

### ISSUE THREAD

**Issue by SmiVan** [solus-project/budgie-desktop#2172]
## Description

The repository details website [here on github](https://github.com/solus-project/budgie-desktop) is set as `https://solus-project.com/`, which does not lead anywhere.
It should probably be changed to `https://getsol.us/` instead.

_Similar issue may be present in other repos, and in particular is present on the [organisation page](https://github.com/solus-project)._

**Comment by guillotjulien** [comment]
Duplicate of #1806, unfortunately nobody have access to change it after the previous project lead left the project. New Solus projects are under the getsolus organization.
