### ISSUE TITLE
Using different window manager

### ISSUE THREAD

**Issue by massimilianobaldo** [solus-project/budgie-desktop#2176]
### Current Budgie version
Arch + Budgie 10.5.3

### Use-cases
I wanna know if is possible to use a different wm with the budgie desktop.
All the features are grates, but for example I want to use a tiling window manager (like Xmonad or even i3) for better productivity.
I try to use gnome session or even the flag *--replace* but the gnome session crash with the only option to log out.

**Comment by JoshStrobl** [comment]
No.
