### ISSUE TITLE
Black Wallpaper/Background

### ISSUE THREAD

**Issue by BatteryDie** [solus-project/budgie-desktop#2178]
## Description
Wallpaper/Background is black. Changing it though gnome setting do not works. 

## Budgie version
budgie-desktop 10.5.2

## Operating system
Debian GNU/Linux 11 (bullseye)

## Steps to reproduce the issue
I installed Debian without DE. I logged and installed budgie-desktop and lightdm via Debian repo on apt-get.

When I logged again, it shows black wallpaper/background. Changing it though gnome setting do not works.

## Actual result
![Screenshot from 2021-10-19 23-38-33](https://user-images.githubusercontent.com/13942195/138024473-8856f80c-518f-461b-9155-7686452c547d.png)

**Comment by JoshStrobl** [comment]
Please use an up-to-date version of Budgie Desktop

**Comment by JoshStrobl** [comment]
No idea, we don't package Budgie Desktop for Debian. You likely need to use a newer version of Debian or a more modern operating system, like Solus.

**Comment by BatteryDie** [comment]
I upgraded to Debian 12 Bookworm (latest version for testing state) from Debian 11 Bulleye (latest version for stable state). I successfully installed Budgie 10.5.3 from Debian testing repo but it still do not resolve black wallpaper issue.

![Screenshot from 2021-10-20 12-58-59](https://user-images.githubusercontent.com/13942195/138138120-db77d920-7f8c-4074-a264-60b97d39cc7d.png)
