### ISSUE TITLE
Building on Fedora 22

### ISSUE THREAD

**Issue by gibranlavigne** [solus-project/budgie-desktop#218]
Hello! I'd like to ask whenever something can be done to fix make.
i can't completion to compile budgie-desktop source, Part of my "make" output:

> Making install in rundialog
> make[1]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/rundialog'
> make  install-am
> make[2]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/rundialog'
>   CC       budgie_run_dialog-RunDialog.o
> RunDialog.c: In function ‘budgie_run_dialog_search_applications’:
> RunDialog.c:1377:11: error: too many arguments to function ‘g_desktop_app_info_search’
>   _tmp5_ = g_desktop_app_info_search (_tmp3_, &_tmp4_);
>            ^
> In file included from RunDialog.c:23:0:
> /usr/include/gio-unix-2.0/gio/gdesktopappinfo.h:170:11: note: declared here
>  gchar *** g_desktop_app_info_search (const gchar *search_string);
>            ^
> RunDialog.c:1377:9: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
>   _tmp5_ = g_desktop_app_info_search (_tmp3_, &_tmp4_);
>          ^
> RunDialog.c:1378:9: warning: assignment from incompatible pointer type [-Wincompatible-pointer-> types]
>   search = _tmp5_;
>          ^
> Makefile:524: recipe for target 'budgie_run_dialog-RunDialog.o' failed
> make[2]: *** [budgie_run_dialog-RunDialog.o] Error 1
> make[2]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/rundialog'
> Makefile:657: recipe for target 'install' failed
> make[1]: *** [install] Error 2
> make[1]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/rundialog'
> Makefile:474: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

so.. how to fix this problem? i hope you can help me now to completion installing proccess.
thank you :)

**Comment by gibranlavigne** [comment]
i just try to disable rundialog installation, with this:
> ./configure --disable-rundialog && make && sudo make install

but, after it all i got the new problem :

> make[2]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/budgie-plugin'
> make[1]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/budgie-plugin'
> Making install in panel
> make[1]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/panel'
> make  install-recursive
> make[2]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/panel'
> Making install in applets
> make[3]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets'
> Making install in budgie-menu
> make[4]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets/budgie-menu'
> make[5]: Entering directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets/budgie-menu'
>  /usr/bin/mkdir -p '/usr/local/lib/budgie-desktop'
>  /bin/sh ../../../libtool   --mode=install /usr/bin/install -c   libbudgiemenuapplet.la '/usr/local/lib/budgie-desktop'
> libtool: install: error: cannot install `libbudgiemenuapplet.la' to a directory not ending in /usr/lib64/budgie-desktop
> Makefile:474: recipe for target 'install-pkglibLTLIBRARIES' failed
> make[5]: *** [install-pkglibLTLIBRARIES] Error 1
> make[5]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets/budgie-menu'
> Makefile:694: recipe for target 'install-am' failed
> make[4]: *** [install-am] Error 2
> make[4]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets/budgie-menu'
> Makefile:418: recipe for target 'install-recursive' failed
> make[3]: *** [install-recursive] Error 1
> make[3]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/panel/applets'
> Makefile:704: recipe for target 'install-recursive' failed
> make[2]: *** [install-recursive] Error 1
> make[2]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/panel'
> Makefile:861: recipe for target 'install' failed
> make[1]: *** [install] Error 2
> make[1]: Leaving directory '/home/gibran/Repository/Github/budgie-desktop/panel'
> Makefile:474: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

**Comment by ikeydoherty** [comment]
Need to make clean. Re: Vala build issue, that's going to be dependent on your distributions Vala version unfortunately.
