### ISSUE TITLE
Onboard keyboard hardcrashes pc on  5120X1440 resolution

### ISSUE THREAD

**Issue by equareo** [solus-project/budgie-desktop#2182]
I use updated Solus Budgie (Stable)

Starting onboard keyboard with my  5120X1440  screen results in a hard crash due to it being above 32767 pixels. It's a gnome shell [issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3645).

![image](https://user-images.githubusercontent.com/8501648/139652953-2928338a-3560-42c8-9fee-a99b6296850e.png)

I assume the bug can be avoided if the app isn't launched at full screen by default.

**Comment by JoshStrobl** [comment]
Not a Budgie issue. We aren't responsible for Mutter development and Budgie isn't based on GNOE Shell.
