### ISSUE TITLE
budgie-polkit-dialog block all keyboard shortcuts

### ISSUE THREAD

**Issue by Drsheppard01** [solus-project/budgie-desktop#2186]
## Description

budgie-polkit-dialog block all keyboard shortcuts (for example change keyboard layout)

## Budgie version

Budgie-Desktop 10.5.3-240

## Operating system

Solus 4.3

## Steps to reproduce the issue

1. Enable auto input
2. Open the browser or any software which uses Electron
3. Probe change layout

## Actual result

Nothing happened

**Comment by JoshStrobl** [comment]
Yes, this is intentional.

**Comment by Drsheppard01** [comment]
Perhaps you should add a switch keyboard  layout button?
