### ISSUE TITLE
Automatic Hiding of Bottom Panel Fails

### ISSUE THREAD

**Issue by benjoshyo** [solus-project/budgie-desktop#219]
So I have this issue, I like my panels to hide themselves automatically, but with beta 2 when I enable this feature and the panel is at the bottom, It hides itself in the middle of my screen. When I disable it afterwards it stays in the middle of the screen. If I change it to the sides or top and then back to the bottom it goes back to the bottom. The automatic hiding works when the panel is on either side or the top.﻿

**Comment by ikeydoherty** [comment]
The feature will be rewritten as it was too derpy. We're going to add window dodge in future instead. Closing this as the feature is gone for now
