### ISSUE TITLE
Screen freezes while scrolling fast ( mouse pointer still works )

### ISSUE THREAD

**Issue by Arghya-019** [solus-project/budgie-desktop#220]
Whenever i try to scroll fast in any application like mozilla , gedit or even the terminal the desktop screen freezes for some minutes and sometimes even permanently. i have to reboot to work. It works ok if i scroll slowly.

This is my system info ::

# inxi -F
Resuming in non X mode: glxinfo not found. For package install advice run: inxi --recommends
System:    Host: gablu Kernel: 4.0.3 x86_64 (64 bit) Desktop: Gnome 
           Distro: Solus Operating System Beta 2 
Machine:   System: Dell product: Inspiron N5110
           Mobo: Dell model: 0FXK2Y v: A11 Bios: Dell v: A11 date: 08/03/2012
CPU:       Dual core Intel Core i5-2430M (-HT-MCP-) cache: 3072 KB 
           Clock Speeds: 1: 799 MHz 2: 799 MHz 3: 799 MHz 4: 799 MHz
Graphics:  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           Card-2: NVIDIA GF108 [GeForce GT 540M]
           Display Server: N/A drivers: nouveau,intel (unloaded: fbdev,vesa)
           Resolution: 80x24
Audio:     Card-1 NVIDIA GF108 High Definition Audio Controller 
           driver: snd_hda_intel 
           Card-2 Intel 6 Series/C200 Series Family High Definition Audio Controller 
           driver: snd_hda_intel 
           Sound: Advanced Linux Sound Architecture v: k4.0.3
Network:   Card-1: Realtek RTL8101E/RTL8102E PCI Express Fast Ethernet controller
           driver: r8169
           IF: enp5s0 state: down mac: 18:03:73:a5:53:25
           Card-2: Intel Centrino Wireless-N 1030 driver: iwlwifi
           IF: wlp9s0 state: up mac: 4c:80:93:1b:28:3f
Drives:    HDD Total Size: 500.1GB (73.2% used)
           ID-1: /dev/sda model: WDC_WD5000BPVT size: 500.1GB
Partition: ID-1: / size: 77G used: 4.4G (7%) fs: ext4 dev: /dev/sda1 
Sensors:   System Temperatures: cpu: 50.0C mobo: N/A gpu: 47.0 
           Fan Speeds (in rpm): cpu: N/A 
Info:      Processes: 157 Uptime: 39 min Memory: 488.1/3872.1MB Init: systemd 
           Client: Shell (bash) inxi: 2.1.28

**Comment by Justinzobel** [comment]
Both NVIDIA and Intel drivers loaded and I'm not sure Solus is ready for
the dual graphics thing yet. Try disabling one or the other by doing the
following:

sudo nano /etc/modprobe.d/blacklist.conf and put in the file either of the
following, nouvea = nvidia dedicated card, intel = integrated gfx (low
power):
blacklist nouvea
blacklist intel

Then save and reboot and let us know if the issue continues.

**Comment by ikeydoherty** [comment]
Believed to be fixed in v10, if not, please re-open.
