### ISSUE TITLE
No gdm Entry for Budige Desktop

### ISSUE THREAD

**Issue by niyasc** [solus-project/budgie-desktop#221]
I'm using Fedora 21 Workstation. I was able to compile all source files. Then I installed bugie-desktop using `make install` command. It also executed successfully.
But I was not able to find an entry for budgie desktop in gdm. Is there anything extra that I need to do for making budgie-desktop entry in gdm?

**Comment by ffhaddad** [comment]
It's possible the path(s) in the xsession configuration for the Budgie session are incorrect.  Look for a file budgie-desktop.desktop (probably in /usr/share/xsessions). Once found, correct the path to the budgie-session binary for the tags TryExec and Exec.  budgie-session should already be in the path, so you can probably just remove the directory entirely.

**Comment by MaximilienLIX** [comment]
Hello, i'm a archlinux user and i've this .desktop file for budgie.

```
[Desktop Entry]
Name=Budgie Desktop
Comment=This session logs you into the Budgie Desktop
Exec=/usr/bin/budgie-session
TryExec=/usr/bin/budgie-session
Icon=
Type=Application
DesktopNames=Budgie;GNOME

```

**Comment by Justinzobel** [comment]
@niyasc ls -l /usr/share/xsesssions/ please

**Comment by niyasc** [comment]
There was no budgie desktop entry in /usr/share/xsessions .
So I added an entry with content provided by @MaximilienLIX and then changed executable path to provide proper location.

It works.. Thanks for the support.

But, it is not as beautiful as budgie desktop in Solus OS. There is no background and menu is looking ugly. Moreover partitions are not mounting properly. In GNOME when I mount a partition using Nautilus, it asks for password. But in budgie, it directly shows not authorized message.

**Comment by Justinzobel** [comment]
You can set background by right clicking.

The menu is based on what theme you have set. Right click on panel and go
into preferences and change it.

**Comment by ikeydoherty** [comment]
If there is no entry in `/usr/share/xsessions` I would suggest it wasn't installed correctly.

Always ensure you provide `--prefix=/usr` to the `./autogen.sh` script, or `./configure` run.
For your polkit issues (asking for password) I'd recommend looking for `polkit-gnome`, which is what we're using within Solus.

Also ensure you have `gnome-settings-daemon` installed to handle settings management, `gnome-control-center` for extra settings (we integrate with GNOME stack). And a decent GTK theme! :) (Arc, EvoPop, Vertex, etc.)

Last but not least, it's a sad fact that Budgie will always be a inferior on other distributions. It's built for and with Solus, and that is the native home of the Budgie :] However with a bit of work you can get there
