### ISSUE TITLE
Menu selection is not highlighted

### ISSUE THREAD

**Issue by Hadjimina** [solus-project/budgie-desktop#222]
When using the menu  the selection does not appear to be highlighted.

**Comment by ikeydoherty** [comment]
Depends highly on your theme - works for me with Arc and Vertex, but not with EvoPop. Which theme are you using?

**Comment by Hadjimina** [comment]
Ahh yes you are right. I have been running the numix themes, they seem to be pretty popular.

**Comment by ikeydoherty** [comment]
Which ones and what GTK version? We'll need to put a workaround in Budgie if its gonna happen on a lot of themes :]

**Comment by Hadjimina** [comment]
GTK : 3.16.3
The themes I can confirm the problem with are Numix-Frost and Numix-Frost-Light

**Comment by ikeydoherty** [comment]
Fixed in v10
