### ISSUE TITLE
Volume applet incompatible with ALSA

### ISSUE THREAD

**Issue by X0rg** [solus-project/budgie-desktop#223]
If I disable PulseAudio to use ALSA, Volume applet doesn't work.

To disable it, I use the following file, *~/.config/pulse/client.conf*:
`autospawn=no`

GNOME Mixer works fine with ALSA thanks gnome-alsamixer.
Can Budgie support ALSA?

**Comment by ikeydoherty** [comment]
We'll support it via an applet or patch if someone is so inclined, but officially we use gvc, which is PulseAudio based, the default in Solus. I'm closing as I won't implement this myself, as Solus has no need of an option like this.
