### ISSUE TITLE
Strange Wi-fi icon

### ISSUE THREAD

**Issue by thalesrodolfo** [solus-project/budgie-desktop#224]
The wi-fi icon was weird while I was using the live cd and after I installed the system (the first reboot). It seems it was using a different icon theme from the rest of the OS and it size was bigger than the rest of notification area icons. Unfortunately, I don't have a picture of it cause now the problem is gone (after the second system initialization) and it is showing the proper icon. So, the problem seems to occur just during the live cd session and the first installed boot.

**Comment by ikeydoherty** [comment]
Fixed in latest updates to Solus, and budgie-desktop-git
