### ISSUE TITLE
Telegram desktop not pinnable to the panel

### ISSUE THREAD

**Issue by sergioad** [solus-project/budgie-desktop#225]
Hello @ikeydoherty I noted that Telegram desktop is not pinnable to the  pannel, could you fix it?

![captura de pantalla de 2015-06-24 21-12-26](https://cloud.githubusercontent.com/assets/5375145/8345504/c028d332-1ab5-11e5-86f8-d9d932905c65.png)

**Comment by theSoenke** [comment]
Same problem with Android Studio

**Comment by smcdougall** [comment]
Same thing happens with FocusWriter.

**Comment by fastrizwaan** [comment]
also can't pin gnome-terminal, xterm

**Comment by ikeydoherty** [comment]
I have gnome-terminal pinned right now..

**Comment by fastrizwaan** [comment]
oh, I'm on fedora 23 with budige-desktop-git

**Comment by ikeydoherty** [comment]
Which uses what GNOME version ?

**Comment by fastrizwaan** [comment]
$ gnome-terminal --version
GNOME Terminal 3.18.2

gnome-desktop3-3.18.2-1.fc23.x86_64

**Comment by JoshStrobl** [comment]
I can't reproduce this issue under Solus. I have Telegram as well as Gnome Terminal pinned.

**Comment by ikeydoherty** [comment]
Telegram, gnome-terminal, all pin now.
