### ISSUE TITLE
[Wishlist] Place "Cancel" button on the left in budgie-session-dialog

### ISSUE THREAD

**Issue by tista500** [solus-project/budgie-desktop#226]
Greetings,

In Gnome3 Human Interface Guideline, the "Cancel" button of dialogs should be placed on the left side (if locales were LTR) before showing the affirmative buttons.
**Gnome3's Dialogs:** https://developer.gnome.org/hig/stable/dialogs.html.en (please see "Order" paragraph)

Something like this:
![Budgie-session-dialog](https://cloud.githubusercontent.com/assets/6073622/8400006/d462491e-1e52-11e5-8129-422729b64c8a.png)

Regards.

**Comment by Justinzobel** [comment]
To be quite honest I hate the left hand side cancel button. That is also
Gnome's HIG, not Solus/Budgie so I'm not sure what relevance it has...

**Comment by tista500** [comment]
@Justinzobel But Budgie strongly depends on Gnome3 resources, if so, a lots of newbies might be confused that "Why only the session-dialog has right side cancel?" like me, although I don't know which is the best way to place cancel button on...

Regards.

**Comment by ikeydoherty** [comment]
Budgie's existence stems from the fact I disagree with how GNOME is shipped and implemented, so their HIG is entirely irrelevant to us (i.e. they do not call the shots)

Budgie's session dialog is being changed regardless, as when I introduced 'Lock' there are now too many options.
