### ISSUE TITLE
Lateral layout for clock panel applet

### ISSUE THREAD

**Issue by Milozzy** [solus-project/budgie-desktop#228]
Hi,

if I set my panel on the side of the screen, the clock is shown vertically, very awkward/useless (screenshot attached)
![schermata del 2015-06-30 16-57-12](https://cloud.githubusercontent.com/assets/864646/8433969/1b158d02-1f49-11e5-8f36-91c795ba41a3.png)

Would it be possible to offer an option to rearrange it?

Thanks!

**Comment by ikeydoherty** [comment]
Fixed by removing side panels (Left panel will return in future)
