### ISSUE TITLE
Window  Manager is crashing against GNOME 3.17

### ISSUE THREAD

**Issue by alex285** [solus-project/budgie-desktop#231]
#0  meta_screen_free (screen=0x0, timestamp=15555794) at core/screen.c:790
#1  0x00007ffff7b46eb5 in meta_display_close (display=0x96dab0, timestamp=15555794) at core/display.c:1114
#2  0x00007ffff7b481aa in meta_display_open () at core/display.c:914
#3  0x00007ffff7b5065c in meta_run () at core/main.c:434
#4  0x0000000000406763 in main (argc=1, argv=0x7fffffffd558) at budgie-wm.c:53
(gdb) bt --full
No symbol "full" in current context.
(gdb) bt -full                                                                                                          
No symbol "full" in current context.
(gdb) bt full                                                                                                           
#0  meta_screen_free (screen=0x0, timestamp=15555794) at core/screen.c:790
        display = <optimized out>
#1  0x00007ffff7b46eb5 in meta_display_close (display=0x96dab0, timestamp=15555794) at core/display.c:1114
        __func__ = "meta_display_close"
#2  0x00007ffff7b481aa in meta_display_open () at core/display.c:914
        display = 0x96dab0
        xdisplay = <optimized out>
        screen = 0x0
        i = <optimized out>
        timestamp = 15555794
        atom_names = {0x7ffff7b98b29 "WM_PROTOCOLS", 0x7ffff7b98b36 "WM_TAKE_FOCUS", 
          0x7ffff7b98b44 "WM_DELETE_WINDOW", 0x7ffff7b98e27 "WM_STATE", 0x7ffff7b98b55 "_MOTIF_WM_HINTS", 
          0x7ffff7b98b65 "WM_CHANGE_STATE", 0x7ffff7b98b75 "SM_CLIENT_ID", 0x7ffff7b98b82 "WM_CLIENT_LEADER", 
          0x7ffff7b98b93 "WM_WINDOW_ROLE", 0x7ffff7b98ba2 "UTF8_STRING", 0x7ffff7b98bae "WM_ICON_SIZE", 
          0x7ffff7b98bbb "_KWM_WIN_ICON", 0x7ffff7b98bc9 "_MUTTER_HINTS", 0x7ffff7b98bd7 "_GTK_THEME_VARIANT", 
          0x7ffff7b99da8 "_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED", 0x7ffff7b98bea "_GTK_APPLICATION_ID", 
          0x7ffff7b98bfe "_GTK_UNIQUE_BUS_NAME", 0x7ffff7b98c13 "_GTK_APPLICATION_OBJECT_PATH", 
          0x7ffff7b98c30 "_GTK_WINDOW_OBJECT_PATH", 0x7ffff7b98c48 "_GTK_APP_MENU_OBJECT_PATH", 
          0x7ffff7b98c62 "_GTK_MENUBAR_OBJECT_PATH", 0x7ffff7b98c7b "_GTK_FRAME_EXTENTS", 
          0x7ffff7b98c8e "_GTK_SHOW_WINDOW_MENU", 0x7ffff7b98ca4 "_GNOME_WM_KEYBINDINGS", 
          0x7ffff7b98cba "_GNOME_PANEL_ACTION", 0x7ffff7b98cce "_GNOME_PANEL_ACTION_MAIN_MENU", 
          0x7ffff7b99dd0 "_GNOME_PANEL_ACTION_RUN_DIALOG", 0x7ffff7b98cec "_MUTTER_TIMESTAMP_PING", 
          0x7ffff7b98d03 "_MUTTER_FOCUS_SET", 0x7ffff7b98d15 "_MUTTER_SENTINEL", 0x7ffff7b98d26 "_MUTTER_VERSION", 
          0x7ffff7b98d36 "WM_CLIENT_MACHINE", 0x7ffff7b98d48 "MANAGER", 0x7ffff7b98d50 "TARGETS", 
          0x7ffff7b98d58 "MULTIPLE", 0x7ffff7b98d61 "TIMESTAMP", 0x7ffff7b98d2e "VERSION", 0x7ffff7b98d6b "ATOM_PAIR", 
          0x7ffff7b98d75 "_XKB_RULES_NAMES", 0x7ffff7b98d86 "WL_SURFACE_ID", 0x7ffff7b98d94 "_NET_WM_SYNC_REQUEST", 
          0x7ffff7b98da9 "_NET_WM_SYNC_REQUEST_COUNTER", 0x7ffff7b98dc6 "_NET_WM_VISIBLE_NAME", 
          0x7ffff7b98ddb "_NET_SUPPORTING_WM_CHECK", 0x7ffff7b98df4 "_NET_SUPPORTED", 0x7ffff7b98e03 "_NET_WM_NAME",

**Comment by Justinzobel** [comment]
Bug reporting is now done here https://bugs.solus-project.com/

**Comment by alex285** [comment]
Oh :(

**Comment by libcg** [comment]
Just rebuilt budgie-desktop against GNOME 3.17.4, it runs fine (with pull #237).

**Comment by alex285** [comment]
@libcg thats fine now. Thanks! Closing that!
