### ISSUE TITLE
Allow new application instance on Budgie Panel

### ISSUE THREAD

**Issue by alex285** [solus-project/budgie-desktop#232]
A new item "New Instance" (if possible) on applications context menu, plus Ctrl+Click to launch a new instance, instead to bring focus on current running.

**Comment by ikeydoherty** [comment]
This will only be supported via the applications own .desktop file, otherwise it's a massive hack

**Comment by alex285** [comment]
Gnome Shell does that and only allows it, if application allows it. Elementary also does that. I mean the Ctrl+Click for new instance.
