### ISSUE TITLE
Feature Request: Corner Hotspots.

### ISSUE THREAD

**Issue by Luke-Nukem** [solus-project/budgie-desktop#234]
Just started using Budgie. It's damned good and is what I was looking for.
However!

This is really three feature requests in one. One bit of functionality I found myself using all the time in other desktop environments, is a quick jam of the mouse into the corner to bring up an open-window grid.

So the second part of the feature request is that, a window grid for an overview of what is currently open.

The third bit of the request stems from the overlay. When alt-tabbing, it seems to be handy to have some sort of visual guide when switching. More to see at a glance what windows are next in the list.

**Comment by Justinzobel** [comment]
Spam reports are now filed at https://bugs.solus-project.com/ :)

**Comment by Luke-Nukem** [comment]
Hehe, thanks. I wasn't too sure where to put this. Bugzilla has always been just *bugs* in my mind, so I didn't think of it. And the Solus forums appear to be just for the Solus distro.
