### ISSUE TITLE
Installing on Debian Jessie

### ISSUE THREAD

**Issue by vniche** [solus-project/budgie-desktop#235]
Got a few errors on that errand, here's the log file generated by 'make install' (ran 'make clean' before), hope it helps: [log](https://gist.github.com/vniche/2b20b1cd29901adda6ce)

**Comment by veleiro** [comment]
Debian jessie uses Gnome 3.14.  I switched to branch gnome3.14 and it worked fine

**Comment by ikeydoherty** [comment]
`gnome3.14` branch is 11 months out of date. @vniche I need more of the `make` log to find out why RunDialog failed. I think this is a vapi/vala issue tbh.

**Comment by ikeydoherty** [comment]
Debian Jessie is no longer supported, you need a minimum of 3.18 now
