### ISSUE TITLE
Panel always on left monitor

### ISSUE THREAD

**Issue by Limero** [solus-project/budgie-desktop#236]
I have a three monitor setup and the panel is always on the most left monitor, instead of the primary one.

**Comment by Justinzobel** [comment]
Please report at https://bugs.solus-project.com/ and close this issue as github is no longer used for bug tracking. Thanks :)

**Comment by Limero** [comment]
Opened issue on the official bugtracker instead.
https://bugs.solus-project.com/show_bug.cgi?id=124
