### ISSUE TITLE
Can't open anything!

### ISSUE THREAD

**Issue by mandeeps708** [solus-project/budgie-desktop#239]
Installed `Solus OS Beta2`, after some time I am not able to open any application from the launcher. Not even the launcher works with the shortcut (<super> key), I have to click it to open. After clicking on shutdown button on the right, when clicking shutdown icon for logging out (or shut down etc.) it won't do anything.

**Comment by Justinzobel** [comment]
Please report all bugs here: https://bugs.solus-project.com/ as this tracker is no longer used.

**Comment by ikeydoherty** [comment]
Fixed in v10
