### ISSUE TITLE
Cannot open synaptic from menu

### ISSUE THREAD

**Issue by swarnendubiswas** [solus-project/budgie-desktop#240]
I have installed budgie from source on Ubuntu Gnome 15.04 with gnome3 staging ppas, so I have Gnome 3.16. I can start synaptic from the command line, but I cannot start synaptic from the budgie menu. Selecting synaptic from the menu seems to have no effect, for example, the privilege password dialog does not appear. I checked with root terminal from the menu, and that seems to work fine.

**Comment by Justinzobel** [comment]
Please report all bugs at https://bugs.solus-project.com as this bug tracker is no longer used.

**Comment by loctauxphilippe** [comment]
@Justinzobel you can disable issues in the settings of the repo

![screen shot 2015-08-23 at 12 16 02](https://cloud.githubusercontent.com/assets/8809909/9427838/c43c5bf6-4990-11e5-8cbd-147f6ed3faf0.png)

**Comment by Justinzobel** [comment]
I have no access Phil. Ikey will be disabling it soon.

**Comment by ikeydoherty** [comment]
Please ensure you install a correct polkit dialog (i.e. polkit-gnome) on your distro.

Issues are re-opened on GitHub now.
