### ISSUE TITLE
Bad apps popover direction.

### ISSUE THREAD

**Issue by cristian99garcia** [solus-project/budgie-desktop#241]
When you set the panel position option to "Right" or "Left", the apps popover direction is UP, but I think this must be RIGHT or LEFT.
![issue](https://cloud.githubusercontent.com/assets/3912944/9508829/df023536-4c2f-11e5-9f25-2d500916820e.png)

PD: Sorry for my english, how you can see in the picture, I speak spanish :P

**Comment by ikeydoherty** [comment]
Fixed in v10

**Comment by cristian99garcia** [comment]
Nice new! :D
I'll test it... someday
