### ISSUE TITLE
What is Happening with the project?

### ISSUE THREAD

**Issue by diegogarciaa** [solus-project/budgie-desktop#243]
What is Happening with the project?

I mean, the last update was 5 month ago. The owner does not answer anymore... And in the website there is a FUNDRAISER??? ARE YOU FUCKEN SERIOUS?

**Comment by J7mbo** [comment]
![Image](http://vignette3.wikia.nocookie.net/dragonage/images/2/2a/Anchorman-well-that-escalated-quickly.jpg/revision/latest?cb=20120921164818)

**Comment by ikeydoherty** [comment]
Budgie is undergoing a rewrite into C - which we've been entirely transparent about. There's no need for your comment whatsoever. Experimental works were done in my budgie-next and budgie-panel repos and are undergoing merges right now. Look at my repositories.

**Comment by ikeydoherty** [comment]
Also, not sure where you're pulling this 5 month figure from, there were updates in this repo last month. Secondly, the fundraiser is to support the Solus Project as a whole, including the distribution *and* the desktop
