### ISSUE TITLE
Window border disappearing

### ISSUE THREAD

**Issue by ksthiele** [solus-project/budgie-desktop#244]
I don't know if this is only happening in Budgie DE.

But when you take a GTK 3+ native app (nautilus, system monitor etc), maximize and then resize them by drag and dropping the border of that window disappears as well as the rounded corners

**Comment by Justinzobel** [comment]
Please report this on the bug tracker, Github is no longer used for issues:
https://bugs.solus-project.com

**Comment by Blingy** [comment]
making an extra account for that?

nope

**Comment by Justinzobel** [comment]
Then I'm not sure how you expect your bug to be fixed? Good luck!

**Comment by ikeydoherty** [comment]
Closing..
