### ISSUE TITLE
Budgie fails with GTK 3.18

### ISSUE THREAD

**Issue by X0rg** [solus-project/budgie-desktop#246]
Since I've upgraded GTK to 3.18, I'm unable to start Budgie Desktop.
I start Budgie with `startx`, the .xinitrc contains `exec budgie-desktop`.

This is what I got when I try to run Budgie from a standalone terminal:

```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
1944 (budgie-wm) closed with exit code: 139
Launched 1 times
2011 (budgie-wm) closed with exit code: 139
Launched 2 times
2019 (budgie-wm) closed with exit code: 139
Launched 3 times

** (budgie-session:1931): WARNING **: BudgieSession.vala:204: Not relaunching budgie-wm as it has died 3 times already

** (budgie-session:1931): CRITICAL **: BudgieSession.vala:208: Critical desktop component budgie-wm exited with status code 139
```

**Comment by X0rg** [comment]
I was unable to rebuild Budgie Desktop.
I have downgraded all my packages (GTK 3.16), it reworks. Build I'm still unable to build with using AUR [budgie-desktop-git](https://aur.archlinux.org/packages/budgie-desktop-git/) package.

**Comment by Justinzobel** [comment]
Budgie hasn't yet been updated to 3.18 so that would be why. A rewrite is
under-way (which MAY bring 3.18 compatibility) and there is a big focus on
Solus 1.0 at the moment. Once that's out the way we should be able to focus
back on Budgie and ensure it's 3.18 compatible.

**Comment by ikeydoherty** [comment]
We're on 3.18 now
