### ISSUE TITLE
How to build budgie-desktop for openSUSE Leap?

### ISSUE THREAD

**Issue by geckolinux** [solus-project/budgie-desktop#248]
Hi everyone,

I'm trying to build budgie-desktop for openSUSE Leap, but I'm not sure if it will work given the fact that openSUSE Leap still uses mutter and gnome-shell at version 3.16. Is there any way around this?

Thanks a lot!

**Comment by ikeydoherty** [comment]
You can try editing configure.ac to drop the versions down to your versions and try to build it then. I set minimums at 3.18 because this is what we've tested with.

**Comment by geckolinux** [comment]
Thanks a lot @ikeydoherty  for the reply. I tried as you suggested, but it complains about "undefined reference to `clutter_actor_is_visible'". I assume I'm out of luck? Here's the build log:
https://pastebin.mozilla.org/8855374

**Comment by ikeydoherty** [comment]
Can you try it with the change I just pushed there?

**Comment by geckolinux** [comment]
Nice, thanks for the fast fix! Looks like it's compiling cleanly now. (I'm still working on how to actually get it packaged, but that's another challenge.) Cheers.
