### ISSUE TITLE
Start Budige from .xinitrc

### ISSUE THREAD

**Issue by high1** [solus-project/budgie-desktop#249]
I've compiled 10.1 on Arch, and can not find budgie-session binary to start desktop from .xinitrc. Budgie can be started from gdm, but I don't use it. Am I missing something?

**Comment by Justinzobel** [comment]
Install a desktop manager instead like lightdm or gdm etc.

**Comment by high1** [comment]
I know I can, but I would prefer to start desktop from xinitrc.I think Budgie should provide budgie-session, and I think it did before the rewrite.

**Comment by Justinzobel** [comment]
I'd say it's under budgie-desktop in /usr/bin now, try exec budgie-desktop

**Comment by high1** [comment]
Issue solved. Maybe renaming it to budgie-session would make sense?

**Comment by ikeydoherty** [comment]
No because the session is actually gnome-session.

**Comment by feskyde** [comment]
Tried putting this into .xinitrc?

```sh
exec gnome-session --session=budgie-desktop $*
```

**Comment by high1** [comment]
``` shell
exec budgie-desktop
```
worked fine.

**Comment by Justinzobel** [comment]
Awesome @high1 can you please close the issue. :)

**Comment by high1** [comment]
I closed it a day ago...

**Comment by Justinzobel** [comment]
Apologuies @high1 I didn't look up further.
