### ISSUE TITLE
MPRIS applet alignment issue when track name ellipses

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/budgie-desktop#251]
Moved over from Arc-Desktop issues.

When track name is too long and ellipses, alignment is affected, when lower length track is played next it is fixed.

https://cloud.githubusercontent.com/assets/1370117/11257527/fc11ea68-8ea1-11e5-85c5-2121bcfad20b.png

**Comment by ikeydoherty** [comment]
Fixed

**Comment by ikeydoherty** [comment]
![screenshot from 2016-01-02 00-29-16](https://cloud.githubusercontent.com/assets/164489/12072746/0bce5a00-b0e8-11e5-809b-f705f26063be.png)
