### ISSUE TITLE
Request: budgie menu - show items as icons, text beside icon and list

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#252]
Hi,
There's xfce4appfinder, which has configurable interface to search apps, but it is not a menu. It would be great if we could have such configurability like icons, text beside icons and list in budgie-menu,

List view
![1-list](https://cloud.githubusercontent.com/assets/1161682/12013762/d1889006-ad43-11e5-8f1d-014c400cf9e8.jpg)

small list view
![menu-vsmall-smaller](https://cloud.githubusercontent.com/assets/1161682/12013777/2dc78610-ad44-11e5-8ecc-4777ef05937e.jpg)

Text beside Icons
![2-icon-with-text](https://cloud.githubusercontent.com/assets/1161682/12013767/06e12736-ad44-11e5-9bb7-c6704b7dd8c9.jpg)

Icons Only
![3-icons](https://cloud.githubusercontent.com/assets/1161682/12013771/0dd96986-ad44-11e5-9330-b76465b4b66d.jpg)

Please consider, thanks.

**Comment by fastrizwaan** [comment]
![screenshot from 2015-12-31 17-45-45](https://cloud.githubusercontent.com/assets/1161682/12064353/e5079762-afe6-11e5-9ad6-d1871f1fb40c.png)

The run dialog is more beautiful than the traditional application menu, Please consider having alt+f2's menu as menu with icons and without categories, this really will give budgie-desktop a unique personality!

![screenshot from 2015-12-31 17-54-45](https://cloud.githubusercontent.com/assets/1161682/12064372/9c4ea730-afe7-11e5-8ba7-c2a08bfa3974.png)

**Comment by fastrizwaan** [comment]
![screenshot from 2015-12-31 19-25-44](https://cloud.githubusercontent.com/assets/1161682/12064924/74bad826-aff4-11e5-956f-bd6c3b7df691.png)

Icon view with a titlebar looks way better than just plain menu.
![screenshot from 2015-12-31 19-36-14](https://cloud.githubusercontent.com/assets/1161682/12065007/e7b1e1e8-aff5-11e5-8589-6871a5200efe.png)

**Comment by ikeydoherty** [comment]
It's a menu.. adding a titlebar just breaks every HIG ever made

**Comment by fastrizwaan** [comment]
HIG are just Guidelines, nothing more, if it looks good and works better then lets create new HIG. Modern art simply does not follow the traditional art. Beauty and  Functionality are more important that some old HIGs, nowadays "menu bar" is getting extinct...

The mockups look good https://github.com/solus-project/mockups/tree/master/Application%20Launcher
https://github.com/solus-project/mockups/blob/master/Application%20Launcher/applauncher-popup.png

Please consider.

**Comment by ikeydoherty** [comment]
Right.

But it doesn't look good and I fail to see how it would work better. A menu does *not* need a close button, click outside of the menu or use the keyboard

**Comment by ikeydoherty** [comment]
Also, what menubars? We don't have any in the majority of our applications.

**Comment by fastrizwaan** [comment]
Now that most interfaces are switching over to touch interface, this "close" button will help, also it is easier to close the menu with X button with mouse click. Yes, we can hide the X button, if it is not useful.

Menubars! that's exactly what I'm saying, they are out of fashion, they were part of HIGs, like KDE's https://techbase.kde.org/Projects/Usability/HIG/Menu_Bar. Now every web browser, and desktop environment is avoiding it as much as possible.

Thanks.

**Comment by ikeydoherty** [comment]
But with a touchscreen you just have to press anywhere outside of the menu, so the point is still irrelevant.

**Comment by fastrizwaan** [comment]
the point is not of the 'x' button, but overall menu appearance. 

Category based menus had their utility when there was no search feature.

Now, most OSes and Desktops are dropping menu based approach just like application menus. 

e.g., gnome-shell, Android, ios, windows 8, unity desktop have discarded menu based launchers.

elementary os has hybrid, category based + icons.
![slingshot-application-launcher](https://cloud.githubusercontent.com/assets/1161682/12071766/f2357bdc-b0e2-11e5-9b51-341b1deafb65.png)


There are applications which either do not fit or fit many categories, that's why it's been discarded. I'd request we go for search + icon based menu, and we may have categories on/off button on the title as in the mockups.

With the current menu, budgie-desktop, the menu doesn't look any better than gnome2, xfce menu, lxqt, or kde menu, they all look way too similar. Having run dialog like menu will make Solus stand above all other desktops, it will give it a unique style and appearance, which will be a distinguishing factor, just like Raven gives solus a unique personality.

have a look at these desktops' menus:

kde:
![alternativemenus](https://cloud.githubusercontent.com/assets/1161682/12071794/cb9ea87a-b0e4-11e5-8d05-3f0d0ece822c.png)

lxqt:
![trusty-snapshot-1-running-oracle-vm-virtualbox_005](https://cloud.githubusercontent.com/assets/1161682/12071796/d58356ec-b0e4-11e5-9de2-8991e3d2c45e.png)

xfce:
![xfce-desktop-100598245-large](https://cloud.githubusercontent.com/assets/1161682/12071797/dbbeb20e-b0e4-11e5-928e-4e96e7328b3b.png)

lxde:
![lxde-desktop-100598241-large](https://cloud.githubusercontent.com/assets/1161682/12071798/e866fbf6-b0e4-11e5-8765-22512aa6a673.png)

cinnamon: (budgie menu resembles a lot to this)
![cinnamon-desktop-100598240-large](https://cloud.githubusercontent.com/assets/1161682/12071799/f7107b78-b0e4-11e5-8b33-6f6224a7c3b9.png)

We can see that all those desktops have cluttered menus, which doesn't add to their desktop's beauty. Elementary os's slingshot looks better, though.

Thanks.

**Comment by ikeydoherty** [comment]
I'm not talking about the icons, I'm talking about what you're saying about menubars and titlebars on menus, which makes no sense.

> There are applications which either do not fit or fit many categories, that's why it's been discarded. I'd request we go for search + icon based menu, and we may have categories on/off button on the title as in the mockups.

We have search. We have categories that you can switch off. The only thing that isn't there is an icon grid, which in honesty I'm not a big fan of, but hey, patches welcome if someone implements it.

**Comment by fastrizwaan** [comment]
Just noticed, it looks better with built in theme, but looks terrible when not using built-in theme. 

Please, please please, allow icon grid view as an alternative.

**Comment by ikeydoherty** [comment]
Closing this dead issue because it has too many tangents to follow, and we have a final design for the Budgie Menu. The Budgie API allows others to implement their own menus if they dislike the default.
