### ISSUE TITLE
Budgie panel applets don't adjust when the screen resolution changes

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/budgie-desktop#254]
Hi res http://imgur.com/0tWgyZb
Res lowered http://imgur.com/1oX5FRD

**Comment by fastrizwaan** [comment]
Is this related to:
https://github.com/solus-project/budgie-desktop/issues/275

**Comment by ikeydoherty** [comment]
yes this was fixed in #275  justin

**Comment by ikeydoherty** [comment]
Closing, but re-open if it comes back
