### ISSUE TITLE
Please update the fedora/suse rpms at software.opensuse.org

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#255]
Please update the budgie desktop to version 10.x  thanks:

https://software.opensuse.org/download.html?project=home%3Aikeydoherty%3Aevolve&package=budgie-desktop

**Comment by ikeydoherty** [comment]
This is being implemented now. What distro are you on?

**Comment by geckolinux** [comment]
Here's what I came up with. It seems to work fine, but I'm sure the .spec file could be improved... a lot!

https://build.opensuse.org/package/show?project=home%3Asb56637%3Abudgie-desktop&package=budgie-desktop

**Comment by ikeydoherty** [comment]
Currently testing a build now https://build.opensuse.org/package/show/home:ikeydoherty:solus-project/budgie-desktop

**Comment by ikeydoherty** [comment]
I'll add a patch now to see if I can enable 3.16 ..

**Comment by ikeydoherty** [comment]
Done - if you run into issues with deps or 3.16 theme issues or w/e please open a new issue

**Comment by geckolinux** [comment]
Very nice, thanks a ton @ikeydoherty !

**Comment by ikeydoherty** [comment]
Most welcome :)
