### ISSUE TITLE
Budgie requires a lock screen for use within GDM: Design and implement

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#258]
Can't lock the screen using shortcuts. have to manually install and run xlock to have this functionality.

**Comment by ikeydoherty** [comment]
Budgie doesn't yet have a lock screen, which is a hard requirement when using GDM. Long story short we have to provide our own greeter and lock screen to deal with this.

So I'm going to rename this issue and raise the priority, as we need one.

**Comment by ikeydoherty** [comment]
We're going to add a LightDM lock screen only, no GDM interaction. Closing this as now invalid
