### ISSUE TITLE
Feature Request: Task Icon size 40x48 (width 1:1.2 or 1:1.1)

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#259]
Budgie task icon size is squarish so, the task icons look cluttered or too close to each other, It would look better if we have rectangular shape (40x48) instead of square (40x40) (assuming we are using 40 pix size) Please see this windows 10 screenshot

Also notice the Active icon has full box highlighted (chrome as active task) and running app (virtualbox) has only an underline. 

Also notice the thickness of the line for the active applications.

![0size](https://cloud.githubusercontent.com/assets/1161682/12027028/c0d9c9b6-ade6-11e5-95f9-294f1c73f6bb.png)

Please consider. Thanks.

**Comment by ikeydoherty** [comment]
So if I understand you right, you want more padding on the left/right of each icon ?

**Comment by fastrizwaan** [comment]
yes, but the underline should also be part of the the width.

**Comment by fastrizwaan** [comment]
Here's icon sizes in the ration of 1:1.1 (40x1=40:40x1.1=44) i.e., 40x44, The size 40 is achieved by setting size 46 at RAVEN panel settings ? I'm just using size 40 as an example, ration 1:1.1 would look good for most sizes.

![40x44](https://cloud.githubusercontent.com/assets/1161682/12058523/034798d6-af73-11e5-8698-4feb9743df6f.png)

As can been seen from the screenshot, it gives a padding of 1:1.1, so the task icons look not so closed as to cause a feeling of clutter.

The 1:1 ratio (i.e., 40x40) can be used for pinned icons/quick launch icons.

Windows 10, uses 1:1.2 ratio for the task icons padding. This ratio would also help for touch interface. Thanks.

**Comment by ikeydoherty** [comment]
At this moment in time, this feature can be achieved via GTK theming, it's not something I'll enforce as a standard behaviour (The icon tasklist is theme controlled entirely. They can add the padding)

**Comment by ikeydoherty** [comment]
Reopening at request

**Comment by horst3180** [comment]
Setting the button width to panel height * 1.1 would be a good idea, imo. As of now, the buttons look too squished at the default size.
This can't be solved by the theme. For example 22px icons with 5px padding to both sides will look okay, but if you increase the panel size, the padding will quickly become too small.

**Comment by ikeydoherty** [comment]
Cheers my niavity led me to believe in CSS superpowers :)

**Comment by ikeydoherty** [comment]
Turns out we can:

![screenshot from 2016-07-21 22-25-51](https://cloud.githubusercontent.com/assets/164489/17039378/21290bfe-4f92-11e6-8289-5f25bd725be7.png)

**Comment by ikeydoherty** [comment]
Fixed in https://github.com/solus-project/budgie-desktop/commit/4a9be22d4ef91dc48f70c7fb5b64df0b7b5e3883 - thanks guys, and thanks @horst3180 for convincing me of this, and sorry @fastrizwaan for me not getting it :)

**Comment by ikeydoherty** [comment]
Proper 1:1.1 ratio with CSS padding removed and correct size reported internally to Budgie Applets in `panel_size_changed`:

![screenshot from 2016-07-21 22-48-40](https://cloud.githubusercontent.com/assets/164489/17040018/55e58c20-4f95-11e6-9250-e2c92549ad02.png)
