### ISSUE TITLE
Battery Icon - Right click to open Power Settings

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/budgie-desktop#262]
Same as clock, right click should allow user to open Power Settings in GCC.

**Comment by ikeydoherty** [comment]
You mean left click ya?

**Comment by Justinzobel** [comment]
Nope.

**Comment by ikeydoherty** [comment]
but the clock has left click.

**Comment by Justinzobel** [comment]
Oh it is too, I thought it was right. Left seems a bit odd. Left should be a one click action thing. Right should be a context menu.

**Comment by ikeydoherty** [comment]
moving this to 10.3, which will come very soon, I just don't want to ship it with missing translations for this new feature

**Comment by ikeydoherty** [comment]
Oi this was done
