### ISSUE TITLE
Raven close after losing focus

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#263]
Please add an option to make Raven closes after losing focus (i.e. clicking the panel or an application)

**Comment by ikeydoherty** [comment]
This is possible I guess.

**Comment by ikeydoherty** [comment]
Implemented

**Comment by ikeydoherty** [comment]
So yeah that breaks stuff.

**Comment by ikeydoherty** [comment]
Re-implemented, actually not borked this time :]
