### ISSUE TITLE
Titlebar left cornet buttons doesn't work inside left positioned plank launcher area.

### ISSUE THREAD

**Issue by marek287** [solus-project/budgie-desktop#266]
I haven't noticed this problem with other desktop environments.

Buttons start working this area:
![test](https://cloud.githubusercontent.com/assets/9947650/12042804/34f0df2e-ae87-11e5-9411-5dee1e9c6842.png)

**Comment by ikeydoherty** [comment]
And if you maximise the window is it not also warped by the left-side plank? Plank is creating struts along that region to reserve the panel space is it not?

**Comment by marek287** [comment]
If I maximize the window plank is auto hided. If I exit Plank, Chromium close button is working (full screen).

I have notices that close button is working (full screen) with some application )nautilus, system monitor, disks. But not with chromium, firefox, dfconf editor...

**Comment by ikeydoherty** [comment]
So you're saying it works only on windows that have headerbars?

**Comment by marek287** [comment]
Good point. Buttons don't work with titlebar windows.

![image](https://cloud.githubusercontent.com/assets/9947650/12049772/9ef4b748-aef4-11e5-96d1-9ae1dc50b4ec.png)

**Comment by ikeydoherty** [comment]
Alright this appears to be an upstream Mutter issue, looking into it

**Comment by marek287** [comment]
It's seems it was plank issue and it's solved with plank 0.11.0-1.
