### ISSUE TITLE
Multi-Monitor Setup

### ISSUE THREAD

**Issue by markuman** [solus-project/budgie-desktop#27]
If I do
    xrandr --output LVDS --mode 1366x768 --primary --output VGA-0 --mode 1680x1050 --right-of LVDS

I can't see the taskbar anymore.

**Comment by ikeydoherty** [comment]
I *believe* these issues are all resolved now in git, I'll let anyone close this when verified (It should be starting on the primary monitor, wallpaper handling was fixed, etc..)

**Comment by ryanleesipes** [comment]
Ever get any verification to close this? I use it on a multi-monitor setup and haven't had any issues for a while. I'll test it one more time and see what happens.

**Comment by Binero** [comment]
I would test it, but I do not have a dual-head setup anymore. :p
