### ISSUE TITLE
BUG: raven settings - panel size wrong

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#270]
I set the size of the panel to 40, and the size of the panel becomes 34, where are the 6 pixels? Now to achieve the panel size to 40 we need to set 46 as panel size, this is inconsistent behavior.

panel size 40 should set the panel height to 40 and not 34. Thanks.

**Comment by ikeydoherty** [comment]
The panel size *includes* the shadow size, And it's 5px, not 6px difference.

**Comment by fastrizwaan** [comment]
ok, why not exclude 'shadow' size from panel size to be accurate, let the shadow size be added to panel size, like panel_size+5 for budgie.

**Comment by JoshStrobl** [comment]
> why not exclude 'shadow' size from panel size to be accurate?

Because then it wouldn't be accurate. It is still technically taking 40px and thus claiming it as 35px would be inaccurate.

**Comment by ikeydoherty** [comment]
Remember the shadow is internal to the panel

**Comment by fastrizwaan** [comment]
Humans and computer differ in this regard; shadow is not panel, so why include shadow pixels to panel? For geeks that's ok, but for humans this is not quite right.

Would you consider your shadow as part of you?

Also the shadow is overlapping other windows, so that's not a part of panel, visually.

**Comment by JoshStrobl** [comment]
> For geeks that's ok, but for humans this is not quite right.

That literally made no sense.

> Would you consider your shadow as part of you?

The shadow is a part of the panel.

> Also the shadow is overlapping other windows, so that's not a part of panel, visually.

Okay, so here is the deal. It is 40px. That is accurate. Reporting it as 35px isn't. Simple.

**Comment by fastrizwaan** [comment]
humans see objects and their properties as separate, geeks as in OO programmers, they consider shadow as a part of the object.

Do you consider your shadow as part of your being? show we make a door/clothes based on your shadow size? that's not non-programmers perceive.

Bad deal, I have disabled Shadow, still it gives me 35 pixel panel when I chose 40 pixels size, now that's not accurate, is it?

**Comment by ikeydoherty** [comment]
OK good point on disabled shadow.

Alright this is all getting *entirely* too meta, I'll adjust the shadow calculation.

**Comment by ikeydoherty** [comment]
Only for when the shadow is hidden though mind.

**Comment by fastrizwaan** [comment]
ok, that's cool

**Comment by ikeydoherty** [comment]
Also I'd really appreciate it if you could recognise the fact I'm a human being and stop calling me a geek. It's highly offensive and it's getting on my nerves big time.

**Comment by fastrizwaan** [comment]
sorry, didn't mean it otherwise, for me  geek=technical guy, programmers, highly advanced logic; humans=laymen, non-programmers, not too technical. I'll be careful :)

**Comment by ikeydoherty** [comment]
Hmmmmmm I'll let you off this time =P

**Comment by ikeydoherty** [comment]
Eh. Thought this over, architecturally its excess work to lie to ourselves on the real size, and adds unnecessary calculations on the CPU for nothing important
