### ISSUE TITLE
Feature: date and time together or switch display of date and time alternately every few secs

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#272]
I like to see date along with time, this is what I'm seeing on budgie desktop
![date-time](https://cloud.githubusercontent.com/assets/1161682/12058886/4688dc1e-af77-11e5-897a-239fd56d8e8f.png)
It's well and good but date and time in a row are not so good looking.

could we show date and time one after the other every few seconds like we see in news channels, first show time, after some delay date, and this goes on.
![time](https://cloud.githubusercontent.com/assets/1161682/12058906/9d0a4320-af77-11e5-9192-e742bdf4756c.png)
![date](https://cloud.githubusercontent.com/assets/1161682/12058907/9e7c9cb2-af77-11e5-8ed4-278323e440cd.png)

Also alternate way is to have 2 rows, one for date and another for time, like is windows10
![win10](https://cloud.githubusercontent.com/assets/1161682/12058897/7d168ba0-af77-11e5-9a0c-2040bf399651.png)

**Comment by ikeydoherty** [comment]
Date and time settings are controlled in GNOME Settings, which we abide by. Look in GNOME Tweak Tool, I believe the options you find there are suffice. We'll port these options into the Clock Applet's settings UI at some point.

**Comment by ikeydoherty** [comment]
Closing, I'll make a new bug to track clock settings being missing
