### ISSUE TITLE
Request: show Number of notification on the Bell

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#274]
![alert](https://cloud.githubusercontent.com/assets/1161682/12059386/548f8048-af80-11e5-8386-453a98f9bf7d.png)

We only get Red colored bell. Color blind people will not be able to notice.

If we could have superscripted numbers over the bell icon, that would really be more useful. Thanks.

**Comment by ikeydoherty** [comment]
To  keep alignment we can only render on top of the bell, not outside the 16x16 square, so it could become unreadable. I'll give it a go

**Comment by feskyde** [comment]
@ikeydoherty What about putting the number aside of the bell icon, or using an outlined-only icon for no notifications and a filled bell icon for notifications?

**Comment by ikeydoherty** [comment]
@feskyde it would cause the applets to jump around in the tray area by hiding/showing the number

**Comment by ikeydoherty** [comment]
Also we only lightup the bell when you have notifications :)

**Comment by ikeydoherty** [comment]
Closing as current behaviour with highlighted bell is sufficient. Raven shows you the count when you open it

**Comment by fastrizwaan** [comment]
that's not right,

Suppose we had 1 notification, and The bell is highlighted. (highlighted bell with 1 notification). We see the popup and ignores it.

Now we go out for tea, or just to get fresh air.

Now an Important email comes, as we were not sitting at the computer, we would miss the pop up notification on top right.

We see the highlighted bell, and still assume that we have 1 not-so-important notification, whereas, there is an important 2nd notification.

So, just highlighting the bell is not really useful, may be some other form of attention grabbing things to alerts the user like shaking the bell.

I'd suggest displaying number then bell alternately, we could have better animations.

Please observe the bell:
![bell5](https://cloud.githubusercontent.com/assets/1161682/12073270/e2580384-b13b-11e5-92c9-ee0e7430a366.gif)

**Comment by ikeydoherty** [comment]
Again, I disagree. The vast majority of our users are using laptops, and this "animation" is just wasting CPU cycles completely unnecessarily, a further drain on the battery.

If its lit up, it has a notification.

**Comment by Justinzobel** [comment]
Whether it's one notification or 100, you still know you've got to open it to see them.

**Comment by fastrizwaan** [comment]
Justin, my work requires me to quickly respond to emails (email notifications), some are useless, which I'd ignore, but some are important. And I do go out to have tea or take a 10 min break once in a while. So If I see that a useless notification is there, like an advertisement, I'd rather ignore than to respond (lazy indeed). In my mind I'd say ok, there's one notification. If I could see new notification, either as persistent popup or as number, I'd respond.

gnome-shell, keeps the notifications up, it shows in the lock screen.

Highlight with red color to me only means "something went wrong", and also I don't really notice the color change. Animation, it grabs the attention.

Example, while taking a turn a car indicator flashes on and off, so that the other driver could notice, just imagine if only the color of the indicator (yellow/orange) changes and won't flicker, the driver at the back would hardly notice the change, and there's a very high chance of accident occurring.

Something animated would be nice, than just color change.

**Comment by ikeydoherty** [comment]
I can animate the *initial change* but I do not want it to be persistent. This is the whole idea in having a notification center, so you dont miss old notifications.

**Comment by fastrizwaan** [comment]
initial change on every new notification, that'd be great. :)
