### ISSUE TITLE
BUG: screen resolution change does not resize panel

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#275]
![1024](https://cloud.githubusercontent.com/assets/1161682/12060122/871e6b24-af8e-11e5-92f8-0270c97633db.png)

On changing the display resolution to 1024x768 from 1920x1080, the panel does not resize itself to the new resolution.

**Comment by ikeydoherty** [comment]
Looks resized to me, unless I'm being really thick

**Comment by fastrizwaan** [comment]
You are not looking at the panel, see the panel, Also it needs to on resolution change, here's the screenshot after budgie-panel --replace
![0panel](https://cloud.githubusercontent.com/assets/1161682/12060301/9a5b17e2-af92-11e5-9d5a-cf0f9a083daa.png)

After reverting back to 1920x1080, please observe that the panel is not resized to 1920 resolution.
![1920](https://cloud.githubusercontent.com/assets/1161682/12060307/c181db94-af92-11e5-9dd7-fdf5f2d25e3c.png)

**Comment by ikeydoherty** [comment]
Yup, turns out I'm a muppet after all. Soo we follow primary monitor but not a lot else. I now have midget-panel-syndrome :p 

Looking into it, thanks

**Comment by ikeydoherty** [comment]
![screenshot from 2015-12-31 02-28-31](https://cloud.githubusercontent.com/assets/164489/12060394/a54cb128-af66-11e5-935e-98670eac8a78.png)

Implemented, thanks

**Comment by fastrizwaan** [comment]
You're on fire :)

**Comment by ikeydoherty** [comment]
SHIT

Someone find me a bucket of water!

**Comment by ikeydoherty** [comment]
..Was a really bad Dad Joke. Sorry xD

**Comment by fastrizwaan** [comment]
No problem :-), I did git pulled and installed, yet the panel is not resizing to the new resolution! I'm on fedora 23.
![gitc](https://cloud.githubusercontent.com/assets/1161682/12060455/3b502748-af96-11e5-9751-4a46cadce05d.png)

**Comment by ikeydoherty** [comment]
Dumb q but have you tried logging out/back in? Validated here

**Comment by fastrizwaan** [comment]
Yes, logged in again in fedora 23 it won't work; but in Solus OS, it works.

**Comment by fastrizwaan** [comment]
OK, working on other fedora 23 installation. Bug closed already :)
