### ISSUE TITLE
Feature: restart shortcut 'r' like in gnome-shell

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#276]
When we change some settings, or when the desktop becomes unresponsive, and when we update the git install; it would be nice to have a restart alt+f2+"r" to reload budgie-desktop. Thanks.

**Comment by ikeydoherty** [comment]
I wasn't aware the desktop became unresponsive, if so you need to file bugs for those.

To restart the WM: `budgie-wm --replace`
To restart the panel: `budgie-panel --replace`

I won't be adding an "r" restart to Budgie, as it's not supported within our architecture, the panel is a separate process
