### ISSUE TITLE
Feature: HTitle - Hide firefox title bar for more screen space

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#279]
![screenshot from 2015-12-31 18-20-22](https://cloud.githubusercontent.com/assets/1161682/12064536/558fd39c-afeb-11e5-8be7-0b142dbb7d46.png)

https://addons.mozilla.org/en-US/firefox/addon/htitle/

using the HTitle addon, the firefox titlebar hides (need to set always in the htitle preferences), it looks slick and gives more rendering area for web content.

Thanks.

**Comment by ikeydoherty** [comment]
what has this got to do with Budgie?

**Comment by fastrizwaan** [comment]
Just like with arc-theme, this thing will integrate firefox into overall gtk3 apps, like nautilus, gnome3 apps which does not has titlebar but minimize, maximize, close button. also it gives more screen space.
this addon requires xprop and xwininfo
https://bugs.solus-project.com/show_bug.cgi?id=473

**Comment by ikeydoherty** [comment]
OK but the extensions you install on your operating system are not affected by or related to Budgie. Also why are we now duplicating bugs ? :D 

I'm happy to fix it within Solus, and i'll leave your bugs open there (Thanks!) but I'll close it here, because it's nothing to do with Budgie
