### ISSUE TITLE
Autogen on Ubuntu

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#280]
Hi Ikey,

  I've managed to compile the desktop on Ubuntu 16.04 - so great!

Just need to double check my dependencies - when I run ./autogen the plugins list below has a few "no" values - any thoughts what may be missing?

Plugins:
        =======

        natray:                 yes

        budgie-menu:            always
        clock:                  always
        icon-tasklist           no
        notifications           always
        separator:              always
        spacer:                 always
        show-desktop:           no
        tasklist:               no
        status:                 yes
        tray:                   yes
        workspaces:             no

**Comment by fossfreedom** [comment]
self solved ... libwnck-3-dev

**Comment by fossfreedom** [comment]
@ikeydoherty - I've added a write up and compilation instructions on Ubuntu here - if there is anything wrong just shout and I'll correct.

thanks

https://xpressubuntu.wordpress.com/2015/12/31/installing-the-solus-budgie-desktop-on-ubuntu

**Comment by ikeydoherty** [comment]
Looks good! Remember it supports multiple panels too ^^
