### ISSUE TITLE
creating a debian package - missing dependencies?

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#284]
Hi Ikey,

  just looking at creating a debian package - I'm getting the following errors.  Just wondering if somewhere when building raven there is a missing link to the maths library i.e. -lm linker ?

<pre>
dh_shlibdeps -pbudgie-desktop    
dpkg-shlibdeps: warning: debian/budgie-desktop/usr/lib/budgie-desktop/plugins/libbudgiemenuapplet.so contains an unresolvable reference to symbol gtk_box_pack_start: it's probably a plugin
dpkg-shlibdeps: warning: 73 other similar warnings have been skipped (use -v to see them all)
dpkg-shlibdeps: warning: symbol sin used by debian/budgie-desktop/usr/lib/libraven.so.0.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol cos used by debian/budgie-desktop/usr/lib/libraven.so.0.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol sqrt used by debian/budgie-desktop/usr/lib/libraven.so.0.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol floor used by debian/budgie-desktop/usr/lib/libraven.so.0.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol pow used by debian/budgie-desktop/usr/lib/libraven.so.0.0.0 found in none of the libraries
dpkg-shlibdeps: warning: debian/budgie-desktop/usr/lib/budgie-desktop/plugins/libtrayapplet.so contains an unresolvable reference to symbol XSendEvent: it's probably a plugin
dpkg-shlibdeps: warning: 8 other similar warnings have been skipped (use -v to see them all)
dpkg-shlibdeps: warning: debian/budgie-desktop/usr/lib/budgie-desktop/plugins/libstatusapplet.so contains an unresolvable reference to symbol floor: it's probably a plugin
</pre>

any thoughts?

**Comment by ikeydoherty** [comment]
Adding explicit checking for `-lm` now.

```
checking for sin in -lm... yes
checking for cos in -lm... yes
checking for sqrt in -lm... yes
checking for floor in -lm... yes
checking for pow in -lm... yes
```

**Comment by ikeydoherty** [comment]
Should be resolved with these commits:

 - 554bb1fae6b063984e00369dde00a8e67d7d35ee
 - 1d93728d07bb27684336acf5b78659f5e7ed67d3
 - 408c3186878ed060ac4d7a832b0bcccd7e88673a

**Comment by fossfreedom** [comment]
ta - that looks ok now.

I've got these - again - a -lm for the libstatusapplet ?

<pre>
dpkg-shlibdeps: warning: debian/budgie-desktop/usr/lib/budgie-desktop/plugins/libstatusapplet.so contains an unresolvable reference to symbol floor: it's probably a plugin
dpkg-shlibdeps: warning: debian/budgie-desktop/usr/lib/budgie-desktop/plugins/libbudgiemenuapplet.so contains an unresolvable reference to symbol gtk_misc_set_alignment: it's probably a plugin
</pre>

**Comment by ikeydoherty** [comment]
Gonna fix the deprecation in BudgieMenu now too

**Comment by ikeydoherty** [comment]
OK should be all good now.

**Comment by fossfreedom** [comment]
wonderful  - it now passes the library checks.

cheers

**Comment by ikeydoherty** [comment]
Fantastic, thanks
