### ISSUE TITLE
creating a debian package - typelib issue

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#288]
Hi Ikey,

I'm getting the following error:

<pre>
dh_girepository -pbudgie-desktop 
dh_girepository: Could not find gir file for Budgie-1.0.typelib
/usr/share/cdbs/1/rules/debhelper.mk:279: recipe for target 'binary-predeb-IMPL/budgie-desktop' failed
m
</pre>

I thought that this was an error in my debian rules - so I added to the ./configure a "--disable-introspection" parameter via:

<pre>
DEB_CONFIGURE_EXTRA_FLAGS +=	\
				--disable-introspection

</pre>

On compilation though it looks like the "plugin" Makefile was indeed supposed to create such file.  Any thoughts why it threw the "Could not find gir file for Budgie-1.0.typelib" error?

<pre>
make[3]: *** No rule to make target 'Budgie-1.0.typelib', needed by 'all-am'. Stop.
make[3]: Leaving directory '/home/dad/Downloads/budgie-desktop-1.2.1/plugin'
Makefile:514: recipe for target 'all-recursive' failed
ma
</pre>

**Comment by ikeydoherty** [comment]
On Solus:

```
Package budgie-desktop has file /usr/lib64/girepository-1.0/Budgie-1.0.typelib
```

I think you're missing some gobject stuff. I'm going to go and force this in the repo now, please do not disable gobject introspection you will break support for extensions

**Comment by fossfreedom** [comment]
hmm - I'll continue to scratch my head on this one - looks like the gir and typelib stuff was created.

<pre>
dad@dad-VirtualBox:~/Downloads/budgie-desktop-1.2.1$ find . -name "*gir*"
./debian/budgie-desktop/usr/share/gir-1.0
./debian/budgie-desktop/usr/share/gir-1.0/Budgie-1.0.gir
./debian/budgie-desktop/usr/lib/girepository-1.0
./gvc/Gvc-1.0.gir
./plugin/Budgie-1.0.gir
dad@dad-VirtualBox:~/Downloads/budgie-desktop-1.2.1$ find . -name "*typelib*"
./debian/budgie-desktop/usr/lib/budgie-desktop/Gvc-1.0.typelib
./debian/budgie-desktop/usr/lib/girepository-1.0/Budgie-1.0.typelib
./gvc/Gvc-1.0.typelib
./plugin/Budgie-1.0.typelib
</pre>

**Comment by ikeydoherty** [comment]
Is it possible that Debian uses a different location for gobject stuff, and libdir is breaking it due to multiarch?

```
girdir = $(datadir)/gir-1.0
dist_gir_DATA = Budgie-1.0.gir

typelibsdir = $(libdir)/girepository-1.0/
typelibs_DATA = Budgie-1.0.typelib
```

**Comment by fossfreedom** [comment]
yep - Debian & Ubuntu doesnt use the /usr/lib64 stuff - they use /usr/lib for both 32bit and 64bit compilation.

**Comment by ikeydoherty** [comment]
But they also usr some crazy shit like /usr/lib/x86-64-gnu-linux/lib*.so

**Comment by fossfreedom** [comment]
yep - symbolic links all over the place.

tired now - past midnight here.  I'll revisit this tomorrow.  Cheers for your help.  Much appreciated.

**Comment by ikeydoherty** [comment]
np

**Comment by fossfreedom** [comment]
ok - fixed this by ensuring the architecture build was correct and that we explicitly create a gir1.2-budgie-1.0 package for budgie to build against.

**Comment by ikeydoherty** [comment]
Aah, see I wouldn't have thought of that :D
