### ISSUE TITLE
Feature: Restore budgie-panel to defaults, warn on deleting the default panel

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#289]
It is very easy to delete the panels, 

1. Go to Raven->Panel settings
2. Manage Panels, Press + and press -
3. The default panel is gone :(

Now I the user have to manually add items unless he/she knows 

alt+f2 "terminal"

$ dconf reset -f /com/solus-project/budgie-panel/  
$ nohup budgie-panel --replace

Please warn the user when the default panel is being removed.

**Comment by ikeydoherty** [comment]
We don't keep track of what is and isn't the "default panel". The second you do anything to it, it's no longer default.

I'm happy to add a prompt in Raven to ask you to confirm removing a panel if it has any applets ?

**Comment by fastrizwaan** [comment]
yes, that would be nice.

**Comment by kneerunjun** [comment]
I just now messed that up !!!, was changing a few settings on panel and had no idea the "status indicator" had the menu panel-settings-menu. I removed the "status indicator" and had no clue how to get it back! :smile:  .. now :dolphin: recovered with the command above --- sheeeesh .. such a relief!

Nevertheless  - that does change my opinion on budgie! - :+1: take my upvote .. coolest desktop till date

**Comment by ikeydoherty** [comment]
Added an option to reset the entire panel from the terminal, `budgie-panel --replace --reset`:

https://github.com/solus-project/budgie-desktop/commit/3a1d67bb657832bac05f48d816ef94e462db1283

**Comment by ikeydoherty** [comment]
Removing panels also nukes them from dconf tree:
https://github.com/solus-project/budgie-desktop/commit/15c254682400fe6aa4c01cd5bf62acb6df725e94

**Comment by ikeydoherty** [comment]
![screenshot from 2016-10-26 05-29-57](https://cloud.githubusercontent.com/assets/164489/19713355/469ea532-9b3d-11e6-9a7f-d2b460f59569.png)

**Comment by ikeydoherty** [comment]
This will feature in the next release of Budgie.

**Comment by Crare** [comment]
I still removed the panel even with the warning. It doesn't tell you it deletes the panel completely and there's no way to get it back and with just gui? Maybe just add option to reset panels to default? Also it would help if you could find the panel-thing somehow after you remove it completely.

**Comment by ikeydoherty** [comment]
Sorry but the warning couldn't be any clearer. What else do you think it's going to do?

**Comment by ikeydoherty** [comment]
And if you need to do a full reset:

`budgie-panel --reset --replace&`

**Comment by subhaniminhas** [comment]
I need to Install Ubuntu Budgie Remix on multiple work related PCs. I have to configure Budgie Desktop in a certain manner again and again. Any ways I take make a backup of Budgie Desktop settings and restore again on a new installation. Any configuration file I can copy?

**Comment by simone98dm** [comment]
I have a similar issue, I have installed Budgie as desktop environment on Linux Mint 18 and I deleted the "main" panel (upper panel). How I can restore the panel?
Nowadays I run the command `budgie-panel --reset --replace` every time when I start the pc, but it doesn't save the config which I have done.
Any ideas about how to solve it?

**Comment by fossfreedom** [comment]
@subhaniminhas yours is a different issue - suggest raise a new issue.

@simone98dm again - this appears to be a new issue.  suggest raise a new issue - dont run the reset method - CTRL+ALT+T to open a terminal on login and just run budgie-panel --replace & - hopefully there will be an error message or two indicating what your issue is.

**Comment by betodoescher** [comment]
> Adicionada uma opção para redefinir todo o painel do terminal `budgie-panel --replace --reset`:
> 
> [3a1d67b](https://github.com/solus-project/budgie-desktop/commit/3a1d67bb657832bac05f48d816ef94e462db1283)

Perfect! You saved my day!
