### ISSUE TITLE
Bug: run dialog has a line artifact in the 3rd row

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#290]
![screenshot from 2016-01-02 09-00-56](https://cloud.githubusercontent.com/assets/1161682/12073097/9170eb68-b12f-11e5-8409-eb7882f5618a.png)

1. press alt+f2
2. press L or m or x
3. observe the 3rd row it has a line,

I'm using nvidia 352 drivers, fyi.

**Comment by ikeydoherty** [comment]
Mk it's broken overshoot theming

**Comment by ikeydoherty** [comment]
Fuck me there's some ugly code in there. **goes fishing**

**Comment by ikeydoherty** [comment]
OK we're going to track this now in #293
