### ISSUE TITLE
RunDialog needs some *serious* loving

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/budgie-desktop#293]
**Coding style is inconsistent with codebase**

See `panel/manager.vala` for an example of NICE clean code :)

4 spaces, no hard tabs. No spaces after function name and between parantheses.

- Stop creating new widgets all the time.
- For now, just drop the animations, we'll reimplement them later via the Budgie Animation framework (fancy-ass way of saying GdkFrameClock wrapper)
- Allow launching commands
- Case insensitive, *proper* search (string contains, use a HashMap to cache the AppInfos probably.)
- Link against `libbudgietheme.la` for proper theming, drop it's .css file

**Comment by michaelrutherford** [comment]
I'll go ahead and take a look at it. No promises, but i'd like to knock this one out.

**Comment by ikeydoherty** [comment]
Merci!!

**Comment by ikeydoherty** [comment]
Implemented.
