### ISSUE TITLE
Bugdie runs better on Levono than on the HP ultrabook i own

### ISSUE THREAD

**Issue by jwl-crosse** [solus-project/budgie-desktop#294]
Sorry if I use GitHub wrong, and interestingly enough, I hate to say it but I noticed a certain. . .bias that you guys have toward HP. I am kind of upset and I will not take this lightly. You intentoinally throttle the speed of Bugdie on HP computers (like how that one canadian data company did to the user of the phones), and I have proof:     

$$ public int64 start_time;           /**<Start time (microseconds) of animation */
in the lib folder code
  

you are using intel GPU only programming code to boost the speed of the WM so it is better for Lenovo and Intel shills than it is on HP, which is the better of the few for enterprise devops and systems and the like. SolusOS seems to be of a biased nature of the opinion, is it not? The project CEO works for Intel, so this is almost a conflict of interest. Please fix if and when you are willing. I am working on my own WM, you may use it once and if you come to your senses and support the largest growing platform on the tech world. For now, i will help only Veldt OS and ManjaroLinux because the developers their are more than capable of supporting server and enterprise code support. Until we all meet again; i hope to meat again! 

--Powel Crosse

**Comment by jwl-crosse** [comment]
please i want you to add this to bounty source the website

**Comment by jwl-crosse** [comment]
--powel crosse

**Comment by sudopluto** [comment]
lol

**Comment by karbowiak** [comment]
You high? 
If yes, tell me what you smoke/ingest, cause I want it, shit, I NEED IT!

**Comment by jwl-crosse** [comment]
really? you ask if im high on christmas? i guess the answer is no. im just trying to uncover the truth behind this fraudelent operating system that is SolusoS. --powell crosse

**Comment by jwl-crosse** [comment]
dual booting with temple os does not work of yet either, yet another reason to not use this WM

**Comment by karbowiak** [comment]
You must be fucking high, cause if you aren't, then you must be really fucking retarded.. 

/o\

**Comment by ikeydoherty** [comment]
Dual booting has *nothing* to do with Budgie, it's a *desktop*, not an operating system.

Kindly check your facts before accusing me of being a *shill*.

Let's take a lesson here in Animation Tweening:

An animation has a given length, and a mathematical function to modify a given variable for rendering in each frame of the animation.

To **track the length and progress** of an animation you must have:

start_time

current_time

animation_length

This is animation 101 here. On a typical display running at 60Hz, the calculation is performed 60 times a second. This is to *optimise*, and thus we draw only the frames **inbetween**, aka **tweening**.

This saves load on your system tremendously, and only draws the frames you see, not the ones you *dont'*.

At each given frame, we work out how far we are into the animation by deducting the start time from the current time, and produce a decimal fraction between 0.0 and 1.0, which is our total progress in the animation. We then apply this with a mathematical function, to deduce the new constraint on the property in question, i.e. "x", "y", whichever.

Lastly, I don't even own a HP computer. So I really don't know what you want me to say there.

**Comment by jwl-crosse** [comment]
@karbowiak troll much? you never answered my question about the intel code which clearly is biased on HP

**Comment by ikeydoherty** [comment]
Oh, for the record I don't have a working Lenovo either. Just to be clear.

**Comment by karbowiak** [comment]
Int64 isn't refering to Intel, it's a 64bit integer.. Now go fuck yourself @jwl-crosse

**Comment by jwl-crosse** [comment]
@ikeydoherty thanks for the response it was inform to me. That doesnt change the fact that it is bias on HP's GPU though. What compiler does the Bugdie WM use again? If your answer is CLANG (made by Apple) then you are clearly trying to get people to use intel cards. there is no reason to make a distro and not support cards from other vendors like NVIDIA and amd

**Comment by jwl-crosse** [comment]
@karbowiak int is literally short for Intel, and what do graphics have to do with advanced math and storing numbers? need i say more?

**Comment by ikeydoherty** [comment]
Dude it's open source, use whatever compiler you want. Personally I use GCC 5.2

int is short for INTEGER.

**Comment by ikeydoherty** [comment]
https://en.wikipedia.org/wiki/Integer_(computer_science)

**Comment by karbowiak** [comment]
Why yes, you are right.. It's definitely Intel biased, how dare you ikey! You AMD hater!!!!!!!!!! 111!!1!1!1111eleven

Sigh

**Comment by jwl-crosse** [comment]
@karbowiak i was excited that i was able to reach out to someone. . .then i saw sigh. You cant be so naieve as to think that an intel employee was not hired to do a distro to make people buy intel gpus. Its in the code for jesus sake

**Comment by ikeydoherty** [comment]
Solus has nothing to do with Intel, again, get your facts straight. I'm not paid to work on Solus, it's completely independent and open source, and anyone can hack on it.

**Comment by ikeydoherty** [comment]
*Disclaimer*: The following (and previous) comments should not be mistaken to have any bearing on, or reflection of, the opinion of my employer. I make this comments freely and independently, as the founder of the Solus Project, Solus Operating System, and the Budgie Desktop Environment.

**Comment by ikeydoherty** [comment]
I've seen your post on reddit, and have the following notice to make.

**On behalf of the Solus Project, of which I am founder**:

You're a fucking muppet and you're wasting my time.
