### ISSUE TITLE
unnecessary dependency -  libpthreads?

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#295]
Hi  Ikey,

my debian package is throwing the following error - are you actually using pthreads because the build thinks not?

<pre>
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libstatusapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libnotificationsapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libseparatorapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libicontasklistapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libshowdesktopapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libtasklistapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libclockapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/libraven.so.0.0.0 debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libbudgiemenuapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libtrayapplet.so debian/budgie-desktop/usr/bin/budgie-run-dialog debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/liblockkeysapplet.so debian/budgie-desktop/usr/bin/budgie-panel debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libworkspacesapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/libspacerapplet.so debian/budgie-desktop/usr/lib/x86_64-linux-gnu/libbudgie-plugin.so.0.0.0 debian/budgie-desktop/usr/bin/budgie-wm were not linked against libpthread.so.0 (they use none of the library's symbols)
</pre>

**Comment by ikeydoherty** [comment]
s/error/warning

Off the top of my head I can't think of any threads being used in Budgie, it's all just async single-thread

**Comment by ikeydoherty** [comment]
Closing due to lack of anything actionable
