### ISSUE TITLE
debian - struggling why some .la files want to be installed in global location rather than relative

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#296]
Hi Ikey,

  I'm trying to understand the output of the entire make and make-install process produced when I'm creating my .deb

 - https://dl.dropboxusercontent.com/u/3575524/budgie2.txt

At line 4866 there is an install statement that seems to want to install into a global location on the machine rather than the relative position where the .la position actually exists - .../debian/budgie-desktop/usr/lib/...etc

This is repeated for several .la files.

Firstly - I dont know what these .la files are - are they supposed to be linked into an executable such as budgie-panel ?  If they are that will explain why when I'm looking at the file sizes of the budgie executables in /usr/bin they are about a quarter of the size that I'm seeing if I compile and install via a manual ./autogen.sh --prefix=/usr

Lastly - where is this "install" statement coming from - a Makefile ?  I'm just wondering if the Makefile is "hard-coding" the global location /usr/lib[xyz]/ - does this make sense?  sorry if I'm not making myself clear on this!

**Comment by ikeydoherty** [comment]
They're libtool files, this is normal. In Solus we remove them from our packages. I'll see if they can be disabled

**Comment by ikeydoherty** [comment]
alright so libtool will install these by default, you need to remove them in the packaging apparently. Debian should have guideliens on this ?

**Comment by fossfreedom** [comment]
yep - its straightforward to delete these.

I presume this install warning can be ignored then?

That leaves me worrying about the filesizes of the budgie executables

i.e. when installed manually via ./autogen

<pre>
-rwxr-xr-x 1 root root     57 Jan  2 14:24 budgie-desktop
-rwxr-xr-x 1 root root 899088 Jan  2 14:24 budgie-panel
-rwxr-xr-x 1 root root 151816 Jan  2 14:24 budgie-run-dialog
-rwxr-xr-x 1 root root 635800 Jan  2 14:24 budgie-wm
</pre>

whereas the debian build creates the same executables with the following file sizes

<pre>
-rwxr-xr-x 1 root root     57 Jan  2 13:57 budgie-desktop
-rwxr-xr-x 1 root root 238304 Jan  2 13:57 budgie-panel
-rwxr-xr-x 1 root root  31928 Jan  2 13:57 budgie-run-dialog
-rwxr-xr-x 1 root root 106824 Jan  2 13:57 budgie-wm
</pre>

Any thoughts?

**Comment by ikeydoherty** [comment]
That's fine, we don't strip the binaries when built from git, that's for packaging to handle. The binaries are fully stripped, which is what is supposed to happen. The libraries will be partially stripped too

**Comment by fossfreedom** [comment]
ok - ta.
