### ISSUE TITLE
System tray breaks 'panel end' theming

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#298]
Aside of the NetworkManager indicator, this ocurrs when System Tray icons change:

![captura de pantalla de 2016-01-03 00-21-36](https://cloud.githubusercontent.com/assets/12128317/12077128/55d3d8c8-b1b0-11e5-8cc3-8192609ed9e5.png)

**Comment by ikeydoherty** [comment]
Fixed
