### ISSUE TITLE
polkit version too high for debian/ubuntu?

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#299]
Hi Ikey,

re this configure issue:

Requested 'polkit-gobject-1 >= 0.110' but version of polkit-gobject-1 is 0.105
Requested 'polkit-agent-1 >= 0.110' but version of polkit-agent-1 is 0.105

anything specifically that you need 0.110 and higher or  can we drop down the version requirements for debian & ubuntu?

BTW - seems to compile OK for me with 0.105 - also the new dialog appears and works ok.

**Comment by ikeydoherty** [comment]
Eh, polkit 0.110 is from January 2013, 3 years ago. 0.105 is a year older than that...

Someone might wanna poke Debian and see if someone wants to wake up over there

**Comment by ikeydoherty** [comment]
Fixed in 115ccaf52499e5f76ccf8254d3c565a5ef303e82

**Comment by fossfreedom** [comment]
:) couldnt possibly comment.

For some reason policykit has remained at that old version... but with lots and lots of upstream patches - on my ubuntu 14 updates has been applied.

**Comment by ikeydoherty** [comment]
Fair do :) So whats your config, GNOME 3.16 for Budgie? I'd like to see it working if thats ok ? I'm sure there's a few people now mighty interested in the conversations we've been having about Debian/Ubuntu compatibility of Budgie :]

**Comment by fossfreedom** [comment]
currently I'm working with Ubuntu 16.04 which is Gnome 3.18.

Once we've got that deb working I'll fireup a Ubuntu 15.10 virtual that comes with Gnome 3.16 and see what is what.

**Comment by ikeydoherty** [comment]
Does it actually look ok on Ubuntu though? Their crazy patches and themes really did a lot of damage to the reputation of the old Budgie, I'm hopeful that won't be the case this time

**Comment by fossfreedom** [comment]
yep - as long as you use at a minimum adwaita and humanity icons - dont use the ubuntu ambiance and ubuntu icon set.

Currently using Horst Arc-theme which looks pretty good.  I'm going to play with the moka-icon-theme later.
