### ISSUE TITLE
gvc source - cannot auto-download

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#303]
I've been doing some quick test PPA builds and fell over this bit in autogen.sh

<pre>
# Fetch submodules if needed
if test ! -f gvc/Makefile.am;
then
  echo "+ Setting up submodules"
  git submodule init
fi
git submodule update
</pre>

In debian and launchpad you cannot git clone stuff from external sources - it must be all within the source tree.

Question - rather than having to depend on something that could be constantly changing - maybe better to clone a known good version that you are going to use for Solus directly into the budgie source?

Other query - isnt there a library module prepackaged for this which you can make it a dependency to build against?

For the moment I've manually git cloned this and am carrying the whole  source that is cloned as a debian patch.

**Comment by ikeydoherty** [comment]
> In debian and launchpad you cannot git clone stuff from external sources - it must be all within the source tree.

This is why we distribute tarballs. They contain gvc.

> Question - rather than having to depend on something that could be constantly changing - maybe better to clone a known good version that you are going to use for Solus directly into the budgie source?

Have a look at the .gitmodules, we use a specific commit. It isn't changing

> Other query - isnt there a library module prepackaged for this which you can make it a dependency to build against?

No, otherwise we'd use that and not a git submodule :)

**Comment by fossfreedom** [comment]
Makes sense!  Any chance a comment in the autogen.sh file be added to say all of this... Will stop similar q's ... probably


Sent from Outlook Mobile






On Sun, Jan 3, 2016 at 9:14 AM -0800, "Ikey Doherty" <notifications@github.com> wrote:





> In debian and launchpad you cannot git clone stuff from external sources - it must be all within the source tree.

This is why we distribute tarballs. They contain gvc.

> Question - rather than having to depend on something that could be constantly changing - maybe better to clone a known good version that you are going to use for Solus directly into the budgie source?

Have a look at the .gitmodules, we use a specific commit. It isn't changing

> Other query - isnt there a library module prepackaged for this which you can make it a dependency to build against?

No, otherwise we'd use that and not a git submodule :)

---
