### ISSUE TITLE
Budgie-desktop session failed to start since v10.2.2

### ISSUE THREAD

**Issue by X0rg** [solus-project/budgie-desktop#308]
I start Budgie Desktop with `startx`, my .xinitrc contains `exec gnome-session --session=budgie-desktop`.
Since v10.2.2, Budgie-session fails to start (it works with v10.2.1): panel and WM don't start. I can start them manually.

Using up-to-date Arch Linux, tested on 3 hosts (i686 and x86_64) including 2 VMs.

I attach gnome-session log (--debug option enabled): [gnome.txt](https://github.com/solus-project/budgie-desktop/files/76939/gnome.txt)

**Comment by juvevood** [comment]
seems budgie-panel crashed. it works with v10.2.1 .

**Comment by X0rg** [comment]
Still not fixed with v10.2.3.

**Comment by Anachron** [comment]
Seems like I have the same issue. I cannot start budgie-desktop using .xinitrc and startx on latest arch install.

**Comment by X0rg** [comment]
An ugly solution:
```
dbus-launch --exit-with-session gnome-session --session=budgie-desktop & \
budgie-panel & \
budgie-wm
```
But I can't use the power menu. A fix is still needed.

**Comment by ikeydoherty** [comment]
Budgie doesn't need a fix here. It seems to me you actually have an incomplete install. Check gnome-session, etc, are all installed. A recent bug with Pacman 5 broke things in Arch, this isn't something we can fix. (Relational dependencies show as satisfied when they're not)

**Comment by Anachron** [comment]
Hey @ikeydoherty even after fixing my issue with non-installed dependency (my AUR package manager was not up-to-date) I still have trouble launching budgie-desktop. No matter what I put into my `.xinitrc`, I get a black screen.

**Comment by X0rg** [comment]
I have checked dependencies manually, they are all installed.
```
libwnck3>=3.14  gnome-menus>=3.10.1 gnome-settings-daemon 
libpeas>=1.3.0  mutter>=3.18 desktop-file-utils  libgee
gnome-themes-standard gtk3>=3.16  libpulse  upower  intltool
gnome-session>=3.18  gnome-terminal gnome-control-center
nautilus  libpulse>=2 gnome-desktop>=3.18  upower>=0.9.20 polkit>=0.105
```
I have reinstalled whole packages on my system, it doesn't solve this issue.

**Comment by ikeydoherty** [comment]
Why are you using `dbus-launch` ? Are you using kdbus or something?

**Comment by X0rg** [comment]
My .xinitrc is: `exec gnome-session --session=budgie-desktop`. But when I use it, I have only desktop icons on `startx`:
![screenshot](https://cloud.githubusercontent.com/assets/2873785/13378431/dc06eade-de06-11e5-80d0-94c24e658619.png))

Forget the ugly .xinitrc with dbus-launch, I use it only to have an usable desktop, I'm waiting for a fix.

**Comment by ikeydoherty** [comment]
Where are those icons even coming from? O_O

**Comment by X0rg** [comment]
After reading the gnome-session output (see my first post), I find that:
```
gnome-session-binary[650]: DEBUG(+): GsmManager: Phase WINDOW_MANAGER
gnome-session-binary[650]: DEBUG(+): app /org/gnome/SessionManager/App1 is not for the current desktop
gnome-session-binary[650]: DEBUG(+): GsmManager:	ID: /org/gnome/SessionManager/App1	app-id:budgie-wm.desktop	is-disabled:1	is-conditionally-disabled:0
gnome-session-binary[650]: DEBUG(+): GsmManager: Phase PANEL
gnome-session-binary[650]: DEBUG(+): app /org/gnome/SessionManager/App3 is not for the current desktop
gnome-session-binary[650]: DEBUG(+): GsmManager:	ID: /org/gnome/SessionManager/App3	app-id:budgie-panel.desktop	is-disabled:1	is-conditionally-disabled:0
gnome-session-binary[650]: DEBUG(+): GsmManager: Phase DESKTOP
gnome-session-binary[650]: DEBUG(+): app /org/gnome/SessionManager/App4 is not for the current desktop
gnome-session-binary[650]: DEBUG(+): GsmManager:	ID: /org/gnome/SessionManager/App4	app-id:budgie-polkit.desktop	is-disabled:1	is-conditionally-disabled:0
```

They are disabled because there is `OnlyShowIn=Budgie;` in .desktop files.
It seems XDG_CURRENT_DESKTOP it not set.
When I put `XDG_CURRENT_DESKTOP=Budgie:GNOME exec gnome-session --session=budgie-desktop` in my .xinitrc, it solves this issue.

**Comment by ikeydoherty** [comment]
So I was discussing this with someone on IRC last night, that's one part of the issue, along with the dbus-launch trick.

I'll be happy to accept a `start-budgie` script, similar to `startxfce4` into the official repo, if someone wants to prepare one.

**Comment by X0rg** [comment]
After looking in Gnome session and Cinnamon session how XDG_CURRENT_DESKTOP is set, I have found they use csm_util_setenv() function.
Put `csm_util_setenv("XDG_CURRENT_DESKTOP", "Budgie")` in source code can solve it.

But I think it's easier to set this environnement variable in budgie-desktop (see #350).
And put `exec budgie-desktop` in .xinitrc.

**Comment by Anachron** [comment]
@X0rg so it works on arch with budgie-desktop-git now?

**Comment by X0rg** [comment]
Yes. Try with `exec budgie-desktop` in your .xinitrc.

**Comment by Anachron** [comment]
@X0rg thanks that did the trick!

**Comment by pomkos** [comment]
Sorry to revive an old thread, but was the start-budgie script ever implemented? If not, what is the command to start the GUI from the terminal? If so, it doesn't seem to work for me.
