### ISSUE TITLE
Suspend and Hibernate

### ISSUE THREAD

**Issue by danboid** [solus-project/budgie-desktop#309]
I probably suspend my laptop more than I power it off, at least when running other desktops so I'd like to see Suspend and Hibernate added as options to the Budgie power off/reboot/logout window.

**Comment by ikeydoherty** [comment]
Too many options to put together in the same window, we need to rethink this

**Comment by feskyde** [comment]
@ikeydoherty There is a [GNOME Shell extension](https://extensions.gnome.org/extension/755/hibernate-status-button/) that puts an 'hibernate' button aside of the 'power' button, what about a new icon on the bottom of Raven (thus another dialog for suspend/hibernate)?

![](https://extensions.gnome.org/static/extension-data/screenshots/screenshot_755.png "This.")

**Comment by ikeydoherty** [comment]
I'll have to see how it works because the GNOME Session API is a bit .. limited

```
      Shutdown();
      Reboot();
      CanShutdown(out b is_available);
      Logout(in  u mode);
      IsSessionRunning(out b running);
```

**Comment by danboid** [comment]
That is cacky news Mr D but I'm sure you'll come up with something!

I don't use G3 but every otherLinux desktop of note supports suspend/hib including MATE and I'm sure regular G2 did too so I find it strange that G3 doesn't!

**Comment by ikeydoherty** [comment]
Oh it does, just in a weird-ass way and not through the public API, but did we expect anything less? ^^ You also need to use a keyboard modifier when clicking to launch the end session dialog to even see the options

**Comment by danboid** [comment]
There's another aspect of this request that I totally forgot to mention. Maybe I'm missing it but I can't see any options to set what happens when I close my laptop lid under the budgie (G3?) power settings. I either have it set to Do Nothing / blank screen or suspend on close normally

Maybe it's something that the Cinnamon guys added into their fork but that certainly has such options, I don't know about G3 as I don't want to install it to find out.

I should've also mentioned the workaround I'm using until budgie gains better PM support which is to run `pm-suspend` to enter suspend mode.

**Comment by starquake** [comment]
My laptop suspends successfully with Budgie 10.2.2 on Arch when I close the lid. So I wouldn't mind if the suspend button would be optional. 

BTW I saw an option in gnome-tweak-tool: [When Laptop Lid is Closed](http://i.imgur.com/iN0G9NX.png)  Do you have that disabled?

**Comment by ikeydoherty** [comment]
Solved with the recent introduction of the User Indicator by @JoshStrobl  - much props!

**Comment by thymbahutymba** [comment]
@starquake how you can open Gnome-Tweak-Tool with budgie? I have one error: 
`WARNING : Shell not installed or running
WARNING : Shell not running
None
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 279, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gtweak/app.py", line 41, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python2.7/site-packages/gtweak/tweakview.py", line 58, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python2.7/site-packages/gtweak/tweakmodel.py", line 126, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 335, in <module>
    ShellExtensionTweakGroup(),
  File "/usr/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 309, in __init__
    shell._settings.bind("disable-user-extensions", self.titlebar_widget,
AttributeError: 'NoneType' object has no attribute '_settings'
`

**Comment by fossfreedom** [comment]
This is not a problem with budgie-desktop - your distro will need to patch gnome-tweak-tool to not crash when its opened on a non gnome-shell desktop environment. https://bugzilla.gnome.org/show_bug.cgi?id=780794

**Comment by ikeydoherty** [comment]
Also note that part of my patch here deals with fixing the startup crash https://bugzilla.gnome.org/show_bug.cgi?id=781321

**Comment by thymbahutymba** [comment]
@ikeydoherty i don't understand how i can apply this patch. What i need to do?

**Comment by fossfreedom** [comment]
@thymbahutymba basically you need to unpack the source of your gnome-tweak-tool package then apply the patch (or patches) via patch -p1 < <full-path-to-the-patch-filename>

if in doubt contact your distro maintainer to get gnome-tweak-tool correctly patched.

**Comment by thymbahutymba** [comment]
I use Archlinux, i clone gnome-tweak-tool from git, i copy all patch file into directory and i give your command, but i have some error. 
```Hunk #1 FAILED at 144.
Hunk #2 succeeded at 160 (offset -4 lines).
1 out of 2 hunks FAILED -- saving rejects to file gtweak/widgets.py.rej
```
This is one, but i have other Hunk Failed.

**Comment by ikeydoherty** [comment]
There are 2 patches listed there. One is for GNOME 3.24 and one is for git master, clearly labelled.
In your case apply it the 3.24 patch to your 3.24 tarball.

**Comment by thymbahutymba** [comment]
So... i need to patch https://bugzilla.gnome.org/show_bug.cgi?id=780794 this. I donwload code from git, i try to apply patch with 
`patch -p1 < <path to patch file> (into gnome-tweak-tool directory) and it give me this error:
```
patching file gtweak/tweaks/tweak_group_shell_extensions.py
Hunk #1 FAILED at 306.
1 out of 1 hunk FAILED -- saving rejects to file gtweak/tweaks/tweak_group_shell_extensions.py.rej
```
How i can run gnome-tweak-tool without gnome-shell?

**Comment by ikeydoherty** [comment]
I said tarball ... I thought you were an Arch user? :P

**Comment by danboid** [comment]
Ha hee!

Good one Ikey, and props for being gracious enough for helping him this far. Most other distro maintainers/devs wouldn't give this much slack.

Tip to thymba:

Try using patch -p0 / patch -p1 and try different paths ie run patch in the same dir as the files to patch, then one level above etc. That dance has served me very well over the last couple of decades and one combo will usually work, if the patch and sources align.

**Comment by ikeydoherty** [comment]
```
wget http://ftp.acc.umu.se/pub/gnome/sources/gnome-tweak-tool/3.24/gnome-tweak-tool-3.24.0.tar.xz
tar xf gnome-tweak-tool-3.24.0.tar.xz
cd gnome-tweak-tool-3.24.0
patch -p1 < PATH-TO-THE.patch
./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib
make -j$(($(getconf _NPROCESSORS_ONLN)+1))
sudo make install
```

**Comment by thymbahutymba** [comment]
@ikeydoherty yes i'm archlinux user, i understand i need to dowload tar.xz package from official repository, extract, apply pacth, re-build tar.xz and after install. The patch was applied successful but i can't compress "directory"

**Comment by ikeydoherty** [comment]
Well shit, that works :P Kudos on the monkeypatch approach xD

**Comment by thymbahutymba** [comment]
Ahahah, of course. Reality the problem was another, i open gnome-tweak-tool to set "block after suspend" and i don't found it! Ahah
