### ISSUE TITLE
Panel crashes on Arch when pressing Windows key multiple times

### ISSUE THREAD

**Issue by theSoenke** [solus-project/budgie-desktop#316]
When i press the Windows key multiple times on Arch the panel disappears. How often i have to press the key varies, but after some time it almost always crashes.
I'm using Budgie v10.2.2

**Comment by theSoenke** [comment]
Sometimes it even crashes suddenly without pressing the windows key. Only way to get it back is to first set position to top and then back to bottom in the settings

![budgie-panel-crash](https://cloud.githubusercontent.com/assets/1757301/12518814/154e2872-c13b-11e5-9cab-acc3a13f38cc.png)

**Comment by starquake** [comment]
I'm also runing Budgie v10.2.2. Tried hitting the superkey about 30 times. With the panel at the top and with the panel at the bottom. I'm not having the problem. Any more specifics about your setup?

**Comment by theSoenke** [comment]
I'm using budgie-desktop from the AUR https://aur4.archlinux.org/packages/budgie-desktop
Lately it was not always reproducible when i tried, but it especially happens when i hit the superkey multiple times quite fast

**Comment by theSoenke** [comment]
Another thing i noticed is that it only seems to crash when the panel is at the bottom. 
I don't know whether it's related to this, but when i open the menu sometimes it shows up for a few milliseconds at the top instead of the bottom

**Comment by johnfraney** [comment]
I can't reproduce this bug (Arch, Budgie 10.2.3-3 from AUR)

**Comment by ikeydoherty** [comment]
Cannot reproduce this issue in any configuration. Please update to the latest version, and verify it still happens

**Comment by theSoenke** [comment]
Was also not able to reproduce this anymore. Can be closed for now

**Comment by ikeydoherty** [comment]
\o/
