### ISSUE TITLE
Budgie notifications must use GTK_WINDOW_TYPE_POPUP

### ISSUE THREAD

**Issue by zesterer** [solus-project/budgie-desktop#317]
The title says it all really. Whenever a notification pops up, the window it creates is visible to the window manager as an application window that gets shown in panels and other window management things.

I'm running MATE with budgie-panel, so I wouldn't be surprised if this issue is just due to my stupid setup. But based on my own adventures with desktop panel development, it seems like a more general issue with libwnck.

**Comment by ikeydoherty** [comment]
```vala

    public NotificationWindow(NotificationsView? owner)
    {
        Object(type_hint: Gdk.WindowTypeHint.NOTIFICATION, owner: owner);
        resizable = false;
        skip_pager_hint = true;
        skip_taskbar_hint = true;
```

I would suggest there is something broken in Marco or libwnck, in this instance.

**Comment by feskyde** [comment]
I'm using Solus with Budgie 10.2.2, notifications appear and dissapears in tasklist fastly, executing ´notify-send´ a lot of times makes this issue more visible

**Comment by ikeydoherty** [comment]
Normal tasklist? They don't show in the icon tasklist

**Comment by feskyde** [comment]
Yes

**Comment by ikeydoherty** [comment]
The only way to stop this apparently is to enforce a GTK_WINDOW_TYPE_POPUP, which in turn breaks the shadows

**Comment by ikeydoherty** [comment]
We'll have to enforce it as indicated above, and do the shadow rendering separately. Can't have these crappy issues :D

**Comment by ikeydoherty** [comment]
Implemented. Please note that in future versions of Budgie, using another WM won't be possible
