### ISSUE TITLE
Icon-only Task List: some icons "flashes" when mouse keeps over them

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#318]
- Better explained here:

https://www.youtube.com/watch?v=Gda865461-M

- Note that also window name is not shown

- This not occurs with normal Task List or using GTK3 applications

- The applications that I've tested and has this issue are all GTK2 and Qt5:
 - Firefox
 - Atom
 - Chrome
 - HexChat
 - LibreOffice
 - SimpleScreenRecorder

- For one reason, Telegram Desktop has not any problem

**Comment by ikeydoherty** [comment]
This should be fixed in latest git if you wanna confirm

**Comment by JoshStrobl** [comment]
Not resolved as of master.

**Comment by ikeydoherty** [comment]
Certainly fixed now right?

**Comment by JoshStrobl** [comment]
Yea can't reproduce it at this point.

**Comment by ikeydoherty** [comment]
Ta
