### ISSUE TITLE
nm-applet icon is very small

### ISSUE THREAD

**Issue by Nimayer** [solus-project/budgie-desktop#319]
Network Manager Applet icon appear very small and barely usable on Budgie Desktop 10.2.2
The leftmost icon is the network one:
![small_icon](https://cloud.githubusercontent.com/assets/7339271/12377360/82f026a6-bd1b-11e5-8845-2cec8718fc9a.png)
Tried both the git and AUR versions on Arch Linux

**Comment by Ste74** [comment]
In my manjaro/arch installation is fine , have you try to change icon set ?

**Comment by Nimayer** [comment]
Also tried Evopop or Numix Circle icons but the issue is still there.
What version of Budgie Desktop are you using?

**Comment by feskyde** [comment]
> Update: After installing and opening Telegram-desktop binary from AUR,
the network icon became normal, maybe this helps

Seems to if tray initializes with one icon, it gets small, and a second icon restores the normal size of the tray.

**Comment by starquake** [comment]
Yep that fixes it for me too. Thanks for the workaround.

**Comment by ikeydoherty** [comment]
This is fixed in git and 10.2.4
