### ISSUE TITLE
budgie-panel doesn't fill the entire screen (2560x1440)

### ISSUE THREAD

**Issue by roidm** [solus-project/budgie-desktop#321]
hi, i've installed the budgie-desktop from AUR repo and this is what i get when i login (first pic)

if i press the win key this is what i get (second pic)

<a href="http://imgur.com/0G9iFmj"><img src="http://i.imgur.com/0G9iFmjm.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/TF3kbzc"><img src="http://i.imgur.com/TF3kbzcm.png" title="source: imgur.com" /></a>

System
Arch Linux
Intel Core i7-4790K 
opensource radeonsi driver AMD 7870
(same thing happens using the internal Intel GPU)

**Comment by ikeydoherty** [comment]
How are you logging in.. ? The only time I've ever seen this is when testing XWayland

**Comment by roidm** [comment]
using GDM

**Comment by ikeydoherty** [comment]
Versions.. ? Of .. all of it. :D

**Comment by roidm** [comment]
gdm 3.18.2
mesa 11.1.1
xf86-video-ati 7.6.1 
kernel 4.4.0

btw same thing happens if i logging in with sddm

**Comment by ikeydoherty** [comment]
Please ensure you're doing a clean build from git, and please verify you're not using this via a Wayland greeter or similar. Also verify your version of `mutter`

**Comment by roidm** [comment]
gdm-x-session 
mutter 3.18.2 
clean build from git 
Arc-theme from git 
<a href="http://imgur.com/paMMLHy"><img src="http://i.imgur.com/paMMLHym.png" title="source: imgur.com" /></a>

**Comment by angiest** [comment]
Same issue here. Both installs are Antergos with the latest budgie-desktop from the AUR (10.2.3).  The panel appears as a window and doesn't actually display the panel until I  hit Alt+F2.  I am using lightdm with the lightdm-webkit2-greeter.  Both were working with the previous version in the AUR (10.2.2, I think).  I am currently on a VM.  The other is a laptop with Intel graphics.

Current environment:
extra/mutter 3.18.2-1 (gnome) [installed]
extra/lightdm 1:1.16.7-3 [installed]
extra/xf86-video-vmware 13.1.0-3 (xorg-drivers xorg) [installed]
extra/mesa 11.1.2-1 [installed]
aur/budgie-desktop 10.2.3-3 [installed] (43)
Kernel: 4.4.1-2-ARCH

**Comment by ikeydoherty** [comment]
OK the change I linked above, plus all the recent changes, assures me its now impossible for a Budgie Panel to *ever* have a titlebar (Which should *already* be impossible. Your mutter makes me frown :))

So, please try again with the `budgie-desktop-git` package and let me know how that goes I guess?

**Comment by roidm** [comment]
it works ok now  , thx :)

<a href="http://imgur.com/xWLzf2d"><img src="http://i.imgur.com/xWLzf2dm.png" title="source: imgur.com" /></a>

maybe the raven it's a little bit too wide? what do you think?

**Comment by ikeydoherty** [comment]
It's HUGE! :D I'll fix the ellipsization stuff in a short while so you don't get whiplash trying to use Raven ^^

**Comment by angiest** [comment]
It works on clean installs for me (budgie installed first, no other desktop
environments).  It must have been some kind of weird conflict.

On Sun, Mar 27, 2016 at 7:40 AM, Ikey Doherty <notifications@github.com>
wrote:

> It's HUGE! :D I'll fix the ellipsization stuff in a short while so you
> don't get whiplash trying to use Raven ^^
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/solus-project/budgie-desktop/issues/321#issuecomment-202056388>
>



-- 

We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
    - TS Eliot, "Little Gidding," from "Four Quartets"

**Comment by ikeydoherty** [comment]
Well, glad everything is back to normal now ^_^
