### ISSUE TITLE
Budgie notification doesn't resize

### ISSUE THREAD

**Issue by dn5** [solus-project/budgie-desktop#322]
I'm using latest version of Solus (official ISO). When editing top panel size, the budgie notification doesn't resize to it's full size.  
  
My resolution: 1366x768
Tested on Dell 3542
  
Steps to reproduce:  
* Go to budgie notification
* Go to settings
* Set budgie panel size to e.g. 17px
* Close notification
* Open notification panel again

Result:
![Issue](http://i.imgur.com/MS8FV9A.png)

**Comment by ikeydoherty** [comment]
Please apply all updates, this was addressed.

```
sudo eopkg up
```

Logout and then back in

**Comment by ikeydoherty** [comment]
(Obv if it DOESN'T work - reopen :D)

(p.s. i suck at housekeeping.)

**Comment by dn5** [comment]
Sorry, didn't look into. The update worked. Thanks.
