### ISSUE TITLE
Theming: Tasklist shows dotted borders.

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#324]
This appears when I switch from a window to another:

![2016-01-20-175020_603x78_scrot](https://cloud.githubusercontent.com/assets/12128317/12462672/4d7d0dc4-bf9e-11e5-8275-04ecb73bdef2.png)

**Comment by ikeydoherty** [comment]
ya technically it's a focus issue, aware of it but thanks for raising the issue, means I'll ensure I fix it now :D

**Comment by feskyde** [comment]
And menu has the same issue when navigating with arrow keys, it will look better with a lighter grey background IMHO

**Comment by ikeydoherty** [comment]
fixed
