### ISSUE TITLE
Task List Plugin is missing

### ISSUE THREAD

**Issue by alex285** [solus-project/budgie-desktop#327]
Not sure when this has been introduced. Just compiled from master, and task list and icon applets are missing from options.

**Comment by ikeydoherty** [comment]
Please ensure you install *all* build dependencies, you'll notice in `config.log` you're missing `libwcnk-3.0`

**Comment by alex285** [comment]
Thanks that worked! I didnt notice that JHBuild was rebuilding without reconfiguring after installed libwcnk :/

**Comment by ikeydoherty** [comment]
Aah ok :]
