### ISSUE TITLE
Click on Notifications/Status Indicator top panel applets behaviour with interaction to Raven

### ISSUE THREAD

**Issue by bosyi** [solus-project/budgie-desktop#329]
So i think that if you clicked on 'Status indicator' applet in top panel and Raven reveals with tab Applets activated and then you click on 'Notifications' applet in top panel Raven tab just should be switched to Notifications and not close Raven as it do now.
The same about when 'Notifications' tab of Raven active and you click on 'Status indicator' applet in top panel.

**Comment by ikeydoherty** [comment]
Now the Raven indicator opens Raven, Notifications Icon opens Raven specifically to Notifications View, and that's it. Fully consistency :)
