### ISSUE TITLE
Sound Devices in Raven not verbose enough

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/budgie-desktop#337]
**Image of Sound applet in Raven**:

![screenshot from 2016-02-11 18-45-45](https://cloud.githubusercontent.com/assets/156574/12983245/131399fa-d0f1-11e5-8a76-9b48f7b0d28f.png)

In the image above, we see:
- In Output:
 - 1x Digital Output (S/PDIF)
 - 2x "Speakers" entries
- In Input:
 - 1x Internal Microphone
 - 2x Digital Input (S/PDIF) entries
 - 2x Microphone

In reality (there are screenshots below these bullet points):
- In output:
 - Digital Output (S/PDIF) is actually "Digital Output (S/PDIF) - Yeti Stereo Microphone
 - One speaker is "Speakers - Yeti Stereo Microphone" (you can play sound out of it, alongside your own voice feedback)
 - One speaker is "Speakers - Built-in Audio"
- In input:
 - One Digital Input (S/PDIF) is actually "Digital Input (S/PDIF) - Yeti Stereo Microphone"
 - One Digital Input (S/PDIF) is actually "Digital Input (S/PDIF) - HD Pro Webcam C920"
 - One Microphone is actually "Microphone - Yeti Stereo Microphone"
 - One Microphone is actually "Microphone - HD Pro Webcam C920"
 - Internal Microphone is "Internal Microphone - Built-in Audio"

**Output in Gnome Control Center**:

![screenshot from 2016-02-11 19-03-10](https://cloud.githubusercontent.com/assets/156574/12983532/51e1672e-d0f2-11e5-9c59-a92d63275ef5.png)

**Input Gnome Control Center**:

![screenshot from 2016-02-11 19-04-24](https://cloud.githubusercontent.com/assets/156574/12983548/663f1446-d0f2-11e5-8e1f-8e5b0e3afe00.png)

---

I would like to see more verbose names for everything except "Internal Microphone" (since that implies the built-in microphone, where as doing the same for speakers would still create a lack of clarity).

**Comment by ikeydoherty** [comment]
![screenshot from 2016-03-20 18-09-26](https://cloud.githubusercontent.com/assets/164489/13906121/eba34520-eec6-11e5-9d42-b96eddf99da4.png)

Le fix.
