### ISSUE TITLE
ubuntu powerindicator compilation issue

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#339]
I'm trying to recompile the status applets under ubuntu

I get this error:

<pre>
 make[1]: Entering directory '/home/dad/Downloads/sparky/budgie-desktop-10.2.3/panel/applets/status'
rm -f libstatusapplet_la_vala.stamp && echo stamp > libstatusapplet_la_vala.stamp-t
CDPATH="${ZSH_VERSION+.}:" && cd . && /usr/bin/valac --pkg gtk+-3.0 --pkg gvc-1.0 --pkg upowerglib-1.0 --pkg gio-unix-2.0 --pkg libpeas-1.0 --pkg PeasGtk-1.0 --pkg budgie-1.0 --pkg posix --vapidir=../../../plugin --vapidir=../../../vapi  -C StatusApplet.vala PowerIndicator.vala SoundIndicator.vala
error: Package `upowerglib-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
</pre>

in `/usr/share/gir-1.0` the upower gir file is this (note the case sensitivity) "UPowerGlib-1.0.gir"

if I change the Makefile from `upowerglib-1.0` to `UPowerGlib-1.0` the status applet compiles successfully but fails on the powerindicator applet compilation as follows - any ideas how to overcome this?

<pre>
libstatusapplet_la_VALAFLAGS = \
	--pkg gtk+-3.0 \
	--pkg gvc-1.0 \
	--pkg UPowerGlib-1.0 \
	--pkg gio-unix-2.0 \
	--pkg libpeas-1.0 \
	--pkg PeasGtk-1.0 \
	--pkg budgie-1.0 \
	--pkg posix \
	--vapidir=${top_srcdir}/plugin \
	--vapidir=${top_srcdir}/vapi
</pre>

    PowerIndicator.c:18:28: fatal error: UPowerGlib-1.0.h: No such file or directory
compilation terminated.

**Comment by ikeydoherty** [comment]
`upower-glib-1.0` is in the ./vapi directory

**Comment by ikeydoherty** [comment]
^ That one turned out to be my fault, sorry :D
