### ISSUE TITLE
ubuntu 16.04 theme folder does not compile

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#340]
Taking the release tarball and compiling without removing any vala .c files...

when compiling I get the following compilation issue with the theme folder - any thoughts?

<pre>

make[3]: Entering directory '/home/dad/Downloads/sparky/budgie-desktop-10.2.3/theme'
make  all-am
make[4]: Entering directory '/home/dad/Downloads/sparky/budgie-desktop-10.2.3/theme'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o libbudgietheme_la-budgie-theme-resources.lo `test -f 'budgie-theme-resources.c' || echo './'`budgie-theme-resources.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c budgie-theme-resources.c  -fPIC -DPIC -o .libs/libbudgietheme_la-budgie-theme-resources.o
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o libbudgietheme_la-theme.lo `test -f 'theme.c' || echo './'`theme.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c theme.c  -fPIC -DPIC -o .libs/libbudgietheme_la-theme.o
/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,defs -Wl,-O1 -Wl,--as-needed -o libbudgietheme.la -rpath /usr/lib/x86_64-linux-gnu libbudgietheme_la-budgie-theme-resources.lo libbudgietheme_la-theme.lo  
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libbudgietheme_la-budgie-theme-resources.o .libs/libbudgietheme_la-theme.o   -Wl,--as-needed  -pthread -O2 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,defs -Wl,-O1   -pthread -Wl,-soname -Wl,libbudgietheme.so.0 -o .libs/libbudgietheme.so.0.0.0
.libs/libbudgietheme_la-budgie-theme-resources.o: In function `budgie_desktop_theme_get_resource':
/home/dad/Downloads/sparky/budgie-desktop-10.2.3/theme/budgie-theme-resources.c:12692: undefined reference to `g_static_resource_get_resource'
.libs/libbudgietheme_la-budgie-theme-resources.o: In function `resource_constructor':
/home/dad/Downloads/sparky/budgie-desktop-10.2.3/theme/budgie-theme-resources.c:12806: undefined reference to `g_static_resource_init'
.libs/libbudgietheme_la-budgie-theme-resources.o: In function `resource_destructor':
/home/dad/Downloads/sparky/budgie-desktop-10.2.3/theme/budgie-theme-resources.c:12811: undefined reference to `g_static_resource_fini'
collect2: error: ld returned 1 exit status
Makefile:549: recipe for target 'libbudgietheme.la' failed
</pre>

**Comment by ikeydoherty** [comment]
What version of glib/gtk.. ?

**Comment by fossfreedom** [comment]
libglib2.0-0  is 2.47.5
libgtk-3-0 is 3.18.7
