### ISSUE TITLE
Kill Gnome Tweak Tool with fire

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/budgie-desktop#341]
I think it is reasonable to bring common functionality from Gnome Tweak Tool into Budgie to eliminate the need for a separate tool for changing the appearance of the desktop.

Items I propose for bringing into the Budgie Settings -> General -> Appearance in Raven:

- [x]  Enable desktop icons
- [x]  Cursor Theme

I also propose the addition of a "Fonts" section to Budgie Settings -> General in Raven with:

- [x] Window Titles
- [x] Interface
- [x] Documents
- [x] Monospace

I think it is debatable whether hinting / antialiasing should be in the fonts section or should remain in Tweak Tools. Generally hinting / antialiasing isn't something typically tweaked, even via GTT, but rather using infinality patches, which are outside the scope of this project.

**Comment by ikeydoherty** [comment]
![screenshot from 2016-03-26 18-42-54](https://cloud.githubusercontent.com/assets/164489/14061850/19eb9c96-f383-11e5-875b-70517ae46796.png)

**Comment by Ste74** [comment]
But for changing wallpaper , background locker ?

**Comment by JoshStrobl** [comment]
@Ste74 You can already change your wallpaper with Gnome Control Center -> Background. This is for Gnome Tweak Tool stuff.

**Comment by ikeydoherty** [comment]
Keeping 1992 happy

![screenshot from 2016-03-26 19-03-00](https://cloud.githubusercontent.com/assets/164489/14061924/6adab270-f385-11e5-8a86-7b72f7a15dc5.png)

**Comment by Ste74** [comment]
@JoshStrobl damn you are right :wink:

**Comment by danboid** [comment]
Any idea why I don't see a desktop icons option under Budgie/Raven git (built afresh just now) running under Arch?

I need to launch some GUI programs with special options (to set proxy settings under Chrome, for example) so I need desktop icons to avoid having to open a terminal a use an alias or run a script.

**Comment by danboid** [comment]
I have seen desktop icons appear under budgie sometimes but they don't show most of the time.

**Comment by ikeydoherty** [comment]
You need Nautilus installed.

**Comment by danboid** [comment]
Thanks Ikey!

A quick tip for any other fans of retro desktop paradigms:

Nautilus (Files) defaults to really large icons. To shrink them I had to open Files, click on a file icon then hold down CTRL and use the mouse scroll wheel to resize the icons.

**Comment by ikeydoherty** [comment]
https://git.solus-project.com/packages/nautilus/tree/files/0001-Sane-sensible-defaults.patch :)

**Comment by bogdantomasciuc** [comment]
A way to change startup applications would be nice.

**Comment by ikeydoherty** [comment]
The issue is closed.
