### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by MichaelTiebesl** [solus-project/budgie-desktop#342]
When i open some applications i don't get the default icon-theme in my task-bar.
Any idea how to fix this?

![schermafdruk van 2016-02-21 15-58-09](https://cloud.githubusercontent.com/assets/10792019/13201609/6055fa12-d8b4-11e5-9dbb-4b72042d43e1.png)

**Comment by ikeydoherty** [comment]
This is how X11 applications work. Both hexchat and Google Chrome enforce their own icon decision and send that to the X11 server, which Budgie Panel respects. We use this in place of an application icon if we're told to. It's not actually a bug.

**Comment by ikeydoherty** [comment]
I know a few people have mixed feelings about this, so it's kinda up in the air until I find the best approach

**Comment by MichaelTiebesl** [comment]
Okay, thanks for your time. Then i will wait until the air blows in my direction. :P

**Comment by ikeydoherty** [comment]
Fixed
