### ISSUE TITLE
[10.2.2] network icon strange behavior

### ISSUE THREAD

**Issue by streambinder** [solus-project/budgie-desktop#345]
Hi. It actually isn't really a bug, but I just want to report it.
Network icon in the tray part of the budgie panel behaves in very different ways in very random times.
First, the stock and standard icon is too much different from the others: dark and not that visible.
Second, it sometimes happens that it becomes a little point, instead of an icon. It does not disappear, it just become a little point.
Finally, it rarely happens that totally disappear.

Thank you. Cheers!

**Comment by starquake** [comment]
> First, the stock and standard icon is too much different from the others: dark and not that visible.

I think this depends on the icon-theme you are choosing. If you are using evopop: maybe open an issue here? https://github.com/solus-cold-storage/evopop-icon-theme/issues

> Second, it sometimes happens that it becomes a little point, instead of an icon. It does not disappear, it just become a little point.

See this bug: https://github.com/solus-project/budgie-desktop/issues/319

**Comment by feskyde** [comment]
> I think this depends on the icon-theme you are choosing. If you are using evopop: maybe open an issue here? https://github.com/solus-cold-storage/evopop-icon-theme/issues

@starquake EvoPop is currently unmantained, but as you said, the dark `nm-applet` color is caused by the default icon theme (@streambinder you can try to switch it to the dark variant).

**Comment by streambinder** [comment]
Thank you, @starquake and @feskyde.
Will check it out.

**Comment by streambinder** [comment]
Fixed on Shannon 1.1.
