### ISSUE TITLE
network icon is not visible in 10.2.3

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#346]
Hi,

  running ubuntu 16.04 and budgie 10.2.3

The network icon is not displayed in the panel

nm-applet is running - I can see that with ps -ef | grep nm-applet

It was autoexec'd  via /etc/xdg/autostart/budgie-desktop-nm-applet.desktop

Any thoughts why the icon wouldnt be displayed in the panel?

There doesnt appear to be a network applet in Raven - is this automagically added to the panel somehow?

**Comment by ikeydoherty** [comment]
This has been fixed in latest git (last 2 commits in fact) - we'll need a new point release for this. Closing anyway as its done

See: https://git.solus-project.com/packages/budgie-desktop/commit/?id=0fd822f8bc7cf385f9aacd408204d0c25e56d58c

And: https://git.solus-project.com/packages/budgie-desktop/tree/files?id=0fd822f8bc7cf385f9aacd408204d0c25e56d58c

If you want to patch the current ubuntu pkg before I get the point release out :)

**Comment by ikeydoherty** [comment]
Doing a 10.2.4 now actually, make it easier for you

**Comment by fossfreedom** [comment]
@ikeydoherty - you are a real gent. 

Cheers. I'll grab the latest sources and will rebuild and test.

**Comment by fossfreedom** [comment]
![](http://i.imgur.com/cAT5Cql.png)

@ikeydoherty - I've rebuilt to 10.2.4 but no joy.  Any thoughts on how I can debug further?

I first checked nm-applet was running - ps -ef | grep nm

then I killed the nm-applet process and launched nm-applet &

Next I forced the network-manager server to restart.

Logged out - logged in - not displayed

Logged out- - logged into Lubuntu/gnome  & unity - network icon was displayed

logged out logged into budgie - no network icon.

**Comment by ikeydoherty** [comment]
Huh? I can see the network manager icon in your screenshot. It's the one next to the bell/alert icon.

**Comment by ikeydoherty** [comment]
(Or is that something else entirely? o_O)

**Comment by fossfreedom** [comment]
That's the "Show desktop" applet

**Comment by ikeydoherty** [comment]
Is it possible that this is because Ubuntu patches network-manager-applet heavily?

**Comment by fossfreedom** [comment]
as far as I can gather all the patches come direct from Debian - so nothing specific to Ubuntu.

 - https://launchpad.net/ubuntu/+source/network-manager-applet/1.0.10-1ubuntu1

There appears only one specific patch for Ubuntu - looks like something GNOME specifically requested to not autostart  when using GNOME

**Comment by fossfreedom** [comment]
hmm - maybe I read that wrong - looks like more patches added to Ubuntu.

What is budgie looking for to determine to display the icon?

**Comment by ikeydoherty** [comment]
Well our nm-applet is vanilla, i.e it uses an X11 tray icon *only*. Pretty sure Ubuntu's is patched to use AppIndicator too ?

**Comment by fossfreedom** [comment]
yep - if budgie is only using X11 then that will be the issue.

ho-hum.  Need to find a way to get an appindicator support into budgie. Cheers for the info.

BTW - is there any documentation available on the applet API budgie uses - basically anything that shows how to write python based/ C based applets for budgie?

**Comment by ikeydoherty** [comment]
But it should be able to fall back to X11, this is what worries me. So in the latest tarball, you should see some new shiny gtk-doc, let me know if they're any use. If they're not, I'll try to get some tutorials together

**Comment by fossfreedom** [comment]
thanks - found the documentation.

I'm a python type person - so reading C/Vala doesn't make much sense.

I'm getting a bit lost working out how to display my own widget in the panel.

What I'm thinking of is trying is to add a Gtk.Box containing a Gtk.EventBox to the panel - the Box/EventBox will hold app-indicators (a bunch of icons which among them would be the nm-applet)
