### ISSUE TITLE
missing hints in budgie-panel

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#347]
Hi there,

  I raised the following issue on another projec -

 - https://github.com/gmc-holle/xfdashboard/issues/113#issuecomment-190609128

"What I see by looking at the code of bungie-panel (sic) so far is that it sets the window type to "dock" but does not set the flags "skip-tasklist" and/or "skip-pager". My understanding is that without the flags this application should also be shown in the task list (e.g. by pressing ALT+TAB). If it also listed there then xfdashboard should also do. But maybe I'm wrong and windows of type "dock" shouldn't be shown at all. I'm really not sure if it is a bug or not :("

Should budgie-panel have these two flags set as well as "dock"?

**Comment by ikeydoherty** [comment]
There you go, fixed above ^ :)

**Comment by ikeydoherty** [comment]
If that works for me, lemme know and ill close the issue

**Comment by fossfreedom** [comment]
cheers Ikey - I'll pull the commit for budgie and repackage @gmc-holle fix and give that a test asap.

brilliant work :)

**Comment by fossfreedom** [comment]
cheers - Ikey - this has worked very nicely with the patched xfdashboard.
