### ISSUE TITLE
Python based tutorial on how to add applets to the panel.

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#348]
from #346 

Add a tutorial or two to kick start budgie applet writing.

Documentation is in the tarball - would be better to have this on the solus website under a developers section.

For python developers like me - would be much better if the simple API is python focussed.

For example (thinking about AppIndicators) - a quick tutorial how to add a Gtk.Box to the panel would be useful - i.e. AppIndicators are icons that are added to a Gtk.Box containing an EventBox.

**Comment by ikeydoherty** [comment]
Documentation was added in the `budgie-desktop-examples` repo and the generated docs
