### ISSUE TITLE
Fedora Budgie install

### ISSUE THREAD

**Issue by SLmanDR** [solus-project/budgie-desktop#349]
Reference: https://solus-project.com/budgie/
http://software.opensuse.org/download.html?project=home%3Aikeydoherty%3Asolus-project&package=budgie-desktop
yum is deprecated for dnf:
https://fedoraproject.org/wiki/Dnf
(replace yum with dnf)

**Comment by caoli5288** [comment]
I have made copr repo for fedora 22 and 23, simple type
```
# dnf copr enable caoli5288/budgie-desktop
# dnf install budgie-desktop
```
and enjoy:-)

**Comment by ikeydoherty** [comment]
What is the issue? I've already provided Fedora 22 & Fedora 23 packages via opensuse, and the provided packages are based on my own packages.. I don't get it o_O

**Comment by caoli5288** [comment]
@ikeydoherty He means `yum` is replaced by `dnf`.

**Comment by ikeydoherty** [comment]
And dnf can't install RPMS anymore? :)

**Comment by caoli5288** [comment]
@ikeydoherty Any `yum` command will be redirect to `dnf`. Sample
```
# yum update 
Yum command has been deprecated, redirecting to '/usr/bin/dnf update'.
See 'man dnf' and 'man yum2dnf' for more information.
```

**Comment by ikeydoherty** [comment]
That's fine, but what's wrong with the OBS repo?

**Comment by caoli5288** [comment]
@ikeydoherty OBS repo page still use `yum` to sample install code. It's not your issue.

**Comment by ikeydoherty** [comment]
Sorry man I'm just so tired I'm not getting half of what is going on around me lol

@caoli5288 I'm gonna assume your Fedora package can be better maintained than mine, and probably cleaner too. Thanks for stepping up to the mark, I really appreciate it.

**Comment by caoli5288** [comment]
@ikeydoherty I build it from your spec file :-)

**Comment by ikeydoherty** [comment]
Ok I still don't understand this so I'll close it
