### ISSUE TITLE
Icon size not consistent

### ISSUE THREAD

**Issue by Anachron** [solus-project/budgie-desktop#352]
Icons like "Shutdown" and "Battery" are bigger than the rest. It does look inconsistent.

![2016-03-02-235043_1920x39_scrot](https://cloud.githubusercontent.com/assets/589800/13478520/b5fcedca-e0d1-11e5-9906-5db9c4627f06.png)

**Comment by X0rg** [comment]
+1
It would be better if we can set applet size in applet settings.
Change "Size" in Raven settings only change panel size.

**Comment by darkben** [comment]
+1 it seems icons are not on the same line. Perhaps battery icon could be horizontal ?

**Comment by ikeydoherty** [comment]
Status Applet uses smaller icons (Gtk.IconSize.MENU) because it's a series of indicators. They're not supposed to be the same size as _launcher_ icons. Note that in git, all status icons are now the same size

**Comment by ikeydoherty** [comment]
![screenshot from 2016-07-23 13-02-26](https://cloud.githubusercontent.com/assets/164489/17077789/bdddb672-50d5-11e6-9aec-9e5e1d5e4698.png)

Looks legit to me for the right hand side of the panel. The budgie menu launcher itself will get some love later in the day

**Comment by devxpy** [comment]
Can we change the budgie menu launcher icon using `gtk.css` ?  It looks larger than other icons, its quite disturbing..
