### ISSUE TITLE
network icon not available in 10.2.4

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#354]
Hi Ikey,

 re issue #346 

I've fixed this in ubuntu by changing the exec line in the budgie autostart .desktop file to this

    Exec=dbus-launch nm-applet

Would you be willing to add this to the source - or should I just manage this as a patch on ubuntu?

**Comment by ikeydoherty** [comment]
Why is your session missing dbus support?

**Comment by fossfreedom** [comment]
did a quick ps -ef | grep dbus - dbus daemon is running

![](http://i.imgur.com/RwqYWaH.png)

**Comment by ikeydoherty** [comment]
Alright let me find out if it affects Solus or not, if not I'll whack it in

**Comment by ikeydoherty** [comment]
This is currently in the `next` branch, and will be put in master on the next sync. Thanks for the heads up

**Comment by ikeydoherty** [comment]
I've had to revert that change, as it breaks keyring management and my credentials are no longer accessible when attempting to connect to VPN

**Comment by fossfreedom** [comment]
ok - no worries.  I'll hold the patch on ubuntu.  BTW - gnome credentials and VPN seem to work ok this side.
