### ISSUE TITLE
hiding certain "applications" from the menu

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#355]
Is there a way to hide certain .desktop files from the menu?

I cannot change  the .desktop file itself since that is prepackaged by Ubuntu.  Is there someway I can blacklist certain .desktop files so that it doesnt appear

**Comment by hackis** [comment]
As far as I know, there is alacarte in the repo, so you can download that and use it.

**Comment by fossfreedom** [comment]
thanks hackis -  my question was more related if myself as a packager can hide certain apps from appearing in the menu rather than as a user using alacarte.

However - think I'm going to close this since the enhancement is kind of a niche request.
