### ISSUE TITLE
panel applets appear in random order

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#356]
![Imgur](http://i.imgur.com/frmDMqm.png)

You can see here that the system tray ("EN") is in the middle of the panel applets when it should be left-most.

Similarly the notification icon is supposed to be towards the left hand side - its next to the clock.

Any thoughts what is the issue is?

**Comment by ikeydoherty** [comment]
Fixed in git commits:

c334b2e74e2b8b72e3b36d8558447e19d0ee9399
ed3b508b1e1d84fcf7b1559f9c8a84b9bda91295
