### ISSUE TITLE
Terminator(split terminal emulator) Issue

### ISSUE THREAD

**Issue by mehdip2007** [solus-project/budgie-desktop#357]
while using budgie DE and whn try to use the terminator application the shortcuts for pasting(ctrl+shift+v) also spliting(ctrl+shift+o) arent working,
the only shortcut which is working is open a new tab(ctrl+shift+T)

**Comment by ikeydoherty** [comment]
I'm not quite sure how that's a Budgie issue, those should be handled by the application at the toolkit level..

**Comment by mehdip2007** [comment]
Well this happens when iv use budgie anyway I can close the issue I'm back
to cinnamon

**Comment by ikeydoherty** [comment]
That's .. so helpful. Thanks.
