### ISSUE TITLE
Built-in theme is incompatible with GTK+ 3.20

### ISSUE THREAD

**Issue by City-busz** [solus-project/budgie-desktop#359]
The currently used CSS selectors are no longer available, because GTK+ 3.20 [uses CSS nodes](https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/). I ported the existing theme to GTK+ 3.20, but it's not backward-compatible. You can see my changes here: https://github.com/City-busz/budgie-desktop/commit/847261bdbe7e6f666885e6e433c7b9e8aa79aecc

**Comment by ikeydoherty** [comment]
So what we can do here is conditionally compile in the correct stylesheets, and namespace `theme/` to have `3.18` as default, and `3.20`, something like this sound acceptable?

**Comment by City-busz** [comment]
Yes, it sounds acceptable. The best would be to decide it on run-time, but I don't know if it's possible.

**Comment by ikeydoherty** [comment]
So we can actually cook a path at runtime

```
var version = "%s.%s".printf(Gtk.get_major_version(), Gtk.get_minor_version());
```

Instead of relying on compile time constants.An alternative would be to select paths in a switch for GTK3:

```
switch (Gtk.get_minor_version())) {
    case 20:
       return "somepath";
    case 18:
    default:
        return "defaultpath";
}
```

**Comment by ikeydoherty** [comment]
The following 3 commits have enabled namespacing of the `3.18` theme:
bc4aa04a14c0ddab3de95c3d2790557e11d6993d
1fb7aeffc0dbd505dbce5eaa4ac3a7789e53f59b
14b21dc182b831b9d8aae664897708e467dc3968

**Comment by ikeydoherty** [comment]
@City-busz everything is now in place to allow both the 3.18 and 3.20 themes to live in the same repo and benefit from dynamic runtime selection. As I don't have GNOME 3.20 myself, I'd really appreciate if you could make changes against the latest repo in the 3.20 dir and send a pull request so it lives in Budgie main :D
