### ISSUE TITLE
Support GLSL blur-behind operation

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/budgie-desktop#363]
Pretty much what it says on the tin. Support an (optional) blur-behind for Raven, and eventually, the panel itself.

Could be achieved by modifying the ClutterBlurEffect to use two pipelines, and apply the shader to one pipeline on all non-fully-transparent-regions in the mask from the second pipeline, using `glReadPixels` or equivalent.

**Comment by wolfv** [comment]
Hi Ikey, 

I tried to build something like this into Mutter a long time ago (like a year or so) and I was/am not very experienced with GL and Mutter etc.
However, if I remember correctly the Clutter Blur Effect was not very powerful back then... I think there must be a better option.

**Comment by ikeydoherty** [comment]
@wolfv well, any and all help appreciated on this one, it's something we'll need to build into budgie-wm, and likely apply to a certain window class (i.e. the Raven window) :)

**Comment by wolfv** [comment]
My code from back then is here: https://github.com/wolfv/mutter/blob/master/src/compositor/meta-blur-factory.c but really, consider it garbage. It never worked at all.
One of the problems I had that I wasn't really able to solve is how to get the blur-region (ie. the rendered contents of the windows behind)

**Comment by wolfv** [comment]
Hey Ikey, 

just wondering if you have an idea where in the code of Budgie one would put the blur-code? Ie. where does the compositor have access to the raw image of whats behind the window?

**Comment by ikeydoherty** [comment]
@wolfv it'd need to be implemented as an effect for budgie-wm

**Comment by Jantrushar** [comment]
Check out cinnamon for a working but buggy implementation:
https://github.com/linuxmint/Cinnamon/blob/master/src/st/st-background-effect.c

I have created the same effect for clutter with some changes that work better for my setup. 
I will upload it shortly. 

Performance is much better when rendered to a scaled down FBO. 
Also clutter does not notify overlapping windows that content has changed. So videos under the actor will not update if the foreground actor does not redraw.

**Comment by ikeydoherty** [comment]
Gonna close this as it's Mutter-specific and I don't want Mutter anymore
