### ISSUE TITLE
allow pinned apps for new users

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#365]
One of the most useful parts of budgie is the ability to pin apps to the panel.

But its hidden from the user - they don't know its available unless they are  shown.  Think from a GUI point of view we shouldnt hide stuff by default - functionality should be easily discoverable.

What I would like to try is to add a couple of pinned apps by default for new users - e.g. files + firefox

Is there some way to do this - may be by patching the code?  panel.ini looks like a likely candidate - can I add nautilus.desktop and firefox.desktop to panel.ini some-how?

**Comment by ikeydoherty** [comment]
Al comes down to overrides:
https://git.solus-project.com/packages/os-installer/tree/files/com.solus-project.icon-tasklist.gschema.override

**Comment by fossfreedom** [comment]
:+1: 

thats done the trick.  Cheers!
