### ISSUE TITLE
status tray applet has vanished

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#369]
Hi,

  have recompiled and installed on ubuntu 16.04 32bit and 64bit.

After a reboot, with both, the status-tray-applet has vanished - its not in the list of applets to be added, nor is it visible in the panel

any ideas why?

![](http://i.imgur.com/5dLI0ah.png)

**Comment by ikeydoherty** [comment]
Please fix your build dependencies - you need to add gnome-bluetooth-1.0 (see the list on the front README)

**Comment by fossfreedom** [comment]
ok - thanks - debian its libgnome-bluetooth-dev for the build and most probably libgnome-bluetooth-13 for the package dependencies.

**Comment by ikeydoherty** [comment]
Technically `shlibdeps` should take care of that, we explicitly use symbols from the shared objects
