### ISSUE TITLE
Super + L keyboard shortcut broken

### ISSUE THREAD

**Issue by adamjameschristensen** [solus-project/budgie-desktop#371]
Super + L keyboard shortcut stopped working after updating to budgie-desktop 10.2.5.r5. It was working on 10.2.4.

I see someone else reported this issue on the forums:
https://solus-project.com/forums/viewtopic.php?f=9&t=1297&p=7185

Running Arch Linux 4.5.0-1
budgie-desktop-git v10.2.5.r5.gd43a6df-1

Please let me know if I can provide any additional info!

**Comment by Ste74** [comment]
Compiled in manjaro unstable but not git version ( i compiled from source the 10.2.5)  and not issue here .

**Comment by ikeydoherty** [comment]
No, it didn't "stop" working, it was never provided by Budgie in the first place, therefore nothing broke.
(You can't break something that never existed.)

This is solely down to your choice of display manager. Logic tells me you went from GDM to either LightDM or SSDM. Please re-open if I am somehow incorrect.
