### ISSUE TITLE
invert window Colors

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#372]
Could we please have invert color for windows, so that monitoring becomes easy on eyes?

Gnome-shell has this extension
https://extensions.gnome.org/extension/1041/invert-window-color/

I'm currently using xcalib -a -i, but in future wayland may need it. Thanks

**Comment by ikeydoherty** [comment]
What possible use could this provide? Garish inversions hardly seem easy on the eyes ..

**Comment by ikeydoherty** [comment]
No update in several months, closing
