### ISSUE TITLE
Request: show active task name like in gnome-shell

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#373]
![screenshot from 2016-03-30 04-40-24](https://cloud.githubusercontent.com/assets/1161682/14126868/94105be6-f631-11e5-8492-1d8c761d691a.png)

In the screenshot, terminal is active, but the panel is without any task-lists or task-icons.

I'd like the mac osx, gnome-shell's topbar+ bottom dash-to-dock interface, 

I just want to see the current (active) task name on the top-bar (panel) instead of all running tasks or task-lists.

Could you please consider a plugin which could "show single active task name on the panel."

Thanks.

**Comment by ikeydoherty** [comment]
This isn't a bug. Add a tasklist or the icon tasklist to the panel.
