### ISSUE TITLE
autostart applications?

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#374]
How do we add some applications to autostart? like plank or some other ones like qbittorrent etc.

**Comment by feskyde** [comment]
GNOME Tweak Tool

**Comment by fastrizwaan** [comment]
thanks!
![screenshot from 2016-03-30 05-38-16](https://cloud.githubusercontent.com/assets/1161682/14127954/ad9296bc-f639-11e5-8644-852ea3adc9eb.png)
