### ISSUE TITLE
minimize / close to tray not working?

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#375]
I use qbittorrent, the application's icon is not shown in the system tray
![screenshot from 2016-03-30 05-52-35](https://cloud.githubusercontent.com/assets/1161682/14128129/a02f6d22-f63b-11e5-96a6-1a63ce224c97.png)

wifi icon is showing in the tray though. thanks.

**Comment by ikeydoherty** [comment]
This isn't a Budgie issue. We provide a tray applet, there are only two possible scenarios here:

1) You're not using the tray area (user error, unlikely)
2) You're using a distribution that patches QBitTorrent to use an appindicator. Budgie does not use AppIndicators, not a Budgie issue.

**Comment by fossfreedom** [comment]
@fastrizwaan - if you are using the budgie-remix PPA then this is indeed an appindicator issue.

For a workaround until someone codes appindicator support try this suggestion I made here:

 - https://plus.google.com/+davidfossfreedommohammed/posts/eW4pSWc1zu5

**Comment by ikeydoherty** [comment]
Closing as this isn't strictly a Budgie issue
