### ISSUE TITLE
OwnCloud system tray icon not visible: just a point

### ISSUE THREAD

**Issue by streambinder** [solus-project/budgie-desktop#376]
It randomly happens that it becomes a really little point, otherwise it's completely unvisible, although OwnCloud is currently running.
![schermata del 2016-03-30 20-47-32](https://cloud.githubusercontent.com/assets/7783188/14153661/ffad7514-f6b8-11e5-9ce0-fbd09301ad12.png)

**Comment by starquake** [comment]
Are you running 10.2.4? If not you might be having this problem: https://github.com/solus-project/budgie-desktop/issues/319

**Comment by streambinder** [comment]
Nope, I shouldn't be on 10.2.4, on 10.2.5, instead: the latest version from stable repository of Shannon release.

**Comment by JoshStrobl** [comment]
Happens with qBittorrent as well. I'm wondering if it is a Qt thing. @ikeydoherty thoughts?

**Comment by ikeydoherty** [comment]
Could be

**Comment by streambinder** [comment]
Still experiencing this issue.
Actually, upgraded yesterday everything: budgie-desktop aligned with version 10.2.6, release 86.

Thank you.

![schermata del 2016-07-13 15-45-59](https://cloud.githubusercontent.com/assets/7783188/16805585/24e1d6d6-4911-11e6-93ec-1a86d1ba8ac6.png)

**Comment by ikeydoherty** [comment]
OK no need to bump existing issues, we know they're still a problem, that's why they're still open :)

**Comment by streambinder** [comment]
I'm sorry, then.
Thank you, anyway! :)

**Comment by ikeydoherty** [comment]
No worries :) All open issues will eventually be closed, just the way it works ^^

**Comment by ikeydoherty** [comment]
Should be fixed in 10.2.8 - if not, well, it'll be done with the rewrite one way or another

**Comment by streambinder** [comment]
Yup, it seems to. :+1:

Thank you.

**Comment by ikeydoherty** [comment]
Awesome, thanks :)
