### ISSUE TITLE
1-Pixel Line where the wallpaper is visible when a program is maximized

### ISSUE THREAD

**Issue by creeperlwd** [solus-project/budgie-desktop#377]
![2016-03-31-125040_3840x1080_scrot](https://cloud.githubusercontent.com/assets/14105847/14173641/65227134-f73f-11e5-9d06-fd327f591fed.png)

as you can see in the screenshot, when i maximize a program with the maximize button, there is a 1-pixel wide line where you can see the wallpaper (which is white). this is on arch.

**Comment by ikeydoherty** [comment]
This was fixed in git
