### ISSUE TITLE
Feature Request: New Applet or Option

### ISSUE THREAD

**Issue by c0fe** [solus-project/budgie-desktop#378]
I like the way that Windows has that "My Computer" window in which you get the "C:\" or main hard drive as well as all connected hard drive, their current used and free space and all connected media devices (ex. phone). After speaking to JoshStrobl in the IRC channel he suggested I make a request for an applet. This would be a great option to have and would be a lot easier to get to whatever connected hard drive or media device desired without having to go through directories.

**Comment by ikeydoherty** [comment]
I'm unsure how Budgie is supposed to prove this? "My Computer" is the function of a file manager, namely Nautilus in our instance (which we use but do not write). Is this what you mean?

**Comment by c0fe** [comment]
Yes, that was the suggestion to provide an applet that would customize the file manager used in budgie DE.

**Comment by Ste74** [comment]
Just curios :smile: is not equal to pin nautilus on a panel ?

**Comment by c0fe** [comment]
I can't recall Nautilus having a similar design to My Computer.

**Comment by c0fe** [comment]
Ikey: would this be something you are willing to create?

**Comment by ikeydoherty** [comment]
OK closing this because it's out of scope for core Budgie
