### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by GrisuProjects** [solus-project/budgie-desktop#381]
I have this issue under Budgie 10.2.5. Title says it all.

Would give more system information but I don't know the commands.

**Comment by ikeydoherty** [comment]
Can't open *which* settings?

**Comment by GrisuProjects** [comment]
System settings

**Comment by GrisuProjects** [comment]
Print settings and settings in Raven do work.

**Comment by ikeydoherty** [comment]
Well then you probably don't have `gnome-control-center` installed

**Comment by GrisuProjects** [comment]
Sure I have (At least this is what the software center says)
![screenshot from 2016-04-02 17-40-42](https://cloud.githubusercontent.com/assets/15364860/14227285/39544a52-f8fa-11e5-8fe1-0c82d4fcafa5.png)

**Comment by ikeydoherty** [comment]
And what happens if you run `gnome-control-center` from the terminal?

**Comment by GrisuProjects** [comment]
It says this:
![screenshot from 2016-04-02 17-55-27](https://cloud.githubusercontent.com/assets/15364860/14227374/1eee983c-f8fc-11e5-97ff-8350af06d819.png)

**Comment by ikeydoherty** [comment]
Looks like you've been doing some custom stuff? :/ If this is Solus, then please make sure you have your system up to date:

```
sudo eopkg up
```

If that doesn't fix it, please reinstall gnutls nad libtasn1:

```
sudo eopkg it --reinstall libgnutls libtasn1
```

**Comment by GrisuProjects** [comment]
Actually I don't have custom stuff on my system.
Did the first one: Every thing is up to date
Did the second one: slightly different error this time
![screenshot from 2016-04-02 18-08-13](https://cloud.githubusercontent.com/assets/15364860/14227433/e44f942c-f8fd-11e5-8f2f-5edd7f5e841b.png)

**Comment by ikeydoherty** [comment]
Something is badly pooched on your system. What's the output of:

```eopkg list-repo```

**Comment by GrisuProjects** [comment]
![screenshot from 2016-04-02 18-15-05](https://cloud.githubusercontent.com/assets/15364860/14227472/ed06c24c-f8fe-11e5-8161-f7d14b4c9698.png)

**Comment by ikeydoherty** [comment]
```
sudo eopkg it --reinstall libp11-kit
```

**Comment by GrisuProjects** [comment]
It could be that the system is a bit "different" because originally I had an issue with grub where it said "unknown file system". So I thought I make a clean install. I took my Solus 1.1 USB drive and went through the setup. For the partition management I just used the one where the (non bootable) Solus was - without formatting it(I thought it will format it automatically, which already worked in the past). And after it was installed I rebooted and... There was the **old** Solus!(which I could not boot because of grub)

Maybe it has something to do with this issue, but apart from that everything works ok.

**Comment by GrisuProjects** [comment]
It works!

Thanks a lot, your great

**Comment by GrisuProjects** [comment]
I mean it works but is this output normal:
![screenshot from 2016-04-02 18-32-22](https://cloud.githubusercontent.com/assets/15364860/14227575/43352850-f901-11e5-8a64-22f8aa198a5c.png)

**Comment by ikeydoherty** [comment]
Yeah you see that for every app that has a headerbar in GNOME
