### ISSUE TITLE
Linking failure when building on Ubuntu Gnome Xenial

### ISSUE THREAD

**Issue by swarnendubiswas** [solus-project/budgie-desktop#382]
I get the following error when trying to build Budgie:

/usr/bin/ld: ../lib/.libs/libtoplevel.a(libtoplevel_la-animation.o): undefined reference to symbol 'cos@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:653: recipe for target 'budgie-panel' failed
make[4]: *** [budgie-panel] Error 1

I am using Ubuntu Gnome Xenial with gcc version 5.3.1 20160330 (Ubuntu 5.3.1-13ubuntu3). Not sure if this is reproducible on other distributions. 

It seems this error can be got rid of by appending -lm to LIBS in configure.ac.
`LIBS="$BACKLIBS -lm"`

**Comment by ikeydoherty** [comment]
That would cause global linkage to `libm` which is undesirable. I'll explicitly add it to `libtoplevel` - though this shouldn't be needed as only Raven uses any mathematical symbols directly.

**Comment by swarnendubiswas** [comment]
Nice, thanks.

**Comment by ikeydoherty** [comment]
V welcome :)
