### ISSUE TITLE
support local applets for development

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#385]
Hi,

  I've been looking at writing some plugins for budgie-desktop.

It is common during development of rhythmbox plugins which uses libpeas to support local folders for plugin development e.g.

~/.local/share/budgie-desktop/plugins/mytest/mytest.plugin

Can budgie-desktop be extended at some point to support local plugin development rather than having to  copy stuff into system folders like /usr/lib/budgie-desktop/plugins ?

**Comment by ikeydoherty** [comment]
Hm ok atm we support a path that I should actually change:

`~/.local/share/budgie-desktop/modules`

I'll need to change that to `~/.local/share/budgie-desktop/plugins`

I'll retain compatibility when I change it, don't worry..

**Comment by ikeydoherty** [comment]
Fixed that bit
