### ISSUE TITLE
Order of applets in the panel is not respected

### ISSUE THREAD

**Issue by swarnendubiswas** [solus-project/budgie-desktop#387]
I have applets in the panel in a certain order, but the panel display does not respect it often. This happens after a restart.

In the attached figure, you can see the Thunderbird indicator at the wrong place. This also happened for the show desktop applet, I manually reordered it before taking the screenshot.

![workspace 1_001](https://cloud.githubusercontent.com/assets/7343807/14269555/b7adfbb8-fab3-11e5-8194-849b21e809ed.png)

**Comment by feskyde** [comment]
What version of Budgie do you have installed? Lastest (10.2.5) fixed this
bug

**Comment by swarnendubiswas** [comment]
I built and installed from Git. But I had older versions installed from the budgie-remix ppa before. How can I verify the version (just to make sure that the old binaries are overwritten)?

**Comment by fossfreedom** [comment]
@swarnendubiswas - if you can see the new font control and other stuff in raven you will be running the latest stuff.

**Comment by swarnendubiswas** [comment]
Yes, it is the latest Budgie executables that are running.

**Comment by danboid** [comment]
I've just experienced this with the latest git budgie under Arch when positioning the workspace switcher.

**Comment by ikeydoherty** [comment]
@danboid the issue is still open because it still affects people - it's not forgotten :)

**Comment by ikeydoherty** [comment]
Same issue as #503 - which is believed to be fixed, so tracking there.
