### ISSUE TITLE
Icon Tasklist does not respect Skip Taskbar state

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#388]
from this issue: https://github.com/gmc-holle/xfdashboard/issues/121

The "skip taskbar" window state should be respected by the window list applet and shouldn't show the window in its list regardless if the window is visible or hidden/minimized.

gmc-holle states "the applet does not respect the second one [skip taskbar state] and that's an error in my opinion. If I remove the "Icon task list" applet from the panel and add "Task list" applet to the panel it behaves as expected."

**Comment by JoshStrobl** [comment]
Not sure what you mean by it isn't respected, we check if the window is_skip_tasklist() is `true` and if so, we immediately stop execution of the `window_opened` function.

Reference: https://github.com/solus-project/budgie-desktop/blob/master/panel/applets/icon-tasklist/IconTasklistApplet.vala#L216

**Comment by fossfreedom** [comment]
@JoshStrobl 

  "isn't respected" - not my words :(

I guess what @gmc-holle was saying is that the icon-tasklist applet shows an icon for xfdashboard when launched even though xfdashboard sets skip-tasklist on the window state.

@gmc-holle went on to say that the same behaviour wasn't shown with the standard tasklist applet - no xfdashboard window was added to the tasklist applet. 

So there appears to be a difference in behaviour between the two applets.

**Comment by ikeydoherty** [comment]
@gmc-holle has had since April to leave a comment here justifying that invalid comment, it's not come about so I'm closing the issue.
