### ISSUE TITLE
Windows focus issues when launching apps such as d-feet

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#389]
taken from https://github.com/gmc-holle/xfdashboard/issues/121 (I confirmed gmc-holle observation when launching d-feet from a terminal)

"I saw a lot of windows focus problems,e .g. when starting d-feet from a terminal window the application window of d-feet is displayed below the terminal window where I started d-feet from. The application window of d-feet is neither raised to front nor focused when opened. I don't know if this behaviour is wanted and I also don't know if this may prevent xfdashboard's window to re-appear."

**Comment by ikeydoherty** [comment]
Can't reproduce on Solus.. gonna have to go on guesswork
