### ISSUE TITLE
System tray icons are blurred and misplaced on HiDPI screen.

### ISSUE THREAD

**Issue by lanmasterlan** [solus-project/budgie-desktop#390]
On my 2560 x 1440 screen the icons in the system tray are blurred and misplaced. Also, there is redundant space on both sides.
![pic3](https://cloud.githubusercontent.com/assets/11398807/14326699/6cb310a8-fc2f-11e5-805f-ff4e081f45a5.png)

Arch linux with budgie-desktop 10.2.5 (current git master).

**Comment by ikeydoherty** [comment]
The applications showing the icons must also support HiDPI. Note that we don't *own* those windows. I might be able to put some hacks in to double the icon size on HiDPI

**Comment by ikeydoherty** [comment]
Closing because simply put this just isn't something that can be fixed. It can only happen through replacement of the X11 tray with appindicators
