### ISSUE TITLE
Is there a way to define which applets are default for new users

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#395]
Is there a way to setup for all new user accounts which applets are displayed and in which position (left/middle/right) - I'm hoping there is some-sort of gsettings override possible?

For example - could I drop the need to add the icon tasklist applet to the panel for a new user? ... obviously a user could just use raven later on to readd it needed.

**Comment by fossfreedom** [comment]
currently I'm patching data/panel.ini - if there is an easier/more recommended way please let me know.  

Thanks.

**Comment by ikeydoherty** [comment]
I'll add support for a vendor file

**Comment by ikeydoherty** [comment]
Implemented ^ :)

**Comment by fossfreedom** [comment]
Ikey - you are an officer and a gent :)

cheers!

**Comment by ikeydoherty** [comment]
@fossfreedom well it'll make maintenance much easier for downstreams if they don't have to carry heavy patches to budgie :)
