### ISSUE TITLE
Several Windows of One Application are not Group Together and Task Icons are not Interactive

### ISSUE THREAD

**Issue by Saroufim** [solus-project/budgie-desktop#4]
User case: Steam's Library, Friends List, and Chat are open. User gets a notification but can't immediately tell which Steam icon he/she should press on to read the appropriate notification unless he/she hovers the pointer over each task icon and reads its name.
Possible solution: Make the task icon related to the specific window flash when it requires attention.
Possible Solution number two: group the icons together and show the window that was last interacted with when the user clicks the task icon of that app. Clicking multiple times on that icon would maximize and bring to the foreground one window at a time.
Screenshot: https://dl.dropboxusercontent.com/u/44544435/snapshot34.png
##

**Comment by VanCoding** [comment]
+1 on Solution number 2. But clicking on the icon should only bring the window to the front when there's only one window. If there are multiple windows, it should display previews of the windows with titles above the icon. Clicking on a preview will then open bring the window to the front.

That's how Windows does it, and that's totally awesome & productive.

**Comment by playmer** [comment]
Hey there, I was also curious about the possibility of Solution Number 2. How hard of a feature would that be to add? Possibly with  Window Previews also like in Windows 7+?

**Comment by moghingold** [comment]
+1 on VanCoding's suggestion for how to handle multiple windows. Sounds like that's what Playmer would prefer to use, also. Is there any objection to Windows 7+-style grouping?

**Comment by iamonkara** [comment]
What about Switching using Alt+Tab between grouped applications? I don't see grouping working even Task bar for LibreOffice Calc and its not working during switching apps for Firefox, Chrome etc

**Comment by JoshStrobl** [comment]
> What about Switching using Alt+Tab between grouped applications? I don't see grouping working even Task bar for LibreOffice Calc and its not working during switching apps for Firefox, Chrome etc

This isn't relevant to the switcher and it's IconTasklist was a completely separate issue that was resolved. Let's refrain from necroing issues, thanks.

**Comment by JoshStrobl** [comment]
Closing since grouping is a thing and I'm kinda surprised this task is still open.
