### ISSUE TITLE
Budgie 10.2.5 on GNOME 3.20 stack (Arch Linux)

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#402]
As you can see in [this video](https://youtu.be/ZqMl7ZlJNMM), there are some bugs on Budgie 10.2.5 related to GNOME 3.20 stack:

### Budgie built-in theme:
- Switchs are broken.
- Applet manager titles has a lighter background under them.
- Budgie Menu items padding is smaller.

### Window manager:
- Windows and notifications appears on the upper-left corner.

**Comment by Ste74** [comment]
Yes today arrive also in unstable manjaro and confirm .. but guys , gnome guys are fine but at any revision all change .  :\

**Comment by ikeydoherty** [comment]
Theme fixes came after 10.2.5 for 3.20:
https://github.com/solus-project/budgie-desktop/compare/v10.2.5...master

For one I know the switches are fixed. As for the rest I'm currently unable to test. Regarding the notifications this is a regression in GTK which changes internal API to suit Firefox's broken ass notifications, which then broke ours.

I'll be able to fix notifications, but "windows" - I need more details on this. I suspect again its a GTK 3.20 issue

**Comment by horst3180** [comment]
The notification/window placement issue seems to be a regression introduced in GTK 3.20.2. See here https://bugzilla.gnome.org/show_bug.cgi?id=764403

I confirmed that it works fine with 3.20.1.

So, it should be fixed with the upcoming GTK 3.20.3.

**Comment by feskyde** [comment]
Switches and singletons [patched](https://bugs.archlinux.org/task/48856) on Arch, closing this :smile:.

*Now I need to sacrifice a goat for making the GNOME gods move the GTK+ code faster (or just wait).*

**Comment by ikeydoherty** [comment]
Minor bump in the road :D
