### ISSUE TITLE
Can not select gnome 3.20 themes

### ISSUE THREAD

**Issue by juvevood** [solus-project/budgie-desktop#405]
"Widget Theme" can't support gnome3.20 themes

**Comment by ikeydoherty** [comment]
What's different about GNOME 3.20 themes? i.e. what is different in /usr/share/themes/$theme/ now? I haven't looked.

**Comment by feskyde** [comment]
What distro are you using? I'm on Arch and can change themes :open_mouth:

**Comment by juvevood** [comment]
@feskyde @ikeydoherty .after upgrade gtk3.20,u can 't select gnome3.20 theme in budgie wiget
![deepinscreenshot20160414142223](https://cloud.githubusercontent.com/assets/1421513/14518751/a285d156-01df-11e6-89e5-f21a77f6745e.png)

**Comment by ikeydoherty** [comment]
You still haven't answered my question so I can't help you

**Comment by horst3180** [comment]
I think the issue here is that the theme in question uses versioned theme directories. Since GTK 3.16 themes don't need to have a `gtk-3.0` directory. For example, GTK 3.20 will search for `gtk.css` in the directories `gtk-3.20`, ...,`gtk-3.14`, `gtk-3.0`. See [here](https://git.gnome.org/browse/gtk+/tree/gtk/gtkcssprovider.c#n2007) for more details.

**Comment by ikeydoherty** [comment]
If I underp `load_themes_by_type` this is doable. Ideally we should check the current GTK version as well as the `gtk-3.0` directory me thinks

**Comment by HEXcube** [comment]
> I think the issue here is that the theme in question uses versioned theme directories. Since GTK 3.16 themes don't need to have a gtk-3.0 directory. For example, GTK 3.20 will search for gtk.css in the directories gtk-3.20, ...,gtk-3.14, gtk-3.0. See here for more details.

That explains why Adapta doesn't show up in Raven or GNOME Tweak Tool 3.18. That's why @tista500 bundles GNOME Tweak Tool 3.20 (where this is fixed) along with the theme for GTK3.18 in his PPA. :relaxed:

**Comment by ikeydoherty** [comment]
Adapta shows up in Solus fwiw

**Comment by ikeydoherty** [comment]
Scratch that I just noticed the package is super hacky in Solus

**Comment by HEXcube** [comment]
@ikeydoherty  Maybe Adapta is differentlly packaged for Solus and Ubuntu? :confused:

**Comment by ikeydoherty** [comment]
@HEXcube yeah ours is nasty. I'll fix it in Raven don't worry

**Comment by HEXcube** [comment]
@ikeydoherty Maybe look at Tweak Tool 3.18 and 3.20 to see the how they solved it? :confused: I had a look a Solus Arc package: https://git.solus-project.com/packages/adapta-gtk-theme/tree/package.yml . It copies gtk-3.18 folder to gtk-3.0 and dodges this issue. :grin:

**Comment by ikeydoherty** [comment]
@HEXcube i already said how I'd fix it

 > If I underp load_themes_by_type this is doable. Ideally we should check the current GTK version as well as the gtk-3.0 directory me thinks

**Comment by HEXcube** [comment]
@ikeydoherty  My bad! :sweat_smile: I'm not very good at understanding techincalese u, know. :grin:

**Comment by juvevood** [comment]
My bad ! and thank u  guys！:grin:

**Comment by HEXcube** [comment]
@JoshStrobl U might wanna change [[Solus' Adapta package](https://git.solus-project.com/packages/adapta-gtk-theme/tree/package.yml) coz @tista500 added `gtk-3.0` folder in [this upstream commit](https://github.com/tista500/Adapta/commit/bdea6cb53f6a43e4f50e6581058a3b1bb7ffdd84) for backward compatibility. :grin:

**Comment by JoshStrobl** [comment]
@HEXcube Yea I'll update it.

**Comment by HEXcube** [comment]
Wow! That was real quick! :smiley: 

> Not 100% pertaining to the issue and should've been poked in IRC or on BTS about it

Next time I'll contact u via IRC or G+ and keep issues clean of unrelated stuff. :sweat_smile:  But hey, it wasn't completely irrelevant to the topic. :grin:

**Comment by ikeydoherty** [comment]
^ Fixed

**Comment by HEXcube** [comment]
Thanx for fixing this issue @ikeydoherty ! :relaxed:  Now GTK themes with multiple versioned folders like `gtk-3.20`, `gtk-3.22`, etc (but no conventional `gtk-3.0`) are selectable from _Raven_ :smiley:
