### ISSUE TITLE
Raven switches on panel configuration are wider than all other

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#413]
Look to the "Stylize region" and "Shadow" switches, all other switches in Raven are fine, except for these two (probably a bug on widget location).

![captura de pantalla de 2016-04-16 13-33-54](https://cloud.githubusercontent.com/assets/12128317/14582354/8ecc37e0-03d8-11e6-840b-a04b456165f1.png)

![captura de pantalla de 2016-04-16 13-34-58](https://cloud.githubusercontent.com/assets/12128317/14582355/8ecdee82-03d8-11e6-9e24-afe16844ac16.png)

![captura de pantalla de 2016-04-16 13-36-17](https://cloud.githubusercontent.com/assets/12128317/14582356/8ed04b28-03d8-11e6-85d2-0c45cff2df11.png)

**Comment by ikeydoherty** [comment]
"All other switches"  - There are only two switches in the screenshots you've provided, and personally I don't think they look right when stretched out like big Playskool buttons

**Comment by feskyde** [comment]
"All other switches **in Raven**" - There are five switches left, those looks right, that's what I meant.

![captura de pantalla de 2016-04-16 19-50-03](https://cloud.githubusercontent.com/assets/12128317/14584095/da1e99b6-040c-11e6-9841-939ea6fc8117.png)

:point_up_2: And the two in Raven's volume applet

**Comment by ikeydoherty** [comment]
Oh. Wow I totally misread this, sorry. So this *only* happens when not using built-in theme, yes?

**Comment by feskyde** [comment]
Yes

**Comment by ikeydoherty** [comment]
Fixed in acbdcc063f1055200d1bf639f8904ad99bcfe21d
