### ISSUE TITLE
print key is not hooked up to gnome-screenshot

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#415]
Forgive me if this is the wrong place to put this.  Possibly this is a budgie-wm issue?

The print key and other combinations to take screenshots of the desktop/windows as per org.gnome.settings-daemon.plugins.media-keys don't appear to be hooked up to gnome-screenshot.

**Comment by ikeydoherty** [comment]
Duplicate of #261

**Comment by fossfreedom** [comment]
ok - ta.

**Comment by ikeydoherty** [comment]
(I want to fix it too btw. I tried doing it in Vala but hit the limitations of the language, sadly. We need a C->Vala bridge.. I even have a branch where I started all this..)

**Comment by fossfreedom** [comment]
this one? https://github.com/solus-project/budgie-desktop/tree/c-api

I'll add this to our bug tracker.  Once budgie-remix is launched and lots more people get to see and use the desktop, I'm going to throw out regular requests to help out with this sort of thing.

**Comment by ikeydoherty** [comment]
Nope this one https://github.com/solus-project/budgie-desktop/tree/screenshot-iface :)

**Comment by arivasvera** [comment]
@ikeydoherty 
> Nope this one https://github.com/solus-project/budgie-desktop/tree/screenshot-iface :)
Link to 404
