### ISSUE TITLE
shrinking the panel size below 32px makes the nm-applet icon lose its colour

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#417]
launchpad bug https://bugs.launchpad.net/budgie-remix/+bug/1572770

![](https://bugs.launchpad.net/budgie-remix/+bug/1572770/+attachment/4641053/+files/black%20wifi.png)

Maybe stop the panel  from being able to shrink below 32px?  Or maybe more complicated find the largest panel iconsize and stop the panel from shrinking below that size?

**Comment by ikeydoherty** [comment]
Seems *more* like a theme issue - try with Faba Mono, you'll see what I mean.

**Comment by ikeydoherty** [comment]
Any thoughts?

**Comment by fossfreedom** [comment]
Seems to be the network applet itself rather than the theme.

Yeah - asking to stop the panel from shrinking smaller than the max icon size is protecting the user from their own folly.  Lets close this.

**Comment by ikeydoherty** [comment]
@fossfreedom I'll keep an eye out for this. In reality the problem is, as I think you know, we need to move over to AppIndicator, sooner, rather than later.. :/
