### ISSUE TITLE
adding a separator on the left of the system tray adds space to the right hand side

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#418]
Seems strange but true.

Launchpad bug https://bugs.launchpad.net/budgie-remix/+bug/1572773

![untitled](https://cloud.githubusercontent.com/assets/996240/14715552/279f9884-07e1-11e6-97cf-f2ef5e5ae180.png)

Before adding the separator - all looks ok

![](https://bugs.launchpad.net/budgie-remix/+bug/1572773/+attachment/4641056/+files/1.png)

After adding the separator - notice the space to the left of the system tray

![](https://bugs.launchpad.net/budgie-remix/+bug/1572773/+attachment/4641057/+files/2.png)

**Comment by ikeydoherty** [comment]
In your Raven screenshot the separator is at the start of the system tray.. o_O

**Comment by fossfreedom** [comment]
ever get the feeling left and right is just too complicated...

ok - add the separator to the left of the system tray adds space to the right side!

**Comment by ikeydoherty** [comment]
Same issue as #503, off-by-one..
