### ISSUE TITLE
Taskbar window reorder

### ISSUE THREAD

**Issue by IlyaBizyaev** [solus-project/budgie-desktop#421]
_Enhancement proposal_

It would be nice to be able to reorder icons of opened applications on the taskbar. That's especially handy when reordering pinned shortcuts.

**Example (Unity):**
![Unity](https://cloud.githubusercontent.com/assets/11175213/14760557/cee8cb50-094f-11e6-802e-58b2c5c6f5bc.gif)

**Comment by fossfreedom** [comment]
This is already on the TODO list https://github.com/solus-project/budgie-desktop/blob/master/TODO.md

**Comment by IlyaBizyaev** [comment]
Thank you for reply! Waiting for implementation :blush:
**Closed.**
