### ISSUE TITLE
Drag & Drop for menu items

### ISSUE THREAD

**Issue by IlyaBizyaev** [solus-project/budgie-desktop#422]
_Enhancement proposal_

At the moment, there seems to be no way in Budgie to create a desktop shortcut, except for copying it from `/usr/share/applications` or manually creating. It would be a nice time-saving feature if a user could simply drag icons from Budgie menu to the desktop or a panel.

**Example (Windows 10):**
![g4qhku](https://cloud.githubusercontent.com/assets/11175213/14760691/3b5e20a2-0953-11e6-8ea9-0c5b7951313a.gif)

**Comment by fossfreedom** [comment]
drag and drop to the icontask list applet is covered by the TODO list - https://github.com/solus-project/budgie-desktop/blob/master/TODO.md

**Comment by IlyaBizyaev** [comment]
Thanks, will be waiting for implementation!
