### ISSUE TITLE
Allow menu selection by "hovering" with the cursor.

### ISSUE THREAD

**Issue by YamashitaRen** [solus-project/budgie-desktop#426]
I think that it would be nice...
Seems like this opinion is shared by others :

"Unlike those others, in Budgie's menu you have to click on a category to select it while on all these others you select a category by hovering over it. I much prefer the latter approach."
https://www.reddit.com/r/linux/comments/3spflc/solus_os_budgie_de_10rc_test_drive_alternative_to/cwzsmcc

"The menu itself is fairly easy to use, although it requires a click to be able to view the applications within a category"
http://dasublogbyprashanth.blogspot.fr/2016/01/review-solus-10-shannon.html

**Comment by ikeydoherty** [comment]
This has now been implemented as a (non-default) option :)
