### ISSUE TITLE
[Feature Request]: Autolocking (with LightDM/Light Locker)

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#427]
Arch's patched Budgie Desktop uses GNOME Screensaver through an autostart file in the @City-busz's [`budgie-helper`](https://github.com/City-busz/budgie-helper) component.

Thanks to this, GNOME Screensaver makes Budgie gain the ability off turning screen of and locking automatically (thing that is not possible in vainilla Budgie + LightDM, as in Solus).

So, the idea is to add those two things, if possible :smile:.

**Comment by ikeydoherty** [comment]
GNOME Screensaver isn't maintained from what I know.

**Comment by feskyde** [comment]
Sorry, I not explained it well:

> So, the idea is to add those two things, if possible :smile:.

I'm refering to the automatic locking/turning off screen ability with LightDM in "vainilla" Budgie.

**Comment by feskyde** [comment]
Going to close this but Raven still locks using LightDM locker in Solus 1.2

**Comment by feskyde** [comment]
This is fixed, let's concentrate on #477
