### ISSUE TITLE
Missing layout keyboard indicator

### ISSUE THREAD

**Issue by behroozramezani** [solus-project/budgie-desktop#430]
I'm using Budgie-desktop on Arch linux. I have two layout keyboard.Is there any way add layout indicator to panel in budgie?

**Comment by niyasc** [comment]
@JoshStrobl 
I have also same question. I am using Budgie Desktop in Fedora. I can switch keyboard layout using default GNOME shortcut, ie, `Super + Space`.

Is there any official keyboard layout indicator for Budgie Panel?

**Comment by ikeydoherty** [comment]
Why is Josh being pinged? I'm the maintainer. And no, there is currently no indicator.

**Comment by fu-sen** [comment]
GNOME supports keyboard switching by IBus by default.

https://help.gnome.org/misc/release-notes/3.6/i18n-ibus.html.en

Order to ensure that future many users use with Budgie and Solus,
If not corresponding to this user be packaged input method future may not be used.
I think support is ideal, such as Cinnamon.

**Comment by ikeydoherty** [comment]
This is a target for 1.2.1, please stop refreshing these threads, we've said its being done :)

**Comment by ikeydoherty** [comment]
This has been implemented in in git master and will be released soon

![screenshot from 2016-07-19 05-26-04](https://cloud.githubusercontent.com/assets/164489/16938621/aab0986a-4d71-11e6-9070-feb1ab2fbfc4.png)
