### ISSUE TITLE
Wifi is turn off at boot

### ISSUE THREAD

**Issue by behroozramezani** [solus-project/budgie-desktop#432]
I using Archlinux+budgie. When i login to budgie wifi is off. I turn on it manualy. when i shutdown or restart Arch linux and login again to budgie wifi is off. why?

**Comment by feskyde** [comment]
It's probably a NetworkManager issue than a Budgie's one

**Comment by behroozramezani** [comment]
Does anyone have this issue on budgie?

**Comment by starquake** [comment]
No I do not have this problem. Did you configure NetworkManager correctly?

https://wiki.archlinux.org/index.php/NetworkManager#Configuration

**Comment by ikeydoherty** [comment]
OK so this isn't , and cannot, be a Budgie issue. This issue pertains to your distribution that ships and packages NetworkManager
