### ISSUE TITLE
Chrome Notifications Not Showing Up / Feature Request

### ISSUE THREAD

**Issue by The5heepDev** [solus-project/budgie-desktop#437]
Hey. Right now, i cannot see the chrome notification icon in the system tray. Is there a way of getting it to show up or a way to get chrome's notifications to show up in Raven? This would be a cool feature to have chrome notification integrate into raven. Thanks!

**Comment by ikeydoherty** [comment]
Chrome is a proprietary extension of Chromium - by nature there is absolutely nothing we can do. Also see the answer in the G+ community explaining why Chromium uses HTML5 notifications and doesn't use any native APIs.

Long story short Chromium is the one not playing ball and needs modifying

**Comment by The5heepDev** [comment]
@ikeydoherty For some reason the chrome notifications aren't showing up at all... Is there a way to fix this?

**Comment by ikeydoherty** [comment]
I get Chrome notifications here :/ HTML5 ones

**Comment by The5heepDev** [comment]
@ikeydoherty The Chrome notifications show up when they first appear, but the icon in the system tray that lets you see all notifications never shows up :/
