### ISSUE TITLE
Feature: skin/themes like firefox for budgie

### ISSUE THREAD

**Issue by fastrizwaan** [solus-project/budgie-desktop#438]
Hi,
Please visit this with firefox, hover on any theme, see the colorful beauty!
https://addons.mozilla.org/en-US/firefox/themes/

Can we support skins/image overlay for budgie desktop that makes it more lively and colorful with image as skins like with firefox thems, the various shell themes are just plain and bland.
![screenshot from 2016-05-06 22-30-44](https://cloud.githubusercontent.com/assets/1161682/15088283/2c129d3c-140f-11e6-8a8b-6e5a304dcaf4.png)
![libreoffice_themed_top](https://cloud.githubusercontent.com/assets/1161682/15088285/33d70d8c-140f-11e6-8640-d46f3eabbadc.png)

**Comment by ikeydoherty** [comment]
No idea what Shell themes have got to do with this. Anyway, Budgie is fully themable with GTK CSS styles, I'm really not about to go and invent a theme engine for nobody to make themes.
