### ISSUE TITLE
Remove default theme in budgie settings

### ISSUE THREAD

**Issue by Ste74** [solus-project/budgie-desktop#440]
Hi there :smile: i have disable the switch 'default theme' in raven settings but not find the key in dconf-editor . Can you point me where is ? 
![schermata del 2016-05-08 19-36-15](https://cloud.githubusercontent.com/assets/11218234/15099377/33f9a54a-1554-11e6-8313-b73b46855aab.png)

thank you guys :wink:

**Comment by ikeydoherty** [comment]
```
com.solus-project.budgie-panel builtin-theme
```

**Comment by Ste74** [comment]
Thank you Ikey .. found :stuck_out_tongue_winking_eye:
