### ISSUE TITLE
How do you enable plugins at compile time?

### ISSUE THREAD

**Issue by sixtyfive** [solus-project/budgie-desktop#443]
Right now the end of my `./configure` runs looks like this:

```
        Plugins:
        =======

        natray:                 yes

        budgie-menu:            always
        clock:                  always
        icon-tasklist           no
        notifications           always
        separator:              always
        spacer:                 always
        show-desktop:           no
        tasklist:               no
        status:                 no
        tray:                   yes
        workspaces:             no
```

Is there any way to enable at least the `workspaces` plugin? I've tried `./configure --help`, but unfortunately it doesn't contain any info about plugins afaics...

**Comment by fossfreedom** [comment]
You didn't mention which distribution you are using.  It is likely you are missing libpeas-gtk.  The readme has all the dependencies you need to compile

**Comment by ikeydoherty** [comment]
You're missing the wnck development files

**Comment by sixtyfive** [comment]
I'm trying to get Budgie working under what was once an LMDE2 and is now best described as Frankendebian. You were right that not all dependencies were yet installed. I think I've tracked them all down now (except for `libpolkit-gobject-1-0`, which, even in Sid, only seems to be available in 0.105). All plugins except for `status` are now enabled. Might that be because of the older `libpolkit-gobject` version?

**Comment by ikeydoherty** [comment]
Status is going to be gnome-bluetooth headers probably:

```
     upower-glib >= upower_required_version,
     gnome-bluetooth-1.0 >= bt_required_version
```

**Comment by ikeydoherty** [comment]
btw our polkit requirement is 0.105:
```
m4_define([polkit_required_version], [0.105])
```

**Comment by sixtyfive** [comment]
Hmm, both my `upower-glib` and `gnome-bluetooth` are newer than required.

According to HEAD's `README.md` these are your polkit requirements:

```
    - polkit-agent-1 >= 0.110
    - polkit-gobject-1 >= 0.110
```

I'm quite happy though, as Budgie just booted up without crashing for the first time :smile:. For any googlers coming along, take heed when trying this. It requires extensive abuse when doing it on a Jessie-based system.

**Comment by sixtyfive** [comment]
Hmm, stuff like wanting to change my desktop background (I click the menu item, nothing happens), would that be due to running on an unsupported platform or is it just broken atm?

**Comment by ikeydoherty** [comment]
@sixtyfive do you have gnome-control-center installed?

**Comment by sixtyfive** [comment]
Indeed, I don't. Because of the black magic required to get Budgie to compile, a lot of Gnome things can't be installed now. Is it difficult to change my copy of the Budgie sources to launch something different, e.g. `xfce4-settings-manager`?

**Comment by ikeydoherty** [comment]
Sure, if you want. Just note that xfce4-settings-manager is for XFCE and won't actually *do* anything for Budgie, so it'll be a pointless exercise.

**Comment by sixtyfive** [comment]
Well, at least _some_thing would happen then, and there's some desktop-agnostic things included with it as well. Sort of sad that Budgie depends on Gnome programs instead of just the libraries.

Anyways, regarding g-c-c ... since `raven/powerstrip.vala` already seems to print a debug message, how about making it a user-visible dialog or notification instead?

**Comment by ikeydoherty** [comment]
What do you mean, "sad"? Budgie is designed with GNOME integration in mind.

**Comment by sixtyfive** [comment]
First off, I'm sorry if you felt offended in any way by that sentence. I think Budgie ist great and I'm looking forward to it growing and receiving more attention from older distributions as well. What I meant was simply that [to tinkerers like me] a DE is usually more useful the fewer dependencies it works well with.
