### ISSUE TITLE
Mutter and Chrom(e/ium) are not best friends

### ISSUE THREAD

**Issue by sixtyfive** [solus-project/budgie-desktop#444]
Somehow Chrom(e/ium) uses it's own window title bar slash tab bar. For some reason, Mutter draws the regular window title bar above that.

**Comment by kbrgl** [comment]
There's a setting in Chrome / Chromium under Settings > Appearance > Use system title bar and borders. Enabling it should (hopefully) fix your problem.

**Comment by sixtyfive** [comment]
Ouch, that was far too simple. Sorry to have bothered you with it and thanks for the quick help!
