### ISSUE TITLE
Files not reflected when added. 

### ISSUE THREAD

**Issue by Juvenciodas** [solus-project/budgie-desktop#445]
If I am in any directory, then add some data, the folder is not reflected. I will need to go back once then back in to the folder to see the data that was added. It doesn't seem to refresh live. 

Running budgie desktop on manjaro stable.

**Comment by ikeydoherty** [comment]
Folders? What's not reflected? We don't show folders anywhere. Confused, please elaborate.

**Comment by Juvenciodas** [comment]
Hi ikeydoherty.
Thanks for your time. The folder application that allows you to browse through your file system.

The problem is,  I am  only having the issue on my test drive. I have now setup manjaro budgie on my main drive and I have no issues on that drive.
So on my side I can't reproduce the issue.

But to clarify if I copied or renamed a document, mp3,  video or picture, in the file explore app, it would not refresh unless I reopen that document location.

**Comment by ikeydoherty** [comment]
@Juvenciodas Budgie doesn't have a file manager - so I'm not sure what you mean?

**Comment by ikeydoherty** [comment]
Reply wouldn't have hurt.
