### ISSUE TITLE
Debian Review issue 2: Clarification of copyright between LGPL and GPL-2+

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#447]
Taken from debian [RFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824967)

> I think the ftp-masters will want debian/copyright to be more specific
about which files are LGPL and which are GPL.

**Comment by ikeydoherty** [comment]
ftp-masters should look closer at the files then, there is a clear distinction between what is LGPL and what is GPL. Every one of the source files has a license header.

A simple grep can tell them all they need:

```
 ✘ ikey@solus-bdw  ~/Projects/budgie-desktop   master  grep -R "Lesser General" | cut -d : -f 1 | uniq | grep -v LICENSE
imports/natray/na-tray-manager.c
imports/natray/na-tray-child.h
imports/natray/na-tray-child.c
imports/natray/na-tray.h
imports/natray/na-tray-manager.h
config/budgie-config.h
config/budgie-config.c
config/budgie-config.vapi
theme/theme.c
theme/theme.vapi
theme/theme.h
lib/toplevel.vapi
lib/toplevel.vala
lib/animation.vala
lib/manager.vala
lib/shadow.vala
panel/popovers.vala
panel/uuid.vala
plugin/plugin.c
plugin/applet-info.h
plugin/popover-manager.h
plugin/popover-manager.c
plugin/applet.h
plugin/plugin.h
plugin/applet.c
plugin/applet-info.c
libsession/libsession.vapi
libsession/libsession.vala
```

**Comment by ikeydoherty** [comment]
What else do they need btw? Some kind of maintained license list? Seems a pain in the ass.

**Comment by fossfreedom** [comment]
I'll ask when I push the next release this week.  

The holdup for the release is the copyright listing  requirement; it's taking a long time since there are lots and lots of copyright holders listed.

**Comment by ikeydoherty** [comment]
Lots and lots of copyright holders? really.. ? o_O GitHub has graphs to show who contributes what

**Comment by fossfreedom** [comment]
k - the debian/copyright file now contains the correct files for LGPL.  cheers

**Comment by ikeydoherty** [comment]
Redirecting to #465
