### ISSUE TITLE
Debian Review issue 3: upstream tarball contains generated files

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#448]
Taken from debian [RFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824967)

>I note that the upstream tarball contains generated files (*.c *.vapi
*.css *.png *.html). I personally think these need to be removed from
the upstream tarball and VCS if present in either of those and always
created at build time. If upstream doesn't want to do that an
acceptable workaround would be to remove these files in `debian/rules
clean` and in `debian/rules build` before autoreconf/configure are
run. Alternatively you could use the gitub-generated tarballs which
only contain what is in git. Looks like you will need to package some
more build-deps here though, like gulp-sass.

What is your viewpoint  of the points raised:
1. removing generated files - what files is the reviewer referring to?  I'm a little nervous of attempting to do a blanket remove of *.c *.vapi *.css *.png *.html without understanding the implications here
2. VCS if present
3. Makefile only generate at build time
4. Didn't realise that there is a build-dependency of gulp-sass - is there?
5. Apparently the recommendation here is to use "github generated tarballs" instead of release tarballs ...

**Comment by ikeydoherty** [comment]
Do Debian not understand how `make distcheck` works???

**Comment by ikeydoherty** [comment]
Redirecting to #465
