### ISSUE TITLE
Use 24x24 pixels as the icon size in the Budgie Menu

### ISSUE THREAD

**Issue by snwh** [solus-project/budgie-desktop#450]
I noticed that the Budgie menu uses 22x22 icons, which is a deprecated size from the GNOME2 era, the use of the more standard 24x24 would be better suited for such a modern desktop. 

(This would be much appreciated by icon theme designers who don't ship 22x22 versions of their icons.)

**Comment by ikeydoherty** [comment]
Forgot to close this on the live stream, thanks :D 
f89d2f2787c850ed6ee3e6831a0f9821045a75eb
