### ISSUE TITLE
is it possible to switch off budgie's notification popup and use another notification system

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#451]
There is a bit of a clash with budgie's notification popups and ubuntu's

On ubuntu various apps have dependencies on packages like "libnotify-bin" and "notify-osd"

If these apps are  installed and those extra packages are also installed, any notifications popups appear twice.

Is there a way to hide the actual budgie popup from appearing but leave the notification icon turning red for a new system message?

**Comment by ikeydoherty** [comment]
Why are you using notify-osd ? That's a different notification daemon. I think your effort to break Budgie up into pieces is getting out of control now.

libnotify-bin is just the binary programs of libnotify, i.e. notify-send, which is a CLI tool to send notifications to the `org.freedesktop.Notifications` dbus name, which Budgie owns in this context.

I'm really worried now where this rabbit hole is heading. I can't have deficiencies in Ubuntu's design affecting Budgie

**Comment by fossfreedom** [comment]
lightbulb moment - I suspect the OP has installed another notification system as well.  That is causing this issue.

Sorry about that.

**Comment by ikeydoherty** [comment]
No I'm not saying to close the issue :P I still think it warrants discussion - it just needs fully explaining to me ^^
