### ISSUE TITLE
Clicking on the notifications icon should always open notification center

### ISSUE THREAD

**Issue by snwh** [solus-project/budgie-desktop#453]
Right now clicking the bell icon opens Raven in applets view, the expected behaviour would be that it opens raven in notifications view.

**Comment by ikeydoherty** [comment]
It should open to Notifications view if you have any notifications

**Comment by snwh** [comment]
Yeah, but even if no notifications are present it should still open the notifications. ;)

**Comment by ikeydoherty** [comment]
Blame @JoshStrobl :P

**Comment by JoshStrobl** [comment]
> Yeah, but even if no notifications are present it should still open the notifications. ;)

I completely disagree. It should go to the applet view, because that is where your interactions will likely be if you don't have notifications.

**Comment by snwh** [comment]
@JoshStrobl that makes no sense. The expectation for clicking on the notifications icon is that the notifications centre will open. Giving it 2 different behaviours is sure to confuse users.

When there are no notifications the notifications centre will have the empty state UI.

**Comment by ikeydoherty** [comment]
#457 makes this a lot more easy to conceptualize, Josh.

**Comment by ikeydoherty** [comment]
Notification icon now only opens Notifications, Raven Trigger always opens Applets View
