### ISSUE TITLE
Applet Icons

### ISSUE THREAD

**Issue by snwh** [solus-project/budgie-desktop#457]
![screenshot from 2016-05-23 20-38-39](https://cloud.githubusercontent.com/assets/1217306/15489193/9dede0b4-212b-11e6-8c24-892c39b39d23.png)

In the "add applet" menu, the list of applets and their icons needs updating, some can/should use standard icons:

- Budgie Menu `start-here-symbolic`
- Show Desktop Button `user-desktop-symbolic`
- _Bluetooth Indicator `bluetooth-symbolic`_
- _Volume Indicator `audio-volume-high-symbolic`_
- _Power/Battery Indicator `battery-full-symbolic`_
- _Session `system-shutdown-symbolic`_
- Status Indicator `avatar-default-symbolic`

_*those in italics are upcoming indicators/applets_

Others need custom icons:

- [x] Icon task list `icon-task-list-symbolic`
- [x] Task list `task-list-symbolic`
- [x] Separator `separator-symbolic`
- [x] Spacer `spacer-symbolic`
- [x] Notifications `notifications-applet-symbolic`
- [x] Clock `clock-applet-symbolic`
- [x] System Tray `system-tray-symbolic`
- [x] Workspace Switcher `workspace-switcher-symbolic`
- [x] Lock Keys Indicator `num-lock-symbolic` & `caps-lock-symbolic`

**Comment by snwh** [comment]
I'll create the missing icons and check them off when completed

**Comment by snwh** [comment]
Icon source: https://github.com/snwh/budgie-icons/tree/master/hicolor/scalable

**Comment by ikeydoherty** [comment]
Closing as source disappeared

**Comment by snwh** [comment]
They just moved (edited previous comment).

**Comment by ikeydoherty** [comment]
Re-opening because I'm blind. XD

**Comment by snwh** [comment]
Nah, it's my bad.

**Comment by ikeydoherty** [comment]
In it's current form this is now merged, thank you! We'll update the remainders post rewrite =)

Cheers a lot for those icons, really make a difference
