### ISSUE TITLE
Can't open player from MPRIS applet

### ISSUE THREAD

**Issue by snwh** [solus-project/budgie-desktop#459]
There's not a way to launch or bring-to-focus the whichever player is in the MPRIS applet.

Suggested solution: click the album art.

**Comment by GrisuProjects** [comment]
Why double-click? Single-click would be more convenient to me. Also it would feel strange when it would have a double-click action but no single-click one.

**Comment by snwh** [comment]
That's fair.

**Comment by ikeydoherty** [comment]
I'd advise reading the commit message on this one. It's implemented, but at this point in time, virtually useless.
