### ISSUE TITLE
`wmctrl -l` output missing results

### ISSUE THREAD

**Issue by saghm** [solus-project/budgie-desktop#462]
I'd like to use [wmctrl](https://sites.google.com/site/tstyblo/wmctrl) for some scripts I've written, but when attempting to use it to list the currently open windows (after installing from source), it only seems to be missing much of the information. For example, if I only have my browser open, then the only result shown is budgie-panel. If I open a new application (e.g. Emacs) and then run `wmctrl -l` again, it starts showing Firefox, but not Emacs. Then, if I close Emacs, Firefox stops being listed in the output. Opening a third application (as well as Emacs and Firefox) does not cause Emacs to be added to the output. As best as I can figure out, wmctrl will only detect one window beyond the panel, and even that only if another window is opened afterwards.

The homepage for wmctrl does note that it "only works with window managers that implement the EWMH specification". Is this behavior just due to Budgie's window manager not implementing this specification? If not, is there any known reason why wmctrl would not work with Budgie?

Thanks a bunch!

**Comment by ikeydoherty** [comment]
Not sure why `wmctrl` is even showing Budgie Panel, it's a dock-type window that skips page and taskbar.

Note our internal window management functions come from Mutter itself, so if there's a problem, that is mostly likely where it would be. Have you tried using wmctrl with GNOME Shell before? (Recent versions)

**Comment by saghm** [comment]
I have used it with Gnome before without issue, although I think only as recently as 3.18. I'll try it out on Gnome again and see if I can replicate the issue there.

**Comment by ikeydoherty** [comment]
Closing due to lack of response
