### ISSUE TITLE
Debian review issue 4: Would it be possible to sign tags and releases

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#463]
Request from Debian,

Ikey - would you consider signing both tags and releases in future releases?

 - https://wiki.debian.org/Creating%20signed%20GitHub%20releases
 - https://help.github.com/articles/signing-tags-using-gpg/

Apparently Debian's policy is to encourage upstream to sign commits (which you are doing), tags and releases to provide assurance of the stuff being built.

**Comment by ikeydoherty** [comment]
The commits are signed already and have been for weeks, obviously tags will be too.

As I distribute the tarball passing `make distcheck` on the tag, (And let's not forget ACL here on the solus-project repos) - they shouldn't *use* my tags. Using the GitHub generated tarball is *not* supported.

**Comment by ikeydoherty** [comment]
Redirecting to #465
