### ISSUE TITLE
Debian review issue 5: spelling and typo's

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#464]
Ikey,

Debian review comment:

  feeling like piggy in the middle here - so sorry in advance :(

<pre>
$ codespell --quiet-level=3
./raven/sound.vala:384: dont  ==> don't
./raven/sound.vala:395: dont  ==> don't
./raven/Makefile.am:44: calender  ==> calendar
./gvc/gvc-mixer-control.c:514: successfull  ==> successful
./gvc/gvc-mixer-control.c:1503: everytime  ==> every time
</pre>

Apparently these are an issue when running "codespell"

**Comment by ikeydoherty** [comment]
GVC is a git submodule I don't control the code for, they should raise the issue upstream with GNOME, not me.

As for spelling issues in the code, who cares. I'm the maintainer, not them. If the spelling mistakes occur in *translations*, then it is an issue..

**Comment by ikeydoherty** [comment]
They won't hit a release until I've done with the `app-system` branch

**Comment by ikeydoherty** [comment]
^ Integration practices have now been document, before we start falling down a rabbit hole :)

**Comment by ikeydoherty** [comment]
Redirecting to #465
