### ISSUE TITLE
please decide where is the bug manager

### ISSUE THREAD

**Issue by cybernet** [solus-project/budgie-desktop#466]
on the site bug tracker is specified to be at https://bugs.solus-project.com/

in my opinion it's best to be in one place only

**Comment by ikeydoherty** [comment]
Solus bugs are on the Solus bugzilla. Budgie-specific bugs are on GitHub.
Regardless of your opinion, it doesn't give you free license to decide to move bugs to GitHub and claim you were directed there

**Comment by cybernet** [comment]
so why having them in 2 places is a good solution ?
https://bugs.solus-project.com/buglist.cgi?component=Desktop&list_id=5921&product=Solus%20Operating%20System%201.0&resolution=---

**Comment by ikeydoherty** [comment]
Because Budgie is distro-agnostic and code collaboration happens solely on GitHub.
When I closed the issue it indicated it wasn't something that was up for discussion.
