### ISSUE TITLE
Monitor-Edge Pixel Gap

### ISSUE THREAD

**Issue by Web-eWorks** [solus-project/budgie-desktop#469]
Running (fully updated) Solus 1.1, with a two-monitor setup, I am running into an issue.

When maximizing certain applications (Nautilus, Firefox, Atom, KSP, etc...) on my second monitor, there is a one pixel gap (through which the desktop background can be seen) between the edge of the window and the edge of the screen.  This gap appears on both the window content and window decorations, so I believe it to be an issue in the desktop/WM.

![20160608_134235_hdr](https://cloud.githubusercontent.com/assets/4218491/15905064/6e55326e-2d81-11e6-9ed1-7871abbc0375.jpg)

![screenshot from 2016-06-08 13-44-56](https://cloud.githubusercontent.com/assets/4218491/15905071/767debc0-2d81-11e6-9c06-4eaed1fdb0dd.png)

In addition, this issue seems to be present on the first screen as well, although not visible.  Placing the mouse at the very left hand side of the screen, Plank appears to only register a 'mouse hover' (as evidenced by icon glow) occasionally.

**Comment by TheAifam5** [comment]
Must be problem with your theme.
![gap](https://cloud.githubusercontent.com/assets/2192274/17189286/2562adb6-5441-11e6-994a-b384e422d312.png)

I'm using Adapta-Nokto.

**Comment by Web-eWorks** [comment]
Adapta-Notoko:
![screenshot from 2016-07-27 18-59-10](https://cloud.githubusercontent.com/assets/4218491/17195554/6dfd4582-542c-11e6-9d9c-76487bd0539b.png)
![screenshot from 2016-07-27 19-10-37](https://cloud.githubusercontent.com/assets/4218491/17195753/d8f0b74c-542d-11e6-812c-53844b8fa8bf.png)

On all three screenshots, there is a one-pixel gap that windows don't occupy, showing my desktop.
The first screenshot was taken with a physical camera, hence the pixels.

If it helps, here's my monitor arrangement:
![screenshot from 2016-07-27 19-02-06](https://cloud.githubusercontent.com/assets/4218491/17195649/1bacbe56-542d-11e6-8ef6-8eb4f4bb97f3.png)

And here are two images showing the issue, with and without a window:
![screenshot from 2016-07-27 19-07-50](https://cloud.githubusercontent.com/assets/4218491/17195705/7dcf8e1a-542d-11e6-9a72-fd038c2f05c6.png)
![screenshot from 2016-07-27 19-08-01](https://cloud.githubusercontent.com/assets/4218491/17195706/7f129a92-542d-11e6-8ba9-f1db89f2af2f.png)

**Comment by ikeydoherty** [comment]
Can anyone confirm if this is happening in GNOME Shell?

**Comment by Gabe-Linux** [comment]
I can confirm it doesn't happen with GNOME Shell 3.20 (on Arch). It appears to be an issue with budgie-panel, as only when you drag it into the top left corner of the screen and within the height of the panel does it show the pixel of space. It looks like @TheAifam5 put his window below the panel, hence why he doesn't have the gap.

Is budgie-panel possibly reserving an extra pixel on the right hand side?

**Comment by ikeydoherty** [comment]
No I meant running a panel on GNOME. lol.

**Comment by Gabe-Linux** [comment]
My bad :D Running budgie-panel on top of GNOME Shell does result in that pixel of space. Once budgie-panel is killed the issue is gone again.

**Comment by ikeydoherty** [comment]
Well if someone is willing to test the patch I'm about to make... we'll see if your theory stands @Gabe-Linux  - have a feeling you're right now

**Comment by ikeydoherty** [comment]
^

**Comment by Gabe-Linux** [comment]
The patch fixes the issue.

![extra-pixel](https://cloud.githubusercontent.com/assets/677488/17541375/bb2be56a-5e8c-11e6-9540-a594cabe9241.png)

**Comment by ikeydoherty** [comment]
Unless I'm being dumb there's a window overlap onto your panel

**Comment by Gabe-Linux** [comment]
I'm trying really hard to see the overlap, but I don't think it's there. It does kinda look like there is in the picture, but there is no visible overlap when looking at my monitors.

**Comment by ikeydoherty** [comment]
Fuck it. Call it fixed. Lol. Thanks for testing @Gabe-Linux !
