### ISSUE TITLE
[Feature] Vertical workspaces

### ISSUE THREAD

**Issue by PJkeeh** [solus-project/budgie-desktop#470]
Add an option to add vertical workspaces instead of just the horizontal ones

**Comment by ikeydoherty** [comment]
What possible difference does it make.. ?

**Comment by PJkeeh** [comment]
Can be quite useful to have, since it's a bit faster at times to use. Most desktop enviroments seem to have them.

**Comment by ikeydoherty** [comment]
I.. don't see the difference. 

So you'd use: CTRL+ALT+LEFT/RIGHT for horizontal switching by default, and CTRL+ALT+UP/DOWN for vertical. And the same amount of distance with the mouse on the workspace applet. Talk me through it because I don't get it - and I don't wanna rebuke something just because I don't understand. Gimme a usecase :)

**Comment by PJkeeh** [comment]
Yea, I use exactly that. When programming I have my IDE on the right top and output/documentation on the bottom right. On the top left I have my browser with research etc. On the bottom left I have music and mail, chat, things I don't have to go to that often. That's a simple example I guess, cause most of the time I have 3x2, since I have my network readouts with throughput etc, and wireshark to the right of my output and a terminal on the left of the IDE. It's just the one thing I miss from Unity I've grown used to.

**Comment by feskyde** [comment]
So you're talking about **a grid of workspaces** instead of using horizontal ones only?

**Comment by PJkeeh** [comment]
Yea, both horiontal and vertical ones. Like this: [http://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/109/10947/10947f1.jpg](url)

**Comment by PJkeeh** [comment]
Seems like there already was an issue about this, [https://github.com/solus-project/budgie-desktop/issues/460](url)

**Comment by ikeydoherty** [comment]
In that case.. Closing as duplicate of #460 - we'll track there
