### ISSUE TITLE
solus data directory for panel.ini - trying to customise the top panel for all users

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#471]
Using Solus 1.1 - testing configuring budgie-desktop via a separately supplied panel.ini in the confdir (/etc/budgie-desktop) or datadir (/usr/share/budgie-desktop)

I added a panel.ini to /usr/share/budgie-desktop 

Created a new user and logged into him - the panel was the standard panel - not my custom panel.ini

Any ideas what I'm doing wrong?

contents of /usr/share/budgie-desktop/panel.ini

[Panels]
Panels=Top Panel

[Top Panel]
Children=Budgie Menu;Spacer 1;
Position=Top

[Budgie Menu]
ID=Budgie Menu

[Spacer 1]
ID=Spacer

**Comment by ikeydoherty** [comment]
Do you have a *fully updated* Solus 1.1 from the last few days?

**Comment by fossfreedom** [comment]
no - fresh download.  Ok - by inference of your question this is a post 1.1 fix?

I'll download 1.2 this weekend and have a retry.

**Comment by ikeydoherty** [comment]
We released 1.1 in March, the fix was in April:

https://github.com/solus-project/budgie-desktop/commit/9fe26335f2fc374b01da5b1297694ccb8e0c0818

And yeah I'd agree, wait for 1.2, so you have less messing about :D

**Comment by fossfreedom** [comment]
all seems to work nicely with 10.2.6 - cheers!

**Comment by ikeydoherty** [comment]
Awesome
