### ISSUE TITLE
[Feature] snap to quarters

### ISSUE THREAD

**Issue by scheckley** [solus-project/budgie-desktop#472]
Is it possible to get applications to snap to corners of the desktop as well as sides? Cinnamon does this.

Thanks.

**Comment by adamjameschristensen** [comment]
+1

**Comment by ikeydoherty** [comment]
That'd need to happen at the Mutter level

**Comment by adamjameschristensen** [comment]
Looks like that has been requested
https://bugzilla.gnome.org/show_bug.cgi?id=751857

**Comment by ikeydoherty** [comment]
Closing this because we can't implement that without Mutter implementing it first
