### ISSUE TITLE
Gnome Epiphany missing "Pin to panel' menu item

### ISSUE THREAD

**Issue by MadcapJake** [solus-project/budgie-desktop#476]
This application does not offer a "Pin to panel" option when you right click on its icon in the panel tasklist.

**Comment by ikeydoherty** [comment]
This is actually fixed in git, what version of Budgie and what distro?

**Comment by MadcapJake** [comment]
Solus 1.2, freshly installed last night.

**Comment by ikeydoherty** [comment]
OK cheers, we might need a nother budgie sync in Solus then :)

**Comment by icyswift** [comment]
hey ikey, 
i cannot pin visual studio code to the panel or plank.
Is this the same issue.

Thanks for all your hard work on this great distro :clap:

**Comment by ikeydoherty** [comment]
That was fixed too
