### ISSUE TITLE
Lock icon in raven is triggering lightdm

### ISSUE THREAD

**Issue by taaem** [solus-project/budgie-desktop#477]
Since now budgie integrates gnome-screenlock, the lock icon in raven should trigger gnome-screenlock and not lightdm anymore.
Now if you lock the screen via Raven lightdm locker appears but if you unlock the session gnome-screenlock is triggered.

PS: I think the top panel of gnome-screenlock should be the same color as budgie panel and not black.

**Comment by ikeydoherty** [comment]
Fixed in git, available in Solus 1.2 repos
