### ISSUE TITLE
budgie panel disappearing

### ISSUE THREAD

**Issue by gothmog123** [solus-project/budgie-desktop#483]
It disappears for like a second when starting some apps. Sometimes it changes into a colourful mess of distorted pixels. Is this a known bug?

**Comment by ikeydoherty** [comment]
No definitely not a known bug, please provide all details (distro/drivers/budgie version/etc) so we can work out what is going on

**Comment by gothmog123** [comment]
Hi, thanks. I'm on Arch, all the latest packages. Haswell chromebook with the intel modsetting driver - no xf86-intel. Maybe that's the problem.

**Comment by ikeydoherty** [comment]
There is no "intel modesetting driver" - If you're using Intel graphics you should be using xf86-video-intel (I've no idea what Arch calls it) to ensure you have full capabilities, this driver provides KMS (modesetting) usage for Intel

**Comment by gothmog123** [comment]
Sorry to be pedantic, but people do talk about getting rid of the xf86-video-intel, see this thread for example:

https://bbs.archlinux.org/viewtopic.php?id=213533

it actually fixes some problems.

**Comment by ikeydoherty** [comment]
It looks like Arch is constantly updating the xf86-video-intel driver blindly [1], so it is unsurprising there are issues. I also note they're not enabling DRI3 by default which they _should_ with latest xf86-video-intel and mesa.

For reference, within Solus:
https://git.solus-project.com/packages/xorg-driver-video-intel/tree/package.yml

Known to be working all the way through to Skylake.

Closing this issue as its driver related and something Budgie can't do anything about.

[1] https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/xf86-video-intel

**Comment by gothmog123** [comment]
Thanks, no problem, I understand completely.

Can I ask you another question about using budgie on Arch? Is it likely to break, ex. like Cinnamon (because of crazy Arch updates)? 

What will usually happen when I'm on a given version of Budgie and gtk/gnome suddenly gets a major version update?
