### ISSUE TITLE
Vertical window snap

### ISSUE THREAD

**Issue by Timalex** [solus-project/budgie-desktop#484]
Ability to snap windows by dragging them to the edge of the screen, not just horizontally, but vertically as well.

**Comment by porkslapchop** [comment]
I don't think that's possible since it isn't possible in gnome. Could be wrong though

**Comment by ikeydoherty** [comment]
We need to wait for the behaviour to appear upstream in Mutter, @porkslapchop is correct

**Comment by ikeydoherty** [comment]
Closing this because there's really nothing we can do about this until Mutter supports it

**Comment by framerate** [comment]
Is there a link to Mutter we can follow for this?

**Comment by JoshStrobl** [comment]
@framerate Here's a few.

- https://gitlab.gnome.org/GNOME/mutter/-/issues/704
- (From 2014): https://bugzilla.gnome.org/show_bug.cgi?id=740404

You can also install the budgie-window-shuffler applet developed by Ubuntu Budgie, it's in the Solus repo. That *should* do the trick. Please note that this was packaged by someone that is not a member of the Solus team and thus I cannot guarantee it will work. Upon installation, relog and it'll show up under Budgie Desktop Settings where you'd add and configure other applets.

Quarter tiling and triple tiling are items we will support in Budgie 11's window manager (which won't be based on Mutter). Like it's 2020 and ultrawides + 4k monitors exist, gimme more windows.

**Comment by framerate** [comment]
Thanks Joshua. I'm on an ultrawide and have a vertical 1080 next to it so IM READY. 

Lemme know when I can test Budgie 11 ♥️
