### ISSUE TITLE
Polkit dialog theming fails after reboot/log out

### ISSUE THREAD

**Issue by poltertec** [solus-project/budgie-desktop#487]
Couldn't find a bug report for this so... here we go :) 
Every time you reboot or log out, the polkit dialog sets itself to the built in theme.
Rest of Budgie  (session-dialog, etc) keep the selected theme perfectly.

Screenshot before and after log out:
![screen before](https://cloud.githubusercontent.com/assets/8506580/16542992/405213fe-40bf-11e6-981b-04ce4482f935.png)
![screen after](https://cloud.githubusercontent.com/assets/8506580/16542994/4aa1570c-40bf-11e6-932f-73ca5ba8fc33.png)

**Comment by ikeydoherty** [comment]
Fixed in the above commit :)

![screenshot from 2016-07-21 20-27-58](https://cloud.githubusercontent.com/assets/164489/17035898/c96ff5fe-4f81-11e6-9472-02b79d54bf9d.png)

**Comment by poltertec** [comment]
superb :)
