### ISSUE TITLE
Launching a pinned app spawns extra "Starting x" task

### ISSUE THREAD

**Issue by megapctr** [solus-project/budgie-desktop#488]
When I launch a pinned app "x" from icon task list, task list shows additional "Starting x" app and the cursor changes to busy.

![starting](https://cloud.githubusercontent.com/assets/4096683/16547920/5676da66-417d-11e6-8207-c6377904e5a0.gif)

Recorded on Solus 1.2

The "Starting" task goes away after a couple of seconds.

**Comment by ikeydoherty** [comment]
That's because you're using *two* tasklist applets in one panel. The other tasklist is provided by libwnck, something we cannot address. Both of them are in the same process and not catching each others SN messages. To me this is an invalid use of the tasklists.

**Comment by megapctr** [comment]
I organized them this way because I wanted to have a task list and a quick launch bar. If it's already been requested to add a quick launch bar, I think this issue can be closed

**Comment by ikeydoherty** [comment]
That's fine, but it's *not* a quick launch bar, so from that perspective it's an invalid bug :) Some form of quick launching will be added in future, but through dedicated launchers.
