### ISSUE TITLE
Missing translations in Budgie

### ISSUE THREAD

**Issue by darkben** [solus-project/budgie-desktop#493]
Hi,

after updated my system today i notice that french translations aren't complete in the locale file :

https://github.com/solus-project/budgie-desktop/blob/master/po/fr_FR.po

But when i'm going on transifex all strings are well translated

https://www.transifex.com/solus-project/budgie-desktop/translate/#fr_FR/budgie-desktoppot/45204074?reviewed=no

Example : Power off box isn't translated in Budgie 10.2.6

Is it normal ? Is it planned to Budgie 10.3 ?

Thanks

**Comment by ikeydoherty** [comment]
I synced the translations yesterday, so perhaps they've changed since?

**Comment by darkben** [comment]
It's strange because the missing strings have been translated some weeks ago. I don't understand. The last sync seems to be dated at april 25.

**Comment by ikeydoherty** [comment]
This was the last time the script picked up changes in sync:
https://github.com/solus-project/budgie-desktop/commit/66b1650158969c71eab824c836811f9d65586899

7 days ago

**Comment by darkben** [comment]
Ok... French files are 100% translated and the strings are missing. How can we correct this problem ? How can i help ?

**Comment by ikeydoherty** [comment]
Well I can't do anything until after work but I'll check then :)

**Comment by darkben** [comment]
Ok ! Big thanks Ikey !

**Comment by darkben** [comment]
Ikey, i have translated 2 strings today in the two french files : 

https://www.transifex.com/solus-project/budgie-desktop/language/fr_FR/

https://www.transifex.com/solus-project/budgie-desktop/language/fr/

Strings are 100% translated, you can sync again and verify all is ok.

Thanks again !

**Comment by ikeydoherty** [comment]
They should now be in and we'll sync into Solus soon :)

**Comment by ikeydoherty** [comment]
https://github.com/solus-project/budgie-desktop/commit/640d7859e6cf3ec1e3a7e77bd6ba2aa55ddc858f :D

**Comment by feskyde** [comment]
I'm too late to say that "Launch [Application]" tooltips on pinned items are untraslatable too? :confused:

**Comment by ikeydoherty** [comment]
Fack.

**Comment by darkben** [comment]
Thanks Ikey but i don't see french language here [https://github.com/solus-project/budgie-desktop/commit/640d7859e6cf3ec1e3a7e77bd6ba2aa55ddc858f]. (fr.po or fr_FR.po)

**Comment by ikeydoherty** [comment]
I'm using the sync script that works for _every other language_, it's not a problem my end, they need to be 100% complete on Transifex at the time of sync

**Comment by darkben** [comment]
Ok Ikey no problem. If you can sync again before publishing updates it will be great !
