### ISSUE TITLE
Close run dialog when focus lost

### ISSUE THREAD

**Issue by theSoenke** [solus-project/budgie-desktop#494]
The new run dialog in v10.2.6 is really nice, but when i loose focus e.g. by clicking somewhere on the screen i can't close the run dialog anymore without selecting it again. I think the best behavior would be to close the run dialog automatically when focus is lost. Similar to the behavior of raven

**Comment by ikeydoherty** [comment]
Fixed in the above commit :)

**Comment by theSoenke** [comment]
thanks :)
