### ISSUE TITLE
wandering Raven Trigger applet

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#503]
![](http://i.imgur.com/NJT3zDg.png)

sorry about the screenshot - think you can just about make out in the Raven Panel (somewhat hidden at the bottom of the screen) that the user indicator appears right most but is supposed to be just to the left of Raven Trigger (i.e. not quite in the order listed in the "end" section of Raven)

Had manually set the new applets in the correct position and then on reboot the Raven Trigger applet decided to wander leftwards.

**Comment by ikeydoherty** [comment]
You're not using this in deployment are you? `master` is for development work, not stable use

**Comment by fossfreedom** [comment]
Absolutely no where near the community!  This is a make dist snapshot build of the latest stuff for development purposes.

**Comment by ikeydoherty** [comment]
Awesome - had me worried there :P Yeah I've noticed the wandering on my laptop, but it's not happening on my NUC, which is super odd. I have a feeling that two or more applets share the same `position` gsettings key and things are borking

**Comment by sunnyflunk** [comment]
Can confirm that the order of applets gets mixed up on the unstable version in Solus.
Name                : budgie-desktop, version: 10.2.6, release: 88

A bit of testing is showing that the switch in order occurs when I move an applet from center to right on the panel. The order corrects itself if I then move that same applet back to center. 
Also tested and it happens when moving from left to center

**Comment by ikeydoherty** [comment]
Fixed. So sorry.

**Comment by ikeydoherty** [comment]
You'll only be able to test this with a *completely* reset dconf tree of Budgie, which means you cannot have Budgie Panel running at the same time. Please verify.

**Comment by ikeydoherty** [comment]
Actually hold off testing for now, there's more to be done on this

**Comment by ikeydoherty** [comment]
That'll help ^

**Comment by ikeydoherty** [comment]
Alright its legit fixed this time, I swear. Lol.

**Comment by sunnyflunk** [comment]
So I figured the best way to validate the process was a package.yml of the git clone + build [http://hastebin.com/adukimidal](http://hastebin.com/adukimidal) (and ensure no conflict of current installed version). 

Built, installed, rebooted. Always created a new user (so no stale dconf) to log-in. Then without changing anything, move the icon list from left to center to right. Result is a couple of the applets shuffling still (didn't initially catch the separator and spacer were already out of order!).

![panel](http://i.imgur.com/sr9KPXM.png)

An important thing I noticed (which may be related) was that after creating a new user, you couldn't move applets down to the last two positions as if it thinks you're already at the end (could still move them up the list). Also more obvious example of them starting off in the wrong order. Removing all applets, and re-adding them fixes this new issue, but would still shuffle the applets when moving them to the right.

![http://i.imgur.com/qoRWU4X.png](http://i.imgur.com/qoRWU4X.png) <- can't click down

**Comment by ikeydoherty** [comment]
Ya I'm talking about with a fully reset dconf, and a clean install (No git/package mixing)

**Comment by fossfreedom** [comment]
ok - looks fixed.  Thanks!

**Comment by ikeydoherty** [comment]
https://www.youtube.com/watch?v=B6mh45mA_JY
