### ISSUE TITLE
Configure number of workspaces

### ISSUE THREAD

**Issue by danboid** [solus-project/budgie-desktop#504]
It would be nice if budgie/Raven allowed you to configure the number of workspaces without resorting to gnome-tweak-tool or had editing GNOME config files. In fact it doesn't seem that it respects the gnome-tweak-tool workspace setting.

**Comment by TheAifam5** [comment]
Right now on Archlinux changing number of workspaces in GnomeTweakTool sometimes crashing whole workspace and moving back to GDM(asking for login).

**Comment by JoshStrobl** [comment]
Was resolved a while back and you can modify the number of virtual desktops.
