### ISSUE TITLE
Small gap on the top and incorrect padding

### ISSUE THREAD

**Issue by TheAifam5** [solus-project/budgie-desktop#511]
Hey,
I found small gap on the top.
Display resolution: 1920x1080 one monitor

(standard gnome cursor icon)
I think compositor needs to be moved a little bit and resized.
Its moved 1 px to left and cutting 1px of mouse pointer(left border) but on right side showing 1px more.

I think top and bottom sides are good (except this black gap on top)
![top-gap](https://cloud.githubusercontent.com/assets/2192274/17094532/3d45b920-5250-11e6-93d8-4824d4eac2cf.png)

PS. Beauty project <3

**Comment by ikeydoherty** [comment]
..What?

**Comment by TheAifam5** [comment]
You dont see black line on the top of image?

**Comment by ikeydoherty** [comment]
The image is smaller than a postage stamp, how am I meant to see anything?

**Comment by TheAifam5** [comment]
Just click, hold CTRL and scroll if you using Chrome.

**Comment by ikeydoherty** [comment]
Or you could provide better screenshots..

**Comment by TheAifam5** [comment]
OK i will try send better screenshot:)

**Comment by TheAifam5** [comment]
![top-gap](https://cloud.githubusercontent.com/assets/2192274/17094888/21a99e96-5252-11e6-8a1c-289585a25547.png)

I think now you can see this black line (1px) on the top of my screen.

**Comment by ikeydoherty** [comment]
I can't recreate this with the built-in theme, this looks specific to what I'm assuming is Adapta. Do you get the same issue with the internal theme?

**Comment by TheAifam5** [comment]
Yes its Adapta-Notko.
And yes, Adapta making that gap :)
Thanks. :)

And about cursor pointer:
I have actually standard gnome cursor theme. White border of cursor (1px) is cutted when is moved to the left, and when cursor is on right side showing border(1px) and inside color (1px).

**Comment by ikeydoherty** [comment]
So in budgie-wm we don't directly handle cursor manipulation, this is handled by mutter, which is also used by gnome-shell. Please ensure you have a valid cursor icon theme set, and also check whether this is a gtk2 vs gtk3 issue, for example

**Comment by TheAifam5** [comment]
I will check with other cursor themes.. Thanks for active support :)

**Comment by ikeydoherty** [comment]
np :) Luckily I was up earlier today so I could be involved in this ^^

**Comment by TheAifam5** [comment]
This cursors works good:
https://kver.wordpress.com/2015/01/09/curses-i-mean-cursors/

So must be issue with default cursor theme provided by gnome.

I think, that's all :)
I already reported issue with black line to Adapta repo.
Have a nice day. :)

PS. You doing good work. I had KDE and Gnome env and was really heavy. Your project its really light and that's why i love it :)

**Comment by ikeydoherty** [comment]
Good choice! We actually default to Breeze in Solus - they work really well with Budgie =)

Glad to see you're getting things resolved, sorry there was nothing immediate I could do in Budgie itself :)

**Comment by tista500** [comment]
@ikeydoherty,

I'm sorry it's Adapta specific issue and just now I've committed fix (I've completely forgotten to purge styles I've done for budgie-desktop 8.x in past)...

Best Regards.

**Comment by ikeydoherty** [comment]
@tista500 no need to apologise, these things happen :D I'm just grateful that there are theming options for Budgie, keep up the good work :D
