### ISSUE TITLE
Gnome-Screenshot issue

### ISSUE THREAD

**Issue by TheAifam5** [solus-project/budgie-desktop#513]
After installation of "gnome-screenshot" package program cannot be started but after relog(logout&login again), works without problems.

![screenshot](https://cloud.githubusercontent.com/assets/2192274/17098389/60c04a3e-5262-11e6-8247-58db212acec8.png)

**Comment by ikeydoherty** [comment]
Use  `gnome-screenshot -i`, not a Budgie problem. Package issues are for Arch to fix
