### ISSUE TITLE
Resizable logout window?

### ISSUE THREAD

**Issue by TheAifam5** [solus-project/budgie-desktop#514]
Hey,
I don't know but i think logout window should be not resizable and movable.

![screenshot from 2016-07-27 11-44-46](https://cloud.githubusercontent.com/assets/2192274/17171127/8e198462-53ef-11e6-92a8-c36ad9d4eb7c.png)

Logout window saving position and size.. now i need relog :P

**Comment by ikeydoherty** [comment]
Agreed, looks derpy as fuck. I'll fix it after work lol, cheers

**Comment by ikeydoherty** [comment]
Fixed by @JoshStrobl in https://github.com/solus-project/budgie-desktop/commit/9df2769bfd3a5a30cb7669d3945429b887bbe7ad
