### ISSUE TITLE
pin to desktop

### ISSUE THREAD

**Issue by danboid** [solus-project/budgie-desktop#515]
I'd like to see an easy way to add shortcuts to the desktop. In fitting with the current way to add shortcuts to the panel, it'd be handy if you could right-click on the icon for a running app and choose 'Pin to desktop' (if Files is installed) but I'd also like to see the ability to pin non-running stuff to the panel or desktop by right-clicking an app within the foot (Budgie 'Start') menu too please.

**Comment by ikeydoherty** [comment]
Its... doable... But nasty. It then means having to access the desktop files each time we open a menu to see if the file exists..

Also at this moment right click within the Budgie Menu is broken

**Comment by danboid** [comment]
Is that how Cinnamon etc does it too? It doesn't sound too expensive to me but I trust your opinion as the author. I know nothing!

The way I organise my desktop is to have the stuff I use all the time (browser, terminal, file manager and IDE/text editor) as panel shortcuts and then slightly less used (but still frequently accessed) stuff and/or stuff that requires a spesh command to launch as desktop icons.

Writing this has made me realise that I can't edit the properties for panel shortcuts but maybe that should be a separate ticket. Besides, I'm not so bothered so long as I can edit the properties of desktop shortcuts which I can already.

**Comment by ikeydoherty** [comment]
No idea - I don't use Cinnamon. `stat` in general is an expensive call, and depends on the speed of the disk, filesystem, and what the schedulers doing.

**Comment by ikeydoherty** [comment]
And if we're going to use Cinnamon as the baseline for how things can be implemented then we're all kinda stuck up shitcreek aren't we.

**Comment by danboid** [comment]
Cinnamon is no bastion of quality, that's for sure.

I'm sure Budgie will eclipse it in every way that matters before the years out if you carry on at your usual breakneck pace!

**Comment by JoshStrobl** [comment]
Not planning on implementing pin-to-desktop functionality. The future desktop icons implementation will be oriented solely towards files and mounts.
