### ISSUE TITLE
[Arch Budgie-Desktop-Git] Cannot change the "Lid-Close" behaviour on my Thinkpad T520.

### ISSUE THREAD

**Issue by Snisser** [solus-project/budgie-desktop#525]
I'm a really big fan of the Budgie-Desktop. I'm currently using it on my Desktop and trying to set it up on my Thinkpad 520. I went through the regular settings, gnome-tweak-tool, /etc/systemd/logind.conf and /etc/UPower/, nothing out of all this worked for me. I just want my Laptop to "do nothing" when the lid is closed.

**Comment by ikeydoherty** [comment]
Forgive me, but how is this a Budgie issue? This is a systemd issue, no?

**Comment by Snisser** [comment]
Hm, sorry i'm not a Tech-guy, ofcourse it could be something else. Though on Xfce, Gnome, Mate everything worked as i wanted. Because of this i thought it would be a Budgie-Thing.

Thanks for the friendly response though! I think i'm going to close this and go to Reddit, maybe posting this here is really a bit off-topic :P.

Kind regards, have a good day and keep doing what you're doing!

**Comment by Snisser** [comment]
Hm, sorry i'm not a Tech-guy, ofcourse it could be something else. Though on Xfce, Gnome, Mate everything worked as i wanted. Because of this i thought it would be a Budgie-Thing.

Thanks for the friendly response though! I think i'm going to close this and go to Reddit, maybe posting this here is really a bit off-topic :P.

Kind regards, have a good day and keep doing what you're doing!

**Comment by ikeydoherty** [comment]
I think this is what you need: http://unix.stackexchange.com/a/52645/106986

Trust me I understand your annoyance with this - we've a similar pain-in-the-arse over in Solus :(

**Comment by Snisser** [comment]
Thank you for the link! Going to look into it as soon as i'm home! :) 

Nha, it's not annoyance, it's just a problem i need to fix. I'm not using Arch because i want a trouble-free experience ;D

Going to keep trying and eventually post the solution over here i think, just so people with similar problems may find a solution over here  :)

Don't worry, i really have faith in you Solus-Guys. Since the first release of Solus-Project (OS), i was fascinated by the elegance, good documentary, support that solus provides, overall i'm just a big fan :)

**Comment by Snisser** [comment]
Oh my god, problem solved through your link. I seriously forgot to uncomment the line i was editing! Everything works WONDERFUL now, BUDGIE FTW! :)

**Comment by ikeydoherty** [comment]
Main thing is you're up and running properly now :D
