### ISSUE TITLE
A problem with disabling animations

### ISSUE THREAD

**Issue by cyber-doug** [solus-project/budgie-desktop#526]
Using the pre-installed tweak tool for Solus, I have disabled animations and restarted the system. It works as expected with only one exception. It's possible to open Budgie Menu by tapping the Super key, but it's not possible to close it by pressing it again (however, this _works when animations are enabled_).

Instead, **it hides while holding Super and reappears after you release the key**. It's very awkward. It won't close unless I click somewhere else.

It is reproducible with any theme or any other related configuration available within Raven or Tweak Tool.

**Comment by ikeydoherty** [comment]
Disabling animations is currently unsupported in Budgie
