### ISSUE TITLE
gnome-software kills budgie-panel ... and can kill gnome-session

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#527]
http://pastebin.com/0pB9CAiJ

this is a journalctl -ae > output.txt dump

Ikey,

  at around line 215 lots of errors thrown up by budgie-panel.  Looks like its been hit lots of times and this crashes budgie-panel.  After a couple of budgie-panel respawns, gnome-session dumps you to the login screen.

I do note that when you install any software, budgie-panel does momentarily disappear and then reappears.  It looks like if you tell gnome-software to do 3 or 4 quick installs, this disappear/reappear of budgie-panel causes the crash of gnome-session.

Any ideas how to produce better logs to pin down the issue?

D

**Comment by ikeydoherty** [comment]
aug 07 00:58:07 a-desktop gnome-session[3440]: *** Error in `budgie-panel': free(): invalid next size (fast): 0x0000000001db2b70 ***


Oh Vala... You poor lost soul.

Can I get the backtrace from `coredumpctl gdb` please?

**Comment by fossfreedom** [comment]
ok - have got the user in question to install and run that:

 - http://pastebin.com/AHuFYLkr

**Comment by fossfreedom** [comment]
ok - have managed to crash budgie-panel myself

http://pastebin.com/QKx3KrC8

does that help?

**Comment by fossfreedom** [comment]
ikey - is this commit anything to-do with this issue - looks like its in the same area

 - https://github.com/solus-project/budgie-desktop/commit/8959401656d13c107badf3ad871eb331ea750ebf

TIA

**Comment by ikeydoherty** [comment]
Maaaay be part of it I'm unsure, you anyway of testing?

**Comment by apolitech** [comment]
Any updates about this bug? I was the person that found it.

**Comment by ikeydoherty** [comment]
No updates from me - I already made some blind fixes in git.

**Comment by apolitech** [comment]
I see ikeydoherty . Thx for you time. A quick question off topic when packet tracer, gns3, whireshark and zenmap will be available in solus?

**Comment by ikeydoherty** [comment]
Eh wireshark and zenmap have been in for a very long time

**Comment by ikeydoherty** [comment]
(Like probably a year)

**Comment by apolitech** [comment]
quick question. I use system monitor made by @fossfreedom and i get this error http://pastebin.com/RKJtiaAG . it's the same problem like above or it's a applet problem? @fossfreedom  it's not available at this time (it's on vacantion) and i wanna help in any way i can

**Comment by fossfreedom** [comment]
@ikeydoherty 

testing the very latest master commits on a make distcheck build on 16.04.1 - unfortunately budgie-panel is still crashing when installing new software

http://pastebin.com/b1LGt5pr

**Comment by ikeydoherty** [comment]
Note to self: ideally we should add a delay system and an atomic refcount to ensure we only end up doing the refresh once within a given time period.

**Comment by fossfreedom** [comment]
k - thanks.  Going to patch and test immediately.  Thanks.

**Comment by ikeydoherty** [comment]
Cheers

**Comment by fossfreedom** [comment]
ok - after some testing with 10.2.7 on 16.04, sorry to say that this issue is still occuring :/

**Comment by ikeydoherty** [comment]
OK well sure we tried. ^^

**Comment by fossfreedom** [comment]
Ikey - is there a simple patch I can include to turn off the menu refresh option.  Whilst it is kind of nice to have the menu update when a new app is loaded, its more than annoying to have the whole session crash when doing just a full update of all the latest repository patches.

**Comment by ikeydoherty** [comment]
Remove this from BudgieMenuWindow.vala:

```
            /* Think of deferred routines.. */
            Idle.add(()=> {
                tree.changed.connect(refresh_tree);
                return false;
            });
```

Round line 185.

**Comment by fossfreedom** [comment]
ta - much appreciated.

**Comment by fossfreedom** [comment]
ok - we have a dupe here - closing this in favour of this - https://github.com/solus-project/budgie-desktop/issues/632
