### ISSUE TITLE
Multitouch Won't Work

### ISSUE THREAD

**Issue by sir-tim-mccabe** [solus-project/budgie-desktop#528]
I'm running Arch Linux, and I've tried both the budgie-desktop and budgie-desktop-git packages from the AUR. Unless I log into Gnome Shell, log out, and then log into Budgie, Budgie won't recognize multitouch on my touch screen (eg two-finger tap, pinch zoom, etc.)

**Comment by sir-tim-mccabe** [comment]
Actually, with more experimentation, I realized that it works if I log into Budgie, log out, then log into Budgie again.

**Comment by ikeydoherty** [comment]
o_O sounds ... odd.... not sure how to reproduce without the hardware

**Comment by sir-tim-mccabe** [comment]
Alright, I'll keep searching for a solution. Tried switching display managers - I started on lightdm, so I switched to gdm and found that the log out fix doesn't work (just to make things stranger). I'm on a Lenovo Yoga 14.

**Comment by ikeydoherty** [comment]
Ok we'll certainly keep this issue open

**Comment by sir-tim-mccabe** [comment]
I just experienced this issue while using Gnome out of nowhere, so it isn't Budgie specific. I think it's fair to close this issue.
