### ISSUE TITLE
Strange graphical behaviour

### ISSUE THREAD

**Issue by danielmelogpi** [solus-project/budgie-desktop#53]
I just installed Budgie from the repository and it's behaving very oddly. 
I'm using 2 displays and when I open something in the left display, a "shadow" of it is displayed agains the background in the right one.

I'm not sure if it has a connection, but dragging a windows causes a break in the desktop wallpaper around it and sometimes the tail of the movement can be seen (this last one I can't provide a printscreen, because doing it fix the thing.

Also, the taskbar is transparent most of the time, except for when I open Google Chrome (it becames brown in both displays) .

Here some info about my sistem. If there is something else I can provide, let me know.
```
uname -mrs
Linux 3.13.0-30-generic x86_64

uname -a
Linux earth-kingdom 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty
```

![captura de tela de 2014-07-12 19 55 36](https://cloud.githubusercontent.com/assets/3124696/3563017/c99c380e-0a18-11e4-9588-2fd612a5d319.png)
![captura de tela de 2014-07-12 19 56 59](https://cloud.githubusercontent.com/assets/3124696/3563018/c99f2c30-0a18-11e4-9d9b-a06365beb9c0.png)
![captura de tela de 2014-07-12 19 58 31](https://cloud.githubusercontent.com/assets/3124696/3563019/c9a19524-0a18-11e4-87d9-8e548b1a4993.png)

**Comment by ryanleesipes** [comment]
Any ideas as to what is causing this @ikeydoherty ?

**Comment by ikeydoherty** [comment]
The shadows and artefacts were resolved a while back with the rewrite. If the issue prevails, please open a new issue specifically relating to the new conditions.
