### ISSUE TITLE
Focus after closing application menu

### ISSUE THREAD

**Issue by niyasc** [solus-project/budgie-desktop#530]
**Scenario** : Consider an open application, then we click on application menu, and then close it without opening any application. Then normal expectation is, previously opened application should be focused. But window is no more focused.

This behavior is present with raven. If one window is focused and we open, then close raven, window is focused again.

**Comment by ikeydoherty** [comment]
I'll see if I can make this the very last 10.2.8 feature to land..

**Comment by ikeydoherty** [comment]
And done ^^
