### ISSUE TITLE
Notification time stamps in Raven are 24 hour time even though I am using the AM/PM setting in GNOME Control Center

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#534]
Notification time stamps are in 24 hour time instead of AM/PM time.

**Comment by ikeydoherty** [comment]
Resolved by @cybre in 55bcfc1678f6c7f9e721e6aa582b16ccfc8bf0c7 :)

**Comment by tristan957** [comment]
Thanks for the fix guys!
