### ISSUE TITLE
Skype missing Pin to Panel!!

### ISSUE THREAD

**Issue by thecodechef** [solus-project/budgie-desktop#536]
Hey guys @JoshStrobl @ikeydoherty just wanted to let u guys know that Skype for linux is not showing Pin to Panel in its Panel Context Menu

Thanks for Listening, Jeremy

**Comment by ikeydoherty** [comment]
Not sure why you're pinging Josh, I'm the Budgie author.

**Comment by thecodechef** [comment]
I didn't know who was the project manager i just was told to put up on here instead on dev.solus-project.com now that i know i will make sure to only mention @ikeydoherty from now on ok

and also i was think about putting a new feature request but since it pertains to this as well just ask it now 

#### Feature Request: Add Pin to Panel in Application Menu for a Context Menu

**Comment by ikeydoherty** [comment]
I was just curious why it needed a ping regardless :P Bugs get seen - emails get sent. 
Just to clarify is this for Skype for Linux Alpha, or the old Skype?

**Comment by JoshStrobl** [comment]
> Just to clarify is this for Skype for Linux Alpha, or the old Skype?

Current Skype for Linux Alpha. Reproduced on git. I'll get ya a PR.

**Comment by ikeydoherty** [comment]
Resolved with the latest git changes
