### ISSUE TITLE
budgie-desktop not updated for Fedora 24 on OBS

### ISSUE THREAD

**Issue by notadrop** [solus-project/budgie-desktop#544]
Fedora 24 has been out for a couple of months; however, budgie-desktop is still not available for it on [OBS](https://software.opensuse.org/download.html?project=home%3Aikeydoherty%3Asolus-project&package=budgie-desktop).

**Comment by diazbastian** [comment]
@notadrop is update

**Comment by ikeydoherty** [comment]
Needs testing but yeah we finally have an F24 repo :)
