### ISSUE TITLE
Strange behiavour of notifications

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#546]
Take a look to [this video](https://youtu.be/WJRXnLsD3yQ).

As you can see:
- First notification appears with a big margin at the top (like a panel with default size and a little more space)
- When vertical space is full they still spawn in bottom instead of placing where the previous notifications appeared

**Comment by JannikHa** [comment]
I don't mean to be offensive but what do you expect? These kind of notifications have a specific **timeout**, meaning that if one notification is still "active", there can't be spawn another one at **it's place** or **before** that, so it spawns right under the last one, it's just the way it works.

I really understand what you mean, but when is the time when you seriously have the notification stacked up like this?

**Comment by feskyde** [comment]
Yes, I know how notifications works right now, but they shouldn't try to appear outside the screen, just placing them at the left side (as XFCE, but it's a very screen-spammy solution) or removing the first ones (Raven can store them so there isn't necessity of showing all untill they're timed out).

I sent this issue after deploying my Hexo site using a plugin that sends a notification for every single action during the page building, I'm not using it now but the issue still remains.

**Comment by ikeydoherty** [comment]
Your plugin should be updating the existing notifications by retaining their ID

**Comment by feskyde** [comment]
Same for `notify-send`?
