### ISSUE TITLE
PSPP Missing Panel Pin

### ISSUE THREAD

**Issue by ImpossibleRubix** [solus-project/budgie-desktop#547]
Hello, PSPP is missing the 'Pin to panel' option in the right-click menu.

Justin said to post the following lines:
```
WM_CLASS(STRING) = "psppire", "Psppire"
/usr/share/applications/pspp.desktop
```

Cheers!

**Comment by ikeydoherty** [comment]
@JoshStrobl fixed it in bfcd828251837b1a5648ef7f87e61310c7fd5162 :)
