### ISSUE TITLE
Run dialog might have much better search

### ISSUE THREAD

**Issue by nazar-pc** [solus-project/budgie-desktop#549]
I'm sometimes forgetting how application is translated to my current locale, but I know how executable is called.
For such cases when I type `gnome-disks` I expect to get in results corresponding application, whatever is its translated naming.

Also on my system (Ubuntu 16.10) desktop file (`/usr/share/applications/org.gnome.DiskUtility.desktop`) have following contents:
```
[Desktop Entry]
Name=Disks
Comment=Manage Drives and Media
Keywords=disk;drive;volume;harddisk;hdd;disc;cdrom;dvd;partition;iso;image;backup;restore;benchmark;raid;luks;encryption;S.M.A.R.T.;smart;
Exec=gnome-disks
Icon=gnome-disks
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;HardwareSettings;X-GNOME-Utilities;Settings;HardwareSettings;
DBusActivatable=true
X-Ubuntu-Gettext-Domain=gnome-disk-utility
```
But looks like this original contents is also ignored (I mean original untranslated `Name`, `Comment` and `Keywords` keys), which is why I can't use any of these words in order to get an application in search results.

**Comment by ikeydoherty** [comment]
A lot better search has now landed in https://github.com/solus-project/budgie-desktop/commit/09a9200a0cde31cdeeadd89818d26d587f165e93 :)

Going to feature in `10.2.8`
