### ISSUE TITLE
Budgie-Menu Category Icons missing

### ISSUE THREAD

**Issue by Snisser** [solus-project/budgie-desktop#550]
It could be my own stupidity but as you can see in my screenshot, the category-icons (on the left!) are missing on the budgie-menu. Are they supposed to be gone? If not, how can i activate them again?

Screenshot: http://imgur.com/hwmiiyr

**Comment by ikeydoherty** [comment]
They're not missing, they're intentionally removed in the new design

**Comment by apolitech** [comment]
Is there any way to add a option to have the icons if you whant it?
