### ISSUE TITLE
Login Screen style (same as Shutdown menu)

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#554]
Login Screen style improvements, similar to Shutdown menu which looks much nicer.

<img src=http://i.imgur.com/cTokzFS.png>
<img src=http://i.imgur.com/BIq8pjQ.png>

**Comment by feskyde** [comment]
There is a [greeter](https://github.com/solus-project/lightdm-budgie-greeter) for LightDM ongoing

**Comment by ikeydoherty** [comment]
Closing as Budgie itself doesn't provide a greeter, but yes we intend to provide a Budgie-stylized greeter for Solus as @feskyde kindly indicated :)
