### ISSUE TITLE
Unlock migration path for 10.2.7

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/budgie-desktop#555]
The changes introduced between 10.2.6 and pending-10.2.7 break the update approach due to the switch to the user indicator, for session management.

Requires a migratory path to allow a new release. Blocker.

**Comment by ikeydoherty** [comment]
Required additions at `migration-level` 1:

`Name=User Indicator`
`Name=Raven Trigger`

**Comment by ikeydoherty** [comment]
This is now resolved and in master

**Comment by ikeydoherty** [comment]
@fossfreedom just a heads up, a 10.2.7 is in the very-near-future, and this change could affect your users.

**Comment by fossfreedom** [comment]
Ta. Thanks for the heads up. Plans already in place ;)

On 9 Sep 2016 07:26, Ikey Doherty <notifications@github.com> wrote:

@fossfreedom<https://github.com/fossfreedom> just a heads up, a 10.2.7 is in the very-near-future, and this change could affect your users.

**Comment by ikeydoherty** [comment]
Coolness :) If you want to disable the migration feature just use gsettings overrides to set the `migration-level` to 1, but its kinda handy..
