### ISSUE TITLE
Right click menu on panel icons won't move applications to the chosen workspace

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#558]
When right-clicking the panel icons, this menu is shown. When choosing to move the window to a specific workspace nothing happens. Clicking "Move to workspace right/left" will do the intended action.
![screenshot from 2016-09-05 20-12-23](https://cloud.githubusercontent.com/assets/11936772/18259028/47f1f3cc-73a5-11e6-9b70-6f42662394be.png)

**Comment by JannikHa** [comment]
What is your **operating system** and **Budgie Version**?

**Comment by tristan957** [comment]
Sorry. Solus and 10.2.7

**Comment by JannikHa** [comment]
Using **Arch Linux** with **Budgie 10.2.7**. Tried to reproduce the problem but failed.
Does this problem occur with **every** application or just with specific ones? Will try to mimic this problem on **Solus OS** ASAP.

**Comment by tristan957** [comment]
It doesn't seem to work for any window. I tried Chrome, Atom, and Nautilus.

**Comment by JoshStrobl** [comment]
Resolved with the new IconPopover implementation, which let's you move to a specific workspace.
