### ISSUE TITLE
Battery Icon Missing

### ISSUE THREAD

**Issue by Zafuzi** [solus-project/budgie-desktop#562]
Battery Icon missing from panel (assuming new triggering stuff is causing this)
But when I try to check the battery in upower I get no statistics or history.

Maybe I am just not looking in the right place?
edit: Full restart doesn't help

Macbook Pro 2014 | Solus 1.2.1
 
upower -i /org/freedesktop/UPower/devices/line_power_ADP1
  native-path:          ADP1
  power supply:         yes
  updated:              Mon 05 Sep 2016 11:05:05 PM PDT (1825 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

**Comment by ikeydoherty** [comment]
Hm this could even be a kernel issue tbh

**Comment by Zafuzi** [comment]
I found an older thread issue sort of outlining the same problem. The solution there had to do with UPower versioning. Maybe the same applies here?

https://github.com/solus-project/budgie-desktop/issues/479

**Comment by Zafuzi** [comment]
So after a full battery cycle the icon is back. My thinking is that this might have been caused from coming out of hibernation. I have the power button set to hibernation on press (which I thought really just shut it down) but it seems that it was just a bug caused by me doing that. I'll see if I can repeat this. Until then I think this issue is closed, I'll open a new one if I find something wrong with hibernate.

**Comment by ikeydoherty** [comment]
I think this is a Solus-specific bug @Zafuzi - thanks for making me aware of it though. We should do some time on power management/acpi in Solus I think
