### ISSUE TITLE
budgie-desktop 10.2.6 does not build with GNOME 3.21 aka GNOME 3.22 on Debian Sid

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#564]
Looks like Debian are preparing to move to GNOME 3.22.  Their automated builder has thrown up a potential issue with missing dependencies.

"Bug#837077: FTBFS, dpkg-shlibdeps: error: couldn't find library libmutter-clutter-1.0.so needed by debian/budgie-core/usr/bin/budgie-wm"

Any thoughts?

build log https://buildd.debian.org/status/fetch.php?pkg=budgie-desktop&arch=amd64&ver=10.2.6-1%2Bb1&stamp=1472662156

relevant lines are this towards the bottom:

dh_shlibdeps
dpkg-shlibdeps: error: couldn't find library libmutter-clutter-1.0.so needed by debian/budgie-core/usr/bin/budgie-wm (ELF format: 'elf64-x86-64'; RPATH: '')
dpkg-shlibdeps: warning: couldn't find library libmutter-cogl.so needed by debian/budgie-core/usr/bin/budgie-wm (ELF format: 'elf64-x86-64'; RPATH: '')

I found [this](https://mail.gnome.org/archives/commits-list/2016-April/msg06846.html) that refers to linking about libmutter-cogl needing to be done in a makefile - do we need something similar in the budgie-wm makefile?

**Comment by ikeydoherty** [comment]
What? GNOME 3.21 isn't the stable version of GNOME. I don't get why this is an issue

**Comment by ikeydoherty** [comment]
If its needed for Debian conformance then I'm gonna need a patch submitted for it - I'm currently unable to test as I don't use unstable releases (They're not meant for the general public and the APIs change)

**Comment by fossfreedom** [comment]
agreed - think the release date of GNOME 3.22 is in a week or two.  Could be just teething pains in Debian packaging.  Or a real issue that guys for example from Arch will query in maybe a few weeks.

I've just installed debian sid in a VM and can confirm their builder observation.

**Comment by ikeydoherty** [comment]
Do we know what libs got added to the mutter-devel-type packages ?

**Comment by mbiebl** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=760439

**Comment by ikeydoherty** [comment]
@mbiebl shouldn't the pkgconfig for `libmutter` not provide all the relevant linking though?

**Comment by mbiebl** [comment]
It does for users of the public API afaics

**Comment by mbiebl** [comment]
tbh though, I don't know if libmutter was ever supposed to be a public library. It seems to have incompatible changes which every new GNOME release. You'd have to ask upstream though.

**Comment by mbiebl** [comment]
looking through gnome-shell's git log, there is
https://git.gnome.org/browse/gnome-shell/commit/?id=093fd54e2b7cf2e57982f78f729394f4f1c0cf4b

It's a bit yuck...

**Comment by ikeydoherty** [comment]
OK so with the change I'm pushing now, when the version of Mutter is higher than `3.21.0`, we'll then use the `rpath`:

```
 ikey@solus-bdw  ~/Projects/budgie-desktop   master ●  readelf -d wm/budgie-wm| grep rpath
 0x000000000000000f (RPATH)              Library rpath: [/usr/lib64/mutter]
 ikey@solus-bdw  ~/Projects/budgie-desktop   master ●  
```

Anything older, we'll deliberately not use it. Thanks a lot @mbiebl for finding these nuggets!

**Comment by ikeydoherty** [comment]
@fossfreedom worth adding this patch into the debian package maybe? Or even waiting for the next release, up to you

**Comment by fossfreedom** [comment]
Thanks ikey.  I'll try the patch and push this as an update. Many thanks.  Will let you know soon.

**Comment by ikeydoherty** [comment]
Cool, thanks :D

**Comment by mbiebl** [comment]
That should do the trick, yes. 
Our debian build checker (lintian) will most likely complain (rightfully so) that the budgie binary now has an embedded rpath, but @fossfreedom can override that lintian error.
Why rpaths are a bad idea in general, see https://wiki.debian.org/RpathIssue

**Comment by ikeydoherty** [comment]
@mbiebl I build Solus, I know rpaths are evil :) GNOME are far too fond of them sadly. **glares at gedit**

**Comment by fossfreedom** [comment]
Has been accepted into Debian Sid.  Cheers Ikey.

**Comment by ikeydoherty** [comment]
Nice one, thanks
