### ISSUE TITLE
Mac Bootup slow with keyboard disabled.

### ISSUE THREAD

**Issue by Zafuzi** [solus-project/budgie-desktop#565]
When I start my mac I get the familiar efi prompt with a 4 second timer, however the timer runs very slow (like one second a minute) and I can't press enter or use the arrow keys. After it finally boots up (about 30 seconds later) the keyboard (but not the mouse) is disabled for a good minute.

This started a few weeks ago I believe after I tried reinstalling macOS to a separate partition, which didn't work because I installed Solus over the recovery partition. I don't really care about macOS, I just wanted to have both for some apps I used.

After that I noticed the boot up problem.  I'm not very knowledgeable in this department; but, I think it has something to do with the difference between boot managers. I think macOS is trying to boot up and then Solus "takes over". My other theory is that it has something to do with acpi settings in the kernel, so maybe I should try setting a bootflag or something?

**Comment by ikeydoherty** [comment]
Sorry I can't see what this has to do with Budgie Desktop. If this is a Solus issue, please report to https://dev.solus-project.com

**Comment by Zafuzi** [comment]
Sorry thought this covered both. Now I realize that budgie is a separate project.

**Comment by ikeydoherty** [comment]
Yeah sorry we try to keep them separate so that they get the proper attention. Core Team monitors dev.solus-project.com, I deal with here :D
