### ISSUE TITLE
Panel taskbar not recognizing chrome apps

### ISSUE THREAD

**Issue by Redneckita** [solus-project/budgie-desktop#566]
Hello, i'm facing a strange issue with the taskbar:

- Before yesterday update the taskbar looks ok, Chrome has it's own icon and webapps too are pinned. Regardless which i have opened first, every webapp (or Chrome windows) has it's own working button:
![before](https://cloud.githubusercontent.com/assets/12221659/18367318/e52e6432-761a-11e6-9012-b50dc21e54eb.png)

- After yesterday update, if i launch any of the webapp (you can get the same from the terminal by running
`google-chrome --app=URL` 
and Chrome start a windows with the url given, with no toolbar) then the webapp favicon takes the place of the Chrome launcher itself:
![after_only_chrome](https://cloud.githubusercontent.com/assets/12221659/18367472/97664778-761b-11e6-8d04-02ac81e9ac6c.png)
Launching inbox:
![after_substitution](https://cloud.githubusercontent.com/assets/12221659/18367368/10d9e07a-761b-11e6-8599-ebb9816c5ddd.png)

- However, if i first launch Chrome then the webapp, it looks ok, it has it's own favicon as a button and i can click them to minimize it, but i can no longer pin to the panel:
![after_looks_ok](https://cloud.githubusercontent.com/assets/12221659/18367492/b66b240e-761b-11e6-80dc-9ecd10819b78.png)

I first tried to get in touch with the [Budgie Remix](https://github.com/budgie-remix/budgie-desktop-environment/issues/27) package maintainers but it looks like they've not changed anything, nor did Google Chrome because plank correctly recognize Chrome Apps. Plus, resetting the panel did not help at all (that's more less what we have been tried so far)

Since i use a lot of Chrome apps for my various tasks this is making me sick, anyone having the same issue? Any help appreciated, thanks in advance

**Comment by ikeydoherty** [comment]
> Before yesterday update

Update of what?

**Comment by Redneckita** [comment]
I use Budgie Remix, and Ubuntu asked me to accept the update. Ence i asked fossfreedom first... But he sent me here

**Comment by ikeydoherty** [comment]
> hmm - not sure. Launch "plank" - and copy the desktop shortcut into the plank launcher. Does this work correctly?

..What has Plank to got to do with it.. ?  I'll get latest Chrome on later and see how things look in git. We're prepping for a 10.2.7 so I'll try to squeeze it in

**Comment by Redneckita** [comment]
> ..What has Plank to got to do with it.. ? I'll get latest Chrome on later and see how things look in git. We're prepping for a 10.2.7 so I'll try to squeeze it in 

We were thinking it could be Chrome's fault but in Plank they keep their behaviour... It was a check i guess, the .desktop window class is recognized that way.
Anyway, thanks for looking into it.

**Comment by ikeydoherty** [comment]
Plank uses BAMF so its not a good test

**Comment by ikeydoherty** [comment]
I'm moving this to the next milestone as I don't know what Ubuntu configuration or updates were part of this change. I suspect it has more to do with Google Chrome itself breaking things.

**Comment by fossfreedom** [comment]
Ikey - agreed - given that the OP mentioned everything was working OK prior to the very latest chrome package update in the last few days, looks like Chrome itself is the "culprit".

**Comment by ikeydoherty** [comment]
For me Google Drive is now opening in the existing Chrome window .. :/

**Comment by Redneckita** [comment]
> For me Google Drive is now opening in the existing Chrome window .. :/

So it doesn't have it's own window even though you have created the shortcut? (the .desktop file)?
Looks like the taskbar messed up steam windows too... Steam has 3 icon: main window, chat window and friend list window. When i start Steam, the pinned icon is the main window, now i don't know why, the pinned icon is the chat window and the unpinned one is the main windows. 
Also budgie panel is crashing a lot, maybe there's something behind?

**Comment by fossfreedom** [comment]
hmm - budgie-panel shouldnt be crashing @Redneckita... however if you notice budgie-panel crashing due to installing/removing apps and/or updating the system (which effectively does the same install stuff) then this is your issue - https://github.com/solus-project/budgie-desktop/issues/527

**Comment by ikeydoherty** [comment]
I find it odd we don't get this in Solus but you do in Ubuntu. Is your gnome-menus package up to date?

**Comment by Redneckita** [comment]
It didn't crash gnome-session @fossfreedom , it just started crashing after the update.

@ikeydoherty 

```
sudo apt-get install gnome-menus 
gnome-menus is already the newest version (3.13.3-6ubuntu3.1).
```

**Comment by ikeydoherty** [comment]
I meant in Ubuntu in general, not your system, lol. 3.13.3 is what we're using too.

**Comment by fossfreedom** [comment]
yeah - 3.13.3 is the ubuntu repo version http://packages.ubuntu.com/xenial/gnome-menus

**Comment by Redneckita** [comment]
> I meant in Ubuntu in general, not your system, lol. 3.13.3 is what we're using too.

Err, sorrry... didn't understood <.<

So on your system Drive has it's own window?

**Comment by ikeydoherty** [comment]
Gonna wrap the reloading check in a semaphore and see if that helps

**Comment by Redneckita** [comment]
I was trying to remove and reinstall budgie-panel but looks like it's not a separate application, and i'm not sure if i dare enough to purge the whole DE...

I do hope it's not Chrome fault. I use a lot the webapps...

**Comment by ikeydoherty** [comment]
Not sure what you think that will help with. :)

**Comment by Redneckita** [comment]
> Not sure what you think that will help with. :)

Don't know, thought a fresh install can help.
About the previous (updated) post?

**Comment by ikeydoherty** [comment]
OK so I can get the "Enjoy Music Player" to open as a separate window, and yeah, its not pinning.

**sets about concocting magic**

**Comment by ikeydoherty** [comment]
Self documenting time...

```
WM_WINDOW_ROLE(STRING) = "app"
WM_CLASS(STRING) = "crx_hncfgilfeieogcpghjnnhddghgdjbekl", "google-chrome"
```

Found in:

```
chrome-hncfgilfeieogcpghjnnhddghgdjbekl-Default.desktop StartupWMClass=crx_hncfgilfeieogcpghjnnhddghgdjbekl
```

**Comment by Redneckita** [comment]
> OK so I can get the "Enjoy Music Player" to open as a separate window, and yeah, its not pinning.
> 
> sets about concocting magic

This happen when you have Chrome open right? Please try and pin Chrome, but leave it closed and launch "Enjoy Music Player" to see if it the pinned Chrome switch to that

**Comment by ikeydoherty** [comment]
For me it just opens a new Chrome window

**Comment by ikeydoherty** [comment]
Yeah ok - so the applet is detecting "google-chrome.desktop" before checking with the StartupWMClass

**Comment by Redneckita** [comment]
> Yeah ok - so the applet is detecting "google-chrome.desktop" before checking with the StartupWMClass

But it worked until now. So have you nailed the issue?

**Comment by ikeydoherty** [comment]
Nearly. Gimme a minute

**Comment by ikeydoherty** [comment]
MK so the icon-tasklist does encounter the ID:

```
** Message: AppSystem.vala:80: Inserted crx_hncfgilfeieogcpghjnnhddghgdjbekl as chrome-hncfgilfeieogcpghjnnhddghgdjbekl-Default.desktop
```

It's just not selecting it. Homing in ....

**Comment by ikeydoherty** [comment]
More weird-style debugging:

```
** Message: AppSystem.vala:107: Found crx_hncfgilfeieogcpghjnnhddghgdjbekl in startupids!
** Message: AppSystem.vala:113: So I found crx_hncfgilfeieogcpghjnnhddghgdjbekl but its not in desktops
```

**Comment by ikeydoherty** [comment]
Lol.. Fixed in git now. Sorry :D

**Comment by ikeydoherty** [comment]
Moved it back to 10.2.7. What a rollercoaster.. :P

**Comment by Redneckita** [comment]
Thanks!!! You're the man! So the next update will fix it right? Can't wait for @fossfreedom to update the packages!

**Comment by ikeydoherty** [comment]
It'll be part of the `10.2.7` release yeah. Currently deciding if we're gonna ship the xsettings manager in this release or wait for the next one

**Comment by Redneckita** [comment]
Amazing, great support and great work on the DE! Long live and prosper Solus and Budgie!

**Comment by ikeydoherty** [comment]
Cheers :)
