### ISSUE TITLE
Pinned Icons are too small after login

### ISSUE THREAD

**Issue by taaem** [solus-project/budgie-desktop#572]
When I restart my PC and login all Pinned icons are really small and not properly rendered.
Until I open them or go over them with my cursor.
If needed I can provide a Screenshot.

**Comment by mussel** [comment]
I also saw this issue while using the code from the master branch. I managed to fix it in PR #551 and if I remember correctly it was related to a missing *queue_resize* call. Perhaps I could try to backport the fix to master while aforementioned pull request is not merged.

**Comment by ikeydoherty** [comment]
Verified in Solus that d15acfa3af4ab31ec8a80129514265b56897fd0d fixed this issue. Recommending distributors of 10.2.7 merge the patch in their packaging.

**Comment by ikeydoherty** [comment]
https://github.com/solus-project/budgie-desktop/commit/d15acfa3af4ab31ec8a80129514265b56897fd0d.patch

**Comment by fossfreedom** [comment]
Will do. Thanks

On 11 Sep 2016 12:40, Ikey Doherty <notifications@github.com> wrote:

Closed #572<https://github.com/solus-project/budgie-desktop/issues/572>.
