### ISSUE TITLE
Raven Sidebar Control icon separates from button

### ISSUE THREAD

**Issue by drakovyrn** [solus-project/budgie-desktop#574]
![wtf](https://cloud.githubusercontent.com/assets/22121493/18412948/087161be-7761-11e6-91e0-40c794137f5d.png)

This happened after removing Raven Sidebar Control from the panel and adding it back. The button is in the right place, and can be clicked open and closed as usual, but the icon and icon animation appears on the left side.

**Comment by ikeydoherty** [comment]
cc: @cybre @fossfreedom: c21429274d4b2f6f9e14b57316635df04c114127

When this change is released it will require rebuilds of haste-applet and screenshot-applet.

Issue is resolved with this change.
