### ISSUE TITLE
"Pin to panel" do not appear in the Web browser Pale Moon

### ISSUE THREAD

**Issue by fu-sen** [solus-project/budgie-desktop#575]
Web browser Pale Moon can be installed to Solus using a dedicated Linux installer (pminstaller).
http://www.palemoon.org/
http://linux.palemoon.org/

but the item of "Pin to panel" to the right-click menu of Pale Moon icon does not exist.

![screenshot from 2016-09-11 10-36-28](https://cloud.githubusercontent.com/assets/5434159/18414635/ec5413bc-780c-11e6-874e-52b2b818abf8.jpg)

The same problem can be reproduced even budgie-remix.
Therefore I was reported as a problem of Budgie.

**Comment by ikeydoherty** [comment]
What's the `xprop` output for the palemoon window? i.e. for google chrome:

```
WM_WINDOW_ROLE(STRING) = "browser"
WM_CLASS(STRING) = "google-chrome", "google-chrome"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
```

Those are the bits I'm interested in. Also I'd need to see a copy of the `.desktop` file along with its filename :)

**Comment by fu-sen** [comment]
Information that is probably sought would be this.

Select the Pale Moon window in xprop (Dare LOCALE remains of Japanese):
http://pastebin.com/juZXLcQt

palemoon.desktop:
http://pastebin.com/aTZj7qi3

**Comment by ikeydoherty** [comment]
So here's the issue:

```
WM_CLASS(STRING) = "Navigator", "Pale moon"
```

Would expect to have a "Pale moon.desktop" file.

**Comment by ikeydoherty** [comment]
^ That'll fix it, if you're up for testing.

**Comment by fu-sen** [comment]
Thanks for the quick fix. I will check it after obtaining a reflection of Budgie.

**Comment by fu-sen** [comment]
Perhaps this would have been reflected in the Solus?
If it than being reflected, not yet this problem is improving.

**Comment by ikeydoherty** [comment]
Its in the latest Solus updates yes

**Comment by ikeydoherty** [comment]
Fixed in git so closing this

**Comment by fu-sen** [comment]
No. I am a package to the latest, but not yet able to confirm the improvement of this work!

**Comment by ikeydoherty** [comment]
I mean the fix is in the git repo, I'm closing the issue because I'm about to send out `10.2.8` for Solus 1.2.1 :) Obviously if somehow the issue does creep back (Unlikely, tested it) you can re-open and slap me

**Comment by fu-sen** [comment]
I understood. I will check later this again in the Solus 1.2.1.

**Comment by fu-sen** [comment]
I was opened again this problem in #659 .

**Comment by cipricus** [comment]
I am having again the same problem in Solus 2017.01.01.0 64-bit
