### ISSUE TITLE
[enhancement] Horizontal volume slider

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#577]
Horizontal volume slider I think better than vertical.

<img src=http://i.imgur.com/AbzbMve.png>
<img src=http://i.imgur.com/zW3OVAz.png>

Also 
- remove "+" and "-" buttons. Raven volume slider doesn't have them.
- add % (0-100%) so you know exactly what the current volume is.

**Comment by ikeydoherty** [comment]
Looks  bad to me, personally. It also has no bearing on Raven. It's designed to be consistent with the media controls found throughout Budgie/Gtk/GNOME/Solus. It's to enhance usability, not just "look ok".
The only instance in which it would be rotated is with extra controls inside the window, now it just looks odd
