### ISSUE TITLE
Shadows no longer appear on leave dialogues after 10.7 update

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#581]
I remember there being shadows on leave dialogues to create contrast between it and the window or desktop underneath it. They seem to have disappeared. Not sure if I'm imagining though.

**Comment by ikeydoherty** [comment]
Ah bugger. Thx.

**Comment by tristan957** [comment]
No problemo.

**Comment by ikeydoherty** [comment]
OK update is in stable in Solus for this, log out and back in again. And the above ^ patch is the fix for it, for the curious observers :)

**Comment by tristan957** [comment]
Just ran upgrade and restarted. I did not notice a difference. I will retry in a an hour or so.
