### ISSUE TITLE
Under Compiz WM Raven offset position is not correct

### ISSUE THREAD

**Issue by nazar-pc** [solus-project/budgie-desktop#583]
Raven is opened at some distance from the right edge, video demo: https://owncloud.mokrynskyi.com/index.php/s/4fbg1slr6r9nO6P
I know this is not a primary environment, but hopefully you can fix this.
Ubuntu 16.10 x64, Compiz as of today (no Unity, just custom Compiz session), `libraven0` package of version `10.2.7-0ubuntu4~yakketyubuntu1`.

**Comment by ikeydoherty** [comment]
Budgie doesn't support third party window managers, I'm not sure what you're trying to accomplish here.

**Comment by nazar-pc** [comment]
I'm asking whether you can run Compiz on Ubuntu (since you already have Ubuntu Budgie-Remix, it is just a matter of installing one package) and take a look if there is a simple fix for this issue.
I'm not satisfied with complete desktop environments available, so I have own custom pack of tools from different projects. Budgie panel mostly works fine (really thank you for this! some other solutions are hadcoded for particular DE), but there are some minor issues like this one which would be nice to fix.

**Comment by ikeydoherty** [comment]
I think you've got it twisted. Ubuntu Budgie Remix is an Ubuntu-based distribution that chose to adopt Budgie as their default desktop environment. Budgie Desktop is a *Solus* project, part of the Solus operating system and our flagship desktop. https://solus-project.com/

It's an independent Linux distribution and hasn't got anything to do with Ubuntu, so there's no packages for us to add. :p 

Budgie WM contains *key integration points* for the Budgie Desktop, including wallpapers, keyboard layout, shortcuts, etc, that are required for a fully functional Budgie Desktop installation.

**Comment by nazar-pc** [comment]
I know it. But my issue is about Budgie Desktop component Raven. I understand that it is positioned perfectly under bugdie-wm even on Ubuntu, so my issue might not be relevant for upstream developers, but there is a hope that this is not a major issue and might be fixed for some users like me even though i doesn't benefit Budgie Desktop project itself.
I'm really sorry if this is completely irrelevant, I just didn't find better place to report this and didn't find any better panel to use.

**Comment by ikeydoherty** [comment]
It might be related to the window type Raven sets. I'll check during the week if I can reproduce this under lighter window managers. In short I have no intention of running Ubuntu and much less in providing Compiz in Solus. Historically many of our crazy-shit bugs have been due to something Ubuntu-specific which is why I originally stopped supporting them before Budgie 10. Luckily things have been improving on that front.

We'll keep this open for now, because if Mutter is somehow masking something invalid we're doing, that's going to eat away at me. I also intend to drop Mutter at some point so it's energy I'd end up investing at some point regardless.

**Comment by ikeydoherty** [comment]
Fixed this a while back and it's in a release. Re-open if its still happening/relevant.

**Comment by nazar-pc** [comment]
If it is included in 10.2.8, then I'm already on it and it is still an issue.
Can I collect some additional info to understand what is wrong?

**Comment by ikeydoherty** [comment]
So I've tried this under Marco and Mutter and the issue isn't present there, so it's obviously some kind of derp within Compiz. I'd advise checking your settings at this point. Chalking it up as another Ubuntu specific bug

**Comment by nazar-pc** [comment]
I've installed Compiz in VM on Ubuntu Budgie Remix (16.04).
The only thing Compiz prints is exactly 2 lines each time I open Raven:
```
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
```
Interestingly, Raven opens correctly after replacing budgie-wm with Compiz until I also restart budgie-panel.

Tried Openbox and Metacity - in both of them works correctly.

**Comment by nazar-pc** [comment]
Compiz with debug output:
```
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (decor) - Warn: No default decoration found, placement will not be correct
compiz (core) - Debug: pending request:
compiz (core) - Debug: - event serial: 50126
compiz (core) - Debug: - event window 0x2401c86
compiz (core) - Debug: - x: 1571 y: 34 width: 317 height: 964 border: 123733739, sibling: 0x2401184
compiz (core) - Debug: refusing to manage window 0x2401c86
compiz (core) - Debug: received event:
compiz (core) - Debug: - event serial: 50126
compiz (core) - Debug: - event window 0x2401c86
compiz (core) - Debug: - x: 1571 y: 34 width: 317 height: 964 border: 123733739, sibling: 0x2401184
compiz (core) - Debug: pending request:
compiz (core) - Debug: - event serial: 50417
compiz (core) - Debug: - event window 0x2401c86
compiz (core) - Debug: - x: 1254 y: 34 width: 317 height: 964 border: 123733739, sibling: 0x2401184
compiz (core) - Debug: received event:
compiz (core) - Debug: - event serial: 50417
compiz (core) - Debug: - event window 0x2401c86
compiz (core) - Debug: - x: 1254 y: 34 width: 317 height: 964 border: 123733739, sibling: 0x2401184
compiz (core) - Debug: stacks are out of sync
```

**Comment by ikeydoherty** [comment]
It shouldn't be trying to decorate the window. It explicitly requests to _not_ be decorated.

**Comment by nazar-pc** [comment]
I've never written anything in Vala (as I never wrote anything useful in C or with GTK), but I decided to hack on it a bit and I found something.

[This line](https://github.com/solus-project/budgie-desktop/blob/37ad1c84dfc7460fa9f92b680ee077da129fd3cc/src/raven/raven.vala#L412) computes incorrect X coordinate:
* `rect.x` is apparently `0` because it doesn't affect anything
* `rect.width` is the correct offset in my case
* `width` (which is `required_size`) is the one that moves Raven from the edge (if I remove it everything is positioned correctly)

What are `react.width` and `required_size`?

**Comment by ikeydoherty** [comment]
It's the screen geometry, i.e. the primary monitor. So while on monitor 0, `rect.x` is 0, on a dual-display full HD setup, `rect.x` could be 1921.

`required_size` is our required (compact) width

**Comment by ikeydoherty** [comment]
Thus... `rect.x+rect.width` is the X coordinate at the very end of the current screen, so removing our `required_size` (`width`) from it gives us the X coordinate for the panel to start at.

**Comment by nazar-pc** [comment]
Is there anything like reference point? If `rect` is monitor dimensions, then in Compiz `x` represents right corner, while under other WMs it is left corner.

**Comment by nazar-pc** [comment]
And here is the answer: https://github.com/solus-project/budgie-desktop/blob/37ad1c84dfc7460fa9f92b680ee077da129fd3cc/src/raven/raven.vala#L342
Maybe other WMs just ignore this (as I found in GTK docs)?
