### ISSUE TITLE
"Pin to Panel" not available on Krita

### ISSUE THREAD

**Issue by gui-milky** [solus-project/budgie-desktop#586]
On Budgie Desktop, Krita can't be pinned to panel
It was installed from the Software Center
![screenshot from 2016-09-13 10-19-38](https://cloud.githubusercontent.com/assets/22163948/18460970/e9318b2a-799b-11e6-975d-6ad9ff393822.png)
------------------------------------------------------
Tell me if something was missing in report
Thanks you (^_^)

**Comment by ikeydoherty** [comment]
THIS one is Krita. >_>
..

OK Krita confirmed working with git build of Budgie - 10.2.8 will solve this
