### ISSUE TITLE
"Pin to Panel" not available on Corebird

### ISSUE THREAD

**Issue by darkben** [solus-project/budgie-desktop#587]
![corebird](https://cloud.githubusercontent.com/assets/1212820/18464978/797de604-7994-11e6-91a9-fe1a5ce4b492.jpg)

Solus : 1.2.0.5
Budgie : 10.2.7

**Comment by ikeydoherty** [comment]
OK Krita confirmed working with git build of Budgie - 10.2.8 will solve this

**Comment by ikeydoherty** [comment]
Clicked wrong one. Shush :P

**Comment by ikeydoherty** [comment]
OK Corebird confirmed working with git build of Budgie - 10.2.8 will solve this

XD
