### ISSUE TITLE
Add startup application in settings

### ISSUE THREAD

**Issue by poltertec** [solus-project/budgie-desktop#592]
Could have overlooked, didn't find it within requests yet.

Would be nice if it was possible to add startup applications from the General Budgie Settings page in raven (example plank).
Would be one less reason to use gnome tweak tool :).

**Comment by ikeydoherty** [comment]
Ideally we need a new app for this as opposed to inside Raven (Horizontal constraints) but yeah, definitely need it

**Comment by ryukinix** [comment]
This will really usefull. I don't understand which the directory path the budgie get to handle the startup applications? In most cases of DE would be `~/.config/autostart` (just like xfce4). 

By other hand, I have some problems using a distro with budgie and xfce4 together. I just don't undestand that very well. We have a special location, only for budige, to put the *.desktop files to startup on login?

**Comment by ikeydoherty** [comment]
Budgie's session is GNOME Session. It uses standard XDG paths. If you want something to only start under Budgie, then use `OnlyShowIn=Budgie;`

**Comment by ryukinix** [comment]
Thanks!

**Comment by quesada** [comment]
+1

**Comment by ikeydoherty** [comment]
Note I will automatically remove all "+1" "me too" comments from hereon out, it makes the conversation difficult to follow. Please show support for issues by using the emoji thumbs up link on the first post in each bug.

**Comment by JoshStrobl** [comment]
Adding apps to autostart has long since been supported in Budgie, this just wasn't appropriately tracked and closed back then, doing so now.
