### ISSUE TITLE
Arch Linux Build Error (budgie-desktop-git)

### ISSUE THREAD

**Issue by Snisser** [solus-project/budgie-desktop#596]

**Comment by feskyde** [comment]
What error?

**Comment by Snisser** [comment]
Error:

==> Beginne pkgver()...
==> Aktualisierte Version: budgie-desktop-git v10.2.7.r6.g6eec2eb-1
==> Beginne build()...
+ Setting up submodules
Submodul 'gvc' (https://git.gnome.org/browse/libgnome-volume-control) 
für Pfad 'gvc' in die Konfiguration eingetragen.
Klone nach 
'/tmp/yaourt-tmp-jannik/aur-budgie-desktop-git/src/budgie-desktop-git/gvc' 
...
Submodul-Pfad: 'gvc': '7e5504db3d85b7a4b5dc0207c47af09b426ad75a' 
ausgecheckt
You should add the contents of '/usr/share/aclocal/intltool.m4' to 
'aclocal.m4'.
./autogen.sh: Zeile 25: gtkdocize: Kommando nicht gefunden.

**Comment by feskyde** [comment]
Install gtk-doc, the AUR package is missing some dependencies

**Comment by ikeydoherty** [comment]
Please provide errors using `LANG=C LC_ALL=C` - otherwise they're no good to me.

**Comment by Snisser** [comment]
Installed gtk-doc and the installation was sucessfull! Thanks for the (fast) help! :)

@ikeydoherty Sorry, will do next time :s

**Comment by ikeydoherty** [comment]
@Snisser you weren't to know, there's no documentation here on creating issues, totally my fault.

Writing one now, sorry

**Comment by Snisser** [comment]
All good, all good :)

Okay, do that :D You guys are awesome, thanks for the support :+1:

**Comment by ikeydoherty** [comment]
Oh if we can get the maintainer of `budgie-desktop-git` to update the PKGBUILD that'd be *amazing*. :D Someone please poke xD
