### ISSUE TITLE
OSD offcenter after second time shown

### ISSUE THREAD

**Issue by andresclari** [solus-project/budgie-desktop#597]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

```
Graphics:  Card: NVIDIA Device 13c2 bus-ID: 01:00.0
Display Server: X.Org 1.18.4 driver: nvidia
Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
GLX Renderer: GeForce GTX 970/PCIe/SSE2
GLX Version: 4.5.0 NVIDIA 352.79 Direct Rendering: Yes
```

Running a dual head setup, with config setup with NVIDIA Settings tool.
No extra settings in xorg.conf.

System freshly updated and rebooted.

**The issue encountered**
Volume / brightness OSD offcenter after the second time shown.

**Steps to reproduce the issue**
Hit the volume keys to trigger the OSD for volume. Notice the first time it shows ok, the second / third time and following it will show offcentered. 

It actually looks like the edge of it it's on the center of the display, instead of the center of the OSD itself.

![screenshot](https://cloud.githubusercontent.com/assets/74197/18570832/8a44cb04-7bad-11e6-96bc-3476610cd32d.jpg)

**Comment by ikeydoherty** [comment]
Just resynced git into Shannon: https://git.solus-project.com/packages/budgie-desktop/commit/?h=budgie-desktop-10.2.7-99

Would you be able to test the latest update (logout+back in) and see if you're still experiencing this?
It should be addressed by f0933cc6560869b72a808896fb69789b2b38c241

**Comment by andresclari** [comment]
Alright, that seems to fix it, thanks!

However, looking at it a more closely, it looks like it's off to the right by about 1cm, that being default position, not being drunk positioning anymore.

I can confirm this on both desktop / laptop.

**Comment by diazbastian** [comment]
I was having the same problem with my integrated GPU Intel. After recompiling the latest version Budgie everything seems fine.

Before
![osd-bad](https://cloud.githubusercontent.com/assets/5126124/18572229/c4c76a2a-7b8f-11e6-8b86-771fec3f4ad4.png)

After
![osd-ok](https://cloud.githubusercontent.com/assets/5126124/18572234/cf77336a-7b8f-11e6-9da2-c40a9b1df4a3.png)

**Comment by ikeydoherty** [comment]
OK well I'm gonna close this, thanks for testing :) I'll make further refinements when it goes to C
