### ISSUE TITLE
Desktop icons are not displayed with the panel to extend desktop (multimonitor setup)

### ISSUE THREAD

**Issue by diazbastian** [solus-project/budgie-desktop#600]
**Operating System**: Fedora 24 64 bits
**Budgie version**: Budgie f0933cc6560869b72a808896fb69789b2b38c241

**The issue encountered**
In a multimonitor setup, to reorganize the secondary monitor above, on the left or below, the desktop icons is shown in secondary monitor, instead of staying with the panel on the primary monitor.

![1](https://cloud.githubusercontent.com/assets/5126124/18604035/04b6eb56-7c4e-11e6-8e7b-9ec2ae132212.png)

Only the default configuration extending the monitor on the right, meets this rule.

![2](https://cloud.githubusercontent.com/assets/5126124/18604036/0ccbdeb4-7c4e-11e6-9b10-408d94c6b0f6.png)

**Steps to reproduce the issue**

1. Activate desktop icons in Raven
2. Connect an extra external monitor
3. Go to screen options and select "extend monitor" (default)
4. Then organize the secondary monitor "up", "left" or "below" of the primary monitor

**Expected results**
Always keep the panel together desktop icons on the primary monitor when using a multimonitor setup.

**Comment by ikeydoherty** [comment]
Budgie doesn't provide the desktop icons, your file manager does, i.e. Nautilus, Nemo, Caja, etc.
Unfortunately there's no way for us to fix this as its an upstream issue with your file manager

**Comment by diazbastian** [comment]
@ikeydoherty Sorry I return to this issue but I want to ask you something. It is important desktop icons for Solus OS/Budgie Desktop user experience?

By default they are not activated, but Budgie helps recall a classic desktop experience using of modern technology. In conversations with some GNOME devs, there is little interest (in truth it is anything of interest) in resolving bugs or add new features, so they said to me in a "politically correct" way to avoid writing reports related, at least I did I care for them or pay someone to solve, as they are in maintenance and have no future plans for that feature.

I'm not saying that you or someone else take care of this, just mention a couple of errors in this feature will continue to affect users indefinitely.

I'll see how that of bountysource works...
