### ISSUE TITLE
Cannot login to budgie desktop 

### ISSUE THREAD

**Issue by swarnendubiswas** [solus-project/budgie-desktop#608]
**Operating System**: e.g. Ubuntu Gnome 16.04, with Gnome 3.20
**Budgie version**: i.e. Budgie 10.2.7 

**The issue encountered**
I built Budgie desktop on my Ubuntu Gnome environment. On the gdm login, I select Budge as the preferred desktop session. However, the session does not start, and the returns to the gdm login screen.
 ...

**Steps to reproduce the issue**
I am not sure whether something is messed up with my previous Budgie builds, but here are the steps.
1) Build Budgie on Ubuntu Gnome 16.04 with gnome 3.20.
2) Reboot and select Budgie on the gdm login screen. 

 ...

I have used Budgie before and it worked. This problem has arisen since the Budgie 10.2.7 release. I am currently using the git tip for building. Any suggestions as to what could be going wrong is appreciated.

**Comment by ikeydoherty** [comment]
First step is making sure your old version is nuked and isn't conflicting with 10.2.7, they're not filepath compatible

**Comment by swarnendubiswas** [comment]
My current installation binaries were in /usr/bin/, while binaries from earlier releases were possibly in /usr/local/bin. I did `rm -rf budgie-*`. Where should I check for other possible installation paths?

**Comment by ikeydoherty** [comment]
Yeah /usr/lib/budgie-desktop or w/e the path is there too

**Comment by swarnendubiswas** [comment]
@ikeydoherty Thanks for the tip. I removed all budgie-related files from my system, and cloned the repo into a new directory and then followed the build instructions. But then I get the following error:
```
checking whether we are cross compiling... configure: error: in `/home/biswass/Documents/github/budgie-desktop':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

`config.log` has the following error entries:

```
configure:3509: $? = 0
configure:3498: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3509: $? = 1
configure:3498: gcc -qversion >&5
```
```
configure:3669: checking whether we are cross compiling
configure:3677: gcc -o conftest    conftest.c  >&5
conftest.c:11:19: fatal error: stdio.h: No such file or directory
compilation terminated.
```

**Comment by ikeydoherty** [comment]
No stdio.h? Sounds like a build dependency issue.

**Comment by swarnendubiswas** [comment]
Thanks for the tip, for some reason the `/usr/include` was empty. I reinstalled the dependencies and built Budgie. Before that, I searched for all Budgie- and Raven-related files and had deleted them. But even after these steps, I continue to experience the original problem (session logs out immediately). Is there other binaries/libs that I need to remove?

**Comment by ikeydoherty** [comment]
Honestly I don't think this is a Budgie thing, you said you had a build of budgie from git, and then somehow all of your development tools were gone. Sounds very much like a distro issue. Or filesystem
issue. Please reopen if you feel this is still a Budgie issue.
