### ISSUE TITLE
Shutdown button on Raven only ask a logout confirmation

### ISSUE THREAD

**Issue by Redneckita** [solus-project/budgie-desktop#609]
**Operating System**: Budgie Remix 16.04.1
**Budgie version**: Budgie 10.2.7 

**The issue encountered**

Clicking the shutdown button on Raven displays a window to "cancel" or "logout" instead of the old options to shutdown, reboot, standby or cancel; I don't know if this is the expected behiaviour with the new User Indicator applet though. 
The old dialog or a shutdown confirm would fit the button better imho.

**Steps to reproduce the issue**

Click the shutdown button on raven and budgie ask "are you sure you want to logout? no/yes"

**Comment by ikeydoherty** [comment]
Yeah currently an issue due to use using `gnome-session`.. Want to get this fixed. :/
Unfortunately the gnome-session d-bus API is .. limited.

**Comment by Redneckita** [comment]
Glad to hear is being worked on! I logout every time i want to shutdown since 10.2.7 :'D

**Comment by Doums** [comment]
Hello,

I'am running under manjaro and I have the same problem after my update today. Also the icon for raven sidebar button is a "?" because it didn't find the corresponding icon, I think or something like that.
My icon theme is Vertex-Maia

**Comment by X0rg** [comment]
Same problem. My icon theme is Faenza.

**Comment by fossfreedom** [comment]
@Doums and @X0rg 

  I would suggest you raise  the raven trigger icon issue as a separate issue

**Comment by jelle619** [comment]
Any updates on this? Still encountering this issue. Raven would be pretty much perfect in my opinion if this issue would be fixed. :D

**Comment by JoshStrobl** [comment]
Closing as wontfix as the plan is to deprecate the power strip in Budgie 11, with it already being disabled / off by default. The Shutdown prompt displays accurate information via the User Indicator.
