### ISSUE TITLE
Bottom panel - menu appears at the top

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#612]
Bottom panel - menu appears at the top

![Alt Text](http://i.imgur.com/QhsFf0E.gif)   

![Alt Text](http://i.imgur.com/geRRaVd.gif)

**Operating System**:  Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

**Comment by fossfreedom** [comment]
duplicate of this https://github.com/solus-project/budgie-desktop/issues/292

**Comment by ikeydoherty** [comment]
Please check existing issues before opening a new one.
