### ISSUE TITLE
 Add a way to change the position of notifications

### ISSUE THREAD

**Issue by diazbastian** [solus-project/budgie-desktop#613]
**Operating System**: fedora 24 64 bit
**Budgie version**: Budgie 10.2.7

**The issue encountered**
There is no way to change the position of notifications

**Steps to reproduce the issue**
mmm... Change the default position Budgie panel in the "panel" tab on Raven.

**Current result**
Although the panel is bottom, notifications continue to appear in the upper right corner

**Expected result**
Notifications are displayed alongside to the main panel (lower right corner when the panel is bottom) or add options in Raven to change position of notifications

**Comment by sstallion** [comment]
Would it be possible to make this configurable? Ideally I'd like to have the opposite behavior (though it needn't be a default): my main panel is on the bottom, but I would prefer that notifications be in the upper right corner.
