### ISSUE TITLE
[Feature Request] Option to disable Arc theme transparencies

### ISSUE THREAD

**Issue by andresclari** [solus-project/budgie-desktop#618]
While some like transparencies everywhere, some people including people with disabilities might not want them. Specially in places like the Files sidebar, where they turn into an usability problem.

We should provide an accessible enough option to disable them, ergo, not via the Tweak tool, but rather in Raven on the theme settings.

Given that users might use a different theme all together, ideally the implementation would:

- Detect if using the Arc theme and have a precompiled Arc variant with --without-transparency option
- If the selected theme is Arc, show a check box "Disable theme transparency"

**Comment by Solarunit** [comment]
> I wish that default built in theme has such an option, so you don't need to install third party theme in order to make panel non-transparent.

https://solus-project.com/forums/viewtopic.php?f=8&t=1811

**Comment by ikeydoherty** [comment]
Doesn't make sense to me. The non-transparent version should just follow a different theme name, which you could select from Raven. I don't really see that Budgie itself for cater for theme internals

**Comment by andresclari** [comment]
Well, if you wanna add to the default install a version of the theme without transparency, that's cool. I wrote the feature this way, because if Arc, is gonna be thought as the main theme of Solus, and assume most people won't change it, then it should be fully integrated throughout.

If that is not the case, indeed, we just need to package the theme without transparency.

**Comment by ikeydoherty** [comment]
Gonna close this as it's not a Budgie issue, its a what-theme-do-you-use issues
