### ISSUE TITLE
Using a custom cursor from ~/.icons shows now cursor in Raven

### ISSUE THREAD

**Issue by andresclari** [solus-project/budgie-desktop#619]
**Operating System**:   Solus 1.2.0.5
**Budgie version**:  Budgie 10.2.7-99

**The issue encountered**
Using a custom cursor theme located in the user ".icons" folder results in Raven not showing anything in the cursor selection popup.

**Steps to reproduce the issue**
Install a custom cursor theme in ~/.icons  and select it via Tweak Tool.
Observe no cursor in Raven theme settings.

**Expected behavior**
Besides Raven being able to see cursor themes from ~/.icons, at least it should show that a different cursor is selected instead of being blank.

**Comment by ikeydoherty** [comment]
Note you should be using `~/.local/share/icons` by now. I'll add it anyway.
