### ISSUE TITLE
Logout/shutdown dialogue from Raven provides only logout option

### ISSUE THREAD

**Issue by yarpus** [solus-project/budgie-desktop#621]
Operating System:Solus 1.2.0.5 64-bit
Budgie version: 10.2.7

The issue encountered
Previously when I entered Power button in Raven panel I was asked if I want to shutdown/restart/logout from my session. 
Then I performed an upgrade (which bumped Kernel, Firefox -- but nothing from Budgie I believe).
Currently I'm just asked about logging out. To actually shutdown my PC I have to first log out and then shutdown from login screen.

Steps to reproduce the issue
Update/upgrade packages. Check behavior of Power button in Raven.

I have only single user with administrative rights.

**Comment by fossfreedom** [comment]
Duplicate of this: https://github.com/solus-project/budgie-desktop/issues/609

**Comment by ikeydoherty** [comment]
Closing, per @fossfreedom's observation
