### ISSUE TITLE
breeze-snow the only option in Raven

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/budgie-desktop#623]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

The mouse cursor option only shows the default breeze-snow theme, while the Tweak tool shows Adwaita and Mate (if installed) as well. 

 ...

Install the GNOME Tweak tool and compare the options with those in Raven.

 ...

**Comment by Snisser** [comment]
Does the problem persist even after rebooting? Experiencing the same issue sometimes, but after a reboot, everything is "fixed".

**Comment by ikeydoherty** [comment]
Yeh this is genuinely a Budgie issue. Raven thinks that Adwaita should be ignored because its an icon theme.. bad filtering
