### ISSUE TITLE
Show Desktop icon on the desktop

### ISSUE THREAD

**Issue by eephyne** [solus-project/budgie-desktop#628]
Arch linux
Budgie 10.2.6

I can't achieve to show desktop icon on the desktop, using gnome-tweak-tool, the option don't do anything
I don't know if this is a normal behavior (if it is, why that ?), or just me.

**Comment by Malmz** [comment]
Using budgie 10.2.7 there is a option to show desktop icons in the raven panel. If I remember correctly it was there in 10.2.6 too. If it's not there, try updating budgie.

**Comment by eephyne** [comment]
Ok thats weird. On another computer (still 10.2.6) there is indeed this option but its missing in the first computer.
Is this option linked to another app/lib ? because Its a really fresh install of arch and there is maybe missing elements

**Comment by Malmz** [comment]
I think desktop icons are handled by Nautilus.

**Comment by Snisser** [comment]
Can't confirm. Using Arch Linux myself and tried the [Budgie-Desktop](https://www.archlinux.org/packages/community/x86_64/budgie-desktop/), aswell as the [Budgie-Desktop-Git](https://aur.archlinux.org/packages/budgie-desktop-git/) Package. On both versions it works flawlessly, either with the **Raven implementation**, as well as with the **Gnome-Tweak-Tool**.

Maybe try these steps:
Navigate to Gnome-Tweak-Tool and Disable Desktop Icons

    $ killall -r nautilus

Enable Desktop Icons.

**Comment by ikeydoherty** [comment]
> Ok thats weird. On another computer (still 10.2.6) there is indeed this option but its missing in the first computer.

See: https://github.com/solus-project/budgie-desktop/blob/master/raven/settings_view.vala#L963

```vala
        if (Environment.find_program_in_path("nautilus") != null) {
````

You need to have Nautilus installed and present before Budgie starts up for the option to be present in Raven.

**Comment by ikeydoherty** [comment]
Closing this as it's a Nautilus issue not a Budgie issue

**Comment by haoyet** [comment]
Since you are on Arch linux, I suggest you install `nautilus-legacy` from AUR and install gnome-tweaks, then you will be able to find Show desktop icons option in gnome Tweaks app.

Hope this helps you!
