### ISSUE TITLE
Menu and applets startup animation when panel is at bottom

### ISSUE THREAD

**Issue by supernova86** [solus-project/budgie-desktop#640]
When the panel is at the bottom of the screen, many times the menu and applets start for a split second like the panel would be at the top then they jump to where they should. I think a hardware/driver issue is out of the question as I tested AMD and Nvidia GPU. Sound more like a GTK/Gnome 3+ issue were panel is stuck at the top and all menus and popups start in that portion of the screen.

Currently using Solus 1.2.0.5, Budgie 10.2.7 and Nvidia GT 730

**Comment by fossfreedom** [comment]
sounds the same as this issue - https://github.com/solus-project/budgie-desktop/issues/292

**Comment by ikeydoherty** [comment]
Is indeed a duplicate, thanks @fossfreedom
