### ISSUE TITLE
[Feature Request] Two or More Panels

### ISSUE THREAD

**Issue by Saroufim** [solus-project/budgie-desktop#65]
It would be nice to have different panels for different purposes. Allowing the user to add multiple panels would be a good move to achieve that.

**Comment by cuentawarra** [comment]
that would be sweet

**Comment by ikeydoherty** [comment]
It is doable, but I think this requires us to switch solely to GSettings to achieve this cleanly. How would we handle adding a new panel, the old GNOME 2 way?

**Comment by Saroufim** [comment]
Don't MATE, Cinnamon, and XFCE4 do it in pretty much the same way?

**Comment by ZetaHunter** [comment]
I'd rather have stability then extra panels.

**Comment by Saroufim** [comment]
Who says it has to be either this or that? New features can go hand in 
hand with stability. Stability without progress can only go so far.

**Comment by ZetaHunter** [comment]
Gonna believe that when panel stops freeze locking my system tyvm :P.
But yeah, this would be a nice feature.

**Comment by ikeydoherty** [comment]
@ZetaHunter thats the popovers, not the panels. Both areas need addressing. One thought is to use large panels that set an input shape, and do away with our popovers. Visually it would be identical,
but it would solve grab issues, the scrolling issues, stop freezing, and permit complex layouts, as well as multiple panels. I see no reason why we can't combine the goals into a logical and organised attempt at stabilising the panel.

**Comment by ikeydoherty** [comment]
Fixed in v10
