### ISSUE TITLE
[Arch] Gnome Update crashed my Budgie Desktop

### ISSUE THREAD

**Issue by Snisser** [solus-project/budgie-desktop#650]
Today i updated Gnome and restarted my systemd. Nothing worked in Budgie Desktop anymore, the Theme is crashed, Windows have no borders, cannot click anything, it's just a mess. What can i do to continue using Budgie Desktop?

OS = Arch Linux

Budgie = budgie-desktop-git (aur)

**Comment by Snisser** [comment]
Missed **gtk-doc**...

**Comment by ikeydoherty** [comment]
Lol weird, I didn't see the issue here but I randomly come across it on reddit xD

**Comment by Snisser** [comment]
Coincidence? I think not ;D
Have a nice day man :)

**Comment by ikeydoherty** [comment]
You too! ^^

**Comment by Snisser** [comment]
Hey Ikey, quick update btw, got the maintainer of the [budgie-desktop-git](https://aur.archlinux.org/packages/budgie-desktop-git/) package to add **gtk-doc** to it's dependencies :)

**Comment by ikeydoherty** [comment]
Awesome, thanks!
