### ISSUE TITLE
budgie-panel crashes after pressing Super when Raven is open

### ISSUE THREAD

**Issue by ishwon** [solus-project/budgie-desktop#651]
Operating System: Solus 1.2.0.5 64-bit
Budgie version: 10.2.7

...
budgie-panel crash
...

1. Open Transmission (v2.92)
2. Press Super + A to open Raven
3. While Raven still open press Super
4. Budgie panel crashes

Systemd journal logs the following:

> Oct 16 11:41:31 coffee-bar budgie-panel.desktop[4582]: (transmission-gtk:4714): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 16 11:41:31 coffee-bar budgie-wm.desktop[4569]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c00007 (Transmissi)
Oct 16 11:41:31 coffee-bar budgie-panel.desktop[4582]: (budgie-panel:4582): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
.
.
.
Oct 16 11:41:41 coffee-bar budgie-wm.desktop[4569]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1400007 (budgie-pan)
Oct 16 11:41:41 coffee-bar budgie-panel.desktop[4582]: (budgie-panel:4582): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

I restarted the panel issuing `budgie-panel --replace &` and could reproduce the issue with the steps above.

**Comment by ikeydoherty** [comment]
None of those messages indicate a crash. Is Raven accessible after this happens?

**Comment by ishwon** [comment]
Yes, Raven is still accessible but budgie-panel goes invisible. Issuing `budgie-panel` from the command line says:

> ** Message: manager.vala:997: Another panel is already running. Use --replace to replace it

**Comment by ikeydoherty** [comment]
Ya Raven is part of the Budgie Panel process. This is something we can't resolve until the rewrite, when we stop using GtkPopover and such.

**Comment by Snisser** [comment]
Having the same issue (sometimes). To "fix" it (for the moment), just open a Terminal and type:

    $ budgie-panel --replace &

And close the Terminal :)

**Comment by ikeydoherty** [comment]
Yeah bottom-panel placement is completely bollocksed with this version of Budgie. Due to us expanding a window to contain the GtkPopover, and the use of GdkGravity, our window gets shot off the edge of the screen into neverneverland. It's pretty much only resolvable by not using GtkPopover

**Comment by ishwon** [comment]
Okay, thanks =)
Will just 'replace' it when the bottom-panel goes off the screen. I guess we can close this issue as others stumbling on this page after looking for a solution will know what to expect next.
