### ISSUE TITLE
Raven slide-in/slide-out animation is jittery and works only for the default theme.

### ISSUE THREAD

**Issue by hersh-verthun** [solus-project/budgie-desktop#652]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

I have selected Adwaita as my "Widget Theme" in the Raven sidebar. With this selection when I open and close the Raven sidebar, the slide-in and slide-out animation is prefixed with a dark shadow.**
...

![raven_animation_bug](https://cloud.githubusercontent.com/assets/22866232/19416473/2aaa2ff8-93af-11e6-9dd3-c05d6c90f528.gif)

 ...

**Steps to reproduce the issue**
* Select Adwaita as the widget theme in the Raven sidebar
* Open/close the Raven sidebar

 ...

**Comment by ikeydoherty** [comment]
Not a bug - you've disabled the internal theme so nothing is overriding the styling. If you use a theme known to support Budgie you won't have this issue

 - Adapta
 - Paper
 - Vertex

All have solid Budgie support, and are in the Solus repos

**Comment by hersh-verthun** [comment]
I understand. Is there an official guide to creating themes for Budgie? I would like to customize Adwaita for better integration with Budgie.
