### ISSUE TITLE
The simplenote executable does not work - asks for "libxss.so.1" file.

### ISSUE THREAD

**Issue by hersh-verthun** [solus-project/budgie-desktop#653]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7
**The issue encountered**: Simplenote from Automattic provides a `tar.gz` for non-debian distros. I unarchived it and tried to run the executable from the command-line. It reported the following error:
```
error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory.
```
I contacted the support team at Automattic and this is their reply
...
![simplenote_not_executing_on_solusos](https://cloud.githubusercontent.com/assets/22866232/19416659/2b5900fa-93b4-11e6-8c35-7840f7954be0.png)
...
I searched for libXss1 package in the "Solus Software Center" and didn't find it. Kindly advise as to how I can install this package. I am still a novice Linux user. I switched to SolusOS from Ubuntu only three days ago.
 ...
**Steps to reproduce the issue**
1. Download the `tar.gz` for [Simplenote] (https://simplenote.com/)
2. Unarchive it
3. Open the unarchived folder in terminal
4. Run the executable

 ...

**Comment by ikeydoherty** [comment]
Sorry this isn't a Budgie Desktop issue. For future reference please use https://dev.solus-project.com

Your issue can be resolved by:

`sudo eopkg it libxscrnsaver`

Cheers :)

**Comment by hersh-verthun** [comment]
Thank you for responding.
That didn't resolve the issue though.

**Comment by ikeydoherty** [comment]
Then you must be missing another library. Use `ldd $binaryName` to find the missing lib

**Comment by hersh-verthun** [comment]
Yes you are right. Running `ldd ./Simplenote` listed a lot of missing libraries.
Shall I open a package request for Simplenote on Phabricator?
