### ISSUE TITLE
Can't pin audacious to panel

### ISSUE THREAD

**Issue by gnarlin** [solus-project/budgie-desktop#655]
**Operating System**: e.g. Solus 1.2.0.5
**Budgie version**: i.e. Budgie 10.2.7 OR specific git commit

**The issue encountered**
When I right click on the Audacious icon in the panel there is no option to pin it there.
 ...

**Steps to reproduce the issue**
Install Audacious, right click icon in panel after running it.

 ...

**Comment by ikeydoherty** [comment]
Please actually edit the OS and Budgie version fields so I know what you're using :)

**Comment by ikeydoherty** [comment]
This was resolved in 54104f3e2e42137f6f8a87a9ae8e5dd26caaad89

TL;DR On the *current* Budgie version you need to log out and back in. New Budgie will immediately recognise the new apps.
