### ISSUE TITLE
Unable to change the lock-screen wallpaper

### ISSUE THREAD

**Issue by hersh-verthun** [solus-project/budgie-desktop#656]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

**The issue encountered**
I chose a lock-screen wallpaper. It is not applied to the lock-screen when I first boot into the system. However, when I lock the screen after logging in, I find my selected wallpaper is applied.

**Steps to reproduce the issue**
1. Go to the 'Budgie menu'
2. Click on `System Settings` in the left partition
3. Click on `Background`
4. Click on `Lock Screen`
5. Select a desired wallpaper
6. Reboot and check if the selected wallpaper is visible at the time of login.

**Comment by Snisser** [comment]
I'm not sure if I misunderstand the problem or not, but the **Lock Screen** is not the **Login Screen**.

The Login Screen gets handled by the **Display Manager**, i assume you use either **Lightdm** or **GDM**. If you use **GDM**, you cannot change the Background. If you use **Lightdm** though, you can change it by customizing the /etc/lightdm/lightdm-gtk-greeter (if you use the **GTK-Greeter**) file.

**Comment by hersh-verthun** [comment]
Marvelous, your distinction is spot on.
Thank you.

**Comment by Snisser** [comment]
Perfect, i hope everything now works as you want!

I actually can't close the thread, I'm just a "spectator" if you wish, not actually a member of the project :)

I think you can close it yourself, though, so Ikey doesn't have to since it's solved anyways.

Have a nice day, cheers :)

**Comment by ikeydoherty** [comment]
Pop onto IRC I'll walk you through lightdm config :)

**Comment by hersh-verthun** [comment]
Thanks Ikey, I got it. I was able to change the login screen wallpaper based on @JannikHa 's reply.
