### ISSUE TITLE
Cannot open the '/' folder from the Places applet if it is bookmarked in Nautilus

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#660]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.8

**The issue encountered**
The new Places applet with Budgie 10.2.8 does not allow you to open the root "/" folder if it is bookmarked in Nautilus. Clicking the blank line in the Places applet where the root folder would be has no action.
 ...

**Steps to reproduce the issue**
Add the Places applet to the panel. Bookmark the root folder to the Nautilus sidebar. Open the places applet. And click the blank line that is displayed.
 ...

**Comment by JannikHa** [comment]
Sorry, do you mean the **/** directory or the actual Root directory **/root**?

If you mean the **/root** directory, you cannot open it because you simply don't have the permission to do so.

**Comment by tristan957** [comment]
According to this website (http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/the-root-directory.html) the / directory is the root directory while /root is the root home directory. But to clear things up, I do mean the /.

**Comment by JannikHa** [comment]
Totally misunderstood you, I'm sorry!
Got your Problem now, though, will try to replicate It ASAP :)

**Comment by tristan957** [comment]
Cool thanks!

**Comment by JannikHa** [comment]
So i tried to replicate the problem on **Arch Linux** with the **Budgie Desktop 10.2.7**, though I was unsuccessful (It worked). Will now try to update my Budgie-Version to yours (10.2.8), didn't even know it's updated yet :) Then I'll try again and report back to you :)

**Comment by tristan957** [comment]
That's really weird. Yea that's exactly what I did. I tried rebookmarking it just in case. Still just a blank line with a folder icon in the applet.

**Comment by JannikHa** [comment]
Just in case, what is your **Nautilus** Version?
Hm, i think Ikey has to take a look at that. I'm almost certain that this is a Nautilus related problem, but i could be wrong. Going to keep try finding out what the problem ist, let's keep each other updated :)

**Comment by tristan957** [comment]
3.20.3 is my current version

**Comment by JannikHa** [comment]
Hm, my guess is that it's an incompability with your Nautilus Version. I don't know when Solus is going to update to the **V. 3.22**. On **Nautilus V. 3.22** everything seems to work just fine.

**Comment by JannikHa** [comment]
Are you still Solus 1.2.0.5  or on 1.2.1? If you're on 1.2.0.5, try upgrading and try to replicate your problem.

**Comment by ikeydoherty** [comment]
I'll try to fix this tonight if someone pings me in like 6 hours when I finish work, so I don't forget xD

**Comment by JannikHa** [comment]
@tristan957 The God arrived, your problem shall be solved soon! ;)
