### ISSUE TITLE
ibus version too high?

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#663]
The readme gives the ibus version required to be v1.5.13 or higher

I presume in debian terms, this is the library libibus-1.0-5 

 - https://packages.debian.org/search?suite=sid&section=all&arch=any&searchon=names&keywords=libibus

In debian sid and ubuntu 16.10 the version available is v1.5.11

Is there something specific in the budgie-desktop implementation that requires a version of ibus so much higher than is available in debian and ubuntu?

TIA

**Comment by ikeydoherty** [comment]
All versions before 1.5.10 are critically broken in one way or another. I'll set it to 1.5.11 if that works for all builds of Budgie
