### ISSUE TITLE
Places applet : double entries

### ISSUE THREAD

**Issue by 1Claude** [solus-project/budgie-desktop#667]
**The issue encountered**

After update from Budgie 10.2.7 to version 10.2.8, the Places applet now shows double entries of some folders, like Downloads and Videos (Téléchargements & Vidéos, in french.)

**Steps to reproduce the issue**

 ...
Budgie 10.2.8
Solus 1.2.1

![capture du 2016-10-20 12-29-08](https://cloud.githubusercontent.com/assets/19640810/19577507/adf65150-96e5-11e6-9e79-e0b06bc2ddb5.png)

**Comment by cybre** [comment]
Post the output of
```bash
cat ~/.config/gtk-3.0/bookmarks
```
and
```bash
cat /etc/xdg/user-dirs.conf
```
please.

**Comment by 1Claude** [comment]
cat ~/.config/gtk-3.0/bookmarks
file:///home/claude/Documents
file:///home/claude/Musique
file:///home/claude/Images
file:///home/claude/Vid%C3%A9os
file:///home/claude/T%C3%A9l%C3%A9chargements
claude@solus ~ $ cat /etc/xdg/user-dirs.conf
cat: /etc/xdg/user-dirs.conf: Aucun fichier ou dossier de ce type (No file or folder of that type)

**Comment by 1Claude** [comment]
My wild guess : maybe it's because of the french language and its accentuated letters like "é". The 2 folders that are showed twice have both an "é" in it. Vidéo (Video) - Téléchargements (Downloads)

**Comment by feskyde** [comment]
> My wild guess : maybe it's because of the french language and its accentuated letters like "é". The 2 folders that are showed twice have both an "é" in it. Vidéo (Video) - Téléchargements (Downloads)

Can confirm, in `es_AR` locale M**ú**sica, Im**á**genes and V**í**deos are shown twice:

![screenshot from 2016-10-21 11-23-11](https://cloud.githubusercontent.com/assets/20542037/19601751/f566b1d8-9780-11e6-996e-3a0f09d6aef8.png)

**Comment by cybre** [comment]
I'm working on fixing this right now.

**Comment by cybre** [comment]
@feskyde Also, that "(null)" issue has been fixed in `master` :D

**Comment by feskyde** [comment]
Yep I know, and now is translated by me, for me :stuck_out_tongue_closed_eyes:
