### ISSUE TITLE
[request] locally integrated menu/global menu

### ISSUE THREAD

**Issue by Gibbz** [solus-project/budgie-desktop#671]
A feature request, id love to see locally integrated menus, similar to what is done in ubuntu. I love how these save screen space and make using small laptop screens more comfortable to use.

Good example seen here:
http://www.webupd8.org/2014/02/ubuntu-1404-gets-locally-integrated.html

**Comment by ikeydoherty** [comment]
We don't have that level of control over Mutter.

**Comment by JannikHa** [comment]
There is a reason the last Ubuntu versions use **compiz** ^^

**Comment by horst3180** [comment]
Doesn't this require GTK patches too?

**Comment by ikeydoherty** [comment]
@JannikHa your comment isn't helpful or related. Canonical do what they do, and even have their own Compiz 0.9 nowadays....

@horst3180 it does, so it's not something we'll be merging as its Canonical-specific. (And frankly, ridiculous.)

**Comment by rilian-la-te** [comment]
Nope for GTK3,  and patched unity-gtk-module for GTK2 (or patched GTK2)

**Comment by ikeydoherty** [comment]
Remember - as much as I might not want things in the *core* of Budgie - there is absolutely nothing stopping someone from implementing an out-of-tree budgie applet to provide a global menubar.
If I do it, it'll suck. I don't have the unity stuff on Solus, I don't really have the time to implement one either.

But, there is demand for such an applet. So make it an independent project on GitHub. Own it, promote it. The people will come :) Thoroughly recommend this route

**Comment by fossfreedom** [comment]
concur with Ikey's advice - maybe this project could be used as inspiration here - https://git.javispedro.com/cgit/topmenu-gtk.git/about/

**Comment by ikeydoherty** [comment]
Honestly I would love to see more applets available for Budgie. The problem with them being in core is two-fold:

 - They fall under my ownership
 - I have to maintain them

I might then make decisions others don't agree with for these components I don't own. Put your own module together (Chuck it together in Vala very easily), set up your own repo and put a github.io site together for it :) Let's start fleshing out an add-on community :)
