### ISSUE TITLE
[request] Task Bar on left & right of screen

### ISSUE THREAD

**Issue by Gibbz** [solus-project/budgie-desktop#672]
A feature request.
The ability to move the menu bar to the left/right of the screen with a icon view layout.
Heres an image I found showing what I mean:
http://www.simpletechietips.com/wp-content/uploads/2015/11/Simple-Techie-Tips-SimpleTechieTips.com-2.png

**Comment by ikeydoherty** [comment]
Currently Raven opens on the right of the screen, what would be the plan there.. ?

**Comment by ikeydoherty** [comment]
Closing as dupe of #541
