### ISSUE TITLE
Usability problem with big number of applets

### ISSUE THREAD

**Issue by DerpyCrabs** [solus-project/budgie-desktop#678]
When one has a big number of applets on panel he must scroll down to change applet position or scroll up to remove applet.
I think it would be convenient to limit applet list height and add scroll to it to always see move and add/remove buttons.
![Too many applets](https://cloud.githubusercontent.com/assets/9917318/19628266/2c3abf2e-9984-11e6-8199-b2df2b0bb21b.png)

**Comment by Baemir** [comment]
This problem is also present for anyone using a screen with a low vertical resolution (such as myself), even if you don't have very many applets enabled. Definitely annoying.

**Comment by JoshStrobl** [comment]
I believe this to be a GTK-related issue and thus will be resolved with our switch to Qt. Marking for the Budgie 11 milestone.

**Comment by JoshStrobl** [comment]
Closing since we've since switched to a dedicate Settings app.
