### ISSUE TITLE
HiDPI panel issues

### ISSUE THREAD

**Issue by NeoVsk** [solus-project/budgie-desktop#679]
**Operating System**: e.g. Solus 1.2.1
**Budgie version**: i.e. Budgie 10.2.8

**The issue encountered**
When setting HiDPI Window Scaling to 2, windows do not respect that panel is larger and the uppermost portion of window is inaccessible (close, minimize, maximize buttons).

**Steps to reproduce the issue**
Either use Gnome Tweak Tool to set Window Scaling to 2, or via terminal 
`gsettings set org.gnome.desktop.interface scaling-factor 2`

![screenshot from 2016-10-23 23-37-31](https://cloud.githubusercontent.com/assets/23018567/19629658/ca59b1b6-9979-11e6-8fd5-e46bca4b719a.png)

**Comment by ikeydoherty** [comment]
You must restart the panel. It only calculates scaling factor on startup

**Comment by ikeydoherty** [comment]
So this is resolved in `budgie-next`, and will be part of the next major version of Budgie

**Comment by ikeydoherty** [comment]
Fixed in git
