### ISSUE TITLE
Couple of bugs with icons in 10.2.8 panel

### ISSUE THREAD

**Issue by iachopolo** [solus-project/budgie-desktop#680]
Operating System: Manjaro stable with Budgie 10.2.8
I'm using Moka icons-theme
2 small bugs:

Bug nº1. Some applications (Chromium, Files and Tomahawk) change their icons in the panel when started:

Before starting them (the n1, n3 and n9 counting from the left)
![captura de pantalla de 2016-10-23 19-08-29](https://cloud.githubusercontent.com/assets/16168428/19629849/2660227c-9954-11e6-8b21-eb473f0016f1.png)

After starting them
![captura de pantalla de 2016-10-23 18-52-03](https://cloud.githubusercontent.com/assets/16168428/19629759/deb45fa8-9951-11e6-9309-5fe6de70f2c8.png)

Bug nº2: I started LibreOffice Writer and then pinned it. When I close it, the LibreOffice Impress icon appears in its place. If I click on it, it launches Impress app.
![captura de pantalla de 2016-10-23 19-04-20](https://cloud.githubusercontent.com/assets/16168428/19629814/85aa04ce-9953-11e6-8244-8be50bbfb996.png)
Then close Impress and open Writer from the menu, the Writer icon is in the place Impress was
![captura de pantalla de 2016-10-23 19-06-20](https://cloud.githubusercontent.com/assets/16168428/19629836/cdd5d8ea-9953-11e6-8fb3-ac2da227e479.png)

Hope its clear enough and helps!
Cheers!

**Comment by ikeydoherty** [comment]
This is within *compliance* of X11 standards. The X11 window overrides the icon, not us. In a few places we _prevent_ those overrides. If you have specific `.desktop` files you wish to not be overriden by the window, then please request them.

This isn't a bug.

**Comment by mjota** [comment]
I have similar problem:

Nautilus and Terminix closed. The icon theme is not ok.
![1](https://cloud.githubusercontent.com/assets/467710/19723863/a0c6897c-9b7d-11e6-9070-b4c211b5b806.png)

Nautilus and Terminix open. The icon theme is ok (Paper).
![2](https://cloud.githubusercontent.com/assets/467710/19724011/37b22882-9b7e-11e6-8346-e458bef7cfd5.png)

Operating System: Antergos with Budgie 10.2.7-3

I think it happens after gnome 3.22 update. Possibly not.

**Comment by iachopolo** [comment]
But what about the 2nd bug. If I can't pin LibreOffice Writer, that should be a bug

**Comment by ikeydoherty** [comment]
LibreOffice writer pins properly here, what is the desktop file name there on Manjaro?

**Comment by iachopolo** [comment]
Sorry, I don't know how to look for it :(

I'll try to make it clearer just in case: If I pin Writer and then close it, Impress gets in its place. Then, it really doesn't get pinned

**Comment by ikeydoherty** [comment]
Yeah that bits fine, but what is the path to the `.desktop` launcher? i.e on Solus we have:

```
/usr/share/applications/libreoffice-base.desktop
/usr/share/applications/libreoffice-calc.desktop
/usr/share/applications/libreoffice-draw.desktop
/usr/share/applications/libreoffice-impress.desktop
/usr/share/applications/libreoffice-startcenter.desktop
/usr/share/applications/libreoffice-writer.desktop
/usr/share/applications/libreoffice-xsltfilter.desktop
```

**Comment by iachopolo** [comment]
Well it's the same path, but they are links from this folder: /usr/lib/libreoffice/share/xdg/
with these names:

```
/usr/lib/libreoffice/share/xdg/base.desktop
/usr/lib/libreoffice/share/xdg/calc.desktop
/usr/lib/libreoffice/share/xdg/draw.desktop
/usr/lib/libreoffice/share/xdg/impress.desktop
/usr/lib/libreoffice/share/xdg/math.desktop
/usr/lib/libreoffice/share/xdg/qstart.desktop
/usr/lib/libreoffice/share/xdg/startcenter.desktop
/usr/lib/libreoffice/share/xdg/writer.desktop
/usr/lib/libreoffice/share/xdg/xsltfilter.desktop
```

**Comment by ikeydoherty** [comment]
Ya that's the same for Solus, was checking it was packaged properly ^^

```
/usr/share/applications/libreoffice-base.desktop:        symbolic link to /usr/lib/libreoffice/share/xdg/base.desktop
/usr/share/applications/libreoffice-calc.desktop:        symbolic link to /usr/lib/libreoffice/share/xdg/calc.desktop
/usr/share/applications/libreoffice-draw.desktop:        symbolic link to /usr/lib/libreoffice/share/xdg/draw.desktop
/usr/share/applications/libreoffice-impress.desktop:     symbolic link to /usr/lib/libreoffice/share/xdg/impress.desktop
/usr/share/applications/libreoffice-startcenter.desktop: symbolic link to /usr/lib/libreoffice/share/xdg/startcenter.desktop
/usr/share/applications/libreoffice-writer.desktop:      symbolic link to /usr/lib/libreoffice/share/xdg/writer.desktop
/usr/share/applications/libreoffice-xsltfilter.desktop:  symbolic link to /usr/lib/libreoffice/share/xdg/xsltfilter.desktop
```
