### ISSUE TITLE
How do I run budgie-panel built from sources with raven that is also from sources

### ISSUE THREAD

**Issue by nazar-pc** [solus-project/budgie-desktop#683]
I've built master branch and trying to run budgie-panel. It works, but it is using raven installed on my system instead of one that was just built from sources.

It might be a dumb question, but how can I run budgie-panel located at `src/panel/.libs/budgie-panel` with raven from `src/raven/.libs` and, possibly, other components there?

**Comment by ikeydoherty** [comment]
You don't run Budgie from a git tree, you must have it installed system-wide

**Comment by nazar-pc** [comment]
Well, do you install it globally every time you make a change just to test?
I hoped there is another way to try it without installing. Maybe, set some environment variables to override where to look for necessary libraries.

**Comment by ikeydoherty** [comment]
I do yes. You can potentially abuse `LD_LIBRARY_PATH` fwiw and set it to the .libs dirs (colon separated)

GSettings schemas must be globally present too remember

**Comment by nazar-pc** [comment]
`LD_LIBRARY_PATH` works, thanks!
I'm building it in Docker container (to avoid installing build dependencies on host system or use VMs), but running on host system.
