### ISSUE TITLE
System Tray Icons too far apart on HiDPI

### ISSUE THREAD

**Issue by asonix** [solus-project/budgie-desktop#685]
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8

**The issue encountered**
The System Tray in budgie when in HiDPI positions icons too far apart. Specifically the network-manager-applet icon has far too much space on either side.

![Image](http://i.imgur.com/duHZl87.png)

**Steps to reproduce the issue**
1. Have HiDPI
2. Open more than one application that uses a tray icon

**Comment by ikeydoherty** [comment]
Not convinced it's a Budgie specific issue. They're embedded windows, we don't actually control them. It's up to the clients to support HiDPI in their tray icons

**Comment by kozec** [comment]
Budgie is what is setting sizes for those embeded windows. Right now, it's pretty-much unusable with HiDPI screen.

**Comment by JosephMcc** [comment]
@ikeydoherty The problem actually looks to be in na-tray. I just tested this fix from mate-panel in budgie-panel and it seems to fix the issue: https://github.com/mate-desktop/mate-panel/pull/756/commits/0b15ea1f6d218cc2a850bef3f0cb98d303c63bc3

**Comment by JosephMcc** [comment]
Because screenshots are fun...
Before:
![selection_028](https://user-images.githubusercontent.com/2231759/41372285-b33a20e2-6f01-11e8-8102-57a9616ab8ff.png)

After:
![selection_027](https://user-images.githubusercontent.com/2231759/41372295-bb2bb176-6f01-11e8-86ed-6db748ed9103.png)

**Comment by JoshStrobl** [comment]
Should be resolved as of #1998 :tada:

Thanks @serebit
