### ISSUE TITLE
The icon used for the log off entry is not the logoff icon but the application-exit icon

### ISSUE THREAD

**Issue by oxayotl** [solus-project/budgie-desktop#724]
As a theme maker, I am trying to get the best icon support for Budgie. However I noticed the icon used for the user log off in the user panel is an icon that should be for application exit. There exists a user log off icon in the Adwaita theme, called `system-log-out`, and in the Actions context, but sadly this icon doesn't provide a `symbolic` version yet.
Here is my recommendation:
- change the icon used in the menu. The relevant code is line 179 in file `budgie-desktop/src/panel/applets/user-indicator/UserIndicatorWindow.vala`, where the line `IndicatorItem logout_menu = new IndicatorItem(_("Logout"), "application-exit-symbolic", false);` should become  `IndicatorItem logout_menu = new IndicatorItem(_("Logout"), "system-log-out", false);`
- add a copy of the currently used icon (i.e., starting from the folder where Adwaita is installed, `Adwaita/scalable/actions/application-exit-symbolic.svg`) in `budgie-desktop/data/icons/actions/` and rename it `system-log-out-symbolic.svg`, or create a new icon and put it there.
- fill a bug on Gnome's bugzilla asking for an official `symbolic` version of system-log-out to be released.

Then, when you update your Gnome dependency for one that includes an Adwaita version that includes a good `symbolic` icon for `system-log-out`, remove the icon from `budgie-desktop/data/icons/actions/`.

Thanks :).

**Comment by ikeydoherty** [comment]
I'm confused - you want us to switch from a standard icon to a non standard icon .. why?

Also Adwaita should not be factored into Budgie design decisions, we're *decreasing* our dependency on GNOME, not solidifying it.

> update your Gnome dependency
Yeah not gonna happen :) Migration++

If we need to include a named icon within the Budgie icons provided, so be it, but let's talk about that.

**Comment by oxayotl** [comment]
Oh okay, I'm not familiar with the project, I thought the dependency on Adwaita was voluntary. My bad. 
Also I got a mental BSOD and forgot that application-installed icon are part of `hicolor` and therefore you would NOT need to upgrade regardless of any change in Adwaita.

The question of standard and non-standard icon is relevant, thanks for mentioning that. I searched through the internet and checked: both `application-exit` and `system-log-out` are both part of the `Standard Icon Names` from the FreeDesktop `Icon Theme Specification` : https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html. 
However, the use of the `application-exit` in this context is not in accordance with the specification, which states `system-log-out` should be used.
Also, this means that actually any icon theme, no matter if designed for Gnome, XFCE, KDE, Unity or otherwise, should cover those icons, which is great :+1:  . You might want however to provide a `symbolic` version of the icon regardless, just in case the theme only provides a full color version (like Adwaita does), because having one full color icon in the middle of a lot of `symbolic` icons would look weird and unpolished, but if this is not a problem it means there is no need to add any specific icon to Budgie.

Thanks for the quick answer :).

**Comment by Vistaus** [comment]
I agree that something needs to change here. I find it very confusing that the log out icon is represented by application-exit.

**Comment by oxayotl** [comment]
No news on this, @ikeydoherty ?

**Comment by oxayotl** [comment]
Does this mean that you do plan on changing the icon for Budgie 11? Or does the desktop change in ways that makes this whole issue irrelevant?

**Comment by ikeydoherty** [comment]
"Incorporated as fixes". As in, I intend to fix it.

**Comment by JoshStrobl** [comment]
Was resolved in bac17590e
