### ISSUE TITLE
Clipping with Icon Theme - Oranchello Used Theme: Adwaita.

### ISSUE THREAD

**Issue by freakyy85** [solus-project/budgie-desktop#727]
**Operating System**: Ubuntu 16.10
**Budgie version**: 10.2.8-0ubuntu2~yakkety

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

uwe@loopy-ubuntu:~/Downloads/Spiele$ budgie-desktop --version
budgie-desktop 10.2.8
Copyright © 2014-2016 Ikey Doherty, Solus Project
uwe@loopy-ubuntu:~/Downloads/Spiele$ 

Use Oranchelo Icon Theme - Clipping at right - part gets removed in the app launcher (open programs) of the Terminal app. The used theme is Adwaita. from gnome3.

**Comment by fossfreedom** [comment]
suggest need a screenshot showing the issue.

**Comment by freakyy85** [comment]
Here a screenshot.
![screenshot from 2016-11-14 17-48-40](https://cloud.githubusercontent.com/assets/746969/20273726/b1708038-aa92-11e6-8191-486b9dffe76c.png)

**Comment by freakyy85** [comment]
Btw, I love budgie. I even prefer it over gnome3 :D

**Comment by ikeydoherty** [comment]
Yknow you're supposed to edit the issue text right?

**Comment by freakyy85** [comment]
sorry will do next time ;D

**Comment by Thisuu** [comment]
This seems more like a _Theme Specific_ issue due to lack of support for Budgie.
This could be solved on Flat-plat by adding 2px padding beside `.budgie-panel  button`,
Adwaita on Solus doesn't have the issue though.
