### ISSUE TITLE
Keyboard Layout Widget does not work with German (de)

### ISSUE THREAD

**Issue by baimafeima** [solus-project/budgie-desktop#742]
<s>Solus 1.2.1</s> Solus 2017.04.18.0
<s>Budgie 10.2.8</s> Budgie 10.3.1

I have activated the standard German keyboard layout (de). 
Typing " ; " and " ' " on an American laptop should then produce the "o" and "a" with two dots on top of it. The two keys are right next to the L.

**Comment by JoshStrobl** [comment]
Please validate if the latest IBUS support improvements in Budgie have resolved this issue.

**Comment by baimafeima** [comment]
Just tested with the latest updates. Unfortunately the issue still persists and I am unable to type the German umlauts or mutated vowels.

**Comment by ikeydoherty** [comment]
You don't need ibus for German, you just need to set the German layout through Input Sources in GNOME Control Center, and remove the US layout. Please confirm. :)

**Comment by baimafeima** [comment]
I removed the US layout from Input Sources and now only have the German and Chinese layouts activated. Unfortunately, I still don't get it to work. Please let me know if you need my help in testing. This only affects the Budgie edition, it is working in GNOME and MATE.

**Comment by baimafeima** [comment]
@ikeydoherty Is this also an IBus issue or related to the Keyboard Layout Widget in Budgie?
