### ISSUE TITLE
Keyboard layout modifiers-only switch

### ISSUE THREAD

**Issue by Antwerpen** [solus-project/budgie-desktop#747]
**Operating System**:  Solus 1.2.1
**Budgie version**: Budgie 10.2.8 

Modifiers-only switch shortcut (i.e. Alt+Shift) is available in the keyboard settings, but it doesn't seem to work. Super+Space works, but it's simply inconvenient.

**Comment by eranj** [comment]
Seems to work on Ubuntu so it's Ubuntu Budgie specific.

**Comment by rvsosn** [comment]
This bug is reproduced on Solus OS 2017.01 (budgie-desktop 10.3.1).
