### ISSUE TITLE
Translations, Swedish: Remove sv_SE, keep sv in Transifex

### ISSUE THREAD

**Issue by hanklank** [solus-project/budgie-desktop#777]
There are two almost duplicate po setups for the Swedish language in Transifex. This might lead to confusion and double work for any new translators. And there also another more important issue -  most translations to Swedish use the sv locale only (Ubuntu, Debian etc).  The reason is that sv_SE won't let people living in Finlandia that are Swedish speaking (i.e having locale sv_FI) use the sv translations. (sv_FI can't fall back on sv_SE, but would fall back to sv if an translation isn't sv_FI specific, i.e. most cases). So, please nuke the sv_SE one, and do keep only the sv one.

**Comment by JoshStrobl** [comment]
This has been resolved in preparation for the use of Weblate. More details will follow on the Solus blog once Weblate is ready to be used for translations.
