### ISSUE TITLE
Can't switch keyboard layout on screen locker

### ISSUE THREAD

**Issue by niihelium** [solus-project/budgie-desktop#788]
Solus Release:	2017.01.01.0
budgie-desktop 10.2.9

Can't switch keyboard layout on screen locker

 ...

How to reproduce:
* Add non-latin layout as secondary ( one layout for all windows, and Super+space switcher)
* Switch layout to non-latin
* Lock screen
* Try to unlock it - wrong password
* Try to change layout - space recognizes as text input
(even no poweroff/restart button so I should long press power button on my laptop)

**Comment by gavvvr** [comment]
Yeah, very annoying :unamused: 
Hope it will be fixed soon.

**Comment by rvsosn** [comment]
This bug is reproduced on Solus OS 2017.01 (budgie-desktop 10.3.1).
It is very annoying.

**Comment by ikeydoherty** [comment]
It's not a Budgie issue, it's a gnome-screensaver issue. And if every other person can stop chiming in to just tell me how annoyed they are, I know. It's annoyed me too. Looking for alternatives.
