### ISSUE TITLE
Can't pin some applications to panel

### ISSUE THREAD

**Issue by rodrum** [solus-project/budgie-desktop#817]
**Operating System**: Solus shannon, release 2017.01.01.0, LSB Version 1.4

**Budgie version**: budgie-desktop 10.2.9

**The issue encountered**

I can't pin Mendeley app to pannel. Right-click doesn't gives the option "Pin to panel".

**Steps to reproduce the issue**

Open Mendeley from menu and right-click the icon in the panel to see that the option is not there.

**Comment by cipricus** [comment]
As a workaround (not as a fix to the bug), in all such cases   

- install  `xprop`
- run it in terminal and click the app’s window
- look in terminal for the line `WM_CLASS(STRING) =`. It should specify "Somename"
- rename the launcher accordingly (`Somename.desktop`) and save it in `~/local/share/applications`
- run it and you should be able to pin it

**Comment by rodrum** [comment]
Thanks, that worked great!

**Comment by cipricus** [comment]
@rodrum - maybe the issue should be more generically called "Can't pin some applications to panel".

**Comment by foivos92** [comment]
i have noticed this with popcorn time as well. i am using budgie on arch and decided to get another popcorn time than the one offered by the AUR. i created a .desktop file for it and that makes it show up at the menu but still can not pin it. funny thing is that the aur popcorn time could be pinned. i hope that detail helps

**Comment by ikeydoherty** [comment]
Filename has to match the WMCLASS. Make sure its the same filename as the AUR version

**Comment by Vistaus** [comment]
I can confirm that the xprop workaround works, at least for QupZilla.

**Comment by IlDordollano** [comment]
I've got a similar problem with Solus 3: showing duplicated Third Party software on Budgie bar.
![screenshot](https://user-images.githubusercontent.com/24453259/29608149-a579f75c-87f3-11e7-964d-7ba8fec5f30d.png)

**Comment by khalismur** [comment]
Have the same problem, also with Mendeley.

**Comment by Vitorvlv** [comment]
Have the same problem with spotify: https://giant.gfycat.com/OldfashionedBriefAustraliankestrel.mp4

**Comment by fwahh** [comment]
Also have the problem with Spotify.

**Comment by Vistaus** [comment]
> Also have the problem with Spotify.

I can confirm that.

**Comment by zorates** [comment]
Same issue with libreoffice-writer.

The suggested workaround to use `xprop` and rename the .desktop file accordingly does not work, as the .desktop launcher for libreoffice-writer already matches the WM_CLASS name:

`WM_CLASS(STRING) = "libreoffice", "libreoffice-writer"`
`/usr/share/applications/libreoffice-writer.desktop`

**Comment by rjurga** [comment]
> BUT! By simply launching a second instance of libreoffice-writer, this second instance actually does become pinnable.

Thanks, this works for me too.

**Comment by NexusPenguin** [comment]
Hi,
Thanks for your help. 
I did as it's said here... The ability to pin the app now shows up... But it has no effects. Icon vanishes as soon as app is closed. 
Any idea ?

**Comment by texelate** [comment]
I am having this problem too though I am running Budgie with Antergos. I want to pin Parole Media Player.

**Comment by djangofan** [comment]
> As a workaround (not as a fix to the bug), in all such cases
> 
> * install  `xprop`
> * open your app (a window has to be visible)
> * run `xprop` in terminal and click the app’s window
> * look in terminal for the line `WM_CLASS(STRING) =`. It should specify "Somename"
> * rename the launcher accordingly (`Somename.desktop`) and save it in `~/local/share/applications`
> * run it and you should be able to pin it

This did not work.  Trying to link an app called Transcribe .   I had to use  /usr/local/share/applications   NOT  ~/local/share/applications .    I have it working now.

**Comment by Femto-godhand** [comment]
Hello all, 
I have encountered the problem too (pin option disappeared), so I have find a way to resolve it. I have launch a command in the terminal in order to reset the budgie panel :
budgie-panel --replace --reset

I have had to reconfigure my panel settings after, but all seems to work now. :)

*more info about the command : https://github.com/solus-project/budgie-desktop/issues/289#issuecomment-256241801

**Comment by JoshStrobl** [comment]
This issue should no longer exist as of git.

**Comment by gusbemacbe** [comment]
@JoshStrobl 

There is still a problem. It is with Spectacle. I added `StartupWMClass=spectacle` to Spectacle desktop file and pinned it, but it seems like:

![spectacle](https://user-images.githubusercontent.com/2257024/58370575-93431f80-7ede-11e9-839c-1265562fe7ee.gif)
