### ISSUE TITLE
Minor bug with the Dropbox tray icon

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#820]
Operating System: Solus 2017.01.01 (with all updates installed)
Budgie version: 10.2.9

If you click on Shutdown to turn off your PC and then cancel to go back, the Dropbox tray icon disappears. The actual process isn't interrupted, it's just the icon that somehow goes away. It doesn't happen with other tray icons like Psensor.

**Comment by mark2741** [comment]
+1 for this issue. This is happening for me for both Dropbox and also Synology Cloud Sync Drive icons - upon clicking Shutdown (even before canceling) they both disappear. So does the networking icon, though that one still functions as evident by right-clicking on where it was placed. The others appear to not just disappear but to be completely unloaded. 

One important note that might differentiate my setup and be a factor: I am using a 4k resolution with scaling set to 2x via:
$ gsettings set org.gnome.desktop.interface scaling-factor 2
