### ISSUE TITLE
Add option to open tasks with double click.

### ISSUE THREAD

**Issue by madprops** [solus-project/budgie-desktop#827]
I have this functionality through some third party application on Windows and it's pretty nice, already got used to it.

Basically, an option to make tasks in the taskbar start with 2 clicks instead of 1. This avoids the problem of opening tasks by accident, which happened to me quite a bit.

**Comment by JoshStrobl** [comment]
Resolved with f1bf616395d3f0274a334244c0cfe05ee8aa0ce1
