### ISSUE TITLE
[User-indicator] GtkButton inside the GtkListRow keeps grabbing ':active' pseudo-class even after closing GtkPopover?

### ISSUE THREAD

**Issue by tista500** [solus-project/budgie-desktop#841]
**Operating System**:  Ubuntu GNOME 17.04 beta
**Budgie version**:  Budgie 10.2.9 stable tarball from git release

*Xorg version*: 1.18.4
*DBus version*: 1.10.10
*Gtk+ 3 version*: 3.22.11
*Gnome-session version*: 3.24.0

*GPU*: HD Graphics 510 (Skylake GT1) 
*Mesa version*: 17.0.2

**The issue encountered**
Hi, I'm an author of Adapta-gtk-theme.
This might be a corner-case, but I could not solve this from theme-side.

Once clicked/tapped any GtkListRows inside that GtkPopover, even after closed/re-opened that GtkPopover, still `:active` pseudo-class was existed/hooked in GtkButton contained by the parent GtkListRow. In my Adapta, `:active` pseudo-class is only for animation properties like Ripple-effects, and I suppose `;active` pseudo-class should be hooked only when we clicked/tapped and/or hit Enter key (button_press_event/key_press_event happens on GtkButton) if I were correct. So I've already added workaround to disable any animations on that GtkButton and the parent GtkListRow in my Adapta.

So is it possible to release that `:active` pseudo-class from GtkButton when closing GtkPopover of user-indicator applet?
 ...

**Steps to reproduce the issue**
1. Open GtkPopover via user-indicator applet.
2. Select (click, tap, or hit Enter key)`Shutdown` GtkListRow item.
3. Select `Cancel` on budgie-session-dialog and close budgie-session-dialog.
4. Re-open GtkPopover of user-indicator applet.
5. Check the pseudo-classes of `row.activatable > button.indicator-item` via css-inspector.

I hope developers could reproduce this issue...
 ...

**What I expected**
`:active` pseudo-class of GtkButton inside the GtkListRow is added only when we click/tap that GtkButton.

Best Regards,
Tista

**Comment by JoshStrobl** [comment]
This should already be resolved but just in case, I added another commit aa258648cde043214c99cbe63d28ca0699dbbda3 that should remove focus from those buttons. Feel free to validate and re-open if the issue persists.
