### ISSUE TITLE
Keyboard Shortcut - "Switch to next input source" doesn't wrap around input sources

### ISSUE THREAD

**Issue by minhng99** [solus-project/budgie-desktop#854]
**Operating System**: Ubuntu 17.04
**Budgie version**: 10.2.9-3ubuntu4 (budgie-desktop 10.2.9)

**The issue encountered**

Input source stuck on English and doesn't change to another input source on shortcut "Switch to next input source"

**Steps to reproduce the issue**

I'm using IBus with 2 input sources (English, Vietnamese [ibus-unikey])

If I press "Super+Space" (Switch to next input source) while using Vietnamese input source then it will change to English but press it again it doesn't change back to Vietnamese

But it does wrap around input sources if I press "Shift+Super+Space" (Switch to previous input source) (It turn to Vietnamese and turn to English again and again)

**Comment by JoshStrobl** [comment]
Has since been resolved.
