### ISSUE TITLE
Tasklist open new window

### ISSUE THREAD

**Issue by finalgamer** [solus-project/budgie-desktop#865]
**Operating System**: Ubuntu 16.10
**Budgie version**: Budgie 10.2.9

Shift + left click on a program in the task list while a window is already open should open a new window of this program.

**Comment by ikeydoherty** [comment]
..Says who?

**Comment by finalgamer** [comment]
Me as a suggestion I might add

**Comment by alunux** [comment]
I think this feature is less suited to some desktop applications, e.g: telegram, spotify, etc. If the application support New Window menu, then I will just press Ctrl + N shortcut to open a new window from the running application.

**Comment by ikeydoherty** [comment]
Right so it's a feature request.. it was worded like a bug report. :p

**Comment by finalgamer** [comment]
My use case for this is:
I am on a different workspace and need to open a new browser. The option of Ctrl + N seems very annoying in this example. So currently I need to right click and choose open new window which is on a different spot for every application. I am suggesting this because I come from dockbarx and windows where shift + left click opens a new application instance. For me this option would be a great improvement!

@alunux In case of Spotify and Telegram they do both handle the instancing on there own. So reopening the application just brings up the current instance.

**Comment by ikeydoherty** [comment]
And single instance applications, when invoked, will always open the existing application. There is no way to detect this from the outside. Fairly sure this bug is a dupe.

**Comment by fossfreedom** [comment]
Ikey - its a variation of #669 and #441

**Comment by JoshStrobl** [comment]
I will consider this for Budgie 11 when I merge the IconTasklist and traditional Tasklist applets, which will be in a different repo (and use a different issue tracker). Closing since it isn't currently in scope.
