### ISSUE TITLE
Quick switching audio outputs from Raven menu broken

### ISSUE THREAD

**Issue by binPanda** [solus-project/budgie-desktop#909]
Solus version: latest snapshot, 2017.04.18.0
Budgie version: 10.3.1

**The issue encountered**
The option to switch to another output source doesn't work anymore. It used to work a few days ago but today I noticed it's not working anymore. When I connect my Bluetooth speaker it appears in the list but I can't click on it to switch so I have to go to sound options for it.

**Steps to reproduce the issue**
It keeps happening every time I connect another output source.

**Comment by michaeltintiuc** [comment]
When I plugin my headphones I can switch between the outputs, only issue is that there's no audio when switching back to built-in laptop audio

**Comment by mrucz** [comment]
Ubuntu 17,04
Budgie v. 10.3.1

**The issue** (as in post #1):
Switching audio outputs in Raven doesn't work; it does work in settings: sound. 
It was working ok right after fresh u17,04bd install untill I enabled the Ubuntu Budgie backports PPA and made an upgrade.
I'm not adding any hw - using only what's already provided on my mainboard and trying to switch between line and hdmi.
As said it works via settings: sound but not via respective Raven pane. The Raven looks bit strange (vide the screenshot).
No idea how to make a proper screenshot as the Raven pane hides immediately after I click whatever, for I made a photo of my screen, hope it's good enough.

![19749499_1492822404097534_1786631370_o](https://user-images.githubusercontent.com/29859564/27789073-5269af7e-5feb-11e7-9ee1-f0076453bdb4.jpg)

Settings:sound looks and works ok:
![1](https://user-images.githubusercontent.com/29859564/27789214-e5469d02-5feb-11e7-97c4-213cdb6cba54.png)


Steps to reproduce:
Upgrade with budgie backports ppa enabled, open raven pane and try to switch audio output, then try the same via settings: sound.

**Comment by fossfreedom** [comment]
k - for the uninitiated - @mrucz has upgraded from budgie-desktop 10.2.9 where apparently things were working to 10.3.1 where things have gone slightly awry.

**Comment by fossfreedom** [comment]
Is this issue the same as this one? https://github.com/budgie-desktop/budgie-desktop/issues/804

**Comment by michaeltintiuc** [comment]
Looks fixed AFAIK

**Comment by michaeltintiuc** [comment]
Although the checkboxes are not updated when a previously selected device has been unplugged, the default output/input devices are not marked as checked.

**Comment by ikeydoherty** [comment]
@michaeltintiuc this also true within PulseAudio itself and GNOME Control Center, no output is selected at that point.

**Comment by michaeltintiuc** [comment]
@ikeydoherty So there's no way of knowing which of the devices it falls back to? We do get audio back to speaks after headphones were disconnected.

**Comment by ikeydoherty** [comment]
I'll figure out something after I wake up / caffeine.

Me at this minute https://www.youtube.com/watch?v=ubeVUnGQOIk

**Comment by michaeltintiuc** [comment]
@ikeydoherty lol, take your time, you and the team are doing the great work! :)

**Comment by ikeydoherty** [comment]
Thanks bud :D

**Comment by JoshStrobl** [comment]
Should be resolved with a6a6ef353a29c71d01ab1a624c23ec9f594a2796
