### ISSUE TITLE
Evolution notifications

### ISSUE THREAD

**Issue by cavkirov** [solus-project/budgie-desktop#926]
**Operating System**: e.g. Solus (latest stable)
**Budgie version**: i.e. Budgie 10.x (not on computer right now, but also latest for Solus)

**The issue encountered**

I've turned off evolution notifications in the settings for notifications. But I still get notifications for every new email. 
I haven't been able to find a setting in Evolution to turn them off though.

**Steps to reproduce the issue**

**Comment by JoshStrobl** [comment]
This is because we use GNOME Control Center and its Notifications section are specific to GNOME Shell, not Budgie. This isn't going to be resolved under Budgie 11.
