### ISSUE TITLE
Feature Request: simple lockscreen

### ISSUE THREAD

**Issue by rilian-la-te** [solus-project/budgie-desktop#93]
For now I can use light-locker for lock screen, but cannot set keybinding for it (setting keybinding in gnome-settings-daemon won`t work).
It is possible to add some form of lock screen or lock screen keybinding to budgie-wm?

**Comment by ikeydoherty** [comment]
I'll add an option in the end session dialog.

**Comment by ikeydoherty** [comment]
Closing as we dont do lockscreens, thats up to your DM - but I'll add the option to activate one from budgie..
