### ISSUE TITLE
Side panel doesn't close if you switch workspaces

### ISSUE THREAD

**Issue by benwaffle** [solus-project/budgie-desktop#937]
**Operating System**: Solus
**Budgie version**: Budgie 10.3.1

Side panel doesn't close if you switch workspaces:

1. Open side panel
2. Switch workspace using workspace switcher in panel
3. Click outside of panel - the panel should close but it doesn't

**Comment by michaeltintiuc** [comment]
I actually like this behaviour, perhaps needs a setting.

**Comment by benwaffle** [comment]
But it's a bug - the panel cannot be closed

**Comment by MggMuggins** [comment]
It's only a bug if someone didn't intend for it to happen.

**Comment by michaeltintiuc** [comment]
@benwaffle I seem to be able to close it when switching workspaces, by hitting super + A or clicking the icons. To be clear, it stays open when switching, but it can be closed after.

**Comment by orschiro** [comment]
Maybe related: https://github.com/budgie-desktop/budgie-desktop/issues/998
