### ISSUE TITLE
Feature: alt+tab to work across workspaces

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#943]
Currently alt+tab cycles through applications on a per workspace basis. This is probably a design decision, but it would be grand to have the option to configure it to work across applications open in all workspaces.

**Comment by vanitasvitae** [comment]
A configuration option for this would be great indeed :)

**Comment by LeonidasJP** [comment]
https://github.com/budgie-desktop/budgie-desktop/issues/282 seems related; have Super + Tab cycle through all screens on all workspaces, where Alt + Tab would limit itself to the current workspace.

**Comment by vinzv** [comment]
I'd love to have the Alt+Tab/Super+Tab Separation. Any chances that it's coming some time?

**Comment by maxmbed** [comment]
I support this idea too.

**Comment by JoshStrobl** [comment]
Was resolved via 38e5befd32aedc23f3ceab295525b156cb215214
