### ISSUE TITLE
Question/Suggestion: Can budgie learn something from previous design work for other DEs?

### ISSUE THREAD

**Issue by owais** [solus-project/budgie-desktop#947]
Some teams have come up with some really interesting designs for desktop shells in the past. Some have been implemented and some were not realized. I was wondering if Budgie would be open to adopting some of those ideas and evolving them further to create a modern and innovative desktop environment. For example, here is some of the design work that https://www.reddit.com/r/Ubuntu/comments/6783xi/browsing_through_dconfeditor_and_found_out_that/dgowgz7/

Would be nice to see something like Unity's (planned but never realized) spread, HUD, app indicators, etc.

**Comment by ikeydoherty** [comment]
TL;DR What you're really asking is for Budgie to provide Unity's successor.

I've said before I dislike (strongly) the HUD so I don't want that in Budgie. I'll support modern indicators in future but not the legacy Unity specific indicators.

**Comment by owais** [comment]
Not really. I'm just asking if Budgie has by design goals in mind regarding
things like window management, workspace management, indicators, menus. The
reason I shared unity's documents is that it was the only DE that proposed
new, somewhat breaking designs for Linux like the spread. Budgie can look
anywhere for design inspiration. Like the notification panel is budget is
awesome and it is very much like OS X. Nothing wrong with that. It is a
good feature to have.

> I'll support modern indicators in future but not the legacy Unity
specific indicators.

Sounds great. Is there any design spec, blog post or wiki document I can
read about budgie's plan with indicators ?

**Comment by owais** [comment]
To be honest, I'm very curious and hopeful about where Budgie is going. It's the only open source desktop that looks promising to me right now. So what I'm really after is to read all design material budgie authors might have written. Most of what I found so was default theming and the sidebar which looks very promising but I'm curious as to what the vision is with window management, workspaces, integration between shell and apps (panel, launcher/dock, etc).

**Comment by ikeydoherty** [comment]
So for Budgie 11 during the initial creation we're going to allow some .. creative freedom. Much like you we think Budgie has potential, but that Budgie 10 is basically boring at this point. So we will be trying new things during the early life of 11, and undoing some of the design limitations of Budgie 10.
What it really means is effectively a new codebase

**Comment by Vistaus** [comment]
Lolwut? The spread is something new? I've used the spread in Enlightenment before Unity came around. So no, Unity wasn't the first on Linux to have the spread.

**Comment by owais** [comment]
Ok, unity was the last. Enlightenment was the first. Who cares? This is about the design direction of budgie, not a thread to decide who was the first ever to do X.

**Comment by JaneSmith** [comment]
How can you dislike the HUD? It's been a long time killer feature of Unity giving great productivity gains, and only now are other DEs just starting to implement it, e.g. MATE in the 17.10 beta: https://ubuntu-mate.org/blog/ubuntu-mate-artful-beta1/

I suspect you don't actually know what the HUD is. HUD doesn't refer to the big pop-up search thing that lets you search for programs or files, but rather to the ability to search through the standard application menu of the currently running program. For example, it lets you search "blu" to find "gaussian blur" entries in Gimp's main menu, etc.

This image explains it clearly: https://ubuntu-mate.org/gallery/layouts/mate-hud-local.gif

**Comment by JaneSmith** [comment]
Any update on this? What's wrong with the HUD? I still feel like there's been a misunderstanding about what the HUD is.

**Comment by JoshStrobl** [comment]
Closing this issue since Budgie 11 isn't going to be developed in this repository and will use a different issue tracker. I'm not opposed to having a HUD in Budgie 11, I actually quite liked using plotinus under GNOME Shell as an example and would like to carry that over, after all Budgie is focused on the desktop and should have more keyboard-driven functionality in the future.

So consider this approved but closing due to the nature of it being out-of-scope for Budgie 10 and my remarks about repo / issue tracker above.
