### ISSUE TITLE
Link to budgie-desktop.org in README

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#968]
Deleting template. Sorry. I don't see a link to the website. :)

**Comment by ikeydoherty** [comment]
@tristan957 BUT HOW DO I REPRODUCE THIS? ON WHAT OS?

>_>

Yeah we should probably link the website.

**Comment by tristan957** [comment]
Reproduce by using `wget` then `grep`ping for `budgie-desktop.org`. Bug on Windows 10, current build. :^)
