### ISSUE TITLE
Inconsistent behavior: Nautilus doesn't switch focus when clicking the desktop icon

### ISSUE THREAD

**Issue by merement** [solus-project/budgie-desktop#976]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1

**The issue encountered**
When Nautilus is open in a directory, for which there's a link on the desktop (also Home and Trash), clicking the icon on the desktop doesn't bring the Nautilus window up (when minimized) or doesn't switch the focus (when unfocused). This only leads to highlighting the icons on the top panel (windows list?) and the respective Plank icon jumps (don't know if this is relevant).

With switching focus it's more complicated because I can swear that sometimes it does switch the focus but I cannot reliably reproduce it.

Why it's inconsistency. All other applications (for instance, pdf files or links to them in the Desktop directory) do bring up/switch the focus to their windows. I understand that internally these are different things but, I believe, from the user interface point of view the behavior ought to be the same.

Is this a Nautilus issue. I don't have a computer with Gnome available but when I did I used desktop icons quite intensively, so I'm 99 percent sure that this wasn't its behavior there. Of course, clicking a desktop icon could open a new instance, unfortunately I don't remember details.

**Steps to reproduce the issue**

1. Make Desktop to show icons.
2. Make a link to any directory in ~/Desktop (if Home or/and Trash are on the desktop, this step is not necessary)
3. Click on the created desktop icon (or Home/Trash), minimize the window that opens, click the same desktop icon again.

(I hope it's not too much of a novel for a minor issue. Thank you, guys, for the great job on Budgie!)

**Comment by ikeydoherty** [comment]
I still don't understand the actual problem. Do note that Nautilus and Plank are not parts of Budgie though. (Plank is only used by default in Ubuntu Budgie)

**Comment by fossfreedom** [comment]
as an aside @ikeydoherty plank is likely to disappear from 17.10 in favour of  "budgie-dock" assuming I can figure out the appropriate panel.ini and other overrides.

**Comment by ikeydoherty** [comment]
Yeah we're basically going to supplant the need for panel.ini by providing a more extensive layout system, and provide a graphical mechanism to switch between them. I need to expose more properties in the format so we can really refine the layouts. Internally we have support from loading the default according to a GSettings key, it just needs fleshing out.

As part of the upstream provided layouts we intend to have Cupertino and Redmond covered, with the Cupertino one being something like the one from the G+ video. The Raven settings UI is becoming a major limiter right now so my weekend focus is ripping settings out into a new app UI, and demoting Raven to an action center (hopefully with proper applet API)

**Comment by ikeydoherty** [comment]
i.e. git is moving too fast right now to definitively say which way works and which doesn't, but we'll preserve the classic Budgie look as the default. Solus will not be using the classic look in our next release, so as a heads up we're very likely going to be using Adapta + Papirus Dark by default, with built-in theming turned off. I haven't quite nailed the default look but I don't know whether we'll enable dock by default.

**Comment by merement** [comment]
The problem is that clicking a desktop icon does not open a window, if that window is minimized. This greatly reduces the value of the desktop for keeping folders or links to folders. I understand that Nautilus is not a part of the Budgie but Nautilus comes by default with Solus Budgie. Plank was installed, in part to remedy the problem with the desktop icons.

**Comment by ikeydoherty** [comment]
I still don't see a problem. If you're double clicking something thats already open, then it would flash the attention hint in the panel, right? This sounds more like an upstream Nautilus issue, where instead you want it to request focus, not attention.

**Comment by merement** [comment]
For instance, if I have a pdf-file on the desktop opened and minimized, clicking the icon on the desktop will bring up that window. If I have, say, a text file, opened and minimized, clicking the desktop icon will open a new instance of gedit with the same file. If there's a doc file, opened (in my case, in WPS Writer) and minimized, clicking the icon will bring up the minimized window. So far, it's only Nautilus that behaves differently. Hence, not a bug but rather inconsistency.  In Gnome, Nautilus, I think, opens a new instance, or may bring up the minimized window (I'm not sure and for at least one more day I won't be able to get to a Gnome distro). In any case, it brings up the window with the directory of interest.

**Comment by ikeydoherty** [comment]
This isn't an inconsistency in Nautilus. If you click the special links, the window will request focus, because it's part of the same Nautilus process. The `.desktop` launchers are specific to each application, so each application will handle it differently. If the application is a unique instance application, then it will typically activate the primary window, depending on the application. For Nautilus, the special link is within the same app, so it only requests attention.

For gedit, you're activating the app with a command line + URL, which is why that opens a new doc. If you had two shortcuts to gedit itself, you'll find that it activates the same instance.

**Comment by merement** [comment]
Yes, I understand that internals are different but, for instance, in Gnome, behaviour at the user level is the same (clicked icon brings the object up). And I do understand that Budgie is not Gnome, so the same behaviour cannot be expected. Is there, at least, some tweak in settings, so that clicking desktop icons would open new window? Somehow, it is implemented in panel's icons: I can choose in the local menu "New Window" (it doesn't work for desktop icons).

**Comment by jrnart** [comment]
I second this, clicking Nautilus icon on Budgie panel doesn't bring the window up when it's minimized. Only alt+tabbing seems to work.

**Comment by Volneilo** [comment]
Probably **jrnart** and I aren't doing it right by commenting a thread 1 year old, but...

Same thing is happening here. Once Nautilus is minimized, clicking the launcher on panel doesn't bring the window up. This happens only with Nautilus, other apps behave normally.

And I found this: once I disable "show icons in desktop", within Budgie settings, the problem goes away!

**Comment by Briffou** [comment]
@Volneilo thanks for pointing out that when "show icons in desktop" is disabled, the problem goes away. I have the same problem and made the same observations as @Volneilo . For instance, if I minimize nautilus, click anywhere on desktop, and try to bring back nautilus through nautilus icon in panel, it doesn't work (no other windows open).

**Comment by JoshStrobl** [comment]
Closing since Budgie now has its own desktop icons implementation.
