### ISSUE TITLE
Battery applet does not update

### ISSUE THREAD

**Issue by Unia** [solus-project/budgie-desktop#98]
Hey,

I just compiled and installed Budgie desktop from git yesterday (Arch Linux, via the AUR) and today I noticed the battery applet does not update at all. It does not even change between discharging and charging. I skimmed through the code and noticed you are using UPower, so I wonder if this is an issue on their end, on Budgie's end or on my laptop's end (Lenovo ThinkPad Edge E130).

In any case, I thought I'd drop in here first and see if you're aware of this issue (if it is one at all) before I go off and investigate.

Thanks!

**Comment by craigerrington** [comment]
Just writing to confirm the same behaviour on Evolve OS - Beta 1 fully up-to-date

No refresh at all. Killing the PID for budgie-panel and having it relaunch updates the icon.

**Comment by Unia** [comment]
I have taken the latest C version of Budgie panel including its applets as a base for a panel of my own. Naturally some things required updating, including the power applet.

It was indeed an API change in UPower as you thought and I have it working in my power applet. I wanted to update your applet as it was me who opened this issue, but you're using an old vapi file which I don't know how to update (and have no time to look into). So, to meet in the middle, here's what I have as a cheat sheet for you: https://gist.github.com/Unia/1431d7f439b651c26e97

**Comment by ikeydoherty** [comment]
Wait you're creating a Budgie-deriv too.. ?

**Comment by Unia** [comment]
Too? There are others? :stuck_out_tongue: 

I'm not trying to recreate the Budgie desktop environment, that would be a waste of effort :) I prefer using a tiling window manager, but I'm also a sucker for some eye candy so I'm building an environment that has both. I only took the old Budgie Panel as a base for the panel, which will be way less configurable (something DWM-like, but with applets instead of the statusbar that reads from the root window)

By the way, the battery applet I linked to does not detect the battery when it is started with the battery plugged in (it needs a device-added signal to do this). I'm working on fixing this.

Maybe I have some spare time this weekend, in which case I can figure out how to make a new UPower vapi thing thingy. However, how would we go about picking which vapi to use?

**Comment by Unia** [comment]
The gist I linked to has been updated. It's ugly with all the ifdefs, but it works at least for the new UPower.

**Comment by FallingSnow** [comment]
Got 2 images of it just so you can see exactly what we are seeing. I looked a little through the code and idk if this has anything to do with it but in upower it says state charging/discharging and https://github.com/evolve-os/budgie-desktop/blob/831ca95291c0cc6d799ff41f4449f9a3172b00d8/panel/applets/status/PowerIndicator.vala#L89 uses a number.
![charging](https://cloud.githubusercontent.com/assets/2512197/6642942/d0e39b36-c965-11e4-9c7f-4e83b51faa01.png)
![onbattery](https://cloud.githubusercontent.com/assets/2512197/6642941/d0e150ec-c965-11e4-883f-5344631939aa.png)

**Comment by ikeydoherty** [comment]
Resolved
