### ISSUE TITLE
graphical glitches when "stylize regions" is on

### ISSUE THREAD

**Issue by RoundDuckKira-deprecated** [solus-project/budgie-desktop#997]
**Operating System**: Solus in its newest version
**Budgie version**: Budgie 10.3.1

**The issue encountered**

Sometimes there's strange graphical glitches where the dark area is bigger than normal, or there's a line through an area where it isn't supposed to be at.

 ...

**Steps to reproduce the issue**

It randomly happens, but try either slapping in the workspace applet, and keep "stylize regions" on, or not even have that, though occurrence is more rare. I guess it generally happens when indicators are appearing and disappearing overtime, especially with apps like Itch, Steam, and SimpleScreenRecorder. Might be more likely to happen in general if programs like Dropbox or ckb-next start in the background. Sadly I can't go and give a general list of steps, as it is a bit random, and instead, I gave an idea on how to increase the likelihood of triggering the bug. 

 ...

**workarounds**

So far, the only workaround is to turn off "stylize regions," which isn't much of a loss to begin with.

**Comment by orschiro** [comment]
I would like to try to reproduce your bug. What are "stylize regions" and where can I find them?

**Comment by gazny** [comment]
They are areas like spacers,dividers, and edges of a panel. These are more noticeable for me with a transparency/hide setting on a panel enabled.

**Comment by EvilRoda** [comment]
I have been having the same issue. Here's a recording.

**Comment by fossfreedom** [comment]
same issue as this? https://github.com/budgie-desktop/budgie-desktop/issues/1064

**Comment by EvilRoda** [comment]
It does appear to be the exact same issue.
